### ISSUE TITLE
Support empty value in md-datepicker and make easy way to change year

### ISSUE THREAD

**Issue by ManiAkasapu** [angular/material#4708] opened 2015-09-18 13:00 UTC
Please support "null" in md-datepicker. i.e If date field is empty show message "No Date selected".
Provide easy way to jump the month and year.

**Comment by jsdev** [comment] 2015-09-18 15:25
@ManiAkasapu it's open source submit a pull request

**Comment by jelbourn** [comment] 2015-09-22 22:14
Dupe of #4643

**Closed by jelbourn** 2015-09-22 22:14 UTC
