### ISSUE TITLE
select: label style/position is wrong on iOS after other md-select selection occurs

### ISSUE THREAD

**Issue by rantiev** [angular/material#11345] opened 2018-06-27 11:37 UTC
## Type:
Bug

# CodePen and steps to reproduce the issue:
#### CodePen Demo which demonstrates the issue: 
http://output.jsbin.com/sabobu

#### Detailed Reproduction Steps: 

1) Tap to first input, don't select any options 
2) Tap to next

### What is the expected behavior?
Color and position of label reverted to initial state

### What is the current behavior?
The first is still focused: lable position not updated, color not reverted to gray

### Which versions of AngularJS, Material, OS, and browsers are affected?

- AngularJS: 1.6.8
- AngularJS Material: 1.1.9
- OS: iOs
- Browsers: Mobile safari

**Comment by Splaktar** [comment] 2018-07-04 20:35
I am able to reproduce this on iOS 11.4. It seems like the `blur` events aren't being triggered or handled properly.

It looks like the newer versions of iOS introduce some non-standard way of interacting with select elements:
![simulator screen shot - iphone x - 2018-07-04 at 16 26 52](https://user-images.githubusercontent.com/3506071/42293329-6686f322-7fa7-11e8-8d3d-4c5805e48b2e.png)
This can be seen with the following [CodePen](https://codepen.io/Splaktar/pen/NzVrXO?editors=1010).

I don't have the ability to run older versions of iOS to determine when this behavior was changed.

I migrated this jsbin to [CodePen](https://codepen.io/Splaktar/pen/LroZWZ?editors=1010) so that I could change it.

As far as I can tell, this is a bug in iOS Safari. If anyone can investigate and provide details on how AngularJS Material can mitigate this iOS bug, please let me know.

**Comment by Splaktar** [comment] 2018-07-04 20:45
It looks like that new select UI is on the iPhone X, but not the iPhone 5s:
![simulator screen shot - iphone 5s - 2018-07-04 at 16 43 48](https://user-images.githubusercontent.com/3506071/42293607-8a01ab38-7fa9-11e8-8fe3-370e30c8ba73.png)

This issue does not occur on macOS Safari (11.1.1 (13605.2.8)).

**Comment by Splaktar** [comment] 2018-07-04 20:59
It looks like the `class="md-input-focused"` isn't being removed from the `md-input-container` when the `blur` event is fired.

The logic related to this can be found here:
https://github.com/angular/material/blob/master/src/components/select/select.js#L400-L422

It's unclear to me what these comments about `$touched` mean or why these extra checks are here for select as compared to input:
https://github.com/angular/material/blob/master/src/components/input/input.js#L386-L399

**Comment by pavelsl** [comment] 2018-07-20 15:36
Wow, i'm very impressed seeing one had reproduced issue i'm talking about. God bless you. I thought you are not exist. Hope in the new version we see less issues not more and this one.

Looking to https://material.angularjs.org/latest/demo/select on my iPad mini iOs 11 i can say that dropdown position never updated after scrolling. Not sure whether you want it like this.

**Comment by pavelsl** [comment] 2019-01-28 08:49
Let's just migrate to new angular and improve new material lib (it's doc and components issues) instead )

**Comment by Splaktar** [comment] 2019-06-06 03:18
I'll re-evaluate this once PR https://github.com/angular/material/pull/11625 gets merged.

**Comment by Splaktar** [comment] 2019-06-06 04:41
I've posted PR https://github.com/angular/material/pull/11739 to solve this.

**Closed** 2019-08-12 21:55 UTC
Labels: P3: important, for: internal contributor, g3: sync, has: Pull Request, os: iOS, type: bug
