### ISSUE TITLE
Warning in Angular Code... Please help me

### ISSUE THREAD

**Issue by jainshravan123** [angular/material#8133] opened 2016-04-20 12:44 UTC
attempted to use unregistered theme 'input'.

This warning is appearing after opening a new page by using $state.go('/some').
Please help me to get out of this.

<img width="1440" alt="screen shot 2016-04-20 at 6 11 59 pm" src="https://cloud.githubusercontent.com/assets/6860473/14674860/a9ddf66a-0723-11e6-955e-347ab62a4829.png">

**Comment by ThomasBurleson** [comment] 2016-04-20 13:36
Closing this issue due to insufficient information. Please resubmit with:

----
Required
----

**Behavior**:
-  What is the issue? * 
-  What is the expected behavior? 

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue :
-  Details: 

**Angular Versions**: *
-  Angular Version: 
-  Angular Material Version: 

**Additional Information**:
-  Browser Type: *
-  Browser Version: *
-  OS: *
-  Stack Traces: 

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

**Closed by ThomasBurleson** 2016-04-20 13:36 UTC

**Comment by jainshravan123** [comment] 2016-04-20 14:17
I am using $mdThemingProvider for theme. I have injected this dependency ($mdThemingProvider) in each of the controller. When i am opening first page, it is working fine but when i am making it redirected to dashboard using ($state.go('/dashboard')) service , it is showing warning which i have posted.  
` function theme($mdThemingProvider)
     {
        $mdThemingProvider.theme('default')
         .primaryPalette('brown')
         .accentPalette('red');
     };`
