### ISSUE TITLE
Wobbles when swiping/scrolling some content on iOS, starting from a button with md-raised

### ISSUE THREAD

**Issue by cadilhac** [angular/material#7696] opened 2016-03-22 14:24 UTC
I have a long page with a md-button inside. I tested this on iOS (9.1) on an ipod, with AM 1.0.6 and Master.
When I scroll the page, it is very smooth. But if I start swiping by first putting the finger on the button and giving an acceleration, the content scrolls but it does so with a lot of wobbles. If I remove the md-raised class, it fixes the issue.

I can not reproduce this in a codepen where the pane is very small on a mobile device. In this context, clicking on the button only shows the ripple after a delay (the famous 300ms I imagine ?) so the swipe behavior is not the same. Inside my own app, there is no such delay and the scroll starts right away, but with these nasty wobbles.

**Comment by topherfangio** [comment] 2016-03-23 20:59
@crisbeto Can you take a look at this and see if you can reproduce this?

One way might be to add a raised button to one of the really long layout guides in the docs, but I'm not sure if that will work.

**Comment by crisbeto** [comment] 2016-03-24 14:19
I didn't manage to reproduce in on my iPhone, but I think I did on my iPad (which is strange considering that both devices are on iOS 9.3). It behaves as if it scrolls up for a split second before it continues scrolling down normally. I had something similar happen at work because of a sticky navbar that received `transform: translateZ(0)' only when it was sticky. Here's my testing setup:


```html
a bit of lipsum goes here
  <md-button class="md-raised">Button</md-button>
a lot more lipsum goes here
```

**Comment by cjardmore** [comment] 2016-04-21 17:08
I was experiencing a similar problem with a cordova app when run on an ipad.  The app implements swipeleft and swiperight events.  When swiping left or right it was very sensitive to even the tiniest slope in the swipe motion.  Upgrading to ios 9.3.1 seems to have stabilized this for me.

**Comment by ThomasBurleson** [comment] 2016-06-01 23:58
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Closed** 2016-06-02 01:55 UTC
Labels: needs: investigation

**Comment by ThomasBurleson** [comment] 2016-06-02 07:05
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.

**Comment by cjardmore** [comment] 2016-06-02 13:12
I see that the issue is closed, but just in case anyone who is still following this thread is interested, I ended up bypassing the md-swipe-left|right directives and went with a custom solution dealing directly with touchstart, touchmove, and touchend events.  Feels almost native, and no wobble issues anymore.
