### ISSUE TITLE
md-button remains in hover state after click, on Chrome

### ISSUE THREAD

**Issue by EvilClosetMonkey** [angular/material#1263] opened 2015-01-22 17:39 UTC
After clicking an md-button and moving the mouse cursor away the button remains in the "hover" state, when using Chrome on Mac. This does not happen when using Safari or Firefox.

**Comment by marcysutton** [comment] 2015-01-22 18:45
I think it's actually the focus state you're seeing. The button is still focused at that point, which you can tell if you hit the tab key. Until we discern hover from focus on buttons, this will continue to be the case. Unfortunately, this behavior is a nightmare to fix cross-browser.

Closing as duplicate of a resolved issue: https://github.com/angular/material/issues/556

**Closed by marcysutton** 2015-01-22 18:45 UTC
