### ISSUE TITLE
FAB Speed Dial shows action buttons when ng-hide=true

### ISSUE THREAD

**Issue by doobix** [angular/material#6331] opened 2015-12-16 01:44 UTC
When ng-hide is true for md-fab-speed-dial, the red FAB button goes away, however the white button(s) are visible. This only happens when class is md-fling, no problems with md-scale. Angular material v1.0.0.

![screen shot 2015-12-15 at 5 41 49 pm](https://cloud.githubusercontent.com/assets/7928977/11829691/4741effe-a353-11e5-9a72-b0f3e166309e.png)

**Comment by topherfangio** [comment] 2015-12-16 18:29
Can you please provide a demo that reproduces this? Just using the default demo and adding `ng-hide="true"` to the speed dial, I can't seem to recreate it.

**Comment by doobix** [comment] 2015-12-16 19:23
The  `<md-fab-speed-dial>` needs to have class `md-fling` to see the bug, class `md-scale` has no problems.

Here's an edited pen of the speed dial demo:
http://codepen.io/anon/pen/Nxxoyx

The white action circle on the right side shows up when `self.hidden=true`.

**Comment by topherfangio** [comment] 2015-12-16 20:35
Thanks for the demo. There's actually two issues here:

1. The demo has some special CSS that hides the fab trigger, but is causing issues with the action items. If you remove this special CSS, the buttons are properly hidden.
2. However, this introduces another issue which is that if the speed dial is initially hidden, the animations are never firing which causes it to not open/close properly. This is described here: https://github.com/angular/material/issues/6111#issuecomment-165197124

I honestly haven't found a quick fix for this, so I will need to continue to investigate.

**Comment by topherfangio** [comment] 2016-01-21 18:25
**Dev Note:** Should consider watching for `$md-resize` broadcast.

**Comment by zanemcca** [comment] 2016-04-11 21:17
I have a similar issue except it is due to my trigger button having a clear background. So in the image below the plus icon is the trigger button and as you can see all of the action buttons are visible behind it. 

![screen shot 2016-04-11 at 5 14 45 pm](https://cloud.githubusercontent.com/assets/3848969/14442660/fce3fbd8-0008-11e6-9ef9-2610241f8367.png)

This is a regression as it was working fine for me in v0.11.4.

**Comment by ThomasBurleson** [comment] 2016-04-28 19:46
This issue is closed as part of our deprecation effort.
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).

**Closed by ThomasBurleson** 2016-04-28 19:46 UTC
Labels: needs: investigation, P4 - Reported By or General PRs/Errors or Edge Cases, type: bug
