### ISSUE TITLE
md-text-float overflows when on same line on mobile

### ISSUE THREAD

**Issue by rohitdatta** [angular/material#1075] opened 2014-12-30 23:32 UTC
When viewing a site that has 2 md-text-float fields on the same row, the text fields will collide into each other. This happens both in the iOS simulator and on an iOS device but this screenshots are from the simulator. Second photo shows what happens if users enters too much text.

![Screenshot of Angular MaterialJS on iOS Simulator](https://cloud.githubusercontent.com/assets/6260066/5584081/83cf597c-9051-11e4-93b5-e3151fcfb82b.png)

![Screenshot showing collision](https://cloud.githubusercontent.com/assets/6260066/5584106/fd891e38-9051-11e4-9b61-84436b897b27.png)

**Comment by mckenzielong** [comment] 2015-01-08 00:16
Not sure if this is useful, but the cause seems like row class is missing a flex-wrap:wrap;

Looking at other doc demos, they make use of layout and layout-sm attributes, however this demo page uses a 'row' class defined in the css and forgoes all layout attributes.

**Comment by ajoslin** [comment] 2015-01-08 00:43
Fixed via 60fcd6f4d8b895162b37a940c3f33164d8044382

**Closed by ajoslin** 2015-01-08 00:43 UTC
Labels: demo
