### ISSUE TITLE
Contact chips demo rendering bugs

### ISSUE THREAD

**Issue by cesarvarela** [angular/material#4145] opened 2015-08-13 17:52 UTC
![image](https://cloud.githubusercontent.com/assets/1172479/9257236/d477e8c8-41ca-11e5-8058-98e987789555.png)

2 bugs 1 screenshot

- the chips are empty
- the name and the picture are mixed in the autocomplete

**Comment by Frank3K** [comment] 2015-08-13 20:35
Which material version and which browser do you use? Seems to work fine on master / Chromium 43.

**Comment by ngraef** [comment] 2015-08-13 20:54
Duplicate of #3475

**Comment by cesarvarela** [comment] 2015-08-13 21:11
Chrome 45.0.2454.26 beta (64-bit)
and
https://material.angularjs.org/HEAD/#/demo/material.components.chips

**Comment by matthiasg** [comment] 2015-08-15 09:28
this bug is easily reproducable when using just keyboard navigation.

Works:
- enter a few letters, the drop-down opens up then clicking the element and it works correctly. 

Doesnt work:
- enter a few letters, the drop-down opens up then press keyboard down and press return on a desired item. 

PS: It would be extremely helpful if pressing `TAB` would select the top most or currently highlighted element from the drop down.

**Comment by topherfangio** [comment] 2015-08-15 17:09
We will definitely work on the bug and get it fixed.

Regarding your tab request, the tab key is used to navigate to the next
item that is keyboard accessible, whereas the enter key is used to select.
If we allowed tab to select, it would go against the accessibility
principles we are trying to ensure all of our components conform to, so I
don't think this is likely.

**Comment by ngraef** [comment] 2015-08-15 19:34
@cesarvarela Sorry, I missed the second part of the issue, where the images get mixed up. I don't think that's a duplicate.

The first part (empty chips when selected using <kbd>Enter</kbd>) is a duplicate of many issues (#3833, #3900, #4087) that have all been merged into #3475, even though that one doesn't describe the problem very well, IMO.

@matthiasg @topherfangio Tabbing to select related to #4058.

**Comment by topherfangio** [comment] 2015-08-15 19:56
@ngraef So, it's not really that we want the "tab to select" feature, it's that we want "select on autocomplete blur"?

**Comment by ngraef** [comment] 2015-08-15 20:46
@topherfangio Not necessarily. I think "select on blur" is bad UX, but the description of #4058 is all about "tab to select". Because contact chips are implemented using autocomplete, whatever happens with that issue will affect chips as well.

**Comment by thebigredgeek** [comment] 2015-09-02 07:38
Any update on this?

**Comment by topherfangio** [comment] 2015-09-03 21:37
There is still another issue with the contact chips that we are trying to resolve (dropdown items aren't rendering properly), but I do believe the issues in this ticket have been resolved in the latest master.

Is anyone still seeing this in master?

https://material.angularjs.org/HEAD/#/demo/material.components.chips

**Comment by cesarvarela** [comment] 2015-09-16 16:58
Yes, the issues seem to be fixed. Thanks!

**Comment by topherfangio** [comment] 2015-09-17 17:16
Thanks for the feedback!

**Closed by topherfangio** 2015-09-17 17:16 UTC
Labels: needs: feedback, needs: review
