### ISSUE TITLE
md-datepicker is not working as expected.

### ISSUE THREAD

**Issue by Nextt1** [angular/material#7723] opened 2016-03-24 08:30 UTC
`md-datepicker` is not giving the propear date when date is selected. 
check this pen http://codepen.io/next1/pen/LNyBgg

If I select 01/03/2016, it gives me output like 2016-02-29T18:30:00.000Z. Now I think because of my timezone is +5:30 it is giving me that result. But It is datepicker so why should it  concern about my time-zone? 
 It should give me the date I select. So how can I get the appropriate date ?

**Comment by DevVersion** [comment] 2016-03-24 13:01
Duplicate of #4636

**Closed by DevVersion** 2016-03-24 13:01 UTC

**Comment by rajathms** [comment] 2017-06-28 07:13
@DevVersion  the current issue #7723 might be Duplicate of #4636, But the issue is not fixed yet I feel .
Even I'm facing the same issue.
