### ISSUE TITLE
mdSelect and ngRequired don't show error with submit button

### ISSUE THREAD

**Issue by michelem09** [angular/material#7815] opened 2016-03-31 12:41 UTC
If you have a submit button and you try to submit a form with a `md-select` required it doesn't show the error.

http://plnkr.co/edit/iLYAHM55U1SRhxHNe7au?p=preview

**Comment by montgomery1944** [comment] 2016-03-31 16:42
Duplicate of https://github.com/angular/material/issues/7767.

**Closed** 2016-04-01 08:20 UTC
