### ISSUE TITLE
md-datepicker icon bleeds over open datepicker when in close proximity

### ISSUE THREAD

**Issue by TylersDesk** [angular/material#4658] opened 2015-09-16 02:52 UTC
I have two md-datepickers side by side.

When datepicker one is open the icon for the second datepicker bleeds over the date selection modal.

![md-datepicker-icon-index](https://cloud.githubusercontent.com/assets/5037139/9895334/9045fefc-5beb-11e5-9afa-2e7ab8418606.png)

**Comment by jelbourn** [comment] 2015-09-16 16:55
@TylersDesk  It would be great if you could provide a CodePen (or similar) demo of this issue.

**Comment by bluebirdtech** [comment] 2015-09-21 17:29
+1 I modified the styling to match eg. height of md-no-float input elements with md-icon within the md-input-container, and I'm seeing background through.

Expected behaviour: Opaque background behind the date text too.

**Comment by jelbourn** [comment] 2015-09-22 18:12
@TylersDesk I haven't been able to reproduce this. Can you provide a demo / reproduction?

**Comment by TylersDesk** [comment] 2015-09-22 18:16
Yes I will throw together a codepen together when I get a moment.

**Comment by jelbourn** [comment] 2015-10-26 19:07
@TylersDesk are you still seeing this problem?

**Comment by RichOren** [comment] 2015-10-29 00:50
@jelbourn - unable to reproduce as well.

**Comment by jelbourn** [comment] 2015-12-01 01:23
Closing this issue for now as non-reproducible.

**Closed by jelbourn** 2015-12-01 01:23 UTC
Labels: needs: demo, priority: medium
