### ISSUE TITLE
mdChips: default remove button doesn't follow Material Design spec

### ISSUE THREAD

**Issue by caseyjhol** [angular/material#11079] opened 2018-01-18 21:05 UTC
Expected appearance:
![chip_expected](https://user-images.githubusercontent.com/2874325/35121308-32282330-fc58-11e7-8c56-504dc6c7abe5.png)

See https://material.io/guidelines/components/chips.html.

* Should be using mdCancel instead of mdClose for the icon
* Opacity should be 54%

Current appearance:
![chip_actual](https://user-images.githubusercontent.com/2874325/35121318-39ae9666-fc58-11e7-9a79-946530dd61b1.png)

* `.md-chip-remove md-icon` has height and width set to 18px, which appears to be correct, but those are being overridden by `md-icon`'s min-height and min-width being set to 24px.

It's reasonably simple to change this to make it match spec; is there a reason it doesn't already? Would you be open to a pull request? I realize I can use a custom template to change the remove button, but I'd rather not have to do that for every instance of mdChips, especially since as far as I can tell, it shouldn't be implemented the way it currently is. I tried searching for any other mention of this, but came up short. Thoughts?

**Comment by Splaktar** [comment] 2018-01-21 09:02
Duplicate of https://github.com/angular/material/issues/9883. Please add your details and input to that issue.

I have investigated fixing this as well, but this would be a breaking change to the library as it could break people's apps. A PR would be welcome, but I don't know when it could be merged as we're still re-evaluating our minor release strategy.

**Closed by Splaktar** 2018-01-21 09:02 UTC
Labels: resolution: duplicate

**Comment by caseyjhol** [comment] 2018-01-22 15:22
Sorry - don't know how I missed that. I'll try submitting a PR, at least for others to use as reference, since it's only a few lines of code that need changing.
