### ISSUE TITLE
MdIconButton ink ripple flashes solid color

### ISSUE THREAD

**Issue by Roundaround** [angular/material#10132] opened 2016-12-14 01:51 UTC
**Actual Behavior**:
 -  `What is the issue? *`
MdIconButton ink ripple flashes solid color if the user clicks and holds for the full ink ripple duration
![](http://i.giphy.com/QGOzBO7lTYHf2.gif)
Tested on the most recent versions, but the bug has been around a good long while...

 -  `What is the expected behavior?`
No solid color - just goes back to transparent

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
http://codepen.io/anon/pen/BQqrYM
 -  `Details:`
From the official demos page, though easily reproducable in any environment

**Angular Versions**: *
 -  `Angular Version:`
Recent (>=1.5.0)
 -  `Angular Material Version:`
Recent (>=1.0.0)

**Additional Information**:
 -  `Browser Type: *`
Google Chrome
 -  `Browser Version: *`
Recent (~54)
 -  `OS: *`
Windows 10
 -  `Stack Traces:`
N/A

**Comment by clshortfuse** [comment] 2016-12-15 00:56
Thanks for the report. Some has already filed this issue.

Dupe of #10086

**Closed by clshortfuse** 2016-12-15 00:56 UTC
