### ISSUE TITLE
0.11.4 md-tabs label colours wrong

### ISSUE THREAD

**Issue by alphatwit** [angular/material#5208] opened 2015-10-16 15:23 UTC
The colours of the tabs seem to be overridden by the same colour scheme as md-warn

selected tab:
```
md-toolbar.md-warn > md-tabs.md-default-theme, md-tabs > md-tabs-wrapper > md-tabs-canvas > md-pagination-wrapper > md-tab-item:not([disabled]).md-active, md-toolbar.md-warn > md-tabs.md-default-theme, md-tabs > md-tabs-wrapper > md-tabs-canvas > md-pagination-wrapper > md-tab-item:not([disabled]).md-focused {
    color: rgb(255,255,255);
}
md-toolbar.md-accent > md-tabs.md-default-theme, md-tabs > md-tabs-wrapper > md-tabs-canvas > md-pagination-wrapper > md-tab-item:not([disabled]).md-active, md-toolbar.md-accent > md-tabs.md-default-theme, md-tabs > md-tabs-wrapper > md-tabs-canvas > md-pagination-wrapper > md-tab-item:not([disabled]).md-focused {
    color: rgba(255,255,255,0.87);
}
md-toolbar > md-tabs.md-default-theme, md-tabs > md-tabs-wrapper > md-tabs-canvas > md-pagination-wrapper > md-tab-item:not([disabled]).md-active, md-toolbar > md-tabs.md-default-theme, md-tabs > md-tabs-wrapper > md-tabs-canvas > md-pagination-wrapper > md-tab-item:not([disabled]).md-focused {
    color: rgba(255,255,255,0.87);
}
```
other tabs
```
md-toolbar.md-warn > md-tabs.md-default-theme, md-tabs > md-tabs-wrapper > md-tabs-canvas > md-pagination-wrapper > md-tab-item:not([disabled]) {
    color: rgb(255,205,210);
}
```

**Comment by chrislambe** [comment] 2015-10-16 16:05
I am also experiencing this. You can see it in effect in the Tabs demo:
https://material.angularjs.org/0.11.4/demo/tabs

**Comment by tsdragon0404** [comment] 2015-10-16 16:51
+1

**Comment by houmark** [comment] 2015-10-16 17:32
@alphatwit @chrislambe @tsdragon0404 This is fixed in HEAD, so the next release will be back to the old styling.

**Comment by salalaslam** [comment] 2015-10-17 07:02
+1

**Comment by Splaktar** [comment] 2015-10-17 19:01
Duplicate of #5155. Fixed in https://github.com/angular/material/commit/c9f822ddbbee4dc148e62b8007dce5fca1feb0aa.

**Closed by Splaktar** 2015-10-17 19:01 UTC
