### ISSUE TITLE
image inside md-card not showing in Safari (desktop and iOS)

### ISSUE THREAD

**Issue by MingyaoLiu** [angular/material#8612] opened 2016-06-01 16:40 UTC
ng-src/src is populated, but nothing is shown in the web app.
This happens for image inside md-card, if outside a md-card it is all fine.
The card demo on material.angular.org also didn't show the image in Safari/iOS.
I tried local image, blob from server, base64, nothing works. All these works in chrome, firefox, and edge
I'm looking for a temporary fix if anyone is experiencing the same issue...
Thanks.

EDIT : I just inspected in safari (just got osx in vmware), apparently md-card->img has a css attrribude "height: 100% !important", removing that solved the problem. Not sure why height 100% is needed, i tested on firefox,chrome,edge there is no difference.

**Comment by ThomasBurleson** [comment] 2016-06-02 02:28
Duplicate of #7692.

**Closed by ThomasBurleson** 2016-06-02 02:28 UTC

**Comment by yanndupuy** [comment] 2016-06-02 02:29
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (400/400 (100%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext1.iad.github.net ([192.30.252.192]:50081 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1b8INT-002Axg-JE
	for yann.dupuy@zyapps.com; Thu, 02 Jun 2016 04:29:04 +0200
Date: Wed, 01 Jun 2016 19:28:13 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1464834493;
	bh=TS9+riiKNm/1658Mnl2XqEal/CpwvopOOaQ4f0NbIwc=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=Th7PQFeQmA6vE+3dRdQZISCnFOOj2G0hsNmtrhMLLr+zHHUnuTIYR9m3/gVxlrTIm
	 2oZ9XRl0aMUGh0BL18Y6SkI9ciecK1OB6TLEYCWK75cz8Te4iSUAvRgGTXyc4XJfPo
	 +Re46houggCzsGKjEwwcEyT2jWVlXt1E+ix6yEXc=

**Comment by yanndupuy** [comment] 2016-06-02 02:29
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (401/400 (100%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o5.sgmail.github.com ([192.254.113.10]:32316)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.87)
	(envelope-from <bounces+848413-8f06-yann.dupuy=zyapps.com@sgmail.github.com>)
	id 1b8INV-002Axk-53
	for yann.dupuy@zyapps.com; Thu, 02 Jun 2016 04:29:13 +0200
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=rXdjQ1v1MbrVFOsG3Y1OeABVRdA=; b=ryoibyxBmkm44D8c
	wDjmrA6qJ4xcPv9PgbnJ0zFabuGMk8ZJEvMpBIbCgnfOtr5BfBVnOU/E5vqYWqmE
	2AQEZmA/EF6Kr+alFjoJI16M6gWJgEn+0H1QnKlyvDf04z1fJZQYLQfpe5AHdhpu
	wkKTTJEzpbGgrXtCa5E3StY6LhY=
Received: by filter0826p1mdw1.sendgrid.net with SMTP id filter0826p1mdw1.2675.574F99BCD
        2016-06-02 02:28:12.497197742 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0004p1iad1.sendgrid.net (SG) with ESMTP id t7Otl-iwQOO3wT-Y83t-9Q
	for <yann.dupuy@zyapps.com>; Thu, 02 Jun 2016 02:28:12.507 +0000 (UTC)
Date: Wed, 01 Jun 2016 19:28:12 -0700
