### ISSUE TITLE
Chips layout issues....

### ISSUE THREAD

**Issue by jyn** [angular/material#2110] opened 2015-04-01 03:32 UTC
https://material.angularjs.org/#/demo/material.components.chips

The layout under "default chip template" looks strange.

![google chromescreensnapz006](https://cloud.githubusercontent.com/assets/83088/6934143/dc38ad9e-d87b-11e4-8328-dd8484dc628d.jpg)

This is on chrome and safari on a mac.

**Comment by devdraweat** [comment] 2015-04-01 04:18
Duplicate of #2081

**Closed** 2015-04-01 18:12 UTC
