### ISSUE TITLE
tabs: Unable to see md-tab-item label fully in IE 11

### ISSUE THREAD

**Issue by SanjanKalsi** [angular/material#11212] opened 2018-04-06 10:17 UTC
In IE 11 to md-tab-item labels are wrapped which becomes evident when the tabs exceed their container.

Instead of overflowing horizontally inside the wrapper, their width is becoming fixed and uniform for all items at the same time.

This issue is present in the latest angularmaterial version as of now.

The issue can replicated by opening the link in IE 11:
[demo](https://material.angularjs.org/latest/demo/tabs) under the dynamic tabs example where 21 tabs are present.

**Comment by Splaktar** [comment] 2018-04-08 06:26
Thank you for taking the time to submit this issue. However it does not follow our **required** issue template. This gives the team the information needed to investigate the bug or prioritize the feature.

**Comment by Splaktar** [comment] 2018-04-08 06:28
This appears to be a duplicate of https://github.com/angular/material/issues/10406. Can you please confirm? A screenshot would be useful in issues like this as well.

**Comment by Splaktar** [comment] 2018-04-09 06:40
OK, thank you for confirming that!

**Closed by Splaktar** 2018-04-09 06:40 UTC
Labels: browser: IE, resolution: duplicate
