### ISSUE TITLE
Documentation error for material-card: some javascript is rendered in the use case

### ISSUE THREAD

**Issue by hubertlepicki** [angular/material#411] opened 2014-10-10 12:57 UTC
https://material.angularjs.org/#/material.components.card/directive/materialCard

has an error. I have no idea where this is coming from but some random JavaScript is rendered:

![screen](https://cloud.githubusercontent.com/assets/33274/4592543/e6125784-507c-11e4-8899-ae85e120c869.png)

**Comment by marcysutton** [comment] 2015-01-13 22:51
Closing as duplicate of https://github.com/angular/material/issues/1010.

**Closed by marcysutton** 2015-01-13 22:51 UTC
Labels: build, doc
