### ISSUE TITLE
md-chips with autocomplete and mdRequireMatch: pressing enter adds the value twice

### ISSUE THREAD

**Issue by Alesha25** [angular/material#5047] opened 2015-10-07 05:06 UTC
Hey, I am using 0.11.1 (checked on 0.11.2 as well ) version of angular material. 

I want to use both the auto complete values and a free text (mdRequireMatch = true), once a type the first letter and pick some option from auto complete (pressing 'Enter') two new chips are added

https://codepen.io/anon/pen/ojWPOw

Type 'ca', see the auto complete opened and pick 'Carrot' (by pressing Enter), two new chips ('ca' and 'Carrot') are added, however only 'Carrot' was chosen

**Comment by topherfangio** [comment] 2015-10-07 17:06
Duplicate of #4412. Please search before adding a new issue. If you believe this is different, please comment and I will reopen.

**Closed by topherfangio** 2015-10-07 17:06 UTC
