### ISSUE TITLE
mdAutocomplete: does not Autoselect correctly

### ISSUE THREAD

**Issue by hollsteinm** [angular/material#8863] opened 2016-06-27 13:58 UTC
**Actual behavior**:
-  What is the issue? *MDAutoComplete does not auto select values with only one character. This results in poor user experience as using enter to submit the form where the autocomplete is used, because the information that was desired was not submitted. Note, in version 1.0.5, in our application, it caused the whole browser to lock. Could not reproduce the locking in newer versions.
-  What is the expected behavior? MDAutoComplete autoselects on a match.

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue : http://codepen.io/anon/pen/zBZYOb
-  Details: Type the letter "A" and view the autocomplete drop-down. "A" is available as an option; however, it is not auto selected. This can be seen in the developer view console logs.

**Angular Versions**: *
-  Angular Version:1.5.5
-  Angular Material Version:v1.1.0-rc.5

**Additional Information**:
-  Browser Type: *Chrome, Firefox, and IE
-  Browser Version: *Chrome (51.0.2704.103 ), Firefox(47.0), IE(11.0.9600.18349)
-  OS: *Windows 7
-  Stack Traces: N/A

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by DevVersion** [comment] 2016-06-27 15:11
So I was looking at the source.

The `md-autcomplete` only `auto` selects, if there is only one possible match.

So since there are **many** matches, if you just enter `A`, the autocomplete will not detect that as an exact match. (See [ in source](https://github.com/angular/material/blob/master/src/components/autocomplete/js/autocompleteController.js#L840))

![image](https://cloud.githubusercontent.com/assets/4987015/16384630/f4f299a8-3c89-11e6-912c-b507b31918b4.png)

It's actually not a bug and it seems to work as expected in my opinion.

@hollsteinm I would be very happy to discuss about that.

Also I will talk to the Team today and try to re-validate the logic.

**Comment by hollsteinm** [comment] 2016-06-27 15:25
Hi, thank you for pointing that out to me. (Guess I didn't read it as closely as I thought). The only problem is that the use case involved selecting a range of numbers that were used as identification. The values were a range of one to three digit numbers. Of course these identifiers had to be filtered out so I could not just do a range, and thus were queried from the database. I think the biggest issue is that if the mdAutcomplete contained a value and 'Enter' was pressed to complete the action, mdAutocomplete would not submit the value in the text field.

**Comment by hollsteinm** [comment] 2016-06-27 15:29
Hi, I actually updated this behaviour in the code pen. Type in "A" and hit Enter. It will notify null, rather than the value in the field. http://codepen.io/anon/pen/zBZYOb. Would you like me to update the bug to reflect this issue or write a new one?

**Comment by DevVersion** [comment] 2016-06-27 15:43
Actually I don't think that's also an issue, since it's the browsers default behavior to submit the form on enter (when focus is on the input)

If you select your choice with the Arrow Keys and then press <kbd>Enter</kbd>, it select the value as expected.

**Comment by mckenzielong** [comment] 2016-06-27 16:05
@DevVersion Probably considered an enhancement, but what about the idea of autoselect on focus loss + match.  

Suppose we have directions: N, NW, NE.  Currently: user types N and tabs off the field -- no item is selected.  Folks who do data entry might appreciate a feature where we auto select when focus is lost if there is a match (saving 2+ keystrokes to filter down and press enter.)  -- user types N, tabs off -- N item is selected.

**Comment by DevVersion** [comment] 2016-06-27 16:11
@mckenzielong Can you file this as an extra issue, so I can discuss it with the team?

**Comment by DevVersion** [comment] 2016-06-27 16:12
Closing this issue for now, because it's actually not a bug, just some wrong understanding.

**Comment by hollsteinm** [comment] 2016-06-27 16:57
The only thing is, "A" is technically an exact match. So shouldn't the statement be "An exact match if it is the only option available".

**Comment by DevVersion** [comment] 2016-06-27 17:16
@hollsteinm Seems to be reasonable request to update the docs. Thanks.

**Closed** 2016-07-10 19:46 UTC
Labels: has: Pull Request, P3 - Docs / Demos / Internal Contrib
