### ISSUE TITLE
Sticky Elements Broken When Initially Hidden

### ISSUE THREAD

**Issue by Anaphase** [angular/material#4499] opened 2015-09-08 23:02 UTC
v0.11.0 introduced a breaking change in the way sticky elements are handled. When multiple sticky elements are in an initially hidden container, an odd bug can be produced.

Here are the steps to reproduce the bug ([illustrated in this CodePen](http://codepen.io/Anaphase/pen/vNOdrv)):

1. Have a hidden container with two or more md-subheader elements.
2. Show the element after that page loads.
3. Scroll the container far enough for the first header to become sticky, but not far enough for the second header to become sticky.
4. Scroll back up to the top.

Notice how the last header's sticky clone is still visible, giving the impression that the first header has become the last header!

After a lot of debugging, I determined that the root of the problem is the while loop on [line 146 of sticky.js](https://github.com/angular/material/blob/v0.11.0/src/components/sticky/sticky.js#L146). This loop is trying to read the `offsetTop`, `offsetLeft` and `offsetParent` of the current element. However, since the element is hidden, `offsetParent` is null ([as noted here](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/offsetParent)), thus making `offsetTop` and `offsetLeft` equal to 0.

Since all the elements will have an initial `top` of 0, the [sorting on line 117 of sticky.js](https://github.com/angular/material/blob/v0.11.0/src/components/sticky/sticky.js#L117) becomes essentially useless, always sorting the array of elements in reverse DOM order. This is ultimately why the last header in the list never has it's sticky clone hidden.

Note that if you are able to scroll past the last element and make it sticky, then this bug will not occur since, probably because the elements offsets get refreshed by that point - but I didn't look into that. Also note this bug cannot be reproduced in browsers that support `position: sticky` [since the scroll handlers aren't used in that case.](https://github.com/angular/material/blob/v0.11.0/src/components/sticky/sticky.js#L41)

**Comment by Anaphase** [comment] 2015-09-08 23:13
For some reason v0.10.1 doesn't have this issue, and I'm 90% sure it has to do with commit 8c921a6. Something to do with the logic changes in `onScroll` maybe.

**Comment by topherfangio** [comment] 2015-09-09 03:01
@Anaphase Definitely looks like the sorting is the issue. Didn't see how that worked when I refactored the code. We'll get this fixed.

**Comment by lievenjanssen** [comment] 2015-09-22 13:13
Since this is a high priority bug introduced in 0.11 shouldn't this be fixed in 0.11.1? It breaks our application.

**Comment by Anaphase** [comment] 2015-09-22 13:43
+1 for including in 0.11.1 - this is the only thing preventing me from upgrading from 0.10.1

**Comment by ThomasBurleson** [comment] 2015-09-22 17:15
@topherfangio - do you have time to investigate this today?

**Comment by topherfangio** [comment] 2015-09-22 19:25
@lievenjanssen @Anaphase I am investigating this today and I remember seeing the issue in the Codepen a few weeks ago when I made my first comment, but as of right now, I cannot reproduce the issue in the Codepen and I have tried 7 browsers across three different machines (2 mac, 1 win) and copied it onto my local machine to test there.

Is there any chance that one of you could help create another Codepen based against the latest that reproduces the issue? Here are some helpful links:

*  Angular Material HEAD
 *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.js
 *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.css 
 *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.js
 *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.css
* AngularJS  Current
 *  Angular 1.3.19 (or greater)
 *  Angular 1.4.6 (or greater).

Oddly, when I put a `console.log()` in the code to show the sorting, they all appear to have the proper top values (i.e. not all `0`) and it appears to properly call `refreshElements()` even though the element is hidden, and it calls it again when you start scrolling, so it all looks like it should be working.

If one of you can help produce a failing example, I will definitely look at it again today/tomorrow and try to get a fix pushed ASAP.

**Comment by Anaphase** [comment] 2015-09-22 20:03
Okay, I figured out why the CodePen demo suddenly failed. The CodePen was using [this CDN link](https://gitcdn.xyz/repo/angular/bower-material/v0.11.0/angular-material.js) for the Angular Material JS library, which is apparently the version at HEAD and not the 0.11.0 tag (somewhat counter-intuitive given the version tag in the URL... is this idiosyncrasy normal?) So, after 2 weeks the CodePen now has a version of Angular Material with new changes in it.

Commit d68b5e2 inadvertently fixed this bug by throttling the request animation frame call. I don't have the time at the moment to investigate *why* this change fixed the issue, but it has. I verified that d68b5e2 fixed the issue by [forking the CodePen](http://codepen.io/Anaphase/pen/YyWoMj) and including [a patched version of 0.11.0](https://dl.dropboxusercontent.com/u/3310824/angular-material/0.11.0-sticky-header-bug-patched.js) with only the changes in d68b5e2 applied. I suppose you can close this bug as a result of d68b5e2.

Note for posterity: I've updated the original CodePen to point to [the actual v0.11.0 Bower file](https://cdn.gitcdn.xyz/cdn/angular/bower-material/v0.11.0/angular-material.js) so that it actually demonstrates the original bug.

**Comment by topherfangio** [comment] 2015-09-22 21:16
I had a suspicion that something like this may be happening, so I manually removed the `$$rAF` throttling from my local code to see if it happened again, but for me, it didn't. Perhaps because I am using Angular v1.4.6 which has some animation/`$$rAF` fixes. Were you using v1.4.4 locally?

Anyway, thanks so much for the update! We'll go ahead and close this issue.

**Closed by topherfangio** 2015-09-22 21:16 UTC
Labels: priority: high

**Comment by ThomasBurleson** [comment] 2015-09-22 21:20
@Anaphase - The GitCDN problem is a known issue: https://github.com/angular/material/issues/4447

**Comment by Anaphase** [comment] 2015-09-23 00:02
@topherfangio, The CodePen examples were indeed using Angular 1.4.4, but even after upgrading them to 1.4.6 the bug is [still replicable](http://codepen.io/Anaphase/pen/vNOdrv), and indeed [still fixed](http://codepen.io/Anaphase/pen/YyWoMj) by the `$$rAF` patch.

**Comment by topherfangio** [comment] 2015-09-23 14:56
@Anaphase Thanks so much for the additional feedback. When I have some time, I'll try to dig in and figure out why the `$$rAF` throttling fixed it, but my guess is that "fixed" a timing issue. Thanks again!
