### ISSUE TITLE
md-nav-ink-bar does not refresh on window resize

### ISSUE THREAD

**Issue by miketricking** [angular/material#11013] opened 2017-12-11 16:31 UTC
**Actual Behavior**:
 -  `What is the issue? *` If you have a navbar aligned to the right, when resizing the window wider or narrower the ink bar does not update it's location so appears in the wrong place
 -  `What is the expected behavior?` ink bar updates when window is resized

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` https://codepen.io/miketricking/pen/QaLBoB
 -  `Details:` Click on 'home' then make then reduce the width of the screensize.

**AngularJS Versions**: *
 -  `AngularJS Version:` 1.5.5
 -  `AngularJS Material Version:` 1.1.0

**Additional Information**:
 -  `Browser Type: *` All versions
 -  `Browser Version: *` All versions
 -  `OS: *` All versions
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by Splaktar** [comment] 2017-12-13 06:38
Duplicate of https://github.com/angular/material/issues/10121.

**Closed by Splaktar** 2017-12-13 06:38 UTC
