### ISSUE TITLE
md-input-container: iOS 9.2 Safari bug - label stays visible when ng-model is reset (clear)

### ISSUE THREAD

**Issue by bonatoc** [angular/material#7347] opened 2016-02-29 22:54 UTC
Label does not get removed from the UI on iOS Safari.
**Upon ng-model reset**, label removal works as expected in Safari OS X El Capitan, Chrome, Firefox.

Latest Select demo shows the bug: from your iOS device/simulator [try the last example, "Validations"](https://material.angularjs.org/latest/demo/select).

![ios-screencap](https://cloud.githubusercontent.com/assets/956531/13413904/5e421288-df4e-11e5-824d-cc021541f7b0.jpg)

It looks like `md-input-has-value` and `md-input-focused` are not removed/toggled from `md-input-container` on Safari iOS. 

I suspect **toggleClass** in the `mdInputContainerDirective / ContainerCtrl`.

Maybe is it's JQlite, because in this codepen forked from the official demo, **if I import Jquery after** angular and AM, and if I fire toggleClass() on the `md-input-container`, it works : 

http://codepen.io/bonatoc/pen/VaYbXX

So maybe JQLite and JQuery ToggleClass do not work the same way under iOS Safari.

**Comment by bonatoc** [comment] 2016-03-01 00:32
I did a quick test. I suspect **toggleClass** in the `mdInputContainerDirective / ContainerCtrl`.

Maybe is it's JQlite, because in this codepen forked from the official demo, **if I import Jquery after** angular and AM, and if I fire toggleClass() on the `md-input-container`, it works : 

http://codepen.io/bonatoc/pen/VaYbXX

Again, iOS Safari only. 
Did not try through Ionic/Cordova yet.

**Comment by topherfangio** [comment] 2016-03-24 20:18
I believe this was fixed in a recent commit. I just tested against master and it seems to be working: http://codepen.io/topherfangio/pen/aNWrOb

If you can still reproduce after upgrading, please comment and we will reopen.

**Closed by topherfangio** 2016-03-24 20:18 UTC
