### ISSUE TITLE
md-tooltip on Firefox: probably performance issue for heavy layout

### ISSUE THREAD

**Issue by tniezurawski** [angular/material#6891] opened 2016-01-28 11:21 UTC
Hi guys,

I've prepared plunker to present this use case:
http://plnkr.co/edit/LhCNvdiA2BDI5BwA7DMR?p=preview

_Description from my plunker:_
Play with tooltips attached to actions buttons. They seems to work laggy, sometimes not showing at all, sometimes hiding unexpectedly.

It is probably a performance issue when we use ```layout="row"``` and/or ```layout="column" ``` somewhere on the top of HTML

I think it works a way better on IE10, IE11 and Chrome.

-- used versions:
Angular: 1.4.9
Angular-Material: 1.0.3

**Comment by ThomasBurleson** [comment] 2016-01-28 17:50
@EladBezalel - can you investigate/review?

**Comment by Nosthertus** [comment] 2016-01-30 05:46
In my case it does not seem to lag.. but it does persist the problem of not toggling sometimes, i think for the lag happens for machine perfomance.

PS: i have used your plunk link to check it out

**Comment by tniezurawski** [comment] 2016-01-30 08:07
Of course we could address this problem to something else than performance.
My assumption to call it "perf issue" was:

- tooltips works fine on Chrome and IE
- tooltips behave like it was described on Firefox - laggy, not toggling sometimes
- when we remove ```layout="row"``` and/or ```layout="column"``` from our HTML tooltip's animation works smooth and reported problems does not occur

**Comment by Anexxia** [comment] 2016-02-01 13:13
+1 Same thing happening with our app. Tooltips work great with Chrome, IE and Edge but laggy, toggling unexpectedly, not opening at all or staying open when using Firefox

**Comment by epelc** [comment] 2016-02-12 20:52
+1 we are having major issues with tooltips opening then instantly closing and not being able to reopen in firefox. Or they just plain don't open at all not even a flicker.

I just tested using the latest firefox on version `0.11.4` through `1.0.5`. I found that they worked in `0.11.3` although with fab speeddial there was an issue where the first time you open the speeddial all tooltips would show and the tooltips in general seemed a bit off due to the circle animations. But they worked perfectly in `0.11.2`.

**Comment by EladBezalel** [comment] 2016-02-12 23:07
After researching this, it seems to be the `display: flex` property on `<div layout="column" ...>`
The tooltip is being added to the body, and because this div `display` is `flex` my guess the Firefox browser is not handling the render well and the `position: absolute` of the tooltip is being harmed by that.
A quick workaround will be - move the `layout="column"` inside ..

**Comment by epelc** [comment] 2016-02-14 01:08
Thanks for the fix @EladBezalel 

I can confirm it works perfectly in 1.0.3 if you remove `layout="column"` from your `body` element.

**Comment by nissoh** [comment] 2016-02-17 21:45
@tniezurawski do you have layout attribute declared on your body?
guess what. firefox has extreme performance issue with display flex on the body tag.

i would recommend having a root container with absolute stretched with 0 in all directions.
let me know if this works for you.

**Comment by tniezurawski** [comment] 2016-02-18 09:16
@nissoh Yup. Everything is in plunkr example. @EladBezalel Confirmed flex perf. issue on FF.

I am not sure we can do something about it beside don't using flex on elements that are high in the hierarchy of the document (e.g. <body>). @ThomasBurleson Maybe we should close this issue?

**Comment by EladBezalel** [comment] 2016-02-18 21:35
@tniezurawski moved this issue to the backlog, 
this issue is not resolved yet, it will be good to track this when a newer releases of FF will come out.

**Comment by stephen-james** [comment] 2016-05-10 10:52
:+1: Thanks @EladBezalel, we had the same issue with `<body>` having `layout="column"`.  We had a heavy page and were noticing any elements with opacity < 1 flickering while showing tooltips (a side effect of FF repaints).  Removing layout from body solved the perf issue.

**Closed** 2016-06-02 01:55 UTC
Labels: browser: FireFox, P4 - Reported By or General PRs/Errors or Edge Cases, type: performance

**Comment by ThomasBurleson** [comment] 2016-06-02 07:09
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
