### ISSUE TITLE
Multiple $mdDialogs

### ISSUE THREAD

**Issue by 32teeths** [angular/material#8932] opened 2016-07-02 06:32 UTC
I wanted to show multiple $mdDialogs but the first dialog automatically closes when the second modal opens. I actually wanted to resolve the result of second modal to first modal . Is multiple dialogs supported  ? Or will it be added soon .

**Comment by DevVersion** [comment] 2016-07-02 07:51
This is a duplicate of #8630

**Closed by DevVersion** 2016-07-02 07:51 UTC
