### ISSUE TITLE
ngWig with angular-material

### ISSUE THREAD

**Issue by kpgarrod** [angular/material#8593] opened 2016-05-30 14:06 UTC
I would like to be able to use a simple wysiwig editor in my a-m project. ngWig is very lightweight, simple to implement in place of textareas and fits the requirement perfectly except for a couple of 'minor' issues:

**Actual behavior**:
-  What is the issue? *
This is a copy of the issue I posted in the ngWig repo [here](https://github.com/stevermeister/ngWig/issues/113) 
1. When I include ng-wig inside a form (with or without md-input-container) the editor does not become focused when tabbing through the form.

2. On a mobile device the keyboard does not appear when focusing on the editor.

-  What is the expected behavior?
 ngWig in a project containing angular-material should behave as it does without angular-material. Ideally ideally it should be possible to contain an ng-wig editor within an md-input-container  

**CodePen** or Steps to reproduce the issue: *
-  Here is a [codepen with ng-wig](http://codepen.io/kpgarrod/pen/BKVeZV) and the same [codepen with  a textarea](http://codepen.io/kpgarrod/pen/dMKEzv)

**Angular Versions**: *
-  Angular Version:
1.5.x
-  Angular Material Version:
1.1.0-rc4

**Additional Information**:
-  Browser Type: *
android /chrome on android
-  Browser Version: *
-  OS: *
android
-  Stack Traces:

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by DevVersion** [comment] 2016-05-30 15:55
Closing this as a duplicate of #8487

**Closed by DevVersion** 2016-05-30 15:55 UTC

**Comment by kpgarrod** [comment] 2016-05-31 06:33
This is hardly a duplicate of #8487.  Summernote depends on JQuery and twitter-bootstrap which I am trying to avoid. ngWig doesn't have those dependencies.  I agree that different projects will require different editors, but there should be some choices that work.

**Comment by stevermeister** [comment] 2016-05-31 07:55
@DevVersion it's not a duplicate, **it's exact issue for angular-material**.

## contenteditable field does not get the focus on mobile devices when you click on it. 
(But it works if you just remove angular-material module from your dependancies)

**Comment by myknbani** [comment] 2016-05-31 08:29
It is not a dupe of #8487 but rather of issue #5937.  There's also this PR  #5939

**Comment by stevermeister** [comment] 2016-05-31 08:34
@myknbani thank you for the link!

**Comment by DevVersion** [comment] 2016-05-31 11:40
@stevermeister Thanks for the clarification. The issue was not very clear at beginning (before its editing). It sounded more like a feature request, to include a RTE in the core. 

As @myknbani shared the link of a previous and more *generic* issue - I'll reopen #5937 (which was closed within our Spring Cleaning)
