### ISSUE TITLE
md-select in master has numerous issues

### ISSUE THREAD

**Issue by hodeyp** [angular/material#3055] opened 2015-05-31 17:59 UTC
the content no longer fills the container when inside a flex element
height/alignment when enclosed in `md-input-container` is wrong

0.9.6...

![screenshot](https://cloud.githubusercontent.com/assets/1916471/7903092/4b8a190e-07c9-11e5-9b14-c76a8a910991.png)

Master...

![screenshot](https://cloud.githubusercontent.com/assets/1916471/7903093/55fb614a-07c9-11e5-89f2-d4171610939f.png)

**Comment by ngraef** [comment] 2015-06-04 00:53
Caused by the change in fd26d1ac6c518f22936ec3be37f059cd3ed26fc4. This is also visible in the "Validations" demo for Select.

0.9.6:
![image](https://cloud.githubusercontent.com/assets/1031317/7974267/23f50f9e-0a25-11e5-9b6d-543dfe69fd6f.png)
0.9.7 & master:
![image](https://cloud.githubusercontent.com/assets/1031317/7974275/3c36e1a4-0a25-11e5-90a1-0f25bc15e263.png)

It seems the width issue is on `md-select-label`, not `md-select` itself.

@robertmesserle any input on this? The commit was titled "updates styles to more closely match md-input-container" -- is there a new way we should be working with `md-select` and `ng-messages` together without `md-input-container`?

**Comment by ferc** [comment] 2015-06-04 02:41
+1

I have the same issue with the last version

**Comment by JuanELo-O** [comment] 2015-06-04 15:54
+1

I thought I was the only one who had the problem

**Comment by IVisualDev** [comment] 2015-06-11 12:05
+1

**Comment by mikaelborg72** [comment] 2015-06-12 06:40
+1

**Comment by tirana** [comment] 2015-06-22 21:04
1. Also I found that md-select and the other input elements had different label color.
The main reason: md-select uses span instead of label. see here: https://github.com/angular/material/blob/master/src/components/select/select.js#L83

2. proposed css changes:
1. default padding is too big. it should be 
md-select {
  padding-top: 17px;
  padding-bottom: 0;
}

2. md-select-label should use 100% of given space.
md-select .md-select-label {
  width: 100%;
}

**Comment by ngraef** [comment] 2015-06-30 16:28
The width and ngMessages style issues appear to be fixed on master, probably by one of @rschmukler 's commits on 6/28. Can anyone else verify?

**Comment by rschmukler** [comment] 2015-07-12 18:22
Closing as most of the issues should be resolved in master. If not, please re-open separate issues for each problem.

**Closed by rschmukler** 2015-07-12 18:22 UTC
Labels: for: internal contributor
