### ISSUE TITLE
md-autocomplete with query in 1.0.5

### ISSUE THREAD

**Issue by Knoxvillekm** [angular/material#7036] opened 2016-02-05 12:29 UTC
When no states were found and click "Create a new one!" console write error:
`Error: [$rootScope:inprog] $apply already in progress`

This is reproduced in the example with checked "Simulate query for results?", but not always. Click many times to "Create a new one!".
With $http or $resource request this reproduced all time.

**Comment by ThomasBurleson** [comment] 2016-02-06 12:33
Unable to reproduce this with https://material.angularjs.org/HEAD/demo/autocomplete.
Which version are you testing against? Url?

**Comment by Knoxvillekm** [comment] 2016-02-06 21:04
HEAD (MASTER)
![123](https://cloud.githubusercontent.com/assets/11072464/12869367/d12325f2-cd25-11e5-841a-173d2dd08290.jpg)

**Comment by DevVersion** [comment] 2016-02-06 21:10
@Knoxvillekm To be honest, I can't reproduce that too. Is anything else to do?

**Comment by Knoxvillekm** [comment] 2016-02-06 21:15
https://www.youtube.com/watch?v=rwi_mbaFayI&feature=youtu.be

**Comment by ThomasBurleson** [comment] 2016-04-28 19:42
This issue is closed as part of our deprecation effort. 
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).

**Closed by ThomasBurleson** 2016-04-28 19:42 UTC
