### ISSUE TITLE
When selecting an item in md-autocomplete it fires a second lookup

### ISSUE THREAD

**Issue by nirving** [angular/material#1835] opened 2015-03-09 00:35 UTC
Example @ http://codepen.io/nirving/pen/pvOapE
1. Enter 'Rich' as the query, you will get 4 items in the list. 
2. Select 'Richmond' and you will get 4 items in the list
3. Select 'Richmond' and no further dropdown is displayed.

I would have though selecting an item would not by default execute a second query, but it appears to be the case.

**Comment by david-gang** [comment] 2015-03-09 12:32
This may be a duplicate of #1732

**Closed** 2015-03-18 17:24 UTC
