### ISSUE TITLE
toast disabeling <body> scrolling

### ISSUE THREAD

**Issue by ranbuch** [angular/material#7729] opened 2016-03-24 12:43 UTC
After toast disappears the body still has a "md-toast-animating" class witch looks like this:

```css
.md-toast-animating {
    overflow: hidden!important;
}
```

and scrolling is disabled.

version:
angular-material@^1.0.6

Thank you.

**Comment by topherfangio** [comment] 2016-03-24 18:50
This is currently by design but we are looking at ways to change this and make it better.

**Comment by ThomasBurleson** [comment] 2016-06-01 23:58
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Closed** 2016-06-02 01:55 UTC
Labels: P4 - Reported By or General PRs/Errors or Edge Cases

**Comment by ThomasBurleson** [comment] 2016-06-02 07:03
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
