### ISSUE TITLE
why not use   <!doctype html>

### ISSUE THREAD

**Issue by liuning108** [angular/material#2207] opened 2015-04-08 10:45 UTC
I add   <!doctype html> tag  ,but  css layout is not   in chrome browser abnormal

**Comment by ThomasBurleson** [comment] 2015-04-08 11:56
@liuning108 - I do not understand your issue here.

**Comment by marcysutton** [comment] 2015-04-08 21:36
Including a doctype triggers Standards mode. So if you see issues when you include it, it indicates something is wrong with your layout. Please include a live demo that shows your complete source code.

**Comment by marcysutton** [comment] 2015-04-24 21:23
Closing as duplicate of https://github.com/angular/material/issues/1470.

**Closed by marcysutton** 2015-04-24 21:23 UTC
Labels: question
