### ISSUE TITLE
Ink color staying on md-button after fast multiple clicks on it

### ISSUE THREAD

**Issue by gabguy** [angular/material#3706] opened 2015-07-13 14:01 UTC
Please fix the button remaining colored with the pressed class (the green light color) after clicking the button multiple times in a row.

A image of the button with the ink color after pressing on it multiple times:
![buttoncolored](https://cloud.githubusercontent.com/assets/7655154/8651276/902f3778-2980-11e5-8171-82df6966741a.PNG)

The original button color:
![original](https://cloud.githubusercontent.com/assets/7655154/8651312/ba36188e-2980-11e5-9939-407d15d0c47e.PNG)

Thanks in advance

**Comment by marcysutton** [comment] 2015-07-13 16:05
What is the purpose for clicking multiple times? I'm pretty sure the button is remaining focused, and you're getting around the logic for keyboard/focus styling.

**Comment by gabguy** [comment] 2015-07-13 16:28
There might not be a purpose for you, but it is still a graphical glitch. I'm just asking if you could please try and fix it

**Comment by mckenzielong** [comment] 2015-07-13 17:32
Think this is a dupe of https://github.com/angular/material/issues/3346 (covers staying light / dark depending on ripple)

**Comment by gabguy** [comment] 2015-07-13 17:35
OK, thank you, sorry couldn't spot it in the issues list

**Comment by ThomasBurleson** [comment] 2015-09-04 04:19
Fixed in v0.11.0-rc2

**Closed by ThomasBurleson** 2015-09-04 04:19 UTC
Labels: resolution: fixed
