### ISSUE TITLE
<TextArea> Scrollbars are not displayed on text area correctly

### ISSUE THREAD

**Issue by cmacdonnacha** [angular/material#8911] opened 2016-06-30 14:52 UTC
**Actual Behavior**:
 -  `What is the issue?` Scrollbars are not displayed on text area correctly when there is whitespace between words. You have no way of seeing all of the text.
 -  `What is the expected behavior?` Scrollbars should appear

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` http://codepen.io/cmacdonnacha/pen/MepMyB?editors=1010
 -  `Details:`

**Angular Versions**: *
 -  `Angular Version:` 1.5
 -  `Angular Material Version:` 1.1.0-rc.5

**Additional Information**:
 -  `Browser Type: Chrome`
 -  `Browser Version: 50.0.2661.102 m`
 -  `OS: Windows 7`
 -  `Stack Traces:`

![image](https://cloud.githubusercontent.com/assets/9777763/16492709/9916d1a0-3eda-11e6-88e4-cc8cda4d3c6d.png)

**Comment by AkashKG** [comment] 2016-07-01 14:56
The link you provided shows the scroll-bar.
![image](https://cloud.githubusercontent.com/assets/10387729/16525440/03ae19ac-3fca-11e6-80a3-0d04285e202a.png)
 Is it still showing the same? If not then close the issue.

**Comment by cmacdonnacha** [comment] 2016-07-01 15:18
@AkashKG It's still not showing for me:

![image](https://cloud.githubusercontent.com/assets/9777763/16526037/2c1d563c-3fa7-11e6-8986-f6d78c765c19.png)

What browser are you using?

**Comment by AkashKG** [comment] 2016-07-01 15:35
I'm using chrome, on Windows. Clean you cookies and cache - and test.

**Comment by ThomasBurleson** [comment] 2016-07-25 15:31
Unable to reproduce.

**Closed by ThomasBurleson** 2016-07-25 15:31 UTC
