### ISSUE TITLE
mdChips : Autocomplete input display 'true' before entered the first time.

### ISSUE THREAD

**Issue by waegen** [angular/material#2518] opened 2015-04-23 11:39 UTC
When creating a chips autocomplete component the first time the component is displayed but not entered (focused) the text 'true' is displayed instead of the placeholder.

See here: http://plnkr.co/edit/7zzPBLuPdxvgFveYl1s9?p=preview

Once the input area got focus the real placeholder is displayed.

Version: v0.9.0-rc2-master-a5c972f
Browsers: Chrome, IE, FF

**Comment by TalPasi** [comment] 2015-04-23 13:51
The problem it if md-search-text is not initialized in the vm first, 

setting vm.searchText = null will resolve the problem, but this is not desired solution

**Comment by ThomasBurleson** [comment] 2015-04-23 14:19
Duplicate of #2515

**Closed by ThomasBurleson** 2015-04-23 14:19 UTC
