### ISSUE TITLE
$mdDialog center issues with firefox

### ISSUE THREAD

**Issue by kschwidder** [angular/material#1593] opened 2015-02-20 23:07 UTC
Context:
We have a long list of items where each item is editable via an $mdDialog component.
The list can not be displayed in the browser window therefore we have to scroll down.

Issue with Firefox;
When you scroll down and select an item the $mdDialog the dialog can disappear since it is not properly centered on the screen.
![firefox center 1](https://cloud.githubusercontent.com/assets/3265624/6311051/8db5ec50-b95d-11e4-9cd0-a9f1b16a5057.png)
![firefox - scroll - bug dialog](https://cloud.githubusercontent.com/assets/3265624/6311050/8d95a562-b95d-11e4-836b-b9a5f77a3932.png)

It works with Safari and Chrome (IE not tested).

**Comment by kschwidder** [comment] 2015-03-05 07:23
IE and Firefox have the problem which inhibits production deployment

**Comment by marcysutton** [comment] 2015-03-11 18:55
Closing as duplicate of #1761.

**Closed by marcysutton** 2015-03-11 18:55 UTC
