### ISSUE TITLE
Flex not working when used inside dialog, release 1.0.4

### ISSUE THREAD

**Issue by JunedS** [angular/material#6971] opened 2016-02-02 08:18 UTC
Tried using flex inside dialog and it is not working as expected. Below is the code pen demo.

http://codepen.io/anon/pen/LGBzPJ

Thanks,
Juned S

**Comment by DevVersion** [comment] 2016-02-02 13:41
Flex in general works in a dialog as same as in other components. That may relate to your template.
As you can see in http://codepen.io/DevVersion/pen/EPpEgq, flex is working there. But there is a problem with the `flex="50"`, it seems that is too much and will wrap directly.

**Comment by DevVersion** [comment] 2016-02-02 13:44
Okay, finished investigation :). The problem is, you applied `layout-margin` which will shrink the `width` from `100%`, so two `50%` won't fit in there anymore. 

See here without `layout-margin`: http://codepen.io/DevVersion/pen/xZJWgx

So, the actual issue (flex isn't working in a dialog) isn't existing.

**Comment by ThomasBurleson** [comment] 2016-02-02 16:05
@thx DevVersion.
Closing as non-issue.

**Closed by ThomasBurleson** 2016-02-02 16:05 UTC

**Comment by JunedS** [comment] 2016-02-03 06:34
Check this out. Code pen with 1.00-rc1. It works with layout-margin and flex="50". This makes me think why the same started breaking.

http://codepen.io/anon/pen/adjgjO

**Comment by DevVersion** [comment] 2016-02-03 06:55
oh can see that. I will take a look later!
