### ISSUE TITLE
$mdBottomSheet still scrolling when parent set

### ISSUE THREAD

**Issue by mortware** [angular/material#7789] opened 2016-03-29 14:21 UTC
I see this issue has been fixed in the past, but it's still occurring for me.

`$mdBottomSheet.show({
    controller: BottomSheetController,
    controllerAs: 'vm',
    templateUrl: 'app/bottomSheet.html',
    parent: angular.element(document.getElementById('content'))
})`

After following the code, an 'md-scroll-mask' element is created and appended to the parent, but it the parent still wants to scroll down. I'm not sure whether this is supposed to set "overflow: hidden" on the parent, but it's not.

**Comment by DevVersion** [comment] 2016-03-29 14:24
@mortware Is this a duplicate of #7410? Can you check please?

**Comment by mortware** [comment] 2016-03-29 14:26
Yes it is, please close this, and i'll follow that one :)

**Comment by DevVersion** [comment] 2016-03-29 14:27
Awesome, thank you :+1:

**Closed by DevVersion** 2016-03-29 14:27 UTC
