### ISSUE TITLE
AutocompleteBug in v 0.10.1

### ISSUE THREAD

**Issue by Anand-Khedkar-Avalara** [angular/material#4261] opened 2015-08-20 14:43 UTC
If item want to search is not present then 'Not Found' message should appear.

See Image below

![autoselect bug](https://cloud.githubusercontent.com/assets/5468345/9386014/3145ec24-4777-11e5-8631-3d1f11d8ff4a.png)

**Comment by nestorneto** [comment] 2015-08-20 14:46
yeah, its not working properly..

**Comment by anand-patel** [comment] 2015-08-20 15:18
Yes, its not working.

**Comment by ngraef** [comment] 2015-08-20 16:16
Duplicate of #3876

**Comment by hannupekka** [comment] 2015-08-27 06:09
If you open this same example in CodePen (button next to "View Source" in the header of "Basic Usage") and try to select any suggestion, `<md-not-found>` always stays visible.

**Closed** 2015-09-10 17:24 UTC
