### ISSUE TITLE
Speed Dial & FAB Toolbar should appear only on clicking the FAB

### ISSUE THREAD

**Issue by mukilane** [angular/material#3214] opened 2015-06-10 16:26 UTC
According to the Material Design spec by Google, the FAB can transform into a toolbar upon press and it can fling out the speed dial also upon press. 
Hovering is not apt for a button. A button is meant to be pressed, not hovered.  And also when we hover away from it, the toolbar/speed dial disappears. This is not desirable. 

It is also given that, the FAB should transform into a 'most common task' or a 'close/back' button, in case of speed dial.

And, the FAB toolbar appears if I simply hover the area where it would appear, making it impossible to access other background contents in that area.

Reference: http://www.google.com/design/spec/components/buttons-floating-action-button.html

**Comment by cebor** [comment] 2015-06-10 16:52
duplicate of #3210

close pls

**Comment by robertbaker** [comment] 2015-06-10 19:43
If you have used the inbox, you should know that that's how it works on desktops. I like when it opens on hover, saving you a click.

**Comment by viztastic** [comment] 2015-06-20 05:19
Agreed with @robertbaker

**Comment by topherfangio** [comment] 2015-06-23 17:01
Hi all, I am planning to add an option called `md-trigger` which can be set to any combination of

* `hover`
* `click`
* `focus`

with a default of `click focus` for the toolbar and `hover focus` for the speed dial.

Does this cover all cases? Do the defaults sound good?

**Comment by cebor** [comment] 2015-06-23 17:07
Will this bring functionality for touch devices ? Also for hover mode ?

**Comment by topherfangio** [comment] 2015-06-23 17:39
@cebor I'm not sure what the issue was with touch devices. I will have to investigate. Regarding "hover mode", do you mean hover on touch devices? Hover on desktop is the existing functionality.

**Comment by cebor** [comment] 2015-06-23 20:23
Currently on touch devices, the menu does not open. Tested on ios and android.

I think what should be done is, that when material detects a touch device the trigger behaviour of the Speed Dial & FAB Toolbar should be changed to `click`.

**Comment by miketran13** [comment] 2015-06-25 05:01
@topherfangio : That's a good choice if you have onlick event because that when it's on the touch devices, we need to press the fab button to show the menu and it's also good that if we have the functions like Inbox: that on touch devices, when we pressing the fab button, It opens the menu with the tooltips are shown and the overlay background. It looks nice.

**Comment by xBelphegorx** [comment] 2015-07-01 15:15
I think that this options for md-trigger is good idea. I have only one question:
It would be available to configure this in one FAB: 
- enable open FAB on click
- disabled open FAB on hover
- enable close FAB on click and hover out ?

**Comment by jlmagee** [comment] 2015-07-22 13:45
@topherfangio @ThomasBurleson 

I added a crude md-trigger so I could specify "click" and resolve two issues.
1. Having the mouse/blur/focus screen geography impair the ability to have other clickable elements below the invisible md-fab-speed-dial element.
2. Inconsistent function when trying to control open status from javascript in my controller

Hope this helps.

*HTML SNIPPET*
    <md-fab-speed-dial id="searchfab" flex layout-align="end end" md-trigger="click" md-open="sd.fabStatus"
                       md-direction="up" class="db-fab md-scale" ng-show="app.findView()">
        <md-fab-trigger flex style="text-align: right;">
            <md-button flex aria-label="menu" class="md-fab md-accent" ng-click="sd.toggleFabStatus()"> 

*CONTROLLER SNIPPET*
    sd.myFabStatus = false;
    sd.fabStatus = sd.myFabStatus;
    sd.toggleFabStatus = function () {
        sd.myFabStatus = !!!sd.fabStatus;
        sd.fabStatus = sd.myFabStatus;
    };
    $timeout(function() { sd.toggleFabStatus(); },750);  // won't open until rendered? necessary in any case
    $scope.$watch('sd.fabStatus', function(newst, oldst){
       console.log(newst);
    });

*DIFF*
5946,5949d5945
<           if (controller) {
<             angular.forEach(element.children(), function(child) {
<               // Attach listeners to the `md-fab-action-item`
<               child = angular.element(child).children()[0];
5951,5953c5947,5955
<               angular.element(child).on('focus', controller.open);
<               angular.element(child).on('blur', controller.close);
<             });
---
>           if (controller.openTrigger !== 'click') {
>             if (controller) {
>               angular.forEach(element.children(), function (child) {
>                 // Attach listeners to the `md-fab-action-item`
>                 child = angular.element(child).children()[0];
>                 angular.element(child).on('focus', controller.open);
>                 angular.element(child).on('blur', controller.close);
>               });
>             }
6035a6038
>         openTrigger: '@?mdTrigger',
6068c6071
<         vm.moused = true;
---
>        vm.moused = true;
6097,6098c6100,6103
<         $element.on('mouseenter', vm.mouseenter);
<         $element.on('mouseleave', vm.mouseleave);
---
>         if (vm.openTrigger !== 'click') {
>           $element.on('mouseenter', vm.mouseenter);
>           $element.on('mouseleave', vm.mouseleave);
>         }
6481d6485
< 
6483,6487c6487,6493
<         if (controller) {
<           angular.forEach(element.children(), function(child) {
<             angular.element(child).on('focus', controller.open);
<             angular.element(child).on('blur', controller.close);
<           });
---
>         if (controller.openTrigger !== 'click') {
>           if (controller) {
>             angular.forEach(element.children(), function (child) {
>               angular.element(child).on('focus', controller.open);
>               angular.element(child).on('blur', controller.close);
>             });
>           }

**Comment by bdteo** [comment] 2015-07-25 03:54
I found some workaround and it is
md-fab-speed-dial {
        overflow : visible;
        height   : 0;
}
It is a bit hackish but this way "mouseenter" event wont be triggered.

**Comment by robertbaker** [comment] 2015-07-25 04:28
@jlmagee I would do an open PR with changes, make sure you sign the agreement.

**Comment by yuanstanley** [comment] 2015-07-27 17:19
+1

**Comment by lanmower** [comment] 2015-08-14 13:21
Since this got merged with 3314, does the hover trigger only happen on the md-fab-trigger element now? or does it still happen for its popup children?

**Closed** 2015-08-14 16:20 UTC
Labels: needs: merging

**Comment by topherfangio** [comment] 2015-08-15 07:41
The default has been changed to never open on hover, (a noted breaking
change) but the demo has been updated to show how you can use md-mouseenter
and md-mouseleave on the speed dial to achieve the same thing.

**Comment by lanmower** [comment] 2015-08-20 11:24
This issue then does not resolve 3314, since the complaint was that hover not only fires on the parent button but it fires if you hover over the hidden children, and this erroneous behavior is not only limited to hovering its clicking too. Can we please re-open 3314 so that that completely separate issue can be addressed.
