### ISSUE TITLE
md-datepicker: style issue with chrome 63+

### ISSUE THREAD

**Issue by HamzaMoummid** [angular/material#11018] opened 2017-12-14 17:05 UTC
**Actual Behavior**:
 -  `What is the issue? *`md-datepicker style issue with chrome versions :
 -  `What is the expected behavior?`i use angular version 1.4 and chrome version 62 it works fine.
But when i update chrome version to version 63 the date picker shows wrong

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
 -  `Details:`

**AngularJS Versions**: * 
 -  `AngularJS Version:` 1.4
 -  `AngularJS Material Version:` 1.4

**Additional Information**:
 -  `Browser Type: *` chrome
 -  `Browser Version: *` 63
 -  `OS: *` windows
 -  `Stack Traces:`

![screenshot](https://i.stack.imgur.com/kutXl.png)

**Comment by eknowles** [comment] 2017-12-14 22:23
Can you add more information, please?

**Comment by HamzaMoummid** [comment] 2017-12-15 09:45
angular md-datepicker is not showing correct in chrome version 63, but it looks nice in chrome version 2 with the same code
https://stackoverflow.com/questions/47818159/date-picker-style-issue-with-chrome-versions

**Comment by johnmcguin** [comment] 2017-12-15 23:07
I am seeing this behavior as well. Angular v 1.5.9, Angular Material v 1.0.9, Chrome v 63.0.3239.84. Looks exactly the same as @HamzaMoummid 's screenshot on SO

**Comment by jigar9992** [comment] 2017-12-21 06:07
I am also facing the same issue with Chrome v Version 63.0.3239.84 , Angular v 1.4.9, Angular Material v 1.0.3 . I found that the issue is with dynamic calculation of `md-calendar-scroll-mask` class's width which is 308px and on latest Material js it calculates 340px. (https://material.angularjs.org/latest/demo/datepicker)

**Comment by Splaktar** [comment] 2017-12-27 10:26
https://material.angularjs.org/latest/demo/datepicker is working fine for me on Chrome 63 and 65 on OS X. 

Is this only being seen on Windows?
Do you have a CodePen example and reproduction steps?
Is this reproducible with AngularJS 1.6.6+ and AngularJS Material 1.1.5?

**Comment by johnmcguin** [comment] 2018-01-02 18:05
@Splaktar , I'm having a hard time recreating this on Codepen as well, but have found a little more information if it helps. When I'm comparing the working codepen with the broken version within my app, I saw that there are two classes which seem to be calculating the wrong width when the datepicker is open. 

.md-calendar-scroll-mask and .md-virtual-repeat-scroller elements both calculate an inline width of 308px in the broken version and a width of 340px in the working codepen.  Further, if I toggle that calculated width off and on on the .md-calendar-scroll-mask element, the issue resolves itself. I'll still work toward recreating this issue in a codepen as well.

**Comment by SatishKumarG** [comment] 2018-01-05 14:08
Add this into your css file.
.md-calendar-scroll-container{
  width:100% !important;
}

**Comment by SatishKumarG** [comment] 2018-01-05 14:09
Add this into your css file.
.md-calendar-scroll-container{
  width:100% !important;
}

**Comment by HamzaMoummid** [comment] 2018-01-16 09:58
Thanks @SatishKumarG

**Comment by Splaktar** [comment] 2018-03-26 19:54
I'm going to close this as this appears to be unreproducible in a demo and is likely app-specific. As my other requests for info have not been addressed.

**Closed by Splaktar** 2018-03-26 19:54 UTC
Labels: needs: demo, needs: more info
