### ISSUE TITLE
Using enter on md-chips with md-autocomplete causes two items to be added

### ISSUE THREAD

**Issue by rafidka** [angular/material#4996] opened 2015-10-03 11:26 UTC
I have the following code for tags on my website:

    <md-chips ng-model="ctrl.tagNames" readonly="ctrl.readOnly"
              md-autocomplete-snap
              md-on-append="ctrl.onAppend()"
              md-require-match="false">
      <md-autocomplete
          md-selected-item="ctrl.selectedTag"
          md-selected-item-change=""
          md-search-text="ctrl.tagQuery"
          md-search-text-change=""
          md-items="tagName in ctrl.findTagNames(ctrl.tagQuery)"
          md-item-text="tagName"
          md-no-cache="true"
          placeholder="Search for a tag">
        <md-item-template>
          <span md-highlight-text="ctrl.tagQuery">{{ tagName }}</span>
        </md-item-template>
        <md-not-found>
          No matches found for "{{ ctrl.tagQuery }}".
        </md-not-found>
      </md-autocomplete>
      <md-chip-template>
        <span>
          <strong>{{$chip}}</strong>
        </span>
      </md-chip-template>
    </md-chips>

It is working correctly, but causes some problems when I use the keyboard instead of clicking. For example, say I want to search for the tag "science" and I type "sci". Then use the keyboard to move to the "science" tag in the auto completion and press Enter. This will cause both "science" and "sci" to be added to the chips.

**Comment by chr22** [comment] 2015-10-03 11:44
Here is a [CodePen](http://codepen.io/chr22/pen/ZGJabN) showing the issue.

**Comment by rafidka** [comment] 2015-10-03 11:49
Thanks @chr22. Do you have any idea how to work around it for now?

**Comment by chr22** [comment] 2015-10-03 11:52
No i have the same issue in my application.

**Comment by tonyawad88** [comment] 2015-10-04 17:16
+1

**Comment by tonyawad88** [comment] 2015-10-04 17:17
I believe it's related to this: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/ngmaterial/_IQ6FzJIH5k/p2Oy1gseCQAJ
?

**Comment by topherfangio** [comment] 2015-10-05 18:35
I believe this is a duplicate of #4412. Please comment if you disagree and I will reopen.

**Closed by topherfangio** 2015-10-05 18:35 UTC

**Comment by tonyawad88** [comment] 2015-10-05 21:53
@topherfangio reading 4412, it's along the same lines. The current workaround is to add md-require-match="true" to the md-chips directive. Hope this helps.

**Comment by jherman** [comment] 2015-10-23 20:30
@tonyawad88 This really isn't a workaround because you can't add in a custom chip then.  The desired affect is to be able to add in a custom chip (if it's not found in the autocomplete list), however if the search text matches a list item, and is that item is selected, it should be added instead of the partial search string.

**Comment by jherman** [comment] 2015-10-23 21:08
In the mean time I've added the following line to fix the issue:
```
 if (angular.element(document.querySelectorAll("md-virtual-repeat-container:not(.ng-hide) li[md-virtual-repeat].selected")).length) return;
```
To:
```
MdChipsCtrl.prototype.appendChip = function (newChip) {
  if (angular.element(document.querySelectorAll("md-virtual-repeat-container:not(.ng-hide) li[md-virtual-repeat].selected")).length) return;
  if (this.useOnAppend && this.onAppend) {
    newChip = this.onAppend({'$chip': newChip});
  }
  if (this.items.indexOf(newChip) + 1) return;
  this.items.push(newChip);
};
```

**Comment by biscolab** [comment] 2015-11-04 17:28
Thanks @rafidka it works! adding your code to angular-material.js will added only one item!
