### ISSUE TITLE
"TypeError: Cannot read property 'focus' of undefined" when using md-tabs

### ISSUE THREAD

**Issue by gpiancastelli** [angular/material#8111] opened 2016-04-19 14:24 UTC
Issue #6776 has been abruptly closed (and discussion restricted) four days ago with a comment about a bug in Angular 1.5.4 due to a change which was being reverted. However, the original report used Angular 1.5.0, so it's hardly believable that the culprit could be a change that was not even made at that time.

> Others in that thread reported the problem was not present in 1.5.3. But I recently had to downgrade to Angular 1.4.8 in order to have that TypeError disappear. 

Specifically, it had to do with md-tabs. I was unable to had tabs shown in the most simple document while working with a bunch of combinations involving Angular 1.5.4, 1.5.5, 1.5.3, and Angular Material 1.1.0rc3. I maintain that md-tabs do not work correctly with any 1.5.x version of Angular. Also, on the Angular Material website, the Angular version used on the demos page is... guess what? 1.4.8. How convenient.

**Comment by ThomasBurleson** [comment] 2016-04-19 14:48
@gpiancastelli - 

* Thank you for the alert that the docs are still using 1.4.8. This is an oversight that will be corrected. Our package.json, in fact, specifies `^1.5.0`. 
* If #6776 manifest in pre-1.5.4 releases, then it should not have been closed.

We will investigate this issue.

> Please note that sarcasm violates our [Code of Conduct](https://github.com/angular/code-of-conduct/blob/master/CODE_OF_CONDUCT.md) "... extend courtesy and respect to everyone".

**Comment by ThomasBurleson** [comment] 2016-04-19 14:52
@gpiancastelli - I am unable to reproduce any Tabs error with 1.5.5. Can you provide steps to reproduce this issue ?

**Comment by ThomasBurleson** [comment] 2016-04-21 00:28
Similar to #4388. May be fixed with #6684.

**Comment by DevVersion** [comment] 2016-04-21 12:02
@ThomasBurleson The PR #6684 is not updated anymore, I will resubmit a working PR if desired, just assign the issue to me if so.

**Comment by gpiancastelli** [comment] 2016-04-21 12:36
@ThomasBurleson I can confirm that Angular 1.5.5 does indeed work. Probably a browser cache issue on my part.

**Comment by ThomasBurleson** [comment] 2016-04-21 13:48
@gpiancastelli - Thank you for the update/reply. Closing this as a non-issue.

**Closed by ThomasBurleson** 2016-04-21 13:48 UTC
Labels: has: Pull Request, needs: more info, type: bug
