### ISSUE TITLE
MD Tabs with bug

### ISSUE THREAD

**Issue by ronildo** [angular/material#9704] opened 2016-09-27 15:35 UTC
**Actual Behavior**:
-  `What is the issue? *`
  - MD Tabs calculation the width with 1px smaller
-  `What is the expected behavior?`
  - All tabs should be in the same row

**CodePen** (or steps to reproduce the issue): *
-  `CodePen Demo which shows your issue:`
  - https://plnkr.co/edit/xvYBOaOd2WJDIedKTaB4
-  `Details:`
  - To reproduce it, run the example and click on the icon. It should show 3 tabs, but if the window is resized, the 4th tab will be displayed.

**Angular Versions**: *
-  `Angular Version: 1.5.8`
-  `Angular Material Version: 1.1.1`

**Additional Information**:
-  `Browser Type: Chrome`
-  `Browser Version: Version 53.0.2785.116 (64-bit)`
-  `OS: MAC OS`

**Comment by levgaas** [comment] 2016-09-28 22:14
The same. 2 Tabs "1" and "Roboto".
I've investigated that this issue is only when md-tabs is used in **md-dialog**. 

http://codepen.io/anon/pen/bwRkba#anon-login

**Comment by clshortfuse** [comment] 2016-12-15 18:58
Dupe of #9429

**Closed by clshortfuse** 2016-12-15 18:58 UTC
Labels: has: Pull Request, P5 - Needs Investigation, ui: CSS
