### ISSUE TITLE
mdTabs RTL behaviour

### ISSUE THREAD

**Issue by NaNgets** [angular/material#9487] opened 2016-09-01 15:42 UTC
mdTabs in RTL mode is a bit broken:
* Next and previous buttons aren't working,
* Swipe (if enabled) is working in the opposite direction.

http://codepen.io/anon/pen/EgxyAL
(change the screen size so it would have pagination)

(with Angular 1.5.8 and Angular Material 1.1.0)

**Comment by topherfangio** [comment] 2016-09-01 17:13
Duplicate of #9292. Should be fixed by #9301 when it gets merged.

**Closed by topherfangio** 2016-09-01 17:13 UTC
Labels: resolution: duplicate

**Comment by anilk533** [comment] 2017-12-20 09:26
RTL direction for material tabs not working.
here is the issue.
https://codepen.io/djidel/pen/NpMpmY

please let me know how to solve

thank you
