### ISSUE TITLE
Sidenav should behave like bottom sheet (drag mouse touch)

### ISSUE THREAD

**Issue by shak18** [angular/material#2286] opened 2015-04-13 15:09 UTC
i belive and according to the apps like gmail, or playstore for android usingg material desing that sidebars should follow the left right mouse touch drag as the bottom sheet already does for the up and down gestures

**Comment by marcysutton** [comment] 2015-04-16 19:01
Looks like this was requested quite a while ago! We should prioritize it @ThomasBurleson. closing as duplicate of #35.

**Closed by marcysutton** 2015-04-16 19:01 UTC
