### ISSUE TITLE
autocomplete: screen reader doesn't vocalize that input is required

### ISSUE THREAD

**Issue by EamonKavanagh** [angular/material#10888] opened 2017-09-06 16:52 UTC
**Actual Behavior**:
 -  When an `md-autocomplete` has the `required` attribute or `aria-required="true"` set, screen readers do not make this known
 -  Like an `md-input-container`, the screen reader should make it clear that the field is required. For example, when an `md-input-container` contains a text element with `aria-required="true"`, it announces "Edit text required".

**CodePen** (or steps to reproduce the issue): *
- See the demo on the Angular Material page here: https://material.angularjs.org/1.1.4/demo/autocomplete, specifically the Favorite state required input
- Tested using ChromeVox 53.0.2784.5 and we've had reports of this using ChromeVox on ChromeOS as well.

**AngularJS Versions**: *
1.6.4-local+sha.617b36117

**Additional Information**:
- Chrome 59.0.3071.115

**Comment by Splaktar** [comment] 2018-08-10 23:42
VoiceOver on macOS reports "Favorite state, required invalid data, combo box" which seems to be working as intended.

On Chromevox for ChromeOS 68, it reports "Favorite state, Collapsed Required, Combo Box is editing, Press up or down arrow for auto completions."

It appears that this was fixed on the Chromevox side since I see the same behavior with AngularJS Material 1.1.4 and 1.1.10.

**Closed by Splaktar** 2018-08-10 23:42 UTC
Labels: P2: required, a11y, reported by Googler, type: bug
