### ISSUE TITLE
AngularJs $mdToast, $mdDialog is not working in route?

### ISSUE THREAD

**Issue by Rexota** [angular/material#1542] opened 2015-02-17 01:53 UTC
I was happily calling `$mdDialog.show` or `$mdToast.show`but I started to use `$routeProvider`, I can't use them anymore, I'm getting this error **when I tried to open toast or dialog**:

    TypeError: Cannot read property 'overflow' of undefined
    at forEach.css (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.6/angular.js:2831:27)
    at Object.JQLite.(anonymous function) [as css] (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.6/angular.js:2944:27)
    at Object.s [as onShow] (https://ajax.googleapis.com/ajax/libs/angular_material/0.7.0/angular-material.min.js:121:1344)
    at https://ajax.googleapis.com/ajax/libs/angular_material/0.7.0/angular-material.min.js:55:2782
    at processQueue (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.6/angular.js:13137:27)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.3.6/angular.js:13153:27
    at Scope.$eval (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.6/angular.js:14353:28)
    at Scope.$digest (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.6/angular.js:14169:31)
    at Scope.$apply (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.6/angular.js:14457:24)
    at done (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.6/angular.js:9614:47)

Here is my app:

    var app = angular.module('APP', ['ngMaterial', 'ngRoute'])

    app.config(['$routeProvider',
    function($routeProvider) {
        $routeProvider.
            when('/', {
                templateUrl: '/assets/tpl/ana.tmp.html',
                controller: 'cbiKontrol'
            })
    }]);
    app.controller('cbiKontrol', ['$scope', '$mdDialog', '$window', '$mdToast', '$location' , function($scope, $mdDialog, $window, $mdToast, $location){

       var toastShow = function(content) {
	       $mdToast.show({
	         template: '<md-toast><span flex>'+content+'</span></md-toast>',
	         hideDelay: 1800,
	         position: "top right"
	       })
	   }
       //toastShow("test") 
    })

   

`ana.tmp.html` only has a lot of divs.

index.tmp.html (when the page is first rendered):

    <!DOCTYPE html>
    <html>
    <head>
    <title></title>
    <link rel="stylesheet" type="text/css" href="/assets/css/stil.css"/>
    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/angular_material/0.7.0/angular-material.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=RobotoDraft:400,500,700,400italic">
    <script src="http://hammerjs.github.io/dist/hammer.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.3.6/angular.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.3.6/angular-animate.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.3.6/angular-aria.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.3.6/angular-route.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angular_material/0.7.0/angular-material.min.js"></script>
    <script type="text/javascript" src="/assets/js/app.js"></script>
    </head>
    <body ng-app="APP" ng-view></body>
    </html>

What can be the problem? I want to use Dialog and Toast classes. I'm new to angularjs.

**Comment by Oza94** [comment] 2015-02-17 14:36
With `$mdToast`, you should create a toast object before showing the toast:

```javascript
// create toast settings object
var toastSettings = $mdToast.simple().content('Hello!');

// show previously created toast
$mdToast.show(toastSettings);
```

Morever, you can't use a custom template/controller with `$mdToast`. [This is described on the docs](https://material.angularjs.org/#/api/material.components.toast/service/$mdToast).

**Comment by gkalpak** [comment] 2015-02-17 14:49
According to the docs, you **can** use custom templates/controllers.

**Comment by Rexota** [comment] 2015-02-17 15:16
The problem is I can't use mdToast and mdDialog after using ngRoute. Before I can use.

**Comment by gkalpak** [comment] 2015-02-18 08:02
@Rexota, it is probably because you use `ngView` on the body (which is not a good idea).
If you use `ngView` on a child-element of body, it [seems to work fine][1].

If you are still facing problems, please create a live reproduction (using CodePen, Plunkr, JSFiddle etc).

[1]: http://jsfiddle.net/ExpertSystem/rcrhj5L5/2

**Comment by Rexota** [comment] 2015-02-18 11:56
@gkalpak Thanks so much. That fixed it.

**Comment by gkalpak** [comment] 2015-02-18 13:04
@Rexota, np. (Please, close the issue if the problem is solved :smiley:)

**Closed** 2015-02-18 13:06 UTC
Labels: bug
