### ISSUE TITLE
md-autocomplete list items doesn't full width

### ISSUE THREAD

**Issue by tsdragon0404** [angular/material#4619] opened 2015-09-14 11:01 UTC
Width of item in list suggestions doesn't expand full div.

**Comment by EladBezalel** [comment] 2015-09-14 11:18
Please provide a CodePen or Plunkr that demonstrates this issue. Here are some starter demo templates that you can use/fork:

*  [CodePen template](http://codepen.io/team/AngularMaterial/pen/BNYppz)
*  [Plunkr template](http://plnkr.co/edit/yP0gB9iTacIQb48thud8?p=preview)

**Comment by tsdragon0404** [comment] 2015-09-15 03:32
@EladBezalel I attached image for that. Thanks.
![untitled](https://cloud.githubusercontent.com/assets/11863784/9867189/fbcc132a-5b94-11e5-81a9-3f374127e8dc.png)

**Comment by EladBezalel** [comment] 2015-09-15 13:29
@tsdragon0404 it's from the material website or your project? I can't investigate from a picture

**Comment by topherfangio** [comment] 2015-09-15 13:40
This looks like a duplicate of #4308.

**Comment by cssensei** [comment] 2015-10-14 10:29
@tsdragon0404 I've submitted a [PR](https://github.com/angular/material/pull/5151) for this issue. Please check and let me know if all it's ok. Thanks!

**Comment by topherfangio** [comment] 2015-10-14 15:52
I think this may have already been fixed as I can't reproduce in 11.3/11.4 which were just released.

@cssensei Can you please re-test with the latest version and let us know if you're still having trouble? If not, could you go ahead and close your PR?

Thanks!

**Comment by topherfangio** [comment] 2015-10-14 15:53
Indeed, should have been fixed in 9dd2e354947746279dddc5a83b263f97c26e0647. I am closing, please re-open if you still have issues.

**Closed by topherfangio** 2015-10-14 15:53 UTC
