### ISSUE TITLE
Menu - Icons on top of text (mobile device)

### ISSUE THREAD

**Issue by runethh** [angular/material#7340] opened 2016-02-29 14:58 UTC
How to reproduce:
1. Go to Menu in the demo area of Angular Material
2. Select Menu
3. Scroll to Menu Width

Observe that the icon and text overlaps

![image](https://cloud.githubusercontent.com/assets/16044495/13398135/459c0c26-defd-11e5-9cf2-b233b4011845.png)

Tested on:
Version: Angular Material 1.0.5
Model: Ipad mini (ME279KN/A)
Browser: Safari 9
Operating system: Safari 9.1 (13B143)

**Comment by topherfangio** [comment] 2016-03-24 20:30
@DevVersion Pretty sure that this has something to do with the wrapper around the menus using the `layout-fill` attribute which sets the height to `100%`. Not sure why it's using that, we might be able to just remove it and fix the issue.

**Comment by DevVersion** [comment] 2016-03-26 17:49
@topherfangio I can't reproduce this one on my end. Can you please take a look again? I'm a bit confused about @runethh steps.

**Comment by Hammild** [comment] 2016-03-29 08:34
+1
I'm experiencing the same problem as @runethh . Works fine in a desktop browser (Chrome 49.0.2623.87) and in horizontal view on an iPad mini. The icon and text only overlaps when in vertical view.

Reproduce:
1. Go to "Demos" > "Menu" > Scroll to "Menu Width"
2. Observe that the icon and text is overlapping (see images for both the vertical- and hotizontal-view).
![menu - horizontal](https://cloud.githubusercontent.com/assets/17002487/14102262/bf44be44-f599-11e5-86e3-acae59eb0cce.png)

![menu - vertical](https://cloud.githubusercontent.com/assets/17002487/14102265/c43c9b92-f599-11e5-9f33-d50bfcf7ec1d.png)
Tested on:
Version: Angular Material 1.1.0-RC1
Model: iPad mini (ME279KN/A)
Browser: Safari 9.3
Operating system: 9.3 (13E237)

**Comment by topherfangio** [comment] 2016-04-04 20:29
@DevVersion Can you reproduce now? If not, just assign it to me and I'll take a look. **Should** be a quick fix :smile:

**Comment by topherfangio** [comment] 2016-04-20 18:30
Well, I thought I fixed this in 12ceef39d80b9b8e49374c121511554132eec847 a few days ago, but it looks like it's still broken. I'll take another look at it 😄

**Comment by DevVersion** [comment] 2016-04-20 18:34
@topherfangio Cool thanks, Still strange, that I can't reproduce that..

**Closed** 2016-06-02 01:55 UTC
Labels: P3 - Docs / Demos / Internal Contrib

**Comment by ThomasBurleson** [comment] 2016-06-02 07:08
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
