### ISSUE TITLE
md select null value

### ISSUE THREAD

**Issue by garaboncias** [angular/material#6851] opened 2016-01-26 16:26 UTC
md-select show selected state even null value is selected (md-input-has-value class is not removed from md-input-container)
demo:
http://codepen.io/anon/pen/vLRjZo

workaround: if first md-options has invalid ng-value (ex: xxxnull) then work as expected (but only if the second md-options use value instead of ng-value which is not documented but used in demos)
![screen shot 2016-01-26 at 17 20 06](https://cloud.githubusercontent.com/assets/2393180/12586564/13762afe-c451-11e5-961e-36eae74e0af5.png)

so there are more problems:
1. null value selection not work as expected
2. value attribute is not documented but used in demos
3. demos' codePens on page https://material.angularjs.org/1.0.3/demo/select use localhost:8080 as source for angular material lib not a CDN

**Comment by trimox** [comment] 2016-01-28 13:47
This issue also occurs if setting the state to just an empty string value. 
ie: <md-option></md-option>
![mdselect](https://cloud.githubusercontent.com/assets/11887843/12646004/a30a4592-c59b-11e5-92ed-2a6df61d2d3f.gif)

**Comment by DevVersion** [comment] 2016-03-06 19:38
Duplicate of #6504.

**Comment by garaboncias** [comment] 2016-03-07 04:39
'menu' spec does't say anything about empty value. Before material v1.0 its works as expected, it has the same behaviour  as an input fields because it's looks like the same.
It's a bug (or at least very inconsistent behaviour) that you can't reach the initial state: the label is down when you don't give a value at the beginning, and once you select anything the label float up and stick there.
#6504  is a workaround not a solution.

**Comment by topherfangio** [comment] 2016-06-28 15:14
@garaboncias Rather than using `null`, you can use `undefined`: http://codepen.io/topherfangio/pen/zBZEeM

This works even in 1.0.3, although there were some styling issues that have been fixed in 1.1.0-RC5.

Does this meet your needs?

**Comment by garaboncias** [comment] 2016-06-28 15:37
unfortunately its a semi-working dirty workaround.
1. not working if you not set the model value to null. In the example:
this.state = null;
2. not working if you use ng-value on md-option (ex. your options are object not a string). In the example:
<md-option ng-repeat="state in ctrl.states" ng-value="state.abbrev">

**Comment by topherfangio** [comment] 2016-06-28 16:32
@garaboncias I see what you mean. Let me dive into it and take a deeper look.

**Comment by topherfangio** [comment] 2016-06-28 16:47
@garaboncias I've updated my Codepen to use `undefined` everywhere. Of particular importance, you must use `<md-option ng-value="undefined">` instead of `<md-option value="undefined">` since the latter will be treated like a string.

http://codepen.io/topherfangio/pen/zBZEeM?editors=1010

Does this solve your issue? If so, perhaps we should update the docs/demos with this capability.

**Comment by garaboncias** [comment] 2016-06-28 22:09
Sorry but not. Its works till other `md-option`s use `value`, but not when use `ng-value` (was my 2. point, when you want to use object as a value) 
please check:
http://codepen.io/anon/pen/wWJjgR?editors=1010

**Closed** 2016-07-10 19:46 UTC
Labels: has: Pull Request
