### ISSUE TITLE
Input with placeholder not playing nicely with angular-translate

### ISSUE THREAD

**Issue by AntonTrapp** [angular/material#1742] opened 2015-03-02 13:30 UTC
I don't know if it is a angular-translate problem or a material problem, but the fix (https://github.com/angular/material/issues/1279) only is working for hardcoded labels (... placeholder="whatever" ...). If I use angular-translate (... placeholder="{{'key' | translate}}" ...) the result is fine if the field is not in focus, if I click on it the placeholder appears 2 times (looks like I am drunk *lol*).

**Comment by ThomasBurleson** [comment] 2015-03-12 02:53
Please provide a CodePen or Plunkr that demonstrates this issue.

**Comment by AntonTrapp** [comment] 2015-03-12 07:55
Not with Plunkr. Tried to add material package on Plunkr - does nothing. Tried to copy the Getting started sample to Plunkr - not working there. A few minutes later Plunkr was offline.

Created a gist with CodePen: https://gist.github.com/anonymous/24a992448590489ce291

You can forget the CSS, the JS too (just provides a translation for the 'translate' filter.

In the form there are 2 input fields, one with a static label and the second with the translation via filter. provides the same generated HTML but looks ugly (label and placeholder if not in focus on the same position, blurry label if in focus). Tested on Chrome with this pen.

**Comment by KayEss** [comment] 2015-03-21 06:20
The `textarea` is similarly broken with dynamic place holders.

**Comment by AntonTrapp** [comment] 2015-03-21 07:54
Can confirm the textarea problem.

As a workaround: When I use it inside the template of a directive

```
emptyLabel: '@?'
...
data-placeholder="{{emptyLabel}}")
```

and call it like this:

```
data-empty-label='{{"model.user.email_placeholder" | translate}}'
```

it is working for me. I have just some additional attribute stuff going on in the compile function (that has nothing to do with the input problem, if it's not working without the compile function try to add a dummy attribute to the input - that's what i'm doing). Maybe this is working for all people that are waiting for a fix or is helping the developers.

**Comment by AntonTrapp** [comment] 2015-04-08 19:31
"That is not an issue with translate. I have found your Pen http://codepen.io/anon/pen/OPBxBe and it clearly uses only a filter. In filters, no DOM operations are involved." - knalli #941 on angular-translate

So it is a material bug.

**Comment by denjello** [comment] 2015-04-29 05:55
yes - I have seen this as well. My temporary CSS workaround was this:

```
:-webkit-input-placeholder {
  opacity:0;
}
:-moz-placeholder {
  opacity:0;
}
::-moz-placeholder {
  opacity:0;
}
:-ms-input-placeholder {
  opacity:0;
}
```

**Comment by zeeshanjan82** [comment] 2015-06-15 11:35
Thanks @denjello

**Comment by vbraun** [comment] 2015-11-03 19:31
This issue has nothing to do with angular-translate (or angular-gettext, whichever you prefer), it happens with any computed value for placeholder. For example, just

    <md-input-container>
        <input placeholder="{{'Email'}}">
    </md-input-container>

shows two placeholders on top of each other with slightly different font.

Using `data-placeholder` is a workaround but applies only on page load; its effectively a one-time binding. For example,

    <md-input-container>
        <input data-placeholder="{{ctrl.email}}">
    </md-input-container>

uses the value of `ctrl.email` on load but does not update if `ctrl.email` changes later on. That is: The `data-placeholder` attribute does change, but the value shown in the placeholder does not.

**Comment by arsonik** [comment] 2015-12-10 09:43
any update ? ?

**Comment by karlfock** [comment] 2016-01-27 09:34
Also having problems with md-input-container with angular-translate. Any news?

**Comment by jonaszuberbuehler** [comment] 2016-02-10 14:00
+1 for a fix

**Comment by thanuzz** [comment] 2016-02-23 10:20
+1

**Comment by Warzou** [comment] 2016-03-01 03:45
+1 Would be great =)
Someone knows if there is a workaround ??

**Comment by AlexanderKozhevin** [comment] 2016-03-04 10:45
+1

**Comment by thanuzz** [comment] 2016-03-09 09:22
I've created a workaround by extending the Angular Material Placeholder directive. I've created an overrule js file in my project with the following code:

```
(function () {
	'use strict'

    angular.module('app.core').config(['$provide', function ($provide) {
    	$provide.decorator('placeholderDirective', ['$delegate', '$translate', function ($delegate, $translate) {
    		var directive = $delegate[0];
			var link = directive.link;

			directive.compile = function () {
				return function (scope, element, attr, inputContainer) {
					link.apply(this, arguments);
					$translate(attr.placeholder).then((translation) => {
						inputContainer.element.find('label').text(translation);

						//Only uncomment following line if you're using static labels or md-no-float attribute
						//element.attr("placeholder", translation);
					});
    			};
    		};

    		return $delegate;
        }]);
    }]);

})(); 
```

The placeholder attribute's value should be the translation key:
```
<input ng-model="myProfile.phone" placeholder="myProfile.phoneNumber" type="tel"  />
```

The decorator injects the $translate service. In the extended link function the translate service is called with the placeholder value and with the result i overwrite the label contents. 
As said in the code comments only uncomment the 'element.attr' if you use 'md-no-float' attribute or static labels. 

Hope this helps!

**Comment by bradrich** [comment] 2016-06-20 02:52
I am not sure if this is still an issue. Please take a look at this pen:  http://codepen.io/bradrich/pen/bewLav.

It would seem that any introduction of a placeholder to a md-input-container input element along with a label simply puts the label above the input.

**Comment by thanuzz** [comment] 2016-06-21 05:38
@bradrich Yeah, sorry about that, I did reproduce the issue and commented on it but removed it again because on second thought the added variant is indeed a bug but is easily worked-around by adding a translated label without the placeholder attribute on the input. I.m.o. this should be the preferred approach by default.

With this option also available I think every possible scenario is covered with placeholders/labels & translate and the only bug left is when you only use a translated placeholder without the label tag.

Maybe you'd like to also add this variant to your pen?

```
      <md-input-container>
        <label translate="placeholder"></label>
        <input type="text" />
      </md-input-container>
```

**Comment by bradrich** [comment] 2016-06-21 13:41
@thanuzz I have added the variant to the pen. I am seeing some weirdness in with this issue. I have forked the material repo and have made the changes in order to reproduce this issue and everything is working as expected. It is the strangest thing. Same versions of angular, material, etc.

Here is the code that is used to handle this type of placeholder, i.e. a placeholder without a label that is not on a md-select element:

```
if (element[0].nodeName != 'MD-SELECT') {
  var newLabel = angular.element('<label ng-click="delegateClick()" tabindex="-1">' + attr.placeholder + '</label>');
  attr.$set('placeholder', null);
  inputContainer.element
    .addClass('md-icon-float')
    .prepend(newLabel);

  $compile(newLabel)(scope);
}
```

If I had to make a guess, it would be that the translate filter delays the scope digest cycle and the above code is altering the placeholder and creating the new label prematurely. Using $timeout would normally be used to wait for the cycle to finish. This could explain how the new label is created, all of the classes are properly added, but then all of a sudden a random placeholder is put back in from the translate filter. The $timeout could be added to the functionality, but you have to wonder if fixing the 2% is worth risking the 98%.

My suggestion is that if you want a translated label, seek another method besides using the placeholder that will eventually become a label and use the label directly as we have in the pen. And, subsequently, this could be chalked up as you have said, as a bad implementation and not an issue...

**Comment by thanuzz** [comment] 2016-06-23 13:28
@bradrich Thanks for your extensive reply. I agree with your suggestion and personally would not add a $timeout for this. I remember back in March I changed the priorities of the translate and material input/placeholder directives trying to fix this but it didn't solved it then. 

If you add a warning or fix, keep in mind both implementations below can be used, the latter if you're using variables in your placeholder text.
```
<input placeholder="{{ 'KEY' | translate }}" />
<input translate translate-attr-placeholder="WITH_VALUES" translate-values="{{values}}" />
```

**Comment by bradrich** [comment] 2016-06-30 19:06
Closed as implementation issue not bug.

**Closed by bradrich** 2016-06-30 19:06 UTC
Labels: i18n: localization

**Comment by palaska** [comment] 2016-09-09 17:15
just use $route.reload() after executing the translate.

**Comment by shivanandbhangari** [comment] 2017-05-26 12:30
hello all,
i am new to angular2 , i am trying to do translation languages from one text to another textbox means if i write in first TextBox the value should be automatically copied in Second TextBox in Model Driven Form or Reactive Form. Can anyone help me out. I am trying it from last one week but i am not getting help from google also plz help me out. Thank you.

**Comment by agawande72** [comment] 2018-04-27 05:44
Working for me
placeholder="{{ 'text' | translate }}"
