### ISSUE TITLE
autocomplete: shows dropdown on top even when there is no room

### ISSUE THREAD

**Issue by begemott** [angular/material#10859] opened 2017-08-18 06:56 UTC
**Actual Behavior**:
 -  `What is the issue? *`
Sometimes the autocomplete dropdown will be shown at the `top` of an input, partially out of the screen, but it should be `bottom` position in this case.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` https://codepen.io/dumchikov/pen/zdRrYO

#### Steps to reproduce
   - The `md-autocomplete` should not have `md-dropdown-position` (position should be determined automatically) 
   -  The `md-autocomplete`'s input should be placed below the screen, so the window should be scrolled to see the input.
   - Scroll the window until the `md-autocomplete`'s input gets the top of the window
   - Focus the input 
   - The autocomplete dropdown will be shown at the top of input partially out of the screen, but should be at the input's bottom

**AngularJS Versions**: *
 -  `AngularJS Version:` 1.5.5
 -  `AngularJS Material Version:` 1.1.4

**Additional Information**:
 -  `Browser Type: *` Chrome, FF, IE
 -  `Browser Version: *` Chrome - 60.0.3112.90, FF - 54.0.1, IE - 11
 -  `OS: *` Window 7

 Another issue reproduced on FF and IE only - after closing the dropdown the window is scrolled to the window top.

**Comment by AkhilNaidu09** [comment] 2017-09-11 11:49
I have a work around for the last point (winodw is scrolling to top after closing drop down)

Issue : _Another issue reproduced on FF and IE only - after closing the dropdown the window is scrolled to the window top._

```
_:-ms-input-placeholder, :root {
  body[style] {
    position: inherit !important;
    top: inherit !important;
    width: inherit !important;
  }

  .md-click-catcher.md-wbTheme-theme {
    height: 100%;
    position: fixed;
    width: 100%;
  }
}
```

**Comment by AkhilNaidu09** [comment] 2017-09-11 11:51
If you want to open options list alway downwards means this is the workaround we have upto now.

open angular-material.js file

change **shouldOpenAroundTarget** to **True**,

```
function calculateMenuPositions(scope, element, opts) {
      var
        containerNode = element[0],
        targetNode = opts.target[0].children[0], // target the label
        parentNode = $document[0].body,
        selectNode = opts.selectEl[0],
        contentNode = opts.contentEl[0],
        parentRect = parentNode.getBoundingClientRect(),
        targetRect = targetNode.getBoundingClientRect(),
         shouldOpenAroundTarget = true,
```

**Comment by alexthewilde** [comment] 2017-09-13 08:49
Another effective workaround is to simply use `md-dropdown-position="bottom"`.

**Comment by areeb5** [comment] 2017-11-17 13:34
this way is justing putting the dropdown elements below the control(md-autocomplete), but that list is very compact, hardly only 2items is showing as i have attached snapshot, kindly any one help me in this,
i have also applied css to body hard coded (height:auto !important;) but that also disturbing the scroll of application.
![i422 cimgpsh_orig](https://user-images.githubusercontent.com/5106831/32949767-cc79ff58-cbc5-11e7-98c6-e69cad8222e3.png)

**Comment by Splaktar** [comment] 2018-03-01 09:12
The window jumping to the top on selection has been fixed. Updated [CodePen](https://codepen.io/Splaktar/pen/vdbjwE?editors=1010#0) showing the fix in 1.1.7.

But the popup is still displaying on top, even when there is no room on the screen to display it. It also disables the window's scroll, so you can't scroll up without closing the popup. If a hard coded `md-dropdown-position` is not defined, it should choose the option which fits the popup the best.

**Comment by Suvarnni** [comment] 2018-10-04 10:18
in which release we can expect this issue fix, because I'm facing a similar issue like this in IE11 browser.

**Comment by Splaktar** [comment] 2018-11-09 22:29
@Suvarnni we would like to get it into 1.1.12. If you are interested in taking a shot at fixing it, I can help review your PR.

**Comment by balajiprasadb** [comment] 2019-01-03 10:54
Hi @Splaktar, I'm facing the same issue. When can we expect this to be fixed?

**Comment by marosoft** [comment] 2019-01-03 15:47
Hi @Splaktar 

The problem is with `top` and `bottom` values of `root` being negative:
<img width="900" alt="screenshot 2019-01-03 at 15 02 38" src="https://user-images.githubusercontent.com/3945455/50645775-3d400080-0f6c-11e9-8647-a7a90ef14678.png">


I made some changes to fix the problem. Please check this [CodePen](https://codepen.io/marosoft/pen/wRyoMd). I am displaying some debug data in the console.

These are my code changes:
<img width="1349" alt="screenshot 2019-01-03 at 15 29 46" src="https://user-images.githubusercontent.com/3945455/50645846-6f516280-0f6c-11e9-874d-0c37bc6d4c2c.png">

This is a [code line](https://github.com/angular/material/blob/master/src/components/autocomplete/js/autocompleteController.js#L143) I changed.

`top` and `bottom` values of `vrect` are relative to the viewport.

**Comment by Splaktar** [comment] 2019-01-03 19:51
@marosoft thank you for looking into that. The fix looks good to me. Please submit a PR.

**Comment by Splaktar** [comment] 2019-02-01 18:49
The fix for this was reverted in PR https://github.com/angular/material/pull/11626 due to a regression that it caused. 

PR https://github.com/angular/material/pull/11629 has been posted to bring this fix back, but it still needs reproduction steps for the regression before it can be investigated and fixed.

**Closed** 2019-02-08 21:11 UTC
Labels: P3: important, for: internal contributor, has: Pull Request, severity: inconvenient, type: bug, ux: integration
