### ISSUE TITLE
Online docs - Child Alignment demo not working correctly

### ISSUE THREAD

**Issue by camden-kid** [angular/material#6576] opened 2016-01-07 15:43 UTC
Related to https://material.angularjs.org/latest/layout/alignment.

After clicking on the View Source icon in the demo the markup doesn't reflect the options selected and the expanded markup display obscures some of the options.

**Comment by mckenzielong** [comment] 2016-01-07 16:11
dupe of #6564

**Comment by DevVersion** [comment] 2016-01-07 17:25
@camden-kid - @mckenzielong is right that's a dupe and is it's already fixed in PR #6567

**Comment by DevVersion** [comment] 2016-03-20 16:20
Already xied with SHA 82625cf4edeba84ef38fb816f1b32ded902c8064

**Closed by DevVersion** 2016-03-20 16:20 UTC
Labels: P2 - Planned Work / Team PRs, ui: flexbox
