### ISSUE TITLE
md-menu Touch devices issue

### ISSUE THREAD

**Issue by Benyaminov-d** [angular/material#3785] opened 2015-07-17 09:37 UTC
Menu on iPhone and Android sometimes not works. Items in menu just not clickable. Also on touch devices menu stay opened when select and item in menu.

I am using bower-material v.0.10.1-rc2

Tried another versions - found even more bugs. Like - menu works, but Tabs on iOS looks very bad and even dont work.

**Comment by FDIM** [comment] 2015-07-20 12:13
I can confirm, menu doesn't go away when item is tapped. I guess its because ng-touch stopPropagation/prevents default for ng-click.

**Comment by luiseklein** [comment] 2015-07-21 15:37
I think it's because the function to "Close menu on menu item click, if said menu-item is not disabled captureClickListener = function(e)" is only listening to 'click' and no touch events.

**Comment by luiseklein** [comment] 2015-07-23 10:18
I found that the menu stopped reacting to touch with 602f49048ddd712798f54130ef4430a9fb52e02d and the changes in util.js transitionEndPromise (now called waitTransitionEnd). When I change this function's content back to the old version, the menus close again on tap. However, this is merely a hint - I don't now what other things have change since then and of the side effects.

**Comment by lucasmartinez** [comment] 2015-07-30 18:41
I agree with FDIM. If I include ngTouch module, md-menu doens't go away. Is there any workaround for this issue ? Can I close mdMenu manually with any function ?

**Comment by ThomasBurleson** [comment] 2015-07-30 19:25
Menu and Select both have conflicts (using `.waitTransitionEnd()`) with ngAnimate v1.4.x. This will be resolved with the https://github.com/angular/material/pull/3949.

**Comment by rschmukler** [comment] 2015-08-17 17:47
This appears to be resolved running `HEAD` on the docs site. Note that we are using Angular `v1.4.3` which also has some bug fixes in it around ngAnimate.

**Closed by rschmukler** 2015-08-17 17:47 UTC
Labels: hotlist: angular-issue, hotlist: animations, needs: investigation, summit
