### ISSUE TITLE
Datepicker Issues (Release 1.0.2) #6725 

### ISSUE THREAD

**Issue by sudharsanmit** [angular/material#6755] opened 2016-01-19 18:29 UTC
Pinned to #6725 . On request of asignee, splitting the issues into multiple tickets.
Standard Day Picker:

Issue 4:
Date can be selected through click of mouse only till Jul-13-2097. But keyboard can be used to select further dates.

**Comment by jelbourn** [comment] 2016-01-19 19:45
Dupe of #6397

**Closed by jelbourn** 2016-01-19 19:45 UTC

**Comment by sudharsanmit** [comment] 2016-01-19 20:21
Not a duplicate of #6397 which talks about minimum date. Read the issue fully. 
It has two parts -
1. It is not allowing date selection beyond Jul-13-2097 using mouse click - means, I scroll to Jul 2097 using Pagedown keys. When I hover on the dates of the month, only dates till Jul 13 are selectable. The further dates are readonly. Why?
2. But if I use arrow keys, I am able to select them.

See the difference between this and #6397?

I don't agree to this arbitrary closure. Kindly reopen. @ThomasBurleson
