### ISSUE TITLE
swipe(left/right): disables default swipe-down behavior in IE on WIN8 RT tablet

### ISSUE THREAD

**Issue by nenicmar** [angular/material#10526] opened 2017-03-23 10:42 UTC
**Actual Behavior**:
 -  `What is the issue?` 
when md-tab-content has defined md-swipe-left and right to swipe the tabs, swipe down gesture made on this md-tab-content element is not working to scroll down the page
 -  `What is the expected behavior?
when md-tab-content has defined md-swipe-left and right to swipe the tabs, swipe down gesture made on this md-tab-content element should still work as default behavior when you swipe down to scroll down the page

**AngularJS Versions**: *
 -  `AngularJS Version:` 
v1.5.5
 -  `AngularJS Material Version:`
v1.1.0

**Additional Information**:
 -  `Browser Type: Internet Explorer
 -  `Browser Version: 10
 -  `OS: WIN8 rt on Samsung ATIV

Tested on another tablets, Android/iOS, and working fine

**Comment by jelbourn** [comment] 2017-03-23 18:39
Also reported by internal Google teams.

**Comment by jelbourn** [comment] 2017-03-23 18:41
The issue is that the "swipe" directive always add `touch-action: none` to the element on which they're applied. Tabs use this to support switching between tabs by swiping left/right. However, this also blocks scrolling. The swiping directive should be configurable to allow specifying which kind of swipes it wants to grab. 

You should be able to see the issue in Chrome Dev tools (mobile device tools) by creating an instance of md-tabs that has long, scrolling content.

**Comment by Splaktar** [comment] 2018-09-10 23:16
This appears to have been fixed in PR https://github.com/angular/material/pull/10455.

**Closed by Splaktar** 2018-09-10 23:16 UTC
Labels: P3: important, browser: IE, has: Pull Request, needs: demo, reported by Googler, resolution: fixed, type: gestures
