### ISSUE TITLE
Tooltip:Bad Placement on button with fixed position

### ISSUE THREAD

**Issue by donnanicolas** [angular/material#2494] opened 2015-04-22 16:49 UTC
If the button is with `position: fixed;` then the tooltip will show in the initial position, even when scrolling

![screen shot 2015-04-22 at 13 40 02](https://cloud.githubusercontent.com/assets/1228656/7279874/793fc80a-e8f5-11e4-90b1-5cd3f0d7f936.png)
![screen shot 2015-04-22 at 13 40 11](https://cloud.githubusercontent.com/assets/1228656/7279875/79524656-e8f5-11e4-893e-94705362b1ec.png)

Tried to see if I could fix it, but didn't quite understood the code, sorry

**Comment by epelc** [comment] 2015-04-22 17:17
@donnanicolas I think it's caused by #2406

**Comment by naomiblack** [comment] 2015-09-04 22:17
Closing as dup of #2406. The fix for that will address this use case also.

**Closed by naomiblack** 2015-09-04 22:17 UTC
Labels: priority: medium, ui: layout
