### ISSUE TITLE
mdDialog is broken on 0.11 with ngAnimate 1.3.18 on Safari

### ISSUE THREAD

**Issue by websirnik** [angular/material#4497] opened 2015-09-08 22:10 UTC
Here is the codepen to test in Safari: http://codepen.io/anon/pen/GpJBej

**Comment by ThomasBurleson** [comment] 2015-09-08 22:29
Wish we had discovered this this morning....

**Comment by RolandHeath** [comment] 2015-09-09 02:26
On chrome 44 it will throw warnings (unable to find node md-dialog in element, angular.js:11707), but still work.
Could this be related to angular 1.4.5?

**Comment by ThomasBurleson** [comment] 2015-09-09 12:11
The warning is a separate logging issue. The mdDialog problems are caused by ngAnimate and [animateCss::maxParseTime( )](https://github.com/angular/material/blob/master/src/core/util/animation/animateCss.js#L317-L318) null reference errors. This will be fixed today and committed to master.

**Comment by ThomasBurleson** [comment] 2015-09-10 14:28
This is related to a logic issue with `$mdUtil.extractElementByName( )`

**Closed** 2015-09-10 14:35 UTC
Labels: browser: Safari, priority: critical, type: bug
