### ISSUE TITLE
md-tab/md-active - Active also the first `md-tab` - when switching from it

### ISSUE THREAD

**Issue by morwin10** [angular/material#7647] opened 2016-03-20 04:58 UTC
I have 2 `md-active` with conditioning that checks if `$location.hase()` is equal to 'signin' or 'signup' 
And according to it, is active the right tab

But it does not work well :
When I switch from `md-tab` **which is written first in the template**    -->   To the second `md-tab` :
It shows the two tabs

I made an example here:
http://run.plnkr.co/plunks/qCuOUOIC3sSOBFVcOIxN/#signin

http://plnkr.co/edit/qCuOUOIC3sSOBFVcOIxN?p=preview

And also gif that shows the problem:

![bandicam 2016-03-20 04-58-47-401](https://cloud.githubusercontent.com/assets/3899222/13902798/e6ed8b40-ee61-11e5-802d-cab6cf4c7c7c.gif)

PS
There is another small issue not related to the topic:
The height of the content changes when the mouse focused in a field

**Comment by topherfangio** [comment] 2016-03-24 19:12
@morwin10 I can definitely see the issue with the Plunkr you provided.

Is there any way that you can reproduce this in a more simple Codepen that doesn't use routes, but uses something like numbers/strings in the `md-active` expression? Or do you think it's a problem with using routes?

**Comment by morwin10** [comment] 2016-03-24 22:57
@topherfangio 
Yes you right. 
the problem is with `$location` service

I did it without using `$location` service
and it work :
http://plnkr.co/edit/O5DnWq?p=preview
http://run.plnkr.co/XoMeiN9v9pKJlmE4/#signup

and here is it with `$location` service : 
http://plnkr.co/edit/T7M2QkPdtrljs4WLsy6k?p=preview
http://run.plnkr.co/BdsCT23F0K3ZjFXb/

I don't know what the problem exactly with `location` service
But for now it works ..
thank you very much for the help  !

**Comment by morwin10** [comment] 2016-03-24 23:45
I don't think that's a problem with routes

I tested it now without route, and without `$location `service

And I used with `window.location` of JavaScript
And there's a strange problem:

Every time I swich from `#signup` to `#signin` it is not active the signin
But only if I do that again, it active the signin.

Here is another example
Clearer

http://plnkr.co/edit/T7M2QkPdtrljs4WLsy6k?p=preview

**Comment by topherfangio** [comment] 2016-03-25 19:31
Okay, so I did a bit of debugging, and it looks like the `location` variable is not updated when the `DialogController` is instantiated: http://plnkr.co/edit/K9xhMM1AU4wpRD6VWzS1?p=preview

Notice in the Plunkr how I add a `$timeout(..., 0)` to make the code run in the next digest loop. If you click the "Sign Up" button, let it open, close it then click the "Sign In" button, you'll notice that the initial `console.log()` incorrectly shows "signup" as the location, but the delayed log correctly shows "signin".

That said, there does still appear to be a height issue I'd love to track down. It seems that the Sign Up dialog always starts bigger and reduces it's size. That definitely seems odd.

**Comment by morwin10** [comment] 2016-03-27 06:54
thank you very much !
It helped me

I do not know what the solution for the height
But it has been solved in my
I do not know what exactly caused it
But I updated it here if you want to see
http://plnkr.co/edit/zAMH4cMGKPxI1DUOhqMx?p=preview
( There is a problem with the width of the input, but for some reason this does not happen in my project )

**Comment by morwin10** [comment] 2016-03-27 06:58
@topherfangio 
thank you very much !
It helped me

I do not know what the solution for the height
But it has been solved for me
I do not know what exactly caused it
But I updated it here if you want to see :
http://plnkr.co/edit/zAMH4cMGKPxI1DUOhqMx?p=preview
(There is a problem with the width of the input, but for some reason it doesn't happen in my project)

**Comment by topherfangio** [comment] 2016-04-04 20:41
Awesome! Glad you got it working!

**Closed by topherfangio** 2016-04-04 20:41 UTC
Labels: needs: investigation, P4 - Reported By or General PRs/Errors or Edge Cases
