### ISSUE TITLE
md-ink ripples display incorrectly on scrolled page

### ISSUE THREAD

**Issue by calebegg** [angular/material#2636] opened 2015-04-30 16:16 UTC
Demo here:

http://codepen.io/calebegg/pen/PqqmGJ

Steps:

1. Click on a button; notice the ripple starts from your mouse cursor
2. Scroll the page a bit (you might have to resize your browser if there aren't enough buttons)
3. Click on a button again. Notice that the ripple now starts from below the mouse cursor (offset by an amount approximately equal to the amount you scrolled).

This is pretty annoying on large pages, because eventually the ink doesn't show up for several seconds.

**Comment by ThomasBurleson** [comment] 2015-04-30 20:25
Also see Plunkr:  http://jsbin.com/dovecamoke/2/edit

**Comment by zzeng4** [comment] 2015-05-01 05:27
same problem here.

**Comment by amaddream** [comment] 2015-05-09 10:14
But this problem dosen't exist in the official website of Material Angular. <a>https://material.angularjs.org/#/demo/material.components.button</a>
Why?

**Comment by calebegg** [comment] 2015-05-11 16:33
The ripples probably work with md-content, but not other scrollable elements.

**Comment by ThomasBurleson** [comment] 2015-08-10 21:11
Depends upon #3952

**Comment by jofftiquez** [comment] 2015-08-26 08:50
Im still having this issue on the latest build I installed. How did you fix this? @calebegg Thanks.

**Comment by ThomasBurleson** [comment] 2015-08-26 10:51
@jofftiquez - can you provide a CodePen demonstrating this issue ?

**Comment by calebegg** [comment] 2015-08-26 14:32
@jofftiquez I did not change my codepen above.

**Comment by robertmesserle** [comment] 2015-08-26 17:16
What browser are you seeing this in?  I have not been able to recreate this with the latest code. (And the CodePen above seems to work for me in Chrome, Firefox, and Safari (on OS X).

**Comment by robertmesserle** [comment] 2015-10-14 08:48
Closing for now - please respond with steps to recreate (ie. browser and OS information) as I cannot reproduce.

**Closed by robertmesserle** 2015-10-14 08:48 UTC
Labels: for: internal contributor, priority: high, reported by Googler, summit

**Comment by luukdv** [comment] 2016-03-08 19:38
Steps to recreate:

```
<div md-ink-ripple ng-repeat="thing in things">
    <p>Button {{$index}}</p>
</div>
```

When tapping a div, ripples work as expected. Whenever you scroll the page, the ripples start too far below the button (as mentioned before: _offset by an amount approximately equal to the amount you scrolled_). I've provided a few debugged screenshots that might help to clarify (button 3 and 4 are tapped).

![before-scroll](https://cloud.githubusercontent.com/assets/5585947/13613709/93d45698-e56d-11e5-9b27-a649e53155bd.png)
![after-scroll](https://cloud.githubusercontent.com/assets/5585947/13613715/96597164-e56d-11e5-85d3-b5023bafa242.png)

Tested on:

- iPhone 5S (with iOS7)
- iPhone 6 (with iOS8)
- Samsung Galaxy S5 (Android 4.4)

- Angular version: 1.5.0
- Material version: 1.0.6

I can't reproduce the problem on desktop browsers.

**Comment by luukdv** [comment] 2016-04-01 12:15
@robertmesserle Do you have enough information or should I open a new issue for this?

**Comment by stephengardner** [comment] 2016-05-06 11:45
+1, not rippling for buttons when page ends up scrollable

**Comment by perry2of5** [comment] 2016-07-19 18:38
If I want ripples outside of md-content, it seems to work if I add position:relative to the element I'd like the ripple attached to in 1.0.9. I hope that helps someone.
