### ISSUE TITLE
md-chips and ng-change

### ISSUE THREAD

**Issue by xeor** [angular/material#3580] opened 2015-07-04 12:46 UTC
It looks like `md-chips` currently does not support `ng-change`, and it only have an attribute (`md-on-append`), to do something when a new item is added.

Either, `md-chips` needs support for `ng-change`, or it needs an `md-on-delete` attribute.
Now, it looks like the best way is to use `scope.$watchCollection` on the md-chip ng-model attribute to trigger what you want to do.

Old issue that kinda asks the same question: https://github.com/angular/material/issues/2259
Forumpost about the same: https://groups.google.com/forum/#!searchin/ngmaterial/ng-change/ngmaterial/AHB3LEMgudI/6TARclcvjYMJ

**Comment by chinnichaitanya** [comment] 2015-07-04 12:51
+1

**Comment by maku** [comment] 2015-07-04 15:33
+1

**Comment by victoryancn** [comment] 2015-07-05 17:11
+10086

**Comment by dmackerman** [comment] 2015-07-06 14:27
`md-on-append` works for when new chips are added, so seemingly just using a generic ngChange would make sense.

**Comment by coty-crg** [comment] 2015-07-21 19:22
+1, would make our lives a lot easier

**Comment by advancedits** [comment] 2015-07-31 01:19
+1

**Comment by typotter** [comment] 2015-08-10 16:33
duplicate of #3857

**Closed by typotter** 2015-08-10 16:33 UTC
Labels: needs: review

**Comment by vishal41190** [comment] 2015-10-15 22:02
+1

**Comment by erinjanae** [comment] 2015-11-10 23:14
+1

**Comment by Liam-Williams** [comment] 2015-11-17 03:24
+1

**Comment by omarjcamo** [comment] 2016-08-02 16:25
+1

**Comment by peter-imrich** [comment] 2016-08-09 09:02
+1

**Comment by vrgakos** [comment] 2016-08-20 16:44
+1

**Comment by VladimirMishyn** [comment] 2016-09-19 08:16
+1

**Comment by tejasrivastav** [comment] 2016-09-20 12:39
+1

**Comment by ycy233** [comment] 2017-02-22 09:55
+1

**Comment by bolau** [comment] 2017-11-27 00:48
md-on-add and md-on-remove work for me:
```
<md-chips ng-model="currentItem.tags" md-on-add="updateTags()" md-on-remove="updateTags()">
</md-chips>
```

**Comment by ibnYusrat** [comment] 2017-12-20 06:20
@bolau  That actually worked! :+1:  Thank you! :1st_place_medal:
