### ISSUE TITLE
mdDatepicker not updating ngModel $error when input updated with invalid date

### ISSUE THREAD

**Issue by rvarbanov** [angular/material#7850] opened 2016-04-01 21:36 UTC
Here is my CodePen demoing the issue:
[http://codepen.io/radi/pen/RaLLoW](http://codepen.io/radi/pen/RaLLoW)

When trying to use mdDatepicker with ngMessagess, you cannot really depend on it to show that the input date is invalid. `ng-message="valid"` will not always trigger if you input invalid date.

**Comment by ThomasBurleson** [comment] 2016-04-28 19:28
This issue is closed as part of our deprecation effort. 
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).

**Closed by ThomasBurleson** 2016-04-28 19:28 UTC

**Comment by rvarbanov** [comment] 2016-04-28 19:40
Wait, it is still an issue...

**Comment by noelmace** [comment] 2016-10-24 09:59
Possible reasons :
- Issue was filed a long time ago - **not in that case**
- Issue has a reasonable workaround - **maybe, but you should tell which one**
- Issue doesn't have a repro case available - **not in that case**
- Issue is real, but fixing it is risky for users who depend on existing behavior - **I don't think so**
- Issue is real, but only affects a very small use case - **ng-message is now used in a lot of projects, so, I don't think so**
- Issue is real, but would require significant work to fix, and is less urgent than other needs. - **maybe, but you should tell why**

"as part of our deprecation effort." I understand there is to many issues to work on given that you're a small team, but a little effort on explaining why you closed an issue in particular could, sometimes, be nice.

Seven months, and the issue is still here, without any explanation ...
