### ISSUE TITLE
mdSelect: Add select component

### ISSUE THREAD

**Issue by ajoslin** [angular/material#276] opened 2014-09-17 13:53 UTC
The mdSelect is a type of [Material Design Menu](https://www.google.com/design/spec/components/menus.html#menus-behavior) that behaves like and resembles a `<select>`. 

![Menu behavior](https://cloud.githubusercontent.com/assets/1045233/5574315/a7d21b66-8f70-11e4-8ec5-11f6793bd96e.png)

<h2>Functional requirements</h2>
 * Menu should be positioned over their "emitting" elements, establishing context
 * The selected menu item should not be shown as a duplicate when expanded
 * Dismiss menu by selecting an item (unless selecting multiple), tapping outside the menu, or using the Escape key
 * Menu animates out from emitting item when expanding

<h2>Accessibility requirements</h2>
 * **mdSelect element**
* `[aria-live="polite"]` makes sure selections are announced in a screen reader. Copy list item text to button only when selection is made with enter/space key, or click (not arrow keys). That way it won't read aloud twice.
 * **Button element**
* `[aria-haspopup="true"]` indicates button launches associated input
* `[aria-controls="_listID_"]` links button to options list
* Needs unique ID for pairing with list
 * **Unordered list**
* [`role="menu"`](http://www.w3.org/TR/wai-aria/roles#menu) to communicate purpose of list
* `aria-labelledby="_buttonID_"` to pair with button element
* `aria-expanded="true | false"` to indicate when associated panel is expanded
* Unique ID for pairing with button
* `tabindex="-1"`to script focus but remove from tab order
 * **Child list items**
* [`role="menuitem"`](http://www.w3.org/TR/wai-aria/roles#menuitem) on each child item
* `tabIndex="-1"` for scripting
 
<h2>Resources</h2>
 * [WAI-ARIA Listbox](http://www.w3.org/TR/wai-aria/roles#listbox)
 * [Using "listbox" and "option" roles vs. "menu" and "menuitem"](http://www.marcozehe.de/2014/03/11/easy-aria-tip-7-use-listbox-and-option-roles-when-constructing-autocomplete-lists/)

**Comment by wayou** [comment] 2015-01-02 08:40
+1 for md-dropdown and md-datetime

**Comment by sebastianhenneberg** [comment] 2015-01-03 18:38
+1

**Comment by nachoargentina** [comment] 2015-01-05 04:51
+1 for your work guys. This is a highly expected component since it's part of the base of components used in the majority of web applications. I was actually working on creating a web-app for my company with the library until I stumble accross this. Can't wait for it to be ready. Thanks again!

**Comment by dongmingliy** [comment] 2015-01-08 07:27
+1

**Comment by moeduffdude** [comment] 2015-01-08 13:48
+1

**Comment by nesteban-aldera** [comment] 2015-01-08 15:38
+1 this is highly expected for us too. Thanks for your great job !

**Comment by randallmeeker** [comment] 2015-01-08 16:22
- 1 
. . . . you know ... to take the pressure off the material peeps

**Comment by edotassi** [comment] 2015-01-08 17:12
+1

**Comment by mramanauskas** [comment] 2015-01-08 20:54
+1

**Comment by saramalla** [comment] 2015-01-10 08:05
+1 Eagerly waiting for this component. Awesome Job BTW!

**Comment by lievenjanssen** [comment] 2015-01-12 10:51
+1 for md-dropdown and md-datetime

**Comment by yarl** [comment] 2015-01-12 12:26
If you quickly need some solution for this, I've made for my purposes quick CSS styling for native `<input>`, you can find it [here](https://gist.github.com/yarl/b3d4b4114d82c8bb041d). Looks good on Chrome, IE10 (probably IE10+), probably Firefox 25+.

![Image](http://i.imgur.com/RVG2HG5.png)

**Comment by seiyria** [comment] 2015-01-12 14:00
Thanks for that @yarl -- it's better than having the default styling for sure!

**Comment by jadrake75** [comment] 2015-01-12 16:12
Thank you @yarl.  I do agree with @seiyria  that it is much better than default styling.  

Given all the silly +1 stuff, I am sure they are looking at.  I see one member asked about multi-select which I would like as well.  I like the way chosen/select2 place the selected items in a box that the use can remove with a click of the "X".  This is also similar to addresses on emails in gmail or outlook.

Another capability to consider is a clear button on the input.  This can be done easily enough as a separate button to trigger it, but and individual clear can be a nice feature.

**Comment by PaulMougel** [comment] 2015-01-12 20:40
@jadrake75 From what I understand, the angular-material team aims to implement the official Material spec (see [here](http://www.google.com/design/spec/components/chips.html) and [there](http://www.google.com/design/spec/components/text-fields.html#text-fields-auto-complete-text-field)). What you are describing will be implemented: the name of the feature you're interested in is chips, due for [0.9](https://github.com/angular/material/milestones/0.9.0) - see #1045
![image](https://cloud.githubusercontent.com/assets/1788596/5710497/e8a530aa-9aa2-11e4-859b-447125060ebc.png)

**Comment by m4cx** [comment] 2015-01-15 15:59
+1

**Comment by ajoslin** [comment] 2015-01-24 23:30
Here's a preview of progress.

What's done:

- Select databinding (multiple and single)
- Proper animations with edge cases (literal edge cases: edge of screen)
- Opening and closing programatically via service

http://ajoslin.co/17cMg

What's left:

- Creating a button for the normal case where he puts a select in his markup.
- Some polish

**Comment by seiyria** [comment] 2015-01-24 23:32
Looks very nice so far! I'm very excited to try this out!

**Comment by luclanet** [comment] 2015-01-24 23:34
Good work :)

**Comment by demisx** [comment] 2015-01-24 23:41
Awesome! This would be a long awaited child. Wish there was  a countdown on the Angular materials website for each of the new components. :)

**Comment by ThomasBurleson** [comment] 2015-01-25 00:47
@ajoslin  - noice!

**Comment by imjerryyang** [comment] 2015-01-25 04:13
Awesome job! Cant wait for the release! Big thanks @ajoslin

**Comment by moeduffdude** [comment] 2015-01-25 04:21
awesome work @ajoslin

i hope this lands before the end of January

**Comment by fundon** [comment] 2015-01-25 06:05
Cool!

**Comment by ilianaza** [comment] 2015-01-26 23:25
Looks great!

**Comment by ilanbiala** [comment] 2015-01-26 23:59
@ajoslin @ThomasBurleson just a suggestion, but I think you guys should start releasing 0.8.0-rc with incremental releases. As it is, most users are testing this out, so most people quickly update to the latest version. This would allow people to start playing around with mdSelect and any other already-fixed issues so that people can provide feedback. This way, 0.8.0 could be almost perfect and as free of little bugs as possible.

**Comment by JoeyHoutenbos** [comment] 2015-01-29 09:59
+1 Eagerly waiting for this component.
I also need a md-date and/or md-datetime component!

**Comment by gustavohenke** [comment] 2015-01-29 10:46
@JoeyHoutenbos about the date pickers, #648 had an extensive discussion about them

**Comment by sunnyshah01** [comment] 2015-01-29 19:49
+1

**Comment by sunnyshah01** [comment] 2015-01-30 07:47
@ajoslin I have used <b>md-select</b> from your branch <b>"wip-select-2"</b> and it works well on first time but it is not working when i clicked second time on the select area. can you provide some solution for that ?

**Comment by seiyria** [comment] 2015-01-30 13:02
I would wait until it's considered done before trying to report issues
against it.

**Comment by marcysutton** [comment] 2015-01-30 21:36
@sunnyshah01 the select is still a work-in-progress, hence the branch name including "wip". @ajoslin is still working on it but it should be ready soon. Until then, it doesn't make much sense to provide solutions for an API that is still in active development.

**Comment by ajoslin** [comment] 2015-01-31 19:45
@sunnyshah01 try the latest push.

I know of most of the current problems / missing features ... but if you find any that I miss, that makes me happy.

**Comment by ajoslin** [comment] 2015-01-31 21:17
@marcysutton so ... accessibility questions.

When there's an input element that opens up a select menu underneath it, I don't ever move focus away from the input element. This is good for the user's keyboard, but what's the best way to get a screenreader to announce the available choices in this case?

**Comment by marcysutton** [comment] 2015-01-31 21:32
In my prototype I sent focus to the selected item and immediately back to the button for two reasons: to get it to announce and to scroll the list of items from the keyboard. Otherwise we may be able to use aria-live. I'd have to experiment with it.

**Comment by ilanbiala** [comment] 2015-02-01 04:57
@ajoslin can you guys publish a 0.8.0-rc0 so we can start playing around with md-select and provide some feedback?

**Comment by sunnyshah01** [comment] 2015-02-02 11:29
@ajoslin  Thanks for md-select push. i have tried it and it works.

**Comment by gustavohenke** [comment] 2015-02-02 19:15
@ilanbiala I think this is only going to happen when all accessibility problems are gone.
For now, you can clone the repository, switch branches and build it locally

**Comment by ilanbiala** [comment] 2015-02-02 21:41
@gustavohenke the issue I have with not publishing is that it doesn't hurt. People are going to play around with it and report functionality bugs, but no one is going to implement it until 0.8.0 is formally released. So the accessibility issue seems pretty pointless and alphas or betas or rc's should really be published to get some feedback and prevent bugs in the real version.

**Comment by seiyria** [comment] 2015-02-02 21:48
@ilanbiala My problem with that is that they may have more work they want to do with the component before releasing it (ie, I bet @ajoslin knows all of the bugs in the implementation right now, if applicable). Releasing it would be an exercise in futility because all those bugs would get reported back in. There's no sense releasing something that's not yet ready for it yet.

We all want it, but I think it's not unwise to wait a bit longer for it to be functional and have all of the structural kinks worked out before releasing it to the masses.

**Comment by ThomasBurleson** [comment] 2015-02-02 21:56
@ilanbiala - Our master branch is a our internal development branch. If the component/source is in master but not yet released in a formal tag/release, then it should be considered still in `development` mode, You can report issues for these if really necessary/desired. 

>  Please note, however, that issue reports for **unreleased** features and/or components can be both superfluous and overwhelming to the team.

**Comment by ilanbiala** [comment] 2015-02-02 22:14
@seiyria A list of known issues would prevent duplicate issues and unnecessary submissions.

**Comment by ajoslin** [comment] 2015-02-02 23:22
I'm going to push what I have now to master tonight/tomorrow.

It's the complete Select, minus keyboard access, accessibility, and demos.

**Comment by luclanet** [comment] 2015-02-02 23:28
Yeah

**Comment by marcysutton** [comment] 2015-02-03 05:58
I think the downside is that people will use an inaccessible component. I don't think it should be in a release candidate without it. Not to mention release candidates are for more than just one component.

**Comment by ilanbiala** [comment] 2015-02-03 17:51
@marcysutton upgrading from whatever it will be called (alpha/beta/rc) to the official version will be pretty easy, and in any event whatever other dropdown I pick to use instead will also not be accessible (probably even less so), so whatever is built in is almost guaranteed to be much better than whatever else I will use in terms of accessibility.

**Comment by ilanbiala** [comment] 2015-02-05 01:28
@ajoslin select component doesn't seem to have made it into master yet. Can you also create a 0.8.0-alpha tag or beta so we can try it out more easily and give feedback?

**Comment by onerinas** [comment] 2015-02-08 10:37
@ajoslin is it available now? because i can't find it on materialjs demos nor in a repository search

**Comment by rryter** [comment] 2015-02-11 14:06
It seems that it was in master not quite a day and then it was removed again. 
Any new information on this? Thanks a lot!

**Comment by marcysutton** [comment] 2015-02-11 16:09
It is not ready, so we removed it from master ahead of the 0.8.0-rc1 release. It will be added back in as soon as we get it more stable.

**Comment by Jarlakxen** [comment] 2015-02-11 18:42
Hi! I think that i could be very useful to have a something like the ng-change in this component.

**Comment by fabioginzel** [comment] 2015-02-11 20:21
+1

**Comment by blarsen06** [comment] 2015-02-12 02:27
This plus multi select ++1

**Comment by gogromat** [comment] 2015-02-13 01:58
+1

**Comment by ask007java** [comment] 2015-02-13 17:13
+1

**Comment by ilanbiala** [comment] 2015-02-15 15:27
@marcysutton isn't an alpha/beta/rc the perfect place to have an almost completely functioning component and get the bugs out by releasing a few more rc's? When it was released initially I already reported 1 bug, and it was a quick fix that could have been merged in with 2-3 other fixes and another rc could have been released. Once 4-5 rc's were released, you guys could have been confident that there were few and possibly even no bugs and could have already started working on 0.8.1 or 0.9.0. I think the ngMaterial release system could be a lot better in terms of releasing more beta releases very frequently every few days and actually having no bugs in the real release 1-2 weeks later.

**Comment by marcysutton** [comment] 2015-02-15 16:44
@ilanbiala the component was not ready for public consumption but it will be out there soon. Please respect our process and release cycle, bossing us around doesn't get it done any faster.

**Comment by ilanbiala** [comment] 2015-02-15 17:54
@marcysutton The whole point of an alpha/beta/rc is that there are some kinks/bugs and it isn't ready for public consumption...

I wasn't bossing you around or disrespecting your release cycle, but I'm trying to give you some suggestions based on how the rest of the community does it. Take a look at AngularJS. The project consistently has new features and bug fixes in the rc releases for a new version (which may break and are probably not ready for public consumption in an enterprise environment). Take a look at Ember.js, which also has multiple rc releases and adds features, fixes bugs, and makes changes all while letting people use definitely not ready for public consumption code. Both extremely popular frameworks and they release multiple minor versions and test releases (Angular releases up to 20 minor releases and test releases each and Ember releases about 10 of each as well).

My whole point is that while the release process now is okay, it could be much better just by having more test releases to ensure the ones for public consumption don't have 100 issues and don't require as much code refactoring later on when it is much more challenging because multiple parts use the same helper. Even gradually getting to that point is fine, but just jumping from 0.7.1 to 0.8.0 with lots of bug fixes kind of defeats the purpose of semver. The beauty of `~0.7.0` means that I expect that version to become more stable as time goes on, but if the package only has `0.7.0` and `0.7.1` and the rest of the fixes go into `0.8.0`, that means now I have to take on other breaking changes just to get the fixes I expected to get in that version.

I'm not trying to be mean; I'm just trying to make ngMaterial better. I'm trying to give completely constructive feedback based on what big frameworks and commonly used packages do to avoid headaches and make development easier.

**Comment by bathos** [comment] 2015-02-15 20:22
@ilanbiala I'm excited about the just-around-the-corner maturity of this beautiful project too, but I do think it's wise not to release unfinished components, especially in this case. If I understand right, md-select it's not yet been made accessible. Let's say everything else is working, though. By its nature, many developers won't even realize that accessibility is absent, so I think the reasoning for holding off is sound: releasing superficially complete but as-yet inaccessible components for a ui system poised for widespread adoption could have a pernicious effect. I'm grateful this team has such high standards.

**Comment by demisx** [comment] 2015-02-15 21:07
It is team's sole decision whether or not a given component is ready to be released and tested by developers or not. There is a certain period in the project when the community feedback is certainly beneficial, but there are times when such feedback is just going to be a burdern, distracting the progress. I guess the `mdSelect` is in the latter phase right now and we need to respect the team's decision regardless how much we are eager to see this baby brought to the world.

**Comment by ilanbiala** [comment] 2015-02-15 21:59
@bathos If I use any other select right now it is inaccessible anyway, so it doesn't hurt by not using mdSelect.

@demisx that's completely fine, but my whole thing isn't just about a feature anyway. And mdSelect even without accessibility is probably more accessible than most other options, so it doesn't hurt...
> My whole point is that while the release process now is okay, it could be much better just by having more test releases to ensure the ones for public consumption don't have 100 issues and don't require as much code refactoring later on when it is much more challenging because multiple parts use the same helper. Even gradually getting to that point is fine, but just jumping from 0.7.1 to 0.8.0 with lots of bug fixes kind of defeats the purpose of semver. The beauty of ~0.7.0 is that I expect that version to become more stable as time goes on, but if the package only has 0.7.0 and 0.7.1 and the rest of the fixes go into 0.8.0, that means now I have to take on other breaking changes just to get the fixes I expected to get in that version.

**Comment by ThomasBurleson** [comment] 2015-02-16 00:49
@ilanbiala - I must insist that you relegate these types conversations to the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial). Our GitHub Issue board is intended for **bug** reports and **feature** requests.

**Comment by ilanbiala** [comment] 2015-02-16 02:00
@ThomasBurleson most companies block Google Groups and so that really doesn't make sense. Also, it splits the issues and requests and requires more maintenance.

**Comment by seiyria** [comment] 2015-02-16 02:03
@ilanbiala they're not asking if their process makes sense, they're asking you to take the discussion there and keep feature requests and bug reports here. This issue pertains exclusively to the mdSelect component, not about their development process or release cycle. Certainly they weren't asking whether or not it was more maintenance, either, as it's their project and they've chosen to manage it this way.

The least you could do is listen to them and stop notifying those of us who are simply waiting for the mdSelect component to get merged with your complaints about their project management style.

**Comment by movibe** [comment] 2015-02-16 09:39
+ 1

**Comment by robertmesserle** [comment] 2015-02-19 19:15
Landing in RC2, shipping later today :beers:

**Closed by robertmesserle** 2015-02-19 19:15 UTC
Labels: component, feature, in progress

**Comment by demisx** [comment] 2015-02-19 20:27
:+1: Canceling my date tonight.

**Comment by Splaktar** [comment] 2015-02-19 20:46
Woohoo! :key: feature! Thanks for all of the hard work.

**Comment by moeduffdude** [comment] 2015-02-20 05:22
thank you for all your hard work!
a congratulatory beer is in order, just stop by my tavern ;)

**Comment by kdela** [comment] 2015-02-20 07:28
Huh I've been waiting for this! Thank you guys! :)

**Comment by ThomasBurleson** [comment] 2015-02-20 10:56
This made me laugh.

On Thursday, February 19, 2015, Dmitri Moore <notifications@github.com>
wrote:

> [image: :+1:] Canceling my date tonight.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/angular/material/issues/276#issuecomment-75129192>.
>


-- 
*Thomas Burleson*
Mindspace LLC

http://www.gridlinked.info
http://www.linkedin/in/ThomasBurleson
https://github.com/ThomasBurleson

**Comment by soichih** [comment] 2015-02-20 21:48
I am playing with md-select on master. It looks great! I have couple of questions.

How can I get notified when user changes value? Is there an equivalent of select/ng-change? 

I tried to add <label> on top of md-select but it shows up below md-select for some reason. Is <label> not supported for md-select?

**Comment by artooro** [comment] 2015-02-20 21:51
@soichih you could use $watch https://docs.angularjs.org/api/ng/type/$rootScope.Scope#$watch

**Comment by marcysutton** [comment] 2015-02-20 21:52
Hello, this issue is now closed. Please use the [ngMaterial Forum](https://groups.google.com/forum/#!forum/ngmaterial) to ask questions. Thank you!

**Comment by DmitryEfimenko** [comment] 2015-02-20 21:53
Another bug on current master version;
Steps to reproduce:
* Place `md-select` inside a `md-dialog`
* Open dialog
* Open select
* Click somewhere outside the dialog to have it removed
* Observe select is still open in the middle of the screen

**Comment by adonix** [comment] 2015-02-21 06:46
@DmitryEfimenko I can confirm the same issue (same steps) but instead of md-dialog I'm using an angular modal.

**Comment by vivekimsit** [comment] 2015-03-20 11:11
Hi,

I am using md-select inside a div. The div expands / collapse on click but when I open the md-select dialog the div is expanded / collapsed too which is unwanted. How can I stop the click event to propagate from the md-select component?

Thanks!

**Comment by sagunpandey** [comment] 2015-06-14 05:42
Hi, 

While using name attribute with md-select, I get the error `Cannot read property '$name' of undefined`. Everything works fine if I remove the name attribute from md-select. But if I do that, I cannot use form validation as it requires the field to have the name attribute. Any help on this?

**Comment by Splaktar** [comment] 2015-06-20 16:17
@DmitryEfimenko @adonix please open a new bug. This issue is closed.

@vivekimsit Please ask those kinds of questions on the [forum](https://groups.google.com/forum/#!forum/ngmaterial). You should be able to add a `ng-click` to a `div` surrounding the `md-select` and under the expanding/collapsing `div` and in the `ng-click` just do `$event.stopPropagation()` to keep it from getting up to the expanding/collapsing `div`.

@sagunpandey Please ask those kinds of questions on the [forum](https://groups.google.com/forum/#!forum/ngmaterial).

**Comment by vectorderivative** [comment] 2015-08-07 01:47
So, what's the status of the multiple attribute?
It's not working.

**Comment by ajoslin** [comment] 2015-08-07 05:05
`md-multiple`

**Comment by vectorderivative** [comment] 2015-08-07 05:18
Oh... Docs lists it as just multiple.
Okay then. Thanks.
