### ISSUE TITLE
mdDialog issue when opening mdSelect 

### ISSUE THREAD

**Issue by prdn** [angular/material#2350] opened 2015-04-16 11:02 UTC
Hi everyone,

I got this problem when opening an mdSelect in an mdDialog.
Something is overriding the style of the dialog and I managed to solve this temporary with the css below
```
.dialog-subhd>div {
  overflow: initial !important;
  position: initial !important;
}
```
master
![schermata 2015-04-16 alle 11 58 18](https://cloud.githubusercontent.com/assets/3747053/7179491/4fb5bdc4-e430-11e4-86cf-fc59c932cd72.png)
with css hack
![schermata 2015-04-16 alle 11 58 02](https://cloud.githubusercontent.com/assets/3747053/7179492/533d9480-e430-11e4-8e80-ce5d9bd17ec4.png)

**Comment by ThomasBurleson** [comment] 2015-04-16 11:41
@prdn - Can you provide a CodePen or Plunkr that demonstrates this issue.

**Comment by Alexandre-io** [comment] 2015-04-16 12:38
Same issue. Here is the codepen:
http://codepen.io/Alexandre-io/pen/WbVWKP

**Comment by ThomasBurleson** [comment] 2015-04-16 16:03
@see https://github.com/angular/material/pull/2351

**Comment by moustacheful** [comment] 2015-04-17 00:45
Same issue here. Also I see there's a 24px padding top coming from `var computedStyle = $window.getComputedStyle(disableTarget[0]);` which seems to come from the md-content padding-top. 

So in addition to the above 'hack' adding a `padding-top: 0 !important` is necessary. 

Returning early in the disableScrollAround() function fixes this, but I'm unsure what this is used for. It doesn't seem like anything else besides `md-select` is using it.

**Comment by albertosantini** [comment] 2015-04-17 08:23
@moustacheful
> Returning early in the disableScrollAround() to disable this function fixes this, but I'm unsure what this is used for. It doesn't seem like anything else besides md-select is using it.

Agreed.

`disableParentScroll: false` in md-select (as stated in #2307) fixes the issue.

**Comment by alanpurple** [comment] 2015-04-17 08:31
same issue in my case...

**Comment by Alexandre-io** [comment] 2015-04-17 21:38
@rschmukler Hi, the commit ab0f67ce37cf7c937b60f12c599a90be6147c537 do not fix the issue :(

http://codepen.io/Alexandre-io/pen/WbVWKP

**Comment by albertosantini** [comment] 2015-04-17 22:05
I am afraid the issue is not fixed.
Please reopen it.

Here I experiment the same behavior described by @Alexandre-io codepen.
![select1](https://cloud.githubusercontent.com/assets/328179/7211754/98587db2-e55e-11e4-924b-342c7312275c.png)
![select2](https://cloud.githubusercontent.com/assets/328179/7211753/985804e0-e55e-11e4-8adc-c6939701c607.png)

**Comment by rschmukler** [comment] 2015-04-20 19:08
This is now fixed. See #2379 for further bug status on select.

**Closed by rschmukler** 2015-04-20 19:08 UTC
Labels: bug
