### ISSUE TITLE
datepicker: with UTC timezone set doesn't handle time offset +2:00

### ISSUE THREAD

**Issue by nicklastromb** [angular/material#12028] opened 2020-10-06 16:53 UTC
## Bug

# Demo and steps to reproduce the issue
1. [Demo page with user interaction](https://stackblitz.com/edit/angularjs-material-datepicker-bug-demo?file=app.js)
1. [Demo page during load](https://codepen.io/nicklastromb/pen/OJXLqeL?editable=true%3Dhttps%3A%2F%2Fmaterial.angularjs.org%2F)

#### Detailed Reproduction Steps (With user interaction)
1. Create a controller with a md-datepicker in the template
1. Set the `ng-model-options` to `{timezone:'UTC'}`
1. Load the view and open the datepicker. The date will be incorrectly displayed in the datepicker and the date will have an updated time offset.
1. The time for the date is now 00:00 (but with correct timezone) instead of the correct timezone adjustment

See demo url (1)

#### Detailed Reproduction Steps (Without interaction)

This step is a bit harder to reproduce as it seems to depend on what is loaded in the view. I've been able to reproduce this in the example for timezone settings at https://material.angularjs.org/latest/demo/datepicker, I've copied the demo to codepen where it seems to appear as long as the calendar is loaded together with the datepicker. I've also experienced this issue without any calendar being loaded in the view.

1. Create a view with a calendar and a datepicker component
1. Set the `ng-model-options` to `{timezone:'UTC'}`
1. Load the view, the datepicker timestamp should now be "00:00" instead of the correct offset

Any selection of a date will update the time offset properly.
Removing the calendar will prevent the problem from occurring. 

See demo url (2)

### Explain the expected behavior
Time for the date should not be affected when opening or loading the datepicker.

### Explain the current behavior
When setting an initial date the time part of the date will be affected when either opening up the datepicker and closing it or during the initial load of the datepicker in some scenarios. This is not expected bahavior.

### Discuss the use-case or motivation for changing the existing behavior

The current behavior is unexpected and may lead to an invalid date being selected when using the datepicker component.

### List the affected versions of AngularJS, Material, OS, and browsers

- AngularJS: 1.8.1, 1.8.0
- AngularJS Material: 1.2.1, 1.1.26
- OS: Windows 10
- Browsers: Chrome 85.0.4183.12
 
#### Screenshots

**When opening the datepicker**
![2020-10-06-184523-RiI1B7KOub](https://user-images.githubusercontent.com/39766853/95231949-25ae3f80-0804-11eb-9581-804573c7e32f.gif)

**During first load**

![2020-10-06-182557-chrome_jFJj1KV2jd](https://user-images.githubusercontent.com/39766853/95231250-3316fa00-0803-11eb-81fd-8614850f635f.png)

After a date is selected after first load the time offset is updated correctly

![image](https://user-images.githubusercontent.com/39766853/95232245-85a4e600-0804-11eb-99ed-b0b347027d60.png)

**Comment by nicklastromb** [comment] 2020-10-07 13:50
May have created a duplicate of #12026 if I understand that one correctly.

**Comment by Splaktar** [comment] 2020-10-10 23:16
> May have created a duplicate of #12026 if I understand that one correctly.

Thank you for this more detailed report. I still don't have enough information in that other issue to take any action.

I can't reproduce your report in the GMT-4:00 timezone, but I'll try doing some testing with GMT+2:00.

**Comment by Splaktar** [comment] 2020-10-10 23:25
OK, I can reproduce this in the GMT+2:00 timezone. Investigating...

**Comment by Splaktar** [comment] 2020-10-11 02:35
OK, I've got a fix for this in PR https://github.com/angular/material/pull/12030.

**Closed** 2020-10-12 17:34 UTC
Labels: P2: required, has: Pull Request, i18n: localization, type: bug
