### ISSUE TITLE
Feature Request - change FAB Toolbar and FAB Actions event mechanic

### ISSUE THREAD

**Issue by xBelphegorx** [angular/material#3344] opened 2015-06-18 12:29 UTC
What is needed: 
1. For FAB Toolbar there is needed change on open/close mechanics. There is needed new variable md-lock that for true will disable mouseenter/mouseleave events, and for false will enable this events.
2. Mandatory call close() method on blur for contoller mdFabSpeedDial/mdFabToolbar is bad idea. I mean that this event should depend on md-lock.

Why this is needed:
If we want FAB Toolbar to be always visible for some events/pages we can't do this in simple manner, but use some tricks and workarounds :( For better understanding what I mean:
http://plnkr.co/edit/smr3JDWXAtxApG5U67E7?p=preview

In this example I'm setting toolbar open when user is on top of page, but toolbar can hide when it's scrolled down. Now I have one more issue to workaround. When I click on button in toolbar and then this button looses focus (by clicking on element of page) toolbar will close even if he is on top of page.

**Comment by topherfangio** [comment] 2015-06-29 00:30
This is a duplicate of #3214, closing in favor of the one with more discussion. Please feel free to join in that conversation :-)

**Closed by topherfangio** 2015-06-29 00:30 UTC
