### ISSUE TITLE
md-tooltip positioning incorrectly when direction is changed

### ISSUE THREAD

**Issue by tyrdavis** [angular/material#10405] opened 2017-02-14 23:41 UTC
**Actual Behavior**:
 -  `What is the issue? *` md-tooltips in 1.1.3 do not appear in the correct position when the md-direction attribute is changed, after rolling over the tooltip at least once. It appears the edge of the tooltip being used to calculate the position is determined on first roll-over of the tooltip, and not updated if the direction is changed.
 -  `What is the expected behavior?` Tooltips should position themselves as they did in version 1.1.1.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` http://codepen.io/anon/pen/qRvEGw
 -  `Details:` Roll over the FAB with the radio set to "bottom", then switch the direction radio button to "left". The _top_ of the tooltip is aligned with the center of the FAB instead of the center of the right edge being aligned to the center of the FAB, as expected.

**Angular Versions**: *
 -  `Angular Version:` 1.5.5
 -  `Angular Material Version:` 1.1.3

**Additional Information**:
 -  `Browser Type: *` Chrome
 -  `Browser Version: *` 55.0.2883.87
 -  `OS: *` Windows 7
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by eqbalsajadi** [comment] 2017-03-06 14:58
+ also tooltips appear on right corner of window for RTL case

**Comment by zehavibarak** [comment] 2017-03-09 14:05
I experience this too when html dir is set to rtl. 
js does'nt assign 'left' as it does when dir attr is set to ltr.

**Comment by EdoMagen** [comment] 2017-04-05 15:41
+1

**Comment by molikh** [comment] 2017-04-10 05:20
+1

**Comment by AmirRaptoR** [comment] 2017-04-19 11:09
+1

**Comment by EdoMagen** [comment] 2017-04-24 20:01
Ok so we ended up building our own.

**Comment by oliversalzburg** [comment] 2017-05-09 10:17
It seems to me like tooltip positioning is completely unreliable once you put multiple tooltips on the same page. We see completely misaligned tooltips on successive hover actions without changing direction.

**Comment by eladh** [comment] 2017-05-28 13:23
hi @eqbalsajadi ,

its seems like the problem is in the _reverseXPosition() - when the position is center its return undef and that cause the tooltip to be position wrongly.
in this case this function should return the position 


```
MdPanelPosition.prototype._reverseXPosition = function(position) {
  if (position === MdPanelPosition.xPosition.CENTER) {
    return;
  }

  var start = 'start';
  var end = 'end';

```

proposed solution:
```
MdPanelPosition.prototype._reverseXPosition = function(position) {
  if (position === MdPanelPosition.xPosition.CENTER) {
    return position;
  }
  var start = 'start';
  var end = 'end';
```

**Comment by eqbalsajadi** [comment] 2017-07-07 08:38
@eladh hi,

I'm moving to material2 right now
hope to not have such probs in material2

**Comment by oliversalzburg** [comment] 2017-07-07 08:42
> hope to not have such probs in material2
#goodluckwiththat ;D

**Comment by eqbalsajadi** [comment] 2017-07-07 09:02
@oliversalzburg Thanks

**Comment by AjawadMahmoud** [comment] 2017-11-11 06:48
Are we seeing this bug taken into consideration?

**Comment by oliversalzburg** [comment] 2018-01-22 19:22
I think I know why this happens. Working on a fix.

**Closed** 2018-02-06 16:25 UTC
Labels: P2: required, has: Pull Request, severity: regression, type: bug
