### ISSUE TITLE
Add private prefix for CSS classes not intended for general use

### ISSUE THREAD

**Issue by calebegg** [angular/material#4718] opened 2015-09-18 21:31 UTC
It would be nice if some CSS classes used some sort of common prefix to indicate that they are "private", similar to how Angular uses $$ as a prefix for private members of angular, $scope, etc. When I look at examples in the inspector, it's not always clear if a specific CSS class is supposed to be for general consumption or to only appear in code generated by a directive (for example, `md-no-style` on list item buttons, which is usable (and useful! see also #2839) outside of generated code, but never appears in documentation or examples as far as I can tell).

Hand in hand with this, I think, would be a commitment to not significantly break the "public" CSS classes within a release.

Perhaps private classes could use two hyphens as in `md--generated-only`.

/cc @naomiblack

**Comment by jelbourn** [comment] 2015-09-22 22:09
Our plan for this is to explicitly document the CSS classes that are part of the public API for a component. Anything not documented this way would be considered private. 

At this point, the vast majority of classes, being undocumented, are private until the stabilization of v1.0. Going to close this for now as a dupe of #594

**Closed by jelbourn** 2015-09-22 22:09 UTC
Labels: reported by Googler
