### ISSUE TITLE
md-subheader

### ISSUE THREAD

**Issue by srinathvsp** [angular/material#1806] opened 2015-03-06 11:39 UTC
hi i have inside md-content subheader sections when i scroll layout moving subheader and stoping on top means above the toolbar wts the mistake pls let me know .. working properly in apple devices but not working android devices

**Comment by jelbourn** [comment] 2015-09-29 17:46
Closing this as "cannot reproduce" / "need more information". Feel free to re-open if you can provide more details.

**Closed by jelbourn** 2015-09-29 17:46 UTC
Labels: browser: Android, needs: investigation
