### ISSUE TITLE
md-select closes immediately in iOS when added to home screen

### ISSUE THREAD

**Issue by hodeyp** [angular/material#4296] opened 2015-08-23 10:20 UTC
When an app is added to the iOS home screen, md-selects close immediately when clicked. This behaviour is not present when the app is run from within iOS Safari itself. Also md-menu items remain open correctly.

**Comment by rschmukler** [comment] 2015-09-21 22:55
@hodeyp how are you adding it to the homescreen? Via safari or as part of a build tool like Phone Gap? If the former, can you confirm this on iOS 9?

**Comment by hodeyp** [comment] 2015-09-22 06:21
I am adding via safari on iOS 9

**Comment by helzgate** [comment] 2015-09-22 20:56
Not working on iOS 8.4.1 either along with cordova 5.3.1 and manually building with cordova cli.

**Comment by rschmukler** [comment] 2015-09-24 22:32
@hodeyp I'm having trouble reproducing this issue with just adding it via home screen. I added both our demo site and [this codepen](http://s.codepen.io/rschmukler/debug/gawZmy?) and they both worked. Can you try using the codepen above and confirm that the issue doesn't happen for you then?

**Comment by helzgate** [comment] 2015-09-25 15:20
I loaded your codepen code into a fresh cordova template using cordova 5.3.1.  I built it and ran it on a iOS simulator iPhone 6 8.4 and it does the same thing, menu disappears without touching it.  Same occurred when i deployed your code to a physical iPhone 5, 8.4.1

**Comment by helzgate** [comment] 2015-09-25 15:27
I upgraded to Cordova 5.3.3 and reinstalled the ios platform then rebuilt the app and redeployed and had same issues as above.

**Comment by helzgate** [comment] 2015-09-25 15:37
I sent you my git archive if it helps.

**Comment by mighe** [comment] 2015-09-28 13:40
I have the same problem as well.

It seems somehow related to 
```
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
```

Without them "add to homescreen" just creates a bookmark that will be opened in safari, with those tags safari shows something different and the select is closed immediately.
If you hold your finger for a while the "magnifier lens" is displayed and the select behaves correctly.
Not only: in "inspect element" mode everything is fine after selecting something (does not matter what).

My project is a simple html5 page, not a cordova app

**Comment by mighe** [comment] 2015-09-29 13:13
#4757 and #4850 are the same issue

i dug around a bit
* safari under iOS does not have this problem
* add to home screen shows this in a consistent way but only with some kind of app configuration (in my case it happens always, I'm still trying to figure out which js/tags are the cause)
* chrome under iOS has this problem always

The problem seems to be that [this event handler](https://github.com/angular/material/blob/master/src/components/select/select.js#L1035) `dropDown.on('mouseup', checkCloseMenu);` is attached before `mouseup` is managed. So we have

click -> event handler attached -> mouseup -> select closed

It is possible that the actual sequence is somehow different, it is still unclear to me what happen under the hood in this specific case and I'm not able to find a real solution (my js-fu is not so great :smile: ).

Anyway for the ones who need a quick-and-dirty way to ship their app now, just change around [here](https://github.com/angular/material/blob/master/src/components/select/select.js#L301) every `element.off('click')` and `element.on('click')` with `mouseup`.
It makes the select work, but it slightly changes it behaviour because it will open the select even if the `mousedown` event is generated somewhere else.

I hope this helps

**Comment by helzgate** [comment] 2015-09-30 14:28
I found the workaround.  If i add jquery it works.  If i remove jquery it breaks but nothing in the material docs says jquery is required!  Unfortunately when i add jquery my click responses in all areas of my app are super slow and it makes my app appear sluggish, when i remove jquery everything is super snappy so i don't want to use jquery!!!!  This is the second project i've been bitten on with jquery and angular not playing nice.

**Comment by helzgate** [comment] 2015-09-30 15:08
Adding angular-touch to my project sped up my mouse clicks so everything is working 100% now.

**Comment by patrickmichalina** [comment] 2015-10-13 17:22
I have the same exact issue using iOS 9. Browser works fine but in standalone (app saved to home screen) the md-select flickers and closes immediately. If I double tap quickly it works..

**Comment by barryvdh** [comment] 2015-10-14 09:53
Can confirm with https://material.angularjs.org/0.11.4/demo/select on the Chrome app on iOS.
Codepen: http://codepen.io/barryvdh/full/pjWgbd
Codepen example also shows the problem when you add it to the homescreen (because it's webapp-capable)

If I look closely, it seems to click on the item that is below my finger. So it counts the 'tap' 2 times, first to open it, but then uses the same tap to select an item from the list.

It worked before, perhaps there was a delay before?

Demo:
 - Show working in Safari
 - Add to homescreen (and web-app capable)
 - Doesn't work there

![material select](https://cloud.githubusercontent.com/assets/973269/10480350/0ce2d482-726a-11e5-8685-c102ce84cee6.gif)

**Comment by barryvdh** [comment] 2015-10-19 08:06
Seems to be fixed by https://github.com/angular/material/commit/7251684315bcc65fcd7599ac88f84dcf51a2a219

**Comment by ThomasBurleson** [comment] 2015-10-19 12:00
Fixed

**Closed by ThomasBurleson** 2015-10-19 12:00 UTC
Labels: browser: iOS, priority: medium, severity: critical

**Comment by sombriks** [comment] 2015-10-19 15:39
Tested on https://material.angularjs.org/0.12.0-rc1/, it's working on ipad2/chrome now
