### ISSUE TITLE
md-autocomplete with placeholder tries to download md-close.svg

### ISSUE THREAD

**Issue by Murarz208** [angular/material#5513] opened 2015-11-03 09:11 UTC
In v1.0.0-rc2 when you define autocomplete like this:
```javascript
<md-autocomplete 
    md-no-cache="true"
    md-selected-item="selectedItem"
    md-search-text="searchText"
        md-items="item in querySearch(searchText)"
    md-item-text="item.name"
    placeholder="Favorite state">
    <span md-highlight-text="searchText">{{item.name}}</span>
</md-autocomplete>
```
It will try to download `md-close.svg` from server. In my case this will cause an error, because this .svg file doesn't exist. Everythig works fine if I replace `placeholder` with `md-floating-label`.
Removing place holder won't resolve issue (autocomplete still tries to download file).

**Comment by robertmesserle** [comment] 2015-11-11 21:44
@ThomasBurleson Is this a bug in `md-icon`?  It shouldn't ever be hitting the server for this, should it?

**Comment by jelbourn** [comment] 2015-11-30 23:14
@Murarz208 I can't reproduce this issue, so I'm closing it for now. 

If you are still experiencing this, can you give more details as to your setup? Or, even better, reproduce in a CodePen (or similar).

**Closed by jelbourn** 2015-11-30 23:14 UTC
Labels: priority: high

**Comment by Murarz208** [comment] 2015-12-30 16:39
Ok this whole issue was my fault. I added interceptor to `$httpProvider`, which changes names of loaded sources (also icons). So when angular tried to load `md-close.svg` my interceptor added slash at the begging of the filename `\md-close.svg` and this new filename was absent in `$templateCache`. Sorry for situation, thanks for help though!
