### ISSUE TITLE
mdToolbar: usage of ngIf on mdToolbar makes hiding delayed

### ISSUE THREAD

**Issue by montgomery1944** [angular/material#7769] opened 2016-03-27 13:43 UTC
When hiding mdToolbar using ngIf, the element is removed from DOM tree with a significant delay. The same issue does not occur, when the mdToolbar is wrapped in div and the ngIf is moved to it.

Demo can be found at http://codepen.io/anon/pen/NNgyvz.

Tested with jQuery 2.2.2, Angular 1.5.2 and Angular Material 1.1.0-rc1.

I can provide a pull request with fixes for this issue, including tests, if this is going to help.

**Comment by trimox** [comment] 2016-03-29 17:39
Confirmed this issue as well. Works in 1.0.4, it's been broken since.

**Comment by DevVersion** [comment] 2016-04-24 12:43
Duplicate of #7929. Fix is pending in #8190

**Closed by DevVersion** 2016-04-24 12:43 UTC
