### ISSUE TITLE
Text does not appear in bubble of chip

### ISSUE THREAD

**Issue by futurechan** [angular/material#2080] opened 2015-03-30 02:14 UTC
![image](https://cloud.githubusercontent.com/assets/3921584/6889274/94c5d8e4-d658-11e4-8521-5b2c5430bc7f.png)

**Comment by MilosStanic** [comment] 2015-03-30 09:30
Same for me here. Plus the 'X' button is huge!

**Comment by ThomasBurleson** [comment] 2015-03-31 03:54
Which os, browser, and version?

**Comment by futurechan** [comment] 2015-03-31 16:44
Windows 7, Chrome, latest?

**Comment by marcysutton** [comment] 2015-03-31 21:58
This is a duplicate of https://github.com/angular/material/issues/2081, which has more details.

**Closed by marcysutton** 2015-03-31 21:58 UTC
Labels: question
