### ISSUE TITLE
md-select mapFn undefined

### ISSUE THREAD

**Issue by wwhurley** [angular/material#6204] opened 2015-12-09 19:15 UTC
In some cases the `mapFn` variable is undefined. This leads to errors like:

```
TypeError: undefined is not a function
    at Array.map (native)
    at Object.SelectMenuController.self.selectedLabels (http://localhost:9001/vendor/js/angular-material/angular-material.js:13780:34)
    at Scope.$digest (http://localhost:9001/vendor/js/angular/angular.js:15888:40)
    at Scope.$apply (http://localhost:9001/vendor/js/angular/angular.js:16160:24)
    at HTMLElement.clickListener (http://localhost:9001/vendor/js/angular-material/angular-material.js:13648:13)
    at HTMLElement.jQuery.event.dispatch (http://localhost:9001/vendor/js/jquery/jquery.js:4435:9)
    at HTMLElement.elemData.handle (http://localhost:9001/vendor/js/jquery/jquery.js:4121:28)
```

It appears to be caused by https://github.com/angular/material/commit/f73e5033bd4446412ca6b5ce7a769901274f4147#diff-d7b463f733c2e3fbc783f38073561b74R632 when `mode` is equal to `display`

**Comment by zainul-realtime** [comment] 2015-12-10 07:39
yeah i have some issue like this , hopefully to be fixed

**Comment by jakubweber** [comment] 2015-12-10 10:12
Same here, need to be fixed

**Comment by sebastiengiroux** [comment] 2015-12-15 20:00
I have the same problem

**Comment by AquariusFR** [comment] 2015-12-18 09:45
Same here, any clues ?

**Comment by suur** [comment] 2015-12-21 12:59
It appears the ```opts``` in ```self.selectedLabels = function(opts) {``` sometimes has the controller scope in it's prototype so ```opts.mode``` is equal to ```$scope.mode```.

A temporary workaround for this would be not to use ```mode``` in scope.

**Comment by nicky-lenaers** [comment] 2016-01-04 16:21
Same issue, needs to be fixed.

**Comment by nicky-lenaers** [comment] 2016-01-06 09:38
For anyone still having this problem, I found it occurs when using ``value=""`` instead of ``ng-value=""``. Hopefully this helps some of you!

**Comment by nicky-lenaers** [comment] 2016-01-06 11:19
Right solution by @suur confirmed working, thanks a lot!

**Comment by mzaarour** [comment] 2016-03-07 16:58
Please patch this bug !!

**Comment by zainul-realtime** [comment] 2016-03-08 01:45
solution is don't use $scope.mode change to another name

**Comment by mzaarour** [comment] 2016-03-10 16:19
Thank you. 
It works when avoid using $scope.mode principaly in a whole app controller. 
However a patch will be welcome

**Comment by darkmavis1980** [comment] 2016-03-14 13:04
+1 same issue here

**Comment by omer123456** [comment] 2016-03-17 11:01
replace `scope.$watch(selectMenuCtrl.selectedLabels, syncLabelText);`
with:

```
scope.$watch(function() { // replaced
        return selectMenuCtrl.selectedLabels();
      }, syncLabelText); 
```

**Comment by fkpwolf** [comment] 2016-04-06 09:21
+1 spend lots of time to find root cause.

**Comment by misherone** [comment] 2016-04-08 10:20
Had $scope.mode in my controller. Thanks suur for your help. Waiting for better incapsulation...

**Comment by DevVersion** [comment] 2016-04-08 13:51
This is a duplicate of #6260, which already has a PR fixing - #7830. 

I will close that issue, because the other issue, is already referenced by the PR.

**Closed by DevVersion** 2016-04-08 13:51 UTC
Labels: P1 - Broken Renders / Major Use Cases
