### ISSUE TITLE
md-datepicker incorrect date validation due by format

### ISSUE THREAD

**Issue by alexpozzani** [angular/material#5135] opened 2015-10-13 15:04 UTC
For regions where the date format is different from "mm/dd/yyyy", when the date is manually typed in the field, the value check is done incorrectly.
For example, here in Brazil where default date format is "dd/mm/yyyy", using the demo site, when we manually inform "28/10/2015", the date is not validated. But when we type in the format "mm/dd/yyyy" (10/28/2015), the date is validated and the value is replicated to the other fields.
I've tried to use $mdDateLocaleProvider with correct configurations, but also didn't work.

See this screenshots...
Default values accessing page:
![defaultvalues](https://cloud.githubusercontent.com/assets/3027167/10458671/515982e6-71a2-11e5-8086-769ee2faacdf.png)

After inform date in "dd/mm/yyyy" format:
![28102015](https://cloud.githubusercontent.com/assets/3027167/10458688/64fc2f74-71a2-11e5-8258-424d78d53dd4.png)

After inform date in "mm/dd/yyyy" format:
![10282015](https://cloud.githubusercontent.com/assets/3027167/10458692/7184bda6-71a2-11e5-86e1-e019d84b2c77.png)

**Comment by sturay** [comment] 2015-10-22 13:03
Having exactly the same issue in the UK where we have the same format as you guys in Brazil. This has the unfortunate effect of making our tests fail as there is no way of programatically opening the date pop-up and selecting a date from there that we are aware of. Bizarrely though, when a number greater than 9 is input into the first (mm) field, it appears to accept that as a day and switches there values accordingly.

Being as the expected date input is in dd/mm/yyyy format, the mm/dd/yyyy format always fails.

**Comment by guilhermecvm** [comment] 2015-11-01 15:09
Same problem #5478

**Comment by jelbourn** [comment] 2015-11-02 19:15
Dupe of #4671

**Closed by jelbourn** 2015-11-02 19:15 UTC
