### ISSUE TITLE
Scrolling bug in sidenav

### ISSUE THREAD

**Issue by nivanson** [angular/material#2354] opened 2015-04-16 13:10 UTC
Hi!

This is about a scrolling bug I found in the docs.

You can see how the sidenav is scrolled to the bottom but there are more things below. I should not have reached the bottom.

I can reproduce this behavior on Mac OS X 10.10.3 by opening angular.material.org and clicking "Directives" in the main menu and then trying to scroll to the bottom in the sidenav.

Screenshots for Mac OS X supplied for versions
![Chrome 41.0.2272.118](https://cloud.githubusercontent.com/assets/64952/7181379/971da392-e44a-11e4-8925-6545187485ed.png)
![Safari 8.0.5](https://cloud.githubusercontent.com/assets/64952/7181380/9720c932-e44a-11e4-9f24-542e13b2170c.png)

Co-worker confirms it's the same on Windows with both Chrome and IE

**Comment by ThomasBurleson** [comment] 2015-04-16 15:55
Duplicate of #2347

**Closed by ThomasBurleson** 2015-04-16 15:55 UTC
