### ISSUE TITLE
layout-padding affecting md-icon positioning in an md-button

### ISSUE THREAD

**Issue by aproxs** [angular/material#8160] opened 2016-04-21 16:17 UTC
This issue has been present since 1.0.6 (1.0.5 doesn't repro the issue)

This little snippet reproduces the issue (verified in codepen):
```
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<div layout-padding flex>
  <md-button class="md-fab md-accent md-mini md-fab-top-right" href="/somewhere">
    <md-tooltip md-direction="left">My Tooltip!</md-tooltip>
    <md-icon>add</md-icon>
  </md-button>
  <div>
    <md-button class="md-fab md-accent md-mini md-fab-top-left" href="/somewhere">
      <md-tooltip md-direction="left">Another Tooltip</md-tooltip>
      <md-icon>add</md-icon>
    </md-button>
  <div>
<div>
```
The first button in the snippet is the repro of the issue and the second button is the workaround that I am currently using.

For some reason, the element rendered for the md-button is getting some additional css applied to it that modifies the padding, and causes the icon to be displaced down.

These are the two selectors that are manipulating the elment's css:
```
8px -- .layout-padding, .layout-padding-gt-sm, .layout-padding-gt-sm>*, .layout-padding-md, .layout-padding-md>*, .layout-padding>*, .layout-padding>.flex, .layout-padding>.flex-gt-sm, .layout-padding>.flex-md
```
```
0px -- .md-button
```
On the second button, which is simply surrounded by a div, the icon is properly aligned and there is only one selector associated with the "padding-top/bottom" properties, the .md-button.

**Comment by ThomasBurleson** [comment] 2016-04-21 18:44
Closing this issue due to insufficient information. Please resubmit with:

----
Required
----

**Behavior**:
-  What is the issue? * 
-  What is the expected behavior? 

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue :
-  Details: 

**Angular Versions**: *
-  Angular Version: 
-  Angular Material Version: 

**Additional Information**:
-  Browser Type: *
-  Browser Version: *
-  OS: *
-  Stack Traces: 

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

**Closed** 2016-04-21 18:45 UTC
Labels: needs: demo

**Comment by aproxs** [comment] 2016-04-22 14:24
@ThomasBurleson, here you have the information in the format you ask. Please let me know if you want me to open a new issue instead.

**Behavior:**
- What is the issue?
<img width="90" alt="screen shot 2016-04-22 at 07 12 03" src="https://cloud.githubusercontent.com/assets/1939830/14744050/cae1e4ca-0859-11e6-8614-8ee045e11589.png">

- What is the expected behavior?
<img width="62" alt="screen shot 2016-04-22 at 07 12 09" src="https://cloud.githubusercontent.com/assets/1939830/14744057/d2e7c1d0-0859-11e6-8ab9-fa7674962c60.png">

**CodePen and steps:**
- CodePen Demo which shows the issue: http://codepen.io/aproxs/pen/bpjobY
- Details:
The codepen shows two buttons with a "+" icon, one with the issue (top-right) and one with the workaround (top-left).
Please take a look at the first post for detailed information on what I think is going on.

**Angular Versions:**
- Angular Version: 1.5.3
- Angular Material Version: >1.0.6
- Additional Information:

**Browser Type:**
- Browser Version: Google Chrome  49.0.2623.112 (64-bit)
- OS: OSX 10.11.3
- Stack Traces: -
