### ISSUE TITLE
md-datepicker not opening on selected date when using date range attributes

### ISSUE THREAD

**Issue by Stephn-R** [angular/material#10542] opened 2017-03-29 14:21 UTC
**Actual Behavior**:
 -  `What is the issue? *`

> The `<md-datepicker/>` component does not open the picker at the current date selected when using the `md-min-date` attribute.

 -  `What is the expected behavior?`

> It should automatically focus on the currently selected date when opening to select another date.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`

> https://codepen.io/anon/pen/xqyvBp

 -  `Details:`

**AngularJS Versions**: *
 -  `AngularJS Version:` 1.3.15
 -  `AngularJS Material Version:` 1.1.3

**Additional Information**:
 -  `Browser Type: *` Chrome
 -  `Browser Version: *` 56.0.2924.87
 -  `OS: *` Windows
 -  `Stack Traces:` No Stack Errors shown

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by sdesmond** [comment] 2017-04-07 19:52
Looks like a duplicate of #9952 and #10209 and others.

**Comment by Splaktar** [comment] 2018-01-11 09:09
Also a duplicate of https://github.com/angular/material/issues/10144. Fixed in 1.1.5.

**Closed by Splaktar** 2018-01-11 09:09 UTC
