### ISSUE TITLE
Angular Material doesn't work with Angularjs version > 3.1.15

### ISSUE THREAD

**Issue by tsdragon0404** [angular/material#3778] opened 2015-07-17 03:59 UTC
When I update version of Angularjs, I have a bug with backdrop.
https://material.angularjs.org/0.10.1-rc2/#/demo/material.components.select
Use "Edit on CodePen" then change version of Angularjs to 3.1.16 or later.
- Click open menu -> then click out site of menu -> menu closed.
- Click open menu again -> the screen is locked.

**Comment by ThomasBurleson** [comment] 2015-07-17 04:07
Duplicate of https://github.com/angular/material/issues/3704

**Closed by ThomasBurleson** 2015-07-17 04:07 UTC
