### ISSUE TITLE
sidenav: when opened, mobile screen is rumpled

### ISSUE THREAD

**Issue by hagfish1210** [angular/material#9348] opened 2016-08-19 04:54 UTC
**Actual Behavior**:
-  `What is the issue?` md-sidenav doesn't work normally.
-  `What is the expected behavior?` right md-sidenav have to be opened smoothly. without screen abnormality

< problem image >
![md-sidenav](https://cloud.githubusercontent.com/assets/13121801/17799289/69aee306-6614-11e6-8ed9-f2319a9f8cda.jpg)

**CodePen** (or steps to reproduce the issue): *
-  `CodePen Demo which shows your issue:` http://codepen.io/hagfish1210/pen/WxWomk
-  `Details:` not totally same with the problem, but similar movement.

**Angular Versions**: *
-  `Angular Version:` 1.5.8
-  `Angular Material Version:` 1.0.9

**Additional Information**:
-  `Browser Type:` chrome
-  `Browser Version:` 52.0.2743.116 (64-bit)
-  `OS:` ubuntu 14.04lts
-  `Stack Traces:`

**Comment by ThomasBurleson** [comment] 2016-08-22 15:27
This will be fixed with the SideNav re-implementation using `$mdPanel`.

**Comment by clshortfuse** [comment] 2016-10-14 01:00
I took the supplied codepen and noticed the CSS was causing issues with the layout. I believe that was the issue and you can the modified I made to fix it here: http://codepen.io/shortfuse/pen/ALgEdb

If in fact there is an animation issue, I couldn't reproduce it with the supplied codepen. Regardless,  #9833 might solve the animation issue.

**Comment by yeager-j** [comment] 2016-10-24 00:07
I have this issue as well. Solution posted by @clshortfuse has not fixed the problem.

**Comment by rollermy** [comment] 2017-06-26 22:20
Any update on this? I have this issue too

**Comment by johnmc5810** [comment] 2017-09-26 18:51
Have this issue too, any work arounds available?

**Comment by rollermy** [comment] 2017-09-28 13:10
I disabled the animation. I decided to not use the right nav in the end, but i think this worked:
```
.right-nav {
  -webkit-transition: none !important;
  transition: none !important;
}
```

**Comment by Splaktar** [comment] 2019-03-28 05:28
The URLs for the images used in the demo reproductions are now 404s. I can't reproduce this given the provided information. If this is still an issue for you, please open a new issue with an updated CodePen reproduction and link to this issue.

**Closed by Splaktar** 2019-03-28 05:28 UTC
Labels: resolution: can't reproduce
