### ISSUE TITLE
calendar: doesn't handle timezone from ng-model-options

### ISSUE THREAD

**Issue by simonered** [angular/material#10431] opened 2017-02-22 10:30 UTC
**Actual Behavior**:
 -  `What is the issue? *` The timezone is not considered: date is always returned with current timezone at midnight
 -  `What is the expected behavior?`The return date is with selected timezone

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` [http://codepen.io/simonered/pen/KWPgNx](http://codepen.io/simonered/pen/KWPgNx)
 -  `Details:` Select the same date both with calendar and datepicker and see the results

**Angular Versions**: *
 -  `Angular Version:` 1.6.2
 -  `Angular Material Version:` 1.1.3

**Additional Information**:
 -  `Browser Type: *` Indifferent
 -  `Browser Version: *` 
 -  `OS: *`
 -  `Stack Traces:`

**Comment by rivertam** [comment] 2017-03-28 19:12
This is a huge issue for our application, and I don't know any workaround besides "don't use angular-md". I don't expect it to get fixed, though, considering the bug is probably considered something of a "feature" at this point. Would break old applications that rely on the bug...

**Comment by simonered** [comment] 2017-03-29 11:57
I ended up writing a custom directive amending the returned date, to use "near" md-calendar. It's a workaround, but I think the bug should be fixed.

```
myApp.directive('tzDate', function($parse) {
	  return {
	    restrict: 'A',
	    require: 'ngModel', 
	    link: function (scope, element, attrs, ngModelCtrl) {
	    	ngModelCtrl.$viewChangeListeners.push(function(){ 
	    		if (ngModelCtrl.$modelValue && angular.isDate(ngModelCtrl.$modelValue)) {
	    			var offset = attrs.tzDate;
	    			offset && $parse(attrs.ngModel).assign(scope, moment(ngModelCtrl.$modelValue).utcOffset(offset, true).toDate());
	    		}
	    	});
	    }
	  };
});

```
`<md-calendar ng-model="calendarDate" tz-date="+02:00"></md-calendar>`

**Comment by rivertam** [comment] 2017-03-29 16:25
Nice! I ended up writing a component (that doesn't rely on moment, although I think moment is probably unnecessary with your approach as well)

```javascript
(function () {
  'use strict';

  angular.module('app.widgets').component('datePicker', {
    templateUrl: 'path/to/template.html',
    controller: DatePickerController,
    bindings: {
      minDate: '<?',
      maxDate: '<?',
      required: '<?',
      placeholder: '<?',
      currentView: '<?',
      name: '<?',
      initialDate: '<?',
      onChange: '&',
      ariaLabel: '<?'
    }
  });

  function DatePickerController() {
    var vm = this;

    if (!vm.initialDate) {
      vm.date = null;
    } else {
      // outer date is UTC
      // convert to local tim
      vm.date = new Date(vm.initialDate.getTime() + 60000 * vm.initialDate.getTimezoneOffset());
    }
    vm.update = update;

    function update(date) {
      // inner date is local time
      // convert to UTC to pass back up
      var utcDate = new Date(date.getTime() - 60000 * date.getTimezoneOffset());
      vm.onChange({ date: utcDate });
    }
  }
}());
```

```html
<md-datepicker
  name="{{$ctrl.name}}"
  ng-required="$ctrl.required"
  md-min-date="$ctrl.minDate"
  md-max-date="$ctrl.maxDate"
  md-current-view="{{$ctrl.currentView}}"
  ng-model="$ctrl.date"
  layout
  md-placeholder="{{$ctrl.placeholder}}"
  ng-change="$ctrl.update($ctrl.date)"
  aria-label="$ctrl.ariaLabel"
></md-datepicker>
```

```html
          <date-picker name="'someDate'" required="true" min-date="ctrl.minDate"
                         initial-date="ctrl.date"
                         on-change="ctrl.date = date"
                         placeholder="'Placeholder'"
                         ></date-picker>
```

I'm a React fan so I reached for the component when I saw this problem.

**Comment by Splaktar** [comment] 2018-01-05 08:09
I can see the difference in behavior and it needs to be fixed. I've updated the [CodePen](https://codepen.io/Splaktar/pen/NXazGg) for 1.1.5 and the issue is still there.

**Comment by Splaktar** [comment] 2018-01-05 09:06
This is needed so that the md-datepicker's calendar panel can be in sync with the md-datepicker's input. That issue is tracked in https://github.com/angular/material/issues/10598.

**Comment by Splaktar** [comment] 2019-08-29 17:01
@gaby64 I haven't had a chance to get back to this. I've been focused on P1 issues. If you want to submit a PR to fix this, I would be happy to review it and try to get it merged.

**Comment by Splaktar** [comment] 2020-05-12 01:06
Opened PR 🧙‍♂️ https://github.com/angular/material/pull/11906  ✨  for this issue.

**Closed** 2020-05-15 18:45 UTC
Labels: P2: required, g3: sync, has: Pull Request, i18n: localization, type: enhancement, ux: integration
