### ISSUE TITLE
swipe: swipe always triggers 'swipe left'

### ISSUE THREAD

**Issue by Looooong** [angular/material#10212] opened 2017-01-04 10:00 UTC
**Actual Behavior**:
 -  `What is the issue? *` Go to [this demo](https://material.angularjs.org/latest/demo/swipe) on an Android device with Chrome 55.0.2883.91, trying to swipe in any direction on the swipe left box always triggers the event. Swiping other boxes doesn't trigger event.
 -  `What is the expected behavior?` Trigger event correctly

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
 -  `Details:`

**Angular Versions**: *
 -  `Angular Version:` 1.4.x, 1.5.x
 -  `Angular Material Version:` 1.1.1

**Additional Information**:
 -  `Browser Type: *` Chrome
 -  `Browser Version: *` 55.0.2883.91
 -  `OS: *` Android 5.0.2, 6.0
 -  `Stack Traces:`

**Note**: I tested with 3 Android devices with Chrome 55.0.2883.91 and could always reproduce. It works on iPhone with Chrome 55.0.2883.79, works on Android with Chrome 50.x.x.x

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by vjku** [comment] 2017-01-04 14:35
Duplicate of #10145  https://github.com/angular/material/issues/10145

**Comment by Splaktar** [comment] 2020-04-15 19:06
Fixed in #10455 which was merged in `1.1.5`.

**Closed by Splaktar** 2020-04-15 19:06 UTC
Labels: resolution: duplicate
