### ISSUE TITLE
md-chips with autocomplete: pressing enter to select not working with angular 1.4

### ISSUE THREAD

**Issue by webley** [angular/material#3833] opened 2015-07-21 06:56 UTC
I'm using angular material 0.10.1-rc2 and angular 1.4.2.  Selecting items in the autocomplete using the mouse is working fine.  However, selecting an item by pressing "enter" results in an empty or malformed chip.  This is happening with the demo autocomplete chips as well as contact chips.

http://codepen.io/davidwolsey/pen/bdxewm

**Comment by smileapplications** [comment] 2015-07-21 10:44
I had the same problem. Put  md-autocomplete-snap="" md-require-match="" in the md-chips

**Comment by webley** [comment] 2015-07-21 11:49
Thanks smile, but the codepen demo already has both of those set, and in fact I don't want to use md-require-match.  This is just behaviour that's changed from angular 1.3 to 1.4.

**Comment by stevenmiles** [comment] 2015-07-22 09:22
Having the same issue with 0.10.1-rc2 and angularjs 1.4.3.

**Comment by yigaldviri** [comment] 2015-07-22 13:54
+1

**Comment by ilanbiala** [comment] 2015-07-22 14:52
Still having this issue with rc3 and 1.4.3.

**Comment by gauravbhavsar** [comment] 2015-07-23 09:28
Same issue with md-contact-chips with v0.10.0-master-cd3e8a1 and angularJS v1.4.2

**Comment by Huijari** [comment] 2015-07-23 22:38
+1

**Comment by schmkr** [comment] 2015-07-27 11:25
+1 (using `angular: 1.4.3` and `angular-material: 0.10.1-rc3-master-eda4782`)

**Comment by schmkr** [comment] 2015-07-28 07:21
Yesterday's released `0.10.1-rc4` still has this issue. You can see for yourself on the [demos page](https://material.angularjs.org/0.10.1-rc4/#/demo/material.components.chips) and start typing a name in the `Contact Chips` section. When you select a contact with a mouse click, everything works like before. However, when you press enter/return to confirm a autocomplete suggestion, the result is an empty chip.

**Comment by andreialecu** [comment] 2015-08-01 18:45
#3900 is related.

**Comment by davidlmiller21** [comment] 2015-08-06 19:15
Issue has to do with this: 
```javascript
MdChipsCtrl.prototype.inputKeydown = function(event) {
  var chipBuffer = this.getChipBuffer();
  switch (event.keyCode) {
    case this.$mdConstant.KEY_CODE.ENTER:
      if (this.$scope.requireMatch || !chipBuffer) break;
      event.preventDefault();
      this.appendChip(chipBuffer);
      this.resetChipBuffer();
      break;
    case this.$mdConstant.KEY_CODE.BACKSPACE:
      if (chipBuffer) break;
      event.stopPropagation();
      if (this.items.length) this.selectAndFocusChipSafe(this.items.length - 1);
      break;
  }
};
```

Is the point of enter to make a custom chip from the user input text?  Otherwise, this is the simple easy fix to get it to work by selecting the element:

```javascript
MdChipsCtrl.prototype.inputKeydown = function(event) {
  var chipBuffer = this.getChipBuffer();
  switch (event.keyCode) {
    case this.$mdConstant.KEY_CODE.ENTER:
      // DO NOTHING
      break;
    case this.$mdConstant.KEY_CODE.BACKSPACE:
      if (chipBuffer) break;
      event.stopPropagation();
      if (this.items.length) this.selectAndFocusChipSafe(this.items.length - 1);
      break;
  }
};

```

**Comment by ngraef** [comment] 2015-08-06 21:29
@davidlmiller21 The code you removed is needed for chips without autocomplete.

After some debugging, the underlying issue here seems to be that `requireMatch` isn't being set as expected in the `MdChipsDirective` scope (from the attribute `mdRequireMatch`). This causes the chips controller to not break out of the keydown handler, and it ends up appending a chip using the input text (`chipBuffer`). The chip buffer then gets cleared, which resets the autocomplete's matches. So by the time `MdAutocompleteCtrl` selects the item (delayed using `$mdUtil.nextTick`), `ctrl.matches` is empty and there is no autocomplete item to select.

As shown in [this demo](http://codepen.io/anon/pen/VLggYr?editors=101) (modified to use strings instead of objects), the chip buffer is getting added as a chip. This shows up as `()` in [the original demo](http://codepen.io/anon/pen/vObbOd?editors=101) because the text chip doesn't have a `name` or `type` property.

**Comment by houmark** [comment] 2015-08-06 23:19
@ngraef Interesting findings there. Did you manage to make a fix? If you have a chunk of code to potentially correct it I would be happy to test it out :) We are quite bothered by this particular bug as we are using chips quite a lot.

**Comment by ngraef** [comment] 2015-08-07 00:22
@houmark After a little more digging, the issue is in [chipsController.js line 87](https://github.com/angular/material/blob/master/src/components/chips/js/chipsController.js#L87):
```
if (this.$scope.requireMatch || !chipBuffer) break;
```

The [`mdChips` directive](https://github.com/angular/material/blob/master/src/components/chips/js/chipsDirective.js#L144) defines `bindToController: true`, which binds the directive's isolate scope properties to `MdChipsCtrl`'s `this` ***instead of*** `$scope`. So the simple solution here is to change the above code to:
```
if (this.requireMatch || !chipBuffer) break;
```

Now, we also have to declare an explicit `true` value for `mdRequireMatch` on `mdChips` otherwise it will be `undefined`:
```
<md-chips md-require-match="true" ... >
```

So an additional fix is needed in order to maintain the current `md-require-match=""` syntax, but I personally think having an explicit value is good.

**Comment by houmark** [comment] 2015-08-07 00:24
Thanks for that @ngraef, I will give it a spin and provide feedback :)

**Comment by ngraef** [comment] 2015-08-07 15:46
I believe there's also an issue here with event propagation. I don't think the keydown event on the autocomplete dropdown should propagate to the chips. In the use case where you don't want `md-require-match="true"` (e.g. being able to select a predefined tag from the autocomplete list or create a new tag from the input value), this propagation becomes an issue.

**Comment by metamatt** [comment] 2015-08-11 21:32
I saw this problem using mdAutocomplete and mdChips together and stepped through the code adding a bunch of logging. The problem I see is that both mdAutocomplete and mdChips attach a `keydown` event handler, and both of these `keydown` event handlers run. When you select an entry from the autocomplete dropdown by pressing Enter, `mdAutocomplete.keydown` calls `mdAutocomplete.select` which defers most of its work via `$mdUtils.nextTick`, during which time `mdChips.keydown` runs and calls `resetChipBuffer`. When `mdAutocomplete.select` starts running, the `$scope.searchText` is valid, but by the time it gets called back via nextTick, the mdChips `resetChipBuffer` has cleared the mdAutocomplete `searchText` and `handleSearchText` has cleared the matches list.

I haven't tried using md-require-match but I don't think I want that behavior anyway.

Near as I can tell, if both keydown event handlers are supposed to run, they should both progress at the same rate -- either both deferred via `nextTick` or neither deferred.

**Comment by typotter** [comment] 2015-08-11 23:07
duplicate of #3475

**Closed by typotter** 2015-08-11 23:07 UTC

**Comment by jherman** [comment] 2015-10-23 19:45
Still seeing this issue:
https://codepen.io/anon/pen/KdQJpW?editors=101

Type in "ca", cabbage will pop up and be auto selected.  Hit 'enter'.  You'll see two chips get added - what you searched for and the cabbage chip.  Expecting only the cabbage chip.

**Comment by houmark** [comment] 2015-10-23 19:54
@jherman Try this codepen that has a different configuration `<md-chips md-require-match="true">`:
https://codepen.io/houmark/pen/YyeBWo?editors=101

**Comment by jherman** [comment] 2015-10-23 21:26
The problem here, is that you can't enter in new chips if they aren't found. I think one of the devs are looking into on #3475.  I had to insert a one liner to fix the issue.  You can see my remarks there.  Thanks!

**Comment by houmark** [comment] 2015-10-23 21:43
You didn't say that it was a requirement to be able to add with chips :) In that case you might still have issues as you also have noticed - the fix was only a part fix and hopefully a better one for all use cases will happen at some point...

**Comment by ven-ivanov** [comment] 2015-10-30 13:36
How can we make md-chips with auto complete accept only valid email address? i use md-on-append and try to load contacts (email address) from db and at the same time type email address to add to to the contacts.

**Comment by canercak** [comment] 2015-11-19 13:28
md-require-match="true" works for me

**Comment by sirlero** [comment] 2015-12-03 16:11
md-require-match="true" works but if you wanna add new items?

**Comment by Waals** [comment] 2017-01-13 17:44
Based on the previous comments, here is a complete fix that worked well for my problem :)

```javascript
angular.module('material.components.chips')

  // here we need to rewrite the 'inputKeyDown' method of the mdChipsCtrl in order to prevent empty chips when the user hits ENTER.
  .config(function($provide) {
    $provide.decorator('mdChipsDirective', function($delegate) {
      
      // get directive
      var directive = $delegate[0];

      // get compile method
      var oldCompile = directive.compile;

      // rewrite compile method
      directive.compile = function() {

        return {

          // return original postLink method in 'post' attribute
          post: oldCompile.apply(this, arguments),

          // create a preLink method to access controller
          pre: function(scope, element, attrs, ctrls) {

            // get original 'inputKeyDown' method
            var inputKeyDown = ctrls[0].inputKeydown;

            // and rewrite it with the fix
            ctrls[0].inputKeydown = function() {

              // if ENTER key pressed, do the magic trick
              if (event.keyCode === this.$mdConstant.KEY_CODE.ENTER) {
                var chipBuffer = this.getChipBuffer();
              }
              
              // else call original method
              else {
                return inputKeyDown.apply(this, arguments);
              }

            };
          }
        };
      };
      return $delegate;
    });
  });
```
