### ISSUE TITLE
Visual indication of changing months in md-datepicker

### ISSUE THREAD

**Issue by victorivens05** [angular/material#4792] opened 2015-09-23 03:28 UTC
Greetings.

I've seen md-datepicker is now documentated, while I was using it with some coworkers, we found out we couldn't select any month other than the current, just after some tentatives we realized that we could achieve that just by scrolling.
Since it's not intuitive at all, I'd suggest to put some visual indication of that behavior, and that indication could be a top and bottom button with arrows to scroll the list to the next or previous month. 
I wrote some code to achieve that, but I still don't know how to make a pull request or something.
The code follows (it already works in the documentation, when the calendar is showing)

    var element = document.querySelector(".md-virtual-repeat-offsetter")
    var oldTrans = element.style.transform;
    var trans = oldTrans.replace("translateY(", "").replace("px)", "");
    
    element.style.transform = "translateY(" + (+trans - 265) + "px)";
    element.style.transition = ".45s all";
    
    setTimeout(function() {
        document.querySelector(".md-virtual-repeat-scroller").scrollTop += 265;
        element.style.transform = oldTrans;
        element.style.transition = "";
    },450);

p.s.: I apologize for any english mistake I might commited.

**Comment by jelbourn** [comment] 2015-09-28 18:12
Dupe of #4856

**Closed by jelbourn** 2015-09-28 18:12 UTC
