### ISSUE TITLE
mdMaxlength : counter doesn't work when click button to clear text 

### ISSUE THREAD

**Issue by sreymouch-leng** [angular/material#2022] opened 2015-03-25 09:13 UTC
I have a description text field and a clear button. When I type some words to description text field and click clear button to clear text in input box the counter doesn't update.
eg: http://codepen.io/anon/pen/myvXeO

**Comment by gkalpak** [comment] 2015-03-27 08:36
Duplicate of #1983 (also mentioned in #1903).

**Closed** 2015-09-04 17:45 UTC
Labels: resolution: duplicate
