### ISSUE TITLE
Weird dialog and md-select warnings & errors since 0.11.0

### ISSUE THREAD

**Issue by Tyrannmisu** [angular/material#4511] opened 2015-09-09 10:51 UTC
I switched from 0.10.1 to 0.11.0 (with angular 1.4.4) and got weird bugs since than, that i do not really understand.

I get the " **Unable to find node '{0}' in element. (angular.js:12416)** "  warning with each and every dialogue that i am opening, it does not matter if it is a custom or confirm-dialog.

When i try to open an md-select inside the dialog i get the following error in chrome:

```
TypeError: Cannot read property 'scrollHeight' of undefined
    at calculateMenuPositions (angular-material.js:12802)
    at angular-material.js:12475
    at new Q (angular.js:14896)
    at Q (angular.js:14883)
    at positionAndFocusMenu (angular-material.js:12472)
    at processQueue (angular.js:14634)
    at angular.js:14650
    at Scope.$eval (angular.js:15916)
    at Scope.$digest (angular.js:15727)
    at angular.js:15955
```

and this one in Fire Fox:

```
Error: contentNode is undefined
calculateMenuPositions@http://localhost:9000/bower_components/angular-material/angular-material.js:12802:9
positionAndFocusMenu/<@http://localhost:9000/bower_components/angular-material/angular-material.js:12475:22
Q@http://localhost:9000/bower_components/angular/angular.js:14896:5
Q@http://localhost:9000/bower_components/angular/angular.js:14883:1
positionAndFocusMenu@http://localhost:9000/bower_components/angular-material/angular-material.js:12472:1
...
```

I can't find anything in the breaking changes-changelog that could cause this, and it also seems like no one else is complaining. 

Am i doing something wrong, or can somebody point me to a direction where to look ?
I am totally clueless right now, the app worked like a charm up to 0.10.1.

Edit:
I also get the same error when using an md-select outside of a dialogue, even if it is something as basic as:
```html
<md-select ng-model="selectedLang.name">
    <md-option ng-repeat="choice in langOptions" value="{{choice.name}}">{{choice.name}}</md-option>
</md-select>
```

**Comment by Tyrannmisu** [comment] 2015-09-09 10:56
The "Unable to find node '{0}' in element." issue was also mentioned in a comment of :  https://github.com/angular/material/issues/4497

**Comment by stewones** [comment] 2015-09-09 19:56
+1

**Comment by shusain** [comment] 2015-09-09 21:09
+1 having this problem with md-select bumping from .10 to .11 fixed the placement of the placeholder label in our project but breaks the md-select itself, once the select is clicked the error above pops up

**Comment by RolandHeath** [comment] 2015-09-10 01:03
Have been having the same issues, but had trouble creating a codepen to replicate anything but the warnings. In my app, the md-select is inside a separate template, included via ng-include.

**Comment by RolandHeath** [comment] 2015-09-10 03:52
CreateSelect() appears to be what generates the SelectContainer which ultimately causes this error. It gets passed as the element to $mdSelect.show(...).
Following from this, $mdSelect.show:
1. Looks around for any child md-content, finds that there isn't one, and stores an empty JQLite. 
2. Can't read the scrollheight of anything in the empty JQLite that it stored, so it throws.

**Comment by ThomasBurleson** [comment] 2015-09-10 13:56
This is a logic issue with `$mdUtil.extractElementByName( )`

**Comment by ThomasBurleson** [comment] 2015-09-10 14:38
Warnings for **Unable to find node '{0}' in element.** have been fixed with SHA a5d84c372f87e96469f6c7d72d42d0aea83fe8fd

**Comment by barlowdw** [comment] 2015-09-10 14:40
Might be a bit late.

For me this is caused by including the jsqrcode library http://webqr.com/llqrcode.js.
Github: https://github.com/LazarSoft/jsqrcode

I created a codepen with a single md-select and including this library. http://codepen.io/barlowdw/pen/WQQGVP

**Comment by aldo-roman** [comment] 2015-09-10 15:57
+1 this error just pop out today after migrating from 0.10 to 0.11

any fix or workaround available?

**Comment by rschmukler** [comment] 2015-09-10 21:10
This is an issue with libraries / code that modify `Array.prototype` (in the case of `jsqrcode` `.remove`) interacting with `$mdUtil.supplant`. We are shipping up a fix now.

**Closed** 2015-09-10 21:18 UTC
Labels: priority: critical, type: bug

**Comment by Tyrannmisu** [comment] 2015-09-11 06:44
Works fine now, thanks ! :)

**Comment by joningib** [comment] 2015-09-14 12:02
@Tyrannmisu how did you fetch the fix down, my bower install fetches the 0.11.x version but it's missing this fix. Are you building it from source?

**Comment by shusain** [comment] 2015-09-14 12:41
@joningib you can bower install angular-material#master to get the latest that isn't yet fully released as a new version

**Comment by joningib** [comment] 2015-09-14 12:43
@shusain Yeah just tried that few minutes ago... I was too quick in asking for help :)

The fix works here! Great! :dancers:

**Comment by andrewboni** [comment] 2015-09-16 21:54
Confirmed that the latest in master fixes this bug. (Was using 0.11)

Thanks!

**Comment by aderbas** [comment] 2015-09-21 15:10
I'm using master (0.11.0) and get this bug. =/

**Comment by tawani** [comment] 2015-09-21 18:12
In my case I have to remove any "Array.prototype" code.
