### ISSUE TITLE
datepicker: when selecting a date around year 1970 in "year view", date changes to current date in the transition to "month view"

### ISSUE THREAD

**Issue by jose-braga** [angular/material#11272] opened 2018-05-07 11:08 UTC
## Bug:

Opening a datepicker in "year view" and then selecting a date around year 1970 (e.g. Jan 1970), makes the date to jump to current date (e.g. 2018-05-07) in the transition to "month view".

# CodePen and steps to reproduce the issue:
#### Detailed Reproduction Steps: 
1. Click on datepicker
2. Click a date around 1970 (e.g. 1970 Jan)
3. The datepicker transitions to month view, but now date is the current date (e.g. 2018-05-07)

### What is the expected behavior?
After the transition to month view, it should show the month of January of 1970.

### What is the current behavior?
After the transition to month view, it shows the month of May 2018 (current month).

### What is the use-case or motivation for changing an existing behavior?
Example: Users trying to select their birth date.

### Which versions of AngularJS, Material, OS, and browsers are affected?

- AngularJS: 1.6.9 (but happened in earlier versions, at least 6 months ago)
- AngularJS Material: 1.1.8 (but happened in earlier versions, at least since 1.1.5)
- OS: Windows 7
- Browsers: Chrome 66.0 and Firefox 59.0.3 (but happened in earlier versions, at least 6 months ago)

**Comment by codymikol** [comment] 2018-08-01 02:38
Can't seem to reproduce this on my end using your codepen. 
I'm on Chrome 67 - macOS 10.13.6 

![datepicker1970](https://user-images.githubusercontent.com/13606342/43497790-fe875cb4-9511-11e8-9c54-6211fbc2d8a4.gif)

**Comment by Splaktar** [comment] 2018-08-01 04:02
I can't reproduce this with the provided CodePen using AngularJS Material 1.1.9 or 1.1.5 on macos with Chrome 68 or Firefox 61.0.1 (64-bit).

Does this only happen on Windows?

**Comment by codymikol** [comment] 2018-08-01 15:00
Just tested on windows 7 in chrome, everything seems to work fine.

**Comment by Splaktar** [comment] 2018-08-01 23:51
Going to close this as not reproducible. If you can provide more details and an updated demo with reproduction, I can re-open this.

**Closed by Splaktar** 2018-08-01 23:51 UTC
Labels: needs: feedback, resolution: can't reproduce
