### ISSUE TITLE
<md-chip> Enchancement: Allow for some chips to be "read-only"

### ISSUE THREAD

**Issue by cmacdonnacha** [angular/material#7998] opened 2016-04-12 08:46 UTC
We can have non read-only chips:

![image](https://cloud.githubusercontent.com/assets/9777763/14454538/fa5bceec-0092-11e6-9034-58b2795af3b5.png)

and we can have read-only chips:
![image](https://cloud.githubusercontent.com/assets/9777763/14454543/0224febe-0093-11e6-9f68-9d4f0ac2b22a.png)

But we have some use cases for the ability to have both. Something like this:
![image](https://cloud.githubusercontent.com/assets/9777763/14454600/51bf848a-0093-11e6-92af-f241bdc2748c.png)

Would this enhancement be feasible?

**Comment by RolandHeath** [comment] 2016-04-13 01:00
In the worst case, you might be able to work around this by providing a chip template in which it is decided based on some attribute whether the chip is read only.

**Comment by DevVersion** [comment] 2016-04-13 19:20
This is a duplicate of #3820 and a PR is in progress - #5799

**Closed by DevVersion** 2016-04-13 19:20 UTC
