### ISSUE TITLE
md-datepicker opens on the wrong month when its container has a scroll bar

### ISSUE THREAD

**Issue by arthursouviron** [angular/material#10209] opened 2017-01-04 07:44 UTC
**Actual Behavior**:
 -  `What is the issue? *`
  md-datepicker opens on the wrong month when its container has a scrollbar and the input is not located at the top of that container.
 -  `What is the expected behavior?`
 md-datepicker should always open on the right date

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
 http://codepen.io/arthur_souviron/pen/vgYVPy
 -  `Details:` Click on the first datepicker, it's working fine. Scroll down and click on the bottom one, it doesn't open on the right month

**Angular Versions**: *
 -  `Angular Version:` 1.5.8
 -  `Angular Material Version:` 1.1.1

**Additional Information**:
 -  `Browser Type: *` Chrome
 -  `Browser Version: *` 55
 -  `OS: *` OS X 10.11.6
 -  `Stack Traces:` none

**Comment by wolfet** [comment] 2017-01-04 23:02
This same issue was referenced in #10144. @ppham27 submitted a PR to fix the issue. Using his build in your codepen fixes the issue for me. I'm really hoping it will land in the next release.

[http://codepen.io/twolfe/pen/qRENEd](http://codepen.io/twolfe/pen/qRENEd)

**Comment by gogodigimo** [comment] 2017-01-04 23:05
Awesome. Thanks, @wolfet !

**Comment by mde17** [comment] 2017-02-24 09:38
not working on 
angular 1.6.2
angular material 1.1.3

**Comment by lobo-tuerto** [comment] 2017-03-09 22:45
I'm seeing this problem with `md-datepicker` with or without parent having a scroll.

**Comment by chchild** [comment] 2017-03-14 22:29
> @alanssoares ... I found out the issue occurred inside the below method of CalendarMonthBodyCtrl.

> CalendarMonthBodyCtrl.prototype.generateContent  = function() {
> ..
> }

> Commenting the below line fixed the issue for me:

> //this.focusAfterAppend.focus();

This worked for me too: [#9952](https://github.com/angular/material/issues/9952#issuecomment-278313631)

Angular: 1.5.5 & 1.6.2
Angular Material: 1.1.3

**Comment by Splaktar** [comment] 2018-01-11 09:06
Duplicate of https://github.com/angular/material/issues/10144. Fixed in 1.1.5.

**Closed by Splaktar** 2018-01-11 09:06 UTC
Labels: resolution: duplicate
