### ISSUE TITLE
Typo in docs! 

### ISSUE THREAD

**Issue by pushkarmoi** [angular/material#7501] opened 2016-03-10 09:24 UTC
Demos> Input> Errors
When the user enters a hourly USD rate.
When the value esceeds a limit, the error shown is: 
" $50,022 an hour? That's a little ridiculous. I doubt event Bill Clinton could afford that."
"event". 
Seriously? You dont make a typo while giving a quirky error message

**Comment by DevVersion** [comment] 2016-03-10 11:37
Closing this, because the issue is already known and a PR is in progress. #7364

**Closed by DevVersion** 2016-03-10 11:37 UTC
