### ISSUE TITLE
md-tooltip not working inside disabled md-tab

### ISSUE THREAD

**Issue by and1gio** [angular/material#1667] opened 2015-02-25 16:53 UTC
```
<md-tab id="tab2" aria-controls="tab2-content" ng-disabled="true">
      Some Title
      <md-tooltip>
            This Feature is not available yet
      </md-tooltip>
</md-tab>
```
the tooltip is disabled too and don't works on hover.

**Comment by yanivefraim** [comment] 2015-02-28 20:00
After a little investigation of this issue, there seems to be two issues here:
1. When rendering the tooltip, the tab does not get the 'pointer-events: none', yet. This means that while debugging with this line of code (inside tooltip's code)
`while ($window.getComputedStyle(parent[0])['pointer-events'] == 'none') ` 
wasn't true, although it was supposed to be. I guess this is related somehow to Angular's rendering order (I have no solution for this, yet)

2. After hard-coding 'pointer-events' on the tab element, just in order to debug this, I see that this code section

 `while ($window.getComputedStyle(parent[0])['pointer-events'] == 'none') {
      parent = parent.parent();
    }
`

will have 'parent' as the 'md-header-items' element (in my test). This is not good as a tooltip's parent and will not work. I guess the 'quick and dirty' solution in this case will be to wrap the '<md-tab-item>' element in case it is disabled in html element (div?), which will have 'pointer-events: auto'. In this case the tooltip will work

*Is it possible to contribute here? I was reading earlier that you are not ready for contributing. I am willing to contribute to this awesome project, but I'm not sure that I'm not waisting my time here.... (:*

**Comment by gbruins** [comment] 2015-03-02 18:00
Same issue with <md-button>.  If disabled, then tooltips do not display.

**Comment by yanivefraim** [comment] 2015-03-02 18:18
Hey,
1. I succeeded to solve the first issue by applying this solution http://stackoverflow.com/questions/28787241/angularjs-ng-disabled-execution-order-on-a-directive.
I'm not sure it is acceptable to wrap the code with $timeout.
2. The second issue is caused by the wrong search for tooltip's parent. There are actually two tooltip parent elements here. Both are wrong: 
a. 'tooltipParent' variable, which is responsible for appending the tooltip to. This element is based on 'md-content' element or 'body'. Both are not good as tooltip location...
b. 'parent' which is responsible for mouse/touch event listeners. This element is based on the first element with 'pointer-events' != 'none'. This is a wrong choice as well. For example, in the tabs, this element is the tabs directives, which will trigger the tooltip for all tab elements (instead of only the desired one) 
I'm not sure how exactly this can be solved without a massive code refactoring. I have no idea who can I talk to here to get advices, and I would love to contribute and fix this issue (already invested several hours in this issue)

**Comment by dohomi** [comment] 2015-06-12 04:00
+1 for making tooltips available inside of ```ng-disabled```. I think its a common case that user wants to disable a button and the tooltip states why the action is not available (yet). I solved it with wrapping the ```button``` inside of a ```span``` but it might be clean if the tooltip would be available.

**Comment by SergeyBukhman** [comment] 2015-06-22 10:52
+1. Tooltip on a disabled control is actually important to communicate why it's disabled

**Comment by houmark** [comment] 2015-07-06 15:20
+1 for making tooltips available on disabled elements.

**Comment by rgolea** [comment] 2015-07-06 15:22
+1

**Comment by FlemmingBehrend** [comment] 2015-07-31 07:46
+1

**Comment by john2x** [comment] 2015-08-12 05:23
@dohomi could you share your workaround? I've tried [this](http://codepen.io/anon/pen/ZGZEwr) but it doesn't work. Thanks.

**Comment by dohomi** [comment] 2015-08-13 13:14
@john2x 
I just changed the span to div, and then you'll see how it works. In general it means, that if you'd choose span as the container just add a few more lines of CSS. Cheers

http://codepen.io/anon/pen/pJBWxo

**Comment by yochayme** [comment] 2015-08-26 13:39
+1

**Comment by du6** [comment] 2015-09-14 22:19
+1

**Comment by ocReaper** [comment] 2015-09-18 08:27
@dohomi Sadly your workaroud didn't work for me, nor in my project nor on codepen.

Anyway +1 for the issue!

**Comment by doppio** [comment] 2015-10-29 04:55
+1 here too. Would be pretty handy. :)

**Comment by Yannic92** [comment] 2015-11-05 22:45
+1

**Comment by BenniG82** [comment] 2015-11-09 08:32
+1

**Comment by alohaglenn** [comment] 2015-11-11 20:10
+1

**Comment by EvgenStudent** [comment] 2015-11-17 14:43
+1

**Comment by kaldebert** [comment] 2015-11-18 13:11
+1

**Comment by joeyperson** [comment] 2015-11-23 23:58
+1

**Comment by JanSchuermannPH** [comment] 2015-12-01 06:54
+1

**Comment by janvandenberg** [comment] 2015-12-02 09:11
+1

**Comment by thandaanda** [comment] 2015-12-07 10:39
+1

**Comment by tobsl** [comment] 2015-12-07 17:04
+1

**Comment by Kratos-SA** [comment] 2015-12-11 12:05
+1

**Comment by DomenicD** [comment] 2015-12-14 01:10
+1

**Comment by nielslucas** [comment] 2015-12-14 09:13
+ 1

**Comment by tuchk4** [comment] 2015-12-30 08:30
+1

**Comment by nissoh** [comment] 2016-01-18 12:44
quickie @dohomi fork that seems to be working
http://codepen.io/anon/pen/adVvLQ?editors=100

and +1 (: ofc

**Comment by cmacdonnacha** [comment] 2016-02-15 15:09
+1 really need this

**Comment by jaGarcia** [comment] 2016-02-17 17:55
+1

**Comment by j-ramirez-bi4group** [comment] 2016-02-22 12:37
+1

**Comment by nmousa** [comment] 2016-03-07 21:49
+1

**Comment by KelvinOm** [comment] 2016-03-15 13:13
+1

**Comment by KelvinOm** [comment] 2016-03-15 13:40
Add for this http://codepen.io/anon/pen/adVvLQ?editors=100 
css like this:
.md-button:disabled {
    z-index: -1;
}

work better!

**Comment by jaGarcia** [comment] 2016-03-15 14:07
Very nice!

**Comment by smfiorillo** [comment] 2016-04-21 21:08
+1 really need this

**Comment by francittadini** [comment] 2016-04-21 21:18
+1

**Comment by houmark** [comment] 2016-04-28 20:39
So now all the tracked issues people have posted and +1 on are just closed due to spring cleaning? So we just repost them all again? They don't get fixed by closing them. While I understand cleaning up is needed, some items are easily removed, while others should stay to be tracked.

This one is fairly simple, and heavily requested so I don't see how it fits the criteria for spring cleaning.

The issue has a working test fork, and there's no workaround I'm aware of.

**Comment by houmark** [comment] 2016-04-28 20:39
@ThomasBurleson The above comment was directed at you.

**Comment by pablozandona** [comment] 2016-05-03 18:48
+1

**Comment by Lykathia** [comment] 2016-06-07 15:48
> So now all the tracked issues people have posted and +1 on are just closed due to spring cleaning?

I've run into half a dozen issues like this one that have been heavily requested, but closed with no explanation or fix. Really destroys confidence. :-1:

**Comment by ThomasBurleson** [comment] 2016-06-07 16:51
@houmark - thx for the ping. Based on the +1(s), this should be reopened. 

> This is also, btw, part of our policy... that we can reopen with new PR, significant, +1(s), or easy fix. Thanks again.

**Comment by crisbeto** [comment] 2016-06-08 16:41
Hey everyone. I understand that this is a pretty common use case and has been open for a while, however I don't see a good way of solving it within Material. The issue here is that if certain elements are disabled, the browser just won't fire any events from them, which seems to be according to the spec. I see a few ways of working around it:

1. Keeping track of the coordinates of the mouse pointer/taps and matching them to the parent element. 
2. Wrapping the parent in another node and listening for events there.
3. Listening for the mouse events on non-disabled children of the disabled element. 

Neither of these is a good solution, because they're either unreliable, bad for performance or might produce unexpected results. On the other hand, it should be simple to work around it in your own project. Here are a few ways of doing it, some of which have also been posted above.

1. Move the tooltip outside the disabled element and wrap it in another one:
  ```html
  <!-- This -->
  <md-button disabled="disabled">
    Button
    <md-tooltip>Tooltip</md-tooltip>
  </md-button>

  <!-- Turns into this -->
  <div>
    <md-button disabled="disabled">Button</md-button>
    <md-tooltip>Tooltip</md-tooltip>
  </div>
  ```
2. Another way, while not very semantic, is to change the node type. For example, disabled divs still fire mouse events. The following looks identical and will show the tooltip:
  ```html
  <!-- This -->
  <md-button disabled="disabled">
    Button
    <md-tooltip>Tooltip</md-tooltip>
  </md-button>

  <!-- Turns into this -->
  <div class="md-button" disabled="disabled">
    Button
    <md-tooltip>Tooltip</md-tooltip>
  </div>
  ```
3. Similar to 1, except applying the tooltip to a child of the disabled element:
  ```html
  <!-- This -->
  <md-button disabled="disabled">
    Button
    <md-tooltip>Tooltip</md-tooltip>
  </md-button>

  <!-- Turns into this -->
  <md-button disabled="disabled">
    <div>
      Button
      <md-tooltip>Tooltip</md-tooltip>
    </div>
  </md-button>
  ```

Finally, I'm always open to suggestions about how we could get around this properly.

**Comment by jobo26** [comment] 2016-06-17 07:15
+1

**Comment by crisbeto** [comment] 2016-07-19 20:24
Closing since we can't do much about this and there are ways to work around it.

**Closed by crisbeto** 2016-07-19 20:24 UTC

**Comment by rushiraj111** [comment] 2017-09-01 09:06
Just add the content of button under span:

<button class="btn btn-primary btn-md"
                ng-click="Submit" ng-disabled="!enableSubmit">
            <span>
                Submit <i class="fa fa-check" aria-hidden="true"></i>
                <md-tooltip md-direction="top">Submit not Available</md-tooltip>
            </span>
        </button>

This worked for me

**Comment by rushiraj111** [comment] 2017-09-01 09:07
Just add the content of button under span:

<--
<button class="btn btn-primary btn-md"
                ng-click="Submit" ng-disabled="!enableSubmit">
            <span>
                Submit <i class="fa fa-check" aria-hidden="true"></i>
                <md-tooltip md-direction="top">Submit not Available</md-tooltip>
            </span>
        </button>
-->

This worked for me

**Comment by dtrenin7** [comment] 2017-09-26 16:35
Thanck you, ushiraj111!!
