### ISSUE TITLE
md-chips with md-autocomplete, selecting an autocomplete suggestion with arrow keys followed by hitting enter does not work

### ISSUE THREAD

**Issue by vikasvelagapudi** [angular/material#4948] opened 2015-09-30 21:17 UTC
When using md-chips with md-autocomplete, selecting an autocomplete suggestion with arrow keys and hitting enter does not appear to work. The expected behavior is that selecting the autocomplete suggestion from the list with the arrow keys and hitting enter would add the suggestion to the list of chips. Instead, the observed behavior is that the chip buffer (or search text) is added to the list of chips. The expected behavior occurs when the using arrow keys and tab or just using a mouse click to select a suggestion.

I want to allow both custom input or autocomplete suggestions for the chips and am therefore not using md-autocomplete-snap and md-require-match.

**Comment by topherfangio** [comment] 2015-10-01 15:38
Any chance you could provide a codepen which demonstrates how it's breaking so we can see a little bit better what you're trying to do?

**Comment by topherfangio** [comment] 2015-10-05 18:37
Duplicate of #4412. Please comment if you disagree and I will reopen.

**Closed by topherfangio** 2015-10-05 18:37 UTC
Labels: needs: demo
