### ISSUE TITLE
md-menu brings up a second scrollbar

### ISSUE THREAD

**Issue by Konkko** [angular/material#3266] opened 2015-06-15 10:25 UTC
Opening menu brings up a second scrollbar.

https://material.angularjs.org/0.10.0-rc4/#/demo/material.components.menu

**Comment by skeenan** [comment] 2015-06-15 12:59
+1 

The issue is that activating a menu triggers right scrollbar on the browser window which causes the view frame to shift slightly when opening closing the menu. This effect can been seen in the menu demo on the official docs.

Would like browser scrollbar suppressed when activating menu.

**Comment by levan1993** [comment] 2015-06-15 15:30
body {
    overflow-y: auto!important;
}

**Closed** 2015-06-15 21:11 UTC

**Comment by lauraerinmann** [comment] 2017-07-28 20:41
Using the current version, this doesn't seem to be fixed.
