### ISSUE TITLE
Datepicker is unusable, remove it from demos?

### ISSUE THREAD

**Issue by super-coder** [angular/material#6278] opened 2015-12-13 05:10 UTC
I can select only current month, what is the point of such a component? There are no arrows like in specs https://www.google.com/design/spec/components/pickers.html#pickers-date-pickers and no way to select  a year

**Comment by DevVersion** [comment] 2015-12-13 14:16
As we can see in the specs, this is a `Picker Dialog`. And we are currently only providing a Picker, which is overlaying the input to select a date. I already created a PR which adds Chevrons to select the month (but this one was denied by the UX team). Here you can see the old one #5971

**Comment by super-coder** [comment] 2015-12-13 14:25
i meant Chevrons. Well, should I close this issue then? Is there any ETA?

**Comment by DevVersion** [comment] 2015-12-13 14:28
I don't know about closing this. I think the datepicker as it currently is is by intention. So you can close that issue.

**Comment by lwj5** [comment] 2015-12-14 15:05
@DevVersion Is it possible for you to create a new repo for the date picker that you have designed? Then everyone who needs it can contribute to it? I think your datepicker is by far the most friendly for general use

Sorry for the hijack, there's no PM feature github.

**Comment by DevVersion** [comment] 2015-12-14 17:34
@lwj5 The problem is, I have no time to work on that specific datepicker, I wan't to work at the actual project. That's why I can create another repository which will be rebased on the actual material project. So it will contain always the newest commits and other people are able to contribute

https://github.com/DevVersion/material-datepicker

**Comment by super-coder** [comment] 2015-12-15 04:28
@DevVersion "I think the datepicker as it currently is is by intention.", but what was the intention behind putting a demo of a datepicker without month switcher? It tool me a while to understand that i had to use mouse wheel

**Comment by DevVersion** [comment] 2015-12-15 06:03
I don't know, that was decided by the UX Team

**Comment by jelbourn** [comment] 2016-01-05 22:34
@super-coder The calendar scrolls. We are following a as-of-yet unreleased spec from the Material Design team; it has indeed come up many times that the scrolling is not super obvious, and we'll be working with the designers to iterate on the appearance. You can follow that issue in #4856

In the future, please reference Angular's [Code of Conduct](https://github.com/angular/code-of-conduct/blob/master/CODE_OF_CONDUCT.md) before filing issues.

**Closed by jelbourn** 2016-01-05 22:34 UTC

**Comment by super-coder** [comment] 2016-03-26 12:50
@jelbourn so after 3 months you will still say it is usable? Be honest - if it's a fail, accept it. See https://github.com/angular/material/issues/4251
