### ISSUE TITLE
Menu with icon not aligned with firefox

### ISSUE THREAD

**Issue by Alexandre-io** [angular/material#3292] opened 2015-06-16 18:46 UTC
Hello,

Maybe duplicate but menu with icon is not aligned with firefox.

![capture](https://cloud.githubusercontent.com/assets/8135542/8191428/45c069e6-1468-11e5-99e4-fb4c78fe1d60.PNG)

related to "display:flex"

**Comment by arcxyz** [comment] 2015-06-16 19:01
Same here.
Firefox 38.0.5 and 40.0a2

**Comment by ThomasBurleson** [comment] 2015-06-16 19:38
Seems to be related to the override `display:flex` in the **md-menu-item**.
This change fixes it:

```css
md-menu-item > .md-button {
    display: inline-table;
}
```

**Comment by tccBen** [comment] 2015-06-16 19:39
It's not just Firefox or menus. I'm using Chrome 43.0.2357.81 m, and Font Awesome. Any md-button with a FA icon in it acts the same way. The flex direction is set to column, so it takes the icon and stacks it with any text content.

**Comment by rschmukler** [comment] 2015-06-21 21:36
This was broken by b1046bc, duplicate of https://github.com/angular/material/issues/3322

**Closed** 2015-06-21 21:42 UTC
