### ISSUE TITLE
enhancement: version variable

### ISSUE THREAD

**Issue by a8775** [angular/material#4918] opened 2015-09-29 17:11 UTC
It looks Angular Material is missing version variable like angularjs has:
https://docs.angularjs.org/api/ng/object/angular.version

**Comment by jelbourn** [comment] 2015-09-29 23:37
Dupe of #3842 

The problem is that ng-material doesn't have its own global property like `window.angular`, so we have to make our version info available through Angular.

**Closed by jelbourn** 2015-09-29 23:37 UTC
