### ISSUE TITLE
Required md-date-picker with Floating label option like other components have

### ISSUE THREAD

**Issue by sunnyshah01** [angular/material#5106] opened 2015-10-12 11:48 UTC
- Floating label in date picker is required optionally.
- Currently there is two buttons in md-date-picker. One is date picker icon button and another is drop down button.
- Date picker should look like another components Input, Select and Autocomplete so all components looks same.
- css for date picker validation message is required

**Comment by corentin-gautier** [comment] 2015-10-14 08:06
+1

**Comment by aviadhahami** [comment] 2015-10-15 16:46
+1

**Comment by StevenGnt** [comment] 2015-10-20 12:30
+1

**Comment by hatuan** [comment] 2015-10-24 14:00
+1

**Comment by barmaley443** [comment] 2015-10-28 14:51
+1

**Comment by jelbourn** [comment] 2015-11-02 19:12
Dupe of #4233

**Closed by jelbourn** 2015-11-02 19:12 UTC
