### ISSUE TITLE
Select validate demo has odd "Pick" string

### ISSUE THREAD

**Issue by danwkennedy** [angular/material#2596] opened 2015-04-28 15:07 UTC
![select](https://cloud.githubusercontent.com/assets/501989/7372778/a75776fc-ed96-11e4-8702-4167afa47551.png)

Not sure what that is. Looks like something got missed in the demo.

**Comment by ngraef** [comment] 2015-04-28 16:04
Duplicate of #2572.

**Closed** 2015-04-28 16:09 UTC
