### ISSUE TITLE
test(util): check scrollTop with pinch-zoom in IE/Chrome

### ISSUE THREAD

**Issue by EladBezalel** [angular/material#8427] opened 2016-05-12 02:08 UTC
https://code.google.com/p/chromium/issues/detail?id=496285

**Comment by DevVersion** [comment] 2016-08-30 12:56
I had a quick discussion with @EladBezalel about the pinch zoom issue.

When looking at the related chrome bugs, I figured out that the original bug was closed and merged into another one.

- https://bugs.chromium.org/p/chromium/issues/detail?id=489206

Nevertheless it is not a bug of Angular Material, and is nearly impossible to fix on our end. 
> We are just depending on native browser functionality, which can't be fixed by us.

I'am going to close this for now, since I'm going to remove that TODO.

@bradrich If you think you are able to solve it easily, feel free to reopen it.

**Closed by DevVersion** 2016-08-30 12:56 UTC
Labels: P2 - Planned Work / Team PRs
