### ISSUE TITLE
md-datepicker sending the day before the one that I select

### ISSUE THREAD

**Issue by jadjoubran** [angular/material#4636] opened 2015-09-15 08:22 UTC
Here's a [codepen](http://codepen.io/jadjoubran/pen/gaPoXg)

When you first open the page, the date is correct - for example `"2015-09-15T08:19:32.808Z"` (today is 09-15)
But as soon as you select `9/13/2015` for example, it shows 1 day before  `"2015-09-12T21:00:00.000Z"`

It seems like it's choosing 1 day before the one that I selected
It happens for every single date that you choose.

**Comment by jadjoubran** [comment] 2015-09-15 08:42
After reading the source code and debugging with a fellow colleague:
Location: We are in Beirut, Lebanon (GMT+3). This is the main cause of the issue.
So when I select `9/13/2015` it shows `9/12/2015` with time `21:00:00`.
So this is most likely a timezone issue.

If you are trying this issue from the U.S., you should probably see the date correct, but the time wrong, something like: `9/13/2015` with time: `06:00:00`
It really depends on your timezone

Is anyone able to verify the issue?

**Comment by jelbourn** [comment] 2015-09-15 16:55
@jadjoubran Do you see this issue [on master](https://material.angularjs.org/HEAD/#/demo/material.components.datepicker)?

**Comment by EladBezalel** [comment] 2015-09-15 17:20
#4215 related

**Comment by jadjoubran** [comment] 2015-09-15 19:52
@jelbourn thanks for helping out! Yes still happening on master. I edited the codepen and added {{myDate}} and the same issue is reproducible

@EladBezalel so what would be the solution? Why would moment.js fix it?
The fix in the commit is only for "11:00" and "23:00" that's weird..

**Comment by jelbourn** [comment] 2015-09-15 21:41
The earlier fix was under the notion that this was purely a Daylight Saving Time issue, which would be only one hour off. Seems like that's not really the case, though. 

Using something like moment.js (or your own date parsing/formatting) fixes this because this bug is caused by the native JS date formatting. Specifically, you can make a Date set to an exact date at hour = 0, minute = 0, seocnd = 0, and have `toLocaleString` still give you the day before. E.g.:
```js
var d = new Date(2015, 9, 8, 0, 0, 0); // Should be Oct. 8th at midnight
d.toLocaleString(); // Would write Oct. 7th, 11:00pm.
```

**Comment by jadjoubran** [comment] 2015-09-16 09:46
@jelbourn Thanks for your answer!
I just ran your code and I got `"10/8/2015, 12:00:00 AM"`
Not sure what that means..

But don't you think we should aim for a generic solution that works for everyone? Because I'm guessing this is going to be reported by anyone outside of the U.S.

I'd love to work on a PR for this, if you agree. But again I'm not sure how we should fix this

**Comment by jelbourn** [comment] 2015-09-16 16:45
A "real" fix for this would be to do full-blown Date internationalization, which isn't really in the scope of ng-material. I'm going to try to make the default more sensible for more timezones. It will never be perfect, but that's why the support for using your own i18n (like moment.js) is there.

**Comment by jelbourn** [comment] 2015-09-22 17:46
@jadjoubran I've tried reproducing this by setting the time on my machine to Beirut time, but I'm not seeing the issue. If the code snippet above does actually render the correct date, I'm not sure where the bug is. 

If you inspect the `data-timestamp` attribute of one of the date cells and then do `new Date(timestamp)` and also `new Date(timestamp).toLocaleString()`, does the result match what is displayed in the calendar?

**Comment by jadjoubran** [comment] 2015-09-23 20:41
@jelbourn I'm using Chrome Version 45.0.2454.99 m on Windows 10.
Indeed it works well if I run `new Date(timestamp)` and `new Date(timestamp).toLocaleString()`. In fact both of them work very well.

It seems that the bug is not in the timestamp (sounds odd I know). Can you please try the following scenario, I think this is how you'll be able to replicate the bug:

1) Change your timezone back to beirut
2) Open my previous [codepen](http://codepen.io/jadjoubran/pen/gaPoXg)
3) You should see the correct date
4) Select another date, you'll see that it shows the (Day - 1 ) with the current hour

**Comment by jelbourn** [comment] 2015-09-23 21:49
@jadjoubran Tested with on Windows 8 with Chrome 45 with the OS timezone set to Beirut, and I still wasn't able to see the problem. 

The bug very likely has to do with the `formatDate` function in `$mdDateLocale`. By default, this uses `Date.prototype.toLocaleDateString`. If this function is actually returning the right string (that should be set to the text input), then I'm baffled. Can you check that the output of `formatDate` is when you select a date? If that seems right, can you trace through the `md-calendar-change` handler in `datePicker.js` and see if there's something going awry there? Thanks so much for the help debugging this.

**Comment by jadjoubran** [comment] 2015-09-25 14:58
Hi @jelbourn 
I tried tracing through this function but using the console, so I was instantiating dates manually and everything was working perfectly. And from this I came to the following conclusion:

https://github.com/angular/material/blob/c2e17ad6ce0a0f16b2169986adb278083ad22eb8/src/components/datepicker/datePicker.js#L264

This is working absolutely fine.. and in fact when I see the error, the input always shows the correct date, but as soon as you render the value in the view or send it to the database or inspect it, you'll see that it's off by 3 hours (because I'm in GMT +3).

So for example, when I get today's Timestamp and I create a new date, I get the following date:
`Fri Sep 25 2015 00:00:00 GMT+0300 (Middle East Daylight Time)`
When you run `.toLocaleDateString()` it works fine: it returns 9/25/2015.

So the problem is not with this code, but mainly with where the date is fully stored - so for example when it's rendered in the view you'll see something like this: `"2015-09-24T21:00:00.000Z"`

So maybe you have an idea where this is happening?

Here's a screenshot that shows the input showing the correct date whereas the view showing the time that is off by 3 hours (because it's trying to convert it to GMT, so it removes 3 hours).
![untitled](https://cloud.githubusercontent.com/assets/2265232/10103849/f9c12314-63ae-11e5-85ae-cf157284e64b.png)

Also notice how the AngularJS inspect plugin shows the correct date with GMT

**Comment by jelbourn** [comment] 2015-09-25 19:37
@jadjoubran it sounds like, while the datepicker treats dates as local time, some other part of your application is treating them as UTC. Does that sound right?

**Comment by jadjoubran** [comment] 2015-09-25 19:39
100%
I am online, let me know if I can help with the debugging process

**Comment by jelbourn** [comment] 2015-09-30 23:00
@jadjoubran If other parts of your app are interpreting the date as UTC, does that means the datepicker itself is always internally consistent? That is, if you click a date in the calendar, that matches the date that renders in the text input?

**Comment by jadjoubran** [comment] 2015-10-01 19:55
Yes, it always does

**Comment by jelbourn** [comment] 2015-10-01 20:21
Based on that, I this doesn't sound like a bug in the datepicker itself. As it is now, the fact that it always deals with local times is working as intended; your app can take that local time and do any necessary conversions to UTC. 

We do want to add a "UTC mode" to the datepicker, but it's not high on the short-term priority list. Going to close this issue for now- feel free to update if there's something I'm missing.

**Closed by jelbourn** 2015-10-01 20:21 UTC
Labels: priority: high

**Comment by prerna12** [comment] 2015-10-02 09:25
Hi @jelbourn @jadjoubran,

I am facing the same issue. Is this issue fixed? Or if you could you kindly suggest some work around that works? Cause the date picker is setting my model to one day previous to the selected date. 

Thanks.

**Comment by jadjoubran** [comment] 2015-10-02 09:42
@prerna12 I wasn't able to fix this yet.. maybe @ThomasBurleson has an idea?

**Comment by jelbourn** [comment] 2015-10-02 16:39
@prerna12 @jadjoubran Based on my understand of this, you need to convert the local value coming from the datepicker to UTC if that is what the rest of your app is using. For any real application, you should be using something like moment.js with `$mdDateLocaleProvider` to do parsing and formatting.

**Comment by verkestk** [comment] 2015-10-02 22:07
I'm seeing something similar, but it's intermittent. Sometimes the value assigned to the ng-model $scope property is this:

```Tue Jun 30 2015 00:00:00 GMT-0500 (CDT)```

And sometimes it's this:

```Tue Jun 30 2015 23:59:59 GMT-0500 (CDT)```

Same component, same page load. Just clicking the same date over and over again produces mostly the first, but about 1/10 of the time the second.

**Comment by jadjoubran** [comment] 2015-10-11 13:01
@jelbourn I tried fixing it by including moment.js but I wasn't able to fix it..
How would you suggest fixing it? I'm not even sure I got it right
Which method of these should I keep?
https://material.angularjs.org/0.11.2/#/api/material.components.datepicker/service/$mdDateLocaleProvider
Is it parseDate? because it never gets called
Thanks!

**Comment by sunnyshah01** [comment] 2015-10-12 09:27
+1

**Comment by jelbourn** [comment] 2015-10-12 17:36
Both `parseDate` and `formatDate` need to be set.

**Comment by altsel** [comment] 2015-11-11 13:21
@jadjoubran I had the same issue. I wrote this directive using moment.js ! Adding this directive to md-datepicker works great for me !
```
var dateDirective = function() {
    return {
        require: 'ngModel',
        link: function(scope, elem, attrs, ngModel) {
            var toView = function(val) {
                return val;
            };

            var toModel = function(val) {
                var offset = moment(val).utcOffset();
                var date = new Date(moment(val).add(offset, 'm'));
                return date;
            };

            ngModel.$formatters.unshift(toView);
            ngModel.$parsers.unshift(toModel);
        }
    };
}
```

**Comment by jadjoubran** [comment] 2015-11-11 15:49
@altsel works like a charm
Thanks a lot!

**Comment by bampakoa** [comment] 2016-02-09 16:54
@altsel Could you share any unit test that you have written for your directive?

**Comment by mbhuie** [comment] 2016-03-03 03:58
+1

**Comment by Nextt1** [comment] 2016-04-02 10:25
Is there any solution to this bug ?? @altsel 's solution in not working for me.

**Comment by achuinard** [comment] 2016-04-12 04:37
Thanks to a great direction from @altsel I have expanded his directive to include 2 features:

1) Specify your app / datepicker's timezone through an ng-attr-timezone
2) Bind to a millisecond epoch instead of a JavaScript Date object (was very useful for my Firebase application)

`    .directive('timezonedDate', function () {
        return {
            require: 'ngModel',
            restrict: 'A',
            link: function (scope, elem, attrs, ngModel) {
                var toView = function (val) {
                    var offset = moment(val).utcOffset();
                    var date = new Date(moment(val).subtract(offset, 'm'));
                    var newOffset = moment.tz.zone(attrs.timezone).offset(date);
                    return new Date(moment(date).subtract(newOffset, 'm').unix() * 1000);
                };

                var toModel = function (val) {
                    var offset = moment(val).utcOffset();
                    var date = new Date(moment(val).add(offset, 'm'));
                    var newOffset = moment.tz.zone(attrs.timezone).offset(date);
                    return moment(date).add(newOffset, 'm').unix() * 1000;
                };

                ngModel.$formatters.unshift(toView);
                ngModel.$parsers.unshift(toModel);
            }
        };

    });
`

**Comment by zaqpiotr** [comment] 2016-04-17 08:58
Hello, @achuinard could You tell me how add Your directive to md-datepicker and how to use it?

**Comment by achuinard** [comment] 2016-04-18 21:33
@zaqpiotr You just add that directive into your angular app, then do something like - 

`<md-datepicker timezoned-date ng-attr-timezone="{{jsTimeZone}}" ng-model="document.ship_date" ng-change="saveData('ship_date')" md-placeholder="Select Date"></md-datepicker>`

**Comment by ggarg2** [comment] 2016-04-18 21:41
Hi @achuinard, please tell me what is jsTimeZone ?

**Comment by achuinard** [comment] 2016-04-18 21:46
@ggarg2 Whatever timezone your user's timezone is. My app lets the user pick a timezone, so for example they want everything in Australian time, I'm not going to let the browser give me epochs for dates based on browser time.

**Comment by crowmagnumb** [comment] 2016-04-29 17:08
The problem I'm running into is if I edit the date directly in the control it gives me the previous day but if I pick from the calendar dropdown in gives me the day I pick! Completely inconsistent. In both cases I'm getting a date in the format "Tue Apr 26 2016 00:00:00 GMT-0700 (PDT)" where the time is 00:00:00 which is what I want because I'm only interested in the day. The above is what I get if I select April 26th, 2016 from the drop-down calendar. But if I *type* in "2016-04-26" I get "Tue Apr 25 2016 00:00:00 GMT-0700 (PDT)"!

**Comment by crowmagnumb** [comment] 2016-04-29 17:47
Ah, I just discovered that it's seems to be a javascript [bug](http://stackoverflow.com/questions/9509360/datepicker-date-off-by-one-day)?

To excerpt from above link ...

```
new Date ('2012/03/21'); // returns: "Wed Mar 21 2012 00:00:00 GMT-0500 (CDT)"
new Date ('2012-03-21'); // returns: "Tue Mar 20 2012 19:00:00 GMT-0500 (CDT)" WHA!
```
 ...and I tested it with md-datepicker. Using slashes works fine, dashes gives previous date.

**Comment by crowmagnumb** [comment] 2016-04-29 18:01
Oh gosh, another update to this issue, apologies. I just discovered that we had the following code ...

```
app.config(['$mdThemingProvider', '$logProvider','moment', '$mdDateLocaleProvider',
         function($mdThemingProvider, $logProvider, moment, $mdDateLocaleProvider) {
    $mdDateLocaleProvider.formatDate = function (date) {
        if (!date) {
            return null;
        }
        return moment(date).format('YYYY-MM-DD');
    };
}
```
... and so it isn't md-datepicker that is defaulting to this style of date, we did that. So I commented it out and found that md-datepicker defaults to MM/DD/YYYY format and so editing that value works! Whew. Ok the date thing is still very, very annoying but I'm just going to not use that format for now.

**Comment by ThomasBurleson** [comment] 2016-04-29 20:13
@crowmagnumb - please open a new issue with your above comments.
