### ISSUE TITLE
md-chips + autocomplete does not look right

### ISSUE THREAD

**Issue by csvan** [angular/material#4600] opened 2015-09-11 20:29 UTC
Compare the md-chips autocomplete here:
https://material.angularjs.org/latest/#/demo/material.components.chips

![autocomplete-bad](https://cloud.githubusercontent.com/assets/1127729/9825550/3dec3d34-58d4-11e5-9d1d-4c99157c5d49.png)

To the regular autcomplete here (last example):
https://material.angularjs.org/latest/#/demo/material.components.autocomplete

![autocomplete-good](https://cloud.githubusercontent.com/assets/1127729/9825546/387ea1ac-58d4-11e5-9dcb-9a5c13a05474.png)

I may be off, but the text (and label/placeholder when either is empty) looks distractingly displaced in the chips example, and the font size is different too. Should they both not match a regular input in order to give a consistent look and feel?

Tested on Chrome 45 under Fedora 22.

**Comment by csvan** [comment] 2015-09-11 20:35
It should be noted that adding the `md-floating-label` attribute to the `md-autocomplete` in chips does not resolve this.

**Comment by hedder** [comment] 2015-09-21 16:33
+1

**Comment by lyschoening** [comment] 2015-10-21 15:11
The font size of the placeholder is also too small (compared to regular inputs/chips; when using an autocomplete with chips). Would that be related to this issue?

**Comment by RolandHeath** [comment] 2015-10-23 02:27
@lyschoening As far as I can tell, this is because for some reason, the font size for the text in the autocomplete dropdown is getting applied to the placeholder text. In my app I've managed to make enough css changes that the text/placeholder will look right, although it doesn't have the floating labels. I'll see if I can reply with the changes I've made, or add them to this post later.

**Comment by brenovieira** [comment] 2015-10-23 04:07
+1.
Seems a duplicate of #4450

**Comment by RolandHeath** [comment] 2015-10-23 04:30
@brenovieira  It does seem that way at first, but that issue is referring specifically to the dropdown elements. I think you're right in that they probably have a common cause.

**Comment by brenovieira** [comment] 2015-10-23 04:41
@RolandHeath, yeah :+1: 

Indeed they're different, but convert to the same:
style of chips + autocomplete looks strange hehhe

**Closed** 2015-10-29 15:21 UTC
