### ISSUE TITLE
datepicker in dialog scroll not disabled?

### ISSUE THREAD

**Issue by cskiwi** [angular/material#9127] opened 2016-07-25 12:50 UTC
**Actual Behavior**:
 -  When scrolling in a md dialog the datepicker conatiner stayes fixed, while the date input is scrolling
![image](https://cloud.githubusercontent.com/assets/847540/17101829/e6d625b2-5276-11e6-89c2-135d514b03c0.png)

**Angular Versions**: *
 -  `Angular Version: 1.5.6` 
 -  `Angular Material Version: master (1.1.0-RC-5)`

**Additional Information**:
 -  `Browser Type: Chrome` 
 -  `Browser Version: 53.0.2783.4 dev-m (64-bit)`
 -  `OS: *` Windows 7

**Comment by crisbeto** [comment] 2016-07-25 13:02
Hmm, I think I pushed a fix for this a while ago. I'll re-check it.

**Comment by crisbeto** [comment] 2016-07-25 15:25
@cskiwi Can you post a Codepen that shows the issue? I couldn't reproduce it neither on master, nor on 1.1.0-rc.5. The last version on which I _could_ reproduce it was 1.1.-rc4. 
For reference, here's the PR that fixed it https://github.com/angular/material/pull/8292

**Comment by ThomasBurleson** [comment] 2016-07-26 12:36
Fixed.

**Closed by ThomasBurleson** 2016-07-26 12:36 UTC
Labels: P0 - Critical Fixes / Build or Deployment Issues, severity: regression, type: bug
