### ISSUE TITLE
datepicker - not all dates are clickable in Firefox 43 when md-max-date is set

### ISSUE THREAD

**Issue by richardsengers** [angular/material#6476] opened 2015-12-28 11:26 UTC
Weird behaviour in Firefox when *only* md-max-date is set
For example
http://codepen.io/anon/pen/LGbPdy
Only the first row of dates are clickable

When resizing the window, all works fine.

**Comment by jelbourn** [comment] 2016-01-05 23:00
@richardsengers I'm not sure what issue you're trying to describe. I tried out your CodePen in Firefox and everything works as expected. `md-max-date` disables dates that are beyond that maximum date, so that behavior is intended. I don't see anything that changes on resize.

**Comment by richardsengers** [comment] 2016-01-06 08:34
@jelbourn  thanks for the reply

![not-selectable](https://cloud.githubusercontent.com/assets/810038/12138176/16da8e1a-b457-11e5-859e-15adcbcb55c6.jpg)

Let me try to explain it  a little bit better by submitting an image. As you can see the max date is set to the 6th of januari. Janurai 3th, 4th and 5th are not selectable / clickable, while januari 1st and 2nd are selectable/clickable

To me it's not quite clear why the dates are not selectable / clickable

ps I'm running Windows 10

**Comment by LeonVay** [comment] 2016-01-22 07:17
@richardsengers 
@jelbourn 
Hi,
faced the same issue, but this one is not reproducible if md-min-date is set.

**Comment by jeffmcardle** [comment] 2016-02-10 15:30
Also witnessed this issue. Removed "md-max-date" and it works fine.

**Comment by koljada** [comment] 2016-03-01 12:58
Hi, 
I also have this issue in Firefox. There's my fiddle:

**Comment by koljada** [comment] 2016-03-01 13:52
But if you just add md-min-date the plugin will work like a charm again!
https://jsfiddle.net/koljada/Lrr8drz5/6/

**Comment by koljada** [comment] 2016-03-01 14:15
And also if you just replace 
`this.firstRenderableDate = this.dateUtil.incrementMonths(this.maxDate, -(this.items.length - 2));`
 with
`this.firstRenderableDate = this.dateUtil.incrementMonths(this.maxDate, -(this.items.length - 2)/2);` 
in the code the problem will disappear.

**Comment by ThomasBurleson** [comment] 2016-04-28 19:46
This issue is closed as part of our deprecation effort.
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).

**Closed by ThomasBurleson** 2016-04-28 19:46 UTC
Labels: needs: investigation, P5 - Needs Investigation
