### ISSUE TITLE
Md-datepicker CSS diferente a los demás inputs

### ISSUE THREAD

**Issue by tramonex-dbardaji** [angular/material#5035] opened 2015-10-06 14:28 UTC
Hi, I was taking a look into the css and I saw that this element (MD-datapicker) is different that the others inputs and for this reason is not adapting well with the others. Also, if you want to modify it to try to have the same effects that the others inputs, you should create an extra wrapper. 

All inputs:
    container { padding: 2px 2px 10px 2px}
    input {  height: 34px; padding: 2px 2px 1px 2px: border: 1px }

MD-Datapicker
   container { padding-bottom: 5px; border-bottom: 1px; margin-left; 12px }
   input {  height: 22px; padding:1px 1px 1px 1px }

**Comment by colinskow** [comment] 2015-10-07 06:38
+1 see also https://github.com/angular/material/issues/4955

**Comment by jelbourn** [comment] 2015-11-02 18:44
Dupe of #4223

**Closed by jelbourn** 2015-11-02 18:44 UTC

**Comment by colinskow** [comment] 2015-11-02 21:48
@jelbourn this issue has actually nothing to do with #4223. This issue is about CSS inconsistencies. That issue is about click behavior.

**Comment by jelbourn** [comment] 2015-11-02 21:52
Whoops, wrong issue. I meant to type #4233

**Comment by colinskow** [comment] 2015-11-03 01:06
OK, that looks related.
