### ISSUE TITLE
mdPanel cancel event

### ISSUE THREAD

**Issue by lashisu** [angular/material#10513] opened 2017-03-20 08:53 UTC
**Actual Behavior**:
 -  `What is the issue? *`
Cancel event is missing, like in confirm dialog.
 -  `What is the expected behavior?`
There must be a cancel event for mdPanel.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
 -  `Details:`

**AngularJS Versions**: *
 -  `AngularJS Version:`1.5.9
 -  `AngularJS Material Version:`1.1

**Additional Information**:
 -  `Browser Type: *`Chrome
 -  `Browser Version: *`56.0.2924.87
 -  `OS: *`Windows 10
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by Splaktar** [comment] 2020-09-07 03:38
There isn't much information here, but I believe that this is a duplicate of https://github.com/angular/material/issues/9557.

That was fixed in `1.1.2` by  PR https://github.com/angular/material/pull/9574.

**Closed by Splaktar** 2020-09-07 03:38 UTC
Labels: resolution: duplicate, type: enhancement
