### ISSUE TITLE
ng-messages animation jump issue

### ISSUE THREAD

**Issue by romanchak** [angular/material#5147] opened 2015-10-14 08:13 UTC
Take a look at "Top Secret Project" > "Client Email" official example:
https://material.angularjs.org/HEAD/demo/input

Type "thatsmyname@gmail.c", then remove last character.
Error message will appear fully then disappear again and then animation will start.

Issue doesn't reproduce vice versa: in case if you already see the error and then pass the validation.
"thatsmyname@gmail." > "thatsmyname@gmail.c"

**Comment by topherfangio** [comment] 2015-10-29 18:42
I believe this is a duplicate of https://github.com/angular/angular.js/issues/12969

**Comment by ivanzvakoms** [comment] 2016-01-02 01:55
confirm it when use ```md-auto-hide="false"```

**Comment by EladBezalel** [comment] 2016-01-09 10:41
@topherfangio do you mind that this issue? i think you're the most related person to this issue right now

**Comment by ThomasBurleson** [comment] 2016-01-15 19:45
Duplicate

**Closed by ThomasBurleson** 2016-01-15 19:45 UTC
