### ISSUE TITLE
button: Disabled button inside dark-grey md-accent md-hue-3 toolbar has wrong text color

### ISSUE THREAD

**Issue by epelc** [angular/material#8819] opened 2016-06-21 17:21 UTC
**Actual behavior**:
-  What is the issue? * Disabled buttons inside of dark-grey hue-3 toolbars have white text indistinguishable from the regular toolbar text/buttons. Note this only happens when `blue-grey` is your accent palette.
-  What is the expected behavior? The text should be greyed so you can see that it is disabled

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue : http://codepen.io/anon/pen/NrbNpa?editors=1010
-  Details: Notice the top toolbar's second button is disabled but the text color is exactly the same as the enabled button

![image](https://cloud.githubusercontent.com/assets/5204642/16239518/2960b23c-37b3-11e6-881d-a9d38cadfde6.png)

**Angular Versions**: *
-  Angular Version: 1.5.6
-  Angular Material Version: 1.1.0-rc.5

**Additional Information**:
-  Browser Type: * chrome
-  Browser Version: * 51
-  OS: * os x 10.11.5
-  Stack Traces:

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by clshortfuse** [comment] 2016-06-22 00:29
Related/Duplicate of #7987

Tagging this to check with #8757 before finishing.

**Closed** 2016-07-25 15:21 UTC
Labels: resolution: duplicate
