### ISSUE TITLE
md-tabs: model.assign is not a function

### ISSUE THREAD

**Issue by robertbaker** [angular/material#3537] opened 2015-07-01 18:37 UTC
Did a bower update from master and my tabs broke. Looks like the tabs demo is also broken.
Not using a ngModel anywhere on tabs.
```
TypeError: model.assign is not a function
    at http://localhost:3000/bower_components/angular-material/angular-material.js:15382:22
    at MdTabsController.Object.defineProperty.set (http://localhost:3000/bower_components/angular-material/angular-material.js:15741:20)
    at init (http://localhost:3000/bower_components/angular-material/angular-material.js:15339:24)
    at new MdTabsController (http://localhost:3000/bower_components/angular-material/angular-material.js:15333:3)
    at Object.invoke (http://localhost:3000/bower_components/angular/angular.js:4443:17)
    at ident.$get.extend.instance (http://localhost:3000/bower_components/angular/angular.js:8991:34)
    at nodeLinkFn (http://localhost:3000/bower_components/angular/angular.js:8101:36)
    at compositeLinkFn (http://localhost:3000/bower_components/angular/angular.js:7534:13)
    at nodeLinkFn (http://localhost:3000/bower_components/angular/angular.js:8137:24)
    at compositeLinkFn (http://localhost:3000/bower_components/angular/angular.js:7534:13) <ui-view layout="column" layout-fill="" flex="" style="max-height: 100%" class="ng-scope">(anonymous function) @ angular.js:12314ident.$get @ angular.js:9101invokeLinkFn @ angular.js:8644nodeLinkFn @ angular.js:8142compositeLinkFn @ angular.js:7534publicLinkFn @ angular.js:7409updateView @ angular-ui-router.js:3959(anonymous function) @ angular-ui-router.js:3921parent.$get.Scope.$broadcast @ angular.js:16149$state.transitionTo.$state.transition.resolved.then.$state.transition @ angular-ui-router.js:3311processQueue @ angular.js:14551(anonymous function) @ angular.js:14567parent.$get.Scope.$eval @ angular.js:15830parent.$get.Scope.$digest @ angular.js:15641parent.$get.Scope.$apply @ angular.js:15935done @ angular.js:10356completeRequest @ angular.js:10528requestLoaded @ angular.js:10469
angular.js:12314 TypeError: model.assign is not a function
    at angular-material.js:15382
    at MdTabsController.Object.defineProperty.set (angular-material.js:15741)
    at Object.<anonymous> (angular-material.js:15388)
    at Object.constantListener [as fn] (angular.js:14196)
    at Scope.parent.$get.Scope.$digest (angular.js:15667)
    at Scope.parent.$get.Scope.$apply (angular.js:15935)
    at done (angular.js:10356)
    at completeRequest (angular.js:10528)
    at XMLHttpRequest.requestLoaded (angular.js:10469)
```

**Comment by robertmesserle** [comment] 2015-07-01 20:19
@robertbaker Can you provide a CodePen or some way for me to see this failing?  Also, what version of Angular and what browser?  I'm not able to recreate this error.

**Comment by robertmesserle** [comment] 2015-07-01 20:29
@robertbaker Do you have `md-selected` as an empty attribute in your `md-tabs` code?  If so, this is the cause.

**Comment by robertmesserle** [comment] 2015-07-01 20:29
Closing for now, will re-open with demo.

**Closed by robertmesserle** 2015-07-01 20:29 UTC
Labels: bug, in progress

**Comment by robertbaker** [comment] 2015-07-01 20:39
@robertmesserle  I have md-selected="1", removed it and it works. According to docs, it should be an integer. I tried "'1'", didn't work.

Also go to the master demo site, go to md-tabs demo. Now switch to a directive using the md-select dropdown. Page doesn't change but appears to, refresh browser, see correct page.

**Comment by robertmesserle** [comment] 2015-07-01 20:53
Ah, thanks for pointing that out!  This was experimental, so I'm going to switch back to the previous method for now.
