### ISSUE TITLE
select: every md-select breaks if one of them is destroyed while animating

### ISSUE THREAD

**Issue by chearon** [angular/material#10747] opened 2017-06-16 20:10 UTC
I could not find an existing issue for this, please feel free to close if it's already in here.

**Actual Behavior**:
 -  `What is the issue? *` If an `md-select` is removed while it's animating away, every `md-select` on the page will cease to function. Note that this is different than the `ng-if` issues reported to break `ng-model`.
 -  `What is the expected behavior?` Other `md-select`s should continue to function

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` https://jsfiddle.net/17yj06p7/
 -  `Details:` Change the second input, which will trigger the `ng-if` to remove the component while it's animating. The first input will no longer work.

**AngularJS Versions**: *
 -  `AngularJS Version:` 1.6.1
 -  `AngularJS Material Version:` 1.1.4

**Additional Information**:
 -  `Browser Type: *` Any
 -  `Browser Version: *` Any
 -  `OS: *` Any
 -  `Stack Traces:` N/A

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by joerideg** [comment] 2017-07-06 07:38
I have the same problem. I thought it should have been fixed in https://github.com/angular/material/issues/10453
However when updating to angular material 1.1.4 it did not fix this issue.

**Comment by chearon** [comment] 2017-07-06 13:11
We're using a workaround that is a little bit better than using `$timeout`:

```javascript
function ngClickHandler() {
  // hide() has already been called by angular internally. If we call it
  // again, it returns the promise created by the first call
  $mdSelect.hide().then(() => {
    // Put the code that would remove the md-select here
  });
}
```

I know it works in a `ng-click` callback but I haven't tried if it works for `ng-change`.

It's too bad that PR didn't fix it, completing the promise on `$destroy` should have done it.... maybe this is a slightly different scenario than the one that was fixing.

**Comment by joerideg** [comment] 2017-07-14 19:23
@chearon Where do you get the $mdSelect service from? Because its not documented as a service in the material library?

**Comment by chearon** [comment] 2017-07-14 19:34
Yeah it might just be used internally, but you should be able to inject it and use it.

**Comment by postama** [comment] 2017-08-30 16:16
We have a large application using angular material, and we experience this bug when updating from 1.0.9 to 1.1.4.

We experience it more often on larger, complex pages and slower API speeds (more difficult to reproduce locally than remote). We are not removing md-select like the reported bug by @chearon, but are changing it's options on click.

![2017-08-30_09-48-17](https://user-images.githubusercontent.com/10147635/29882998-0ade23ac-8d6c-11e7-9891-cd6f81712be2.gif)

I was not able to produce a small test case like @chearon was, but I believe it is the same root cause. The attached gif shows it occurring on our application

**Comment by camhart** [comment] 2017-09-25 17:15
I'm in a similar boat as @postama.  @postama Did you find a work around that worked for you?

**Comment by postama** [comment] 2017-09-25 18:34
@camhart No, we had to stay on angular material 1.0.9 until we have more time to investigate why it's happening.

**Comment by Splaktar** [comment] 2020-10-25 02:01
Fixed by PR https://github.com/angular/material/pull/10556 in `1.1.5`. Fixed [demo](https://jsfiddle.net/splaktar/wpgzs1be/3/) with `1.1.5`.

**Closed by Splaktar** 2020-10-25 02:01 UTC
Labels: resolution: fixed, type: bug
