### ISSUE TITLE
[master#5722449] md-autocomplete - md-not-found text doesn't show

### ISSUE THREAD

**Issue by evoker** [angular/material#4026] opened 2015-08-05 11:53 UTC
md-not-found doesn't work although it's defined.

When looking at the DOM, the code appears and it seems to check 3 variables:
$mdAutocompleteCtrl.matches.length
$mdAutocompleteCtrl.loading
$mdAutocompleteCtrl.hidden

the first and second variable come up true when you enter a string that returns on matches but the third variable returns false. The list is hidden sure but the not found part shouldn't be subjected to the same check, no?

The same directive has an ng-hide property that again checks $mdAutocompleteCtrl.hidden.

I guess the hidden check is not working properly or a different check is needed to show this.

**Comment by bluebirdtech** [comment] 2015-08-11 09:50
+1

This reproduces in the first demo: https://material.angularjs.org/HEAD/#/demo/material.components.autocomplete

**Comment by piyushchauhan2011** [comment] 2015-08-20 16:51
Is there any quick fix ? We are in production and needs `0.10.1` because `md-autocomplete` also have a bug related to scrolling in `0.10.0` which got fixed in latest version.

**Closed** 2015-09-10 17:45 UTC
