### ISSUE TITLE
Hyperlinks broken on mobile if jQuery is loaded

### ISSUE THREAD

**Issue by dozingcat** [angular/material#1972] opened 2015-03-19 23:59 UTC
Demo at http://codepen.io/anon/pen/LEMWqV . In desktop browsers the link works as expected, but in mobile browsers (or Chrome in device emulation mode) the link does not work unless you remove the jQuery script or change the URL to make it invalid.

A similar issue was described in https://github.com/angular/material/issues/1704 and apparently fixed, but now seems to be reoccurring.

**Comment by mckenzielong** [comment] 2015-03-20 03:41
Could be related to https://github.com/angular/material/commit/81bcf7fd15fd76f054814b34d8a877168fc6225c?

**Comment by topherfangio** [comment] 2015-09-08 17:50
Can you verify if this is still an issue? I am not able to reproduce it using the Codepen above in Chrome's device emulation mode or on my iPhone/iPad.

**Comment by topherfangio** [comment] 2015-11-03 23:23
Moving to RC6. Please let me know if you can provide a Codepen to reproduce or if this issue has been resolved.

**Comment by dozingcat** [comment] 2015-11-04 03:01
Seems to be resolved.

**Comment by topherfangio** [comment] 2015-11-04 18:35
@dozingcat Thanks! We'll go ahead and close it. Please open a new issue if you run into it again (and perhaps reference this one).

**Closed by topherfangio** 2015-11-04 18:35 UTC
Labels: for: internal contributor, needs: demo, type: bug
