### ISSUE TITLE
md-virtual-container - number of row

### ISSUE THREAD

**Issue by vigneshnrfs** [angular/material#5449] opened 2015-10-30 03:22 UTC
When the virtual repeat container is hidden initially and then shown, the container displays the data in a reduced height. In this codepen, it does not display any data at all. However in my application, it display 3 rows instead of eight.  I hide the content till the data is loaded from the server and then display the content.

http://codepen.io/anon/pen/pjKEvQ

**Comment by kseamon** [comment] 2015-11-03 15:09
Dupe of #4336. Hoping to fix this week.

**Closed by kseamon** 2015-11-03 15:09 UTC
