### ISSUE TITLE
0.10.1-rc1 md-select does not show pre selected Item

### ISSUE THREAD

**Issue by Tyrannmisu** [angular/material#3758] opened 2015-07-16 07:16 UTC
In 0.10.1-rc1 i have the issue that md-select always shows the input-container label or the placeholder-text until i manually select a value.

I can not get the md-select to show the value that is pre-set in the ng-model (and also matches the md-option ng-value).
The selected item is highlited in the select dropdown but will not be rendered inside the md-select until manually selected.

I would expect that md-select displays the content of it's model (if not undefined/null) and not the label or placeholder.

I use the async functionality.

It seems like md-select can't determine the selected item because the item-list is not loaded yet.
The old md-select still allowed to to display the pre-selected item via md-select-label and i can't find a way to achive something similar now.

Edit:
it works if i pre-load the option list but that destroys the purpose of the async-loading.

**Comment by rschmukler** [comment] 2015-08-03 19:48
@Tyrannmisu can you submit a demo?

**Comment by Tyrannmisu** [comment] 2015-08-04 06:52
Demo on 0.10.1-rc5:
http://codepen.io/anon/pen/oXJrwK

'Scooby Doo' won't show up as selected in the md-select until you click on it (no selection necessary) to load the async values.
It is not possible to pre-select something when using async-options.

**Comment by roymilder** [comment] 2015-08-17 05:08
@rschmukler if you could point me in a direction where to look, I can give it a try. We need this for ourselves as well and we can spend some time trying to solve this.

**Comment by Tyrannmisu** [comment] 2015-08-19 11:43
May be related to : https://github.com/angular/material/issues/4118

**Comment by rschmukler** [comment] 2015-09-10 17:12
Duplicate of #4118 - please follow that one.

**Closed by rschmukler** 2015-09-10 17:12 UTC
Labels: needs: demo, type: bug
