### ISSUE TITLE
md-list-item needs improved treatment of text overflow

### ISSUE THREAD

**Issue by hanthomas** [angular/material#2583] opened 2015-04-27 19:29 UTC
This issue is being created per suggestion from @marcysutton in issue #2438.  The resolution in #2438 while good, reveals a new problem when a list item contains long text.  Because line-height of the text DIV is set to 3.6rem, it causes the text to wrap with a ton of vertical white space.  It would be nice if we had some explicit control over text treatment in list items (other than simply overriding the styles).  Basically, I see a need for 1) wrapping text (but in a nice way with minimal vertical space) or 2) truncate the text with either ellipses or none.

**Comment by rschmukler** [comment] 2015-09-10 18:28
Duplicate of #2199, closing this one.

**Closed by rschmukler** 2015-09-10 18:28 UTC
Labels: ui: CSS
