### ISSUE TITLE
md-select value not populated until you click on the select

### ISSUE THREAD

**Issue by nmaves** [angular/material#2588] opened 2015-04-27 21:44 UTC
We have a select that is populated by an ajax call.  The value in the select is correct on the page.  The label is just not shown until you click on the select.  Once you do you will see that the correct value is selected.  If you click off of the select the correct label that was preselected is shown.

Here is the select code.

```
            <md-select placeholder="Pick" ng-model="browseController.currentKind" ng-change="browseController.reload()">
                <md-option ng-value="kind.id" ng-repeat="kind in browseController.kinds">
                    {{kind.name}}
                </md-option>
            </md-select>
```

And here is the code in the controller to populate the options as well as set the value of the select.

```
        KindsModel.getKinds()
            .then(function (kinds) {
                browseController.kinds = kinds;
                browseController.currentKind = $stateParams.kindId;
            });
```

**Comment by ngraef** [comment] 2015-04-27 23:31
Duplicate of #2575, though this is a good use case to test.

**Comment by rschmukler** [comment] 2015-05-14 17:31
Fixed by #2575

**Closed by rschmukler** 2015-05-14 17:31 UTC

**Comment by wembernard** [comment] 2015-09-17 10:20
Not fixed by #2575

I finally realised if `md-option`(s) are not resolved, placeholder won't display which makes `md-on-open` a broken feature.

Here is a [demo](http://codepen.io/wembernard/pen/garLQK) that show the problem.
