### ISSUE TITLE
mdTimepicker component

### ISSUE THREAD

**Issue by ericodes** [angular/material#5452] opened 2015-10-30 09:06 UTC
The new datepicker is awesome.

Was wondering if a timepicker that works in Safari, Firefox, and IE is in the works?

I love the UI for the Google Maps timepicker, since you can both type in it, or scroll for a time.

Nice to haves:
1. Being able to tab from minutes to seconds to meridian.
2. Being smart enough so that typing:
06:25 -> 6:25 AM
6:25 -> 6:25 AM
14:25 -> 2:25 PM
2:25 pm -> 2:25 PM
2:25pm -> 2:25 PM

Another inspiration which has tons of neat options: https://github.com/jonthornton/jquery-timepicker

**Comment by ngraef** [comment] 2015-11-09 22:16
Duplicate of #5029

**Closed** 2015-11-09 22:23 UTC
Labels: type: component

**Comment by rudzikdawid** [comment] 2015-12-19 18:18
http://simeonc.github.io/sc-date-time/material.html
![timepicker](https://cloud.githubusercontent.com/assets/7476577/11914562/258b19f0-a685-11e5-9565-3fb82f3f8143.jpg)

timepicker with material style :)
