### ISSUE TITLE
md-chips should allow multiple selects

### ISSUE THREAD

**Issue by csvan** [angular/material#4657] opened 2015-09-15 23:26 UTC
Currently, it is only possible to select a single chip in an `md-chips` instance at a time. It would be useful if several chips could be marked as selected as well, akin to how this is handled in `md-select` when the `multiple`  attribute is set.

**Comment by jaymanned** [comment] 2015-09-29 16:58
I absolutely miss this feature. Any workaround?

**Comment by jaymanned** [comment] 2015-09-29 17:00
Of course we would need a way to know which chips have been selected. And it would be great if it worked also on static chips (which I simulate by providing an empty `md-chip-remove` element)

**Comment by LisaTatum** [comment] 2016-02-03 22:10
@jaymanned @ThomasBurleson 

I miss this feature too and I use a checkbox workaround at the moment:

``` 
<md-chips md-transform-chip="newSubject($chip)" md-on-add="addSubjectChip($chip)" placeholder="Enter new subject" 
                  secondary-placeholder="Enter new subject" ng-model="subjectChips">
            <md-chip-template>
                <md-checkbox ng-model="$chip.isSelected">{{$chip.name}}</md-checkbox>
             </md-chip-template>
        </md-chips>
```

+1 for multipe selections with a md-chips.selected property

**Comment by jbadeau** [comment] 2016-03-13 07:10
+1 for multipe selections with a md-chips.selected property

**Comment by ThomasBurleson** [comment] 2016-04-28 20:23
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).

**Closed by ThomasBurleson** 2016-04-28 20:23 UTC
Labels: priority: low, type: enhancement

**Comment by Splaktar** [comment] 2018-04-25 03:01
Duplicate of https://github.com/angular/material/issues/3399.
