### ISSUE TITLE
md-autocomplete with floating-label and icon

### ISSUE THREAD

**Issue by Raidri** [angular/material#7120] opened 2016-02-11 09:51 UTC
Hi,

is there a way to set an md-icon to the md-autocomplete like the md-input-container?
If i have a form with input container and icons and then a md-autocomplete without an icon it looks ugly.

it would nice if i can do something like this one:
```html
<md-autocomplete md-selected-item="rdc.relation"
			                 flex="50"
			                 required>
<md-icon>&#xE88F;</md-icon>
				<md-item-template>
					<span md-highlight-text="preisstufe">{{item.bezeichnung}}</span>
				</md-item-template>
				<md-not-found>
					Keine Preisstufe gefunden.
				</md-not-found>
			</md-autocomplete>`

**Comment by DevVersion** [comment] 2016-02-11 10:47
This seems to be a duplicate of #6150

**Closed** 2016-04-28 19:42 UTC

**Comment by jefferson-silva** [comment] 2016-08-22 17:55
+1
