### ISSUE TITLE
CSS Error on v1.0.0 and v1.0.1 while app deployment in production mode.

### ISSUE THREAD

**Issue by tenshiAMD** [angular/material#6614] opened 2016-01-11 07:37 UTC
This error appeared while deploying the app in production mode, this persist in v1.0.0 and v1.0.1. Could you check this guys? In v1.0.0rc7, the deployment is successful. It keeps on failing in v1.0.0 and v1.0.1.

<b>Sass::SyntaxError: Invalid CSS after "...a screen\0 and ": expected "{", was "(max-width: 599..." (sass):2235</b>

**Comment by odedniv** [comment] 2016-01-11 17:39
+1

**Comment by macchie** [comment] 2016-01-11 18:59
+2

**Comment by kouak** [comment] 2016-01-13 07:47
Duplicate of #6304 ?

**Comment by jelbourn** [comment] 2016-01-15 20:02
Yes, this is a dupe.

**Closed by jelbourn** 2016-01-15 20:02 UTC
Labels: P1 - Broken Renders / Major Use Cases
