### ISSUE TITLE
md-menus not closing when using ng-repeat

### ISSUE THREAD

**Issue by reylibutan** [angular/material#5149] opened 2015-10-14 09:25 UTC
```HTML
<md-menu-bar>
      <md-menu ng-repeat="section in sections">
        <md-button class="navButton" ng-click="$mdOpenMenu()">
          {{section.name}}
        </md-button>
        <md-menu-content>
          <md-menu-item>
            <md-button>Subsection 1</md-button>
          </md-menu-item>
        </md-menu-content>
      </md-menu>
</md-menu-bar>
```

I am doing something like above but unfortunately, if I click a menu, it stays open even if I click other buttons.

I just want it to have the same behavior as

https://material.angularjs.org/latest/demo/menuBar

P.S. If I don't use ng-repeat (meaning, menus are static), it works fine though.

**Comment by reylibutan** [comment] 2015-10-19 09:20
Any ideas how I could fix this? I will try to setup a plunker for this one.

**Comment by marioaleogolsat** [comment] 2015-10-19 10:54
You can inject $mdMenu on your controller and use $mdMenu.hide(); by the end of the function called by the item of the menu.

**Comment by johnSowingo** [comment] 2015-10-26 17:38
+1

**Comment by andrew-cunliffe** [comment] 2015-10-30 18:30
Duplicate of #4484  ... but would be nice to have an interim solution as this is rather frustrating.

**Closed** 2015-11-11 22:28 UTC
Labels: priority: high
