### ISSUE TITLE
Chips with autocomplete display blank item when it is not in the item list

### ISSUE THREAD

**Issue by meassinal** [angular/material#3476] opened 2015-06-26 09:49 UTC
As I test component <b>Chips</b> with autocomplete in demo mode with latest version of material and angular 1.4.1, I found bugs with empty items.

![screen shot 2015-06-26 at 4 44 14 pm](https://cloud.githubusercontent.com/assets/2950432/8374821/b6b83db0-1c22-11e5-994b-063e3160d29e.png)

**Comment by typotter** [comment] 2015-08-11 18:47
duplicate of #3475

**Closed by typotter** 2015-08-11 18:47 UTC
Labels: summit
