### ISSUE TITLE
Date Picker Label

### ISSUE THREAD

**Issue by cranesandcaff** [angular/material#4826] opened 2015-09-24 21:39 UTC
Is there anyway to include a label on the date picker? Without a label the inputs are off center and not in line with other inputs.

**Comment by rlecaro2** [comment] 2015-09-25 14:20
+1.

**Comment by jelbourn** [comment] 2015-09-28 18:17
Dupe of #4233

**Closed by jelbourn** 2015-09-28 18:17 UTC

**Comment by sunnyshah01** [comment] 2015-10-12 08:52
+1
