### ISSUE TITLE
md-disabled-thumb bad position in md-slider when disabled

### ISSUE THREAD

**Issue by fcor** [angular/material#2424] opened 2015-04-20 12:10 UTC
You can see the bug on the material angularjs website : https://material.angularjs.org/#/demo/material.components.slider

When ng-slider is disabled, the white circle (.md-disabled-thumb) is not centered with the grey one (.md-thumb)

**Comment by ThomasBurleson** [comment] 2015-04-20 15:50
Duplicate of #2279

**Closed by ThomasBurleson** 2015-04-20 15:50 UTC
