### ISSUE TITLE
Issues with md-contact-chips v11

### ISSUE THREAD

**Issue by lievenjanssen** [angular/material#4836] opened 2015-09-25 11:59 UTC
Screenshot v10.1:

![image](https://cloud.githubusercontent.com/assets/958643/10099776/21213326-638d-11e5-9648-b55ca07c816b.png)

Screenshot v11:

![image](https://cloud.githubusercontent.com/assets/958643/10099786/3848ec38-638d-11e5-994f-94fc5f33609b.png)

Screenshot HEAD:

![image](https://cloud.githubusercontent.com/assets/958643/10099795/52a03028-638d-11e5-8c11-ded93d32acb0.png)

md-contact-chips looks broken (not working properly on v11, looking strange on HEAD), isn't v10.1 the expected behaviour?

**Comment by topherfangio** [comment] 2015-09-25 13:00
Duplicate of #4450. 0.10.1 behavior is indeed correct.

**Closed by topherfangio** 2015-09-25 13:00 UTC
