### ISSUE TITLE
scss bower-material support

### ISSUE THREAD

**Issue by itajaja** [angular/material#1161] opened 2015-01-11 23:31 UTC
I am using bower-material, Is there a way to provide the sass files along with the compiled css?

**Comment by bogdandjukic** [comment] 2015-01-23 09:43
We would love that too!
Looking forward to it, as we prefer scss over the already compiled css.

**Comment by PaulMougel** [comment] 2015-01-23 11:07
Duplicate of #381

**Comment by nicbon** [comment] 2015-02-26 09:32
#381 has been closed but I believe there are valid use cases for this request.

It is my understanding that the source repository is meant to be used by whoever wants to develop angular-material and the deployment repository is for developers that use angular-material in their own projects.

If that's the case, I would argue that there are valid uses cases for exposing the SCSS in the project builds repository. In these cases the developer doesn't want to mess with the original angular-material css but rather use the SCSS as a library to build his own classes. For instance I might want to access the SCSS variables, or use the handy mixins to build more *-sm *-gt classes.

I personally see the SCSS as being integral part of the library exposed to the developers rather than purely part of the library sources.

**Comment by itajaja** [comment] 2015-02-26 09:42
an example of something similar is done in this [repo for bootswatch](https://github.com/log0ymxm/bootswatch-scss). The use cases for this are several, of course the most important is building additional element that leverage existing mixins. Exposing just the [`core/style`](https://github.com/angular/material/tree/master/src/core/style) folder would be already a big improvement. Another use case would be to intercept and modify the variables before they are used in the material style sheets, or simply using the variables in your own style sheets.

**Comment by paramburu** [comment] 2015-03-04 20:30
+1

**Comment by marcysutton** [comment] 2015-03-13 00:13
@rschmukler should chime in on this, but I believe the reason CSS is provided in a compiled format is due to theming support, where theme CSS is generated dynamically.

**Comment by pzurowski** [comment] 2015-03-16 09:16
+1

**Comment by johannesjo** [comment] 2015-04-05 18:05
+1

**Comment by johannesjo** [comment] 2015-04-05 19:34
For those interested I extracted the styles and put them into their own repository:
https://github.com/johannesjo/angular-material-sass-files

**Comment by marcysutton** [comment] 2015-04-05 19:58
@johannesjo how will that be sustainable? It looks like there are specific filenames referenced and not all of them are present (ex. typography.scss). Also, what about the themes scss?

**Comment by johannesjo** [comment] 2015-04-05 20:01
@marcysutton the colors would have to be replaced with sass-variables/functions. Still working on it. Thank you for reporting the issue, but maybe the repos page is a better place for this. I'm glad for help and suggestions.

**Comment by oste** [comment] 2015-04-05 20:23
:+1: I am also lost on how to properly use the .scss files. There is the Gulp build process but that seems overkill for this use case. Looking forward to seeing how this one pans out :)

**Comment by tkrotoff** [comment] 2015-04-14 09:38
+1

**Comment by stryju** [comment] 2015-07-15 12:36
this would be great

**Comment by ThomasBurleson** [comment] 2015-07-15 14:24
Each build of Angular Material now [also] deploys [angular-material.scss](https://github.com/angular/bower-material/blob/master/angular-material.scss); with required mixins and variables.  

*  This resource was deployed for developers wanting the SCSS master file.
*  The AM team will **not** document how to compile or use this file, etc.

**Closed by ThomasBurleson** 2015-07-15 14:24 UTC

**Comment by stryju** [comment] 2015-07-15 14:47
woohoo! :confetti_ball:

**Comment by breity** [comment] 2015-07-21 18:51
This is great!  Thanks.

**Comment by itajaja** [comment] 2015-07-21 18:53
:tada: thanks!
