### ISSUE TITLE
md-fab-speed-dial opening when moving cursor way below it

### ISSUE THREAD

**Issue by MilosStanic** [angular/material#4257] opened 2015-08-20 10:27 UTC
Please take a look at the animated gif, the fab speed dial opens when I pass with my mouse way below the actual fab. 

![image of fab](http://g.recordit.co/Dr5YjxMhrO.gif)

**Comment by topherfangio** [comment] 2015-08-20 13:36
This was the original/intended behavior, but with the latest code (https://material.angularjs.org/HEAD/#/demo/material.components.fabSpeedDial) we removed this as the default and made it an option by using `ng-mouseenter` and `ng-mouseleave` tied to the `is-open` attribute.

Can you take a look at the latest demos and tell me if I am misunderstanding your issue? If so, could you provide a codepen showing the problem?

Thanks!

**Comment by MilosStanic** [comment] 2015-08-20 18:13
I think you missunderstood. 
I know that the default behaviour has been changed to trigger FAB on click instead on hover. 
But here, I'm showing that it triggersw when I pass my mouse cursor not *over* the trigger FAB, but 50 pixels *below* it.

The screen I posted was shot on the very link you suggested, on the second (lower) example.

**Comment by Yimiprod** [comment] 2015-08-26 16:14
+1, and for me, with version 0.10.1, hover on fab-trigger and fab-action deploy it, not on click on trigger.

**Comment by topherfangio** [comment] 2015-09-02 21:34
@MilosStanic Indeed, the `ng-mouseenter` and `ng-mouseleave` are on the speed dial itself which currently includes the invisible area where the actions will eventually appear when hovered. This is how the current speed dial in Google Inbox works (when you hover your mouse 50-100px above the trigger FAB, it opens). The plan is to add an option in 0.12 which disables this and allows the hit area to be only the same size as the trigger.

For consolidation purposes, I am going to go ahead and close this since #4259 states the exact issue a bit better.

@Yimiprod If you are saying that you can no longer click the trigger to open the speed dial, could you please open a new issue as that sounds like a separate problem?

**Closed by topherfangio** 2015-09-02 21:34 UTC
