### ISSUE TITLE
mdSelect: differences from plain HTML and no label?

### ISSUE THREAD

**Issue by Ugoku** [angular/material#1662] opened 2015-02-25 13:47 UTC
First of all, I know the mdSelect element is *very* new, so if you are already working on this, I apologise for my hastiness :) The mdSelect is a crucial part of a web app I am developing at the moment, so I jumped at the chance of working with it.

I noticed two problems though:
First of all, with a regular input box you can do this and it looks great:
```
<md-input-container>
    <label>Address</label>
    <input ng-model="company.Address">
</md-input-container>
```

However, with an mdSelect I could see no way of adding a proper label to the element. This looks horrible:
```
<div>
    <label>Users</label><br>
    <md-select ng-model="">
        ...options here...
    </md-select>
</div>
```
The demos for mdSelect do not show a label, so I can't use them as inspiration. Is there a proper solution for this, or do I need to put something together myself?

Second, there is a *huge* difference between creating a dropdown in plain HTML and creating one using mdSelect. Use case: you are viewing a company detail page that you want to assign a user to.

With plain HTML it's as simple as this:

```
<select>
    <option value=1>Alice
    <option value=2>Bob
    <option value=3>Carol
</select>
```
I get the selected value from the backend (i.e. a `company` object with a `user` property) and a list of users (each having an `ID` and a `Name` property). Then I can generate the `<select>` and fill the selected value easily.

I tried doing the same with an mdSelect:
```
<md-select ng-model="company.user">
    <md-option ng-repeat="user in users" ng-value="user.ID">{{user.Name}}</md-option>
</md-select>
```

But when I select a new user, it shows the ID instead of the name. So instead, I have to add an mdSelectLabel, use the full object as the ngValue, which means when I get the data from the backend I have to convert this to an object, and when I save I have to convert it back. Why is it so much more work?

```
<md-select ng-model="selectedUser">
    <md-select-label>{{selectedUser.Name}}</md-select-label>
    <md-option ng-repeat="user in users" ng-value="user">{{user.Name}}</md-option>
</md-select>
```
```
$scope.selectedUser = $filter('filter')($scope.users, function(user){return user.ID == $scope.company.UserID})[0];
```

Am I completely missing something here, or is it really this much work to generate a working mdSelect?
Thanks in advance for all your hard work, it is much appreciated!

**Comment by Toilal** [comment] 2015-02-25 14:18
I hope it will be improved too, but from what I know, it's the current way to do ... I've written exactly the same for my app.

The md-select-label is really verbose, and force use to store the whole object instead of ID in ng-model.

**Comment by rschmukler** [comment] 2015-02-25 15:04
@Toilal and @Ugoku are you guys using 0.8.0 or 0.8.1? The select label rendering should have been fixed in 0.8.1. See #1601.

The other issue is a duplicate of #1586. I'm keeping this open to ensure that the first bug (#1601) isn't still in 0.8.1. If it is, this issue will serve for that. If not, please close this issue

**Comment by Toilal** [comment] 2015-02-25 15:06
Right, i'm using `0.8.0-master-d988774` because of bug #1643 occuring in master.

**Comment by rschmukler** [comment] 2015-02-25 15:12
Alright. Well this issue is resolved. Will be taking care of #1643 asap.

**Closed by rschmukler** 2015-02-25 15:12 UTC
Labels: enhancement, question

**Comment by Ugoku** [comment] 2015-02-26 09:00
Ah, I was indeed also using 0.8.0. Thanks for the update, I will look into this today.

**Comment by Ugoku** [comment] 2015-02-26 09:26
Update: it seems to be 99% resolved.
I can now use the `user.ID` as ngModel and `user.Name` is now properly set as label. Changing the mdSelect selected item works as expected, the only thing that doesn't work for me yet is the initial state. But seeing the rest of the bug is fixed, I'm probably missing something myself so I'll dig a bit deeper :)
Thanks for the help!

**Comment by Toilal** [comment] 2015-02-26 09:41
Works for me, even for initial state. Thanks !
