### ISSUE TITLE
md-fab-speed-dial: does not animate the first time

### ISSUE THREAD

**Issue by thanhphat** [angular/material#6594] opened 2016-01-08 08:10 UTC
I use angular material 1.0.1.
The fab speed dial can not view good in the first time.
Here is my code
    html
<md-fab-speed-dial md-direction="up" class="md-scale md-fab-bottom-right">
    <md-fab-trigger>
        <md-button aria-label="menu" class="md-fab md-warn">
            <md-icon md-svg-src="assets/svg/ic_add_white_36px.svg" aria-label="menu"></md-icon>
        </md-button>
    </md-fab-trigger>

    <md-fab-actions>
        <md-button aria-label="Tips" class="md-fab md-raised md-mini md-accent"
                   ng-click="ul.openDialog($event, item)">
            <md-icon md-svg-icon="description" aria-label="Tips"></md-icon>
        </md-button>
        <md-button aria-label="Check list" class="md-fab md-raised md-mini md-warn"
                   ng-click="ul.openDialog($event, item)">
            <md-icon md-svg-icon="list" aria-label="Check list"></md-icon>
        </md-button>
        <md-button aria-label="News" class="md-fab md-raised md-mini md-primary"
                   ng-click="shareHealthNews($event)">
            <md-icon md-svg-icon="web" aria-label="News"></md-icon>
        </md-button>
    </md-fab-actions>
</md-fab-speed-dial>
    

This is screen capture result and DOM
<img width="115" alt="screen shot 2016-01-08 at 3 03 14 pm" src="https://cloud.githubusercontent.com/assets/1578134/12193290/654ba3ae-b619-11e5-947b-f7cbf1186865.png">
<img width="857" alt="screen shot 2016-01-08 at 3 07 04 pm" src="https://cloud.githubusercontent.com/assets/1578134/12193306/8817a374-b619-11e5-9c05-e16793a3166b.png">

**Comment by marino-oneshoe** [comment] 2016-01-11 16:31
+1

**Comment by marino-oneshoe** [comment] 2016-01-11 16:38
use ngCloak like:
<md-fab-speed-dial md-open="ctrl.fabOpen"  class="md-scale" ng-cloak>

**Comment by thanhphat** [comment] 2016-01-11 16:51
I used ngCloak but it can't be fixed.

**Comment by marino-oneshoe** [comment] 2016-01-11 22:18
it look like if the fab component is not initiate properly. The md-fab-action-item needs to get inline styles. 
like so: 
`<div class="md-fab-action-item" style="opacity: 0; transform: scale(0.1); transition-delay: 2ms; z-index: 22;">`

These styles are set by the md-fab-speed-dail component. https://github.com/angular/material/blob/master/src/components/fabSpeedDial/fabSpeedDial.js 
i think is somewhere at line 209. 

There is also a discussion at https://github.com/angular/material/issues/6111 

This thread is a duplicate.

**Comment by ThomasBurleson** [comment] 2016-01-13 02:34
Duplicate of #6111.

**Closed by ThomasBurleson** 2016-01-13 02:34 UTC
