### ISSUE TITLE
RTL Layout 

### ISSUE THREAD

**Issue by EMIN3M1986** [angular/material#2817] opened 2015-05-12 07:11 UTC
Hi.
how can I change the whole layout of the angularjs material component to RTL ?

**Comment by ThomasBurleson** [comment] 2015-05-12 14:02
We will be using the [HTML attribute 'dir'](https://github.com/angular/material/blob/master/src/core/style/mixins.scss#L45-L51) to determine RTL support see:

```scss
/* mixin definition ; sets LTR and RTL within the same style call */
@mixin rtl($prop, $value, $rtl-value) {
  #{$prop}: $value;
  html[dir=rtl] & {
    #{$prop}: $rtl-value;
  }
}
```

We have only recently started to add RTL support. Many of our components will be updated with improved support for the 0.10 release.

**Comment by EMIN3M1986** [comment] 2015-05-13 04:38
Thanks Thomas for you answer.
When is the time of next release ?

**Comment by ThomasBurleson** [comment] 2015-05-13 11:42
See https://github.com/angular/material/milestones for details. Please note
this are `targeted` dates; not guaranteed dates.

**Comment by behiunforgiven** [comment] 2015-05-31 11:32
How can I use rtl mixin to change the layout?

**Comment by ErinCoughlan** [comment] 2016-09-07 18:15
Duplicate of #1080, which adds RTL support for all components.

**Comment by ThomasBurleson** [comment] 2016-09-07 18:16
Duplicate.

**Closed by ErinCoughlan** 2016-09-07 18:15 UTC
Labels: i18n: bi-directional, P4 - Reported By or General PRs/Errors or Edge Cases
