### ISSUE TITLE
md-list-item contains extra <span flex></span> at the end of the item

### ISSUE THREAD

**Issue by leonxchen** [angular/material#8442] opened 2016-05-12 18:49 UTC
**Actual behavior**:
-  What is the issue? *
md-list-item contains extra <span flex></span> at the end of the item

**CodePen** or Steps to reproduce the issue: *
-  Details: 
Here is the code I have:
`<md-list class="md-dense" flex>
            <md-list-item style="padding-left: 20px;" class="md-2-line" ng-repeat="item in someList">
                <div layout="row" class="md-list-item-text">
                    <div>
                        <h4>title</h4>
                        <p class="md-subhead">subtitle</p>
                    </div>
                    <span flex></span>
                    <md-button class="md-icon-button" ng-click="doSomething()">
                        <md-icon class="material-icons">click</md-icon>
                    </md-button>
                </div>
                <md-divider ></md-divider>
            </md-list-item>
        </md-list>`
And my html inspection on the item looks like:
`...
<div layout="row" class="md-list-item-text layout-row">...</div>
<md-divider></md-divider>
<div class="flex"></div>
<div class="_md-secondary-container"></div>
`

**Angular Versions**: *
-  Angular Material Version:rc-1.1.0-rc2

**Additional Information**:
-  Browser Type: * Safari, Chrome
-  Browser Version: * Safari Version 9.1 (10601.5.17.4), Chrome Version 49.0.2623.112 (64-bit)
-  OS: * OS X Yosemite 10.10.5 (14F1713)

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by DevVersion** [comment] 2016-05-12 19:12
Duplicate of #7976. Fix is pending.

**Closed by DevVersion** 2016-05-12 19:12 UTC
