### ISSUE TITLE
toolbar: inside md-dialog does not occupy 100% width in Chrome

### ISSUE THREAD

**Issue by necramirez** [angular/material#9701] opened 2016-09-27 09:25 UTC
**Actual Behavior**:

I'm seeing a gap at the right-most edge between the `md-toolbar` and `md-dialog`. There should be none -- the `md-toolbar` should take up 100% of the width.

**CodePen** (or steps to reproduce the issue): *

No need for CodePen, the issue is visible in the Angular Material Dialog demo:  https://material.angularjs.org/latest/demo/dialog

To reproduce, open that URL in Chrome on Mac OS X, then gradually resize the browser window's width. At regular intervals, the gap appears like this:

![screen shot 2016-09-27 at 5 01 14 pm](https://cloud.githubusercontent.com/assets/167253/18867461/e47d0a0a-84d6-11e6-8656-2f709ba1a5ee.png)

**Angular Versions**: *
-  `Angular Version:` 1.5.5
-  `Angular Material Version:` 1.1.1

**Additional Information**:
-  `Browser Type: *` Google Chrome
-  `Browser Version: *` Version 52.0.2743.116 (64-bit)
-  `OS: *` Mac OS X 10.11.6
-  `Stack Traces:` (none)

**Comment by clshortfuse** [comment] 2016-11-01 09:59
This seems to be a rendering issue with subpixel rendering and the fact the element is being 3D rendered. It can be fixed by popping the element back to 2D once the animation is over, but, if we do that, we'll have a webkit-specific 2D-rendering rounded corner bug.

**Comment by Splaktar** [comment] 2020-12-16 02:25
This was certainly an issue in the past, but I'm no longer able to reproduce it with AngularJS Material 1.2.1 and Chrome 87.

**Closed by Splaktar** 2020-12-16 02:25 UTC
Labels: browser: Chrome, resolution: can't reproduce
