### ISSUE TITLE
mdInput: error message is not shown with md-auto-hide option

### ISSUE THREAD

**Issue by montgomery1944** [angular/material#7653] opened 2016-03-20 17:12 UTC
When mdInput has more than one error message in ngMessages and the input remains invalid during the change of message, the message is not shown. This is caused by an issue in ngMessageAnimation which does not fire showMessage, when md-auto-hide option in turned on. I think that ngMessageAnimation should show the message when the mdInput has md-input-invalid class.

Demo can be found at http://codepen.io/anon/pen/zqZZex.
To reproduce this issue:
1. Type "a" in input
2. Leave the input.
3. Enter the input.
4. Delete "a".
Expected result: "required" message should be visible.
Current result: no message is shown.

Original implementation was added in https://github.com/angular/material/commit/cf7f21aa6c633d9f0bd22013e9a79f99b82b16af.

Tested with jQuery 2.2.2, Angular 1.5.2 and Angular Material 1.1.0-rc1.

**Comment by montgomery1944** [comment] 2016-03-20 18:24
I've created a pull request to fix this issue.

**Comment by DevVersion** [comment] 2016-03-20 18:36
@montgomery1944 As said in your PR, we are working on that issue.

In addition to that, your issue is a duplicate of some previous tracked issues. That's why I close your issue.

-#6767, #6399, #6443

**Closed by DevVersion** 2016-03-20 18:36 UTC
