### ISSUE TITLE
mobile browser's minimal-ui feature is gone because of 'md-content'

### ISSUE THREAD

**Issue by JoeHetfield** [angular/material#3160] opened 2015-06-07 11:12 UTC
In a normal web page, if it is long enough, the mobile browser will  enable 'minimal-ui' mode automatically. (mobile safari will hide it's toolbar at the bottom and smaller the address bar on the top. mobile chrome, which don't have the bottom toolbar will shrink it's  address bar smaller)

I found this feature never happened in angular material. because if I want a sticky tool bar on the page, I must place it above on a md-content element in a column mode flex box, and md-content is self-scrollable, 100% height view-port, and never make the page longer than the browser view-port. 

As a result, the whole page will always be 100% height as the browser view-port and minimal-ui won't be triggered. Of course I can't cancel the use of md-content, but I lost the sticky tool bar and the nice md-scroll-shrink feature.

Is there any work around about this?  or I just didn't get it ?

Thanks in advance.

**Comment by chr22** [comment] 2015-06-07 21:04
+1

**Comment by psmolinsky** [comment] 2015-06-08 07:53
+1

**Comment by epelc** [comment] 2015-06-09 13:54
Duplicate of #1939

**Closed** 2015-09-04 15:17 UTC
Labels: resolution: duplicate
