### ISSUE TITLE
Ability to move a dialog box

### ISSUE THREAD

**Issue by JohnAReid** [angular/material#1118] opened 2015-01-06 12:12 UTC
Is it possible to change the screen location of the dialog box by using click and drag?

The reason I ask is that sometimes the box hides some of the screen display which would be useful to see before closing the dialog. 

Example of suggested:  http://embed.plnkr.co/8CHoiN/preview

**Comment by ThomasBurleson** [comment] 2015-01-06 15:16
@JohnAReid - Great suggestion. 

> An additional  option is to allow the dialog position to persist and reopen to last position.

**Comment by epelc** [comment] 2015-01-07 18:38
Is this really needed? It seems more like a ui problem which you could solve by laying out your data differently.

Maybe it should be in an add on project that's not specific to dialogs or even angular-material. Not entirely sure but it still sounds like your data could be layed out differently.

**Comment by ThomasBurleson** [comment] 2015-01-07 19:51
@epelc - the ability to drag UI widgets/views is a fundamental need for all UI frameworks. Even the Material design shows a drag feature within its design concepts: [Meaningful Transitions](http://material-design.storage.googleapis.com/publish/v_2/material_ext_publish/0B2wX4iIvu8L6aHVOOGxBOW5jZlE/animation-meaningfultransitions-visualcontinuity_music-tablet-01_xhdpi.webm)

**Comment by epelc** [comment] 2015-01-07 19:56
@ThomasBurleson I think dragging general widgets should be supported. However it seems a bit weird with dialogs unless you wanted a swipe down from top to hide gesture. But just moving it around to view content behind it sounds like a layout problem to me.

**Comment by JohnAReid** [comment] 2015-01-07 21:05
ED - If you refer to dialog box as simply a means of displaying a message on the screen with some user interaction, then yes having the ability to move the box around is overkill.  

However if instead the dialog is used get the immediate attention of the user and to do some action (other than OK or cancel) then the ability to move the box is more important. 

I am using it in speech recognition with the dialog box being used to tell the user when to speak but they also need to know what to say which is being partly hidden by the dialog box. As the dialog box is opened by code (not by a user click event and therefore no targetEvent) it is shown in the center of the screen. Even if I could control where the dialog box was located (i.e. top left - by faking the targetEvent values) it would still cause problems when used on different size displays. Hence the request for drag ability.

Hope that explains my request in a bit more detail.

**Comment by epelc** [comment] 2015-01-07 21:16
@JohnAReid Maybe a picture would help to better explain your use case. However you should be able to use a custom dialog template and add a class or id to it so you can specify offsets via css. This would allow you to at least set the initial position.

As a side note on github if you put an `@` in front of someones username it will usually send them a notification :)

**Comment by JohnAReid** [comment] 2015-01-07 21:41
@epelc Thanks for the info on github.

Screen shot id as follows: 

![matvoice](https://cloud.githubusercontent.com/assets/7714810/5653841/b6acb186-96b5-11e4-857d-8d30e0171256.png)

As a side note I can not get the dialog box to reduce in width to less than that shown in the image.

**Comment by epelc** [comment] 2015-01-07 21:50
@JohnAReid Something sliding up from the bottom with your microphone icon and speak now under it would seem like a much better solution. Perhaps a `bottomSheet` would work for this.

You can find the demo for it [here](https://material.angularjs.org/#/demo/material.components.bottomSheet)
 and the docs [here](https://material.angularjs.org/#/api/material.components.bottomSheet/service/$mdBottomSheet) its usage is similar to `mdDialog`.

**Comment by JohnAReid** [comment] 2015-01-07 22:10
@epelc The bottomSheet would be a solution, however the dialog has one added feature -  the user cannot click anywhere else in the window (which in my case means they cannot  click on the speakers and cheat) .

I am not too worried  about my request - as I am going to move most of the screen objects (i.e. everything below the toolbar) into the dialog box which I think will make it a lot more clearer for the user.

However on a general note the request for a moveable dialog box is not unique (plenty examples on google search)  and I think it would be shame for Material Design to take a narrow view (which might stop developers adopting it) - on the other hand most solutions require the use of the full version of jquery which is a further overhead..

**Comment by epelc** [comment] 2015-01-07 22:14
The bottom sheet will dismiss itself if the user clicks an where above it
similar to how the dialog works.

I think your issue is more of a layout problem. But it might be good to
support a draggable dialog.

**Comment by rschmukler** [comment] 2015-02-02 18:39
Closing as a duplicate of #1206

**Closed by rschmukler** 2015-02-02 18:39 UTC
Labels: enhancement, gestures
