### ISSUE TITLE
Angular-Material Demo Codepen examples don't run

### ISSUE THREAD

**Issue by scottrodoty** [angular/material#6780] opened 2016-01-20 14:47 UTC
None of the links to codepen examples on the Angular-Material site work.  I believe this is because the link to angular-material.js is bad. If you look in the settings on the demo codepen examples, it is pointing to:

http://localhost:8080/angular-material.js

![image](https://cloud.githubusercontent.com/assets/2634555/12452114/cce3ba20-bf5a-11e5-8d0a-c2aca3eca638.png)

**Comment by DevVersion** [comment] 2016-01-20 15:01
That's already fixed in d8602747f597879532ff2d1bb23c7a9bec6e6b88 and is online on the `HEAD (master)` version on the documentation.

**Comment by scottrodoty** [comment] 2016-01-20 15:48
Thanks, I see that now, however, the first demo that I selected from HEAD is still not rendering even though the js reference seems to be updated:  Demo->Tabs  Dynamic Height

**Comment by DevVersion** [comment] 2016-01-20 15:59
Everything is working fine for me in `HEAD`. Can you save the `not rendering` codepen and share the link, or better provide a screenshot ;)

**Comment by scottrodoty** [comment] 2016-01-20 19:06
Attaching saved codepen and screenshot

http://codepen.io/scottrodoty/pen/wMpzMe

![screen shot 2016-01-20 at 2 02 46 pm](https://cloud.githubusercontent.com/assets/2634555/12459799/85fc8fe6-bf7e-11e5-9d9a-749fba8d30f0.png)
![screen shot 2016-01-20 at 2 05 54 pm](https://cloud.githubusercontent.com/assets/2634555/12459885/fac1c670-bf7e-11e5-8079-53d46694eb68.png)

**Comment by DevVersion** [comment] 2016-01-20 20:40
Thanks for providing more information! All the other demos are working except for tabs, this demo should be fixed in #6785

**Comment by dracon** [comment] 2016-01-21 11:38
Hi.
Another one?
From the demo site the link to codepen for dialog showing http://codepen.io/pen?
And som of the libraries ar showing localhost:8080

**Comment by langdonx** [comment] 2016-01-21 12:50
@dracon Use CodePen links from HEAD: https://material.angularjs.org/HEAD/

**Comment by ThomasBurleson** [comment] 2016-01-22 05:42
Investigation now. Thank you.

**Comment by ThomasBurleson** [comment] 2016-01-26 21:23
The issue is due to a Mac vs Linux difference in `sed` and our release scripts. HEAD is built by Travis. Latest is generated by the release script. The fix is **in-progress**.

**Closed** 2016-01-28 21:25 UTC
Labels: P0 - Critical Fixes / Build or Deployment Issues

**Comment by langdonx** [comment] 2016-01-29 15:58
Has the fix been deployed to material.angularjs.org?  I can't seem to get any demos to work on any version:

https://material.angularjs.org/HEAD/demo/list
https://material.angularjs.org/1.0.4/demo/list

JS and CSS are still referencing `cdn.gitcdn.xyz` (https://cdn.gitcdn.xyz/cdn/angular/bower-material/v1.0.4-master-0dc2ec7/angular-material.css)

**Comment by DevVersion** [comment] 2016-01-30 16:39
@langdonx - To be honest, I also think `rawgit` is a good choice, it refreshes good and has a really good uptime. For example (https://cdn.rawgit.com/angular/bower-material/v1.0.4-master-00152a2/angular-material.min.js)
