### ISSUE TITLE
feat(input): add new input type from Material Design 2018 spec

### ISSUE THREAD

**Issue by GlauberF** [angular/material#11593] opened 2019-01-10 11:37 UTC
Hello,
Is it possible for someone to update the code and use the latest version of the material to make the new input available?

![deepin screenshot_selecionar area_20190110093659](https://user-images.githubusercontent.com/11314585/50966173-4b85a380-14bb-11e9-8ee4-c598db916770.png)

**Comment by codymikol** [comment] 2019-01-10 15:41
This library uses the original material design spec specified [here](https://material.io/archive/guidelines/). I don't believe there are any plans to implement the new spec.

**Comment by Splaktar** [comment] 2019-01-11 18:21
This is a duplicate of https://github.com/angular/material/issues/11413. As mentioned in https://github.com/angular/material/issues/11413#issuecomment-453609376, you'll want to upgrade to [Angular Material](https://material.angular.io/) in order to get the Material Design 2018 updates.

**Closed by Splaktar** 2019-01-11 18:21 UTC
