### ISSUE TITLE
md-autocomplete. Support of ng-required

### ISSUE THREAD

**Issue by kamarouski** [angular/material#3100] opened 2015-06-03 16:02 UTC
Sometimes we need to apply conditional validation for auto plate fields. Angular provides ng-required directive for this. Can we add support for this directive for md-autocomplete so we can use conditional validation

**Comment by marcysutton** [comment] 2015-06-03 18:22
This is already in our backlog. Closing as duplicate of #2949.

**Closed by marcysutton** 2015-06-03 18:22 UTC
