### ISSUE TITLE
JSPM installation takes angular from npm repo in 1.0.0-rc2

### ISSUE THREAD

**Issue by CxRes** [angular/material#5489] opened 2015-11-02 11:30 UTC
Until 1.0.0-rc1, JSPM is using angular from the github bower repo - which is the official angular repo in its registry as far as JSPM is concerned.  rc2 move to the npm repo and this causes angular to reload twice in the app.

**Comment by ThomasBurleson** [comment] 2015-11-02 15:40
Reload 2x in **what** app?

**Comment by CxRes** [comment] 2015-11-03 00:44
Sorry, my bad. I meant to say any JSPM based app angular is loaded twice when using 1.0.0-rc2. 
Once for `import angular` which loads from bower/angular and the once for `import angular material` which loads angular from `npm:angular`

**Comment by sarod** [comment] 2015-11-05 08:30
Using something like
`jspm install angular angular-material@1.0.0-rc2`

The jspm inspect returns:
```
github:angular/bower-angular 1.4.7
github:angular/bower-material 1.0.0-rc2
github:jspm/nodelibs-assert 0.1.0
github:jspm/nodelibs-process 0.1.2
github:jspm/nodelibs-util 0.1.0
github:systemjs/plugin-css 0.1.19
npm:angular 1.4.7
npm:angular-animate 1.4.7
npm:angular-aria 1.4.7
npm:assert 1.3.0
npm:inherits 2.0.1
npm:process 0.11.2
npm:util 0.10.3
```

The problem is that:
* the install of "angular" is resolved in jspm registry to github:angular/bower-angular 1.4.7.
* the install of "angular-material" resolves in jspm to github:angular/bower-material 1.0.0-rc2 which has a dependency on npm:angular.
This causes "WARNING: Tried to load angular more than once." when lauching the app.

A workaround I found is to specify that we want to install angular from npm:
`jspm install npm:angular angular-material@1.0.0-rc2`

**Comment by ThomasBurleson** [comment] 2015-11-07 14:02
Closed with https://github.com/angular/bower-material/commit/2406c2f4829b3c1fa7b18d3e5a83f440f2b98b19

**Closed by ThomasBurleson** 2015-11-07 14:02 UTC
Labels: type: build

**Comment by Nehon** [comment] 2016-01-31 08:11
Hello, I'm sorry to necro this issue, but I have the reverse issue with that fix.

I'm working behind a sonatype registry proxy for npm and all my dependencies are recommended to be installed with `jspm install npm:dependencyName`.

So typically I already have `npm:angular`, and `npm:angular-animate` installed and when I install 
`npm:angular-material` jspm installs `bower-angular` and `bower-angular-animate`.
 ```
Looking up npm:angular-material                                     
 Updating registry cache...                                          
 Looking up github:angular/bower-angular                             
 Looking up github:angular/bower-angular-animate                     
 ...
```
This conflicts with my npm versions of the dependencies and I experience the same things as OP stated.

To me, if you are pushing angular material to npm, your package.json dependencies should be the one from npm. However, your github:angular/bower-material package.json should reference github dependencies. I know it means 2 different publications, but it would be a lot more consistent, IMO, and would solve this issue (mine and the original one).

I will also file an isse on JSPM project, as it's not clear if the issue is with the way angular-material is published or if it's a jspm issue. And maybe Guy Bedford can shed some light on how to handle this properly.
