### ISSUE TITLE
md-icon mem leak

### ISSUE THREAD

**Issue by djfd** [angular/material#9558] opened 2016-09-09 03:58 UTC
**Actual Behavior**:
 -  `What is the issue? *`md-icon failed to deallocate own watchers when its element is removed **UPD** presumably $observers are lost as well
 -  `What is the expected behavior?`it is expected that there are not any leftovers regardless of removal method

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` [here](http://codepen.io/djFD/pen/GjJbyd)
 -  `Details:`clicking a button removes and then re-creates container. The counter below the button shows an actual watchers qty.

**Angular Versions**: *
 -  `Angular Version:`1.5.7
 -  `Angular Material Version:`1.1.0

**Additional Information**:
 -  `Browser Type: *`Firefox, Chromium, IE
 -  `Browser Version: *`48.0, 52.0.2743.116, 11-
 -  `OS: *`linux
 -  `Stack Traces:`--

**Comment by crisbeto** [comment] 2016-09-09 04:59
[Trying to isolate this further](http://codepen.io/crisbeto/pen/zKvOYL?editors=1010), I'm having trouble reproducing it with a simplified case where it's only `ng-if` that adds/removes it from the DOM. I think that it's some of the logic that manually creates/destroys the container. 

For example, if you replace the `md-icon` with a data binding to `ctrl.icon`, the watchers still don't get cleaned up. [Here's a fork that shows it.](http://codepen.io/crisbeto/pen/RGWbPN) Note that the only change I did was to replace `<md-icon md-svg-src="{{ctrl.icon}}"></md-icon>` from the directive template with `{{ctrl.icon}}`, although the same happens if you try `<span ng-bind="ctrl.icon"><span>`.

**Comment by djfd** [comment] 2016-09-09 05:11
well, watchers are tied to a scope, ng-if creates scope (and then removes it, along with all stuff, including watchers). it is why you cannot reproduce.

in your situation try to set up hook on destroy in angular (just set up break point there). you will see that there are still alive watchers.

I faced the situation where it is need to be scopeless, it is why

**Comment by crisbeto** [comment] 2016-09-09 05:18
What about the situation where there's no Material, but a single Angular binding? The watcher still doesn't get cleaned up.

**Comment by djfd** [comment] 2016-09-09 05:21
if I would know. directive uses element transclusion, possible angular itself does not cleanup properly on removal of element with bindings, need to check

**Comment by djfd** [comment] 2016-09-09 07:07
well, it seems to be an angular issue (or we just cannot properly cook these smelling and fur cats ))

played with [this](http://codepen.io/djFD/pen/KgdPoR) - removed MD and splitted in smaller parts

so compiling does not introduce any extra watchers, that is ok. when entered into pre-linking, the node itself seems to be linked already, I can see a watcher for a binging set to that node.

then postlinking and transclusion, this gives one more extra watcher for the same expression. thus have **2** watchers for a single binding set on the directive node itself. This is already is wrong by self

But surprisingly, removal either of elements (a comment stub) or cloned content does not remove neither of these watchers.

So I am pretty sure now that it is angular core issue. Will post the same to them, using my last pen as a demo

**Comment by crisbeto** [comment] 2016-09-09 07:16
Thanks for looking deeper into it. I'll close this since there's not much we can do about it.

**Closed by crisbeto** 2016-09-09 07:16 UTC
Labels: needs: more info

**Comment by djfd** [comment] 2016-09-09 08:06
but I will be back when resolved on their side, to verify the operation of md-icon ))
