### ISSUE TITLE
Dialogs title doesn't stick on the top of dialog

### ISSUE THREAD

**Issue by Stamy** [angular/material#2889] opened 2015-05-18 09:53 UTC
The title is quite self explanatory. In the custom dialog the sub-header should be sticky as far as I believe. It behaves as a simple text and scrolls down with dialogs content.
https://material.angularjs.org/#/demo/material.components.dialog

**Comment by marcysutton** [comment] 2015-05-18 20:35
This is a duplicate of #1932.

**Closed by marcysutton** 2015-05-18 20:35 UTC
