### ISSUE TITLE
<md-card-content> and <md-card-footer> directives

### ISSUE THREAD

**Issue by lewis-walker** [angular/material#4475] opened 2015-09-04 20:39 UTC
https://material.angularjs.org/latest/#/api/material.components.card/directive/mdCard
clearly shows the titular directives
But they don't exist. They DO appear as css classes.

Can the documentation be updated, or the directives created as suggested by the docs?

**Comment by ThomasBurleson** [comment] 2015-09-04 21:57
Directives will be created. This is a duplicate of another issue. Thx.

**Closed by ThomasBurleson** 2015-09-04 21:57 UTC
