### ISSUE TITLE
md-content within md-tab not scrolling/expanding

### ISSUE THREAD

**Issue by hodeyp** [angular/material#2069] opened 2015-03-29 09:43 UTC
md-tabs-content-wrapper overflow is set to hidden so overflow is never seen. Also how can the refactored md-tab expand to fit contents?

**Comment by DefunctExodus** [comment] 2015-03-29 13:17
I am wondering the same thing

**Comment by trazek** [comment] 2015-03-30 17:32
I am also having trouble with md-tabs content being cut off and have resorted to overriding min-height and overflow: visible where necessary to have it display properly. This is dangerous as with each update, I have to retool my "solution" until a fix is in.

**Comment by kschwidder** [comment] 2015-03-31 10:11
+1
It would be great if changes are published prior in order to adapt them correctly. My last builds have been broken since 27.3.15.

**Comment by robertmesserle** [comment] 2015-03-31 16:10
@kschwidder As with most projects, master is a constantly changing branch that is not necessarily stable - we tag releases when we see code as being ready for release.  My reason for merging tabs into master was to get this feedback before we release 0.9.0.

**Comment by robertmesserle** [comment] 2015-03-31 16:11
This is a duplicate of #2088.

(Technically, #2088 is the duplicate, but I already started discussion on that one.)

**Closed by robertmesserle** 2015-03-31 16:11 UTC
