### ISSUE TITLE
mdInput: extra input on iOS ?

### ISSUE THREAD

**Issue by cdayjr** [angular/material#7206] opened 2016-02-18 16:19 UTC
Using Angular Material 1.0.5, but i've had this for some earlier versions as well. Regularly, I can click on an input and type in, and everything works:

![Working Input - Empty](https://cloud.githubusercontent.com/assets/3406697/13149593/feab18e6-d62f-11e5-8f12-508d63d6e6f2.png)
![Working Input - With Text](https://cloud.githubusercontent.com/assets/3406697/13149594/feacba70-d62f-11e5-96fb-1d9e129e5590.png)

I'm running into a weird issue where I'll tap on the input in iOS and occasionally I'll get a smaller offset vertical bar that otherwise seems to work like a regular input but it won't let me type anything, nor does it count for filling out an input:
![Broken Input](https://cloud.githubusercontent.com/assets/3406697/13149592/fea6e762-d62f-11e5-97fe-5acf88447a89.png)

It seems to line up with the label text that's there before tapping the input. I seem to be getting this on any text input I have, but here's the code for the login form if that helps:

    <form name="loginForm" data-ng-submit="login.login()">
      <div layout="column">
        <md-input-container flex="flex" class="md-icon-float">
          <label>Username</label>
          <md-icon><i class="material-icons">account_box</i></md-icon>
          <input type="text" ng-required="true" ng-model="login.user.username"/>
        </md-input-container>
        <md-input-container flex="flex" class="md-icon-float">
          <label>Password</label>
          <md-icon><i class="material-icons">lock</i></md-icon>
          <input type="password" ng-required="true" ng-model="login.user.password"/>
        </md-input-container>
      </div>
      <md-button flex="flex" type="submit" aria-label="Login" class="md-raised md-primary">Login</md-button>
    </form>

**Comment by topherfangio** [comment] 2016-03-25 20:39
@cdayjr Can you please convert this to a Codepen so that we can play with it on an actual iOS device more easily?

**Comment by ThomasBurleson** [comment] 2016-04-26 13:54
Closing this issue due to insufficient information. Please resubmit with:

----
Required
----

**Behavior**:
-  What is the issue? * 
-  What is the expected behavior? 

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue :
-  Details: 

**Angular Versions**: *
-  Angular Version: 
-  Angular Material Version: 

**Additional Information**:
-  Browser Type: *
-  Browser Version: *
-  OS: *
-  Stack Traces: 

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

**Closed by ThomasBurleson** 2016-04-26 13:54 UTC
Labels: - In Progress, browser: iOS, needs: demo
