### ISSUE TITLE
md-auto-complete not allowing to click outside after clicking close button in it.

### ISSUE THREAD

**Issue by ramanathan92** [angular/material#4075] opened 2015-08-10 07:44 UTC
Scenario : 
If user clicks auto-complete close button after page loads(when auto-complete having default selected one in box).

Problem : 
After clicking close button click outside the auto-complete box, page will get locked(nothing is working,If you tries to click somewhere is not working). We need to refresh page to make it work again as normal.

**Comment by robertmesserle** [comment] 2015-09-15 19:22
This seems to be resolved in the latest code.  Please reply if this is still an issue.

**Closed by robertmesserle** 2015-09-15 19:22 UTC
Labels: priority: critical

**Comment by ramanathan92** [comment] 2015-10-07 12:28
No it is not resolved in latest code also.Still am facing this problem,after upgrading to 0.11.2

**Comment by topherfangio** [comment] 2015-10-07 16:48
@ramanathan92 Can you try against 0.11.2 or master? We've made some additional updates to the autocomplete recently.

**Comment by robertmesserle** [comment] 2015-10-07 17:59
@ramanathan92 Can you provide a CodePen demonstrating the issue?  I have been unable to reproduce.

**Comment by ramanathan92** [comment] 2015-10-08 06:24
sure am working on it.I will provide you that.
