### ISSUE TITLE
Featuer Request: md-toolbar height responsive

### ISSUE THREAD

**Issue by SiddharthaRRamesh** [angular/material#2191] opened 2015-04-07 07:03 UTC
Type: Feature request

On: `md-toolbar` height

Description: `md-toolbar` height should be auto-responsive. According to material spec, height varies on desktops, tablets and mobile. Is there any disadvantage in doing this in the framework itself?

**Comment by ThomasBurleson** [comment] 2015-04-07 12:11
Please check current issues for duplicates before creating a new issue.
Duplicate of #2047.

**Closed by ThomasBurleson** 2015-04-07 12:11 UTC

**Comment by SiddharthaRRamesh** [comment] 2015-04-08 04:26
Sorry!
