### ISSUE TITLE
Broken link to github on main page

### ISSUE THREAD

**Issue by iboozyvoozy** [angular/material#7375] opened 2016-03-02 15:02 UTC
Github link in header on main site has link to non-existent version v1.0.6

`https://github.com/angular/material/tree/v1.0.6`

**Comment by DevVersion** [comment] 2016-03-02 17:33
@robertmesserle Can you create a tag?

**Comment by DevVersion** [comment] 2016-03-02 17:34
- Update - Duplicate of #7355

**Closed by DevVersion** 2016-03-02 17:34 UTC
