### ISSUE TITLE
md-chip should be case insensitive

### ISSUE THREAD

**Issue by LisaTatum** [angular/material#6933] opened 2016-01-30 22:41 UTC
When I use the default chip template: https://material.angularjs.org/latest/demo/chips

and create a chip "orange" that already exists "Orange" that should not be possible.

I want to create entities where the name is unique doesn`t matter wether is upper/lowercase.

**Comment by DevVersion** [comment] 2016-01-31 08:34
That's a duplicate of #5782.

**Comment by DevVersion** [comment] 2016-01-31 08:47
Thanks, can reproduce. I try to take a look.

**Closed** 2016-04-28 19:42 UTC
Labels: type: enhancement

**Comment by gouravsood** [comment] 2016-07-27 19:47
I am also facing the issue. 
Just trying to understand, why this enhancement has been deprecated? This is valid scenario to pick unique values in the chips.
