### ISSUE TITLE
Always-visible, inline datepicker?

### ISSUE THREAD

**Issue by felixfbecker** [angular/material#5674] opened 2015-11-11 15:45 UTC
In other widgets like jQuery UI or UI-Bootstrap you can make the datepicker an always-visible, inline element instead of attached to an input field: http://jqueryui.com/datepicker/#inline.
I need this in a number of applications where I always show content for a specific date.
There doesn't seem to be a way to do this in angular material. I looked a bit at the source and saw the md-calendar directive, which is not documented however. Maybe this should be document as an official widget? Is this the directive I am looking for? Can I use it with the same options as md-datepicker?
If not, maybe an `inline` option could be added to the datepicker directive.

**Comment by felixfbecker** [comment] 2015-11-11 16:20
I just played around with it a bit and it seems like md-calendar is exactly what I need. I just wished this was added to the docs (atleast mentioned) so I don't feel like I'm using internal API that could change anytime without a semver major.

**Comment by EladBezalel** [comment] 2015-11-15 15:26
related #4973

**Comment by jelbourn** [comment] 2015-11-18 00:45
Dupe of #4561

**Closed by jelbourn** 2015-11-18 00:45 UTC

**Comment by silentsnooc** [comment] 2018-09-24 21:08
Kind of solved: https://github.com/angular/material2/issues/4801
