### ISSUE TITLE
datepicker: displays wrong month with align-items:center

### ISSUE THREAD

**Issue by kpgoodale** [angular/material#10274] opened 2017-01-18 20:16 UTC
**Actual Behavior**:
 -  `What is the issue? *` Clicking the calendar icon displays the wrong month/offset.
 -  `What is the expected behavior?` The current date/min-date should be focused.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` http://codepen.io/kpgoodale/pen/VPPpyg
 -  `Details:` Clicking the datepicker icon when the datepicker is at the bottom of the viewable area works as expected. Scrolling down to position the datepicker at the top of the viewable area will display the wrong month.

**Angular Versions**: *
 -  `Angular Version:` 1.5.8
 -  `Angular Material Version:` 1.1.1

**Additional Information**:
 -  `Browser Type: *` Chrome
 -  `Browser Version: *` Version 55.0.2883.87 m (64-bit)
 -  `OS: *` Windows 10
 -  `Stack Traces:`
 -  `Image:` Working
![working](https://cloud.githubusercontent.com/assets/25208674/22081256/e096e808-dd90-11e6-846b-6a73f2a4d6ee.JPG)
Not working
![not_working](https://cloud.githubusercontent.com/assets/25208674/22081264/e4f626ca-dd90-11e6-9691-131595b6b48d.JPG)

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by rhinoceraptor** [comment] 2017-02-14 19:40
This is a possible duplicate of #10144

**Comment by thekud** [comment] 2017-02-16 01:59
The fix mentioned in #10144 (http://codepen.io/phillypham/pen/xRNPdJ) does not fix this issue.

**Comment by kpgoodale** [comment] 2017-02-16 02:01
The fix mentioned in #10144 (http://codepen.io/phillypham/pen/xRNPdJ) does not fix this issue.

**Comment by Splaktar** [comment] 2020-05-27 09:27
Fixed in PR https://github.com/angular/material/pull/10537 as part of https://github.com/angular/material/issues/10144. Released in `1.1.5`.

**Closed by Splaktar** 2020-05-27 09:27 UTC
Labels: resolution: duplicate
