### ISSUE TITLE
mdTabs: Adding mdChip doesn't update tab content height.

### ISSUE THREAD

**Issue by qkmadson** [angular/material#2706] opened 2015-05-04 19:11 UTC
I'm using mdTabs with the md-dynamic-height attribute and, on the tab, users can interact with mdChips. As chips are added, they push any other content below (buttons, etc) off the bottom of the tab and out of view. If the user navigates to another tab and back, the issue is fixed because the updateHeightFromContent() method will be called but, it seems like there should be a way to call updateHeightFromContent or some other mechanism to update the tab height without navigating away and back.

**Comment by marcysutton** [comment] 2015-05-04 19:37
Hi, can you please provide a Codepen or Plunker showing your issue? That is pretty complex to deduce from text only. Thanks.

**Comment by robertmesserle** [comment] 2015-06-04 20:13
@qkmadson I am not able to reproduce this, I believe it has been resolved.  Closing for now, please re-open if it is still an issue with the latest code in master.

**Closed by robertmesserle** 2015-06-04 20:13 UTC
Labels: Demo Needed
