### ISSUE TITLE
feat(panel): add groupName config option

### ISSUE THREAD

**Issue by EladBezalel** [angular/material#8424] opened 2016-05-12 01:51 UTC
add and document `groupName` in [panel](https://github.com/angular/material/blob/464924075b5a68705f9b61dd561246904c8466a6/src/components/panel/panel.js#L152)

**Comment by EladBezalel** [comment] 2016-07-26 17:00
@bradrich is that included in your work?

**Comment by ErinCoughlan** [comment] 2016-07-26 17:21
Yes, this is part of that group work.

**Comment by bradrich** [comment] 2016-08-19 05:36
Closing as this is a duplicate of #8971.

**Closed by bradrich** 2016-08-19 05:36 UTC
Labels: P2 - Planned Work / Team PRs, resolution: duplicate, type: docs, type: feature
