### ISSUE TITLE
md-datepicker red line appears under date when date set in code

### ISSUE THREAD

**Issue by apils** [angular/material#8017] opened 2016-04-13 10:01 UTC
If you have the 'required' attribute and an empty md-datepicker, and then set the date using code (rather than entering it directly into the form) the line under the date is red, indicating it is invalid when it is not. See codepen http://codepen.io/apilsworth/pen/VaXeJy

**Comment by topherfangio** [comment] 2016-04-14 16:34
@apils This appears to be a duplicate of #6086. Can you please verify if it's the same or if it's different?

**Comment by apils** [comment] 2016-04-15 06:58
You're right. It is the same issue. Apologies, didn't spot that one.

**Comment by topherfangio** [comment] 2016-04-15 17:36
@apils No worries! Closing this one as a duplicate.

**Closed by topherfangio** 2016-04-15 17:36 UTC
Labels: needs: more info, resolution: duplicate

**Comment by Ocean-Blue** [comment] 2017-10-13 21:46
Just in case anyone is looking for the answer. The solution is simple.
Instead of **required**, just use **ng-required**, that's it.
