### ISSUE TITLE
Android Device: Animation Performance, md-icon issue on Chrome

### ISSUE THREAD

**Issue by Omkaraaa** [angular/material#1177] opened 2015-01-13 07:19 UTC
I am building Android application using Angularjs, Angular material and Cordova. 
Can somebody help on below issues. Can someone suggest tips/tricks to improve/fix below points?

Issue ~1:
Animations are very very slow on android device. Mainly ripple effects/animations given to md-button are slow. I have tried disabling hardwareAcceleration for cordova still it does not works.
See below Html . 
Code:

![code](https://cloud.githubusercontent.com/assets/8783497/5717283/0ca7b258-9b24-11e4-9326-62d89c30640e.jpg)

Issue ~2:
Multiple click on md-button makes application not responding. Does not give intuition of  which button is active or focus.

Issue ~3:
I observed that with Crome browser on Laptop, there are few problems for demo site also (https://material.angularjs.org), md-button icons are not visible. However same works in firefox. May be md-icon has changed in new build? 
See below image: 

![image](https://cloud.githubusercontent.com/assets/8783497/5717312/84b2e72c-9b24-11e4-8fbf-6de90396613e.png)

**Comment by gngeorgiev** [comment] 2015-01-14 12:03
An option to have only one ripple effect at a time would be great for mobile devices.

**Comment by Omkaraaa** [comment] 2015-01-15 05:15
@gngeorgiev : that is brilliant idea. Are you facing same problem? Have you implemented it?

**Comment by gngeorgiev** [comment] 2015-01-15 08:13
@Omkaraaa No, not yet, but surely I will give it a go if this issue has no progress since multiple ripple effects crash my application with Crosswalk on Android 5.0

**Comment by gngeorgiev** [comment] 2015-01-15 19:40
@Omkaraaa @ThomasBurleson You can take a look at #1204 and see if it will help in this scenario.

**Comment by nafeezabrar** [comment] 2015-02-12 12:36
I just visited demo site from a cordova application. Angular-material's animation is really slow in crodva webclient.

**Comment by atentis** [comment] 2015-03-09 03:34
I agree with the op. I am using buttons on a side nav and it gets ugly when you combine (button ripple + close sidenav + load view w/data).

I look forward to future improvements

**Comment by alexhuot1** [comment] 2015-03-22 01:17
I didn't want to open an other issue, because I guess it's the same problem. The sidenav animation is very slow and the toggle button also. I use phonegap/cordova.

FYI: After mutiple toggle of the sidenav, the perfomance kind of increase and become usable.

Thanks!

**Comment by uriva** [comment] 2015-05-14 23:04
+1

**Comment by iyoukeyyewei** [comment] 2015-06-05 07:27
yes. the button and sidenav are too slow on mobile. I cannot use material angularjs on mobile until the performance improved.

**Comment by uriva** [comment] 2015-06-05 09:51
For me the slowness appears on desktop as well.

**Comment by ThomasBurleson** [comment] 2015-06-05 15:08
@robertmesserle - do you have time to investigate this today?

**Comment by robertmesserle** [comment] 2015-06-05 15:16
@ThomasBurleson I'm not in the office and don't have access to an Android device today, so probably not.

**Comment by simongcc** [comment] 2015-06-22 04:01
+1 ripple is extremely slow in custom Android Tablet with the following configuration for reference:
Android 4.2.2
CPU: ARMv7 1.6GHz (tested in full speed with latest Chrome)
Resolution: 1366 x 720

+1 ripple is fairly slow in a local POS system that is actually a desktop, not sure if it is related to GPU or CPU, the configuration for reference:
Windows 7, 32Bit
Display: Intel Q965/Q963 Express Chipset Family
CPU: Intel E5700 Dual Pentium 3.00G
Resolution: 1024 x 768

In these machines, the ripple respond differently, normally in a Desktop environment, one click will trigger one ripple, in these machines,
* sometimes one click/touch trigger one ripple (true for some Desktop, Android with App running in Webview)
* sometimes one click/touch will trigger the ripple but the ripple will not be staying if it is not long pressing(click/touch)
* when click consecutively, the button color of the background is stuck in dark ripple color without restoration (true for some Desktop, Android with Chrome)

**Comment by MilosStanic** [comment] 2015-06-23 10:57
I confirm very slow sidenav and button animation on Android phonegap/cordova. 
I guess this needs to be fixed, since Material Design is "mobile first".

**Comment by kevindstanley1988** [comment] 2015-06-26 11:55
Device: Samsung Galaxy s6
Angular version: 1.4.1
Material version 0.10

I have a samsung galaxy s6 android, which should be far more than enough power for this framework. I see lagging issues on the sidenav opening and scrolling. I also see lagging issues when i click buttons, for instance I have a menu with 3 menu buttons, I click my logout button and the ripple is slow and then pauses at the end of the animation for about 2 seconds before executing the ng-click. Desktop works great for me, but I have a gaming rig so it is above an average business's computer.

**Comment by uriva** [comment] 2015-06-26 16:02
I'm experiencing similar things on chrome with ubuntu

**Comment by cleever** [comment] 2015-06-26 17:42
The same issues.

**Comment by makersio** [comment] 2015-06-27 17:37
This is really a problem. 

From my point of view good performance in a wrapper like Cordova is essential. Otherwise the whole mobile platform is out of reach when using this framework.

Really like it though so hoping this issue will get attention.

Good luck.

**Comment by sckoh** [comment] 2015-06-28 09:59
same issue

**Comment by plato-cambrian** [comment] 2015-07-03 01:01
+1 for getting angular-material performing on phones!  
PSA for anyone who found this thread looking to build a **performant mobile angular app**:

I have made great progress in the past few days with the [AppGyver](http://www.appgyver.com/steroids) platform.
*Steroids* is their CLI tool to help develop and deploy apps¹
*Supersonic* is a set of javascript extensions² and html components³ built to get native performance wherever possible
You use their cloud build service to make iOs and android binaries, but for development you can just scan a QR code, [here](https://share.appgyver.com/?id=67861&hash=1c1f536a281d991a98efa9a01ce66f04c317f86ad2d380ee02515ca0a7eb6695) is the QR for [my demo app](https://github.com/therealplato/persistence-game).

[1] `npm install -g steroids; steroids create myApp`
[2] `supersonic.ui.layers.pop()`
[3] `<super-navbar-title ng-bind="name">`

**Comment by ryanpager** [comment] 2015-07-04 23:35
I run a very ui/ux complex cordova app w/ Angular Material, and I have none of these problems. I literally have no trouble running all of this stuff on iOS 6, 7, 8 (havent tried 9) or android 4.2+.

Angular: 1.4.1
Material: 0.10.0-master-adcee7d
Ionic: 1.0.1
Devices Tested:
- Armv7 Nexus 5
- Armv7 LG G3
- Armv7 Verizon Droid Tablet
- X86 Samsung Tab 3
- iPhone 5
- iPhone 4s
- iPhone 6
- iPhone 6+
- 2015 Macbook Pro 15"
- i5 (first generation) Desktop

In specific, I run the following with ripple effects:
- md-button
- md-bottom sheet
- md-cards (with added md-ink-ripple)
- fab speed dial

The only "kinda" laggy animation I get are,
a. The Dialog close animation (scale, translate down and opacity) is very fast and janky. I just replaced it to use opacity only, and its fine now.
b. The FAB speed dial gets kinda choppy if I toggle it a ton back to back.

Screenshot of ui:
<img width="330" alt="screen shot 2015-07-04 at 10 10 23 am" src="https://cloud.githubusercontent.com/assets/570872/8509736/316aaa26-227b-11e5-8a7c-07d5c203c75c.png">

Notes on screenshot:
- Header is a md-toolbar
- Buttons in bottom left and right are md-buttons w/ ripple
- Cards are md-card w/ ripple effect
- Main layout has md-swipe-left & md-swipe-right actions
- I use no ionic styling

Let me know if I can provide more information to help.

**Comment by barryvdh** [comment] 2015-07-21 12:43
The ripple effect is working on my Android phone, but it's delaying the click, so it looks sluggish.

`<md-button ng-href=".." md-no-ink="true">..</md-button>`

Has a lot more responsive feel..

**Comment by gngeorgiev** [comment] 2015-07-21 12:46
@barryvdh yeah this is what happens on older devices, I believe this handles well with relatively performant phone and crosswalk.

**Comment by ryanpager** [comment] 2015-07-21 12:50
@barryvdh Im running this on a nexus 4 now, which is a pretty slow device. It still runs very smoothly, and has less than a 100ms click delay. What kind of device are you using to test this on?

**Comment by barryvdh** [comment] 2015-07-21 12:51
Well, it's an HTC One M8 and I'm using Crosswalk and/or latest Chrome, so I wouldn't call that slow..

**Comment by ryanpager** [comment] 2015-07-21 13:17
@barryvdh Could you throw up a code sample gist of the code w/ css applied? A coworker of mine has an M8 and it flies.

**Comment by barryvdh** [comment] 2015-07-22 19:41
@ryanpager Okay it doesn't actually seem to be the md-button that's causing the delay, but it's the combination with changing the route. Perhaps it's the router that's waiting for the animation to finish. I'll see if I can get a Codepen working with the router.

**Comment by oli107** [comment] 2015-07-27 09:11
All of these performance issues can be seen on the demo site as well (material.angularjs.org). Using on a Galaxy S6 edge with chrome, and routing seems to pause until ripple animation has completed and animations like the menus expanding are slow as is the nav drawer opening and closing.

**Comment by atentis** [comment] 2015-07-27 15:45
I can confirm that I had issues with the ripple performance and route changes as well. It seemed to help to put a timout before the route change but obviously that is a bad solution.

**Comment by paambaati** [comment] 2015-07-31 09:11
@ryanpager Can you tell us a little more about your setup, if that's possible? I'm working on a website with Maps functionality and very minimal Angular Material stuff (like a top toolbar, a slidenav on the left, a FAB, and a modal or two), and the website's performance is terrible on Android+Chrome. I've tried using one-time binding wherever possible, but that had zero effect on the slow performance.

**Comment by alexcriss** [comment] 2015-08-20 05:17
I confirm seeing rather slow animations when the sidenav opens or closes and when clicking links on the sidenav on the demo site.

Device is a Huawei Honor 6.

**Comment by gpopovic** [comment] 2015-08-21 19:47
I can confirm the same slow animations (sidenav is awfully slow, and changing route on button click is always ugly :/)

**Comment by ryanpager** [comment] 2015-08-26 22:31
Hey guys, try this application out and see if its running sluggish for you -- id be interested in feedback since I havent seen any issues on a plethora of devices.

https://play.google.com/store/apps/details?id=com.traxohybrid.traxo

**Comment by atentis** [comment] 2015-08-29 23:23
@ryanpager I cannot login after creating an account. Got some token error. Send me a pm if you would like me to take a look. I have a pretty old cpu on my phone (2013 moto x) so it would be nice to test. 

-Adam

**Comment by ryanpager** [comment] 2015-08-30 20:37
@atentis Hey -- good catch, I just fixed the stupid sign up (it was still pointing to our staging environment). Re-sign up in a couple hours when the update comes down (version 2.0.2) and youll be good to go. Sorry about that!

**Comment by braoul** [comment] 2015-11-17 08:38
+1
I have the same problem : the ripple effects are REALLY slow on my modern tablet. The animation begins like 2 or 3 seconds after touching the button.
I am using Cordova and Crosswalk (which should have been faster than normal webview).

**Comment by nitin7dc** [comment] 2016-01-15 12:12
+1

**Comment by jwuliger** [comment] 2016-01-25 11:38
I am having the same issues. I have an Ionic/Cordova app I am developing. I am using a Samsung Galaxy S6 Edge as my high-end test device. Most of all the components have butter smooth animations. The one that kills the performance of the app are the tab content transition animations. They really struggle to move to the next tab. This is with me just copying and pasting the demo right into my code. On the other hand something like the FAB Toolbar, or the bottom-sheet work really well. I am using the latest of everything since I am still developing (Including ngMaterial 1.0.3). I know the team is probably hard at work on Angular 2/Ionic 2. I guess what I am looking for is a good way to override the transition animations, or maybe a work-around? I appreciate any feedback! All the best.

**Comment by Whoknowsit** [comment] 2016-02-02 12:35
Not just on Android. It's also laggy on Chrome (Mac).

**Comment by redyyu** [comment] 2016-04-16 16:59
I am using Chrome on Android 6, Samsung Galaxy S7. and Moto G.
The sidenav animation has same issue. the material angular is 1.0.7

I have another material ng project using 0.9.8, looks much better than 1.0.7.

**Closed** 2016-04-28 20:28 UTC
Labels: browser: Android, type: performance

**Comment by dudafreitasrj** [comment] 2016-05-05 01:52
First sorry for my English.

The problem is that the "angular animate" does not work well when we have animation in animation.

EX:

```
<Div class = "one">
    <Div class = "two"> </ div>
<Div>
```

If we put animation for the class "one" and "two" will be slow, but if we do so:

```
<Div class = "one"> </ div>
<Div class = "two"> </ div>
```

The animation will be fast. I did this test several times and in all in the first case was slow and the second was fast.

The SlideNav does just that is so slow.

**Comment by nitin7dc** [comment] 2016-05-07 05:50
For md-sidenav adding css hardware acceleration to all md-sidenav classes solves the issue.

Add following code to your custom css and place it after angular-material.css

```
md-sidenav.md-closed-add, md-sidenav.md-closed-remove {
  display: -webkit-flex;
  display: -ms-flexbox;
  display: flex;
  -moz-transform: translateX(0) !important;
  -ms-transform: translateX(0) !important;
  -o-transform: translateX(0) !important;
  -webkit-transform: translateX(0) !important;
  transform: translateX(0) !important;

  -moz-transform: translateZ(0) translateX(0) !important;
  -ms-transform: translateZ(0) translateX(0) !important;
  -o-transform: translateZ(0) translateX(0) !important;
  -webkit-transform: translateZ(0) translateX(0) !important;
  transform: translateZ(0) translateX(0) !important;

  -moz-transform: translate3d(0, 0, 0) !important;
  -ms-transform: translate3d(0, 0, 0) !important;
  -o-transform: translate3d(0, 0, 0) !important;
  -webkit-transform: translate3d(0, 0, 0) !important;
  transform: translate3d(0, 0, 0) !important;
  transition: 0.2s ease-in all !important; }

md-sidenav.md-closed-add.md-closed-add-active, md-sidenav.md-closed-remove.md-closed-remove-active {
  -moz-transform: translateX(0) !important;
  -ms-transform: translateX(0) !important;
  -o-transform: translateX(0) !important;
  -webkit-transform: translateX(0) !important;
  transform: translateX(0) !important;

  -moz-transform: translateZ(0) translateX(0) !important;
  -ms-transform: translateZ(0) translateX(0) !important;
  -o-transform: translateZ(0) translateX(0) !important;
  -webkit-transform: translateZ(0) translateX(0) !important;
  transform: translateZ(0) translateX(0) !important;

  -moz-transform: translate3d(0, 0, 0) !important;
  -ms-transform: translate3d(0, 0, 0) !important;
  -o-transform: translate3d(0, 0, 0) !important;
  -webkit-transform: translate3d(0, 0, 0) !important;
  transform: translate3d(0, 0, 0) !important;
  transition: all 0.2s cubic-bezier(0.25, 0.8, 0.25, 1) !important;
}

.md-sidenav-left, md-sidenav {
  left: 0;
  top: 0;
  -moz-transform: translateX(0) !important;
  -ms-transform: translateX(0) !important;
  -o-transform: translateX(0) !important;
  -webkit-transform: translateX(0) !important;
  transform: translateX(0) !important;

  -moz-transform: translateZ(0) translateX(0) !important;
  -ms-transform: translateZ(0) translateX(0) !important;
  -o-transform: translateZ(0) translateX(0) !important;
  -webkit-transform: translateZ(0) translateX(0) !important;
  transform: translateZ(0) translateX(0) !important;

  -moz-transform: translate3d(0, 0, 0) !important;
  -ms-transform: translate3d(0, 0, 0) !important;
  -o-transform: translate3d(0, 0, 0) !important;
  -webkit-transform: translate3d(0, 0, 0) !important;
  transform: translate3d(0, 0, 0) !important;
}

.md-sidenav-left.md-closed, md-sidenav.md-closed {
  -moz-transform: translateX(-100%)!important;
  -ms-transform: translateX(-100%)!important;
  -o-transform: translateX(-100%)!important;
  -webkit-transform: translateX(-100%)!important;
  transform: translateX(-100%)!important;

  -moz-transform: translateZ(0) translateX(-100%)!important;
  -ms-transform: translateZ(0) translateX(-100%)!important;
  -o-transform: translateZ(0) translateX(-100%)!important;
  -webkit-transform: translateZ(0) translateX(-100%)!important;
  transform: translateZ(0) translateX(-100%)!important;

  -moz-transform: translate3d(-100%, 0, 0)!important;
  -ms-transform: translate3d(-100%, 0, 0)!important;
  -o-transform: translate3d(-100%, 0, 0)!important;
  -webkit-transform: translate3d(-100%, 0, 0)!important;
  transform: translate3d(-100%, 0, 0)!important;
}

md-sidenav.md-locked-open-add, md-sidenav.md-locked-open-remove {
  -moz-transform: translateX(0) !important;
  -ms-transform: translateX(0) !important;
  -o-transform: translateX(0) !important;
  -webkit-transform: translateX(0) !important;
  transform: translateX(0) !important;

  -moz-transform: translateZ(0) translateX(0) !important;
  -ms-transform: translateZ(0) translateX(0) !important;
  -o-transform: translateZ(0) translateX(0) !important;
  -webkit-transform: translateZ(0) translateX(0) !important;
  transform: translateZ(0) translateX(0) !important;

  -moz-transform: translate3d(0, 0, 0) !important;
  -ms-transform: translate3d(0, 0, 0) !important;
  -o-transform: translate3d(0, 0, 0) !important;
  -webkit-transform: translate3d(0, 0, 0) !important;
  transform: translate3d(0, 0, 0) !important;
}

md-sidenav.md-locked-open, md-sidenav.md-locked-open.md-closed, md-sidenav.md-locked-open.md-closed.md-sidenav-left, md-sidenav.md-locked-open.md-closed, md-sidenav.md-locked-open.md-closed.md-sidenav-right, md-sidenav.md-locked-open-remove.md-closed {
  -moz-transform: translateX(0) !important;
  -ms-transform: translateX(0) !important;
  -o-transform: translateX(0) !important;
  -webkit-transform: translateX(0) !important;
  transform: translateX(0) !important;

  -moz-transform: translateZ(0) translateX(0) !important;
  -ms-transform: translateZ(0) translateX(0) !important;
  -o-transform: translateZ(0) translateX(0) !important;
  -webkit-transform: translateZ(0) translateX(0) !important;
  transform: translateZ(0) translateX(0) !important;

  -moz-transform: translate3d(0, 0, 0) !important;
  -ms-transform: translate3d(0, 0, 0) !important;
  -o-transform: translate3d(0, 0, 0) !important;
  -webkit-transform: translate3d(0, 0, 0) !important;
  transform: translate3d(0, 0, 0) !important;
}
md-sidenav.md-closed.md-locked-open-add {
  -moz-transform: translateX(0) !important;
  -ms-transform: translateX(0) !important;
  -o-transform: translateX(0) !important;
  -webkit-transform: translateX(0) !important;
  transform: translateX(0) !important;

  -moz-transform: translateZ(0) translateX(0) !important;
  -ms-transform: translateZ(0) translateX(0) !important;
  -o-transform: translateZ(0) translateX(0) !important;
  -webkit-transform: translateZ(0) translateX(0) !important;
  transform: translateZ(0) translateX(0) !important;

  -moz-transform: translate3d(0, 0, 0) !important;
  -ms-transform: translate3d(0, 0, 0) !important;
  -o-transform: translate3d(0, 0, 0) !important;
  -webkit-transform: translate3d(0, 0, 0) !important;
  transform: translate3d(0, 0, 0) !important;
}
md-sidenav.md-closed.md-locked-open-add-active {
  -moz-transform: translateX(0) !important;
  -ms-transform: translateX(0) !important;
  -o-transform: translateX(0) !important;
  -webkit-transform: translateX(0) !important;
  transform: translateX(0) !important;

  -moz-transform: translateZ(0) translateX(0) !important;
  -ms-transform: translateZ(0) translateX(0) !important;
  -o-transform: translateZ(0) translateX(0) !important;
  -webkit-transform: translateZ(0) translateX(0) !important;
  transform: translateZ(0) translateX(0) !important;

  -moz-transform: translate3d(0, 0, 0) !important;
  -ms-transform: translate3d(0, 0, 0) !important;
  -o-transform: translate3d(0, 0, 0) !important;
  -webkit-transform: translate3d(0, 0, 0) !important;
  transform: translate3d(0, 0, 0) !important;
}

.md-sidenav-backdrop.md-locked-open {
  display: none;
  -moz-transform: translateX(0) !important;
  -ms-transform: translateX(0) !important;
  -o-transform: translateX(0) !important;
  -webkit-transform: translateX(0) !important;
  transform: translateX(0) !important;

  -moz-transform: translateZ(0) translateX(0) !important;
  -ms-transform: translateZ(0) translateX(0) !important;
  -o-transform: translateZ(0) translateX(0) !important;
  -webkit-transform: translateZ(0) translateX(0) !important;
  transform: translateZ(0) translateX(0) !important;

  -moz-transform: translate3d(0, 0, 0) !important;
  -ms-transform: translate3d(0, 0, 0) !important;
  -o-transform: translate3d(0, 0, 0) !important;
  -webkit-transform: translate3d(0, 0, 0) !important;
  transform: translate3d(0, 0, 0) !important;
}

.md-sidenav-left, md-sidenav {
  -moz-transform: translateX(0) !important;
  -ms-transform: translateX(0) !important;
  -o-transform: translateX(0) !important;
  -webkit-transform: translateX(0) !important;
  transform: translateX(0) !important;

  -moz-transform: translateZ(0) translateX(0) !important;
  -ms-transform: translateZ(0) translateX(0) !important;
  -o-transform: translateZ(0) translateX(0) !important;
  -webkit-transform: translateZ(0) translateX(0) !important;
  transform: translateZ(0) translateX(0) !important;

  -moz-transform: translate3d(0, 0, 0) !important;
  -ms-transform: translate3d(0, 0, 0) !important;
  -o-transform: translate3d(0, 0, 0) !important;
  -webkit-transform: translate3d(0, 0, 0) !important;
  transform: translate3d(0, 0, 0) !important;
}

.md-sidenav-left.md-closed, md-sidenav.md-closed {
  -moz-transform: translateX(-100%)!important;
  -ms-transform: translateX(-100%)!important;
  -o-transform: translateX(-100%)!important;
  -webkit-transform: translateX(-100%)!important;
  transform: translateX(-100%)!important;

  -moz-transform: translateZ(0) translateX(-100%)!important;
  -ms-transform: translateZ(0) translateX(-100%)!important;
  -o-transform: translateZ(0) translateX(-100%)!important;
  -webkit-transform: translateZ(0) translateX(-100%)!important;
  transform: translateZ(0) translateX(-100%)!important;

  -moz-transform: translate3d(-100%, 0, 0)!important;
  -ms-transform: translate3d(-100%, 0, 0)!important;
  -o-transform: translate3d(-100%, 0, 0)!important;
  -webkit-transform: translate3d(-100%, 0, 0)!important;
  transform: translate3d(-100%, 0, 0)!important;
}
```

**Comment by augiegardner** [comment] 2016-06-28 07:24
Why is this closed?

The DEMO site has terribly slow ink ripples for every button when viewed from a brand new galaxy s6 edge. They're basically non existent.

Can anyone tell me why it's closed? Did I miss a note of a fix?

**Comment by ryanpager** [comment] 2016-06-28 12:56
Any non-critical issues I believe were triaged so that they can focus on angular material 2.

**Comment by foaudkajj** [comment] 2016-08-27 07:13
+1

**Comment by SlavaSlimmy** [comment] 2016-11-23 09:40
+1
