### ISSUE TITLE
Flex and layout-wrap doesn't work on safari

### ISSUE THREAD

**Issue by gearguy365** [angular/material#10701] opened 2017-05-30 05:38 UTC
**Actual Behavior**:
 -  In OSX and iOS Safari browser no **flex** value is working on child elements when **layout-wrap** is applied in parent element.
 -  Child elements are expected to go in new row with accordance to the flex value, which works fine in all other browsers. 

**How to reproduce**
 -  Issue is visible throughout demo and API reference pages in **material.angularjs.org**, for example:

![bug](https://cloud.githubusercontent.com/assets/2935672/26569139/a9e79a9e-452a-11e7-964b-2b016ec4b90e.PNG)

**Comment by AkhilNaidu09** [comment] 2017-06-06 11:42
Iam also facing the same issue in iPad. layout-wrap will not work in safari. event i tried to use flex-wrap css properties still same issue in safari

**Comment by jeddai** [comment] 2017-06-06 16:55
I am also seeing a similar issue on desktop. While it does not prevent other aspects of Angular Material from working as expected, it would be great for this to be fixed given that this is highly important for making responsive sites and generally laying out websites properly.

<img width="853" alt="screen shot 2017-06-06 at 11 52 26 am" src="https://user-images.githubusercontent.com/4909307/26841285-a20ffa12-4aae-11e7-9a6c-a553d0690aa5.png">
(Safari Version 10.1.1 (12603.2.4))

**Comment by homerjam** [comment] 2017-07-20 15:22
+1

**Comment by LeoLozes** [comment] 2017-07-21 12:19
Related to #10345 and #10388 ...

**Comment by danielgranat** [comment] 2017-07-29 22:18
Experiencing the same issue, I understand this is caused by a safari bug. I tried solving this by changing the -webkit-flex-basis to match the flex percentage, and it looks like it solved the issue.
This is an example of the bug http://plnkr.co/edit/qhi5xwYF5QRi5C9yGD2e?p=preview
This is the workaround- http://plnkr.co/edit/ebD73Qh5tIK538dWknl2?p=preview

What do you think? Is this a good solution or am I misusing flex-basis?

**Comment by FlorianBurgevin** [comment] 2017-09-12 12:34
Not in 1.1.5 👎  :(

I can't upgrade material version without break my app on safari...

Any news?

**Comment by andrew-cunliffe** [comment] 2017-09-15 21:23
👍 

had really been hoping 1.1.5 was going to fix this, been stuck on 1.1.1 for a while now due to this, but then we are starting to prepare to upgrade the material 2 now :) still would be nice to update and address some of the bugs recent versions have fixed elsewhere ;)

**Comment by ThomasBurleson** [comment] 2017-09-15 21:40
@andrew-cunliffe - if you prepare a focused Pull-Request fixing this issue, then I will work to get it merged into `master`.

**Comment by andrew-cunliffe** [comment] 2017-09-17 14:06
So I went to look at fixing this (ran into a number of issues running the project and assume they are known - conflicts in master package-lock.json so had to remove this file to perform npm install, out of date dependencies which mean running the project with Node 8 fails, when you update it builds and runs the tests but the docs are not building locally due to and issue with parsing the params in the comments for directives etc etc...)

Anyhow that aside I took a different approach and found it was an issue with the layout.scss file... a change implemented to not use a dynamic value but force 100% width... however this change was a PR done by yourself for v1.1.2 - https://github.com/angular/material/pull/9572/files

Now I can see on that PR you have a few other issues (which if I had fully followed the chains here I might have found sooner...)

Based on there being several issues with this past PR I wonder what the best course of action is? I could submit a PR to undo that PR, which will fix Safari but I assume that PR was fixing a problem elsewhere?

What do you do in this situation, revert that change and consider that past PR and alternatives to fix it? Leave Safari broken? Something else?

**Comment by FlorianBurgevin** [comment] 2018-01-17 14:06
Still not in this version... ??

Someone tested on safari with 1.1.6? Is it better or not?

**Comment by Splaktar** [comment] 2018-01-29 23:11
@andrew-cunliffe I think that all of the NodeJS, `package-log.json`, and docs build issues have been fixed in 1.1.6 and master. 

There are quite a number of open layout issues that are quite serious. I plan to take some time to review them all and decide upon a course of action.

There is some information on the root of this bug here: https://github.com/angular/material/issues/5345#issuecomment-267838710

**Comment by Splaktar** [comment] 2018-01-29 23:16
This is a duplicate of https://github.com/angular/material/issues/10345 where the bug in Safari is identified and linked.

**Closed by Splaktar** 2018-01-29 23:16 UTC
Labels: browser: Safari, resolution: duplicate, ui: flexbox, ui: layout
