### ISSUE TITLE
mdDateTime - a date time picker

### ISSUE THREAD

**Issue by mlb6** [angular/material#648] opened 2014-11-14 05:24 UTC
Hi,

It would be very nice to have a date and a time picker.
This could be inspired by this project : http://amsul.ca/pickadate.js
Here are my suggestions (based on use case I already had in some e-commerce projects):
- Ability to select 1 or multiple dates (To select a technical appointment with your cable company)
- Ability to select a period (To select dates of departure and return in a travel website)
- Ability to enable or disable dates based on a model of availability.
- Ability to display 1 or multiple calendars.

Thanks

**Comment by dg1202** [comment] 2015-02-10 19:31
+1

**Comment by ThomasBurleson** [comment] 2015-02-25 20:42
@marcysutton  - I re-opened for @robertmesserle implementation efforts.

**Comment by calidion** [comment] 2015-03-04 16:40
i18n is a must.
thanks.

**Comment by dsbaars** [comment] 2015-03-13 22:25
@marcysutton Why is the forum closed?

**Comment by marcysutton** [comment] 2015-03-13 22:29
@dsbaars it's not actually closed. I believe all you have to do is sign in and register. I have multiple Google accounts, and only one is registered to view that forum.

**Comment by nickleefly** [comment] 2015-03-20 13:34
A react component here http://material-ui.com/#/components/date-picker
![vertical](https://cloud.githubusercontent.com/assets/1024773/6752355/c2608126-cf48-11e4-9df6-b7bb6f07e335.png)
![horizontal](https://cloud.githubusercontent.com/assets/1024773/6752358/c4411a3c-cf48-11e4-85d5-566fe0c870b8.png)

**Comment by dsbaars** [comment] 2015-03-20 14:11
@nickleefly Looks good, but i'm missing the month/year-selector which makes it not very user-friendly for  example, choosing your birthdate.

**Comment by bastienJS** [comment] 2015-04-04 12:25
If you guys do the datepicker then please offer also an inline version. It does not make sense on a desktop/tablet browser to open a dialog just for setting a date...

**Comment by marvoh** [comment] 2015-04-06 04:31
What was decided about this? Cannot seem to find the discussion on Google.

**Comment by mprentic-harris** [comment] 2015-04-28 13:40
@bastienJS for "inline version" does this refer to a popup like is seen in most web applications today vs an actual dialog window?

**Comment by denjello** [comment] 2015-05-01 13:33
In case any googlers are following this, maybe a good idea to correct this image. Spoiler: Friday is the 14th, not the 13th.
http://www.google.com/design/spec/components/pickers.html#pickers-date-pickers
![Friday the 13th](https://material-design.storage.googleapis.com/publish/material_v_3/material_ext_publish/0B7WCemMG6e0VUTVnTWd4SUxZRTg/components_pickers_date1.png)

**Comment by robertmesserle** [comment] 2015-05-01 13:36
That looks right to me for 2014

**Comment by denjello** [comment] 2015-05-01 14:35
Its confusing because apparently the "NOW" time is Friday the 7th, but the selection has been made on Thursday the 13th (the turquoise circle). The banner at the top shows BOTH Friday (the 7th???) and March 13th which is a bit of a semantic slide-tackle.

**Comment by mprentic-harris** [comment] 2015-05-04 13:26
@denjello OK, I finally see what you are talking about. It wasn't clear from your description. The issue is that Thursday is selected on the date picker, but the header shows Friday. That is certainly unexpected. I notice that it is correct on two other screenshots, but wrong on the first two.

**Comment by kuitos** [comment] 2015-05-06 08:14
+1

**Comment by trsrm** [comment] 2015-05-25 10:44
+1

**Comment by kamarouski** [comment] 2015-05-27 04:59
Just an idea to shoot. Can we have an option to have datetime picker "inline" i.e. appear right below\above the input rather than huge popup dialog. The dialog is good for mobile devices but for web "classic" behaviour might be better and less confusing to users.

**Comment by bartlomiejborzucki** [comment] 2015-05-28 14:22
+1

**Comment by kamarouski** [comment] 2015-05-31 15:30
I know that you hate these kind of questions, but are there any plans to have date time picker in master in near future? Are there plans to implement it using phased approach like with menu?

I know you are are very busy with a lot of stuff and will patiently wait for this important component, though a little bit of clarity here would be very helpful.

**Comment by mprentic-harris** [comment] 2015-06-01 14:31
I don't have an official answer, but I feel that "in near future" is unlikely. Work is happening and will likely occur in a separate WIP branch at some point. Even after that branch opens, it will likely take more than a month to stabilize the component.

**Comment by nhduc296** [comment] 2015-06-04 13:44
+1

**Comment by csvan** [comment] 2015-06-06 10:25
+1

**Comment by csvan** [comment] 2015-06-06 10:27
For those looking for a current solution, consider this:

https://github.com/mobinni/material-date-picker

**Comment by opadillaintegrify** [comment] 2015-06-09 14:31
The "milestone 0.10.0" at the top of this page got my hopes up, but I'm looking at https://material.angularjs.org/0.10.0-rc1/#/ and not seeing any mention of a date picker.   :(

**Comment by georgebarbarosie** [comment] 2015-06-10 16:27
@opadillaintegrify as far as I can see there is quite active development happening on wip/calendar for feat(datepicker). Seeing how 0.10-rc2 added two new controls, I'd say it's not impossible that 0.10 final would contain datepicker. If not 0.10 then not too long after it.

**Comment by tbaeg** [comment] 2015-06-10 18:05
+1

**Comment by idoo** [comment] 2015-06-10 18:33
:+1:

**Comment by tflori** [comment] 2015-06-11 15:30
+1

**Comment by benbrownlol** [comment] 2015-06-11 15:56
+1

I desperately need this!

**Comment by ivanhtp** [comment] 2015-06-11 17:26
@SimeonC solution looks pretty descent for now. I'll be really sad to implement it right now and the team release one or two days ahead :yum:

**Comment by nestorneto** [comment] 2015-06-13 22:39
+1

**Comment by Ins87** [comment] 2015-06-15 11:16
+1

**Comment by ask007java** [comment] 2015-06-15 20:19
+1

**Comment by malammar** [comment] 2015-06-15 23:42
+1

**Comment by benbrownlol** [comment] 2015-06-16 10:20
@SimeonC solution doesnt seem to work for me, trying to figure out whats causing the conflict, some kind of style conflict it seems.

![screen shot 2015-06-16 at 11 20 18](https://cloud.githubusercontent.com/assets/7733537/8180915/b2de5fd2-1419-11e5-87b9-feb8c65d19e4.png)

**Comment by chinnichaitanya** [comment] 2015-06-16 10:22
Yes even I'm facing the same issue as above but there are no errors though.

**Comment by jozsi** [comment] 2015-06-16 10:23
That's a known bug: https://github.com/SimeonC/md-date-time/issues/16

**Comment by SergeyBukhman** [comment] 2015-06-16 11:10
+1

**Comment by edinella** [comment] 2015-06-16 21:55
+1

**Comment by jojoyuji** [comment] 2015-06-16 21:56
+1

**Comment by MacgyverMartins** [comment] 2015-06-16 22:08
+1

**Comment by ThomasBurleson** [comment] 2015-06-16 22:22
We are actively working on this component.
Locking the conversation for now...

**Comment by jelbourn** [comment] 2015-08-18 17:56
`md-datepicker` has landed in master. Please file specific bugs and features requests going forward.

**Closed by jelbourn** 2015-08-18 17:56 UTC
Labels: for: internal contributor, type: component, type: feature
