### ISSUE TITLE
The "next tab arrow" icon  on IE in a dialog is always inactive and the selected tab underline is missing

### ISSUE THREAD

**Issue by flex123** [angular/material#8248] opened 2016-04-27 21:48 UTC
On Chrome, the "next tab arrow" icon is active and the selected tab is underlined

![image](https://cloud.githubusercontent.com/assets/10717743/14869213/fb6f73ec-0c9f-11e6-863d-dc5a6b07e6c6.png)

On IE, the "next tab arrow" icon is inactive and the selected tab is not underlined

![image](https://cloud.githubusercontent.com/assets/10717743/14869190/e36db704-0c9f-11e6-816d-fc00bc6aa1b4.png)

**Comment by ThomasBurleson** [comment] 2016-04-29 13:38
Closing this issue due to insufficient information. Please resubmit with:

----
Required
----

**Behavior**:
-  What is the issue? * 
-  What is the expected behavior? 

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue :
-  Details: 

**Angular Versions**: *
-  Angular Version: 
-  Angular Material Version: 

**Additional Information**:
-  Browser Type: *
-  Browser Version: *
-  OS: *
-  Stack Traces: 

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

**Closed by ThomasBurleson** 2016-04-29 13:38 UTC
