### ISSUE TITLE
1.1.0-rc1 list broken

### ISSUE THREAD

**Issue by cadilhac** [angular/material#7513] opened 2016-03-10 18:46 UTC
With 1.0.6 I had a working list in a sidebar, built like this:

```
<md-list>
    <md-list-item ui-sref="Register">
        <md-icon md-font-icon="fa-user-plus" class="fa" style="font-size:20px;margin-right:20px;"></md-icon>
        <span>Register</span>
    </md-list-item>
</md-list>
```

Alignment was perfect, click to trigger a route was perfect and I had a hover effect (background color on hover).
I switched to 1.1.0-rc1 and display is broken (left alignment different for each line of the list), click does not do anything and there is no hover effect anymore.

I noticed that the generated html code is not the same anymore. There is a button tag injected between the list-item and the A tag...

**Comment by DevVersion** [comment] 2016-03-10 18:57
Please provide a demo (with 1.0.6 working and the broken one) - and please check within `master` / `HEAD`.

**Comment by cadilhac** [comment] 2016-03-10 18:59
Hummm, very strange. I can't reproduce that in a codepen. Here it is: http://codepen.io/anon/pen/jqrVEy

Only the alignment is not expected. It is right align instead of left aligned.

I'm wondering what causes the 2 other issues. I checked with Firebug and I can see that a button tag is injected in the list-item... in my app only.

**Comment by cadilhac** [comment] 2016-03-10 19:12
Updated my previous msg. Sorry for that.

**Comment by DevVersion** [comment] 2016-03-10 19:19
@cadilhac This should be already fixed in `master`, but I can't test it yet, because travis has issues.

**Comment by cadilhac** [comment] 2016-03-10 19:24
ok, will wait for your signal.
Can you tell me why the alignment in codepen is right-aligned, even with 1.0.6? In my app and 1.0.6 it's correctly left-aligned.

**Comment by cadilhac** [comment] 2016-03-10 20:47
I know why there is a difference in alignment. In my app I use P tags for the text of my list. In this case this is left-aligned. If I use SPAN tags, like in your docs, it is right-aligned. No idea why...

**Comment by siteshackinc** [comment] 2016-03-11 05:45
Just wanted to comment on this one, as I didnt see this earlier when I posted my issue. But the margin-right is offcanvas. seems to be off by 32px. Adding a span tag with style margin-right temporarily fixes the alignment issue.

**Comment by DevVersion** [comment] 2016-03-11 18:16
Fixed in `master` / `HEAD`. If any other issues appear with the overflow, then they're fixed within #7531

**Closed by DevVersion** 2016-03-11 18:16 UTC
Labels: needs: investigation

**Comment by cadilhac** [comment] 2016-03-11 18:23
I now target MASTER in this [codepen](http://codepen.io/anon/pen/WwxLem) and I don't see it fixed.

**Comment by DevVersion** [comment] 2016-03-11 18:27
Oh the list is definitely fixed. The actual issue was, that the inner-content box was wider the parent container. That's why your text went of the list item. 

So the alignment of your text is not caused by list, it's either caused by the icon you used.

http://codepen.io/DevVersion/pen/oxLJgw

**Comment by cadilhac** [comment] 2016-03-11 18:30
There are several issues in my OP. In the last codepen I sent you, there is no hover effect, no ink ripple. Where is the fix?

About the icon, what is the right way to have my fontawesome icon and being left-aligned then? Seems strange to me that it works with a P tag and fails with a SPAN tag (your doc suggests a span).

**Comment by DevVersion** [comment] 2016-03-11 18:35
@cadilhac In this [codepen](http://codepen.io/DevVersion/pen/oxLJgw). Everything works as expected:
- Ripple
- Hover
- Click / Href
- Layout / Alignment

About the icon, this maybe another issue, can you please track this in a new issue or on the Google Group. I'm really overwhelmed by so many side-questions. After v1.1.0rc1 many issues had been tracked.

**Comment by cadilhac** [comment] 2016-03-11 18:36
Check with latest firefox then. Nothing works.

**Comment by DevVersion** [comment] 2016-03-11 18:41
@cadilhac I can't reproduce this on my Firefox and Chrome. Would you please so kind and share your browser information? And maybe clear the cache?

**Comment by cadilhac** [comment] 2016-03-11 18:49
Cache cleared. Issue still here.
What to say about version more than 45.0 english x64?

Also, FYI, under IE11 in your codepen, I rarely see the ripple. Sometimes yes, usually not. And when I click the listitem, the text shifts diagonally as if it was a basic button. In 1.0.6 everything is correct inside all browsers for me.

**Comment by DevVersion** [comment] 2016-03-11 18:53
Still can't reproduce on Firefox 45.0 Mac OS X Yosemite. 

![image](https://cloud.githubusercontent.com/assets/4987015/13712256/ea96fcf4-e7c2-11e5-844f-1643b8e33f80.png)

What Operating System are you using?

**Comment by cadilhac** [comment] 2016-03-11 18:56
Sorry, Windows 7 Ultimate x64

**Comment by cadilhac** [comment] 2016-03-11 19:25
Just to be sure, I checked on another computer (windows 8.1). Firefox is 44.0 there.
All mentioned issues were reproduceable. Also in IE11 I also get the same strange button effect that I couldn't see under chrome and firefox.

**Comment by DevVersion** [comment] 2016-03-11 19:34
That's really weird. I can't reproduce this on -  Win 10 IE11 - Firefox 45.0 Mac OS X. 
We need someone else to confirm that..

**Comment by cadilhac** [comment] 2016-03-11 19:44
Triggered a Win10 VM. Works well under Edge. Fails under Firefox too.
I understand that you need a confirmation, but I tried under 3 different machines with 3 different Windows OS versions and they all fail in firefox.
Just to be clear, I'm testing [the codepen you mentioned](http://codepen.io/DevVersion/pen/oxLJgw).

**Comment by ThomasBurleson** [comment] 2016-03-11 21:24
@cadilhac - please provide some snapshots of your issues.

**Comment by cadilhac** [comment] 2016-03-11 21:26
How can I provide a smapshot? The issue is in the interaction. Mouse move -> no hover effect. Mouse click -> no ripple and click handler.

**Comment by DevVersion** [comment] 2016-03-11 21:26
@cadilhac You can provide a screenshot of the DOM using Inspection, then I can take a look at the element structure.

**Comment by cadilhac** [comment] 2016-03-11 21:30
Good point. Here it is.

![snapshot](https://cloud.githubusercontent.com/assets/50608/13716027/82dcd582-e7a6-11e5-83cb-0fb05bc6ebc9.jpg)

**Comment by DevVersion** [comment] 2016-03-11 21:43
Issue spotted. You're definitely not using the latest version. 
- Content inside of a `button` causes click issues with Firefox / IE.  

So in your DOM structure, the `_md-list-item-inner` etc. are wrapped inside of the button.

But I've recently fixed that in 497190b72a552b67a39222d087c87958ab359ced, so that shows that you're not using the latest `HEAD` / `master` version.

![image](https://cloud.githubusercontent.com/assets/4987015/13716314/951be880-e7da-11e5-94bd-5a7f471deb60.png)

**Comment by cadilhac** [comment] 2016-03-11 21:47
Well, I showed you the codepen, and you sent one to me too. They use:

//cdn.gitcdn.xyz/cdn/angular/bower-material/master/angular-material.min.css
//cdn.gitcdn.xyz/cdn/angular/bower-material/master/angular-material.min.js

I see "master" in here...

**Comment by DevVersion** [comment] 2016-03-11 21:50
True, that's strange, but in my case the file is correctly loaded as it should.
Maybe it's still related to your cache. Let's try using the new `gitcdn.link` site, because `xyz` is not desired anymore.

http://codepen.io/DevVersion/pen/oxLJgw

**Comment by cadilhac** [comment] 2016-03-11 21:54
Fixed! :)

Now it can't be a cache problem. The 2 other computers I checked had never seen the involved web sites and files. Seems like xyz is not serving the files we thought it would serve...

**Comment by DevVersion** [comment] 2016-03-11 21:57
@cadilhac Glad to hear that `.link` works now :+1:

**Comment by shershen08** [comment] 2016-04-26 15:43
Upgrading the code in the lists to the mentioned in the codepens and Angular Material version to 1.1.0.-rc4 - solved the problem for me.
But is there a way to make ```<md-buttons>``` click inside of the ```<md-list-item>``` work in Firefox if **I am still on 1.0.7 version**?
