### ISSUE TITLE
Circular progress animation is wrong inside dialog

### ISSUE THREAD

**Issue by ido567** [angular/material#5039] opened 2015-10-06 19:04 UTC
The animation of a indeterminate circular progress bar inside a dialog with custom layout is looking weird!
You can look at the codepen example:

https://codepen.io/anon/pen/jbmZgV

**Comment by ThomasBurleson** [comment] 2015-10-06 19:16
The progressCircular indicator looks fine to me: see [Online Docs](https://material.angularjs.org/0.11.2/#/demo/material.components.progressCircular).
 
What is the issue?

**Comment by EladBezalel** [comment] 2015-10-06 19:18
Hey @ThomasBurleson I can see it too on mobile. (LG G3 Chrome)

**Comment by ThomasBurleson** [comment] 2015-10-06 19:27
@EladBezalel - assigned to you. LOL

**Comment by ido567** [comment] 2015-10-06 19:40
Also happens on Chrome version 45.0.2454.101 m

**Comment by ThomasBurleson** [comment] 2015-10-06 19:51
I am not seeing anything wrong in Chrome Canary (v48.x): http://codepen.io/ThomasBurleson/pen/xwdWRQ

![screen shot 2015-10-06 at 2 52 55 pm](https://cloud.githubusercontent.com/assets/210413/10320581/c93d8c1c-6c39-11e5-9544-b2716553beb2.png)

**Comment by ido567** [comment] 2015-10-06 20:18
That's what I see in my codepen:
![Image](http://i.imgur.com/LOmj97M.png)

For your's I see the following error (from mobile and chrome):
![Image](http://i.imgur.com/IfPRl0f.png)

**Comment by ThomasBurleson** [comment] 2015-10-06 20:32
@ido567 - notice the Console errors? Make sure you are using:

```js
angular.module("MyApp", ['ngMaterial'])
```

**Comment by ido567** [comment] 2015-10-06 21:11
I managed to make your codepen to work, but I don't see any circular progress.
I can see dialog with auto-complete component, but that's it.

**Comment by ThomasBurleson** [comment] 2015-10-06 21:19
My apologies: here is the CodePen with the dialog and circular progress indicator:  http://codepen.io/ThomasBurleson/pen/MamVvV

**Comment by ido567** [comment] 2015-10-06 21:23
I'm sorry, but it still not working! It looks the same as my picture above

**Comment by ThomasBurleson** [comment] 2015-10-06 22:37
@topherfangio - can you help investigate this issue? I am unable reproduce any problem.

**Comment by spektor56** [comment] 2015-10-07 21:41
The animation is not smooth and skips around for me on Chrome: Version 45.0.2454.101 m.  On the angular material demo site it does a little hiccup after every rotation.

**Comment by EladBezalel** [comment] 2015-10-10 20:15
It seems to be the `md-dialog-content` css `overflow: auto` property.
I can't figure why overflow influencing the animation..

**Comment by topherfangio** [comment] 2015-10-14 15:43
@EladBezalel It appears to be something with the transform actually.

In order to make it prettier as it scales to larger sizes, we actually make the circular progress 100px wide/tall and then do `transform: scale(0.5)` to get it back to 50px/50px. If we change this to `scale(1)` or even `scale(0.75)`, the animation is once again smooth. I tried a bunch of different values and it started to degrade at around `0.60`.

I'm really not sure *why* it's doing this, but the transform seems to be the root of the issue.

Hopefully this will point you in the right direction :smile:

**Comment by ThomasBurleson** [comment] 2015-10-14 15:47
@topherfangio - we did the reverse scaling for exactly that reason:  smooth anti-aliasing at values > 50 <= 100 px. I can understand the animation being smoother with `scale(1)`. But I am completely confused why `scale(0.75)` does not degrade animation while `scale(0.5)` does.

@jelbourn, @robertmesserle - Thoughts ?

**Comment by EladBezalel** [comment] 2015-10-14 16:21
well, it's smooth with `scale(.55)` also..

**Comment by Soulcyber** [comment] 2015-10-20 07:31
for me the indicator start look glitching from 0.63 and below on Chrome 46.0.2490.71 m

**Comment by EladBezalel** [comment] 2015-10-31 13:43
After more investigations.. found out that if we mute the `z-index` of the toolbar it's working..
also if muting `min-height` it's working, my guess, somehow the container height is influencing the animation position
https://codepen.io/EladBezalel/pen/KdeByy

**Comment by robertmesserle** [comment] 2015-11-20 19:43
This seems like the browser is just choking on how many simultaneous animations there are.  If you turn off the outer rotation animation on the spinner, it works fine.

Also, adding a z-index of 2 or greater to `md-progress-circular` seems to fix the issue for some reason.

@ThomasBurleson Do we want to add the z-index along with a comment warning future developers to <movie voice>forget everything you know about CSS</movie-voice>?

**Comment by robertmesserle** [comment] 2015-11-20 19:44
Or more likely, add the z-index only when it's inside of a dialog.  I'm not sure if it would be better to add it globally.

**Comment by EladBezalel** [comment] 2015-11-20 19:48
@robertmesserle IMO a z-index inside a dialog with a <batman-voice> comment would be a lot better! but yea i think it's this easy fix instead of getting into the hood of the animations

**Comment by robertmesserle** [comment] 2015-11-20 19:52
@EladBezalel Yea, I'm not sure that this bug is going to have a logical fix.  It's also temporary as I believe this is being rewritten; however, I worry about other circumstances where this bug will exist due to the user's CSS rather than being inside of a dialog.  Adding a z-index of 2 globally would likely fix these issues without having any real negative impact.

**Comment by EladBezalel** [comment] 2015-11-20 20:09
SGTM until the rewrite

**Closed** 2015-11-20 20:19 UTC
Labels: priority: critical, ui: mobile
