### ISSUE TITLE
Demo site does not work in IE11

### ISSUE THREAD

**Issue by amedeomar** [angular/material#1317] opened 2015-01-27 23:57 UTC
The console shows an error after loading
![image](https://cloud.githubusercontent.com/assets/10732836/5929834/7159a336-a688-11e4-9661-210e481da35a.png)
![image](https://cloud.githubusercontent.com/assets/10732836/5929841/91b4a23e-a688-11e4-93e9-fbda092eb344.png)

**Comment by marcysutton** [comment] 2015-01-28 00:29
@ajoslin I debugged this one for half an hour and I can't track down the cause.

**Comment by marcysutton** [comment] 2015-01-29 02:10
Fixed with e3e38eaf9cfc33b84432eede1dd85ac8f0c58886

**Closed by marcysutton** 2015-01-29 02:10 UTC
