### ISSUE TITLE
Datepicker Issues (Release 1.0.2) #6725 

### ISSUE THREAD

**Issue by sudharsanmit** [angular/material#6757] opened 2016-01-19 18:30 UTC
Pinned to #6725 . On request of asignee, splitting the issues into multiple tickets.
Standard Day Picker:

Issue 5:
Input date 13/20/2097 through keyboard. On clicking calendar icon, the date Jan 20 2098 gets highlighted and able to select first week of Jan 2098 (1,2,3 & 4) selectable thru mouse. Unable to choose any before or after. Also note, no restriction on the month (13 entered).

**Comment by jelbourn** [comment] 2016-01-19 19:45
Dupe of #6397

**Closed by jelbourn** 2016-01-19 19:45 UTC

**Comment by sudharsanmit** [comment] 2016-01-19 20:23
Not a duplicate of #6397 which talks about minimum date. Read the issue fully. 
Issues here -
1. Why does an arbitrary date of Jan 20 2098 get highlighted on the calendar when I entered an invalid date?
2. Why is the first week of Jan 2098 alone selectable by mouse while others are readonly?
3. Why does it not validate an invalid input and mark it with a red underline?

**Comment by sudharsanmit** [comment] 2016-01-19 20:23
I dont agree to this arbitrary closure. Kindly re-open. @ThomasBurleson

**Comment by jelbourn** [comment] 2016-01-19 20:32
The issue is that the date selection is capped on both ends (past and future). It's the same underlying fix for both.

**Comment by sudharsanmit** [comment] 2016-01-19 20:43
@jelbourn Pls note - I entered an invalid date and a random date popped up. Even if the cap on both ends addressed, the invalid input will still be an issue which is not addressed as per #6397.

**Comment by RolandHeath** [comment] 2016-01-20 01:18
@sudharsanmit It wasn't a random date, you entered 13/20/2097 and the Date constructor tried to interpret it for you as 12/20/2097 + 1 month = 1/20/2098
