### ISSUE TITLE
input-container: label and input are not aligned in violation of the spec

### ISSUE THREAD

**Issue by alelau** [angular/material#10830] opened 2017-08-03 10:33 UTC
**Actual Behavior**:
 -  `The alignment between the label and the input text content is not like the one specified on the material design documentation`
![screen shot 2017-08-03 at 12 25 37 pm](https://user-images.githubusercontent.com/6724794/28917996-ef43075e-7847-11e7-977c-53f93bfda65f.png)

 -  `https://material.io/guidelines/components/text-fields.html#text-fields-layout`
![screen shot 2017-08-03 at 12 31 39 pm](https://user-images.githubusercontent.com/6724794/28918001-f3a45136-7847-11e7-99a6-1ae5ff0a330d.png)

**AngularJS Versions**: *
 -  `AngularJS Material Version:1.1.4`

**Comment by Splaktar** [comment] 2020-05-28 07:58
Duplicate of https://github.com/angular/material/issues/10105.

**Closed by Splaktar** 2020-05-28 07:58 UTC
Labels: resolution: duplicate, type: spec alignment
