### ISSUE TITLE
ng-outlet is not rendering to full width

### ISSUE THREAD

**Issue by ashishpatel02** [angular/material#8967] opened 2016-07-07 11:43 UTC
i have few component which is loading through routing dynamically but it's not taking full width. Please find below: 

```
<workspace $router="::$$router" class="ng-scope ng-isolate-scope">
    <div layout="column" layout-fill="" class="layout-fill layout-column">
        <md-content flex="15" layout="column" id="app" class="layout-column flex-15">
            Content
        </md-content>
        <md-content flex="80" layout="column" class="md-default-theme layout-column flex-80"> // Rendering 80% for Column
            <!-- ngOutlet:  -->
            <ng-outlet class="ng-scope">
                <itemparent $router="::$$router" class="ng-scope ng-isolate-scope">
                    <!-- ngOutlet:  -->
                    <ng-outlet class="ng-scope">
                        <itemparent-list $router="::$$router" class="ng-scope ng-isolate-scope">

                            <div flex="100" layout="column" class="inputdemoErrors ng-scope aligned layout-column flex-100"> // Not Rendering 80% for Column, it should be as "md-content flex=80" is alerady having full height and width then also why?
                                Content
                            </div>
                        </itemparent-list>
                    </ng-outlet>
                </itemparent>
            </ng-outlet>
        </md-content>
        <footer flex="5" class="footerheight flex-5">
            Content
        </footer>
    </div>
</workspace>

```

**Comment by DevVersion** [comment] 2016-07-07 12:41
Closing this issue due to insufficient information. Please resubmit with:

----
Required
----

**Behavior**:
-  What is the issue? * 
-  What is the expected behavior? 

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue :
-  Details: 

**Angular Versions**: *
-  Angular Version: 
-  Angular Material Version: 

**Additional Information**:
-  Browser Type: *
-  Browser Version: *
-  OS: *
-  Stack Traces: 

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

**Closed by DevVersion** 2016-07-07 12:41 UTC

**Comment by chenyingyin** [comment] 2016-12-01 05:31
![default](https://cloud.githubusercontent.com/assets/24284270/20782714/60f05eaa-b7c9-11e6-9006-f7beb8bef322.png)
