### ISSUE TITLE
How do I fetch the MD version number from code?

### ISSUE THREAD

**Issue by SanderElias** [angular/material#1515] opened 2015-02-14 17:40 UTC
I like to build plunks to demonstrate issues. However, for some items I use rawgit to get the latest build. That is all working very well, but sometimes it would be handy if i could show or log the MD version. I did a shallow search for this, but could find not how to get it.
So, How to get the MD version?

**Comment by gkalpak** [comment] 2015-02-14 20:29
You probably mean something like [angular.version][1]. That is indeed handy !

[1]: https://docs.angularjs.org/api/ng/object/angular.version

**Comment by hitigon** [comment] 2015-06-08 21:09
+1 really need this

**Comment by ThomasBurleson** [comment] 2015-08-10 22:15
Duplicate of #3842

**Closed by ThomasBurleson** 2015-08-10 22:15 UTC
