### ISSUE TITLE
menu: dark theme no more handled

### ISSUE THREAD

**Issue by zeprone** [angular/material#10062] opened 2016-11-25 08:26 UTC
**Actual Behavior**:
Hi, I just update angular-material from 1.0.8 to 1.1.1 and md-menu is no more handling dark-theme.
**CodePen** (or steps to reproduce the issue): *
http://codepen.io/anon/pen/KNqGpr
this codepen is the md-menu from angular-material website, configured to use dark-theme on 1.1.1

http://codepen.io/anon/pen/qqjJZZ
this one is the same one but with 1.0.9 version.

I did some test, regression occured in 1.1.0 version.

Regards,
Benoit.

**Comment by ElPsyCongro** [comment] 2016-12-23 22:26
+1

**Comment by clshortfuse** [comment] 2016-12-24 15:23
Related #9100

PR #9212 

The current debate is whether to render light or dark background, if it's a  regression or correction in 1.1.0

**Comment by zeprone** [comment] 2017-01-07 21:46
based on https://material.io/guidelines/style/color.html#color-themes 
we should have a dark background, like the dialog one in section "dark theme"

**Comment by clshortfuse** [comment] 2017-01-27 15:51
Closing, since duplicate of #9100

**Closed by clshortfuse** 2017-01-27 15:51 UTC
Labels: needs: team discussion, ui: theme
