### ISSUE TITLE
textarea problem on safari

### ISSUE THREAD

**Issue by sombriks** [angular/material#7774] opened 2016-03-27 16:47 UTC
hello, 

this snippet behaves oddly when running under osx/ios safari: http://codepen.io/anon/pen/oxwqEd

the very same snippet looks pretty nice on chrome and firefox.

**Comment by DevVersion** [comment] 2016-03-30 09:54
@crisbeto Can you take a look? I recently switched back to Windows, so I'm not able to test that.

**Comment by crisbeto** [comment] 2016-03-30 09:58
I'm on Windows as well. I tried it out on a VM that I have with OSX, but the Safari is kinda old and we don't seem to be supporting it.

**Comment by DevVersion** [comment] 2016-03-30 10:01
@crisbeto Yes, I know that, I will test that later on my MacBook. Just tested with iOS and I can confirm, it behaves really odd.

**Comment by crisbeto** [comment] 2016-03-30 16:51
The textarea behaves fine, but for some reason that button "sinks" into it:

![img_0098](https://cloud.githubusercontent.com/assets/4450522/14150249/7293b540-f6a8-11e5-8da6-0a250a4e35a3.PNG)

**Comment by crisbeto** [comment] 2016-04-24 08:56
@sombriks, Seems like some kind of browser flexbox issue, which also happens in IE and there's a console warning about it. You can achieve exactly the same layout, without the display issues, if you remove the `flex` attribute from the `md-button`, the `div` around the button and the `md-input-container`:

```html
 <h4>Comentar ocorrência</h4>
  <form flex layout="column" layout-margin layout-align="center center" name="novocomentario" ng-submit="savecoment()">
    <md-input-container class="md-block">
      <label>Novo comentário</label>
      <textarea required ng-model="novocoment.dsccomentocorrencia" md-maxlength="900"></textarea>
    </md-input-container>

    <div>
      <md-button ng-disabled="!novocoment" class="md-raised md-primary" type="submit">
        Publicar
      </md-button>
    </div>
  </form>
```

@DevVersion what do you think about this one, I'm not sure whether this is the proper way to use the `flex` attribute?

**Comment by DevVersion** [comment] 2016-04-24 09:02
@crisbeto I think you're right. 

There are currently a few bugs with the FlexBox engine in some browsers.
- https://github.com/angular/material/issues/7714
- https://github.com/angular/material/issues/7753

I would close this issue, because it's actually a duplicate and it is currently not recommended to apply flex attributes on buttons.

**Comment by crisbeto** [comment] 2016-04-24 09:08
Alright, I'll come it. @sombriks you should be able to work around this with the snippet I posted above.

**Closed by crisbeto** 2016-04-24 09:08 UTC

**Comment by sombriks** [comment] 2016-05-19 15:27
@crisbeto Sorry for delay, indeed all it took was remove flex from md-input-conainer surrounding textarea. Thank you!

iOS version is fine again.
