### ISSUE TITLE
datepicker: invalid value on first load from string

### ISSUE THREAD

**Issue by TemitaTom** [angular/material#12075] opened 2021-01-26 11:32 UTC
## Demo and steps to reproduce the issue
[This blank StackBlitz demo](https://stackblitz.com/edit/angularjs-material-blank?file=app%2Fapp.template.html) can be used to create a reproduction that demonstrates your issue.

**Demo URL (required)***:  

#### Detailed Reproduction Steps

**HTML**
```html
<md-content ng-app="MyApp" ng-controller="AppCtrl as ctrl" layout-padding="" layout-margin="" class="datepickerdemoMoment">
  <form name="form1" ng-model="ctrl.form">
  <md-datepicker name="datep" ng-model="ctrl.myDate" ng-change="ctrl.onDateChanged()" md-placeholder="Enter date"></md-datepicker> 
  Date: {{ctrl.myDate | date:shortDate}} {{ form1.datep.$error }}
</md-content>
  </form>
<!--
Copyright 2020 Google LLC. All Rights Reserved. 
Use of this source code is governed by an MIT-style license that can be found
in the LICENSE file at http://material.angularjs.org/HEAD/license.
-->
```

**JS**
```js
(function () {
  'use strict';

  angular.module('MyApp', ['ngMaterial', 'ngMessages', 'material.svgAssetsCache']).config(function($mdDateLocaleProvider) {
    /**
     * @param date {Date}
     * @returns {string} string representation of the provided date
     */
    $mdDateLocaleProvider.formatDate = function(date) {
      return date ? moment(date).format('L') : '';
    };

    /**
     * @param dateString {string} string that can be converted to a Date
     * @returns {Date} JavaScript Date object created from the provided dateString
     */
    $mdDateLocaleProvider.parseDate = function(dateString) {
      var m = moment(dateString, 'L', true);
      return m.isValid() ? m.toDate() : new Date(NaN);
    };
  })
  .controller("AppCtrl", function($log) {
    this.myDate = "2021-01-20T07:00:00Z";

    this.onDateChanged = function() {
      $log.log('Updated Date: ', this.myDate);
    };
  });
})();


/**
Copyright 2020 Google LLC. All Rights Reserved. 
Use of this source code is governed by an MIT-style license that can be found
in the LICENSE file at http://material.angularjs.org/HEAD/license.
**/
```

With this code, the date IS INVALID. In version AMjs 1.2.1 work great.

### List the affected versions of AngularJS, Material, OS, and browsers

- AngularJS: 1.8.2
- AngularJS Material: 1.2.2
- OS: All
- Browsers: All
- Screen Readers: 
 
#### Stack Trace
```

```

**Comment by Splaktar** [comment] 2021-02-01 01:45
Since a StackBlitz demo (required) was not provided, I had to do some work to get this sample code to run. Here's the [StackBlitz demo](https://stackblitz.com/edit/datepicker-invalid-value-on-first-load-from-string-12075?file=app%2Fapp.template.html).

**Comment by Splaktar** [comment] 2021-02-01 02:08
For now, the quick workaround is doing
```js
ctrl.myDate = new Date("2021-01-20T07:00:00Z");
```
instead of 
```js
ctrl.myDate = "2021-01-20T07:00:00Z";
```

**Comment by Splaktar** [comment] 2021-07-05 21:01
It looks like this was caused by https://github.com/angular/material/commit/b406623f08cd229ea76cc06298eea764bd51ab84.

**Comment by Splaktar** [comment] 2021-07-05 21:49
Fixed in https://github.com/angular/material/pull/12115

**Closed** 2021-07-08 17:45 UTC
Labels: P2: required, has: Pull Request, severity: regression, type: bug

**Comment by j-walker23** [comment] 2021-08-06 16:58
Dang, this only fixed it for string. Not moment objects.
