### ISSUE TITLE
Monkey patching Array or Object breaks $mdDialog open/close animation

### ISSUE THREAD

**Issue by jmcpeak** [angular/material#4355] opened 2015-08-27 18:40 UTC
So I finally tracked down what was causing my open/close animations to not work.

Turns out if you monkey patch Array or Object anywhere in the controller or out it basically acts like targetEvent was not set. (If you patch String, it is fine though, weird.)

http://codepen.io/jmcpeak/pen/VvZWYj?editors=101

**Comment by dnadoba** [comment] 2015-08-28 09:33
the problem is that the $mdUtil.supplant doesn't check with hasOwnProperty while it iteration over the values
https://github.com/angular/material/blob/5d03df8ea38ae8fdc245d7edcac7e3b5fcb3795c/src/core/util/util.js#L268

**Comment by ThomasBurleson** [comment] 2015-10-08 00:19
Fixed with `hasOwnProperty( )`

**Closed by ThomasBurleson** 2015-10-08 00:19 UTC
