### ISSUE TITLE
New date adapter for Date Picker

### ISSUE THREAD

**Issue by Marcusg62** [angular/material#12024] opened 2020-09-24 04:17 UTC
## Bug, Enhancement Request, or Proposal

# Demo and steps to reproduce the issue

**Demo URL (required)***:  
https://stackblitz.com/angular/kdleeqglvbb?file=src%2Fapp%2Fdatepicker-views-selection-example.ts

### Discuss the use-case or motivation for changing the existing behavior

Since Chrome suggests moving away from Moment, it would make Lighthouse happier if there were a newer Date Adapter for date pickers. I also propose that the `MomentDateAdapter` should be depreciated. In the [project status](https://momentjs.com/docs/#/-project-status/) for Moment.js, they say one of the only reasons to keep using Moment is if other libraries have it as a dependency. If this could be done, it would be a great way to show leadership about moving the web forward. 

I'm not sure if this is the correct channel to raise this issue, but I wanted to make sure people were aware. 

#### Screenshots

<img width="533" alt="Screen Shot 2020-09-23 at 10 14 59 PM" src="https://user-images.githubusercontent.com/21998115/94100239-521c9180-fdea-11ea-8097-6d29bd872545.png">

**Comment by Splaktar** [comment] 2020-09-24 18:30
Please submit Angular Material and CDK questions [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/components/issues). This repo is for AngularJS Material.

**Comment by Splaktar** [comment] 2020-09-24 18:33
Duplicate of https://github.com/angular/components/issues/20599.

**Closed by Splaktar** 2020-09-24 18:33 UTC
