### ISSUE TITLE
md-input-container not showing error ng-messages 

### ISSUE THREAD

**Issue by vlio20** [angular/material#6767] opened 2016-01-19 21:18 UTC
Hi,
There are cases when the error message (ng-message) not showing, try to play with the codepen below.
the input field is required and minlength set to 2:
http://codepen.io/vlio20/pen/KVybvx?editors=110

Steps to reproduce:
1. focus on input.
2. enter 1 char & focus out (blur) -> minlength error message is displayed.
3. delete the char from step 2 -> no message is displayed, when the required message should have been displayed.

Note-1: The form is invalid with correct message

Note-2: in happens for other validations as well (other then required and minlength).
 If I am overriding the styles like bellow, it seems to be working, but the animations are not good when the error message is changed:

```
md-input-container.md-input-invalid .md-auto-hide .md-input-message-animation:not(.ng-animate) {
  opacity: 1;
  margin-top: 0;
}

md-input-container.md-input-invalid [ng-messages] {
  max-height: 19px;
}
```

I am using 1.0.2 version, but it seems to be broken since 1.0.0

**Comment by keithajackson** [comment] 2016-01-20 19:33
+1 - I am doing custom messaging for server-side errors with ng-messages using an `md-input-container`, and I'm running into the same issue.

```
<md-input-container>
  <div ng-messages="vm.loginServerErrors"
       role="alert">
    <div ng-message="loginFailed">
      Oops! That username and password combination was incorrect.
    </div>
  </div>
</md-input-container>
```

This code worked with v0.11, but no longer works after bumping to 1.0.  Looking into the DOM on the rendered page, the class `md-auto-hide` is getting applied to the `ng-messages` div.  Removing this class restores the original behavior.

**Comment by vlio20** [comment] 2016-01-20 19:40
@keithajackson, did you add some custom code to fix this?

**Comment by keithajackson** [comment] 2016-01-20 19:45
@vilo20  I was hoping to avoid it, but it's looking like I have to override a CSS style to make a workaround:

The offending rules (which are getting applied to the `ng-message` children, not the `ng-messages` parent, are:
```css
md-input-container .md-auto-hide .md-input-message-animation:not(.ng-animate) {
    opacity: 0;
    margin-top: -100px;
}
md-input-container:not(.md-input-invalid) .md-auto-hide .md-input-message-animation {
    opacity: 0;
    margin-top: -100px;
}
```

**Comment by keithajackson** [comment] 2016-01-20 19:49
GOT IT.  I needed to disable auto-hiding on my `ng-messages` div, changing:

```
<div ng-messages="rgn.loginServerErrors" role="alert">
```

to

```
<div ng-messages="rgn.loginServerErrors" role="alert" md-auto-hide="false">
```

The [md-input docs](https://material.angularjs.org/latest/api/directive/mdInput) note that messages will automatically be hidden until the `md-input-container` sets an `md-is-error` expression.

**Comment by keithajackson** [comment] 2016-01-20 19:56
Workaround: I made a [somewhat fixed codepen](http://codepen.io/anon/pen/JGMRzG?editors=110) off your issue, @vlio20 , by handling the visibility myself:

```js
<div ng-messages="registrationForm.agencyName.$error" md-auto-hide="false" ng-if="registrationForm.agencyName.$touched"
```

**Comment by vlio20** [comment] 2016-01-20 20:01
@keithajackson, yea it worked! thanks!!! I think it should be the default behavior.  
Now I have very long html tags :(

Thanks @keithajackson, I will close this issue.

**Comment by keithajackson** [comment] 2016-01-20 20:17
@vlio20 I think we should keep this open.  The workaround fix still results in broken animations.

Open [codepen](http://codepen.io/anon/pen/xZpRVE?editors=110), then:
1. focus on input.
2. enter 1 char & focus out (blur) -> minlength error message is displayed.
3. delete the char from step 2 -> second message slides in, bumping elements down. Then the first message disappears, snapping everything back up.

**Comment by brunsgaard** [comment] 2016-01-21 02:06
Hay guys, thanks for the workaround. Keep the issue open I just ended up here having the same problem as you guys. Lets hope for a real fix soon that will also fix the animation.

**Comment by ThomasBurleson** [comment] 2016-01-27 04:40
A full, valid PR would be welcomed.

**Comment by stephengardner** [comment] 2016-02-27 05:13
Based on this conversation, ng-messages are effectively not working with angular material?  Is that what I'm seeing?

**Comment by vlio20** [comment] 2016-02-27 07:34
You are right. It's not even an edge case

**Comment by photusenigma** [comment] 2016-03-01 18:55
+1

**Comment by dougpix** [comment] 2016-03-01 18:57
+1

**Comment by volmerf** [comment] 2016-03-03 12:37
+1

**Comment by jobo26** [comment] 2016-03-03 12:38
+1

**Comment by pjwalmsley** [comment] 2016-03-03 20:59
+1

**Comment by danidewitt** [comment] 2016-03-03 21:15
+1

**Comment by galharth** [comment] 2016-03-07 12:30
+1

**Comment by autumnfjeld** [comment] 2016-03-08 21:59
+1

**Comment by tomiplaz** [comment] 2016-03-09 16:32
+1

**Comment by pablozandona** [comment] 2016-03-15 18:47
+1

**Comment by phxrefugee** [comment] 2016-03-18 16:01
+1

**Comment by destegabry** [comment] 2016-04-07 15:54
+1

**Comment by alexilyaev** [comment] 2016-04-13 15:12
I have an `<md-checkbox>`  that I'm trying to show an error for when not selected, on form submit.

```html
<md-input-container class="md-block">
  <md-checkbox name="tos" ng-model="Register.tosAgreed" required>
    I agree to the Terms of Service
  </md-checkbox>

  <div ng-messages="Register.basicForm['tos'].$error">
    <div ng-message="required">You must accept the Terms of Service.</div>
  </div>
</md-input-container>
```

The error doesn't show when submitting, mainly because `md-input-invalid` is not added to the `md-input-container` like it does with regular inputs.

**Comment by vianneyniji** [comment] 2016-04-28 13:49
+1

**Comment by alexilyaev** [comment] 2016-04-28 21:30
@ThomasBurleson I see the issue is closed, can you tell us what was the solution?  
Will my example above be fixed?

**Comment by brianfeister** [comment] 2016-04-29 18:17
+1... this issue has been a huge problem for my team for a long time and was excited to find it addressed in a bug report and now disappointed to see that it's closed.

**Comment by akiro** [comment] 2016-05-06 10:16
+1

**Comment by davidcestare** [comment] 2016-05-09 15:26
+1

**Comment by vlio20** [comment] 2016-05-09 15:29
@ThomasBurleson, is this issue resolved?

**Comment by smolyakoff** [comment] 2016-05-12 06:45
+1 This bug needs a proper fix

**Comment by jpmermoz** [comment] 2016-05-17 03:43
+1 here

**Comment by PAKISTANESSS** [comment] 2016-05-20 16:33
+1, release a fix please.

**Comment by engineerkhushal** [comment] 2016-05-27 15:06
For those who are seeking a custom fix here is one.

1. Define this css

```
md-input-container .md-auto-hide .md-input-message-animation:not(.ng-animate), md-input-container .md-input-message-animation.ng-enter, md-input-container:not(.md-input-invalid) .md-auto-hide .md-input-message-animation {
  opacity: 1;
  margin-top: 0px;
}

.ng-messages-fix{
  visibility: hidden;
}
```

And then use ngMessages like these

```
<div ng-messages="form.inputField.$error" ng-class="{ 'ng-messages-fix' : form.inputField.$pristine}">
	<div ng-message="required">required</div>
	<div ng-message="maxlength">length exceeded</div>
	<div ng-message="pattern">not acceptable</div>
</div>
```

**Comment by mlqmarkos12** [comment] 2016-06-22 19:46
+1

**Comment by RajanRastogi** [comment] 2016-06-24 06:15
+1

thanks for the workaround, but love to see this fixed.

**Comment by BevanR** [comment] 2016-07-05 22:01
+1

@engineerkhushal; This doesn't seem to work with `<md-checkbox>`.  Any ideas?

**Comment by EricWVGG** [comment] 2016-07-06 15:34
+1

**Comment by ymind** [comment] 2016-07-22 10:07
+1

**Comment by pandales** [comment] 2016-07-22 21:10
I had a similar problem and I added the ng-show directive to the ng-messages in this way
<div ng-messages="accountForm.email.$error" ng-show="accountForm.email.$touched">

and it worked!!!!

**Comment by vlio20** [comment] 2016-07-23 04:01
@pandales, can you please supply some code, or even better create a pen or plunker?

**Comment by pandales** [comment] 2016-07-23 22:41
@vlio20 this is the code that I did.
<md-input-container>
      <label>Email address</label>
      <input type="email"
             name="email"
             ng-model="form.account.email"
             required>

      **<div ng-messages="accountForm.email.$error" ng-show="accountForm.email.$touched">
        <div ng-message="required">This is required!
        </div>
        <div ng-message="email">This field must be a valid email**
        </div>
      </div>
    </md-input-container>

Adding the ng-show directive to the ng-messages div guarantees that the md-auto-hide directive don't be evaluated,  and use the .$touched state in the form guarantees that the messages only are shown after the input is focus.

**Comment by technotomahi** [comment] 2016-08-10 04:40
@keithajackson, I have tried your custom server messages  [plunker](http://codepen.io/anon/pen/GoyjPM) it seems not working. 

The error message is displaying no matter what I set to the loginFailed variable in the javascript.

**Comment by technotomahi** [comment] 2016-08-10 05:28
Hi, 

I was trying to implement a custom server side error message display at md-input containetr. The [plunker](http://plnkr.co/edit/4lLDijmmjfzN9PSbzpPK?p=preview) is here. 

Here I can set the error class at the md-container so the level and the red botton border is highlighted. But I am unable to show the error message for the same. 

Can anyone have a look . what I am doing wrong.

**Comment by nuragic** [comment] 2016-09-27 10:38
Still broken, I'm using `v1.1.1`.

The problem seems to be the the `ng-animate` class not being applied properly to the message element (only applied to the parent `ng-messages` not to the child `ng-message`). So this rule is hiding the error message because he doesn't have the `ng-animate` class.

```css
md-input-container .md-input-message-animation:not(.ng-animate) {
    opacity: 0;
    margin-top: -100px;
}
```

Anyone working on it? Thanks!

**Comment by lookapanda** [comment] 2016-10-03 19:05
I can't really believe this issue is not fixed yet. It has been reported 10 months ago. 
I'm also having it.
+1

**Comment by mcianc** [comment] 2016-10-05 14:00
+1

**Comment by vlio20** [comment] 2016-10-06 05:10
@ThomasBurleson, this issue should be reopened as it still breaks in v1. 1.1 as @nuragic pointed.

**Comment by jammed343** [comment] 2016-10-15 05:50
The animations are completely broken and unusable.
If you enter an input and then remove it. Then enter it again, error messages disappear.

Either animations should be disabled or fixed, currently this is very unstable

**Comment by ThomasBurleson** [comment] 2016-10-15 12:14
Based on community feedback, reopening.
@clshortfuse  - may be related to other animation/ngMessage fixes.

**Comment by kuhnroyal** [comment] 2016-10-15 12:51
I adapted the provided sample to 1.1.1 and angular 1.5.5 and it seems to be working. Maybe a problem with older ngMessage versions?

http://codepen.io/kuhnroyal/pen/LRBojo

**Comment by ThomasBurleson** [comment] 2016-10-15 12:55
@kuhnroyal - Thanks for the update. We will confirm and close.

**Comment by nuragic** [comment] 2016-10-17 16:27
@ThomasBurleson @clshortfuse 

Please take a look at http://codepen.io/nuragic/pen/QKVYBg?editors=1010 to see the unexpected behavior. Error messages are there but they are not visible... 😕

**Comment by clshortfuse** [comment] 2016-10-17 16:41
@nuragic Thanks for this! The issue seems to stem from an issue related to the element's lifecycle and calling of ngAnimate. This has been resolved in a WIP PR related to CSS density. I will try to see if I can cherrypick portions of that PR to quickly this issue.

**Comment by nuragic** [comment] 2016-10-17 16:57
@clshortfuse You're welcome! Glad to see this issue is being address and we're in the right direction :) Let me know if there's anything more I can do to help. Thanks!

**Comment by kuhnroyal** [comment] 2016-10-17 17:17
Good find, the original issue doesn't occure anymore, as far as I can tell tho.

**Comment by topherfangio** [comment] 2016-10-24 22:02
@nuragic I believe your issue is related to https://github.com/angular/material/pull/9473 which should hopefully be merged soon.

Additionally, I just pushed a PR related to ng-messages with Autocomplete, but it could be affecting standard inputs too: https://github.com/angular/material/pull/9909

@vlio20 @jammed343 @mcianc @lookapanda If your issue doesn't relate to one of these, could you please provide an updated Codepen which shows the issue so we can investigate?

I'm also adding myself to the thread so I can keep up with it better.

**Comment by vlio20** [comment] 2016-10-25 14:03
@topherfangio , seems like this is solved. Thanks a lot

**Comment by kadoshms** [comment] 2016-11-14 16:55
There's a workaround for this issue:

By adding a `ng-show="Form.fieldName.$touched"`  to the `ng-messages` directive. 
That actually made the validation work as expected, including the animation.

**Comment by alexrojaslara** [comment] 2016-11-22 17:21
+1

**Comment by avilao** [comment] 2017-01-19 12:07
+1

**Comment by mikila85** [comment] 2017-03-02 13:28
?????

**Comment by rafaeldev** [comment] 2017-03-09 18:37
Hi guys!

I have another scenario where the message doesn't works...
I need set some attributes (ng-pattern and required) on input after input render.

In debbuging I saw that line on code:
https://github.com/angular/material/blob/e06284aa4745dd7323a872a0a9290fd026747e30/src/components/input/input.js#L1020

and don't know why the md-input-container haven't the class "md-input-invalid".

That behavior is expected?

An exemple:
http://codepen.io/rafaeldev/pen/wJgaZV?editors=1010

**Comment by topherfangio** [comment] 2017-03-20 22:17
@mikila85 Are you still having issues? If so, please provide a Codepen so that we can investigate.

@rafaeldev It looks like the `md-input-invalid` class is not properly being applied to the parent `<md-input-container>`. I will look into this. In the meantime, here is a workaround that you can use to manually set the class: http://codepen.io/topherfangio/pen/PpQBvb?editors=1000

**Comment by offwork** [comment] 2017-03-21 16:43
don't get this warning when you remove the 

> md-require-match

 attribute in the **$mdAtuocomplete**

**Comment by topherfangio** [comment] 2017-03-21 17:39
@offwork What warning? Can you elaborate?

**Comment by rafaeldev** [comment] 2017-03-21 17:57
@topherfangio Thanks for reply e for help me!

**Comment by jellyfush** [comment] 2017-03-21 23:39
I have a similar problem with firefox 52.0 on ubuntu, Chrome is fine. See http://codepen.io/anon/pen/vxRpJK the error shows then disappears.

**Comment by bruno-serfe** [comment] 2017-07-05 17:46
Is this still an issue? there's no fix for this?

**Comment by jellyfush** [comment] 2017-07-10 23:46
Its a bit of a pain but I found it best just to not use ng-message for server side errors in this case, I just use a loop/switch to display them styled the same way... similar to the way the document say's to display info underneath

**Comment by bruno-serfe** [comment] 2017-07-11 12:37
Do you have an example of that? The problem is that I'm using ng-message, I don't understand why those messages work on the login example and not over the rest of the pages.. 

Thanks

**Comment by jellyfush** [comment] 2017-07-11 22:26
@bruno-serfe Yea its kind of frustrating. Seems like some weird thing with the animation setting the opacity to 0 when finishing, could actually be an angular bug but haven’t looked into it enough.

If you wanted to do something similar to the ng-message you could reference this https://codepen.io/anon/pen/dRwXQE you could put a switch in there to render the message the way you want. Seems like a bit of an ugly hack, but works form me.

Of course if you were getting errors back from the server I would remove the ng-if and just have it print the returned error. Can be used in combination with ng-message but it looks as though only one can be active at a time otherwise they sit on top of each other

**Closed** 2017-07-18 16:45 UTC
Labels: has: Pull Request, P4 - Reported By or General PRs/Errors or Edge Cases

**Comment by beany-vu** [comment] 2017-11-18 02:50
I also faced the issue. If I set the form's name with dash character "-", then it didn't show the error message. However, when I changed to camel case, it's okay.

**Comment by DmitryRogov** [comment] 2017-12-01 20:10
I had a similar problem. As it turned out, one form was inside another one. Check your page layout

**Comment by Talhah** [comment] 2018-04-03 16:27
I have finally found a solution that works with the help of @topherfangio 

https://codepen.io/talhahm/pen/EEpyqv
