### ISSUE TITLE
Sidenav animation broken with Angular 1.4.4

### ISSUE THREAD

**Issue by rscottfree** [angular/material#4246] opened 2015-08-19 21:42 UTC
The sidenav animated fine with Angular 1.4.3, but is broken with Angular 1.4.4. I would put a codepen here but clicking on the demo codepen button brings up a broken codepen--not sure what is going on there.

I'm using version 0.10.1-rc5 of angular-material.

**Comment by ThomasBurleson** [comment] 2015-08-19 22:33
We are aware of this and are researching the issue.

**Comment by topherfangio** [comment] 2015-08-19 23:49
Duplicate of #4152.

**Comment by lscordilis** [comment] 2015-08-26 21:50
+1 This started happening to me as well after I updated Angular in my projects.

**Comment by rdesimone** [comment] 2015-08-30 08:34
Same here, unfortunately the latest version of the new router can not be used. It requires 1.4.4. IMO there should be a better coordination between the various teams

**Comment by ThomasBurleson** [comment] 2015-08-30 13:11
@rdesimone - The Angular 1, Angular 2, Angular Dart, and Angular Material teams support each other **and** communicate daily. 

The reality is that we are all moving **very** fast to deliver amazing software to the community. And while we remain steadfast and focused on quality and excellence, we are admittedly working with very complex systems and inventing new tools and solutions as we go... 

Even with our extensive Karma and Protractor tests, our CI server, and our build processes, the teams may still publish Releases that manifest some issues or incompatibilities [across browsers, devices, and versions].  

This is where you and the community are so important. Your testing and feedback helps to alert and guide us to deliver quality improvements and great software. Thank you for all your help and input.

**Closed** 2015-08-30 13:11 UTC
Labels: hotlist: angular-issue, hotlist: animations

**Comment by rdesimone** [comment] 2015-08-30 14:36
@ThomasBurleson nobody doubts that you are providing great software. As the AM team is a core team of the Angular project (as far as I understood from the notes of Brad Green), it should be made sure that the simplest AM app does not break with a new Angular release. Everybody accepts that there will be bugs and not everything can be tested.Thanks!

**Comment by lscordilis** [comment] 2015-08-31 14:19
@ThomasBurleson We all understand the challenges you and the Angular teams face in providing these great tools that all depend on one another. We're just here to help :)
