### ISSUE TITLE
feat(contact-chips): add support for ng-change

### ISSUE THREAD

**Issue by izeau** [angular/material#3857] opened 2015-07-22 14:52 UTC
Hi guys, [here's a codepen](http://codepen.io/anon/pen/OVowEo?editors=101) showing the issue.

Basically, to trigger a function when the `<md-contact-chips>` updates, we (seemingly) have to use `$scope.$watch`, which I'm trying to avoid thorough the codebase. Can we have it working (or a similar attribute such as `md-contact-change`)?

**Comment by rgolea** [comment] 2015-07-22 19:51
Try with `$scope.$watchCollection` or if not pass in a 3rd parameter as `true`:
```
$scope.$watchCollection('whatever', fn)
//or
$scope.$watch('whatever', fn, true);
```

**Comment by izeau** [comment] 2015-07-23 07:28
Thanks for the heads up! But I’d really like it as an attribute.

**Comment by rgolea** [comment] 2015-07-23 07:59
Well... You can always do a directive. The thing is that the actual `ng-change` is based on the view change:
(Code from source)
```
var ngChangeDirective = valueFn({
  restrict: 'A',
  require: 'ngModel',
  link: function(scope, element, attr, ctrl) {
    ctrl.$viewChangeListeners.push(function() {
      scope.$eval(attr.ngChange);
    });
  }
});
```
You can always do something like this:
```
.directive('hardChange', function(){
    return {
        restrict: A,
        require: 'ngModel',
        link: function(scope, elem, attr, ctrl){
            scope.$watchCollection(function(){
                 return ctrl;
            }, function(newVal, oldVal){
              if(newVal === oldVal) return;
              scope.$eval(attr.hardChange)
            });
       }
    };
});

**Comment by izeau** [comment] 2015-07-24 11:03
Yeah sure but that looks to me like a feature Material could offer by itself!

**Comment by rgolea** [comment] 2015-07-24 11:10
Do a fork and do a PR yourself if you want...

**Comment by typotter** [comment] 2015-08-10 04:01
What we need to do here, is update the $viewValue of the ngModelCtrl on md-chips when the collection changes. This should not be too hard, and should make ng-change work for you.

**Comment by beazergood** [comment] 2016-02-29 14:35
Hi peeps. I'm a bit of a noob when it comes to Github and how all this works.  I've read this as it's not released yet and 1.1.0 is the target release for this functionality?... That correct?

**Comment by aleccool213** [comment] 2016-04-28 18:15
any chance of this ever being done?

**Comment by avilaj** [comment] 2016-10-05 16:31
Has this been fixed? we need this in order to subscribe to ngModel $viewChangeListeners.

**Comment by jmwilkinson** [comment] 2017-02-08 01:41
Why was this closed? This issue isn't fixed.

**Comment by rhclayto** [comment] 2017-05-29 04:37
This is still an issue.

**Comment by Splaktar** [comment] 2017-11-28 01:28
Reopening this because the original PR was closed (not merged) and there has been a significant number of requests to reopen the issue here and in https://github.com/angular/material/issues/3580.

If someone wants to open a PR with a fix, we'll take a look at it and try to get it merged. Before working on the PR though, please submit an updated CodePen that reproduces this issue with AngularJS `1.6.6` and AngularJS Material `1.1.5`.

**Closed** 2018-03-23 23:57 UTC
Labels: P4: minor, for: external contributor, needs: Pull Request, needs: investigation, severity: inconvenient, type: enhancement
