### ISSUE TITLE
Init of md-menu throws exception when trigger element uses data- prefix for ng-click

### ISSUE THREAD

**Issue by yobacca** [angular/material#6659] opened 2016-01-13 00:04 UTC
I get the following error when the trigger element of a md-menu uses "data-"-prefix for ng-click.

Error: triggerElement is null
init@http://localhost/bower_components/angular-material/angular-material.js:21489:5

I just saw that there was a similar issue for md-menu-item, which has already been fixed: https://github.com/angular/material/issues/3397

I fixed the issue in my local copy of angular-material.js accordingly to Commit dc01149 in line 21488 of angular-material.js as follows:

```javascript
  this.init = function init(setMenuContainer, opts) {
    opts = opts || {};
    menuContainer = setMenuContainer;
    // Default element for ARIA attributes has the ngClick or ngMouseenter expression
    //triggerElement = $element[0].querySelector('[ng-click],[ng-mouseenter]');
    triggerElement = $element[0].querySelector('[ng-click],[ng-mouseenter],[data-ng-click],[data-ng-mouseenter],[x-ng-click],[x-ng-mouseenter]');
```

**Comment by DevVersion** [comment] 2016-04-24 08:29
This is a duplicate of #8080 - Fix is already pending in #8163

**Closed by DevVersion** 2016-04-24 08:29 UTC
Labels: P1 - Broken Renders / Major Use Cases
