### ISSUE TITLE
Feature request "dateTime picker"

### ISSUE THREAD

**Issue by mthomasson** [angular/material#11206] opened 2018-04-03 13:32 UTC
### Feature request:
In material design specifications, there is a time picker, but it is actually not available in the angular material library.
 Some unofficial repositories exist for this, but it would be better to have it part of Angular material, and none of them support a "DateTime picker", that would leave the user chose the date first, and the time afterward.

### What is the expected behavior?
A time picker would be available, and a DateTime picker as well

### What is the current behavior?
Only a datePicker is available

### What is the use-case or motivation for changing an existing behavior?
Need to add a DateTime picker in my app, but does not find any suitable, out of the box tool that follows material's guidelines

### Which versions of AngularJS, Material, OS, and browsers are affected?
Angular 1.x.x
Any browser, any OS

**Comment by Splaktar** [comment] 2018-04-05 06:45
Duplicate of https://github.com/angular/material/issues/5029

**Closed by Splaktar** 2018-04-05 06:45 UTC
Labels: resolution: duplicate
