### ISSUE TITLE
md-dialog + ng-messages

### ISSUE THREAD

**Issue by 0101adm** [angular/material#6516] opened 2016-01-02 03:47 UTC
1.0.1

chrome

ng-messages bumps the width of the dialog when an error shows.

![untitled screencast](https://cloud.githubusercontent.com/assets/5133412/12073129/e552326c-b0c8-11e5-9178-3e7fd72f4ed2.gif)

```
form(	novalidate=''
				name='contactAgentDialogCtrl.form'
				layout='column')

			md-input-container.md-block
				label
					| Email Address

				input(	type='email'
							ng-model='contactAgentDialogCtrl.email'
							ng-required='true'
							name='email')

				ng-messages(for='contactAgentDialogCtrl.form.email.$error'
								role='alert')

					div(ng-messages-include='app/common/ng-messages.html')
```

**Comment by EladBezalel** [comment] 2016-01-02 11:12
This looks like a bug, can you please provide a codepen?

**Comment by 0101adm** [comment] 2016-01-12 00:38
cannot dup.

**Comment by mangrish** [comment] 2016-01-28 05:11
This is definitely happening with ngMaterial 1.0.3 and angular 1.4.9 on both the latest Chrome and Firefox versions. 

This bug is perhaps most notable when a dialog window only contains a form.

The cause seems to be the ```md-input-container``` getting it's sizing from including both the input field and the ngMessages container.  When a user modifies the input control the container will resize itself to adjust for what's inside the ```ng-messages``` container. That's why you see the container change size between initial state, valid state and whatever is the active state in ngMessages (as seen in the gif above). The dialog container is set to flex so there is probably some css that needs to be set when in this mode.

You can make it work by simply removing any ngMessages from the md-input-container.

**Codepen**:http://codepen.io/mangrish/pen/ZQoyXb

**Comment by mangrish** [comment] 2016-01-28 05:35
P.S. @EladBezalel @0101adm Will this be reopened or should i open a new issue?

**Comment by EladBezalel** [comment] 2016-01-28 14:48
If it's a valid codepen I will reopen this issue

**Comment by mangrish** [comment] 2016-01-29 00:10
I should add this was tested on:
**OS:** Mac OS X El Capitan (10.11.3)
**Firefox:** 44.0
**Chrome:** 48.0.2564.97 (64-bit)
**Safari:** 9.0.3 (11601.4.4) 
**Opera:** 34.0.2036.50

Data I entered was:
**title/role:** Cowboy
**start year:** 1999
**end year:** 2009

**Comment by mangrish** [comment] 2016-02-03 07:36
Any idea on a work around for this?

**Comment by EladBezalel** [comment] 2016-02-03 21:35
use md-dialog like this:
``` html
<md-dialog flex="80">
...
</md-dialog>
```

**Comment by ThomasBurleson** [comment] 2016-06-01 23:59
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Closed** 2016-06-02 01:55 UTC
Labels: needs: demo

**Comment by ThomasBurleson** [comment] 2016-06-02 13:28
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
