### ISSUE TITLE
autofocus on md-select search input field

### ISSUE THREAD

**Issue by buzybee83** [angular/material#9669] opened 2016-09-22 13:11 UTC
**Actual Behavior**: 
-   `What is the issue? *` Cannot autofocus the search input field in md-select-header. If navigating the page purely by keyboard, the search field can't be accessed without the click of the mouse. 
-  `What is the expected behavior?` If md-select has md-select-header with search input field, the field should be auto-focused by default or optionally - similarly to Select2/ui-select 

**CodePen** (or steps to reproduce the issue): *
-  No codepen, as it can be seen in the Angular-Material Demo page

**Angular Versions**: *
-  `Angular Version:` 1.5.6
##  -  `Angular Material Version:` 1.1.1

Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
>   Add more lines if needed.

**Comment by mckenzielong** [comment] 2016-09-22 14:44
Possibly related or dupe of #9146.  I did an ugly work around that forces focus on the input here: http://codepen.io/mckenzielong/pen/GqGkZJ

**Comment by npbenjohnson** [comment] 2017-06-12 22:16
This is a larger accessibility issue than just focus on opening the menu. I forked your workaround to make it accessible (and even uglier) https://codepen.io/npbenjohnson/pen/weWzPy?editors=1111

**Comment by Splaktar** [comment] 2018-02-27 21:00
Duplicate of https://github.com/angular/material/issues/9146.

**Closed by Splaktar** 2018-02-27 21:00 UTC
Labels: resolution: duplicate
