### ISSUE TITLE
Hide tooltip after clicking button.

### ISSUE THREAD

**Issue by chriseyhorn** [angular/material#2957] opened 2015-05-22 18:52 UTC
I have md-tooltip on some md-buttons and after clicking the button I want it to cancel in order to get out of the way of some UI that I am showing.  Any advice on the best way to achieve this?

Best Regards,
Chris

**Comment by marcysutton** [comment] 2015-05-22 19:27
This is a duplicate of #1968.

**Closed by marcysutton** 2015-05-22 19:27 UTC
