### ISSUE TITLE
md-menu behavior

### ISSUE THREAD

**Issue by mavillar** [angular/material#7866] opened 2016-04-04 09:51 UTC
Hi,

I have implemented a md-menu within a md-list-item and all seems to works fine but a little problem when clicked second time.

![captura de pantalla 2016-04-04 a las 11 35 28](https://cloud.githubusercontent.com/assets/3111892/14244403/38333482-fa5b-11e5-8119-0ea83a21fa49.png)
![captura de pantalla 2016-04-04 a las 11 35 20](https://cloud.githubusercontent.com/assets/3111892/14244404/38358a48-fa5b-11e5-9d34-c5939c5e43d0.png)
![captura de pantalla 2016-04-04 a las 11 35 09](https://cloud.githubusercontent.com/assets/3111892/14244405/3837ffb2-fa5b-11e5-933f-01f63116ae80.png)

The first time I click on one item, the menu is shown correctly but when clicked another time on the same list-item, the menu is positioned in other place.

How can I solve this?

**Comment by ThomasBurleson** [comment] 2016-04-20 22:55
Closing this issue due to insufficient information. Please resubmit with:

----
Required
----

**Behavior**:
-  What is the issue? * 
-  What is the expected behavior? 

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue :
-  Details: 

**Angular Versions**: *
-  Angular Version: 
-  Angular Material Version: 

**Additional Information**:
-  Browser Type: *
-  Browser Version: *
-  OS: *
-  Stack Traces: 

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

**Closed by ThomasBurleson** 2016-04-20 22:55 UTC
