### ISSUE TITLE
tabs: pagination not updating on scope modification

### ISSUE THREAD

**Issue by whittssg** [angular/material#8667] opened 2016-06-06 13:11 UTC
**Actual behavior**:
-  What is the issue? Md-Tab disappears when using a scope variable in the header label 
-  What is the expected behavior? The tab shouldn't disappear like in prior angular-material versions 

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue : http://plnkr.co/edit/mWETJfdaGE75t1NxVji0?p=preview
-  Details: I am trying to show a scope variable in a tab label header like this:

```
<md-tabs>  md-border-bottom md-dynamic-height>
        <md-tab label="Tab 1 without scope" flex>
                    
        </md-tab>
                
        <md-tab  flex>
                    <md-tab-label>
                      Tab 2 with scope {{field}}
                    </md-tab-label>
                    
        </md-tab>
</md-tabs>
```

In RC4 and other stable releases this works fine but in the latest RC5 release the tab header disappears when the scope variable is updated.

Thanks

**Angular Versions**: *
-  Angular Version: 1.5.3
-  Angular Material Version: 1.1.0 RC5

**Additional Information**:
-  Browser Type: Chrome / IE FireFox
-  Browser Version: Chrome 50 / IE 11 / Latest Forefox
-  OS: Windows 7
-  Stack Traces:

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by graphefruit** [comment] 2016-06-06 13:52
@whittssg Tried it on IE11, FF aswell on Chrome - Saw the error but was fixed after i corrected the syntax error:
```<md-tabs>  md-border-bottom md-dynamic-height> ```
Should like:
```<md-tabs md-border-bottom md-dynamic-height>```

**Comment by whittssg** [comment] 2016-06-06 14:10
Sorry about the syntax error. So i guess something changed between RC4 and RC5 in the way that the tabs widths are calculated? I tried it on 1.0.9 and RC4 and it lets me add more text than was originally there when the tabs were created. Thanks

**Comment by graphefruit** [comment] 2016-06-06 14:18
Without big debugging: 
The problem is, that the Name-Change doesn't trigger the `updatePagination`-Function.
If you resize your window the scope gets the window-resize event and everything works fine again.

Try
```
<md-tabs md-stretch-tabs ..>
```
That will not set a fixed with to the pagination-wrapper (but care, if the name gets to long the ink-bar is not strechted)

**Comment by DevVersion** [comment] 2016-06-06 14:23
The `md-pagination-wrapper` always has a fixed height.

```sss
width: 357px;
```

So, once you enter more text, the width will be exceeded and it will wrap.

![image](https://cloud.githubusercontent.com/assets/4987015/15824691/afc0c966-2c00-11e6-871e-4d651dc617b7.png)


In RC4, we always watched the template by using the `DOMSubtreeModified` event (really not a good way) and triggered an update on change.

```js
    element.on('DOMSubtreeModified', function () {
      ctrl.updatePagination();
      ctrl.updateInkBarStyles();
    });
```

This was removed in RC5 with SHA 77958a173d38aa321d9929dd8071e6ac1ef0c84c, which is now using an MutationObserver instead of listening to that event (bad performance - as said above).

The MutationObserver should probably watch for Content Modification as well.

FYI: @graphefruit just already posted some information here, while I was writing here :)

**Comment by whittssg** [comment] 2016-06-06 18:24
Thanks for the info.. I tried md-stretch-tabs and although it does show the content correctly it wasn't the look that i was going for so i ended up giving my original scope variable more width by adding (NA) to the end then when i bind my stuff to it i replace NA with the scope value which is normally between 0 and 99 so it seems to work well for now. (one of my tab's contents is basically a list and i wanted the list count to show in the tab header.

Thanks again.

**Comment by willramos** [comment] 2016-06-14 21:15
I'm encountering a similar issue.

I notice that `<md-tabs md-stretch-tabs="always">` will solve the problem, in terms of functionality, but it gives a bloated, "mobile look," which might not be... ideal in many cases. 

Changing the window width (or the middle panel-thing, in the example by @whittssg above) will make the missing tab appear, but it's not something we want our users doing.

For me specifically, I have an issue where the rightmost tab intermittently becomes hidden. Similar to @whittssg's issue. What happens is... md-pagination-wrapper will estimate 1 pixel less than what is needed to display my rightmost tab, and therefore hides it. My tabs exist within an md-dialogue, so I wonder if the "shapeshiftiness" of it throws the md-pagination-wrapper size off?

**Closed** 2016-06-20 12:35 UTC
Labels: needs: investigation
