### ISSUE TITLE
md-selected-item-change

### ISSUE THREAD

**Issue by armangevorgyan** [angular/material#7833] opened 2016-04-01 08:38 UTC
when i select item first time then nothing happens. second time item selected. 
i want call function when click one on item in list

**Comment by ThomasBurleson** [comment] 2016-04-20 23:06
Closing this issue due to insufficient information. Please resubmit with:

----
Required
----

**Behavior**:
-  What is the issue? * 
-  What is the expected behavior? 

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue :
-  Details: 

**Angular Versions**: *
-  Angular Version: 
-  Angular Material Version: 

**Additional Information**:
-  Browser Type: *
-  Browser Version: *
-  OS: *
-  Stack Traces: 

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

**Closed by ThomasBurleson** 2016-04-20 23:06 UTC
