### ISSUE TITLE
content: covers other DOM elements

### ISSUE THREAD

**Issue by pengxianggui** [angular/material#10945] opened 2017-10-20 02:15 UTC
I don't know why. I have an ul with some  li, and a md-content ,  I want to show the list as a select with css. But it be covered by md-content, no matter how I set z-index. 

It is worth mentioning that ul and li are all above the md-content， at least in firefox 3D view. As you can see in the picture, the li-3 is above the md-content, but it's covered.

![image](https://user-images.githubusercontent.com/16299169/31802367-6afe5928-b580-11e7-8d02-eb9e9bc33f54.png)

Please give me some advice. ths!

**Comment by Splaktar** [comment] 2018-12-31 03:38
This sounds like it might be the same issue as https://github.com/angular/material/issues/2961, but I can't tell since there are no reproduction steps and this report does not follow the required issue template. I'm going to close this and track this in https://github.com/angular/material/issues/2961.

**Closed by Splaktar** 2018-12-31 03:38 UTC
Labels: needs: demo, needs: more info, resolution: invalid
