### ISSUE TITLE
ngMessages UI jump when used in combo with ng-show

### ISSUE THREAD

**Issue by houmark** [angular/material#5298] opened 2015-10-21 17:59 UTC
Sometimes it's nice to only show an error message **after** a field is touched or submitted. So to do that we have used ng-show on the outer ng-messages element like below:

```
<div ng-messages="ctrl.form.title.$error" ng-show="ctrl.form.title.$touched || ctrl.form.$submitted" role="alert">
```

This works fine, but since some of the recent changes related to "multiple" we started seeing a small "UI jump" when leaving the field and the error message was to be shown (or not due to no errors).

To reproduce:

Add the ng-show condition on a field with ng-messages, focus the field, leave the field. The design will now jump just one pixel or so (only the first time).

Not exactly sure what would be the simplest solution, but I thought I would at least report this so someone else might be able to figure out a simple solution.

**Comment by peio72** [comment] 2015-10-21 21:06
+1

**Comment by chrislambe** [comment] 2015-10-29 17:10
Also being affected by this. Here's the commit and rule that caused the issue:
https://github.com/angular/material/commit/3d0b4181e1b7e58e5a606c9d13b59d97a0ce8b5a#diff-74a081d9d358e41d6c52623c1b29422dR178

@topherfangio, do you remember why this rule was added?

**Comment by ngraef** [comment] 2015-10-30 22:49
@houmark Is your issue fixed by faa8b5b7ed036a5c9adf04ad0fa451fa2876adbd?

**Comment by houmark** [comment] 2015-10-31 02:38
With the specific bottom border yes, but I have another somehow related issue now which makes a larger jump in the area below the the input field only when I have a condition on the ng-messages, which creates a ~24px height below due to the ng-messages first being display:none; due to ng-hide and that changes after the first validation (when blurring the field) — even if the validation is successful.

So it's a part fix for me or something else not directly related to this one but related to ng-messages and recent changes.

I've checked if we have anything special going on in our styling, but it does not look like it, it's pretty basic, but the combo with the ng-show on the ng-messages seems to be the reason for this.

**Comment by houmark** [comment] 2015-10-31 04:02
I created a simple pen (forked from the input demo) where I added the ng-show on the "first name" field and one error message. As you can see, there's a whole lot of jumping going on there. Didn't use to be like that and I find this to be largely disturbing to a smooth UI.

Pen here: http://codepen.io/houmark/pen/zvaWyb/

Also the postal code is jumping around when erroring, but I did not touch that one at all and it acts the same in the demo.

**Comment by ngraef** [comment] 2015-10-31 20:24
The sliding up and down in your demo is fixed on master (by the commit mentioned above). Demo: http://codepen.io/anon/pen/GpGYeb

So as you mentioned, the issue is that `md-input-container` doesn't allocate space for `ng-messages`, so the UI jumps when `ng-messages` is shown after initially being hidden.

This snippet of CSS fixes the issue, but it's very much a workaround, not a solution:
```css
md-input-container [ng-messages].ng-hide {
    display: block !important;
    visibility: hidden;
}
```

**Comment by houmark** [comment] 2015-11-02 19:43
@ngraef Yeah, I had been brewing on something similar, and while it's a workaround, it's not really that bad and has made our forms stable again (read non-jumpy), so thanks for that. Hope to see a more permanent fix soonish :)

**Comment by oste** [comment] 2015-11-06 04:11
here is a demo showing the issue

**Comment by mallowigi** [comment] 2015-11-06 12:09
+1

**Comment by maelfrize** [comment] 2015-11-09 20:43
+1

**Comment by satheesh786** [comment] 2015-11-13 06:04
+1

**Comment by sunnyshah01** [comment] 2015-11-16 11:42
+1

**Closed** 2015-12-09 00:26 UTC
Labels: - Breaking Change, - In Progress, priority: high, ui: CSS
