### ISSUE TITLE
need <md-button style <input type="file"

### ISSUE THREAD

**Issue by alanpurple** [angular/material#3310] opened 2015-06-17 07:00 UTC
I need to file input component and this doesn't fit to material design

Is their any way I can use md-button for file input?

**Comment by jameswyse** [comment] 2015-06-17 07:38
:+1: I needed this recently as well.

Bit of a hack, but you can get it working by hiding the input and proxying the click events to the input. Something like this:

#### HTML:
```html
<input id="fileInput" 
       name="file" 
       type="file" 
       class="ng-hide" 
       multiple>
<md-button id="uploadButton" class="md-raised md-primary">
  Choose Files
</md-button>
```

#### Link Function
```javascript
  link (scope, element, attrs) {
    const input   = element.find('#fileInput');
    const button = element.find('#uploadButton');
    
    if (input.length && button.length) {
      button.click((e) => input.click());
    }
  }
```

**Comment by alanpurple** [comment] 2015-06-17 07:54
@jameswyse 
Thanks, your tip code might suffice

**Comment by marcysutton** [comment] 2015-06-17 20:09
This is a duplicate of https://github.com/angular/material/issues/2151.

**Closed by marcysutton** 2015-06-17 20:09 UTC

**Comment by artemijan** [comment] 2016-01-29 11:54
Actually it wouldn't work on apple devices, triggering click on file input doesn't call "choose file" dialog

**Comment by HetalParmar** [comment] 2016-02-08 11:08
dfgdfg

**Comment by egunsoma** [comment] 2016-02-19 00:12
Another hacked solution, though might be a little cleaner:

**HTML:**
```html
<input id="fileInput" type="file">
<md-button class="md-raised" ng-click="upload()">
  <label>AwesomeButtonName</label>
</md-button>
```
**JS:**
```javascript
app.controller('NiceCtrl', function ( $scope) {
  $scope.upload = function () {
    angular.element(document.querySelector('#fileInput')).click();
  };
};
```

**Comment by leocaseiro** [comment] 2016-02-26 00:26
If you use a ```<label>``` instead of ```<md-button>``` and reference the ```for="input-file-id" to your input[type=file], you don't need to bind your click, save some JS. Work just fine:

```html
<input class="ng-hide" id="input-file-id" multiple type="file" />
<label for="input-file-id" class="md-button md-raised md-primary">Choose Files</label>
```

**Comment by fricks** [comment] 2016-02-26 17:57
@leocaseiro +1

**Comment by alanpurple** [comment] 2016-02-26 17:59
@leocaseiro  Thx, I'll try

**Comment by unnieTron** [comment] 2016-03-07 17:14
@leocaseiro Did you try implementing something to show the selected file in the page

**Comment by leocaseiro** [comment] 2016-03-07 20:33
Hi @unnieTron, yes, I did!

It worked great. You can see also on #2151 some more examples or alternatives...

**Comment by Nextt1** [comment] 2016-03-21 06:43
@leocaseiro  +1

**Comment by randallmeeker** [comment] 2016-06-01 15:13
this was a great solution, but label does not seem to respect `.md-primary` for different themes. for me its always blue (the default theme)

**Comment by leocaseiro** [comment] 2016-06-01 23:55
@randallmeeker if you force with `md-colors` works for you? I'm sorry, I need to investigate a little deeper. 

```html
<input class="ng-hide" id="input-file-id" multiple type="file" />
<label for="input-file-id" class="md-button md-raised md-primary" md-colors="{color: 'primary'}">Choose Files</label>
```

My config is like [this one](https://material.angularjs.org/latest/Theming/03_configuring_a_theme) and is seems working just fine:

```javascript
$mdThemingProvider.theme('default')
    .primaryPalette('indigo', {
         'default': '900'
    })
    .accentPalette('red');
```

**Comment by randallmeeker** [comment] 2016-06-02 13:31
@leocaseiro thanks a bunch. I was unaware of the `md-colors` directive which will help a ton.

**Comment by fme-samuelbirk** [comment] 2016-06-29 11:27
This might have been fixed.
```html
<md-button class='md-raised md-primary' id='upload' multiple='false' ngf-multiple='true' ngf-select='upload($files, $file, $event)' type='file'>
    Upload
  </md-button>
```
seems to work as expected

**Comment by dinusuresh** [comment] 2016-07-06 04:53
@fme-samuelbirk 

You are using [ng-file-upload](https://github.com/danialfarid/ng-file-upload)

**Comment by fme-samuelbirk** [comment] 2016-07-06 10:46
yep

**Comment by simonh1000** [comment] 2016-12-19 14:37
@leocaseiro found this looking for a solution for NG2 and it worked

**Comment by ScottRFrost** [comment] 2017-03-08 19:12
Ran in to this same issue, so I hacked together a quick solution without having to make extra directives / etc..  Basically, render the regular HTML dialog, but with the ugly browse button BEHIND the cute material button.  This is better than hiding the input control all together because you still can see the file name to let the user know which file they picked.

HTML:

     <label class="md-secondary md-raised md-button bring-forward" md-ink-ripple for="xFile">
          <span>Select File</span>
     </label>
     <input type="file" ngf-select ng-model="xFile" name="xFile" id="xFile" class="file-input-hide">

CSS:

     .file-input-hide {
         position: relative;
         left: -6em;
     }
     .bring-forward {
         z-index:10;
     }

**Comment by joergenv** [comment] 2018-08-07 22:29
@leocaseiro Thanks for a great example - but I inherited some code with a md-button tag-directive, with some attributes like 'on-upload', 'on-complete', 'url' and so on. How to use these data?
