### ISSUE TITLE
Auto complete Dropdown not closing in ie 11

### ISSUE THREAD

**Issue by Sriram143** [angular/material#3245] opened 2015-06-12 14:25 UTC

**Comment by epelc** [comment] 2015-06-12 19:14
@Sriram143 What version are you using? Have you tried the latest master?

**Comment by Sriram143** [comment] 2015-06-12 19:30
Yes i am using latest master. still not closing when i set minlenght=0

**Comment by Abrissirba** [comment] 2015-06-12 23:28
I have the same problem on both select and the new menu component in both IE and firefox. I think the problem is related to 6911506712a9ef71ebefbcd63f427e4325d82001 where the scroll lock was updated. 

When I tried the components in the demo page, $window.getComputedStyle(element[0])  returned "" in chrome which works fine. However in both firefox and IE it returns" auto" which makes the substraction with 1 to return NaN. Then the z-index will be set to 99 which will placethe backdrop that listens for clicks and that it will close the dropdown, select or menu  behind the scroll lock element. Because of this the click event on the backdrop will never be triggered and the dropdown will not be closed. I'm not sure why the z-index is hard-coded to 99 if the z-index is NaN. How would one handle when the z-index is set to auto. Is it possible to get the actual z-index in another way?

**Comment by webmandman** [comment] 2015-06-15 19:40
Same problem. And after updating from 0.9.8 to 0.10.0 it did improve a bit.

This screencapture is at 0.9.8
![autocompletedropdownissues](https://cloud.githubusercontent.com/assets/991677/8168902/fadc4746-135a-11e5-8512-1118067ad62c.gif)

And with 0.10.0
![autocompletedropdownissues 0 10 0](https://cloud.githubusercontent.com/assets/991677/8168956/4a99f472-135b-11e5-8ee1-09ed07b68730.gif)

Still problematic. I typed "santa" and it stopped at "san", then I typed "ta" and it stopped at "t". Nasty delays going on here. Then ofcourse the suggestions would disappear.

**Comment by rschmukler** [comment] 2015-06-21 23:40
@webmandman please open a new issue for the performance / delay you were describing. The z-index issue is resolved in a commit to follow shortly.

**Closed** 2015-06-21 23:41 UTC
