### ISSUE TITLE
Disappearing inputs on iPad (safari)

### ISSUE THREAD

**Issue by natcohen** [angular/material#5707] opened 2015-11-12 22:14 UTC
When scrolling on the input demo with an iPad (iOS 9 using safari), the inputs disappear (see attached)

![image](https://cloud.githubusercontent.com/assets/7813574/11132913/b1b6eb6c-8960-11e5-8151-04dfe52f5a78.png)

**Comment by ThomasBurleson** [comment] 2015-11-16 19:45
@natcohen - which version of Angular Material are you reviewing ?

**Comment by topherfangio** [comment] 2015-11-16 19:48
Just tested; it's happening on master. I've seen this before; tracking down the other issue now...

**Comment by topherfangio** [comment] 2015-11-16 19:54
References #2887 and #3446. I believe they are all caused by the same issue which if I remember correctly is something to do with using `translateZ(0)` to force hardware acceleration mixed with the `md-content`s `overflow: scroll`.

One of the other issues mentions using `overflow: initial` to fix it, but that obviously breaks other things. 

That said, I don't recall seeing this on iOS until recently, so perhaps this is a slightly different issue.

**Comment by jpike88** [comment] 2015-12-07 23:57
relevant reading

http://blog.teamtreehouse.com/increase-your-sites-performance-with-hardware-accelerated-css

**Comment by iu3564** [comment] 2016-02-15 06:49
I have same problem, but transform: translate3d(0px, 0px, 0px); resolve the issue

**Comment by ThomasBurleson** [comment] 2016-04-28 20:23
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).

**Closed by ThomasBurleson** 2016-04-28 20:23 UTC
Labels: browser: Safari

**Comment by jeevasusej** [comment] 2018-07-13 12:31
I have used this solution for the whole content of the ipad. but the we are getting issue in the datepicker after applying this.
`transform: translate3d(0px, 0px, 0px); `
