### ISSUE TITLE
Layout: Flex doesn't expand with expressions in class attributes

### ISSUE THREAD

**Issue by jmuharsky** [angular/material#6547] opened 2016-01-05 18:43 UTC
**REPRO STEPS**: (pre-built repro at [Plnkr](http://plnkr.co/edit/LUX1l0wsCNLnWjVDTqqS?p=preview))
1. Create an angular material (1.0.1 at time of this bug) page with a flex layout.
2. On the element where 'flex' is applied, add a class name with an expression, ex:
```html
    <div class="{{ 'foo' }}">My Flex Content</div>
```

**EXPECTED BEHAVIOR**
The element should flex formally.

**ACTUAL BEHAVIOR**
The flex attribute is ignored.

**Comment by david-meza** [comment] 2016-01-09 20:02
That's because you are using an angular expression in an HTML attribute that is not being watched by angular. Have you tried using ng-class instead? It should work as intended (it does in the Plnkr). 
    <div ng-class="{{ 'foo' }}">My Flex Content</div>

**Comment by jmuharsky** [comment] 2016-01-09 20:23
The best-practices recommendation is fair and appreciated.

**Comment by ThomasBurleson** [comment] 2016-06-01 23:59
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Closed** 2016-06-02 01:55 UTC
Labels: P2 - Planned Work / Team PRs, ui: flexbox

**Comment by ThomasBurleson** [comment] 2016-06-02 13:27
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
