### ISSUE TITLE
Site broken in mobile Safari

### ISSUE THREAD

**Issue by mrienstra** [angular/material#2814] opened 2015-05-12 00:21 UTC
https://material.angularjs.org/

Console: `ReferenceError: Can't find variable: jQuery (angular.js:4169)`

iOS 8.3, Safari browser, iPhone 5. Verified using two different devices.

![img_1608](https://cloud.githubusercontent.com/assets/669326/7577851/fda6bff2-f801-11e4-8fa0-3cc38983da58.jpg)

**Comment by ThomasBurleson** [comment] 2015-05-12 01:12
Unable to reproduce.

**Comment by Koslun** [comment] 2015-05-12 01:38
The page looked similar to me on a Chrome v42 on Windows 7. Resolved after reloading the page and stopping something that was eating all the network bandwidth.

So thinking that if both of your devices also had some network bandwidth issues, that might be the cause of this.

**Comment by mrienstra** [comment] 2015-05-12 18:22
I'm still seeing it. Reloading does not help. Issue is independent of network (cellular or wifi). Again, I saw this on my phone and on my colleague's phone (granted they are very similar, both running iOS 8.3).

Here's the stack trace:

![screen shot 2015-05-12 at 11 16 28 am](https://cloud.githubusercontent.com/assets/669326/7594983/1454d72e-f899-11e4-901a-b1ba3e2fa757.png)

**Comment by mrienstra** [comment] 2015-05-12 18:28
I asked my friend to load it on her iPhone 6 Plus, she saw the same broken view (minus the drop shadows)

![img_0671](https://cloud.githubusercontent.com/assets/669326/7595126/f930d514-f899-11e4-9f7a-fe46d833c234.PNG)

**Comment by ThomasBurleson** [comment] 2015-05-12 19:54
Investigating. Thank you.

**Comment by cleever** [comment] 2015-05-12 22:08
Experiencing the same issue in the Windows Phone mobile browser (Internet Explorer - Windows Phone 8.1)

**Comment by ThomasBurleson** [comment] 2015-05-12 22:21
@cleever, @mrienstra  - can you flush your browser cache and retry ?

**Comment by mrienstra** [comment] 2015-05-13 00:02
:thumbsup: Fixed for me!

**Comment by cleever** [comment] 2015-05-13 01:05
Working now! Thank you @mrienstra . :+1: 

Unfortunately, sidebar and animations are very slow.
Some visual glitches are happening too.

**Comment by ThomasBurleson** [comment] 2015-05-13 01:32
@cleever - please report those performance bugs in a separate issue. Close this one.

**Closed by ThomasBurleson** 2015-05-13 01:32 UTC

**Comment by daniel-nagy** [comment] 2015-05-14 00:17
iPhone 4, running IOS 7.1.2, I get the same error `ReferenceError: Can't find variable: jQuery (angular-material.js:1377)`

Further inspection shows this line as the culprit.
```javascript
// On mobile w/out jQuery, we normally intercept clicks. Should we skip that?
isHijackingClicks: (isIos || isAndroid) && !jQuery && !forceSkipClickHijack
```

**Comment by ThomasBurleson** [comment] 2015-05-14 12:33
@daniel-nagy - please flush you browser cache and make sure you are using the latest code from master with these changes: SHA a22f6817fb6e89f7004d:

```js
var hasJQuery =  (typeof window.jQuery !== 'undefined') && (angular.element === window.jQuery);
```

**Comment by daniel-nagy** [comment] 2015-05-14 12:47
This resolves the issue, Thank you.

**Comment by ThomasBurleson** [comment] 2015-05-14 13:01
:+1:
