### ISSUE TITLE
mdChips with mdAutocomplete doesn't work on return

### ISSUE THREAD

**Issue by rgolea** [angular/material#3900] opened 2015-07-26 15:02 UTC
Hey guys! Just found a small bug. Whenever you try selecting an option by pressing return it doesn't work. But if you press tab it does. You can reproduce that on the demos on the select vegetables demo. Thank you!

**Comment by houmark** [comment] 2015-07-27 18:21
This one is truly a usability killer and should be simple to fix?

**Comment by andreialecu** [comment] 2015-08-01 15:09
+1 for this.

Repro here: https://material.angularjs.org/0.10.1-rc5/#/demo/material.components.chips

Go to the contact chips and start typing, then hit down arrow on the keyboard and select something with enter. It's broken with the keyboard, but it works with the mouse.

**Comment by houmark** [comment] 2015-08-01 15:12
If you use tab when having selected one it works as expected. Only hitting enter breaks it.

**Comment by ngraef** [comment] 2015-08-07 16:21
Duplicate of #3833

**Comment by typotter** [comment] 2015-08-10 03:41
I am not able to reproduce this at HEAD.

**Comment by houmark** [comment] 2015-08-10 03:48
@typotter Then it's because you're not testing correctly :) For the Vegetable demo on the AM website, using HEAD, type in "bro" and hit ENTER, and it will show an empty chip. Then try again using TAB or the mouse to select the result. Does not happen if you're **not** filtering in the results and just arrow down and select.

Much more details in #3833

**Comment by typotter** [comment] 2015-08-10 03:54
What browser are you using?
I did the following in Chome:
went to: https://material.angularjs.org/latest/#/demo/material.components.chips
scroll to Vegetable chips demo
clicked the input
Typed "BRO"
Pressed <enter> - nothing happened; no result is selected.
pressed <arrow-down> to selected Broccoli result
pressed <enter> - chip is added.

**Comment by houmark** [comment] 2015-08-10 04:02
1) Your demo link is pointing to latest, not HEAD. This is a recent issue that is happening in HEAD and not in the latest release.

2) I'm using Chrome, but I just re-tested in Safari and Firefox to make sure and it also happens there.

Like it is written in the subject line of this issue report and the other extensively researched issue report, this happens with chips that uses **md-autocomplete**. The demo you need to use is the last one in the list on the below page:
https://material.angularjs.org/HEAD/#/demo/material.components.chips

See attached screenshot.
<img width="1175" alt="screenshot 2015-08-09 23 00 44" src="https://cloud.githubusercontent.com/assets/467330/9159254/8af62c56-3eea-11e5-8c6b-df1aaa2fb1d4.png">

Request to reopen...

**Comment by typotter** [comment] 2015-08-10 04:08
confirmed

**Comment by qjlee** [comment] 2015-08-10 22:38
Sorry, I think I just raised the same issue here as well, https://github.com/angular/material/issues/4087, maybe someone can close it and mark as duplicate? Any quick workaround or timeline for fixing this issue please?

**Comment by houmark** [comment] 2015-08-10 22:40
#3833 has much more details and investigations into the cause of this. I have yet to find time to test out the proposed improvement.

**Comment by typotter** [comment] 2015-08-12 00:08
Dupe of #3475

**Closed by typotter** 2015-08-12 00:08 UTC
Labels: severity: regression, type: bug
