### ISSUE TITLE
after 0.9.0 long lines in md-list-item look squashed 

### ISSUE THREAD

**Issue by david-gang** [angular/material#2747] opened 2015-05-06 06:07 UTC
This issue is opened in continuation of
https://groups.google.com/forum/#!topic/ngmaterial/O5jXE4HMSkg

Long lines in md-list-item looked like squashed together
http://plnkr.co/edit/VrlWj8bvN17hUj8OHO2H?p=preview

There is no space between the lines. You can see the same text outside or inside the md-list-item. Outside it looks much nicer as there is space between the lines.

**Comment by rschmukler** [comment] 2015-05-20 18:49
@david-gang sorry for the delay. In the demo you linked above, I do not see anything not rendering properly? Which text specifically looks wrong? Sorry!

**Comment by david-gang** [comment] 2015-05-21 06:05
hi @rschmukler .
I updated the plunkr. please look again at the line which starts "Brunch this". It looks like there is no space between the lines

**Comment by rschmukler** [comment] 2015-06-28 23:17
Closing as duplicate of #2199

**Closed by rschmukler** 2015-06-28 23:17 UTC
Labels: Demo Needed
