### ISSUE TITLE
element.focus() in $mdSidenav causes page jump

### ISSUE THREAD

**Issue by nolandubeau** [angular/material#1891] opened 2015-03-12 20:25 UTC
Hi,  
I am building an application which has a layout similar to the angular material design site.  At the very top of the page however, is another md-toolbar.  Below the first toolbar is the sidenav and the main content area.

With a layout like this when the sidenav is finished opening, element.focus() is called.  This causes the page to focus to the sidenav toolbar top, and causes the toolbar above the sidenav to be partially visible (since the page has scrolled).  Is it really necessary to have the element.focus() in the updateIsOpen function?  If I comment out element.focus(), the issue is fixed.

if (scope.isOpen) {
  //element.focus();
}

**Comment by marcysutton** [comment] 2015-03-12 21:14
Focus is necessary for accessibility purposes, so that screen reader users are directed into sidenav. Sounds like we may need to do some CSS wrangling to support both use cases. Can you provide a Codepen or Plunker with your markup showing the jump?

**Comment by DavidVaini** [comment] 2015-03-25 14:15
I am also having this issue, I do not want it to snap, is there a way to override this behavior? I do not want the sidenav to "snap" causing the page to jump.

**Comment by DavidVaini** [comment] 2015-03-25 15:39
I can confirm that if you comment out that line it stops the focus, however this isn't a solution for me as modifying angular itself will not work with our deployment strategy (not to mention its bad practice).

**Comment by DavidVaini** [comment] 2015-03-25 15:52
Perhaps a fix like this would work:
```
              var x = window.scrollX, y = window.scrollY;
              elemment.focus();
              window.scrollTo(x, y);
```

**Comment by marcysutton** [comment] 2015-03-25 18:55
Smooth scrolling is something I've done in the past. That makes it so you can still focus an element and while smoothing out the jump.

**Comment by DavidVaini** [comment] 2015-03-25 19:11
Except thats not the desired effect, why force scrolling? could we have it as an optional config property? I think most people would just want the side nav to slide out and thats it.

I would say if people want it to scroll smoothly down, they could just write their own javascript to do it. 

It just seems to go away from being extensible if you force scrolling. You could implement no scrolling/no snapping and then if someone wants to smooth scroll, they could add an event to handle it. Just my 2 cents.

**Comment by marcysutton** [comment] 2015-03-27 23:04
The scrolling would only be added to smooth out `focus`, which is required for the sidenav component. I'm looking into how to make this better while still keeping it accessible for keyboard and screen reader users.

**Comment by DavidVaini** [comment] 2015-03-30 13:13
I guess, I wonder why its required to scroll, to me it would make sense to have two behaviors. One that doesn't scroll but still focuses, and one that focuses and scrolls. Could bet set by a config proerpty on the slidenav.

**Comment by dmackerman** [comment] 2015-03-30 13:15
This is actually causing us issues in our app, because we want to focus inputs when the sidenav opens - and it appears that this is overriding that for us.

**Comment by DavidVaini** [comment] 2015-03-30 13:20
Or at the very least have an option that disables focus entirely, that way for those who want to create their own focus behavior rather than being forced into one way could do that. Just have a warning that if you remove focus it will break screen readers until you implement your own. This would fix every issue, with the caveat that in documentation you would have to warn the end user about the possibility of breaking screen readers temporally.

**Comment by marcysutton** [comment] 2015-03-30 21:38
Ok, this sounds like a good candidate for more options. The `$mdDialog` has a similar configurable property with an accessibility warning in the docs, `focusOnOpen`.

**Comment by DavidVaini** [comment] 2015-03-30 21:55
:+1:

**Comment by marcysutton** [comment] 2015-04-02 00:14
So the issue with scrolling is that the sidenav *could* be inside of a scrolled element, complicating the calculated offset top. I'll keep working on it, but I'm hoping the override introduced in #2108 will be enough of a fix for this issue. Let me know.

**Closed** 2015-04-08 16:43 UTC
Labels: ready

**Comment by williamverdolini** [comment] 2015-07-01 12:51
I'm using the latest version, but It seems to me that this issue is still open...I made a [plunker](http://plnkr.co/d16my8pzOFpEZgNEzeA0) to see the bug. When I open the menù from toggle, the page focus on sidenav and scroll to it. how to prevent this scroll?

**Comment by koshuang** [comment] 2015-07-03 06:34
+1

**Comment by chris-carrington** [comment] 2015-10-17 18:52
Currently the sidenav is position absolute so it's at the top of the page when it comes in. So when it's focused you scroll to the top. Make it position fixed so when the focus happens it's already in view and goes no where. No js overrides required

```
md-sidenav {
  position: fixed;
}
```

**Comment by ThomsC** [comment] 2016-01-21 15:54
override with css doesn't work for me

**Comment by Warzou** [comment] 2016-02-24 05:08
+ 1

**Comment by gambolputty** [comment] 2016-03-06 09:38
+1

**Comment by MaadMax** [comment] 2016-11-17 18:02
It doesn't work if the sidenav has a top css property. In my case I want the sidenav under the navbar and when the sidenav is opened there's a ugly glitch where the window scroll to the top of the sidenav (which is at top:80px to be under the navbar). Have you a trick to fix that ?

**Comment by MaadMax** [comment] 2016-11-17 20:29
+1

**Comment by bamtron5** [comment] 2016-11-20 21:57
```
md-options="'{focus: top}'"
```
Something like that.  I will css this for now.  +1 and thank you.

**Comment by midhunadarvin** [comment] 2017-06-28 16:00
The overide with CSS doesn't work for me. I would like my design to remain as such, i don't want to mess with my CSS. It's just the focus behaviour that i would like to turn off. Can this be implemented?

**Comment by tellyipock** [comment] 2017-12-20 21:31
I'm dealing with the same problem now. Any solutions besides position: fixed; ?

**Comment by Splaktar** [comment] 2019-05-10 16:28
@midhunadarvin @tellyipock please open a new issue with a CodePen reproduction.
