### ISSUE TITLE
mdSelect: options are duplicated if the model value is pre-set

### ISSUE THREAD

**Issue by yboycn** [angular/material#1676] opened 2015-02-26 01:11 UTC
http://codepen.io/anon/pen/YPvzBE

The select has 3 options, apple, orange and mango. However, when I set 'selected' to 'apple', the options I got in the drop down is:
apple
apple
apple
orange
orange
orange
mango
mango
mango

**Comment by ngraef** [comment] 2015-02-26 01:40
This was fixed in 9e0ca4430f9f3add077a21ccb5a963e48a7f7d83.

**Comment by rschmukler** [comment] 2015-02-26 14:05
Indeed, it was fixed. Closing.

**Closed by rschmukler** 2015-02-26 14:05 UTC

**Comment by leeyeh** [comment] 2015-02-27 12:13
Thanks for the fix. However, it still shows the placeholder text when the model value is preset.

see: http://codepen.io/anon/pen/OPEjmd

I can file a new issue if preferable.

**Comment by leeyeh** [comment] 2015-02-27 13:21
Duplicate of #1699. Sorry.
