### ISSUE TITLE
SideNav with overlay force scroll content to top

### ISSUE THREAD

**Issue by OneMuppet** [angular/material#8020] opened 2016-04-13 15:05 UTC
Here is a video displaying an issue where opening the side nav with an overlay will force the content to scroll to top. The side nav without the overlay works fine.

https://dl.dropboxusercontent.com/u/8318643/AngularMaterialDesignBug%20-%20sidenav%20with%20overlay.mov

**Comment by DevVersion** [comment] 2016-04-13 19:17
@OneMuppet This is a duplicate of #5850 - A PR was already pending but it is now outdated and needs some work.

**Closed by DevVersion** 2016-04-13 19:17 UTC
