### ISSUE TITLE
md-toolbar with icon button and mdSideNav - icon click is active when it shouldnt

### ISSUE THREAD

**Issue by KalpanaAr** [angular/material#6993] opened 2016-02-02 23:46 UTC
I have an icon button for menu on toolbar. When I click on the menu icon, it will be overshadowed by left sidenav and when I close the sidenav, the icon button appears clicked like shown below. Can someone tell me how to over
![menu icon](https://cloud.githubusercontent.com/assets/8092075/12768375/d7ba4a16-c9d4-11e5-9aa0-e4d110f337b6.PNG)
![after clicking on icon menu](https://cloud.githubusercontent.com/assets/8092075/12768380/dfa54ee2-c9d4-11e5-8f18-d87184acbdd7.PNG)
![closing side nav](https://cloud.githubusercontent.com/assets/8092075/12768381/dfab0116-c9d4-11e5-8c24-a37d6680e4d5.PNG)

come this issue?

**Comment by DevVersion** [comment] 2016-02-03 12:40
@KalpanaAr Second duplicated issue of #5563 and also a duplicate of your created issue #6994. Please close both issues (#6994 and this one)

**Comment by ThomasBurleson** [comment] 2016-02-04 13:19
Duplicate.

**Closed by ThomasBurleson** 2016-02-04 13:19 UTC
