### ISSUE TITLE
ng-disabled on md-icon in md-list-item does not work

### ISSUE THREAD

**Issue by shalabhaggarwal** [angular/material#3356] opened 2015-06-19 06:07 UTC
When ng-disabled is applied on md-icon acting as a secondary on md-list-item, it does not have any effect on the dynamically generated button which still fires.

Here is a codepen: http://codepen.io/anon/pen/bdoqLb

**Comment by mukilane** [comment] 2015-06-19 06:32
Duplicate of #3176 
Pls close.

**Comment by shalabhaggarwal** [comment] 2015-06-19 06:38
I dont think #3176 covers the case for ng-disabled.

**Comment by topherfangio** [comment] 2015-11-03 18:21
Appears to still be an issue in 1.0.0-rc2: http://codepen.io/topherfangio/pen/EVpeBV

Prioritizing for RC4 (don't think we can get it into RC3).

**Comment by topherfangio** [comment] 2015-11-23 17:24
This has a PR waiting, but it looks like I need to rebase it before we merge. Will definitely get this merged into RC6.

**Closed** 2015-11-25 09:05 UTC
Labels: - In Progress, needs: merge, priority: high
