### ISSUE TITLE
miss lib on 0.9.3 'goog'

### ISSUE THREAD

**Issue by redyyu** [angular/material#2860] opened 2015-05-15 04:14 UTC
It's in angular-material.js

![screen shot 2015-05-15 at 12 04 58 pm](https://cloud.githubusercontent.com/assets/724821/7646803/46b107a6-fafb-11e4-8426-8f34a444ea99.png)

![screen shot 2015-05-15 at 12 05 22 pm](https://cloud.githubusercontent.com/assets/724821/7646806/534de18c-fafb-11e4-8ab7-8295269c7339.png)

**Comment by YogurtShen** [comment] 2015-05-15 06:26
got the same problem
I removed line7~line43
`
goog.provide('ng.ngMaterial');
goog.require('ng.material.components.autocomplete');
goog.require('ng.material.components.backdrop');
goog.require('ng.material.components.bottomSheet');
goog.require('ng.material.components.button');
goog.require('ng.material.components.card');
goog.require('ng.material.components.checkbox');
goog.require('ng.material.components.chips');
goog.require('ng.material.components.content');
goog.require('ng.material.components.dialog');
goog.require('ng.material.components.divider');
goog.require('ng.material.components.gridList');
goog.require('ng.material.components.icon');
goog.require('ng.material.components.input');
goog.require('ng.material.components.list');
goog.require('ng.material.components.progressCircular');
goog.require('ng.material.components.progressLinear');
goog.require('ng.material.components.radioButton');
goog.require('ng.material.components.select');
goog.require('ng.material.components.sidenav');
goog.require('ng.material.components.slider');
goog.require('ng.material.components.sticky');
goog.require('ng.material.components.subheader');
goog.require('ng.material.components.swipe');
goog.require('ng.material.components.switch');
goog.require('ng.material.components.tabs');
goog.require('ng.material.components.toast');
goog.require('ng.material.components.toolbar');
goog.require('ng.material.components.tooltip');
goog.require('ng.material.components.whiteframe');
goog.require('ng.material.core');
goog.require('ng.material.core.gestures');
goog.require('ng.material.core.theming');
goog.require('ng.material.core.theming.palette');
goog.require('ng.ng');
goog.require('ng.ngAnimate');
goog.require('ng.ngAria');
`
and the last line 
`ng.ngMaterial = angular.module("ngMaterial");`

which looks working fine then
Is that correct?

**Comment by yarl** [comment] 2015-05-15 09:09
Duplicate of #2858

**Closed** 2015-05-15 12:30 UTC

**Comment by ThomasBurleson** [comment] 2015-05-15 13:36
We have updated our release script(s) and release version 0.9.4 with fixes to our deployed files.
Please see the [ChangeLog](https://github.com/angular/bower-material/blob/master/CHANGELOG.md) for details.

**Comment by ThomasBurleson** [comment] 2015-05-15 13:57
@everyone - Check out the amazing work that @robertmesserle did with our [Release Script](https://github.com/angular/material/blob/master/release.js)

> This will give you a hint of all the steps and complexity we address in order to release great, quality versions of Angular Material.
