### ISSUE TITLE
Datepicker on Firefox occasionally renders oddly on close

### ISSUE THREAD

**Issue by joereynolds** [angular/material#9265] opened 2016-08-09 09:28 UTC
**Actual Behavior**:
 -  `What is the issue? * `On Firefox (48 and 38) if you highlight some text on the calendar and then select a date, it will render the body of the calendar on to the page itself.
 -  `What is the expected behaviour?` I would expect the calendar to just select that date, not select the date and render on to the page.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
 -  `Details:` Click the caret to open the calendar. Highlight some text within the calendar. Select a date. The calendar should have rendered itself onto the page. It will only disappear when you re-open the calendar.

**Angular Versions**: *
 -  `Angular Version:` 1.5.6
 -  `Angular Material Version:` 1.1.0-rc-5 and the latest source

**Additional Information**:
 -  `Browser Type: *` Firefox
 -  `Browser Version: *` 38 and 48
 -  `OS: *` Linux (mint)

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by crisbeto** [comment] 2016-08-12 14:35
I couldn't reproduce this on Firefox 48 on Windows 10 from the demos. Can you provide some more info or a demo?

**Comment by joereynolds** [comment] 2016-08-12 15:44
Here's a gif of me clicking on and off of the calendar, I realise this isn't much but hope it helps!

![calendar](https://cloud.githubusercontent.com/assets/9536682/17628154/ee1e67c4-60ab-11e6-8175-0795e91eea15.gif)

**Comment by crisbeto** [comment] 2016-08-12 16:33
Hmm, that seems like it could be related to the OS or even the graphics card. I'll try to set up a VM to reproduce it.

**Comment by lmadams** [comment] 2016-08-17 12:34
I have the same error on LinuxMint 17.3 and Windows 7. (Firefox47.0)
But in Google Chrome working normally.

**Comment by crisbeto** [comment] 2016-08-17 13:24
I wasn't able to reproduce it on the following VM setups, with [the current demo from master](https://material.angularjs.org/HEAD/demo/datepicker):
* Linux Mint 18 with Firefox 47.
* Windows 7 with Firefox 48.
* Windows 10 with Firefox 48.

I'll close the issue since this doesn't look like something related to the browser or Material. It can always be reopened if somebody has a demo where this can be reproduced.

**Closed by crisbeto** 2016-08-17 13:24 UTC
Labels: needs: demo
