### ISSUE TITLE
[md-chips] - ng-repat only working after filter

### ISSUE THREAD

**Issue by eloyleonardo** [angular/material#5626] opened 2015-11-09 11:12 UTC
When i use a ng-repeat with a md-chip it doesn't draw any components until i filter the collection.
[here is a code pen with the issue] (http://codepen.io/eloyleonardo/pen/gaBZjw)

**Comment by rwillmer** [comment] 2015-12-07 13:06
Duplicate of, or related to, #2829

**Comment by topherfangio** [comment] 2016-01-06 19:28
Closing in favor of #5709.

**Closed by topherfangio** 2016-01-06 19:28 UTC
