### ISSUE TITLE
datepicker misalignment

### ISSUE THREAD

**Issue by JesusPlz** [angular/material#10374] opened 2017-02-06 17:05 UTC
**Actual Behavior**:
 -  `What is the issue? *`
When you open a date picker, the focus is not on the current month, but on a random future month depending on the position of date picker within a page. It seems like the focus of date picker is determined by the distance to the top of a page. For example, if date picker is positioned somewhere in the middle of a page, when I open date picker on Feb 6, 2017, the focus is on Aug, 2017. If I move the position of date picker upward within the page, the focus moves up as well, i.e. it focuses on July or June depending on how far you move it up. Eventually, if I move date picker to the very top of the page, the focus correctly lands on Feb, 2017. 
 -  `What is the expected behavior?`
I expect the focused month to be the current month instead of a random month as a result of the position of date picker within a web page. 

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
You can replicate the issue using the last two date pickers in the second column below. https://material.angularjs.org/1.1.0/demo/datepicker
 -  `Details:`
![image](https://cloud.githubusercontent.com/assets/7959107/22657373/433800aa-ec64-11e6-97cb-c1ccd5d7fe2c.png)

**Angular Versions**: *
 -  `Angular Version: 1.5.8`
 -  `Angular Material Version: 1.1.3`

**Additional Information**:
 -  `Browser Type: Chrome`
 -  `Browser Version: 56.0.2924.87`
 -  `OS: Windows 7`
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by rhinoceraptor** [comment] 2017-02-09 22:20
This is a duplicate of #10144.

**Comment by sdesmond** [comment] 2017-04-07 20:55
and #9952

**Comment by adickson311** [comment] 2017-06-09 03:08
I believe this is fixed in 1.1.4.

**Comment by Splaktar** [comment] 2018-01-11 09:10
Duplicate. Fixed in 1.1.5.

**Closed by Splaktar** 2018-01-11 09:10 UTC
