### ISSUE TITLE
md-datepicker inside mdDialog displays way over the input location

### ISSUE THREAD

**Issue by FabVillegas** [angular/material#5551] opened 2015-11-04 17:14 UTC
![image](https://cloud.githubusercontent.com/assets/7811470/10945873/0fa3f3c8-82e5-11e5-9f9a-e7fd695fec85.png)

If I open the dialog and open the datepicker, everything works fine.

![image](https://cloud.githubusercontent.com/assets/7811470/10945893/27488e6c-82e5-11e5-9b3c-cf921d2319b3.png)

If I scroll down, the datepicker starts to move away

![image](https://cloud.githubusercontent.com/assets/7811470/10945910/38261e20-82e5-11e5-97cd-e1032ac1a378.png)

**Comment by DevVersion** [comment] 2015-11-04 17:50
Normally scrolling shouldn't be possible due an opened dialog.

http://codepen.io/DevVersion/pen/RWYrVR

**Comment by FabVillegas** [comment] 2015-11-04 18:24
I dont mean scrolling the dialog. If you scroll the content behind the custom dialog, the datepicker moves.

Ill provide a codepen whenever I have a chance. Busy day. :cry:

**Comment by PawelOwczarekFalcon** [comment] 2015-11-05 15:37
+1 i have the same bug :(

**Comment by DevVersion** [comment] 2015-11-05 15:43
It would be great, if someone of you guys, with the problem, can provide a codepen :+1:

**Comment by FabVillegas** [comment] 2015-11-13 06:06
> It would be great, if someone, with the same problems, provide a codepen 

Sorry it took so long...

> Perhaps you can provide a codepen too?

Using your own codepen friend

Everything is fine
![image](https://cloud.githubusercontent.com/assets/7811470/11139841/cea61804-8999-11e5-9344-bfb2e25b7c62.png)


If you open it

![image](https://cloud.githubusercontent.com/assets/7811470/11139851/effbb4aa-8999-11e5-95b1-a0e04c61749c.png)

The datepicker is displaced...

I insert another button in the text and open the dialog at a lower view position

![image](https://cloud.githubusercontent.com/assets/7811470/11139889/46d15b90-899a-11e5-91db-00ae2a2f98b8.png)


The datepicker is further displaced
![image](https://cloud.githubusercontent.com/assets/7811470/11139892/4ee0ba60-899a-11e5-87f2-e64d0810b173.png)

**Comment by FabVillegas** [comment] 2015-11-13 06:17
The whole problem, and this is my guess, is that the whiteframe of the datepicker goes inside the body, not the dialog mask, so the property top counts from the top of the body

**Comment by jelbourn** [comment] 2015-11-13 17:24
Dupe of #5501

**Closed by jelbourn** 2015-11-13 17:24 UTC
