### ISSUE TITLE
Label rendering on IE11 create horizontal scroll bar with 1.1.0-rc2

### ISSUE THREAD

**Issue by peio72** [angular/material#7930] opened 2016-04-07 16:25 UTC
The CSS rule in angular-material.css line 2307 create horizontal scroll bar to appear when a label is present.

Viewable on the input demo page too.

Please help.

**Comment by DevVersion** [comment] 2016-04-07 17:42
@peio72 Thank's for the information you provided, but line numbers from the distributed file are not really helping. 

It would be better, to copy / paste the wrong CSS rule and share it here.

Additionally, I'm not seeing that issue on IE11? Can you provide more information? 
- On which Input in the Demo?
- Is it using Floating Label

**Comment by peio72** [comment] 2016-04-07 19:22
Here is the css rule:

md-input-container.md-icon-left.md-input-focused > label:not(.md-no-float):not(._md-container-ignore), md-input-container.md-icon-left.md-input-focused > label .md-placeholder, md-input-container.md-icon-left.md-input-has-placeholder > label:not(.md-no-float):not(._md-container-ignore), md-input-container.md-icon-left.md-input-has-placeholder > label .md-placeholder, md-input-container.md-icon-left.md-input-has-value > label:not(.md-no-float):not(._md-container-ignore), md-input-container.md-icon-left.md-input-has-value > label .md-placeholder, md-input-container.md-icon-right.md-input-focused > label:not(.md-no-float):not(._md-container-ignore), md-input-container.md-icon-right.md-input-focused > label .md-placeholder, md-input-container.md-icon-right.md-input-has-placeholder > label:not(.md-no-float):not(._md-container-ignore), md-input-container.md-icon-right.md-input-has-placeholder > label .md-placeholder, md-input-container.md-icon-right.md-input-has-value > label:not(.md-no-float):not(._md-container-ignore), md-input-container.md-icon-right.md-input-has-value > label .md-placeholder {
    width: calc((100% - 36px - 18px) / 0.75);
}

It's on input with placeholder when label is displayed.

**Comment by DevVersion** [comment] 2016-04-25 17:36
@crisbeto Can you take a look at your PR and confirm it with this issue.

- #8116

**Comment by DevVersion** [comment] 2016-04-25 17:44
Closing as a duplicate of #7403. A fix is also pending in #8116

**Closed by DevVersion** 2016-04-25 17:44 UTC
Labels: needs: investigation
