### ISSUE TITLE
mdSticky: directive with scope params lose assignment

### ISSUE THREAD

**Issue by Raidri** [angular/material#4979] opened 2015-10-02 10:01 UTC
Hi,

i have a directive which has different kinds of scopes. If the mdSticky component clone the directive, the scope values will be lost. But it is nessecary that the scope state stay active.

That is my directive:

```javascript
subnavigation.directive('subNavigation', function($mdSticky){
	return {
		restrict: 'E',
		replace: true,
		scope: {
			navigate: '&',
			activeComponents: '=',
			versions: '=',
			tariffs: '=',
			settings: '='
		},
		templateUrl: 'Resources/Public/js/app/shared/directives/subnavigation/subnavigation.html',
		link: function (scope, element) {
			$mdSticky(scope, element);
		}
	};
});
```

```html
<md-content>
			<sub-navigation navigate="bootstrap.navigateTo(component)" versions="versions"
			                active-components="activeComponents" tariffs="tariffs" settings="settings"></sub-navigation>
...
</md-content>
```

Do i something wrong or is this a bug?

**Comment by topherfangio** [comment] 2015-10-02 15:29
Could you please provide a very simple [Codepen](http://codepen.io) using the latest versions which shows the issue? It will help us better understand and track down the issue.

Here are the links to the latest versions:

*  Angular Material HEAD
 *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.js
 *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.css 
 *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.js
 *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.css
* AngularJS  Current
 *  Angular 1.3.19 (or greater)
 *  Angular 1.4.6 (or greater).

**Comment by Raidri** [comment] 2015-10-07 10:15
Here a Demo:
http://codepen.io/Raidri/pen/BoWXxq

**Comment by topherfangio** [comment] 2015-10-07 16:58
Awesome, thanks for the demo!

**Comment by mackelito** [comment] 2015-11-09 10:38
Does the $mdSticky service require that the element is wrapped in a <md-content> tag?

**Comment by EladBezalel** [comment] 2015-11-30 18:13
@Raidri I can't understand what are you trying to do?

The demo has nothing to do with your original issue, can you try to explain again what is the issue and provide a proper Codepen?

**Comment by Raidri** [comment] 2015-12-01 07:04
@EladBezalel sorry for that.

I have a directive with a selectbox. if i scroll down and the selectbox is sticky all items are deleted in the selectbox.

Here is a new Version:

http://codepen.io/Raidri/pen/EVqMbQ

**Comment by EladBezalel** [comment] 2015-12-04 16:00
@Raidri the problem is not in `md-select`,
This is not working either with a [regular input](http://codepen.io/EladBezalel/pen/OMJmov) 
I assume it's because of coping ng-model.

Eventually i [made it work](http://codepen.io/EladBezalel/pen/NxWjYB) by defining a container div and compiling the select twice for the original and for the copy element. 
I hope this it's helping!

Closing as it's not our bug. If you find it wrong and can think of how this is ngMaterial issue please write it here and i will re open.

**Comment by viztastic** [comment] 2016-01-01 11:39
Hi, I can confirm I am experiencing the same issue.. I suspect this is a case of the documentation needing to be fleshed out a bit more for $mdSticky ?

**Comment by DevVersion** [comment] 2016-02-13 18:19
As we currently clone the given element in `$mdSticky` we can't copy the directive states / controllers etc. 
That's why in general a clone of the actual directive won't work. In this case we should create the clone ourself using the plain template. More information can be found [here](https://github.com/angular/material/pull/7151/files#diff-4065ad3ed2c87a3cc4f77dc7e0af6c8fR25). #7151, which contains a `scope`fix and a few documentation improvements, will close this issue, because this is actually not a bug, it's just a logical reaction of angular.

**Closed** 2016-02-23 16:52 UTC
Labels: needs: merge, P4 - Reported By or General PRs/Errors or Edge Cases
