### ISSUE TITLE
md-autocomplete: [feature] adding category functionality 

### ISSUE THREAD

**Issue by samithaf** [angular/material#7166] opened 2016-02-16 03:22 UTC
Would be great if can have different categories in auto complete dropdown. Same feature do exist in jQuery auto complete https://jqueryui.com/autocomplete/#categories

E.g. Employee search, search term "an" will gives a list as follows
**Developers**

- Andy
- Andrew

**Testers**

- Annie
- Anne

**Comment by topherfangio** [comment] 2016-04-20 20:07
Duplicate of #7417. Please comment if you disagree and I will reopen.

**Closed by topherfangio** 2016-04-20 20:07 UTC

**Comment by samithaf** [comment] 2016-05-07 08:29
It's pretty much the same feature. @topherfangio #7417 is been marked as deprecated. Does that mean it will never be part of autocomplete Material?

**Comment by topherfangio** [comment] 2016-05-09 15:44
@samithaf It means that it is not likely to be part of the Material 1 Autocomplete unless someone else is willing to work with us and contribute the functionality.
