### ISSUE TITLE
Error in js part of md-sidenav API reference example code

### ISSUE THREAD

**Issue by evan10s** [angular/material#3959] opened 2015-07-30 21:31 UTC
On the [API reference page for the md-sidenav directive](https://material.angularjs.org/latest/#/api/material.components.sidenav/directive/mdSidenav), the controller for the example `MyApp` given (to toggle the sidenav state) seems to be missing a dependency on the `$mdSidenav` service.

When I tried to test this in Chrome (using the code given in the reference, without the `$mdSidenav` dependency specified), I got a `TypeError: $mdSidenav is not a function` message in the console, and the sidenav did not open.  Upon adding the `$mdSidenav` dependency, there was no error message, and the sidenav opened.

It seems like the controller given in the example should have the `$mdSidenav` dependency listed, although maybe not because the [demo sidenav page](https://material.angularjs.org/latest/#/demo/material.components.sidenav) does not have an `$mdSidenav` dependency for its controller.  Is the documentation for this missing something, or am I doing something wrong?

The controller that worked for me:
```javascript
app.controller('MyController', ['$scope', function ($scope, $mdSidenav) {
    $scope.openLeftMenu = function () {
        $mdSidenav('left').toggle();
    };
}]);
```

**Comment by EladBezalel** [comment] 2015-11-17 15:21
I couldn't reproduce it, here's my [Codepen](http://codepen.io/EladBezalel/pen/rOPbgG) that has been copied pasted from the docs.

I close this for not as i don't see any issue, if you still have this problem please provide a codepen and i'll reopen this issue.

**Closed by EladBezalel** 2015-11-17 15:21 UTC
Labels: summit

**Comment by himanshushankhala** [comment] 2016-04-06 05:05
Hi @EladBezalel,
I was able to reproduce it. Please visit following link to download my code. 
https://drive.google.com/open?id=0B-CqiIo597GmTVRtZ3NpcHEyVFE

Hope to get a quick resolution or alternative for the same.
Thank you

**Comment by EladBezalel** [comment] 2016-04-06 05:31
@himanshushankhala please create a codepen

**Comment by royyhlee** [comment] 2018-01-06 01:01
having the same issue

**Comment by Splaktar** [comment] 2019-05-10 15:57
@royyhlee if you are still seeing the issue, please open a new issue with a CodePen reproduction.
