### ISSUE TITLE
tabs: pagination Not Working on IE11

### ISSUE THREAD

**Issue by rk150390** [angular/material#11574] opened 2019-01-03 16:27 UTC
In our application we are using md-tabs. one place we 9 tabs and container doesn't have enough space to display all the tabs at a time. Apart from IE all the browsers adds pagination buttons to navigate and view additional Tabs. The problem in IE. **IE not adding pagination button instead it's trying to display all the tabs only in available space** so all the tabs are **overlapping**.

This issue is not depending on number of api calls or amount of data. happeing all the time in IE

# CodePen and steps to reproduce the issue:
### What is the expected behavior?
Browser should add pagination buttons when there are more number of tabs

### What is the current behavior?
Internet Explorer not adding pagination buttons

### What is the use-case or motivation for changing an existing behavior?
Our business requirement is : Application should work in IE and chrome without any difference

### Which versions of AngularJS, Material, OS, and browsers are affected?

- AngularJS:  1.6.10
- AngularJS Material: 1.1.4
- OS: Windows 10
- Browsers: Internet Explorer

**Comment by Splaktar** [comment] 2019-01-03 19:56
This is fixed in `1.1.11`. Here's an updated [CodePen](https://codepen.io/Splaktar/pen/JwpOZJ). This is a duplicate of https://github.com/angular/material/issues/10406.

You can see all of the fixes related to `md-tabs` in the [CHANGELOG](https://github.com/angular/material/blob/master/CHANGELOG.md#1111-2018-12-20).

**Closed by Splaktar** 2019-01-03 19:56 UTC
Labels: browser: IE, resolution: duplicate
