### ISSUE TITLE
Layout system does not work with Safari.

### ISSUE THREAD

**Issue by mikol** [angular/material#1720] opened 2015-02-28 18:23 UTC
**Commit:** `e2148f1`

**User Agents**

Mozilla/5.0 (iPhone; CPU iPhone OS 10_9_5 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12B411 Safari/600.1.4

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/600.3.18 (KHTML, like Gecko) Version/7.1.3 Safari/537.85.12

**Reproducing**

1. Create a container with three items and layout attributes `layout="row" layout-wrap`.
2. Each item should include the `flex` attribute and a `min-width: 320px` CSS declaration.
3. View the page with Safari on iOS (I used 8.x on both a real and simulated iPhone 6) or OS X.

**Actual Results**

The items do not wrap as expected. See the screenshot below, in which it is clear that the items are still laid out left-to-right rather than stacked top-to-bottom as expected for `layout-wrap` at this viewport width. I suspect this has something to do with the way that `autoprefixer` is configured – i.e., contrary to claims that recent Safari versions (starting with 7 on iOS) implement the final version of the flexbox layout specification, Safari is not 100% compatible and angular-material.css is missing the vendor prefixes required by Safari’s actual implementation.

![2015-02-28-09-42-30](https://cloud.githubusercontent.com/assets/377413/6427196/454e279e-bf2e-11e4-9708-160bfd15b60b.png)

**Expected Results**

The items stack top-to-bottom as expected on Android Chrome.

![2015-02-28-09-49-01](https://cloud.githubusercontent.com/assets/377413/6427256/062d55be-bf31-11e4-8b57-3b8f0c8bf31c.png)

**Comment by mikol** [comment] 2015-03-02 04:15
[CodePen](http://codepen.io/anon/pen/qEKwXX)

**Comment by mikol** [comment] 2015-03-02 19:20
It looks like Safari does not use `min-width` to calculate `flex-basis`. In order to work around this issue, we need to override the `flex-basis` imparted by the `[flex] { flex: 1; }` declaration (which uses the shorthand and assigns `flex-basis: auto` by default). Our declaration must use `!important` or be more specific:

```
.item {
  ...
}

[flex].item {
  -webkit-flex-basis: 318px;
  flex-basis: 318px;
}
```

See this [CodePen](http://codepen.io/anon/pen/yyqLGr).

**Comment by mikol** [comment] 2015-03-02 20:03
I have opened problem ID 20009174 with Apple.

**Comment by milanart** [comment] 2015-03-03 04:32
probably even i'm facing same problem with safari 5.1.7 on windows 7 desktop. the same problem is with android 4.0(using cordova app) also.
even angular-material site is not able to use flexbox on safari.(safari is on left, chrome is on right)
![safari-2](https://cloud.githubusercontent.com/assets/2988727/6456494/d28444b4-c18a-11e4-844c-f78996867dcb.jpg)

this is where i'm implementing.
![safari-1](https://cloud.githubusercontent.com/assets/2988727/6456543/ae8e77fe-c18b-11e4-9d38-59d2a74b736a.jpg)

**Comment by epelc** [comment] 2015-03-03 16:46
@milanart Safari for windows hasn't been updated in years. I don't really think it's a goal to support it anymore.

**Comment by ThomasBurleson** [comment] 2015-03-03 19:52
@rschmukler - Can you look into this today?

**Comment by milanart** [comment] 2015-03-04 03:58
@epelc i know, but its not just about safari 5.1.7. but the problem is same for android 4.3 and older(with cordova).
hardly few windows users use safari. but there are lots of people with android 4.3- devices.

after going through following links i was able to fix most of the flex related problems,
https://css-tricks.com/old-flexbox-and-new-flexbox/
http://stackoverflow.com/questions/17156444/flexbox-layout-does-not-work-in-internet-explorer-10
https://css-tricks.com/using-flexbox/

the problem I found is there is no fix added in css
```
flex-direction: column; // this line is given in material.css

//these 2 lines both should be added to fix for older version
-webkit-box-direction: normal; 
-webkit-box-orient: vertical; 
```
there are many fixes needed for various flex properties, after fixing some of by myself i was able to achieve the following. (uploaded here http://pastebin.com/n7McpS35)
still, i'm not able to solve width for flexbox.
![safari-3](https://cloud.githubusercontent.com/assets/2988727/6477981/d71ef940-c24f-11e4-8b50-ba0465e88240.jpg)

**Comment by ThomasBurleson** [comment] 2015-03-04 04:03
@milanart - This looks very helpful. Thank you.

**Comment by mikol** [comment] 2015-03-04 17:48
I also opened an issue with WebKit: https://bugs.webkit.org/show_bug.cgi?id=136041

**Comment by mikol** [comment] 2015-03-04 17:48
I also updated an issue already opened with WebKit: https://bugs.webkit.org/show_bug.cgi?id=136041

**Comment by epelc** [comment] 2015-03-05 16:05
@milanart Ahh I didn't realize it was also a problem on mobile. Sorry about this.

**Comment by rschmukler** [comment] 2015-04-01 22:33
Angular material targets android 4.4+. 4.2/4.3 only represent ~2% of web traffic according to caniuse. The safari bug is very interesting, but, out of our control. Closing.

**Comment by milanart** [comment] 2015-04-07 14:22
dont take it wrong but, angular material website has used css fallbacks for safari. but not provided the same in material repo. 
I request you to please go though my comments above
.
Also, may i know how much web traffic is from android 4.4?

**Comment by oliverzy** [comment] 2015-04-07 15:45
I think the issue also happened on IOS6 which uses mobile safari 5 because it only support old flex syntax

**Comment by SiddharthaRRamesh** [comment] 2015-04-13 10:18
Using 0.8.3 and it is still not resolved. I am not able to use the `flex="x"` attribute.

**Comment by ThomasBurleson** [comment] 2015-04-13 11:56
@SiddharthaRRamesh - please retry with latest for **/angular/material/#master**

**Comment by SiddharthaRRamesh** [comment] 2015-04-13 12:28
@ThomasBurleson Yeah I did try it, still no success! 
The same markup works fine on chrome but not on IOS 4, 5, 6 and 6+

Here is my markup:

`<div layout="row" layout-align="space-around center" layout-sm="column">
  <div flex="20">
    <img ng-src="" hide-sm hide-md flex="20" />
 </div>
<div flex="40">
  <md-card style="min-height:370px;"></md-card>
</div>
<div flex="40">
  <md-card style="min-height:370px;"></md-card>
</div>
</div>```

**Comment by akashma19** [comment] 2015-06-24 06:59
i am new to angular material i have one problem with responsive.. in mobile also it's showing desktop version of website. i tried every thing.. but when i resize the chrome window it's working but on actuall mobile screen....plzz help

**Comment by lukavent** [comment] 2015-07-15 21:32
Sorry, but I don't see why this task is closed.
iPhone 4s is still relevant.
Wheather for people who are using cordova or for classic browser usage.

Will there be a solution to make the layout system working in iPhone 4s?

**Comment by rschmukler** [comment] 2015-07-20 14:54
@lukavent on a framework level we do not support browsers that old. I will discuss with the team to see whether it is worth compiling against the old standard as a small effort. That being said, I imagine there will be plenty of other issues besides just the layout that we will not support on the older versions. None the less, we can revisit whether it is worth including the old flex standard as an easy win.

**Comment by PierrePaul** [comment] 2015-09-17 13:07
I'm having the same issue on safari 8 and all iPhone versions I got access to. Any idea if it's going to be fixed or if there is a flag/easy fix to apply?

**Comment by akashma19** [comment] 2015-09-17 16:37
add meta tag
<meta name="viewport" content="width=device-width; initail-scale=1" />

**Comment by csvan** [comment] 2015-09-27 19:24
For people still having trouble even on recent versions of Safari, this may be relevant:

https://bugs.webkit.org/show_bug.cgi?id=136041

**Comment by ThomasBurleson** [comment] 2015-10-02 01:57
Currently we use the following SCSS rules: https://github.com/angular/material/blob/master/src/core/services/layout/layout.scss#L185

```scss
  .flex {
    box-sizing: border-box;
  }

  .flex              { flex: 1;  }   // === 1 1 0%
  .flex-grow,         { flex: 1 1 100%;  }
  .flex-initial     { flex: 0 1 auto;  }
  .flex-auto        { flex: 1 1 auto;  }
  .flex-none        { flex: 0 0 auto;  }

```

I think we need to use:

```css

.flex { flex : 1 1 0%; }

```

But the minification is corrupting this...

**Comment by ThomasBurleson** [comment] 2015-10-10 03:48
Closed with SHA 2478f1d2b064d5e06ba57d01b5460fe232f4b270

To expedite issue resolution, please always test with the latest versions:
*  Angular Material HEAD
  *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.js
  *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.css 
  *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.js
  *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.css
* AngularJS Latest Release versions:
  *  Angular 1.3.19 (or greater)
  *  Angular 1.4.6 (or greater).

> If you still have issues please open a new issue with a CodePen demo.

**Comment by stevenmiles** [comment] 2015-10-13 13:22
I was having the same issue as OP with an iPad iOS 9.0.1 with 0.11.3 and md-card  which includes 2478f1d. 2478f1d didn't change the behaviour.

The safari bug that @csvan shared contained a work around for the issue. 

Flexbug: https://github.com/philipwalton/flexbugs#11-min-and-max-size-declarations-are-ignored-when-wrapping-flex-items
Work around Demo: http://codepen.io/philipwalton/pen/RPMqjz

This work around fixed the issue for me.

**Comment by ThomasBurleson** [comment] 2015-10-16 00:50
@stevenmiles - Here is that same demo but shown working with latest ngMaterial in master:

http://codepen.io/ThomasBurleson/pen/bVrmqm

**Closed by ThomasBurleson** 2015-10-16 00:50 UTC
Labels: needs: team discussion, priority: high, ui: flexbox, ui: layout

**Comment by DmsChrisPena** [comment] 2015-10-26 20:33
Is the safari Issue patched in the newest ngAngular. About to update our site with it and want to make sure.

**Comment by brianfeister** [comment] 2017-04-17 14:18
This bug is back with a vengeance in material `1.1.3`. I was hoping it was just my older version of Safari but it's all versions of Safari. This is absolutely critical, and #10516 is open to account for it. I'm still trying to figure out how to fix it, I'll PR when I do but can we escalate this @ThomasBurleson ?

**Comment by stephengardner** [comment] 2017-04-18 14:36
@brianfeister `1.1.2` is okay, though?  I'm having trouble testing due to not owning a Safari enabled device.  Considering downgrading
