### ISSUE TITLE
Massive performance issue using  with IE 11

### ISSUE THREAD

**Issue by hamsaya** [angular/material#7832] opened 2016-04-01 05:30 UTC
The issue is how the angular-material.css file renders the elements on the page. Here is a demo of what I am talking about:

Chrome and firefox work fine.. IE is the issue..

I have updated to the latest of angular material still no luck ... 

http://codepen.io/hamsaya/pen/KzXzEG

This is has a massive impact on the usage of angular material.

**Comment by clshortfuse** [comment] 2016-04-01 05:42
I can't reproduce it. Can you try removing the md-tooltip to see if the performance improves? There are two watchers per md-tooltip which could negatively affect performance.

**Comment by hamsaya** [comment] 2016-04-01 06:58
I tried it in several I.E. Browsers without a luck. Di you try I.E.? I can provide a video demo if needed. 

I will try to remove the tooltips later and see if any performance changes occure...

**Comment by crisbeto** [comment] 2016-04-01 07:45
I tried it out with IE11, but didn't see anything out of order.

**Comment by hamsaya** [comment] 2016-04-01 12:20
Try moving between tabs using IE then try it with Chrome or Firefox... you will see the difference.. Now  you could add more  list item (and my original code is more complex) and then IE will break but chrome will render it just fine.

**Comment by hamsaya** [comment] 2016-04-01 12:32
Here is a youtube video with page reload and tab navigation: https://www.youtube.com/watch?v=C0128pKFrq8

**Comment by crisbeto** [comment] 2016-04-01 12:36
Alright, now I get it. I was clicking around last time. Chrome should defiinitely be faster than IE, but this is waaay too slow.

**Comment by hamsaya** [comment] 2016-04-01 13:32
Just did quick check on watch and digest 
Watch Count: 196
Digest Cycle Length: 5.54

**Comment by crisbeto** [comment] 2016-04-01 13:40
Seems like CSS issue, rather than one with Angular. I believe it could be related to https://github.com/angular/material/issues/7540

**Comment by hamsaya** [comment] 2016-04-01 14:24
@crisbeto that is what I suspected ...

**Comment by sdebionne** [comment] 2016-04-01 14:30
If you switch back to 1.0.5 in your code pen, IE gets back on track. I don't know if 1.1 is far from release but it may be worth to consider a 1.0.7 with just the fix for IE (that is already in 1.1rc1)...

**Comment by crisbeto** [comment] 2016-04-01 16:49
@hamsaya I'm not sure how it was in 1.0.5, but it's much better in 1.1.0-rc2. Here's a fork of your fiddle: http://codepen.io/crisbeto/pen/eZGWVQ. It still has a bit of stutter, but it's better than 1.0.6.

**Comment by hamsaya** [comment] 2016-04-01 16:51
@crisbeto  since 1.1 is in RC I did not try it... 1.0.5 looks good too...

**Comment by hamsaya** [comment] 2016-04-01 17:40
@crisbeto are we going to expect this be completely fixed in 1.1.0?

**Comment by crisbeto** [comment] 2016-04-01 17:51
I can't guarantee anything, but I'll be looking into the stutter that happens the first time you switch tabs. As for the major lag that was being seen in 1.0.6, as I understand it, it made it into the release by accident so it should be removed in 1.1.0.

**Comment by crisbeto** [comment] 2016-04-06 21:03
I'll close this one for now since the main performance issue will be resolved in 1.1. As for that slight frame drop I experienced in the codepen, I couldn't reproduce it locally so it might be caused by something within codepen.

**Closed by crisbeto** 2016-04-06 21:03 UTC
Labels: browser: IE, P1 - Broken Renders / Major Use Cases, type: performance

**Comment by hamsaya** [comment] 2016-04-08 15:18
There is still some performance issue per #4940
