### ISSUE TITLE
RC6 - Datepicker Demo - Typed in dates are marked as invalid

### ISSUE THREAD

**Issue by runethh** [angular/material#6053] opened 2015-12-03 12:33 UTC
How to reproduce: 
1. Select Datepicker in the menu
2. Change one of the dates using the keybord, observe that the date is flagged as "invalid" by the red line underneath

**Comment by jelbourn** [comment] 2016-01-05 22:48
@runethh I can't reproduce this issue. It has probably been fixed. Closing this issue now- we can re-open it if someone can provide a reproduction in CodePen or similar.

**Closed by jelbourn** 2016-01-05 22:48 UTC

**Comment by runethh** [comment] 2016-01-21 15:02
The issue still exists in 1.0.2

How to reproduce:
1. Load datepicker:
![image](https://cloud.githubusercontent.com/assets/16044495/12483858/915dad96-c057-11e5-9f88-cb3fe2408f67.png)

2. Use the mouse cursor to select a valid date in the "With ngMessage" datepicker
![image](https://cloud.githubusercontent.com/assets/16044495/12483912/d6aff516-c057-11e5-92ac-f281184ac742.png)

3. Observe that the date is accepted, indicated by the absence of a warning. Also the line below the date is grey

4. Now select the date using the mouse cursor. Use the keybord to delete the last digit, and type the exact same digit again. Hit enter. Now observe that a warning appears and the line below turns red.

![image](https://cloud.githubusercontent.com/assets/16044495/12483990/4b7e9410-c058-11e5-91e4-d6be65e2fde0.png)

**Comment by jelbourn** [comment] 2016-01-21 16:37
@runethh Which browser are you using? I still cannot reproduce this.

**Comment by runethh** [comment] 2016-01-22 10:09
I can reproduce it on Angular Material version 1.03 on: 

Desktop: 
Chrome - Version 47.0.2526.111 m on Windows 7. 

Mobile: 
Safari version 8, on Iphone 5S
Chrome version 47 on Samsung Galaxy

**Comment by traqutor** [comment] 2016-01-22 11:10
Same problem (chrome 48.0.2564.82 ubuntu) when I use keybord to type in date red error label occurred, when I change days and month the date is correct.


![zrzut ekranu z 2016-01-22 12-05-45](https://cloud.githubusercontent.com/assets/4752790/12509134/a22d7292-c100-11e5-9498-91a89ec394e8.png)

**Comment by runethh** [comment] 2016-02-29 09:52
This issue is still present in 1.0.5.

Traqutors comment hints that the typed in dates are registered with the wrong date format (DD/MM/YYYY vs MM/DD/YYYY)

**Comment by jelbourn** [comment] 2016-03-02 00:41
Then this sounds like a dupe of https://github.com/angular/material/issues/4671
