### ISSUE TITLE
md-select + multiple

### ISSUE THREAD

**Issue by 0101adm** [angular/material#6365] opened 2015-12-17 15:28 UTC
ive set a specific width to an md-select.

selecting enough elements to span beyond the width of the select spills over. 

could see behavior to truncate (and add an ellipses) to long entries.

![untitled screencast](https://cloud.githubusercontent.com/assets/5133412/11873510/25fa3162-a498-11e5-86da-9506c8ca7ae3.gif)

**Comment by jayeshanandani** [comment] 2016-01-05 03:00
Duplicate of #6312

**Closed** 2016-01-12 00:39 UTC
