### ISSUE TITLE
bug(toast): causes scrollbars to hide while animating in

### ISSUE THREAD

**Issue by sebakerckhof** [angular/material#6743] opened 2016-01-19 10:29 UTC
I have a page where the body has scrollbars, when adding an toast to it, the scrollbars are hidden for a moment and then reappear.

Btw, this seems opposite to:
https://github.com/angular/material/issues/4019

**Comment by DevVersion** [comment] 2016-01-19 19:23
Here a demo to reproduce the issue. http://codepen.io/DevVersion/pen/jWaedW

**Comment by dani3l** [comment] 2016-01-27 19:36
hotfix: 
```
.md-toast-animating {
  overflow: initial !important;
}
```

that works for me for now

**Comment by sebakerckhof** [comment] 2016-04-20 21:49
@ThomasBurleson Why deprecated?

**Comment by ThomasBurleson** [comment] 2016-04-28 19:42
This issue is closed as part of our deprecation effort. 
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).

**Closed by ThomasBurleson** 2016-04-28 19:42 UTC
Labels: P4 - Reported By or General PRs/Errors or Edge Cases
