### ISSUE TITLE
Make the standard $mdDialog methods work with HTML in their title/content

### ISSUE THREAD

**Issue by MJDSys** [angular/material#1762] opened 2015-03-03 14:24 UTC
Currently, the standard $mdDialog template uses ng-bind for the title and content of the dialog.  It would be nice to switch that over to using ng-bind-html, as that would allow for the safe insertion of HTML code without requiring to build a custom template each time.

To try it out, I overrode the template in my app to be able to style some of the dialog text.  The only problem is that users need to either use $sce to mark strings as trusted, or to include the ngSanitize module.  I think that trade of is worth it to make the standard dialogs more useful.

**Comment by ThomasBurleson** [comment] 2015-04-12 19:38
Related to #1495

**Comment by marcysutton** [comment] 2015-04-14 21:37
Closing as duplicate of #1495.

**Closed by marcysutton** 2015-04-14 21:37 UTC
