### ISSUE TITLE
md-datepicker first impression feedback

### ISSUE THREAD

**Issue by no-more** [angular/material#4178] opened 2015-08-15 08:57 UTC
Hi,

First of all, great job. 

I have just tried the new date picker and have a few questions:
 * The date picker does not fit well with other input (http://codepen.io/anon/pen/doLBzj). Shouldn't it be working inside a md-input-container as md-select is currently doing ?
 * It took me some time to understand the scroll to change month feature. Perhaps there should be an other way to change month and year
 * It does not fully support localization :

![2015-08-15_124808](https://cloud.githubusercontent.com/assets/3856871/9288204/e4af5da2-434b-11e5-8aee-371e89a6d33c.jpg)

In this case (french) the date format should be dd/mm/yyyy and not mm/dd/yyyy
The first day of the week is l (Lundi -> Monday) not d (Dimanche -> Sunday)

 * Someone should update the input demo page to include select and date as samples
 * will there be a datetime picker ?
 * there should be an option to disable some dates
 * an other option to change background color of some dates as weekends or make it customizable would be great

Thanks a lot, it's a great component

**Comment by no-more** [comment] 2015-08-15 09:04
After more testing it seems the date format displayed (mm/dd/yyyy) is related to the browser configuration. If I switch to a french environment it's correctly display. You can ignore this point. But the first day of week is still not correctly set.

**Comment by ngraef** [comment] 2015-08-15 21:15
Yes, it looks great so far! But because there's no hint that the calendar can be scrolled, it also took me a surprisingly long time (~30-45 seconds) to figure out how to change months.

Perhaps adding arrows (in addition to the scrolling) would be better? Something like the Windows 10 toolbar calendar:

![image](https://cloud.githubusercontent.com/assets/1031317/9290834/ecb8363e-4366-11e5-882d-318d4625e041.png)

[The material spec](https://www.google.com/design/spec/components/pickers.html#pickers-date-pickers) also uses arrows in addition to swiping.

**Comment by stevenmiles** [comment] 2015-08-17 07:56
Agree with both previous comments about trying to figure out the calendar scrolling. Took me a similar amount of time to figure out what was going on.

**Comment by kamarouski** [comment] 2015-08-17 08:21
+1 for calendar scrolling. Took me a while to figure it out.

**Comment by Koslun** [comment] 2015-08-17 09:54
+1 for an up and down button respectively, to change month. Especially important to actually show the picker slide up and down when changing month so that it is easier to actually understand that this is something you can do.

Think it should also be considered to follow the scrolling guidelines for grids in this case: https://www.google.com/design/spec/components/grid-lists.html#grid-lists-behavior. I.e. to cut off a bigger chunk of another month to indicate that you can actually view it. So a solution might be to show both the following month's title along with the first row and half the second row. Possibly also the more of the preceding month's rows.

As it is now I tested it for several minutes without noticing that you could change month by scrolling. I might however be biased as I assumed it was an incomplete version of the material design date picker. Which is shown to be horizontal, as horizontal scrolling seems to be "discouraged due to breaking normal reading patterns" (see [grid scroll guidelines](https://www.google.com/design/spec/components/grid-lists.html#grid-lists-behavior)) I assumed it was not scrollable. 

Regardless of my bias I do think it would be better to either include more rows from either proceeding or following months or completely cut off showing the following month's title if the view port is deemed too small to allow further extending.

**Comment by jelbourn** [comment] 2015-08-17 19:15
The scrolling behavior is from the spec we are following, which is not yet published to the Material Design site. The calendar shows one extra row from the next month, which is meant to indicate that it can be scrolled. Based on the amount of confusion, though, I'll ask our UX people about how we can make it more clear.

The not aligning with md-input is likely caused by an issue with the `md-input` itself, due to #3234.

The internationalization is all done through `$mdDateLocaleProvider`. Please see the [docs](https://material.angularjs.org/HEAD/#/api/material.components.datepicker/service/$mdDateLocaleProvider).

**Comment by ngraef** [comment] 2015-08-17 19:45
@jelbourn In case this helps the UX team: I did notice the extra row for the next month, but with just the month/year title (see Aug-Sep below), it looked to me like an action on a card (see [Cards - Actions](https://www.google.com/design/spec/components/cards.html#cards-actions)), so my first instinct was to try clicking it (more times than I'm proud to admit). However, moving to the Sep-Oct example where the extra row also contains a few dates, I think the scrolling is much clearer.

<img src="https://cloud.githubusercontent.com/assets/1031317/9313915/5da05da6-44eb-11e5-9f5d-9cf108bbf4e1.png" width="300" />   <img src="https://cloud.githubusercontent.com/assets/1031317/9313926/70239b32-44eb-11e5-8d51-f2667d2d3d5e.png" width="300" />

**Comment by epelc** [comment] 2015-08-17 20:46
+1 for calendar scrolling I didn't notice it until I read this. I highly doubt any of my users would have figure this out easily.

Also it doesn't position it self above the button if there isn't enough room for itself.
![image](https://cloud.githubusercontent.com/assets/5204642/9315764/1f48232c-44ff-11e5-8dc6-4a9dc87e9c97.png)

Also the numbers seem a bit light almost to the point where they look disabled. But otherwise great job this date picker looks amazing!

**Comment by Koslun** [comment] 2015-08-17 22:37
@jelbourn Had a similar experience as @ngraef . Showing just the title of the next month below the current left me thinking it was just part of the design, albeit a weird one. 

I at least seem to be the only one here who completely failed to notice the scroll. Did a blind test on a friend who also noticed it after like 5-10 seconds. Also trying to click the month title

Great that you're forwarding this to the UX team. Great work with the implementation anyway!

**Comment by stevenmiles** [comment] 2015-08-18 08:07
> The calendar shows one extra row from the next month, which is meant to indicate that it can be scrolled

@jelbourn the next month below the current month didn't give me an indication that it could be scrolled. Just like @ngraef and @Koslun, it indicated to me that I should click it. This is why it took me a while to figure it out. I was clicking, not scrolling.

In addition, I think the current date picker is a little inconvenient if you want to select a date that isn't near the current date without whirling the mouse wheel or swiping like a crazy person.

**Comment by MilosStanic** [comment] 2015-08-18 10:42
Comparing Lumx date picker http://ui.lumapps.com/directives/date-picker with this one, it seems Lumx is more inline with the MD specs. 

When you click on the big year in the Lumx datepicker, it opens a year selector, which is very handy. And it has arrows to pick month. 

As for the feature requests, it would be nice to be able to expose an on-click or on-change event so we can bind actions to it. (maybe it's already possible, I didn't test)

Also, it is often desireable to be able to set minimum date and/or maximum date on datepickers, so the dates out of min/max range would be disabled/grayed out. Especially if we were to implement a date-range picker. 

Just my 2 cents ;)

**Comment by nestorneto** [comment] 2015-08-18 15:01
It really should not be only by scroll. I also think that there should be a way to return to the current month. When you scroll down for a while and wants to return to the current month is a little painful to locate.

It would be wonderful if the behavior of month text be like md-subheader (float while scrolling)

**Comment by jelbourn** [comment] 2015-08-18 17:55
Setting a min/max date is tracked by #4158

No change events are exposed now, feel free to file a more specific issue for that.

**Comment by Koslun** [comment] 2015-08-19 01:46
@MilosStanic If I understand @jelbourn correctly from his comment above, this implementation is following another unpublished part of the MD spec for what I assume is the inline version of the date picker.

**Comment by stevenmiles** [comment] 2015-08-19 07:52
Also, doesn't seem to work well with smaller displays

![image](https://cloud.githubusercontent.com/assets/623813/9351183/3900eca8-464f-11e5-935a-df9ab7039335.png)

**Comment by MilosStanic** [comment] 2015-08-19 09:37
@Koslun yes, I thought I understood so about unpublished MD spec part, but I wasn't sure. Anyhow, I've been waiting for a datepicker since December 2014, so I really wish it comes true soon.

**Comment by bluebirdtech** [comment] 2015-08-19 09:40
Great to see this added - thank you!

Requests/suggestions on the initial implementation:
 - Can the icon be optional?  Perhaps added explicitly using md-icon.
 - Masked input when typing in a date would make it easier:
   - No need to type out slashes
   - Structure is shown when there's no value specified
   - Date component can be selected when it is tapped, allowing to replace a value easily
   - Ideally, it would be possible to use the mousewheel to change the selected component value, but I'm not sure how that would work in a touch friendly way.  Perhaps open the picker and use selectors for components.  Leading on to..
 - Feels like it should be possible to select values for date components directly when the picker is open.  eg. Tap the month name and pick a new one.  Certainly for year I'd say this is really important, or you just have to resort to typing, which without masking involves selecting regions of text.

Let me know if I should create separate issues for any of these.

Justin

**Comment by bitoverflow** [comment] 2015-08-25 09:38
Feature request: Option to enable time-picker in the same widget

**Comment by piyushchauhan2011** [comment] 2015-09-02 01:27
I don't like the datepicker doesn't look material at all. As a user, it's also not intuitive to use as everyone is accustomed to principles of selecting month and year using click and not scrolling. 
The only thing that is material is the opening animation. Unfortunately not the best component!

**Comment by bluebirdtech** [comment] 2015-09-02 08:44
+1 I was expecting the above look and feel

**Comment by matthiasg** [comment] 2015-09-02 13:53
great start! 

it would be nice if for each month (i.e for each day) shown a async callback could be executed returning a float (0-1) which could be used in styling (obviously not 1 callback per day).

e.g a backend component could color days by checking a backend calendar  (basically executing a function)..

A full calendar could show a white text on dark blue for already fully booked days and black on white for free days which should be picked (and shades inbetween)

same for individual on/off of dates .. (makes days unselectable)

optimally it should raise sensible events on hover over days to show a tooltip/preview of the exact days schedule or some related information when necessary for e.g picking a date for scheduling.

**Comment by brianfeister** [comment] 2015-09-03 20:05
+1 For the critique that scrolling is not obvious.  I actually sat and clicked all over the place for a few minutes before I realized there was a scrollbar that was not visible (a Chrome thing, I believe).  Seems very minimal in terms of features, but I would use it anyway since I'm already using this library, however, without some kind of up / down indicator to change months I doubt I will use this component.

**Comment by cah-alexsukhodolsky** [comment] 2015-09-08 20:59
+1 ditto re: the calendar scrolling confusion. Took me a while to figure it out as well.

**Comment by chandrask** [comment] 2015-09-11 16:17
Any reason why the UI is not following the material design guidelines? I am referring to the datepicker UI guidelines here https://www.google.com/design/spec/components/pickers.html#pickers-date-pickers

**Comment by 2zillion** [comment] 2015-09-11 16:18
Any reason why the UI is not following the material design guidelines? I am referring to the datepicker UI guidelines here https://www.google.com/design/spec/components/pickers.html#pickers-date-pickers

**Comment by jelbourn** [comment] 2015-09-11 18:45
Summarizing changes from other issues and PRs here:

* I've added a subtle shadow and a new opening animation to better cue the fact that the calendar is scrollable with #4547
* Support for setting the first day of the week addressed via #4498 

Latest version can be seen [here](https://material.angularjs.org/HEAD/#/demo/material.components.datepicker).

Again, we are following a upcoming Material Design spec for the datepicker that hasn't been finalized/published yet. The current implementation is our starting point, and more improvements/features will be coming in down the line. There will likely be some changes in the calendar pop-up behavior for smaller screen sizes.

**Comment by bluebirdtech** [comment] 2015-09-11 19:49
@jelbourn Many thanks for the improvements. Looking forward to seeing what's to come.

**Comment by Koslun** [comment] 2015-09-12 03:53
@jelbourn Great improvement with the shadow but think some kind of scrollbar is still needed to indicate that it is scrollable. Especially if no other buttons are added. 

Only did a blind test with one guy but still took a while before he noticed that it was scrollable.

**Comment by LeoLozes** [comment] 2015-09-15 09:38
@jelbourn thanks! looks better than before, and it's more clear that you can scroll the calendar. I still think a lot of user will look for arrows, but let's see what comes next. 
The year selector thing is really important. There are a lot of use cases (other than the date of birth) where it's necessary to select a different year (driving license, studies, etc.), and right now it's really jarring to go several years back / forward.

**Comment by jelbourn** [comment] 2015-09-15 23:43
Closing this feedback thread now that most of these things have / have had their own issues. File any new feedback in new issues (one issue per thing).

**Closed by jelbourn** 2015-09-15 23:43 UTC

**Comment by bjfletcher** [comment] 2015-09-22 11:23
> we are following a upcoming Material Design spec for the datepicker that hasn't been finalized/published yet

@jelbourn I'd hugely appreciate a link for that, for some solid evidence that this date picker is as per the upcoming specification, before spending some time on this.

P.S. Thanks for the dazzling, impressive date picker :)

**Comment by Koslun** [comment] 2015-09-22 16:21
@bjfletcher Your comment puzzles me. Maybe I'm misunderstanding you but I do not think he's lying. 

As far as I've seen @jelbourn is an official contributor to this repository and Google employee. I do not see why he would lie about this being part of the upcoming Material Design spec. At the very least I would think he wouldn't lie with all the other Google employees who are also contributing to this repository.

Don't think you'll be getting a link to the actual upcoming specification either. As Google seems to keep that under wraps, or at least not bother to show it publicly until it's done. Though I would love to see it too.

**Comment by ThomasBurleson** [comment] 2015-09-22 16:46
Locking this conversation. Please move to the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)
