### ISSUE TITLE
md-fab-speed-dial: md-tooltip in md-button messes with open / closed state

### ISSUE THREAD

**Issue by philipprottner** [angular/material#3748] opened 2015-07-15 18:05 UTC
having **md-tooltip**s in the **md-button**s inside the md-fab-speed-dial leads to strange opening / closing behavior (after the first opening). A temporary fix right now is to move the md-tooltip into the md-icon elements I have in the md-buttons

**Comment by topherfangio** [comment] 2015-07-16 02:05
I don't think tooltips work very well at all in 0.10.0, we've made many improvements in preparation for 0.11.0.

Could you try the latest version in master and see if the issue persists?

If so, could you describe a bit more what happens and what browser you are using?

Thanks!

**Comment by jaitaiwan** [comment] 2015-07-28 07:02
@topherfangio I just tried the latest master branch 691e6f3aca and I can see that the speed dial tries to close really quickly with tooltips. Not sure if that's the same issue @philipprottner was having but its what I'm seeing.

**Comment by jaitaiwan** [comment] 2015-07-28 07:04
Woops, looks like I am using bower-material so I assume I won't have the latest changes available to me.

**Comment by jaitaiwan** [comment] 2015-07-28 07:05
I can confirm that the latest changes in this repo seem to fix the behaviour for me.

**Comment by topherfangio** [comment] 2015-08-03 16:15
@jaitaiwan Awesome! I'm going to go ahead and close this, please re-open if you are still seeing broken behavior in master or one of the latest -rc releases.

**Closed by topherfangio** 2015-08-03 16:15 UTC
Labels: needs: review
