### ISSUE TITLE
Input with ng-messages in column layout height issue

### ISSUE THREAD

**Issue by peio72** [angular/material#4937] opened 2015-09-30 16:19 UTC
Hello, upgrading to 0.11.1 and now got layout issues using inputs in a column layout as shown here:

![columns](https://cloud.githubusercontent.com/assets/13556248/10199119/903d7ede-679f-11e5-9e64-e4fab4eb52e7.png)

with the code:

```

<div layout layout-sm="column">

                        <md-input-container flex>
                            <label>Street Number</label>
                            <input required name="companyStreetNumber" ng-model="company.streetnumber" type="text" maxlength="10">
                            <div ng-messages="registerForm.companyStreetNumber.$error" ng-show="registerForm.companyStreetNumber.$touched">
                                <div ng-message="required">Required field.</div>
                                <div ng-message="maxlength">10 characters maximum.</div>
                            </div>
                        </md-input-container>

                        <md-input-container flex>
                            <label>Street Name</label>
                            <input required name="companyStreetName" ng-model="company.streetname" type="text" maxlength="40">
                            <div ng-messages="registerForm.companyStreetName.$error" ng-show="registerForm.companyStreetName.$touched">
                                <div ng-message="required">Required field.</div>
                                <div ng-message="maxlength">40 characters maximum.</div>
                            </div>
                        </md-input-container>

</div>

```

In 0.11.0 vertical alignement is ok not in 0.11.1 anymore.

Please help. 
Thanx.

**Comment by germanferrero** [comment] 2015-10-01 05:45
Same Here:
![screenshot 22](https://cloud.githubusercontent.com/assets/7140856/10213650/47a1d408-67e6-11e5-86d4-bec572d79971.png)

**Comment by topherfangio** [comment] 2015-10-01 15:12
This should be fixed when #4915 gets merged.

**Comment by sunnyshah01** [comment] 2015-10-12 11:59
+1

**Comment by topherfangio** [comment] 2015-10-12 18:23
#4915 has been merged, can you please retest against the latest master? If the issue is not resolved, please comment and I will reopen.

**Closed by topherfangio** 2015-10-12 18:23 UTC
