### ISSUE TITLE
material design is getting applied to the html markup with the roboto font and toolbar effect getting applied with no color getting applied to it on the background. 

### ISSUE THREAD

**Issue by prajwal78** [angular/material#1142] opened 2015-01-08 18:32 UTC

**Comment by PaulMougel** [comment] 2015-01-08 18:38
Duplicate of #1143.

**Comment by prajwal78** [comment] 2015-01-08 18:46
It works on plnkr but the code doesn't work on my local machine.

**Closed** 2015-01-08 18:59 UTC
