### ISSUE TITLE
[URGENT] Autocomplete autofocus

### ISSUE THREAD

**Issue by allocenx** [angular/material#8134] opened 2016-04-20 13:49 UTC
So i have a big problem and its urgent for this big project that i am working on. So i have an autocomplete inside the chips. The problem is that i can't make when the page loads to make that autocomplete field auto focused...Anyway have any ideea on how i can manage doing that? Nicely please?

**Comment by ThomasBurleson** [comment] 2016-04-20 14:40
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)

**Comment by ThomasBurleson** [comment] 2016-04-20 14:41
Closing this issue due to insufficient information. Please resubmit with:

----
Required
----

**Behavior**:
-  What is the issue? * 
-  What is the expected behavior? 

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue :
-  Details: 

**Angular Versions**: *
-  Angular Version: 
-  Angular Material Version: 

**Additional Information**:
-  Browser Type: *
-  Browser Version: *
-  OS: *
-  Stack Traces: 

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

**Closed by ThomasBurleson** 2016-04-20 14:41 UTC
