### ISSUE TITLE
MdSidenav ability to disable escape

### ISSUE THREAD

**Issue by gpopovic** [angular/material#3469] opened 2015-06-26 05:15 UTC
Is it possible to somehow disable escape key or know when it was pressed?

Because when user press escape key, sidenav will be closed, but i have no way of knowing sidenav was closed.

This is problematic because I cannot know when sidenav was closed (therefore, i'm unable to change $state)

Is there a solution to this problem?

**Comment by tuhoojabotti** [comment] 2015-06-26 09:07
Why would you want to change state if the users closes the sidenav? I think it would be quite confusing for the user, if they want to escape without doing anything.

**Comment by gpopovic** [comment] 2015-06-27 06:22
I have edit form in a sidenav, and i wanted to make sure users could link to it.

That's why when users click on a button, state is changed and sidenav is opened and when users click X in sidenav, state is also changed.

Sidenav is opened/closed with ui.router onEnter and onExit. I know sidebar wasn't designed for that, but there is no other viable in angular material for a quick full screen window open (with animations)

**Comment by ThomasBurleson** [comment] 2015-09-04 05:02
Duplicate of https://github.com/angular/material/issues/4100

**Closed by ThomasBurleson** 2015-09-04 05:02 UTC
