### ISSUE TITLE
md-select doesn't line up with other input elements in md-content

### ISSUE THREAD

**Issue by smartshaila** [angular/material#2793] opened 2015-05-10 00:57 UTC
I've got several md-input-containers and an md-select in an md-content with layout set to row, and the md-select doesn't line up with the other input fields. 

As a temporary override, I can explicitly set margin-top to 1.7em on the md-select to get it to line up.

**Comment by david-gang** [comment] 2015-05-10 08:13
:+1 
We experience the same issue with FF.

**Comment by smartshaila** [comment] 2015-05-10 14:43
I've experienced the issue with Chrome, I haven't tested in any other browsers.

**Comment by Dkendal** [comment] 2015-05-10 16:23
:+1 can confirm in firefox 39.0a2

**Comment by fisch0920** [comment] 2015-05-13 13:22
:+1: experiencing on Chrome

**Comment by redyyu** [comment] 2015-06-03 13:06
![screen shot 2015-06-03 at 8 55 19 pm](https://cloud.githubusercontent.com/assets/724821/7960486/83194392-0a33-11e5-928e-02b26c049477.png)

input inside md-input-container will get string height.
it's cause by parent layout="row" and other md-select inside md-input-container is too hight.

1. I need md-input-container is for validation.
2. I need selects have relative fixed width so parent element is layout="row".

I can only manual override it by custom css?

**Comment by robertmesserle** [comment] 2015-06-16 15:54
@smartshaila I believe I addressed this issue sometime last week - can you confirm that this is still an issue in 0.10.0?  Closing for now, will re-open if it is still an issue.

**Comment by ninety7** [comment] 2015-06-16 16:09
I updated to 0.10.0 and still have this issue, same as the screenshot from @redyyu

**Comment by robertmesserle** [comment] 2015-06-16 16:11
Can somebody create a CodePen demonstrating this issue?

**Comment by redyyu** [comment] 2015-06-16 17:11
here you are.

http://codepen.io/anon/pen/WvEyeR

**Comment by robertmesserle** [comment] 2015-06-16 17:31
Awesome, thanks!  For 0.11.0, I believe we are going to have a focused
effort on tying the styles for all inputs together more cleanly.  It's
great to have this example to include.

**Comment by redyyu** [comment] 2015-06-16 17:36
I did update my last comment, with more details, hope that's helpful...

**Closed** 2015-06-28 21:53 UTC
Labels: CSS

**Comment by eneufeld** [comment] 2016-02-03 10:09
The issue is still there if the md-select is wrapped in a ng-transclude element.
The css selector for aligning md-select inside md-input-container is "md-input-container > md-select" but for all other input elements it is "md-input-container .md-input"
