### ISSUE TITLE
All demos on Codepen are broken - wrong JS CDN link to angular-material

### ISSUE THREAD

**Issue by wembernard** [angular/material#6745] opened 2016-01-19 11:09 UTC
All Codepen demos on https://material.angularjs.org/latest/ are broken because you use a bad CDN setting: `http://localhost:8080/angular-material.js` in `Pen Settings/Javascript` tab.

**Comment by DevVersion** [comment] 2016-01-19 12:24
That's a known issue and a dupe of  #6695.

**Comment by wembernard** [comment] 2016-01-19 12:51
Indeed :+1: 

Didn't find that issue, my bad.

**Comment by DevVersion** [comment] 2016-01-19 12:58
No problem ;) anyway thanks for opening an issue. Can you please close your duplicated issue?

**Closed** 2016-01-19 16:59 UTC
