### ISSUE TITLE
Contact Chips Demo (<number_of_chips>%3) > 0 ? weird ng-repeat behavior : okay;

### ISSUE THREAD

**Issue by dkemper01** [angular/material#4163] opened 2015-08-14 17:33 UTC
Please see this pen for a consistently reproducible demo of this problem.  To reproduce, instead of typing, simply click four contacts to add them to the list of selected contact chips.  

[http://codepen.io/dotComb/pen/EjJroK](http://codepen.io/dotComb/pen/EjJroK)

**Comment by topherfangio** [comment] 2015-08-21 17:41
Can you please provide a description of the actual problem? It's kinda hard to guess exactly what the issue is, but after playing with it, I assume you are referring to the extra whitespace between the items in the bottom list?

<img width="650" alt="screen shot 2015-08-21 at 12 39 48 pm" src="https://cloud.githubusercontent.com/assets/54370/9414975/cfa48166-4801-11e5-8b8d-9b938b636a5d.png">

**Comment by dkemper01** [comment] 2015-08-22 14:44
Yeah, so in the screen shot you have provided, notice how Smith and Metzger's list elements actually exist in the DOM but are invisible to the user.  Further, any number of contacts divisible by three renders appropriately, otherwise the issue in your screen shot happens.

**Comment by topherfangio** [comment] 2015-09-03 22:01
@dkemper01 Is this causing any issue in production code, or is this specific to the docs demo?

**Comment by dkemper01** [comment] 2015-09-04 19:15
My concern is specifically with the demo.  As you might expect, however, the demo is a somtimes a solid indicator of whether or not features and functionality get adopted.  That said, on the contact chips demo, I added some stuff and was going to make a pull request if the dev team finds this useful. 
    A - you can click the chips now.     B - Added shift-delete feature to remove selected chip and all after.
http://dankemper.net/t3/examples/angular/material-start/app/contact-chips-demo.html

Date: Thu, 3 Sep 2015 15:01:44 -0700

**Comment by dkemper01** [comment] 2015-09-04 19:27
Note too - the auto-complete list in the pen does not display the list of filtered contacts based on what the user types.  Further my original change that prompted this issue is minor, and IMHO indicative or a problem with either a material directive or something within angular itself.

**Comment by ThomasBurleson** [comment] 2016-04-28 20:26
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).

**Closed by ThomasBurleson** 2016-04-28 20:26 UTC
Labels: priority: low, type: demos
