### ISSUE TITLE
md-autocomplete suggestions expand unnecessarily on binding of new result set

### ISSUE THREAD

**Issue by tden012** [angular/material#2542] opened 2015-04-24 06:51 UTC
For some reason, the suggestion box on md-autocomplete momentarily displays results that it shouldn't do every time I return a new result set from a promise (at least that is what it looks like to me)

For example:

1) Assume that I am searching for 'Jonathan' in the autocomplete box.
2) Assume also that the server serves up 4 other names, all starting with 'J'
3) When I press 'J' into the input box, all 5 names appear in the suggestion box
4) When I press the next letter 'o', I find that the list filters down to 2 names ('Jonathan' and 'Jon.) - however... before it filters down, the suggestion box inexplicably expands and contracts as if extra entries were added and removed quickly. When I used chrome to check this out, it confirmed my suspicion - it was rapidly adding and removing entries from the suggestion box (At an element level, the suggestion box is an unordered list ('ul' element) with list items ('li' elements) being added and removed.

The problem for me is that this is visually jarring to the user, who has to see the suggestion box expand and contract on every key press. Is there a way to fix this?

**Comment by robertmesserle** [comment] 2015-06-04 17:13
@tden012 I cannot reproduce this - can you confirm that it is still an issue with the latest code?  Closing for now, but reply to this thread to re-open if it is still occurring.

**Closed by robertmesserle** 2015-06-04 17:13 UTC

**Comment by tden012** [comment] 2015-06-14 11:14
Thanks Robert. It's been a busy few days, so apologies for the delay. I'll pull down the latest code and give it another crack.

**Comment by paulflo150** [comment] 2015-08-11 21:43
I am noticing this as well, and I believe it happens because of the .md-autocomplete-suggestions li animation (md-autocomplete-list-out and md-autocomplete-list-in) which appears to animate the height from 0 to 40px and vice versa when adding/ removing records.

It doesn't happen on the demo site though, nor do I see that behavior on codepen for that matter.

Any thoughts on what the purpose of that animation is?

Thanks!
