### ISSUE TITLE
md-select default value

### ISSUE THREAD

**Issue by ilanbiala** [angular/material#1863] opened 2015-03-10 23:22 UTC
Is there currently a way to set a default value for md-select other than setting the ng-model of the field? Is that the intended way?

**Comment by epelc** [comment] 2015-03-11 13:28
@ilanbiala The regular html5 `select/option` has a `selected` attribute. I'm not sure if it works with `md-select` but you can also set `value=""` on one of your options as a hack if the first method doesnt work.

http://www.w3schools.com/tags/att_option_selected.asp

**Comment by prestonvanloon** [comment] 2015-03-19 18:18
+1

**Comment by rschmukler** [comment] 2015-03-23 16:14
You should be able to do it with either `ng-model` on the select itself, or by setting `selected` on one of the `md-option`s. If this isn't working, let me know and we will turn this into a bug.

**Comment by adsamcik** [comment] 2015-03-31 14:27
It shows the default option but it doesn't set the value, so when I retrieve it with $scope.model, the value is undefined, like it would have never been set to any value.

**Comment by rschmukler** [comment] 2015-04-01 21:48
@adsamcik As per this [demo](https://jsfiddle.net/rschmukler/0ju750xo/) it appears to be working.

**Comment by rschmukler** [comment] 2015-04-05 18:19
Closing as I can't reproduce it (see demo above). If it persists, please open a new issue with a demo.

**Closed by rschmukler** 2015-04-05 18:19 UTC
Labels: bug, Demo Needed

**Comment by prasad47** [comment] 2015-08-25 08:32
+1 @ demo

**Comment by langhoangal** [comment] 2015-12-29 10:31
Just note for who go here, in the demo:
- The second way (use selected="selected") won't work with Angular Material release 1.0.0. 
- The first one is OK.

**Comment by vcyang** [comment] 2016-01-06 07:44
If u wanna set the first option as the default value while using `ng-repeat` in `md-option`, maybe you can use `ng-selected="$first"` as below:
![1311c813-e955-4cc6-ad7b-72b062d2fd92](https://cloud.githubusercontent.com/assets/9650396/12137514/35f6ea5c-b48c-11e5-9342-a37908b13e96.png)

**Comment by Berg-it** [comment] 2016-05-31 07:36
>             <md-select ng-model="vmIdPage.number">
>                      <md-option ng-value="mod" ng-repeat="mod in vmIdPage.initObject.listeModaliteMisePlace" ng-selected="{{ mod.id === vmIdPage.number.id ? 'true' : 'false' }}">
>                         {{mod.libelle}}
>                      </md-option>
>             </md-select>

**Comment by anthony-zingbox** [comment] 2016-06-08 00:45
@Berg-it sadly selected=false is invalid according to the HTML spec - the following works though:

`<md-select ng-model="vmIdPage.number">
                 <md-option ng-value="mod" ng-repeat="mod in vmIdPage.initObject.listeModaliteMisePlace" ng-attr-selected="{{ (mod.id === vmIdPage.number.id) }}">
                    {{mod.libelle}}
                 </md-option>
        </md-select> `

**Comment by Muneem** [comment] 2016-06-12 11:23
is this issue resolved?

**Comment by Berg-it** [comment] 2016-06-14 14:54
For me I solved this usnig **ng-selected**:

                <md-select ng-model="vmIdPage.finalObject.categoriePersonnel" style="min-width: 200px;">
                    <md-option ng-value="opt" ng-repeat="opt in vmIdPage.initObject.listeCategoriePersonnel track by opt.id" ng-selected="{{ opt.id === vmIdPage.finalObject.categoriePersonnel.id ? 'true' : 'false' }}">{{opt.libelle}}</md-option>
                </md-select>

**Comment by MurWade** [comment] 2016-07-01 03:30
@Berg-it  if you use ng-change on the md-select with your approach it gets called when it shouldn't. Are you experiencing that also.

**Comment by aseem2625** [comment] 2016-08-08 14:20
@MurWade 
Yes, it happens for me. For @MurWade, it worked because he is not using ng-change.

**Comment by Seiifer** [comment] 2017-04-13 09:15
Is there a way to set the default value, only when there is only one `<md-option>` ?
Meaning we are iterating on a dynamic list using `ng-repeat`.

**Comment by gullocean** [comment] 2017-04-21 14:20
@ilanbiala 
How are you? I have one question for you. I used the md-select, but when I added the ng-selected attritbute in md-options tag, it is firing the automatically ng-change event even though I didn't select anything.. In a word, when page is loaded, the ng-change is firing by ng-selected attribute.. so is there any way to prevent the auto change event when page is loaded? I just want to get the change event when selectbox is change..

**Comment by dsinkey** [comment] 2017-04-24 23:22
I'm getting the same thing.  I have ng-change set on the md-select.  If I use ng-repeat and ng-selected the ng-change is called multiple times and the value selected is the last value in the ng-repeat.

                <md-input-container flex="50">
                    <label>Site</label>
                    <md-select ng-model="data.site" ng-change="siteSelectChanged(data.site)">
                        <md-option ng-repeat="site in sites" value="{{site}}" ng-model="data.site">
                            {{site}}
                        </md-option>
                    </md-select>
                </md-input-container>

**Comment by bfsmithATL** [comment] 2017-05-02 01:10
Just got this working and felt compelled to drop you all out there a quick note, rather than be a persistent lurker, lol.  I was experiencing the same behavior everyone was reporting until I refactored a bit.  @dsinkey, I think one issue you are experiencing may be the result of having defined ng-model="data.site" on both your md-select and your md-option.  You only need to define it on the md-select directive.

Regarding the setting a default value for an md-option which is derived via iterating with ng-repeat, I found that I had to use the ng-selected directive on the md-option directive and evaluate the repeated option against what I set in ng-model AND use interpolation for the evaluation, which I found bizarre.  See this [fiddle demo](https://jsfiddle.net/bfsmithATL/acLdhvut/4/) which I forked from @rschmukler  from his post on March 23, 2015.  

The list will default to "List Item 2" since ng-model (the selectedEntity variable) is initially set to {id: 2, description: 'List item 2'};  

You will also notice that ng-change is raised at least once, upon the setting of the default value.  This is evident by a date/time string rendered in green **INSTEAD** of the string default "Initial Load" when the controller is loaded.

Hope this helps some of you out there on the interwebz.  :-)
