### ISSUE TITLE
IE11 md-select shows both md-content and body scrollbars

### ISSUE THREAD

**Issue by evoker** [angular/material#3442] opened 2015-06-24 14:40 UTC
Check the demo page in IE11 to see the issue: https://material.angularjs.org/latest/#/demo/material.components.select

When opening a select box, an additional scrollbar (from the body or html tags presumably) appears.

I have not been able to find a workaround for this sadly.

Any thoughts?

**Comment by Londovir** [comment] 2015-06-24 14:52
Possibly a duplicate of #3432? Seems like the suggested fix in that one might address this also.

**Comment by evoker** [comment] 2015-06-25 07:17
They do look a bit similar but not sure what's been suggested would work as a fix. I can't really hack material to add this and not sure how I would go about adding this as CSS.

**Comment by rschmukler** [comment] 2015-07-09 17:17
closing as duplicate of #3432

**Closed by rschmukler** 2015-07-09 17:17 UTC
