### ISSUE TITLE
CSS error in <md-list-item> in dense md-list

### ISSUE THREAD

**Issue by zamcsaba** [angular/material#9720] opened 2016-09-28 23:17 UTC
**Actual Behavior**:
 -  `What is the issue? *`
<br>The line height of the `<h3>` element within a `<div>` with class "md-list-item-text" in an `<md-list-item>` with classes "md-3-line md-long-text" or "md-2-line" in a dense `<md-list>`, the `line-height` property of the `<h3>` element in "md-list-item-text" `<div>` is not correct. The current value is 1.06, but some characters (especially 'g', 'y') are not correctly visible. I added `line-height: 1.1 !important;` to that element in my CSS file and the characters were fully visible.
 -  `What is the expected behavior?`

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
```html
<md-list class="dense">
  <md-list item class="md-3-line md-long-text">
    <div class="md-list-item-text">
      <h3>Some text with 'g' and 'y' characters</h3>
      <p>Lorem ipsum dolor sit amet, ei mucius eripuit molestie vim. Unum munere no qui, eum scripta tamquam cu.</p>
    </div>
  </md-list-item>
</md-list>
```
 -  `Details:`

**Angular Versions**: *
 -  `Angular Version:` 1.5.5
 -  `Angular Material Version:` 1.1.1

**Additional Information**:
 -  `Browser Type: *` Chrome
 -  `Browser Version: *` 53.0.2785.116
 -  `OS: *` Microsoft Windows 10 Pro
 -  `Stack Traces:` 

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by DevVersion** [comment] 2016-09-30 16:36
Duplicate of #8890

**Closed by DevVersion** 2016-09-30 16:36 UTC
