### ISSUE TITLE
md-autocomplete styling without float

### ISSUE THREAD

**Issue by bluebirdtech** [angular/material#3064] opened 2015-06-01 13:37 UTC
I'm using inputs without a floating label, just using the placeholder to save space.

I can't seem to get md-autocomplete to match the style of other inputs though?

![md-autocomplete-placeholder](https://cloud.githubusercontent.com/assets/3141867/7913969/b5907da0-086b-11e5-8b1c-0cde31ea8320.png)

I've tried wrapping in md-input-container which doesn't seem to help, nor with md-autocomplete-snap.

**Comment by lkaragol** [comment] 2015-06-12 21:37
+1

I just need a normal input styled autocomplete but without floating label (actually no label)

**Comment by san4ik** [comment] 2015-06-15 14:41
+1

**Comment by lkaragol** [comment] 2015-06-18 22:32
Hey, what about the following css hack? I know, it's not suitable for whole project but may be used in a directive or something else. At least, unit someone done the right things, ha?

md-input-container > label{
  color:rgba(0,0,0,0) !important;
}

**Comment by robertmesserle** [comment] 2015-07-06 21:56
This is a duplicate of #3219 (I know this issue is older than that one, but I'm going to use that one for tracking this bug.)

**Closed by robertmesserle** 2015-07-06 21:56 UTC

**Comment by bluebirdtech** [comment] 2015-07-06 21:59
Thanks Robert
