### ISSUE TITLE
mdDialog: clickOutsideToClose does not remove the element in FF

### ISSUE THREAD

**Issue by 2009** [angular/material#2479] opened 2015-04-22 05:28 UTC
See this demo: http://codepen.io/anon/pen/EjxyXL

After showing the dialog, clicking outside or hitting escape leaves the element in the DOM, not letting you open it a second time.
Happens with both options clickOutsideToClose and escapeToClose.
I've tested this in chrome and it works fine.

Firefox version is 31.0

**Comment by Axel186** [comment] 2015-04-27 11:56
+1

**Comment by dmitriz** [comment] 2015-05-06 04:34
Same Bug in Chrome 42.0.2311.90 :

- Click outside doesn't close any of the dialogs.
- Press Escape closes the 3rd dialog but not 1 and 2:

https://material.angularjs.org/#/demo/material.components.dialog

**Comment by kevin-frugier** [comment] 2015-05-28 08:31
I confirm the bug reported by @dmitriz , the same code on Angular Material 0.8.3 worked fine (dialogs could be closed by clicking outside). But in Angular Material 0.9.0, 0.9.3 & 0.9.4, __dialogs can't be skipped anymore__. This is really annoying since 1.it's a regression compared to previous versions 2.it forces us (unless an easy patch is provided) to redesign our dialogs to have a "close" button when it was not needed before.

**Comment by mdekrey** [comment] 2015-06-17 21:49
:+1: 

Definitely not the behavior as described at https://material.angularjs.org/0.10.0/#/demo/material.components.dialog for Chrome 43.0.2357.124.

**Closed** 2015-07-05 21:57 UTC
Labels: Contributor
