### ISSUE TITLE
dialog: freezes app on close

### ISSUE THREAD

**Issue by tbence94** [angular/material#10741] opened 2017-06-15 13:59 UTC
**Actual Behavior**:
 -  `What is the issue? *`
Open an alert (or any kind of) dialog, then close it by pressing OK (or clicking outside).  It freezes for ~4 seconds then closes, and I have to wait another ~4 second till i get back the responsiveness of the page.
(Eg.: close the dialog, wait till it closes, than hover over the a button, and you will have to wait ~4s to be able to see the button respond by changing its color...)
 -  `What is the expected behavior?`
The dialog should close instatnly (or at least within reasonable time <100ms) and the page should be responsive after that.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` https://codepen.io/anon/pen/YQpWJB
 -  `Details:` Click the button. Close the alert by clicking "OK". Wait till it closes, hover over the "OPEN" button to see when the page becomes responsive again. (The whole process should take 4-8 seconds)

**AngularJS Versions**: *
 -  `AngularJS Version:` 1.6.2 (tested it with 1.5.5 as well. Same result)
 -  `AngularJS Material Version:` 1.1.4

**Additional Information**:
 -  `Browser Type: *` Google CHrome
 -  `Browser Version: *` Version 60.0.3112.24 (Official Build) beta (64-bit)
 -  `OS: *` Ubuntu 17.04 LTS

**Comment by mayvid14** [comment] 2017-07-01 18:17
I cannot see the issue you mentioned in your CodePen. It's working as per your expected behavior.

**Comment by tbence94** [comment] 2017-07-03 07:21
That's odd. I still have this issue. I tried it in incognitoe mode and disabled all flag and extension and it's still a problem. (I tried it with the codepe I pasted above) :(

**Comment by pichon-e** [comment] 2017-08-27 20:25
It is only on Mac OS with chrome. I have the same issue.

**Comment by afilini** [comment] 2018-03-23 11:07
Any news? this is still not working on Chrome 65 with macOS.

**Comment by Splaktar** [comment] 2018-03-26 01:46
I just tested the above CodePen on `Version 65.0.3325.162 (Official Build) (64-bit)` and `Version 67.0.3379.0 (Official Build) canary (64-bit)` on macOS `10.13.3 (17D102)` and everything was almost instantly responsive with no delays.

I also tested with an [updated CodePen](https://codepen.io/Splaktar/pen/oqGWqO?editors=1010) using AngularJS Material 1.1.8 and AngularJS 1.6.9. No issues seen there either.

I have run into a similar problem with MatDialogs in Angular Material lately. I haven't been able to identify the cause there either after 20 hours of debugging and testing. I am able to see the issue in Chrome, Firefox, and Safari. In that case, I can't reproduce it in CodePen/Stackblitz, only in my project. I even created a whole new GitHub repo to reproduce the issue and after pulling out a few proprietary features, the dialog started performing as expected. 

My guess is that your issue is also likely related to some app-specific config/styles/behavior. Hopefully you have better luck debugging your app's issue than I have had with mine!

I'm going to close this for now as it seems to be app-specific, but if anyone can provide a reproducible example on either CodePen or GitHub, then I would be happy to re-open this and look into it.

**Closed by Splaktar** 2018-03-26 01:46 UTC
