### ISSUE TITLE
Open dialog relativeTo

### ISSUE THREAD

**Issue by luano** [angular/material#2271] opened 2015-04-11 20:47 UTC
I would like to open a dialog at a position relative to a another component.

On a smaller device it is ok to center dialogs and the animation is nice, but in some scenarios and in particular on larger screens centering is not always a great option and can lose the context of the interaction a bit. Therefore I would like to open the dialog relative to another componet e.g. rightOf/leftOf etc.

**Comment by epelc** [comment] 2015-04-13 15:11
@luano you can use the `parent` option of `$mdDialog.show(mdDialogOptions)`

See the full docs [here](https://material.angularjs.org/#/api/material.components.dialog/service/$mdDialog). The options are near the end of the page.

**Comment by luano** [comment] 2015-04-13 19:45
That's ok, but when the parent is set that way it will clip the dialog to its bounds. The method will also center the dialog and this may again obscure the 'source' element or be a bit visually disconnected.

**Comment by cah-alexsukhodolsky** [comment] 2015-06-29 16:12
+1

**Comment by ThomasBurleson** [comment] 2015-06-29 16:44
Duplicate of #1206

**Closed by ThomasBurleson** 2015-06-29 16:44 UTC
Labels: G
