### ISSUE TITLE
100% height on body element causing issues

### ISSUE THREAD

**Issue by jasedwards** [angular/material#681] opened 2014-11-18 17:58 UTC
I am using bootstrap and I have set one of my row elements to be 500 px.  I have content above and below this as well.  when the page renders I get the top half gray (my body background-color) and the bottom white.  I went in to dev tools to take a look and the issue is that the body is not resizing.  when I get rid of height:100% that is set on body element in angular-material.css then the issue is fixed.

**Comment by adamduren** [comment] 2015-01-22 19:47
I am experiencing this issue as well. @jasedwards Any update on this issue?

**Comment by adamduren** [comment] 2015-01-22 19:53
What is the intention of setting `height: 100%;` in `angular-material.css`?

I was about to work around the issue with `html, body { min-height: 100%; }` in my own css file.

**Comment by jasedwards** [comment] 2015-01-26 20:05
I believe I had just set min-height:100% in my main css file to overwrite it.

**Comment by ggranum** [comment] 2015-02-05 21:05
The 100% height on the body element is also the cause of the address bar failing to hide on scroll on (at least) Android+Chrome.

**Comment by rschmukler** [comment] 2015-02-07 22:50
The intention is to keep the `body` height fixed so that an inner `md-content` is what scrolls. This makes it so that things like sticky work correctly. It is worth exploring whether we can do something better...

**Comment by ggranum** [comment] 2015-02-08 18:01
@rschmukler Thanks. Unfortunately I'm sure that you've realized by now (perhaps accompanied by a bit of sinking feeling) that even if there isn't something better overall we still won't be able to use 100% height on body.  Here's my reasoning:

- The failure to hide the address bar on mobile is a complete non-starter for real world use. 
- Even if mobile browsers are updated to 'fix' the address bar issue it won't help those older mobile devices that have the most restricted screen real estate. Also, that's a years-long adoption cycle.
- The longer this issue is set aside, the more internal development is made assuming a static height on body:  so, more bugs and more pain later. Unless we're *really* lucky and there is a simple universal hack.

I hope that the team chooses to rip off this bandaid as soon as possible. The number and variety of fixes that are likely to be introduced to fix this in the wild are likely to lead to more developer pain the longer the current behaviour is maintained. It will also lend to more bugs filed later as consuming devs and teams 'forget' which of their styles only exist to work around this issue.

Thanks again - and of course, thanks for *all* the hard work.

**Comment by sp90** [comment] 2015-03-25 13:27
Okay guys the best solution that i found to this issue was following:
```css
html, body {
	position: fixed;
	top: 0; 
	bottom: 0;
	left: 0;
	right: 0;
	margin: 0;
	padding: 0;
	height: 100%;
}
```
This actually solves all issues iv'd run into on safari and chrome on mobile devices

Give it a try and give some feedback on the solution - if it works for you i will open a pull request for it

**Comment by robertmesserle** [comment] 2015-03-25 18:11
The team agrees that this is a major issue; however, these changes will impact a number of components and will require very thorough testing.

**Comment by mateeyow** [comment] 2015-05-28 07:42
:+1:

**Comment by akanimh** [comment] 2015-09-04 16:46
What @ggranum has mentioned mirrors my opinion as well. This really affects designs with long scrolling content on old devices and new. Many users are already used to the address bar hiding itself on down scroll, without it a claustrophobic-feeling UX can occur.

A possible work around involves, removing the 100% height, setting `md-sidenav` and `md-toolbar` to fixed position and affixing a helper class with breakpoints to nudge the content that now flows beneath these. This nullifies the use of `md-content` completely though, and breaks full height `md-sidenav` as you now rely on content to stretch page height.

Looking forward to how this will be addressed, and thanks again for all the work.

**Comment by naomiblack** [comment] 2015-09-04 22:22
@robertmesserle can you please have a close look at this and decide whether we should 1) do this before 1.0  or 2) defer because it's out of scope/too complex to do before 1.0.

I'd prefer to do it pre-1.0 if possible because of the impact on many components. Could you investigate?

**Comment by alfirin** [comment] 2015-09-18 12:39
Hey guys,

First of all thanks for all your hard work.
We are using angular-material in my company and this issue is a major issue.

Could we have more information about this issue (when t will be corrected) ?

Thanks a lot.

**Comment by mackelito** [comment] 2015-11-06 10:19
+1.. we are also facing issues with 100% on body

**Comment by alfirin** [comment] 2015-11-06 11:18
+1 for us. Please keep us updated about this.

**Comment by Ore4444** [comment] 2015-11-06 22:03
It's a critical bug that's been open for a year. What's up with that??

**Comment by baelter** [comment] 2015-11-10 09:22
This one is biting us in the ass constantly. Have anyone found a solid work around?

**Comment by mallowigi** [comment] 2015-11-10 14:50
Just put up "body { height: auto !important }" ?

**Comment by baelter** [comment] 2015-11-10 14:59
That gives weird scroll jumps when opening menus etc.

**Comment by harryPL** [comment] 2015-11-20 15:28
+1, any news about this?

**Comment by ThomasBurleson** [comment] 2015-12-01 19:30
Currently, we have 

```css
html, body {
  min-height : 100%;
}
```
For dialogs, menus, autocomplete, sidenav, etc. we use a backdrop (sometimes invisible) and expect leverage the body height. Does `min-height` still interfere with your needs ?

**Comment by ggranum** [comment] 2015-12-01 20:43
@ThomasBurleson Start a new project using any three random 'getting started' type guides. Does the address bar hide when you scroll down on a mobile device? I seriously doubt it. Thus the answer is going to be 'yes, this should be a block-ship'. 

Angular Material should never have gone to RC with this bug. It is incredibly likely that you won't be able to fix this issue correctly until the next major point release. And that is unbelievably sad.

**Comment by ThomasBurleson** [comment] 2015-12-02 12:29
@ggranum - thx for the feedback. I will escalate a discussion with the team today.

**Comment by ThomasBurleson** [comment] 2015-12-04 16:49
Getting Started and Layout documentation improvements are coming with PR https://github.com/angular/material/pull/6082

**Comment by ThomasBurleson** [comment] 2015-12-04 20:41
Closed with SHA f6e97a02a9c88b1695094a8a85a11958924e4c61

**Closed by ThomasBurleson** 2015-12-04 20:41 UTC
Labels: needs: merge, priority: critical, ui: layout

**Comment by Araknos** [comment] 2020-12-20 18:08
Is this supposed to be resolved ? I still have the issue using Angular 9.

**Comment by Splaktar** [comment] 2020-12-21 03:58
@Araknos Please submit Angular Material and CDK questions [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/components/issues). This repo is for AngularJS Material.
