### ISSUE TITLE
md-nav-bar: Ink bar does not update when resizing buttons

### ISSUE THREAD

**Issue by dbrgn** [angular/material#9966] opened 2016-11-03 15:34 UTC
**Actual Behavior**:
 -  `What is the issue? *` When resizing the width of the buttons in a md-nav-bar with media queries (responsive design), the ink bar does not update.
 -  `What is the expected behavior?` The ink bar detects size changes of the object and redraws.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` https://codepen.io/anon/pen/RobXxM
 -  `Details:` Load the page with a browser wider than 900px. Now make the browser window smaller. The media query triggers at 900px and resizes the buttons. The ink bar remains the old size.

**Angular Versions**: *
 -  `Angular Version:` 1.5.5
 -  `Angular Material Version:` 1.1.1

**Additional Information**:
 -  `Browser Type: *` Chromium
 -  `Browser Version: *` 54.0.2840.90 (64-bit)
 -  `OS: *` Linux

**Comment by 1adnauj** [comment] 2016-12-15 22:01
I have the same problema, there are any work arround?

**Comment by Splaktar** [comment] 2017-12-13 07:01
Going to close this as a duplicate of https://github.com/angular/material/issues/10121, even though this one was submitted first as the other has more discussion.

**Closed by Splaktar** 2017-12-13 07:01 UTC
Labels: resolution: duplicate
