### ISSUE TITLE
1.1.10 requires minimum angular 1.7.2 but should work with 1.4 and higher

### ISSUE THREAD

**Issue by marshfire** [angular/material#11348] opened 2018-06-29 08:38 UTC
## Bug, enhancement request, or proposal:
Bug

# CodePen and steps to reproduce the issue:
#### [CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd) which demonstrates the issue: 
no reproducer (build issue in existing projects that use bower with a dependency of angular-material ~1.1.*)

#### Detailed Reproduction Steps: 
1. readme states that angular >1.4 is required
1. package.json requires ^1.7.2

### What is the expected behavior?
at least continue working with angular 1.6

### What is the current behavior?
build conflicts in all our projects

### Which versions of AngularJS, Material, OS, and browsers are affected?

- AngularJS: 1.4, 1.5, 1.6
- AngularJS Material: 1.1.10
- OS: all
- Browsers: all
 
### Is there anything else we should know? Stack Traces, Screenshots, etc.

introduced by this: https://github.com/angular/material/commit/f6534d6f27a8bdb9802bf510db07d87e4c758d70

**Comment by clemator** [comment] 2018-06-29 12:21
I have the exact same issue

**Comment by IMM0rtalis** [comment] 2018-06-29 14:06
@marshfire @clemator   are you loading angularJS just over dependencies automatically or have you specified this? - I just look again via https://docs.npmjs.com/files/package.json#dependencies and this syntax just says that it supports up until angularJS 1.7.2 ... maybe it would make even sense to limit it to a min-version as well, but after research I think the repository here is correct but your package.json maybe wrong.

**Comment by marshfire** [comment] 2018-06-29 14:17
@IMM0rtalis we usually allow 3rd party dependencies to patch their versions (thus we say "angular-material": "~1.1.5") 1.1.5 has the minimum feature set we needs and we want to be able to get patches but not minor version updates (e.g. no automatic 1.2)

for angular we say "angular": "~1.6.x" (allows everything >= 1.6.0 and < 1.7.0)

in material 1.1.10 angular is required as "^1.7.2" which meens it is compatible with 1.7.2 and everything not major breaking above, but not with versions below (so it allows to be resolved to >= 1.7.2 and < 2.0.0)

This is now an unresolvable conflict and needs touching of every component/ module relying on it. Since material and angular is used by nearly everything we do this would mean touching 50+ projects and releasing new versions.

**Comment by IMM0rtalis** [comment] 2018-06-29 14:22
Oh ok, you are right, sorry. I just read again about the carret: https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004

@Splaktar

**Comment by IMM0rtalis** [comment] 2018-06-29 14:35
@marshfire  Can you check if my PR would be the correct dependency description?

**Comment by Splaktar** [comment] 2018-06-29 18:31
Responding to the OP, you mention that your project uses Bower and then you refer to the `package.json` that Bower doesn't use (it's for NPM). Can you please provide the exact error message?

**Comment by Splaktar** [comment] 2018-06-29 18:43
For 1.1.10, we did bump the minimum Bower dependencies to AngularJS `^1.7.2` from `^1.6.0`: https://github.com/angular/bower-material/blob/master/bower.json.

Please note as indicated [here](https://github.com/angular/bower-material#installing-angularjs-material) support for Bower is deprecated.

For NPM, we support a [wider range of versions](https://github.com/angular/bower-material/blob/master/package.json#L7-L12), `1.4 - 1.7.0 || ^1.7.2`, because their dependency syntax is well [documented](https://docs.npmjs.com/files/package.json#dependencies). I was not able to find such documentation for Bower.

The root cause of this is that AngularJS `1.7.1` is not compatible with AngularJS Material. So we needed to come up with dependency versions that we knew would work.

I will look into whether Bower can support something like `1.4 - 1.7.0 || ^1.7.2`.

**Comment by Splaktar** [comment] 2018-06-29 18:53
It looks like version ranges are in fact supported by Bower (from their [install docs](https://bower.io/docs/api/#install)). It's not clear if they support the `||` operator though.

**Comment by Splaktar** [comment] 2018-06-29 18:56
FYI: You can always choose to stay with a specific version (or range) with Bower as it has the interactive conflict resolution in the CLI.

After some manual testing, it looks like Bower can support the `1.4 - 1.7.0 || ^1.7.2` syntax. I'll update `bower.json` to use that.

**Comment by Splaktar** [comment] 2018-06-29 19:12
OK, this has been pushed up to `bower-material`. You can install from `master` to get this updated set of dependencies using these [steps](https://github.com/angular/bower-material#bower). 

If you want a more stable dependency, you can use the version after the next PR gets merged which will look something like `1.1.10-master-3ef9a02`. You can find the hash to use in the [list of commits](https://github.com/angular/bower-material/commits/master) for bower-material. But you'll need to use one of them after this last commit ("update(bower): use the same dependency range as NPM").

The other option as mentioned above is to just use Bower's conflict resolution to tell it to use the AngularJS `1.6.x` version that you need.

The updated dependencies for Bower will be part of 1.1.11 as well.

**Closed by Splaktar** 2018-06-29 19:12 UTC

**Comment by Splaktar** [comment] 2018-06-29 19:18
Oh one more note, if you are actually on AngularJS `1.4.x`, please upgrade to at least `1.6.x` ASAP. Currently we only provide a minimum level of support for AngularJS `1.4.x` while fully supporting `1.5`, `1.6`, and recommending `^1.7.2`.

For the upcoming AngularJS Material `1.2.0` release, we plan to drop support for AngularJS `1.4` and `1.5`. We'll continue to support `1.6` while focusing our support on the AngularJS LTS which should match `^1.7.2`.

**Comment by Splaktar** [comment] 2018-06-29 21:25
`1.1.10-master-3660a32` is now available with the fix to `bower.json`.

**Comment by marshfire** [comment] 2018-07-02 07:07
@Splaktar Thanks for the fix. We're using angular 1.6, not 1.4 (1.4 was mentioned in the readme of bower-material). The switch to 1.7 is already planned, but still takes a while.
