### ISSUE TITLE
Md-chips readonly

### ISSUE THREAD

**Issue by gpopovic** [angular/material#5610] opened 2015-11-07 21:11 UTC
I can't figure out why, but it appears that when i write in my code <md-chips readonly="true">, it gets shortened to 
just <md chips readonly> which is then ignored by md-chips (md-chips are not disabled).

I'm solving it by using ng-attr-readonly="true" but that is just a nasty hack.

This should be somehow solved...

**Comment by DevVersion** [comment] 2015-11-16 19:26
Hello,

Can you please tell us more, as I currently understand your flag for ```readonly``` isn't working?
Its perfectly working for me (https://material.angularjs.org/HEAD/demo/chips)

So please provide more information.

Thanks in advance!

**Comment by kalvarez2** [comment] 2015-11-18 16:41
Actually, I had the same issue, pasting the code from the demo and just pointing to my controller was ignoring the readonly attribute. I changed it to "ng-attr-readonly" and it started working, I think some of my grunt tasks is removing the attribute "readonly"... I can provide my gruntfile if that helps...

thanks!

**Comment by topherfangio** [comment] 2016-01-06 19:31
Duplicate of #4746.

**Closed by topherfangio** 2016-01-06 19:31 UTC
