### ISSUE TITLE
md-select: display model value as selected value if model have a value

### ISSUE THREAD

**Issue by pradeepkumarrawat** [angular/material#1760] opened 2015-03-03 12:09 UTC
If there is a value in model, it should be displayed as selected.
Right now md-select do not display it untill we click on select. Once we click it, it display the value without selecting it.

See here..
http://plnkr.co/edit/25kM4i4z6MkPKqDKGRs2?p=preview

**Comment by mzbyszynski** [comment] 2015-03-03 15:53
Duplicate of #1699

**Closed** 2015-03-03 16:31 UTC
