### ISSUE TITLE
The md-toolbar in a md-dialog still got the "md-default-theme" class in 0.11.4

### ISSUE THREAD

**Issue by dennislaupman** [angular/material#5169] opened 2015-10-14 19:25 UTC

**Comment by hkjels** [comment] 2015-11-23 11:09
I can confirm that this is an issue. I've solved it by passing the theme as a local, but it should not be necessary.

**Comment by DevVersion** [comment] 2016-02-19 08:16
That seems to be a duplicate of #5899 and should be fixed in #7154. Would be great if you close your issue, because it's a duplicate.

**Comment by DevVersion** [comment] 2016-03-14 20:34
Fixed with SHA a653122cadf5feba15ca6da8fb876098997892dc

**Closed by DevVersion** 2016-03-14 20:34 UTC
