### ISSUE TITLE
Md Menu Not oppening

### ISSUE THREAD

**Issue by amanuel2** [angular/material#8378] opened 2016-05-08 16:57 UTC
Hello There! I am having this problem with Md-Menu.. it use to open but now it dosent for some reason... I dont understand why it changed:

Codeplace:
https://ide.c9.io/amanuel2/fourm2

Html:

```
<head>
  <style>
    .avatar {
      height: 50px;
      width: 50px;
      border-radius: 50%;
      position: relative;
      right: 13px;
      /*bottom: 10px;*/
    }
    
    md-toolbar.md-hue-2 {
      position: relative;
      bottom: 18px;
    }
    
    button.md-icon-button.md-button.md-ink-ripple {
      width: 80px;
      height: 60px;
    }
    
    #NEW_TOPIC_BUTTON {
      position: RELATIVE;
      left: 1620px;
      background-color: #81C784;
      font-weight: bold;
    }
    
    #add_icon {
      position: relative;
      bottom: -4px;
    }
    body {
   -moz-transform: scale(0.8, 0.8);
    zoom: 100%;
    }
  </style>
</head>

<div class="toolbardemoBasicUsage">

  <md-content>

    <br>

    <md-toolbar class="md-hue-2">
      <div class="md-toolbar-tools">
        <md-button class="md-icon-button" aria-label="Menu">
          <md-icon md-svg-icon="img/icons/menu.svg"></md-icon>
        </md-button>
        <h2>
          <span>Welcome {{Username}}</span>
        </h2>
        <span flex=""></span>
        <md-button class="md-icon-button" aria-label="Favorite">
          <md-icon md-svg-icon="img/icons/favorite.svg" style="color: greenyellow;"></md-icon>
        </md-button>


        <md-menu>
          <md-button class="md-icon-button" aria-label="More" ng-click="openMenu($mdOpenMenu,$event)">
            <img class="avatar" src="{{image}}" />
          </md-button>
          <md-menu-content width="4">
            <md-menu-item>
              <md-button ng-click="goToProfile();">
                <ng-md-icon icon="perm_identity" style="fill: black" size="20"></ng-md-icon>
                Profile
              </md-button>
            </md-menu-item>
            <md-menu-item>
              <md-button ng-click="goToSettings();">
                <ng-md-icon icon="settings" style="fill: black" size="20"></ng-md-icon>
                Settings
              </md-button>
            </md-menu-item>
            <md-menu-item>
              <md-button ng-click="logout();">
                <ng-md-icon icon="logout" style="fill: black" size="20"></ng-md-icon>
                Logout
              </md-button>
            </md-menu-item>
          </md-menu-content>


        </md-menu>

      </div>
    </md-toolbar>
</div>

<div class="toolbar_new_topic">
  <md-button id="NEW_TOPIC_BUTTON" ng-click="showNewTopic($event)" flex="100" flex-gt-md="auto">
    <ng-md-icon icon="add_box" style="fill: white" size="20" id="add_icon"></ng-md-icon>
    <span id="text_new_topic" color="white">New Topic</span>
  </md-button>
</div>

<div ui-view>

</div>

```

Javascript : 

```
(function(angular) {
    var app = angular.module('ForumApp');

    app.controller('authHome', ["$scope", "$firebaseObject", "$state", "$mdDialog", "$mdMedia", "$firebaseArray", "refService", "currentAuth", authHomeCtrl])

    function authHomeCtrl($scope, $firebaseObject, $state, $mdDialog, $mdMedia, $firebaseArray, refService, currentAuth) {
        $state.go('authHome.desc')
        var auth = refService.ref().getAuth() ? console.log() : $state.go("home")

        var obj = $firebaseObject(refService.ref().child("UserAuthInfo").child(currentAuth.uid));
        obj.$loaded(function(data) {
                $scope.Username = data.Username;
                $scope.Email = data.Email;
                $scope.UID = currentAuth.uid;
                $scope.image = data.Image;
            },
            function(error) {
                console.error("Error:", error);
            }
        );
        
        

        $scope.goToProfile = function(){
            $state.go("authHome.profile", {
            "UID": $scope.UID,
          })
        }
        $scope.openMenu = function($mdOpenMenu, ev) {
            $mdOpenMenu(ev);
        }

        $scope.logout = function() {
            refService.ref().unauth();
            $state.go("home");
        }
        
        $scope.goToSettings = function(){
            $state.go("authHome.settings", {
                "UID" : $scope.UID,
                "USERNAME" : $scope.Username
            })
        }

        $scope.showNewTopic = function(ev) {
            if (ev) {


                var useFullScreen = ($mdMedia('sm') || $mdMedia('xs')) && $scope.customFullscreen;
                $mdDialog.show({
                        controller: 'newTopicCtrl',
                        templateUrl: 'views/newTopic.html',
                        parent: angular.element(document.body),
                        resolve: {
                            // controller will not be loaded until $waitForAuth resolves
                            // Auth refers to our $firebaseAuth wrapper in the example above
                            "currentAuth": ["refService", function(refService) {
                                // $waitForAuth returns a promise so the resolve waits for it to complete
                                return refService.refAuth().$requireAuth();
                            }]
                        },
                        targetEvent: ev,
                        clickOutsideToClose: true,
                        fullscreen: useFullScreen
                    })
                    .then(function(answer) {
                        //Then Argument
                    }, function() {
                        //Canceled Dialog
                    });

            }

        }

    }

})(angular);
```

**Comment by colinshen** [comment] 2016-05-09 02:57
I have same problem.

**Comment by DevVersion** [comment] 2016-05-09 14:58
Closing this issue due to insufficient information. Please resubmit with and a **demo** without an external IDE please:

----
Required
----

**Behavior**:
-  What is the issue? * 
-  What is the expected behavior? 

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue :
-  Details: 

**Angular Versions**: *
-  Angular Version: 
-  Angular Material Version: 

**Additional Information**:
-  Browser Type: *
-  Browser Version: *
-  OS: *
-  Stack Traces: 

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

**Closed by DevVersion** 2016-05-09 14:58 UTC

**Comment by amanuel2** [comment] 2016-05-13 02:16
@DevVersion Seriously... is this an actual Angular-Material Issue?? @colinshen you figured it out?

**Comment by DevVersion** [comment] 2016-05-13 04:50
@amanuel2 I was only asking for a resubmit with a demo,  without Cloud9. Some Team Members don't have an account and would like to see a Codepen, Plunker, JSFiddle, JSBin instead..

**Comment by amanuel2** [comment] 2016-05-13 11:55
@DevVersion cloud9ide is a seriously awesome online ide... now you guys are tired to even sign up? Wow ok, look at what world we live in today.

**Comment by DevVersion** [comment] 2016-05-13 12:02
@amanuel2 No one said that Cloud9 is not awesome. Cloud9 is a very cool Web IDE.

About being tired. I'm honestly feeling a bit offended... We're definitely not tired, if you see how much PR's we're submitting daily. 

We're putting **much** effort in issues like yours, but I think asking for a Codepen, which **only** shows the actual issue and not other parts of your app, is not too much.

**Comment by amanuel2** [comment] 2016-05-13 20:25
@DevVersion  sorry man i got a little mad there... ill try to reproduce problem on plnk or codepen
