### ISSUE TITLE
mdGridList: update of ng-repeat'ed tiles not handled correctly

### ISSUE THREAD

**Issue by jo-me** [angular/material#2702] opened 2015-05-04 17:56 UTC
Hi,

I have several (dynamic) sets of items that I display in the gridlist using ng-repeat on tile level.

This has worked fine in 0.8.3. In 0.9 (RC3) there are 2 effects that are problematic.

1) When replacing the data the grid content is based on, the new tiles are appended to the existing ones before the old ones are removed. This behavior isreally ugly and also visible in the tab bar control.

2) The height of the grid list is apparently calculated at the wrong moment. It remains the height when old + new tiles were in displayed in the grid. Therefore the "frame" of the tiles is way too big. 

Both effects can be easily seen in an existing codepen that was created by ecunal for issue #2227 
http://codepen.io/ecem/pen/myZVgv

Thanks.
Jochen

**Comment by shawn-simon** [comment] 2015-05-05 00:57
: ( can't upgrade here either. What if you want the entire tile to be surrounded in an anchor tag?

**Comment by ThomasBurleson** [comment] 2015-05-05 03:07
@shyndman  - nasty bug here.

**Comment by DaveRevay2** [comment] 2015-05-15 06:26
Try removing the CSS transition.

**Comment by dmackerman** [comment] 2015-06-01 16:56
Works fine without the CSS transition, but shouldn't it work with transitions as well?

**Comment by Splaktar** [comment] 2015-06-06 15:34
I am seeing the same problem here. CodePen: http://codepen.io/Splaktar/pen/jPmMJz

It is even worse on Firefox which always keeps the size of the containing white frame very tiny. I've been able to reproduce these issues on 0.9.4 and 0.9.8-rc1.

**Comment by Seiifer** [comment] 2015-06-26 12:05
This is describing the same issue :
http://stackoverflow.com/questions/31053433/css-transition-making-tile-position-wrong-angular-material

Didn't manage to make it work with ngAnimathethough.

**Comment by zlwaterfield** [comment] 2015-08-10 01:29
I had the same issue. It seems to be the bottom padding being too large (not update correctly). I fixed it with :

md-grid-list {
  padding-bottom: 0 !important;
}

Not the best fix but it works for me.

**Comment by dsal1951** [comment] 2015-08-24 21:58
I am still having this issue and am using version 10.0 of the code on Chrome 44.0.  Unfortunately zlwaterfield's work around doesn't work for me.  I am using a css transition (the exact same one used in the demo), but I had the exact same problem before I put the transition in place.  

Other info:  I am using the latest stable release of Angular 1.3 and do use ngAnimate throughout my app but I don't think its being used on the grid-list at all

**Comment by shyndman** [comment] 2015-09-23 23:33
@jo-me,

> 1) When replacing the data the grid content is based on, the new tiles are appended to the existing ones before the old ones are removed. This behavior isreally ugly and also visible in the tab bar control.

This is ngAnimate and ngRepeat, not the mdGridList. ngRepeat triggers `$animate.leave`, and `$animate` sees that the grid tiles have transitions. It will then wait that long before removing the element, believing that an animation is occurring.

If you want to prevent this from happening, you will have to tell ngAnimate that there is no leave transition. I've forked your pen and added some CSS that demonstrates the fix. http://codepen.io/shyndman/pen/KdgqEw?editors=010

> 2) The height of the grid list is apparently calculated at the wrong moment. It remains the height when old + new tiles were in displayed in the grid. Therefore the "frame" of the tiles is way too big.

You're correct that this is ngGridList. It incorrectly assumes that the tile elements are removed from the DOM instantly. We're already tracking this in #1559, so I'm closing this off as a dupe.

**Closed by shyndman** 2015-09-23 23:33 UTC
Labels: type: bug, ui: layout
