### ISSUE TITLE
md-tooltip doesn't work on firefox 38.0.5

### ISSUE THREAD

**Issue by Nosthertus** [angular/material#3430] opened 2015-06-24 00:35 UTC
i am trying to make a button on toolbar to show a tooltip whenever the mouse hover on an icon button
```HTML
<md-button class="md-icon-button" ng-href="#/cotizacion">
    <md-tooltip>Cotizacion</md-tooltip>
    <md-icon md-font-icon="fa fa-lg fa-pencil-square-o" aria-label="Cotizacion"></md-icon>
</md-button>
```

but it doesn nothing, even on click, i am using the lastest version `0.10.0`

**Comment by xforceco** [comment] 2015-06-24 05:14
It works, please try to follow the demo page, and ensure you have properly included angular-material.min.css, angular material icons, and angular-material.min.js

**Comment by Nosthertus** [comment] 2015-06-24 05:59
the code is the same on the demo, and even the demo doesn't work for me, only if i check "insert dive" and i'm loading all libraries but yet it doesn't work, i am using firefox browser

**Comment by xforceco** [comment] 2015-06-24 06:46
I see you intend to use font-awesome.
Have you included it properly?

https://material.angularjs.org/latest/#/api/material.components.icon/service/$mdIconProvider

And please provide a plunker for details, as I am sure at least for:

  <md-button class="md-icon-button" ng-href="#/cotizacion">
      <md-tooltip>Cotizacion</md-tooltip>
      <md-icon md-font-icon="fa fa-lg fa-pencil-square-o" aria-label="Cotizacion"></md-icon>
  </md-button><md-button class="md-icon-button" ng-href="#/cotizacion">
      <md-tooltip>Cotizacion</md-tooltip>
      <md-icon></md-icon>
  </md-button>

the tooltip is working in my codepen

**Comment by Nosthertus** [comment] 2015-06-24 06:49
@xforceco but why it doesnt work even in the demo?

**Comment by xforceco** [comment] 2015-06-24 06:52
![pr3](https://cloud.githubusercontent.com/assets/12808889/8324203/89e0b798-1a80-11e5-9fd8-3dda342d2c00.png)

which demo page are you referring to?
tooltip works, but I am not sure whether your font-icon works

**Comment by Nosthertus** [comment] 2015-06-24 06:57
![firefox version](http://i.imgur.com/ApmBNvN.png)

i am still learning angular material and i have no idea how i would properly set the classes on $mdIconProvider

**Comment by Nosthertus** [comment] 2015-06-24 07:04
@xforceco on the demo, when you hover the button, does the tooltip work?

**Comment by xforceco** [comment] 2015-06-24 07:12
@Nosthertus Yes, it is a screen capture when I hover on the button, so I don't understand why you said demo not working.

**Comment by Nosthertus** [comment] 2015-06-24 07:13
@xforceco because in my screen, the demo doesn't work, just when i click on "insert dive"

**Comment by sajmons** [comment] 2015-06-24 08:49
I can confirm that in FireFox 38.0.5 hover tool-tips isn't working.

CodePen: http://codepen.io/anon/pen/RPjLzW

**Comment by Londovir** [comment] 2015-06-24 14:09
Seems like some sort of odd Firefox issue. If you single step in Firefox, you hit a call to `setVisible(true)` buried in the method `bindEvents` for the md-tooltip. For Firefox, though, single stepping that line actually diverts you into `createEventHandler/eventHandler` of jqLiteOn, and eventually the method calls run out without the call to `setVisible` ever resolving. In fact, oddly enough, a single single-step action doesn't visibly do anything in Firefox developer tools, which is odd. I can't quite figure out what's happening with that. It's almost like that is trying to call `setVisible` but fails, for some reason.

In Chrome, BTW, that call to `setVisible` resolves instantly, and then it proceeds to the event handlers. Not sure why Firefox is getting pre-empted or ignoring the call to `setVisible`.

Note, though, that moving your cursor off the bound element (fab) IS triggering the `setVisible(false)` call properly.

**Comment by Nosthertus** [comment] 2015-06-24 17:05
@Londovir so, should i wait for the developers to see if they can fix this in another updated version?

**Comment by JDGoldman** [comment] 2015-06-24 17:51
I have the same issue with Firefox 38.0.5.

**Comment by Splaktar** [comment] 2015-06-26 02:50
This is already reproducible in the tooltip.spec.js tests. If Karma is run with Firefox 5 of the tests fail.

1a07051 does indeed fix the tests and causes them to pass on all browsers.

**Closed** 2015-07-01 16:29 UTC

**Comment by Luxiyalu** [comment] 2015-07-21 03:23
For the time being, use something like this to force the display:

````
<md-button class="md-fab md-accent" aria-label="Play" ng-mouseenter="show=true" ng-mouseleave="show=false">
  <md-tooltip md-visible="show">
    Play Music
  </md-tooltip>
</md-button>
````

**Comment by danieladz** [comment] 2015-07-23 12:30
I'm having the same issue with the tooltip also the icon in the button doesn't recognize any hover action for example color changing on hover... 
@Luxiyalu I tried your way and it didn't work on firefox :(

**Comment by Splaktar** [comment] 2015-07-23 18:37
This should be working in 0.10.1-rc3. 

As for the button hover behavior, I think that most button hover styles were removed a couple releases ago since they aren't in the spec (don't work on mobile).

**Comment by gilad905** [comment] 2016-07-13 08:49
I had the same problem (md-tooltip worked on Chrome but not on Firefox) and found out that this can be caused by placing md-tooltip as an **indirect** child of md-button. E.G:
`				
<md-button id="reload-button" class="md-icon-button material-icons">
	<span style="margin:auto">
		refresh
		<md-tooltip>Reload</md-tooltip>
	</span>
</md-button> 
`

Instead of
`
<md-button id="reload-button" class="md-icon-button material-icons">
	refresh
	<md-tooltip>Reload</md-tooltip>
</md-button> 
`

It actually makes sense that md-tooltip would be expected to be the direct child of md-button, but since in Chrome the 2nd case **also works,** this might be a cause for confusion among developers.

**Comment by naveenjafer** [comment] 2016-07-15 09:02
In my case I have a Md-list element on which I am trying to create a tooltip. Works on chrome and safari but fails on firefox.

**Comment by ThomasBurleson** [comment] 2016-07-15 12:37
We support **evergreen browsers** n-1; Firefox v38 is not supported.
