### ISSUE TITLE
input-container: seems odd inside md-toolbar

### ISSUE THREAD

**Issue by sombriks** [angular/material#8741] opened 2016-06-11 21:54 UTC
**Actual behavior**:
-  What is the issue? Got unexpected color over the input field inside md-toolbar
-  What is the expected behavior? normal appearance even if inside md-toolbar

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue : http://codepen.io/anon/pen/XKdrop?editors=1001
-  Details: a blue rectangle over input field

**Angular Versions**: \* 
-  Angular Version: 1.5.3
-  Angular Material Version: 1.1.0-rc2

**Additional Information**:
-  Browser Type: \* chrome 
-  Browser Version: \* latest stable
-  OS: \* fedora 23
-  Stack Traces: none

---

Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
>   Add more lines if needed.

**Comment by bradrich** [comment] 2016-06-23 17:35
This issue pertains to the fact that there is not a way to place contrasting color themes on inputs. However, with a little bit of work, you can get a satisfactory approach.

Pen:  http://codepen.io/bradrich/pen/BzQgJO

The Material team is working on a theming release that will better address the input color systems. @EladBezalel can address these upcoming improvements.

**Comment by DevVersion** [comment] 2016-06-23 17:36
Here is the related PR, which will probably open some new _doors_.
- #8757

**Comment by jonathanwiesel** [comment] 2016-11-29 14:40
Having the same issue here, any workaround?

**Comment by Splaktar** [comment] 2018-12-09 10:43
Duplicate of https://github.com/angular/material/issues/7987.

**Closed by Splaktar** 2018-12-09 10:43 UTC
Labels: resolution: duplicate
