### ISSUE TITLE
$rootScope:inprog: $digest already in progress 

### ISSUE THREAD

**Issue by sazary** [angular/material#8938] opened 2016-07-04 08:09 UTC
Hi
I'm getting this error through Sentry, and I can't find out which component is causing this error or what behavior on part of user causes this error, and I can't reproduce this. On the page that this error is thrown from I've used mdButton, mdList and mdToolbar among some other components.
Here is the actual crash report:  http://miare.ir:9000/share/issue/322e3232/

**Angular Versions**: *
 -  `Angular Version:` 1.5.7
 -  `Angular Material Version:` v1.0.8-master-3e452d2

**Additional Information**:
 -  `Browser Type: *` Mobile Safari UI/WKWebView 
 -  `Browser Version: *` 9.3.2
 -  `OS: *` iOS 9.3.2
 -  `Stack Traces:`
```
$rootScope:inprog: $digest already in progress
  at ? (~/angular/angular.js?3437:68:0)
  at m(~/angular/angular.js?3437:17804:0)
  at callback(~/angular/angular.js?3437:17542:0)
  at element(~/angular/angular.js?3437:25627:0)
  at element(~/angular/angular.js?3437:3488:0)
  at this(~/angular/angular.js?3437:3476:0)
  at eventObj(~/raven-js/src/raven.js?ae06:257:0)
  at dispatchEvent([native code])
  at ev(~/angular-material/angular-material.js?ec27:2262:0)
  at ev(~/angular-material/angular-material.js?ec27:1920:0)
  at event(~/angular-material/angular-material.js?ec27:2164:0)
  at o(~/angular-material/angular-material.js?ec27:2354:0)
  at element(~/angular-material/angular-material.js?ec27:2401:0)
  at element(~/angular/angular.js?3437:3488:0)
  at this(~/angular/angular.js?3437:3476:0)
  at name(~/raven-js/src/raven.js?ae06:257:0)
  at setAttribute([native code])
  at this(~/angular/angular.js?3437:3328:0)
  at attrName(~/angular/angular.js?3437:3427:0)
  at name(~/angular/angular.js?3437:8183:0)
  at value(~/angular/angular.js?3437:22021:0)
  at context(~/angular/angular.js?3437:8194:0)
  at $$observers(~/angular/angular.js?3437:321:0)
  at name(~/angular/angular.js?3437:8192:0)
  at this(~/angular/angular.js?3437:9719:0)
  at newValues(~/angular/angular.js?3437:12295:0)
  at value(~/angular/angular.js?3437:16952:0)
  at $digest(~/angular/angular.js?3437:17286:0)
  at $apply(~/angular/angular.js?3437:17552:0)
  at status(~/angular/angular.js?3437:11697:0)
  at callback(~/angular/angular.js?3437:11903:0)
  at this(~/angular/angular.js?3437:11836:0)
  at this(~/raven-js/src/raven.js?ae06:257:0)
```

**Comment by DevVersion** [comment] 2016-07-04 10:45
Hey, thanks for the issue. It's pretty difficult to find the problem without any running demo.

I just took a look at the Stack Trace and figured out that your issue is related to the `$mdGesture` service.

Can you probably try to create a Codepen (or something else) and explain how you're interacting with your App? (it must relate to any interaction)

**Comment by crisbeto** [comment] 2016-07-04 11:24
FYI Sentry has the "Breadcrumbs" section that shows what the user was doing before he/she got the error. Seems like the last action was on a `div.ng-scope`.

**Comment by DevVersion** [comment] 2016-07-04 11:26
Ah well, that's pretty neat, but doesn't really help. It can be any `<div>` element.

**Comment by crisbeto** [comment] 2016-07-04 11:28
Yes, but the Material ones usually have at least some class associated with them.

**Comment by DevVersion** [comment] 2016-07-04 11:29
Yeah, definitely, but we can't identify it yet.

**Comment by crisbeto** [comment] 2016-07-28 15:12
I'll close this since we can't do anything without a case that reproduces the error.

**Closed by crisbeto** 2016-07-28 15:12 UTC
