### ISSUE TITLE
md-menu does not show properly on firefox

### ISSUE THREAD

**Issue by kschwidder** [angular/material#7914] opened 2016-04-06 16:48 UTC
When opening the demo-site 1.1.0-RC2 the menu in firefox is not shown properly.
It seems to be a css issue. Would be nice to fix this.

Menu-items are shown similar to layout=column mode
<img width="261" alt="firefox" src="https://cloud.githubusercontent.com/assets/3265624/14325065/db2076f0-fc27-11e5-988e-e507f9a7e3b5.png">

properly shown in chrome

<img width="258" alt="chrome" src="https://cloud.githubusercontent.com/assets/3265624/14325069/de835e0c-fc27-11e5-8c43-c20bda232bd5.png">

**Comment by manish2535** [comment] 2016-04-06 17:24
Duplicate of [https://github.com/angular/material/issues/7824](url)

**Closed** 2016-04-20 23:07 UTC
Labels: resolution: duplicate
