### ISSUE TITLE
mdChips (feature): value expression

### ISSUE THREAD

**Issue by smashercosmo** [angular/material#3529] opened 2015-07-01 08:45 UTC
Provide value-expression for mdChips similar to "select" expression in ngOptions.
Use case: 
1. I have a list of values [{ title: 'One', value: 1 }, { title: 'Two', value: 2 }, { title: 'Three', value: 3 }];
2. I want to provide value expression to mdChips like "item.value"
3. So when I add first two items in the model (for example using autocomplete), i'll get the model, that will look like [1,2]

**Comment by heyton** [comment] 2015-07-01 08:55
+

**Comment by liyatang** [comment] 2015-07-02 10:25
+

**Comment by ilanbiala** [comment] 2015-07-22 21:28
+1, I think my request (#3863) is a duplicate of this.

**Comment by ilanbiala** [comment] 2015-07-23 14:24
@typotter are you guys already working on a fix for this or would you be willing to accept a PR?

**Comment by typotter** [comment] 2015-08-10 03:44
ilanbiala is correct, this is accomplished by using a Custom Chip Template.

**Closed by typotter** 2015-08-10 03:44 UTC

**Comment by smashercosmo** [comment] 2015-08-10 07:54
@typotter no, it's not. because you might want to show in template one thing and keep in model something different.

**Comment by typotter** [comment] 2015-08-10 15:15
@smashercosmo: Can you please provide an example? You can put anything into the chip template. If your chip label is not a field of your collection object, but a function of it, you can do that to:


    <md-chip-template>
      <span>{{getChipLabel($chip)}}</span>
    </md-chip-template>

**Comment by smashercosmo** [comment] 2015-08-10 15:48
@typotter 
```javascript
$scope.list = [{ title: 'One', value: 1 }, { title: 'Two', value: 2 }, { title: 'Three', value: 3 }];
$scope.model = [];
```
```html
<md-chip-template>
  <span>{$chip.title}</span>
</md-chip-template>
```
After adding all three chips, I'll get (One) (Two) (Three) in my view, but I also want to have [1,2,3] in my model. This is the same functionality that you can get with ng-options by using "select as label for value in array" syntax. Does this make sense?

**Comment by typotter** [comment] 2015-08-10 16:03
If you want the collection model to be [1, 2, 3] instead of  [{ title: 'One', value: 1 }, ...], you can provide an md-on-append expression, but you will also need an external function to render the chip label:

    md-on-append="$chip.value"

and chip template:

    <md-chip-template>
      <span>{{getChipLabel($chip)}}</span>
    </md-chip-template>

What you're proposing, at heart, is to get the label for a chip _from somewhere external to the chip object_, which can be accomplished as demonstrated above. Proving an expression like ```item.value``` will not work, since you want your collection to be the integers, and not the objects containing the `value` field.

Alternatively, you could convert the collection wherever you use it:

    myInts = myChips.map(function(chip) { return chip.value; });

**Comment by ilanbiala** [comment] 2015-08-10 16:08
@typotter why was an ng repeat expression like that of select not implemented?

**Comment by typotter** [comment] 2015-08-10 16:30
Chips contains only the collection of selected objects and has no knowledge of the available options. This is why such an expression is not used - the list of available options is outside the scope of Chips' concerns.
