### ISSUE TITLE
Dialogs showing unnecessary vertical scrollbar

### ISSUE THREAD

**Issue by LucasKuhlemann** [angular/material#9640] opened 2016-09-19 17:01 UTC
**Actual Behavior**:
 -  `What is the issue? *`
Every dialog is adding an unnecessary vertical scrollbar to the body.
 -  `What is the expected behavior?`
No scrollbar.

**CodePen** (or steps to reproduce the issue): *

The issue can be seen on angular material's own demo:
https://material.angularjs.org/1.1.1/demo/dialog  
Notice that any opened dialog creates a disabled vertical scrollbar.

**Angular Versions**: *
 -  `Angular Version:`
1.5.8
 -  `Angular Material Version:`
1.1.1

**Additional Information**:
 -  `Browser Type: *`
Chrome
 -  `Browser Version: *`
Version 47.0.2526.106 (64-bit)
 -  `OS: *`
Linux 4.2.0-22-generic #27-Ubuntu x86_64 x86_64 x86_64 GNU/Linux
 -  `Stack Traces:`
None

**Comment by DevVersion** [comment] 2016-09-20 09:07
I cannot reproduce this on Chrome 53 on Windows 10.

**Comment by LucasKuhlemann** [comment] 2016-09-20 11:17
I noticed I could only reproduce this in ubuntu and Debian,  but not on windows or Android.

**Comment by U-like** [comment] 2016-09-20 15:12
I cannot reproduce this on Chrome 53 on Ubuntu 16.04.

**Comment by DevVersion** [comment] 2016-09-20 17:25
I was also not able to reproduce this on Xubuntu 14.04+

Going to close this issue as I consider this as an edge case.

**Closed by DevVersion** 2016-09-20 17:25 UTC
