### ISSUE TITLE
icon: svg icons stop working on older android versions

### ISSUE THREAD

**Issue by sombriks** [angular/material#9477] opened 2016-09-01 04:18 UTC
**Actual Behavior**:
 -  `What is the issue? *` missing svg icons

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` see screenshots
 -  `Details:`

This one (android 6 webview) works as expected:
http://imgur.com/B9fYQFp

This one (android 4.4.2) is missing svg icons:
http://imgur.com/zQAWKbg

Don`t know if it`s related, but using chrome://inspect this error pops out on problematic android 4.4.2 device:

> ReferenceError: Set is not defined
>     at i (file:///android_asset/www/bower_components/angular-material/angular-material.min.js:15:11559)
>     at Object.n.$get (file:///android_asset/www/bower_components/angular-material/angular-material.min.js:15:14146)
>     at Object.invoke (file:///android_asset/www/bower_components/angular/angular.min.js:41:456)
>     at file:///android_asset/www/bower_components/angular/angular.min.js:43:265
>     at d (file:///android_asset/www/bower_components/angular/angular.min.js:40:432)
>     at e (file:///android_asset/www/bower_components/angular/angular.min.js:41:158)
>     at Object.invoke (file:///android_asset/www/bower_components/angular/angular.min.js:41:243)
>     at file:///android_asset/www/bower_components/angular/angular.min.js:53:3
>     at q (file:///android_asset/www/bower_components/angular/angular.min.js:7:355)
>     at Object.<anonymous> (file:///android_asset/www/bower_components/angular/angular.min.js:52:476) angular.js:13920

**Angular Versions**: *
 -  `Angular Version:` 1.5.8
 -  `Angular Material Version:` "1.1.0-rc.5-master-2d8eb6d"

**Additional Information**:
 -  `Browser Type: *` android webview
 -  `Browser Version: *` 6.0 and 4.4.2
 -  `OS: *` android
 -  `Stack Traces:` see above

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by clshortfuse** [comment] 2016-09-12 13:31
Can you post a codepen demo showing the issue?

**Comment by clshortfuse** [comment] 2016-10-10 15:28
I can't reproduce this issue without some sort of demo, so I'm closing this. 

@sombriks If you are still having an issue, people create a codepen showing the issue and reply here.

**Closed by clshortfuse** 2016-10-10 15:28 UTC
Labels: browser: Android, needs: demo, resolution: can't reproduce
