### ISSUE TITLE
$mdSideNav no longer animates in angular 1.4.4

### ISSUE THREAD

**Issue by hodeyp** [angular/material#4152] opened 2015-08-14 10:24 UTC

**Comment by julienpa** [comment] 2015-08-14 12:50
I have the same issue with Angular Material 0.10.1

**Comment by brianfeister** [comment] 2015-08-14 15:04
:+1:

**Comment by AleksueiR** [comment] 2015-08-17 12:53
:+1:

**Comment by nestorneto** [comment] 2015-08-18 14:36
the animations seem more fluid in angular 1.3.x than in 1.4.x. Anyone else feels like this?

**Comment by julienpa** [comment] 2015-08-18 14:38
@nestorneto although I didn't try with Angular 1.3.x, it's completely possible: ngAnimate was largely re-written in 1.4 and it may have introduced some performance issues for some modules I guess

**Comment by ThomasBurleson** [comment] 2015-08-18 15:07
The Angular teams are working on improvements to ngAnimate and *request animation frame* optimizations. We hope to have these types of perf issues more fully addressed by start of next week.

**Comment by julienpa** [comment] 2015-08-18 15:34
Thanks for the update @ThomasBurleson !

**Comment by topherfangio** [comment] 2015-08-19 23:50
@matsko Per your request, here is a codepen demonstrating the problem: http://codepen.io/topherfangio/pen/OVeNym

**Comment by hallaji** [comment] 2015-08-20 16:58
@topherfangio :+1:  I have the same issue too.

**Comment by prijindal** [comment] 2015-08-21 19:00
I think the problem is somewhere in angular-animate 1.4.4
Instead of using 1.4.4 using 1.4.3 resolved my problem

**Comment by topherfangio** [comment] 2015-08-21 20:40
Yes, I believe the team is investigating some changes in 1.4.4 that might be causing the issue. It looks like there were quite a few updates, though, so it's possible we need to update the material component too.

Hopefully we'll hear back soon about whether or not it's actually an issue in 1.4.4.

**Comment by matsko** [comment] 2015-08-21 20:43
I'm working on a fix right now.

**Comment by topherfangio** [comment] 2015-08-21 20:47
Sweet. Thanks @matsko!

**Comment by miclaus** [comment] 2015-08-25 08:39
Thank you @matsko !

**Comment by matsko** [comment] 2015-08-25 17:16
1.4.5 will fix the issue: http://codepen.io/yearofmoo/pen/aOeaYY

**Comment by ThomasBurleson** [comment] 2015-08-25 17:53
@matsko - what was the commit that fixed this ?

**Comment by matsko** [comment] 2015-08-25 17:55
Not merged into master yet. Waiting for Igor to review https://github.com/angular/angular.js/pull/12669

**Comment by Blackmoonx** [comment] 2015-08-28 12:51
@matsko Is there any ETA for 1.4.5 release?

**Comment by matsko** [comment] 2015-08-28 14:45
Later today if all goes smoothly

**Comment by Wsiegenthaler** [comment] 2015-08-29 02:04
Just updated to 1.4.5 and animation is back

**Closed** 2015-09-01 15:14 UTC
Labels: hotlist: angular-issue, hotlist: animations, needs: investigation
