### ISSUE TITLE
contact-chips: Clicking the scrollbar closes the contact list instead of performing a scroll operation

### ISSUE THREAD

**Issue by molehillrocker** [angular/material#11813] opened 2019-10-24 14:21 UTC
## Bug, enhancement request, or proposal:
Bug.

# CodePen and steps to reproduce the issue:
#### [CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd) which demonstrates the issue: 
Can be reproduced with the AngularJS Material demo [here](https://material.angularjs.org/latest/demo/chips#contact-chips).

#### Detailed Reproduction Steps: 
1. Focus input field under *Searching asynchronously*
1. Type a letter, e.g. `a`
1. Click on the scrollbar (or a scrollbar button)

### What is the expected behavior?
The scrollbar scrolls the list of contacts up or down.

### What is the current behavior?
The contact list is closed.

### What is the use-case or motivation for changing an existing behavior?
Users need to use the mouse wheel to be able to scroll the list of contacts, some users over here have no mouse available and need to use the buttons on their notebook, unfortunately the touch panel is not capable of performing scroll operations.

### Which versions of AngularJS, Material, OS, and browsers are affected?

- AngularJS: 1.7.7
- AngularJS Material: 1.1.20
- OS: Windows 7/Windows 10
- Browsers: IE11
 
### Is there anything else we should know? Stack Traces, Screenshots, etc.
Nope.

**Comment by marosoft** [comment] 2019-11-04 20:52
Hi @molehillrocker 

Is it a duplicate of #11776 ?

**Comment by molehillrocker** [comment] 2019-11-05 07:51
The behavior is the same as in #11776, however #11776 targets *md-autocomplete* and I observe this issue in *md-contact-chips*. But since I think both use the same code or are derived from each other, I'd say yep, than it is a duplicate. :)

**Comment by Splaktar** [comment] 2020-03-07 11:15
Verified that this is fixed by https://github.com/angular/material/commit/5b0c9ba9e0e5313925f6a27390559f32028fd95b in IE11.

**Closed** 2020-03-07 11:17 UTC
Labels: P3: important, browser: IE, for: external contributor, resolution: fixed, type: bug
