### ISSUE TITLE
md-autocomplete demo hang Chrome browser tab

### ISSUE THREAD

**Issue by tolemac** [angular/material#3334] opened 2015-06-17 22:35 UTC
1) Load demo page on browser https://material.angularjs.org/latest/#/demo/material.components.autocomplete

2) Click "what is your favorite US state" 
3) Select "Alabama"
4) Click remove button (on the right of control)
5) Click out of to lost focus

The browser is frozen.

Tested on Chrome versión 43.0.2357.124 m

**Comment by mukilane** [comment] 2015-06-18 05:54
+1
But it doesn't freeze the whole browser. Just the single process/tab is frozen. 
On Chrome Version 43.0.2357.125

**Comment by tolemac** [comment] 2015-06-18 06:03
Yes, only the current tab.

**Comment by jgoux** [comment] 2015-06-18 06:36
Duplicate of https://github.com/angular/material/issues/3287

**Closed** 2015-06-18 09:32 UTC
