### ISSUE TITLE
md-card-actions button alignment with layout-xs="column"

### ISSUE THREAD

**Issue by ad0ran** [angular/material#7575] opened 2016-03-15 16:54 UTC
There seems to be an alignment issue if you apply layout-xs and layout-align-xs.
codepen: http://codepen.io/anon/pen/yOVjXW

**Comment by topherfangio** [comment] 2016-03-16 19:10
This appears to be caused by the first and last elements having left and right margin set (respectively), but them not being equal. Ideally, we'd find a better solution (perhaps having the card container have the proper padding).

That said, I do not see a single instance in the [spec](http://www.google.com/design/spec/components/cards.html) where a card's action stretch all the way across. The card actions should be short words, and thus they should generally fit even on mobile devices.

**Comment by ad0ran** [comment] 2016-03-16 21:13
@topherfangio it's odd though, because if you just set the layout to "column" and the layout-align to "start" (like in the vertical buttons example) the buttons align just fine.

i just added the md-raised classes to the buttons off the codepen example: http://codepen.io/anon/pen/qZRZJK

**Comment by DevVersion** [comment] 2016-03-19 20:07
@topherfangio When want to apply the correct padding, then we need to use some conditional checks in CSS, but that's not possible. 

So at the moment I figured out two ways:
- Condition Classes through JavaScript
- Remove *Last Type of* Margin when Breakpoint Small is matched

**Comment by topherfangio** [comment] 2016-03-21 21:10
@DevVersion What are the conditional checks we want to use? Shouldn't the `md-card-actions` always have a certain amount of padding?

**Comment by DevVersion** [comment] 2016-03-21 21:16
@topherfangio I played a bit with the action button padding.

And tried to move the padding upward to the `md-card-actions` container, but then I noticed that there will be always a different padding for different action types.
- `md-button`
- `md-icon-button`

So for that, we need to have some conditional checks and apply a proper class (which applies the padding etc.) on the `md-card-actions` container, like `.md-icon-actions` or `.md-button-actions`.

**Comment by topherfangio** [comment] 2016-03-21 21:23
Hmm, I am not sure we can pick one or the other. For instance, there are many cases where the actions can contain both:

![card actions](http://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0Bzhp5Z4wHba3MHh2ZlhHVUMyQlk/components_cards17.png)

_pulled from http://www.google.com/design/spec/components/cards.html#cards-actions_

**Comment by ThomasBurleson** [comment] 2016-04-28 19:34
This issue is closed as part of our deprecation effort. 
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).

**Closed by ThomasBurleson** 2016-04-28 19:34 UTC
Labels: P4 - Reported By or General PRs/Errors or Edge Cases, ui: CSS

**Comment by kirchhoffandre** [comment] 2017-11-01 13:17
is there some code example for the Angular Material Card Mock Up here? I really like the design of the official website/ cards-action.
