### ISSUE TITLE
md-menu not click able

### ISSUE THREAD

**Issue by emps** [angular/material#6109] opened 2015-12-06 22:54 UTC
ng-click on buttons inside md-menu-item not working
( md-menu-item md-button ) im on master

btw demo of (codepen works)

**Comment by thanhtruong0315** [comment] 2015-12-07 03:53
I had the same error.

**Comment by jayeshanandani** [comment] 2015-12-07 05:17
+1

**Comment by GoulwenBZH** [comment] 2015-12-07 13:27
I had the same problem in rc6 and master.

**Comment by SuperheroicCoding** [comment] 2015-12-07 15:43
Did you check if it's a problem with z-index stacking? The pointer-events are cached by the md-backdrop.

For me, the md-backdrop that gets attached to the body, was in front of the opened menu.

The problem is that the md-open-menu-container is  in RC6 a child of md-menu. If the md-menu is inside a different z-index stacking branch the backdrop can be above it. In your case it's maybe the md-toolbar that has an z-index of 2.

    <md-backdrop> --> z-index: 94
    <any-element> 
      <another element> --> z-index: < 94
        <md-menu/> --> z-index: 95 but it is always under the backdrop because the z-index: 94 of the parent is handled as independent stacking branch.
      </another element>
    </any-element>
</element>

I hope this helps a little bit. When you increase the z-index of the <another-element> you'll loose that click anywhere to close menu behavior (above the area of the another element).

 If you have that z-index problem we should rename or create a new issue with a proper title.

**Comment by brianppoole** [comment] 2015-12-07 19:10
I'm noticing the same thing as @SuperheroicCoding . Here's a short demo of some evidence:

![menu-item-disabled](https://cloud.githubusercontent.com/assets/4633629/11636732/88769a7e-9ceb-11e5-8908-149bd40bdd6a.gif)

Also, I'm noticing the font color changed to white after updating to RC6, but that might be unrelated since I tend to play with the themes a lot. If I have time soon, I'll create a CodePen isolating the issue.

**Comment by SuperheroicCoding** [comment] 2015-12-07 20:57
@brianppoole exactly, thanks for the demo. Yes the font color is maybe from a custom style. Perhaps on md-menu. I had the same issue.

**Comment by sathishvj** [comment] 2015-12-08 07:30
@SuperheroicCoding Is there a workaround z-index we can use?  Also on which element?  I've been trying a bunch of combinations without success.

**Comment by SuperheroicCoding** [comment] 2015-12-08 08:34
@sathishvj 
I don't see a quick fix for that. 

But you can make the menu working again. Try to reduce the md-backdrop z-index until your open menu receives the clicks again. The menu will work, but the closing of the menu when you click outside will not work above the toolbar.

**Closed** 2015-12-08 21:04 UTC
Labels: priority: critical
