### ISSUE TITLE
Link doesn't work on Mobile both iOs and Android

### ISSUE THREAD

**Issue by hengsokly** [angular/material#1948] opened 2015-03-18 06:23 UTC
I have just updated angular-material to the version ( 0.8.3-master-a15347c ). However, when I include jQuery then the link doesn't work anymore in mobile.
Here is my code

    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/angularjs/1.3.6/angular.min.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/angularjs/1.3.6/angular-animate.min.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/angularjs/1.3.5/angular-aria.min.js"></script>
    <script src="/bower_components/angular-material/angular-material.js"></script>

```html
<a href="http://google.com">Google</a>
```

**Comment by marcysutton** [comment] 2015-03-18 18:03
Closing as duplicate of https://github.com/angular/material/issues/1826.

**Closed by marcysutton** 2015-03-18 18:03 UTC
