### ISSUE TITLE
md-dialog's locals not available upon instantiation when using bindToController

### ISSUE THREAD

**Issue by xenit-raven** [angular/material#2449] opened 2015-04-21 10:13 UTC
I have the following code where I would like a variable from outside to be available in the dialog's controller immediately. Why do the locals bind after the constructor's finished?

    showComments(event, node : Node) {
        this.$mdDialog.show({
            controller: CommentsController,
            controllerAs: 'cc',
            templateUrl: resources + '/html/module/comment-dialog.tmpl.html?v=' + lastModified,
            targetEvent: event,
            locals : {
                node : node
            },
            bindToController : true
        })
    }
----------------
    class CommentsController {
        node : Node;
     
        static $inject = ['$mdDialog'];
        constructor(private $mdDialog) {
            console.log('CONSTRUCTOR - node', this.node); // UNDEFINED
        }
     
        debug() {
            console.log('DEBUG - node', this.node); // OBJECT AVAILABLE
        }
    }

**Comment by gkalpak** [comment] 2015-04-23 08:46
Duplicate of #1534 (?)

**Closed** 2015-05-20 12:03 UTC
