### ISSUE TITLE
mdFabSpeedDial - Using ng-repeat in mdFabActions does not hide items generated from ng-repeat

### ISSUE THREAD

**Issue by Kiougar** [angular/material#3275] opened 2015-06-15 22:23 UTC
What the title says.

Example [codepen](http://codepen.io/anon/pen/pJrwLM)

**Comment by topherfangio** [comment] 2015-06-29 00:34
Duplicate of #3224, closing in favor of the one with more discussion. Please feel free to jump into that one :-)

**Closed by topherfangio** 2015-06-29 00:34 UTC
