### ISSUE TITLE
Keyboard disappear in android default browser for inputs!!?

### ISSUE THREAD

**Issue by farzinpashaee** [angular/material#8192] opened 2016-04-24 17:42 UTC
i am trying to test my login form inside android default browser using angular martial input component,  but as soon as focusing into one input keyboard suddenly disappears. same problem on official input demo in https://material.angularjs.org/latest/demo/input

**Comment by ThomasBurleson** [comment] 2016-04-24 21:52
Duplicate of #7945

**Closed by ThomasBurleson** 2016-04-24 21:52 UTC
