### ISSUE TITLE
ng-checked generating too many events

### ISSUE THREAD

**Issue by LastTribunal** [angular/material#9040] opened 2016-07-15 14:54 UTC
ng-checked generating too many events
   <md-checkbox ng-checked="...

http://codepen.io/anon/pen/oLpwWo
F12 to console, click a checkbox to see many many many events...

 -  `Angular Version:` v1.5.7
 -  `Angular Material Version:`v1.1.0-rc.5-master-d593229

**Comment by DevVersion** [comment] 2016-07-15 16:11
I already investigated at that issue a long time ago, and it seems to relate to the inherited native checkbox link function. (See #8284)

**Comment by LastTribunal** [comment] 2016-07-15 22:36
thank you

**Comment by DevVersion** [comment] 2016-07-16 09:30
Let's keep it open, since we should be able to fix that.

**Comment by LastTribunal** [comment] 2016-07-16 21:21
Dude, I can;t believe you're only 16.  Amazing! :D

**Comment by crisbeto** [comment] 2016-07-23 10:23
I'm not sure that this is an issue with Material, but rather Angular's `ngChecked` directive. [You can see that the event fires as often, even if you remove all the checkboxes and you put `ngChecked` on an empty div.](http://codepen.io/crisbeto/pen/XKqXgN?editors=1000)

**Comment by crisbeto** [comment] 2016-08-02 16:59
I decided to invest a little more time into this since I noticed that the digests were being triggered properly when removing the dependency on `ngMaterial`. It turns out that this concerns other built-in Angular directives and is caused by `ngAria` (on which Material has a dependency). 

Here are a couple of examples. Note that the only difference between the two is dependency on `ngAria`: 

1. [This one only triggers the callback twice on load and then once for every click.](http://codepen.io/crisbeto/pen/PzdJEV?editors=1010)
2. [The one triggers 4 digests on load and 2 for each click.](http://codepen.io/crisbeto/pen/vKzZRa?editors=1010)

After looking at the source, it seems like `ngAria` [sets up an additional watcher](https://github.com/angular/angular.js/blob/master/src/ngAria/aria.js#L134) for a specific set of directives, causing the function to be triggered twice. I'll close the issue since this is the intended behaviour, without which `ngAria` wouldn't work properly.

**Closed by crisbeto** 2016-08-02 16:59 UTC
Labels: type: bug
