### ISSUE TITLE
angular materiel  1.0.7 - md-bottom-sheet click on backdrop (md-backdrop) don't close the bottom sheet 

### ISSUE THREAD

**Issue by aviyi** [angular/material#7975] opened 2016-04-11 13:16 UTC
This It happens because md-bottom-sheet-backdrop class on md-backdrop become with _md-backdrop.(underscore)
its angular-material.js at line  6407

**Comment by DevVersion** [comment] 2016-04-11 17:29
Hey @aviyi - I just took a look at your issue and I'm not able to reproduce this on the latest release. Can you provide us a demo or show us what bottomsheet options you're using?

**Comment by aviyi** [comment] 2016-04-12 11:41
Take a look in angular material site  version 1.0.6
https://material.angularjs.org/1.0.6/demo/bottomSheet
compared to 1.0.7
https://material.angularjs.org/1.0.7/demo/bottomSheet
when i clicking on backdrop in 1.0.6 is close the bottom sheet 
in 1.0.7 its  does  not  . 
in addition  when the bottom sheet are open the backdrop of the bottom sheet does not  cover the sideNav (this sidenav are clickable)
see attached image 
![bootmsheet](https://cloud.githubusercontent.com/assets/15788205/14458811/2450961c-00b4-11e6-8e39-7bf561451865.PNG)

**Comment by DevVersion** [comment] 2016-04-12 12:07
@aviyi Thanks for the report, I can reproduce your bug on the `1.0.7` release. It seems to be fixed in the latest release (`v1.1.0-rc2`).

- https://material.angularjs.org/1.1.0-rc2/demo/bottomSheet

If you have any further questions, please let me know.

**Closed by DevVersion** 2016-04-12 12:07 UTC
Labels: needs: investigation
