### ISSUE TITLE
Some error occurred in angularMaterial/md-contact-chips component

### ISSUE THREAD

**Issue by mib008** [angular/material#10172] opened 2016-12-23 05:28 UTC
I’m using the release version v1.1.1, it was occurred when click the remove button on md-chip:
(https://cdn.gitcdn.link/cdn/angular/bower-material/v1.1.1/angular-material.js)

```js
TypeError: Cannot read property 'nextTick' of undefined
    at MdChipsCtrl.removeChipAndFocusInput (angular-material.js:24883)
    at fn (eval at compile (angular.js:14432), <anonymous>:4:516)
    at expensiveCheckFn (angular.js:15485)
    at callback (angular.js:25018)
    at ChildScope.$eval (angular.js:17229)
    at ChildScope.$apply (angular.js:17329)
    at HTMLButtonElement.<anonymous> (angular.js:25023)
    at defaultHandlerWrapper (angular.js:3456)
    at HTMLButtonElement.eventHandler (angular.js:3444)
 
MdChipsCtrl.prototype.removeChipAndFocusInput = function (index) {
  this.removeChip(index);
 
  if (this.autocompleteCtrl) {
    // Always hide the autocomplete dropdown before focusing the autocomplete input.
    // Wait for the input to move horizontally, because the chip was removed.
    // This can lead to an incorrect dropdown position.
    this.autocompleteCtrl.hidden = true;
    this.$mdUtil.nextTick(this.onFocus.bind(this));
  } else {
    this.onFocus();
  }
};
```
 
This error also occurred on https://material.angularjs.org/latest/demo/chips (Edit on CodePen).
I have rewritten local reference to if(this.$mdUtil) this.$mdUtil.nextTick(this.onFocus.bind(this));
Please help investigating this.

**Comment by ppham27** [comment] 2016-12-27 18:46
This is fixed in the master branch. See [Issue #9520](https://github.com/angular/material/issues/9520) and commit [a3b3e7b037fb02acae5c1d979e8373d7e8c93dfd](https://github.com/angular/material/commit/a3b3e7b037fb02acae5c1d979e8373d7e8c93dfd).

**Comment by topherfangio** [comment] 2017-01-04 22:07
Closing as duplicate of #9520.

**Closed by topherfangio** 2017-01-04 22:07 UTC
Labels: needs: triage by dev
