### ISSUE TITLE
md-theme directive doesn't work correctly with md-dialog

### ISSUE THREAD

**Issue by AxxlForce** [angular/material#6221] opened 2015-12-10 13:48 UTC
may be related to #5899 

I assign the parent of md-dialog options to a div on which I apply a theme via md-theme. Not all child elements get themed (see screenshot).

If i use $mdThemingProvider.setDefaultTheme() insted of the md-theme directive, the dialog gets themed correctly. I need to theme my application during runtime though.

![screenshot from 2015-12-10 14-25-36](https://cloud.githubusercontent.com/assets/3379964/11716598/3e7447b6-9f4b-11e5-9861-6cb0c1ac1f63.png)

**Comment by DevVersion** [comment] 2016-02-19 08:15
Yes, duplicate of #5899 and fixed in #7154. Can you please close your issue, so I don't need to reference  it as a duplicate.

**Comment by DevVersion** [comment] 2016-03-14 20:34
Fixed with  SHA a653122cadf5feba15ca6da8fb876098997892dc

**Closed by DevVersion** 2016-03-14 20:34 UTC
