### ISSUE TITLE
Sub-menu of nesting menus can't open

### ISSUE THREAD

**Issue by juliadou** [angular/material#7312] opened 2016-02-26 23:05 UTC
Demo: http://codepen.io/anon/pen/yOLOEa .

How to reproduce:
1. Click on File.
2. Hover over the first "New" option and wait until the sub-menu is open.
3. Mouse straight down to the second "New" option.

The first "New" sub-menu closes and the second sub-menu doesn't open.

It's also reproducible if the second sub-menu is open and you mouse up to the first one.

![nestingmenu](https://cloud.githubusercontent.com/assets/1686525/13367831/4686dfa4-dc9a-11e5-9c10-ed1c85cb1ceb.png)

**Comment by DevVersion** [comment] 2016-02-27 18:20
Closing that issue because it's a duplicate of #6685.

**Closed by DevVersion** 2016-02-27 18:20 UTC
