### ISSUE TITLE
(Bug) md-datepicker sets different dates depending on the inputted format

### ISSUE THREAD

**Issue by jblaketc** [angular/material#9775] opened 2016-10-06 21:59 UTC
**Actual Behavior**:
 -  `What is the issue? *`
I'm getting a different date set in the ng-model, depending which date format I put in the datepicker 
![image](https://cloud.githubusercontent.com/assets/9706971/19172039/78b276a0-8be5-11e6-89e2-a5890600a54a.png)
![image](https://cloud.githubusercontent.com/assets/9706971/19172058/8b96334c-8be5-11e6-8ca5-4c7120b68fac.png)

 -  `What is the expected behavior?`
I expect the 2016-10-06 to set the datetime as "2016-10-06T05:00:00.000Z"

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` 
http://codepen.io/anon/pen/rrJrAR
 -  `Details:`
I manually enter 2016-10-06 and it displays inaccurately in the output of ngModel. I'm doing this at 5pm CST so when I calculate UTC (9pm), I expect the date to be 2016-10-06

**Angular Versions**: *
 -  `Angular Version:` 1.5.5
 -  `Angular Material Version:` 1.1.1

**Additional Information**:
 -  `Browser Type: *` Chrome
 -  `Browser Version: *` Latest
 -  `OS: *` Win 8
 -  `Stack Traces:` None

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by crisbeto** [comment] 2016-10-07 05:24
How are you calculating UTC? It seems to work fine for me, but I'm in a different timezone.

**Comment by StupidIncarnate** [comment] 2016-10-07 06:16
@crisbeto I'm not really sure what you mean by calculating UTC. It's however Angular is handling it from the date picker input to the ngmodel storage. I'm not doing anything special in the code with it; I only noticed it was happening because my e2e test data is in a date string format by some random choice.

I just tried the codepen on my phone and I'm getting the same discrepancy. I'm on -0500 timezone so maybe if you set your comp to cst, you might be able to reproduce.

![screenshot_20161007-010718](https://cloud.githubusercontent.com/assets/276331/19180462/8ef2f7b4-8c2b-11e6-818c-8e82b2f2157e.png)
![screenshot_20161007-010732](https://cloud.githubusercontent.com/assets/276331/19180464/956621ac-8c2b-11e6-9c54-caa6dfa8376c.png)

**Comment by crisbeto** [comment] 2016-10-07 07:04
I guess what I was trying to ask was whether you were doing any extra processing on it. I'll try reproducing it later.

As an aside, we recently switched to re-using some of the logic from Angular's `input[type="date"]`, which also allows you to specify the timezone. E.g. you can try setting `ng-model-options="{ timezone: '-0500'" }"` on the datepicker.

**Comment by crisbeto** [comment] 2016-10-09 12:28
Alright, I see what you mean @StupidIncarnate and @jblaketc, however it doesn't look like there's much we can do about it in Material. The way the default date parsing works is that [the string gets passed through `new Date`](https://github.com/angular/material/blob/master/src/components/datepicker/js/dateLocaleProvider.js#L191) and whatever is returned gets assigned to the model. E.g. you can try these two to reproduce it:

```js
console.log(new Date('2016-10-06'));
console.log(new Date('2016/10/06'));
```
I'm not quite sure _why_ it's adjusting the first one, but in my timezone it does the same, except that the times are `2:00` and `0:00`, whereas yours are `0:00` and `4:00`.

Since Material isn't a date parsing library, we try to keep these defaults as simple as possible and reliant on the browser API. If this is an issue for you, you can provide your custom parsing via the `$mdDateLocaleProvider`. [You can see and example in our docs on how to do custom parsing and formatting.](https://material.angularjs.org/HEAD/api/service/$mdDateLocaleProvider) Let me know if you need any more help.

**Closed by crisbeto** 2016-10-09 12:28 UTC
Labels: needs: investigation

**Comment by jblaketc** [comment] 2016-10-10 20:40
@crisbeto I understand about the default thing. I think it should get patched in material though (even if it's an issue in javascript itself), since otherwise it'd have to be patched in every project.

I'm not sure where in the code it takes the input and converts to a datetime, but I think something like this would fix this weird case:

````javascript

if(date && _.isString(date)) {
    date = 	date.replace(/-/g, '\/').replace(/T.+/, ''));
}
date = new Date(date);
````

We're checking for a string because if they converted it to a date in the parseDate function, then we want to do the passthrough. Otherwise, we're making sure it's a string and making sure to fix the format that causes the bug. Any inputs with / would get ignored. 

Seems to have a good multitude of answers on the issue: http://stackoverflow.com/a/31732581

**Comment by crisbeto** [comment] 2016-10-10 20:44
While this does work, Material also supports custom formatting and this will break once users change it.

**Comment by jblaketc** [comment] 2016-10-10 20:48
Even if you do that fix right before you convert to date and stick it in the ng-model, and ONLY before you stick it in the ng-model? I'd assume it'd then get read out by the formatter, and because it's already a date object, format it no problem.

**Comment by crisbeto** [comment] 2016-10-10 20:57
Yes. The problem is that you never know how people might end up using it. Also this opens up the door to having to deal with all other kinds of edge cases related to dates (see https://github.com/angular/material/issues/9714)
