### ISSUE TITLE
The checkbox directive is work incorrect

### ISSUE THREAD

**Issue by phamtuananh791994** [angular/material#8733] opened 2016-06-11 04:59 UTC
I'm using demo in https://material.angularjs.org/latest/api/directive/mdCheckbox with safari and find the checkbox directive is work incorrect with color. This is a video.
https://youtu.be/V9KwWK8V1Bo

**Comment by DevVersion** [comment] 2016-06-11 08:39
I can't see anything wrong.

Please use the issue template and explain what's the issue? and what's the expected behavior?

**Comment by wesleycho** [comment] 2016-06-11 13:32
This looks like an issue - I was able to reproduce this [here](http://codepen.io/wesleycho/pen/zBrXEQ) on Safari. If you check any two consecutive checkboxes in reverse order quickly then you should see this issue (i.e. the 5th then 4th one).

**Comment by phamtuananh791994** [comment] 2016-06-11 15:31
That right. I see it more than one but i can't described it with issue template.

**Comment by ThomasBurleson** [comment] 2016-06-12 14:12
This is an edge case related to animations. Nevertheless, this issue is closed as part of our ‘Surge Focus on Material 1 and Material 2' efforts.  For details, see our forum posting @ http://bit.ly/1UhZyWs.

**Closed by ThomasBurleson** 2016-06-12 14:12 UTC
Labels: browser: Safari, type: bug
