### ISSUE TITLE
md-grid-list is broken in Safari

### ISSUE THREAD

**Issue by delad77** [angular/material#1927] opened 2015-03-16 20:35 UTC
Hi,

All the simple md-grid-list demos don't work on Safari. Just open the following:
https://material.angularjs.org/#/demo/material.components.gridList

It happens on iOS and desktop alike. Desktop is better.
It is currently blocking my app development since I was counting on it and the only thing that i didn't check was this one... have you tested the grid list under safari at all? I have seen several issues but I can't seem to find a solution. 

Thank you !
E.

**Comment by mwymann** [comment] 2015-03-17 09:10
+1

**Comment by JulianWielga** [comment] 2015-03-17 17:41
https://github.com/angular/material/commit/4572e80a20cbe8bb5d3415a9ffb0fde8150ff084

**Comment by depoll** [comment] 2015-03-19 23:05
+1 -- would love to see the fix go in soon.

**Comment by bonatoc** [comment] 2015-03-20 04:44
@depoll 
If you're in ahurry, you can manually fix this in : 
[https://github.com/JulianWielga/material/commit/4572e80a20cbe8bb5d3415a9ffb0fde8150ff084](https://github.com/JulianWielga/material/commit/4572e80a20cbe8bb5d3415a9ffb0fde8150ff084)

**Comment by amay0048** [comment] 2015-04-04 10:26
Replicated 
![screen shot 2015-04-04 at 9 18 25 pm](https://cloud.githubusercontent.com/assets/6089717/6992291/2f3f3228-db11-11e4-97d8-a0c6cea471a9.png)

**Comment by amay0048** [comment] 2015-04-04 12:45
Found this was caused by a missing trailing brace in calc css string which mean that safari wouldn't apply it. Just submitted a pull request with a fix for this.

**Comment by ThomasBurleson** [comment] 2015-04-04 14:11
Fixed with 33049cff96cd643e76159fc2d72cbd9fb911245c

**Closed by ThomasBurleson** 2015-04-04 14:11 UTC
Labels: ui - browser
