### ISSUE TITLE
md-fab-speed-dial with fab action buttons hidden, get in front of other elements on the page

### ISSUE THREAD

**Issue by fjnogueira** [angular/material#5021] opened 2015-10-05 15:38 UTC
![delete_button_does_no_work_below_fab_shadow](https://cloud.githubusercontent.com/assets/9854191/10285175/8461e2b0-6b7f-11e5-9a2e-865d0db40ecf.gif)
when include a fab speed dial, it obstructs access to elements (when hidden), a possible hack might be changing the z-index of the hidden fab action buttons when hidden

**Comment by topherfangio** [comment] 2015-10-05 16:07
Duplicate of #4259. Should be closed when #4847 is merged.

**Closed by topherfangio** 2015-10-05 16:07 UTC

**Comment by auty** [comment] 2015-10-16 00:44
@topherfangio I'm still encountering this issue using v0.11.4. @fjnogueira Have you been able to confirm the fix using v0.11.4?

**Comment by topherfangio** [comment] 2015-10-16 01:43
@auty Can you provide a Codepen? Also, what browser are you using?

**Comment by auty** [comment] 2015-10-16 23:04
@topherfangio Here's the Codepen http://codepen.io/auty/pen/Vvrarm/. It appears the placement of the id attribute is causing the issue. Having "id='FAB'" in the div causes the issue seen above. Moving "id='FAB'" to the element <md-fab-speed-dial> resolves the issue.

**Comment by topherfangio** [comment] 2015-10-17 18:41
@auty Ah, indeed. The speed dial achieves the proper effect using the CSS property `pointer-events: none`. So, if you wrap it in another `<div>`, you'll need to add it there as well.

That said, the FAB buttons have a `md-fab-bottom-right` class that you can apply which will do the positioning you want without the extra wrapper. You just need to make sure it is a sibling to the scrollable content, and whatever wraps both of those has to have `position: relative`.

Here is an example of what I mean: http://codepen.io/topherfangio/pen/gaXxva

**Comment by auty** [comment] 2015-10-17 23:09
@topherfangio Thanks! I really appreciate the thorough explanation.
