### ISSUE TITLE
Error on Autocomplete Demo

### ISSUE THREAD

**Issue by rhllor** [angular/material#5424] opened 2015-10-29 10:14 UTC
Hi, 
I don't understand how use mdAutocomplete and mdNotFound with clickable item into mdNotFound.
On Demo(1.0.0 RC1) the link is clickable and working but on codepen the link is not clickable. If i use the exemple on my project ng-click don't work as codepen. 

Any Issue for this problem? 
Regards

**Comment by topherfangio** [comment] 2015-10-30 00:08
It is broken on the Codepen because our links unfortunately always point to HEAD/master (this issue will be fixed in the next release). So, this is an actual/reproducible bug on both HEAD and the codepen.

We will investigate.

@robertmesserle Any chance this has something to do with the changes you made for the IE scrollbar fix?

**Comment by robertmesserle** [comment] 2015-10-30 00:57
Seems unlikely, but it's possible.

**Comment by rhllor** [comment] 2015-11-02 08:52
Thanks all for reply

**Comment by topherfangio** [comment] 2015-11-06 00:35
I don't believe this was actually fixed by 5ae3d4c, I need to find a different solution and/or do some more testing to ensure the fix I had in mind doesn't break anything in IE.

**Comment by topherfangio** [comment] 2015-11-09 23:33
I'm going to go ahead and bump this to RC5 so that I can test it more thoroughly when I get back to my IE machine.

**Comment by DevVersion** [comment] 2016-01-22 20:13
Is this related to #5526?

**Comment by rhllor** [comment] 2016-03-03 22:18
yep

**Closed** 2016-04-28 20:26 UTC
Labels: P4 - Reported By or General PRs/Errors or Edge Cases, type: bug
