### ISSUE TITLE
md-datepicker: transparent look

### ISSUE THREAD

**Issue by kschwidder** [angular/material#5170] opened 2015-10-14 19:56 UTC
since 0.11.4 the datepicker is shown in transparent mode when opening.
in 0.11.3 it is correct. 

Can be seen in latest demo page.

**Comment by biomassives** [comment] 2015-10-14 19:57
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (116/100 (115%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o3.sgmail.github.com ([192.254.112.98]:50888)
	by server23.websitehostserver.net with esmtps (TLSv1.2:DHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.85)
	(envelope-from <bounces+848413-b37a-greg=biomassiv.es@sgmail.github.com>)
	id 1ZmSAW-003U0M-1n
	for greg@biomassiv.es; Wed, 14 Oct 2015 14:57:01 -0500
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=rkf5HBZR31b4oVtO5+921ipmuLQ=; b=dphgCElg5IwzsNXU
	pAAMRE9idGQbFHVxdkfz1WuOO9C015XyfO5Acqq/4Hr6uEo/uyGq4lW8s2UjVq3f
	6wQ4+pM45WaV7fRH3ybZaOaHWXfOEwk7N4G0teJ9sID2kfRq9EuDgkw6SpdTxl6Z
	OLKe+Qm+gk4tx8nDnVN7+xC0fAg=
Received: by filter0601p1mdw1.sendgrid.net with SMTP id filter0601p1mdw1.26897.561EB38A22
        2015-10-14 19:56:58.600612362 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0005p1iad1.sendgrid.net (SG) with ESMTP id vCVjqDmZQ3eq3xfdMGeoaw
	for <greg@biomassiv.es>; Wed, 14 Oct 2015 19:56:58.414 +0000 (UTC)
Date: Wed, 14 Oct 2015 12:56:58 -0700

**Comment by bastienJS** [comment] 2015-10-14 20:07
duplicate of a duplicate :P https://github.com/angular/material/issues/5165

**Comment by ThomasBurleson** [comment] 2015-10-14 21:52
Fixed.

**Closed** 2015-10-14 21:51 UTC

**Comment by mattiLeBlanc** [comment] 2015-11-01 23:42
Hi, Just updated to 0.11.4 using MeteorJS and ran into the transparency issue. How do I apply the fix? For Meteor there only seems to be version 0.11.2, 0.11.4. Best just to downgrade to .11.2 and wait for 1.0.0 to hit Atmosphere?

**Comment by davidrensh** [comment] 2015-11-17 16:43
It's not been fix yet.
![capture1](https://cloud.githubusercontent.com/assets/14281421/11217840/9d1ce2d0-8d0f-11e5-8ef3-196a56171ac6.GIF)
![capture2](https://cloud.githubusercontent.com/assets/14281421/11217846/a61ffdea-8d0f-11e5-95a3-9dc1582d2b0a.GIF)

**Comment by mattiLeBlanc** [comment] 2015-11-17 23:47
You can apply the styles for yourself until there is a fix in .0.11.5

```
// FIX FOR DATEPICKER in version 0.11.4

.md-datepicker-calendar, .md-datepicker-input-mask-opaque
    background: rgb(255,255,255);


.md-calendar-date.md-calendar-selected-date .md-calendar-date-selection-indicator, .md-calendar-date.md-focus.md-calendar-selected-date .md-calendar-date-selection-indicator
    background: rgb(33,150,243);
    color: rgb(255,255,255);
    border-color: transparent;

.md-calendar-date-selection-indicator:hover
    background: rgb(224,224,224);

.md-calendar-day-header
    background: rgb(224,224,224);
    color: rgba(0,0,0,0.87);

.md-calendar-date-disabled, .md-calendar-month-label-disabled
    color: rgba(0,0,0,0.26);
```

**Comment by davidrensh** [comment] 2015-11-18 01:52
Another solution is use:
 <script src='https://cdn.gitcdn.xyz/cdn/angular/bower-material/v1.0.0-rc4/angular-material.js'></script>

**Comment by lyurko** [comment] 2015-11-18 16:02
Thanks @mattiLeBlanc - that did the trick!

**Comment by davidrensh** [comment] 2015-11-18 16:22
Matti' solution is working for style, but it could be date message event issue.

**Comment by rjmcguire** [comment] 2015-12-12 18:29
The mattiLeBlanc CSS didn't fix the issue for me. I had to add md-calendar { background-color: white; }

**Comment by mattiLeBlanc** [comment] 2015-12-13 00:59
This is without my fix:
![image](https://cloud.githubusercontent.com/assets/5285035/11764756/dff7ad70-a190-11e5-8efa-c84fc1728b7d.png)

And this is with my fix:
![image](https://cloud.githubusercontent.com/assets/5285035/11764757/ee70a7d0-a190-11e5-966e-dae957461501.png)

So not sure why you explicitly needed to set the background :?

**Comment by rjmcguire** [comment] 2015-12-13 09:03
Agreed, it made no sense looking at all the classes affecting the
background.

I'm mixing bootstrap and angular a bit so maybe that caused it.
