### ISSUE TITLE
dialog: this[0].focus is not a function

### ISSUE THREAD

**Issue by evoker** [angular/material#5363] opened 2015-10-26 15:21 UTC
In some cases, confirmation dialogs give the message in the title. This happens when clicking both cancel and ok callbacks.

I have pinpointed the error to this line:

     if (!options.$destroy) options.origin.focus();

**Comment by topherfangio** [comment] 2015-10-27 17:06
Any chance you could provide a Codepen which shows this bug in action? It would really help us track down why the `origin.focus()` is causing an issue.

I think it has something to do with the dialog's `targetEvent` option, but I am not sure.

@EladBezalel Can you take a quick look? I think it's something in the `getBoundingClientRect()` function due to it returning `focus   : angular.bind(source, source.focus)`. Can possibly fix with `source.focus || angular.noop` but I'd like you to double-check my thinking on this.

**Comment by EladBezalel** [comment] 2015-10-27 18:32
@evoker a codepen would be very helpful!

@topherfangio sounds about right, when a codepen will be available let's take a look and see what's going on in there.

**Comment by Tyrannmisu** [comment] 2015-11-03 13:44
I Get the same error with material 1.0.0-rc2.
In my case it happens if i delete an element that will be removed from an ng-repeat after a confirm. (but i don't know if this really causes the issue).

I will try to reproduce this in an codepen.

**Comment by leftstick** [comment] 2015-12-22 05:40
I think this might be caused by the `targetEvent`. I have the same issue while i `merged` the `targetEvent` as following:

```javascript
var defaults = {
        title: 'Confirm',
        content: ''
};

var opts = angular.merge({}, defaults, data);

var confirm = $mdDialog.confirm()
            .title(opts.title)
            .textContent(opts.content)
            .targetEvent(opts.event)
            .ok('OK')
            .cancel('CANCEL');

$mdDialog.show(confirm);
```

Just use the original `$event` will be fine to solve this

**Comment by EladBezalel** [comment] 2015-12-22 07:34
@Tyrannmisu Of course you get this issue, you're sending the index as an event.

@leftstick you can try use `angular.extend`

**Closed by EladBezalel** 2015-12-22 07:34 UTC
Labels: needs: investigation, type: bug

**Comment by oshri** [comment] 2016-09-20 06:47
I solve this issue by set { targetEvent: null }
