### ISSUE TITLE
multiple md-select overflows incorrectly the input-container

### ISSUE THREAD

**Issue by dohomi** [angular/material#6312] opened 2015-12-15 10:32 UTC
Hello

there is an issue if the selected values of ```md-select```expand ```md-input-container```. Here the codepen and a screenshot:

http://codepen.io/anon/pen/LGGNoo

<img width="535" alt="screen shot 2015-12-15 at 11 28 17" src="https://cloud.githubusercontent.com/assets/489221/11808213/4e42ad40-a31f-11e5-9305-12cc067a62b0.png">

I suggest the ```md-select```should grow with the selected options and expand the ```md-input-container```height.

**Comment by topherfangio** [comment] 2015-12-16 17:06
@rschmukler Not sure if this is the best solution, but here is a quick fix/workaround for this issue:

```css
.md-select-value *:first-child {
  width: calc(100% - 24px);
}
```

I don't see anything in the spec about how to handle this situation, but it looks like we're already assuming that we will cut it off and use an ellipsis, it just wasn't working correctly.

**Comment by Masadow** [comment] 2015-12-18 13:23
:+1:

**Comment by nicgirault** [comment] 2016-01-09 10:43
:+1:

**Comment by bostondv** [comment] 2016-01-18 14:36
+1

**Comment by yccteam** [comment] 2016-01-19 12:21
I've noticed this bug as well. It seems to be working fine on version 0.10.x but not on versions 0.11.x and on
Version 10:
http://plnkr.co/edit/T1UzWlWY8aaMWrM9xPWb?p=preview
There's also a version 0.11 there that was added locally so you can switch to see the bug on version 0.11.
Here's a live example with 1.0.2:
http://plnkr.co/edit/hTBqUnFQQekNEy5YUVc5?p=preview

**Comment by pasqLisena** [comment] 2016-01-19 15:45
+1

**Comment by nicgirault** [comment] 2016-02-01 19:33
+1

**Comment by anatolyz** [comment] 2016-02-08 11:18
I found this workaround:
http://codepen.io/anon/pen/MKzYNY
Just fix styles:
`.md-select-value *:first-child {
    flex: 1 1 auto;
}`

**Comment by dohomi** [comment] 2016-02-09 02:40
@anatolyz did you try your workaround inside of Firefox? For me the workaround only works with Chrome.

**Comment by anatolyz** [comment] 2016-02-09 08:47
@dohomi, I checked in versions 41.0.1, 43.0.1, 44.0.1 (updated twice), it works.

**Comment by norfolkislander** [comment] 2016-02-22 05:02
It would be great if the overflow was hidden. It would be even better if you could change the display to show something like "5 of 25 selected"

**Comment by ThomasBurleson** [comment] 2016-04-28 19:46
This issue is closed as part of our deprecation effort.
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).

**Closed by ThomasBurleson** 2016-04-28 19:46 UTC
Labels: - Easy fix, ui: CSS

**Comment by bobwah** [comment] 2016-05-24 15:11
how is this closed?

**Comment by EmmanuelPREVOST** [comment] 2016-05-24 15:12
@bobwah https://github.com/angular/material/issues/6312#issuecomment-215541062 can't you read ?

**Comment by bobwah** [comment] 2016-05-24 15:19
I can read it was deprecated when could have been fixed with simple css within material rather than having to apply our own...

**Comment by dohomi** [comment] 2016-05-25 01:22
If you check out the newest version of material you will see that the handling changed: now every option is wrapped into a new line

**Comment by volmerf** [comment] 2016-09-19 09:28
With Angular Material 1.1.1 this behaviour changed again. Instead of putting the selected option on separate lines they are now aligned next to each other again. This causing the select to get a growing width after selecting more options. Is there a way to fix this? See screenshot
![screen shot 2016-09-19 at 11 27 00](https://cloud.githubusercontent.com/assets/4939781/18627583/10394a22-7e5c-11e6-8908-0c8b93306bc7.png)
![screen shot 2016-09-19 at 11 27 45](https://cloud.githubusercontent.com/assets/4939781/18627592/1bfed7c8-7e5c-11e6-97fc-e388f16dc8ac.png)

**Comment by topherfangio** [comment] 2016-09-30 19:34
@volmerf The `md-select` is designed like most HTML elements to grow and shrink based on the size of it's content. If yours is too large, you have a few options:

1. Set a `max-width` in the CSS as I've done here: http://codepen.io/topherfangio/pen/amLbEo
2. Just set the `width` in the CSS, or
3. Use `flex` to make it take up a certain size in it's container.

All three of these will ensure that the text is truncated when there is too much to fit.

Are you facing a situation where one of the three options above won't work?

**Comment by khichar-anil** [comment] 2016-10-05 20:09
@topherfangio : Nice suggestion. You saved my time.

**Comment by garretwilson** [comment] 2017-02-09 22:28
> Are you facing a situation where one of the three options above won't work?

Yes, this seems to be broken. Sure, if I put `flex="30"` on my `<md-input`> it will keep the contained `<md-select>` from growing more than 30% of the width of my `$mdDialog`, even though I keep selecting items in the list:

```html
<div layout="row" layout-xs="column" layout-padding>
  <md-input-container flex="30">
    <label>Foo</label>
      <md-select ng-model="dialog.foo" ng-model-options="{trackBy: '$value.id'}" multiple>
```

But here's the huge problem: if I keep selecting items in the list, soon the `$mdDialog` will start increasing its width _as if the `<md-select>` were expanding horizontally_!! It's as if I've prevented the _visible_ part from expanding, but something invisible is still expanding horiontally. Specifically the `<div layout="row"` is still expanding, taking up the full space, and making the dialog grow wider, even though the `<md-select>` is still at its 30%-of-the-width size.

**Comment by topherfangio** [comment] 2017-02-10 21:33
@garretwilson Can you provide a Codepen that I can play with and maybe fix?

**Comment by garretwilson** [comment] 2017-05-04 22:01
Now in Angular 1.6.4 with Angular Material 1.1.3, nothing I can do will keep the selection dialog from growing wider than my `$mdDialog`. 😦 

```html
<div layout="row" layout-padding>
  <md-input-container flex>
    <label>Analytics</label>
    <md-select ng-model="dialog.selectedCategories" ng-model-options="{getterSetter: true, trackBy: '$value.id'}" multiple>
      <md-option ng-repeat="category in dialog.getCategories()" ng-value="category">{{category.label}}</md-option>
    </md-select>
  </md-input-container>
</div>
```

I haven't had time to create a Codepen. But you should be able to reproduce it---very basic stuff I'm doing here.

**Comment by njcaruso** [comment] 2017-06-19 14:57
This is working fine for me - just change ```white-space: no-wrap``` to:

```
  .md-select-value {
    span:first-child {
      white-space: normal;
    }
  }
```

**Comment by mih-kopylov** [comment] 2017-06-29 07:11
@ThomasBurleson Could you please reopen this issue - there's a simple solution that @njcaruso has provided above. 
This bug is really annoying and is looks very easy to be fixed.

**Comment by garretwilson** [comment] 2017-11-21 20:49
Please reopen this. This really gets in the way of development.

**Comment by Splaktar** [comment] 2017-11-22 08:49
@garretwilson please open a new issue with a CodePen demonstrating the issue. If possible, it would be nice to know if it was working for you in `1.1.0`.
