### ISSUE TITLE
Virtual Repeat does not like top/bottom margins on its child elements 

### ISSUE THREAD

**Issue by averas** [angular/material#6574] opened 2016-01-07 13:43 UTC
If you take the example on Virtual Repeat - Deferred Loading from the Angular Material page and add a margin to the repeated elements the scrolling becomes erratic after one has scrolled to the end.  Even though it seems that the elements don't keep scrolling, the actual scrolling position keeps increasing so that when you want to scroll up again you have to scroll the same distance you tried to scroll down.

Example (also changed the number of elements to 100):
http://codepen.io/anon/pen/EPWqvo

(Chrome/OSX)

**Comment by RolandHeath** [comment] 2016-01-08 00:49
Related/duplicate of #4169

**Closed** 2016-01-13 02:45 UTC
