### ISSUE TITLE
add chips readonly display as tags

### ISSUE THREAD

**Issue by ilovett** [angular/material#7601] opened 2016-03-16 19:53 UTC
I think the readonly styles could hide the box shadow and not modify the cursor... something like:

```
md-chips.md-THEME_NAME-theme {

  &[readonly="true"] {
    
    .md-chips {
      cursor: inherit;
      box-shadow: none;
    }

  }
```

Additionally it would be nice to have some optional class to display chips inline in readonly format.

I'd be happy to contribute if a PR is solicited.

**Comment by topherfangio** [comment] 2016-03-16 20:44
There is no box-shadow on chips at the moment, and the cursor is currently always the default cursor, so I'm not following you 100%.

In regards to your second statement:

> Additionally it would be nice to have some optional class to display chips inline in readonly format.

Have you looked at the Static Chips demo available at https://material.angularjs.org/latest/demo/chips? It sounds like what you want.

**Comment by ilovett** [comment] 2016-03-16 21:55
Thanks, I checked out HEAD docs and see that the cursor seems to be fixed for readonly.

Regarding the box shadow, it is on the `md-chips-wrapper`

The problem with static chips is that it doesn't work with `ng-repeat`.

Check out this [codepen](http://codepen.io/ilovett/pen/EKZyVR)

**Comment by topherfangio** [comment] 2016-03-17 17:58
@ilovett Gotcha; I didn't realize that the bottom line was a box shadow; on most of our other components, it is a `bottom-border` so I was confused.

That said, I don't think we can/should automatically remove the box shadow in readonly-mode. If a developer is actually using it as an input (like it was intended), then users should still see the bottom line even in readonly mode.

Perhaps we should add a ".md-static" (or maybe ".md-chips-as-tags" or something) class which removes that styling. I'm going to mark this as a feature request and prioritize it, but if you were interested in submitting a PR, I would be happy to help you through it and figure out a good solution.

**Comment by ilovett** [comment] 2016-03-17 18:04
Great, thanks.  Sure, I've forked material and have successfully built and opened up demos with `gulp watch-demo`.  Should I just go ahead with the idea of adding a specific overriding class?  If so let me know the preferred nomenclature.

**Comment by topherfangio** [comment] 2016-03-17 18:13
Yeah, that would be great! I'd say go ahead and make it `md-static`. I think that will work the best and goes along with our current nomenclature.

**Comment by ilovett** [comment] 2016-03-21 17:36
Great, I've opened my first pull request... please let me know if theres anything you would like changed!

**Comment by ThomasBurleson** [comment] 2016-04-28 19:34
This issue is closed as part of our deprecation effort. 
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).

**Closed by ThomasBurleson** 2016-04-28 19:34 UTC
Labels: P4 - Reported By or General PRs/Errors or Edge Cases, type: enhancement
