### ISSUE TITLE
icon: id does not replace url links

### ISSUE THREAD

**Issue by KlausSievers** [angular/material#10794] opened 2017-07-11 06:57 UTC
**Actual Behavior**:
If you insert the same icon serveral times, the id is extended with "_cache"+Uid, to have an unique id. The querySelector for the replacement is querySelectorAll('[id]'). 

The problem comes with custom svg icons, which have a clip-path in the def-tag.  In the svg itself the relation is created with clip-path="url(#id)". Thus the id of the clip-path is replaced too, the link refers to nothing.
In my case this leads to not displaying the icon, when it should appear for the second time.

The clip-path is just the example in my case. The same problem could occure with all tags, which are identified with their id within the svg, like pattern, ...

**AngularJS Versions**: 
 -  `AngularJS Version:` 1.4.8
 -  `AngularJS Material Version:` 1.1.1

**Additional Information**:
 -  `Browser Type:` Chrome
 -  `Browser Version:` 59.0.3071.115
 -  `OS:` Windows 10

**Comment by Splaktar** [comment] 2018-08-02 19:26
Duplicate of https://github.com/angular/material/issues/8689 which has open PR https://github.com/angular/material/pull/11342.

**Closed by Splaktar** 2018-08-02 19:26 UTC
Labels: resolution: duplicate
