### ISSUE TITLE
md-fab-speed-dial not working for first time.

### ISSUE THREAD

**Issue by jainshravan123** [angular/material#8156] opened 2016-04-21 13:51 UTC
When i am clicking on first time on fab, it's not working. After second click, it is woking fine. And i want that it md-actions must be hidden for first time but these are showing by default while md-open="false".
Please help me. It may look like that it is copy of others but i didn't find any correct answer so please don't close it. 

<img width="112" alt="screen shot 2016-04-21 at 7 15 57 pm" src="https://cloud.githubusercontent.com/assets/6860473/14711130/d5497dce-07f5-11e6-96ab-aa0c6983cc4f.png">
<img width="1074" alt="screen shot 2016-04-21 at 7 18 04 pm" src="https://cloud.githubusercontent.com/assets/6860473/14711131/d5a7cbae-07f5-11e6-8a38-2544d44bb86f.png">

**Comment by ThomasBurleson** [comment] 2016-04-21 13:51
Closing this issue due to insufficient information. Please resubmit with:

----
Required
----

**Behavior**:
-  What is the issue? * 
-  What is the expected behavior? 

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue :
-  Details: 

**Angular Versions**: *
-  Angular Version: 
-  Angular Material Version: 

**Additional Information**:
-  Browser Type: *
-  Browser Version: *
-  OS: *
-  Stack Traces: 

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

**Closed by ThomasBurleson** 2016-04-21 13:51 UTC
