### ISSUE TITLE
Child alignment demo isn't working on 1.0.0

### ISSUE THREAD

**Issue by zevmo** [angular/material#6361] opened 2015-12-17 13:25 UTC
It appears that the demo example for the child alignment feature (https://material.angularjs.org/latest/layout/alignment) is not changing the toolbar results, nor the example code. It seems that there is a lack of a background there too. :)

![screen shot 2015-12-17 at 8 23 16 am](https://cloud.githubusercontent.com/assets/2286035/11870642/86677952-a497-11e5-9def-b2dca18fe67b.png)

**Comment by ngraef** [comment] 2015-12-18 00:31
Duplicate of #6319

**Closed** 2016-02-01 16:40 UTC
Labels: P2 - Planned Work / Team PRs, resolution: duplicate, type: docs, ui: flexbox

**Comment by ThomasBurleson** [comment] 2016-02-01 20:40
Fixed with SHA da53c00
