### ISSUE TITLE
mdSelect causes page to jump to top in firefox(again  #3020 )

### ISSUE THREAD

**Issue by xtiggerk** [angular/material#3479] opened 2015-06-26 12:36 UTC
Hi, 
i confirm this issues on Firefox, when you open a md-select and click an item in the list, it jumps up right to the bottom of the md-select. 
If you open a md-select, and click outside to close it, it jumps up to top. :/

**Comment by rschmukler** [comment] 2015-06-28 22:14
Just checked the [demo](http://material.angularjs.org/#/demo/material.components.select) and could not reproduce the issue. Could you submit a codepen or something showcasing this?

**Comment by dreamoftrees** [comment] 2015-06-29 00:42
I'm also getting this error, but only with Firefox (mac) version: 38.0.5

Not 100% sure but may be something to do with handleHiddenChange function on autocompleteController.js

Demo:
http://codepen.io/anon/pen/QbaayZ

**Comment by xtiggerk** [comment] 2015-06-29 09:21
Thanks for the demo, issues 'works' on Firefox 38 (windows) and Firefox developer 42 (windows too)

**Comment by rschmukler** [comment] 2015-06-30 15:01
Can confirm issue with *autocomplete* on firefox, but select seems to be working as expected.

Can you guys confirm that [the select works](http://codepen.io/anon/pen/JdMgZb) for you in firefox?

**Comment by xtiggerk** [comment] 2015-06-30 15:23
Hey,
the select doesn't work on Firefox webdeveloper 40.0a2 (2015-06-22) and Firefox 38.0.5 (sorry ;) same issues)
Windows 8.x

**Comment by dreamoftrees** [comment] 2015-07-03 02:56
Both the select and autocomplete still scroll to the top of the page when selected. I'm assuming it's the same select component that is effecting both.

Test Results on mac(10.10.3)
Firefox (38.0.5). - Fails, scrolls to top
Chrome (43.0.2357.130 (64-bit)). - Pass, doesn't scroll
Safari (8.0.6 (10600.6.3)). - Pass, doesn't scroll

**Comment by rschmukler** [comment] 2015-07-09 15:23
@dreamoftrees and @xtiggerk can you check this demo which is using the code off of master. [demo](http://codepen.io/anon/pen/VLxmyM) is working for me with Firefox 38.0.5 on OX X. Thanks!

**Comment by xtiggerk** [comment] 2015-07-09 15:28
Works fine for me :) on windows 8.1 FF and FF developer
Thanks

**Comment by rschmukler** [comment] 2015-07-09 15:29
@xtiggerk thanks for the super quick reply. Closing!

**Closed by rschmukler** 2015-07-09 15:29 UTC
Labels: bug, Demo Needed

**Comment by AkhilNaidu09** [comment] 2017-06-06 11:29
@rschmukler Iam still getting this issue in Firefox and as well as in iPad also
https://codepen.io/anon/pen/VLxmyM. i think we should re-open this isse.
Firefox version : 53.0b1 (32-bit)

**Comment by csvital** [comment] 2018-02-12 08:40
@rschmukler I am still getting this error too in Chrome (64.0.3282.140). I tried material v1.1.3, v1.1.5, v1.1.7 and result not changed. When I clicked an option in mdSelect it jumps to bottom, to the mdselect where it is

**Comment by Splaktar** [comment] 2018-02-18 06:50
@csvital this fix was improved in 1.1.5 via https://github.com/angular/material/pull/10549 and is still working in 1.1.7. 

If you are seeing a problem with a select in a dialog, https://github.com/angular/material/issues/9724 is tracking that. 

If your problem is something else, please open a new issue with a CodePen reproduction.
