### ISSUE TITLE
Card directive do not have the correct padding/margin on Internet Explore

### ISSUE THREAD

**Issue by ahweis** [angular/material#3472] opened 2015-06-26 07:05 UTC
The content part of the card directive do not have the correct spacing when rendered in Internet Explore.

_Example:_
Open the demo page for the card directive in Internet Explore:

https://material.angularjs.org/latest/#/demo/material.components.card

**Comment by topherfangio** [comment] 2015-09-28 15:28
Duplicate of #2974.

**Closed by topherfangio** 2015-09-28 15:28 UTC
Labels: browser: IE, priority: medium
