### ISSUE TITLE
(bug) Ripple effect in md-list directive

### ISSUE THREAD

**Issue by thiagofront** [angular/material#2737] opened 2015-05-05 20:59 UTC
I have a problem
I am using angular material for making a mobile app with Cordova
only the ripple effect in lists is very annoying when I give scroll

**Comment by mckenzielong** [comment] 2015-05-05 21:41
dupe of https://github.com/angular/material/issues/2430?

**Comment by thiagofront** [comment] 2015-05-05 22:19
there she spoke only `md-button` directive. But the problem is in all directives that somehow use the ripple effect

**Comment by marcysutton** [comment] 2015-05-06 20:17
List controls use `md-buttons` under the hood, pretty sure this is still a duplicate.

**Closed** 2015-05-12 16:44 UTC
