### ISSUE TITLE
Firefox 50.1.0 issue - scroll to top when selecting/closing md-autocomplete dropdown

### ISSUE THREAD

**Issue by irinaMbarbu** [angular/material#10272] opened 2017-01-18 16:50 UTC
**Actual Behavior**:
 -  `Browser is scrolled to top when selecting/closing autocomplete dropdown*`
 -  `Scroll should stay in the same place`

**CodePen** (or steps to reproduce the issue): *
 -  `http://codepen.io/eloyleonardo/pen/QbZvwG`
 -  `this was also reported in https://github.com/angular/material/issues/3511 , so there is also the above example that for us is not working added by eloyleonardo`

**Angular**:
 -  `Version: v1.6.1*`

**Additional Information**:
 -  `Browser Type: Firefox*`
 -  `Browser Version: 50.1.0*`
 -  `OS: Windows 10*`
----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by ahlarsen** [comment] 2017-02-02 11:56
+1
I'm experiencing the same problem, it seems that the scroll offset is not set correctly after close as the body gets the top property set when opened which causes the scroll to top. Same goes for the dialog and properly also other components.

**Comment by murhum1** [comment] 2017-02-14 11:10
+1, experiencing the same issue with both md-select and md-dialog.

**Comment by leobustamante** [comment] 2017-02-16 20:50
I'm experiencing the same problem, and I can't rollback to 1.1.1 version.

Does anyone have a workaround or a definitive solution for this issue?

tks

**Comment by nganbread** [comment] 2017-02-19 22:28
Im still experiencing this in versions 1.1.1-1.1.3 for IE(11.0.10240.17113) and FF(51.0.1-32bit)

**Comment by nganbread** [comment] 2017-02-19 22:29
Though, strangely enough I have another webapp I manage that is on 1.1.0 that doesn't seem to suffer from this issue...

**Comment by nganbread** [comment] 2017-02-19 22:58
My workaround for the moment (and the reason why https://material.angularjs.org/latest/demo/select isn't affected by this issue) is to make the `<body>` non scrollable and 'delegate' the scrolling (and all content) to a full sized child

codepen fork + fix: http://codepen.io/nganbread/pen/QdXpBe
```scss
body{
    overflow: hidden;
    max-width:100%;
    max-height:100%;

    > div {
        overflow: auto;
        display: block;
        max-height: 100%;
    }
}
```

**Comment by andrescachero** [comment] 2017-03-03 17:33
+1 So far fixed with @nganbread workarround

**Comment by leobustamante** [comment] 2017-03-03 20:46
> My workaround for the moment (and the reason why https://material.angularjs.org/latest/demo/select isn't affected by this issue) is to make the <body> non scrollable and 'delegate' the scrolling (and all content) to a full sized child

@nganbread thanks for your workaround. It fixes the scrolling issue but it causes a layout issue: an extra scrollbar(full window) appears when options are visible.

**Comment by JonathanOne** [comment] 2017-03-09 12:58
I believe the issue was once fixed in #5676 (and also reported in #3511) but then returned with #9458 ?

**Comment by garaboncias** [comment] 2017-04-03 01:34
For me its seems the same behaviour both in chrome/Firefox and even after #10549 .
These is because in HTML5 render mode (use <!DOCTYPE html> in html)
document.documentElement.scrollTop should be used instead of document.body.scrollTop when restore scroll position. (http://stackoverflow.com/questions/31857876/scrolltop-returns-0-if-there-is-a-doctype) 

however in quirks mode  (no doctype) it works with body.scrollTop

**Comment by veritas** [comment] 2017-04-03 13:53
@garaboncias Do you mind sharing some code so that I can verify my fix? I feel that I'm doing exactly what you have mentioned in your comment but without any browser targeting ([here](https://github.com/angular/material/pull/10549/commits/9c8b0b89a0aebbc51657e31cc6fc30f5eefe5555#diff-a1919fe5ddcba0e8888df1ee8f3f3727R291)).

**Comment by garaboncias** [comment] 2017-04-04 08:28
Sorry, that's my fault, i just tested against the master branch, but your fix is not merged yet. fix is ok.

**Comment by davidvincentfr** [comment] 2017-05-30 11:59
I fix this bug with this few css lines (sorry too much !important anything else was working) :

html {
    &[style="overflow-y: scroll;"] {
        overflow: initial !important;
        body {
            position: relative !important;
            top: 0px !important;
        }
    }
}

**Comment by jon-h86** [comment] 2017-06-05 13:10
I can confirm this is still an issue on my firefox.. Any word on a solution?

**Closed** 2017-07-18 16:52 UTC

**Comment by TakeshiDaveau** [comment] 2017-09-13 08:26
I still have the issue with md-dialog in Firefox 55.0.3

**Comment by imannorouzi** [comment] 2017-09-27 02:24
Here is a workaround. Just move the scroll from the body element to an inner element like below:

<body>
    <div id="container">
    </div>
<body>

// Style 
body{
    height: 100%;
    width: 100%;
    overflow: hidden;
}
#container{
    height: 100%;
    width: 100%;
    overflow-y: scroll;
}

**Comment by binchentx** [comment] 2017-09-28 14:26
I am still having this issue using Chrome v61 (angular-material.min.js v0.11.0)
Everytime the results hidden caused scroll to top.
1. Show some results, then back space to less than required search text length
2. Show some results, then keep typing till No Found
3. select one from result

imannorouzi's work around won't help me since I have a large screen and need main scrollbar.

**Comment by nganbread** [comment] 2017-09-28 14:47
I agree with @binchentx that the fix isnt sufficient; it also breaks inertial scrolling on iOS devices

**Comment by veritas** [comment] 2017-09-28 15:12
@binchentx have you tried using the newest material version? Path for that was applied in 1.1.5.

@nganbread which fix does not work for you? The workaround proposed by @imannorouzi?

**Comment by binchentx** [comment] 2017-09-28 15:31
I think it is same or similar to the issue which mddialog hide/close will scroll the page to top.

**Comment by binchentx** [comment] 2017-09-28 15:43
@veritas You are SO RIGHT AND GOOD. 
I tried angular-material.min.js v1.1.5 (and its css), the problem solved, both for md-autocomplete and my other md-dialog.

**Comment by binchentx** [comment] 2017-09-28 19:56
But, I a lot of changes (styles) and I had to rollback and stay with v0.11
1. md-select added a lot of extra spacing
2. background-color changed
etc.

**Comment by nganbread** [comment] 2017-09-28 19:59
@veritas apologies, the fix does seem to be working and @bichentx's workaround is no longer necessary. Thanks for your hard work!

**Comment by veritas** [comment] 2017-09-28 20:10
@binchentx I would like to encourage you to try keep the latest version and override the CSS styles in your own style sheet. Your version seems to be very old. It's a lot of work so of course keep in mind your deadlines ;) 

@nganbread no problem. I'm glad I could help

**Comment by binchentx** [comment] 2017-09-28 20:26
@veritas Thanks, but I think it may need a lot of work to upgrade other library files.
Just Angular.material.min.js and its css caused a lots of issues.
For example md-select added all spaces from the leading tabs of my <md-option ..> line. Then I can only see ... as in selected option.

**Comment by binchentx** [comment] 2017-09-28 21:53
@veritas I will go with v1.0.5, which have jump top resolved and also not much style changes.
Thanks for your help

**Comment by BurakAkyildiz** [comment] 2017-11-10 08:54
Im having this isssue with material v1.1.5. $mdDialog scrolls top when closed
