### ISSUE TITLE
Update Angular peerDependencies for compatibility with Angular 1.6

### ISSUE THREAD

**Issue by kibertoad** [angular/material#10311] opened 2017-01-26 16:42 UTC
**Actual Behavior**:
 -  Currently Angular peerDependencies are listed like this:

{
    "angular": ">=1.3 <1.6",
    "angular-animate": ">=1.3 <1.6",
    "angular-aria": ">=1.3 <1.6"
  }

 -  `What is the expected behavior?`

Angular peerDependencies should look like this:

{
    "angular": ">=1.3 <1.7",
    "angular-animate": ">=1.3 <1.7",
    "angular-aria": ">=1.3 <1.7"
  }

**Comment by graingert** [comment] 2017-02-09 12:05
duplicate of #10111 @kibertoad please check for open issues before making a new one.

**Comment by ThomasBurleson** [comment] 2017-03-06 23:34
See https://github.com/angular/bower-material/pull/36

**Closed by ThomasBurleson** 2017-03-06 23:34 UTC
