### ISSUE TITLE
md-select breaks if the scope has a property called `mode`

### ISSUE THREAD

**Issue by jelbourn** [angular/material#6260] opened 2015-12-12 00:06 UTC
Due to the combination of this line:
```js
scope.$watch(selectMenuCtrl.selectedLabels, syncLabelText);
```

And then
```js
self.selectedLabels = function(opts) {
  opts = opts || {};
  var mode = opts.mode || 'html';
  ...
  if (mode == 'html') {
    mapFn = /* ... */
  } else if (mode == 'aria') {
    mapFn = /** ... */
  }
  return selectedOptionEls.map(mapFn).join(', ');
}
```

mapFn will be `undefined`

**Comment by ThomasBurleson** [comment] 2015-12-12 00:56
should this be:

```js
self.selectedLabels = angular.bind(self, function(opts) {... });
```

**Comment by jelbourn** [comment] 2015-12-12 01:19
@ThomasBurleson that would still cause the issue. The fix is to change the caller:
```js
scope.$watch(selectMenuCtrl.selectedLabels, syncLabelText);
```
to
```js
scope.$watch(function() {
  return selectMenuCtrl.selectedLabels();
}, syncLabelText);
```

**Comment by code-tree** [comment] 2016-03-31 05:41
This was very confusing... thanks for working on it. Please apply the fix, as I can confirm it works.

**Comment by homerjam** [comment] 2016-04-07 00:13
+1

**Comment by crisbeto** [comment] 2016-04-21 19:11
Closing this one since it's a duplicate of https://github.com/angular/material/issues/6204 and should have been fixed with https://github.com/angular/material/pull/7830

**Closed by crisbeto** 2016-04-21 19:11 UTC
Labels: - Easy fix, needs: merge, P1 - Broken Renders / Major Use Cases, reported by Googler
