### ISSUE TITLE
md-select: selected items are displayed in a column instead of a row

### ISSUE THREAD

**Issue by danjarvis** [angular/material#6176] opened 2015-12-08 21:10 UTC
The issue occurs when using the `multiple` mode and selecting 2 or more items.

[Codepen](http://codepen.io/danjarvis/pen/JGowVe)

Introduced in ~~1.0.0-rc6~~ 1.0.0-rc5

**Comment by mprentic-harris** [comment] 2015-12-08 23:19
This is a duplicate of https://github.com/angular/material/issues/5926.

**Closed** 2015-12-09 02:08 UTC
