### ISSUE TITLE
md-datepicker with top label like the input control?

### ISSUE THREAD

**Issue by Sun3** [angular/material#5920] opened 2015-11-25 22:30 UTC
I would like to request the md-datepicker to work the same way the input control works with the top label. Of caused inside a md-contaier or md-input-container.

If you have  bunch of md-datepicker fields without the top label uses do not know what date have been entered

```
<div layout="" layout-sm="column">
        <md-input-container flex="">
          <label>Property Name</label>
          <input ng-model="property.propertyName">
        </md-input-container>

        <md-container class="calendarDiv">
          <label class="customLabel">Viewed</label>
          <md-datepicker ng-model="property.dateViewed" md-placeholder="Date Viewed"></md-datepicker>
        </md-container>    
</div>
```

```
<md-container class="calendarDiv">
     <label class="customLabel">Purchased</label>
     <md-datepicker ng-model="property.datePurchased" md-placeholder="Date Purchased"></md-datepicker>
</md-container>
```

I am open to any suggestions.

**Comment by jelbourn** [comment] 2015-11-25 23:29
Dupe of #4233

**Closed by jelbourn** 2015-11-25 23:29 UTC
