### ISSUE TITLE
md-select: ng-change issue

### ISSUE THREAD

**Issue by kschwidder** [angular/material#1576] opened 2015-02-19 20:42 UTC
md-select does not support ng-change event. 
According to angular select it does. In order to listen to change events $watch has to be implemented which is not very performant.

http://plnkr.co/edit/m4PMSuVnkhwxrFijcOsb?p=preview

**Comment by ajoslin** [comment] 2015-02-19 23:25
This is because the md-select-menu actually creates a new ng-model, it doesn't share the md-select's ng-model.

@rschmukler we could manually get/set the `ngModelController` from the `<md-select>` element and set it to element.data() on the menu.

**Comment by rschmukler** [comment] 2015-02-23 20:02
fixed in f4ce10eea6590ac431b7b15c44242b76219e1f7f

**Comment by seiyria** [comment] 2015-02-23 23:31
This doesn't seem to be working: 
```jade

                        md-select.no-margin-top(ng-model="player.title",ng-change="changeTitle()")
                            md-option(ng-value="title",ng-repeat="title in titles") {{title}}
```

Does not seem to be calling ng-change ever.

**Comment by seiyria** [comment] 2015-02-23 23:47
Ah, that commit does not appear to have made it into 0.8.0. Can we get a quick maintenance release for that fix?

**Comment by rschmukler** [comment] 2015-02-24 16:07
We will discuss the possibility of a maintenance release. Closing this issue since it's resolved.

**Closed by rschmukler** 2015-02-24 16:07 UTC

**Comment by axelson** [comment] 2015-03-16 21:09
Is this in 0.8.3?

**Comment by Splaktar** [comment] 2015-03-16 21:50
@axelson yes.

**Comment by axelson** [comment] 2015-03-17 00:33
Thanks! It turns out I just had a syntax error...

**Comment by david-gang** [comment] 2015-03-18 12:28
I think this should be documented.

Currently it is not : https://material.angularjs.org/#/api/material.components.select/directive/mdSelect

**Comment by Novashock** [comment] 2015-03-30 17:57
@Splaktar Are you sure this has been resolved in 0.8.3 release? it is not working for me!

**Comment by demisx** [comment] 2015-04-01 00:38
Doesn't work for me in 0.8.3 either. Show stopper.

**Comment by demisx** [comment] 2015-04-01 00:41
Works for me in 0.8.3

**Comment by rschmukler** [comment] 2015-04-01 21:18
Ignore the above reference... I mistyped. If anyone is having issues with it in 0.8.3 please open a new issue with an example codepen / plunker so we can debug

**Comment by resh2302** [comment] 2017-01-13 19:25
can someone share an example? It doesn't work for me :|

**Comment by AnimaMundi** [comment] 2017-01-27 17:04
doesn't work for me either!

**Comment by dubcdr** [comment] 2017-02-21 22:06
not working for me either

**Comment by nickgraz** [comment] 2017-03-07 22:10
It is a little but this is working for me:

https://material.angularjs.org/latest/api/directive/mdSelect

`md-on-close`

`<md-select ng-model="model[field]" md-on-close="debounceSave()">`

It isn't great, because now it runs even if it doesn't change! But it does work!

**Comment by tschieggm** [comment] 2017-03-27 21:23
This doesn't appear to work for me and the unit test checking it has been commented out in https://github.com/angular/material/commit/21d15baec30ea1b7f978efdf71352efbe2039d2e

**Comment by cangzhang** [comment] 2017-06-26 03:33
not working for me. v1.1.4

**Comment by pavelsl** [comment] 2018-03-05 13:11
Doesn't work for me as well. As for md-on-close it triggers function always, regardless model changed or not. If user doesn't select anything function will be triggered anyway.

**Comment by Splaktar** [comment] 2018-03-07 18:57
Here's a [demo](http://plnkr.co/edit/m9UKaL6l12sTt93Udtn6?p=preview) of `ng-change` working with `md-select` in 1.1.7. If you are having problems with this, please submit a new issue with a CodePen reproduction.

**Comment by Splaktar** [comment] 2018-03-07 19:22
@david-gang you are correct that this is missing from the docs. Opened https://github.com/angular/material/pull/11152 to add it.
