### ISSUE TITLE
md-subheader : scrolling is really slow since angularjs 1.3.16

### ISSUE THREAD

**Issue by Badisi** [angular/material#3193] opened 2015-06-09 19:56 UTC
Since angularjs 1.3.16, scrolling in a md-content that has md-subheader(s)  (using the touchpad on a macbook pro) is really slow.

This can be seen in the 0.10.0-RC1 [demo](https://material.angularjs.org/0.10.0-rc1/#/demo/material.components.subheader) that's using angular 1.4.0.

**Comment by Badisi** [comment] 2015-06-10 17:13
Seems that it has been fixed in 0.10.0-RC2

**Comment by codeator** [comment] 2015-06-16 20:50
Not fixed, 0.10.0 angular 1.4.1 same issue

**Comment by Badisi** [comment] 2015-06-16 21:09
I thought it was fixed but you are right it's not.
In fact since 0.10.0-RC2 they rollback the demo to angular 1.3.15 which make me think it was fixed.

So I'm still having issues with angular 1.4.x but more or less performance issues (not scrolling).

**Comment by codeator** [comment] 2015-06-16 21:18
downgrading to 1.3.15 resolving perfomance issues with angular-material, so stack 1.3.15 / 0.10.0 works very fine,  1.3.16 are issues too

**Comment by Badisi** [comment] 2015-06-16 21:26
Yes, I'm also sticking with 1.3.15 / 0.10.0 for now.

**Comment by mertenhanisch** [comment] 2015-06-20 19:10
+1
the subheader appears to be slowing down the site in chrome, but not in firefox. even when i change position of the subheader from sticky to relative.
i tried to have the page exactly as in the angular material demo of subheaders, also trying a somewhere else suggested fix of applying position: relative to the container didn't help. using angular 1.4.2 and material 0.10.0

**Comment by shakhrillo** [comment] 2015-06-28 16:00
+1
I also trying to find the answer Hope It will be fixed the next updates

**Comment by ThomasBurleson** [comment] 2015-07-06 21:39
This issue is a duplicate of #3531

**Closed by ThomasBurleson** 2015-07-06 21:39 UTC
