### ISSUE TITLE
7.1 - 8.3 Touch events not firing ng-click on Android/IOS hybrid apps/mobile browsers

### ISSUE THREAD

**Issue by atentis** [angular/material#1826] opened 2015-03-07 23:50 UTC
I have a hybrid app that is Ionic and Material. Performance was acceptable on on all versions of Material Angular below 8.0. 8.0 - 8.3 on the Ripple emulator works perfect but as soon as I deploy to a device the application is such a slug that it is completely unusable. I am not seeing any errors in visual studio.

This is my environment:
Material Angular 8.0 - 8.3
Ionic bundle: Ionic, v1.0.0-beta.14, angular 1.3.6
Visual Studio 2013 Community Edition w/ Cordova
Moto X 2013 Android 4.4.4

Any help would be greatly appreciated!

--Update 1--
I have discovered more information related to the issue. It looks like I was slightly incorrect in my op about a couple things...

1. The issue is not necessarily that the app becomes slow as it is more of that the touch input is not registering very well. I have to tap many many times on any buttons or links that use ng-click to get them to finally register. It literally has to be very fast and repeated taps to get the click event to fire.
2. It is not 8.0 and above, it is 7.1 and above. Basically the versions since hammer.js was removed.
3. In addition to the android 4.4.4 device I have tried on another with 5.0.1 and it has the exact same issue. 

--Update 2--
It is a conflict with the Ionic framework that started at version 7.1 of Angular Material. If you remove Ionic from your project the ng-click will work again

--Update 3--
I have confirmed this same issue happens not just in android apps but on android and IOS mobile websites as well. I have hosted a test site with material 8.3 here http://www.louspubcrawl.com/

**Comment by gustavohenke** [comment] 2015-03-08 02:53
You should probably post some reproducible code.

**Comment by atentis** [comment] 2015-03-08 20:33
@gustavohenke Do you have any suggestions on how I could do that? I do not have the issue in ripple which makes me believe if I build out my entire project into a plunker that I would have not have the issue there either. It seems as if it only happens when deployed to a device. Here is my index.html

<!DOCTYPE html>
<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, target-densitydpi=medium-dpi, user-scalable=0" />
        <meta charset=" utf-8" />
        <title>Hopscotch</title>
        <link href="Content/ionic.css" rel="stylesheet"/>
        <link href="Content/angular-material.css" rel="stylesheet"/>
        <link href="Content/index.css" rel="stylesheet" />
    </head>
    <body ng-app="mgmtAppModule">
        <ion-nav-view name="loginContent"></ion-nav-view>
        <ion-nav-view></ion-nav-view>
    
    <script src="cordova.js"></script>
    <script src="scripts/platformOverrides.js"></script>

    <script src="scripts/index.js"></script>

    <script src="external/ionic.bundle.js"></script>
    <script src="external/angular-aria.js"></script>
    <script src="external/angular-resource.js"></script>
    <script src="external/angular-material.js"></script>
    <script src="external/angular-cookies.js"></script>

    <script src="scripts/mgmt-app-module.js"></script>
    <script src="scripts/config.js"></script>
    <script src="scripts/login/lg-login-ctrl.js"></script>
    <script src="scripts/layout/menu-layout-ctrl.js"></script>
    <script src="scripts/maintenance/mr-create-request-ctrl.js"></script>
    <script src="scripts/maintenance/mr-display-ctrl.js"></script>
    <script src="scripts/maintenance/mr-maint-service.js"></script>
    <script src="scripts/payments/pm-display-payments-ctrl.js"></script>
    <script src="scripts/payments/pm-make-payment-ctrl.js"></script>
    <script src="scripts/shared/authorization/authService.js"></script>
    <script src="scripts/shared/authorization/httpInterceptorService.js"></script>
</body>
</html>

**Comment by atentis** [comment] 2015-03-09 01:57
I have discovered more information related to the issue. It looks like I was slightly incorrect in my op about a couple things...

1. The issue is not necessarily that the app becomes sluggish as it is more of that the touch input is not registering very well. I have to tap many many times on any buttons or links that use ng-click to get them to register. It literally has to be very fast and repeated taps to get the click event to fire.
2. It is not 8.0 and above, it is 7.1 and above. Basically the versions since hammer.js was removed.

**Comment by atentis** [comment] 2015-03-09 05:12
I have created a brand new VS project with only Angular Material, Ionc and their dependencies. 
If you include any version of Ionc with Angular Material 7.1 and up the Angular ng-clicks will not work on an Android device.

Regular html buttons will not work with the ng-click at all and the material buttons will only works after may repeated presses. As soon as you drop Ionic or move to Material Angular 7.0 + Hammer.js the ng-clicks will work perfectly.

**Comment by atentis** [comment] 2015-03-09 23:55
I have confirmed this same issue happens on a regular website using a mobile android device. I have hosted a test site with material 8.1 here http://www.louspubcrawl.com/

**Comment by thaiat** [comment] 2015-03-12 09:47
yep i am aware of that, the trick is to only integrate the ionic css when trying to work with both framework

**Comment by atentis** [comment] 2015-03-12 22:50
@thaiat but than you cannot use the ion views

**Comment by bradmartin** [comment] 2015-03-13 02:47
Is this related to the issue with hammer.js being removed as speculated in this issue: https://github.com/angular/material/issues/1406 ?

**Comment by thiagoaos** [comment] 2015-03-13 12:48
Nothing yet? Is there some palliative solution?

**Comment by atentis** [comment] 2015-03-24 17:36
@thiagoaos Guessing not until 9.0 is ready

**Comment by DMDc0de** [comment] 2015-03-27 15:28
As a palliative, for now you can use 

`data-tap-disabled="true"`

on each angular material directive that is not playing nice with the Ionic Framework, like the selects and the tabs. Something like 

```html
<md-select placeholder="Pick" ng-model="vpos.currency" flex data-tap-disabled="true">
     <md-option value="1" data-tap-disabled="true">One</md-option>
     <md-option value="2" data-tap-disabled="true">Two</md-option>
</md-select>
```

**Comment by bradmartin** [comment] 2015-03-27 15:46
This works, but also disables scrolling. So on mobile its not a good
solution at all unfortunately.

Brad Martin

**Comment by DMDc0de** [comment] 2015-03-27 15:49
In which directive do you find scrolling is not working? For the md-select scrolling is working both on android and ios (for me at least). Do you want me to provide some code?

**Comment by bradmartin** [comment] 2015-03-27 16:07
Scrolling will work, but if you attempt scrolling while tapping/holding an
element with the data-tap-disabled attribute then you cannot scroll. This
was the case when the original issue
https://github.com/angular/material/issues/1406 was opened on Feb. 5th. So
maybe the data-tap-disabled has been improved to handle scrolling but from
my testing you cannot begin scrolling if you are holding an element with
data-tap-disabled="true" set.

**Comment by bradmartin** [comment] 2015-03-27 16:10
I think this issue can be merged with #1406 and #1528. @marcysutton @ajoslin @ThomasBurleson

**Comment by wrousseau** [comment] 2015-03-29 16:48
Is this still planned for 0.9.0 ?

**Comment by drastick** [comment] 2015-03-31 13:08
I too would like to know if this is planned for 0.9.0

**Comment by rlucian** [comment] 2015-04-02 15:14
this commit https://github.com/angular/material/commit/7b780712a5f05ded9dfe0047c0cbf0f6ddcb6405 seems to be related to this bugs and several other related bugs.
could someone check and confirm?

**Comment by CR88** [comment] 2015-04-02 20:45
Using the rawgit references, and on Ionic, still broken.

**Comment by ThomasBurleson** [comment] 2015-04-02 21:17
@drastick - we are working on these for 0.9 release.

**Comment by badger27** [comment] 2015-04-10 13:17
also having this problem

**Comment by badger27** [comment] 2015-04-10 13:19
But it only happens  after I build to a device. Tried all the above with no results.

**Comment by ThomasBurleson** [comment] 2015-04-13 17:45
For mobile solutions that are also using jQuery, you can now use $mdGestureProvider in 
```js
   app = angular.module('MyApp', ['ngMaterial'])
      .config(function( $mdGestureProvider ) {
          $mdGestureProvider.skipClickHijack();
      });
```
This will configure $mdGesture to **not** intercept clicks (stop propagation and prevent defaults).

**Closed by ThomasBurleson** 2015-04-13 17:45 UTC
Labels: bug, conflict, gestures

**Comment by debarko** [comment] 2016-08-04 17:09
Thanks a lot for the above fix. It solved a huge issue which was causing a major headache for me.
Angular Google Maps Directive Autosuggest stopped working since the touch wasn't reaching to the item in the list of suggested items. Finally this solved it.

**Comment by vasuvuggu** [comment] 2017-02-10 09:58
Hi all, button events are not triggered in cordova ios mobile app,
i have tried all of the options mentioned above.
& deviceready event in cordova also not firing.
Plz let me know if any suggestions.
