### ISSUE TITLE
Exception happening in production code in angular-material code (but I don't know how to reproduce them)

### ISSUE THREAD

**Issue by yoav-zibin** [angular/material#8245] opened 2016-04-27 21:02 UTC
Exception 1:
TypeError: Cannot set property '$window' of null
    at o (http://ajax.googleapis.com/ajax/libs/angular_material/1.1.0-rc4/angular-material.min.js:8:2859)
    at new <anonymous> (<anonymous>:6:27)
    at Object.instantiate (http://ajax.googleapis.com/ajax/libs/angularjs/1.5.5/angular.min.js:41:473)
    at Object.n [as attach] (http://ajax.googleapis.com/ajax/libs/angular_material/1.1.0-rc4/angular-material.min.js:8:2751)
    at Object.attach (http://ajax.googleapis.com/ajax/libs/angular_material/1.1.0-rc4/angular-material.min.js:8:1937)
    at d (http://ajax.googleapis.com/ajax/libs/angular_material/1.1.0-rc4/angular-material.min.js:9:219)
    at ja (http://ajax.googleapis.com/ajax/libs/angularjs/1.5.5/angular.min.js:80:350)
    at n (http://ajax.googleapis.com/ajax/libs/angularjs/1.5.5/angular.min.js:66:28)
    at g (http://ajax.googleapis.com/ajax/libs/angularjs/1.5.5/angular.min.js:58:305)
    at n (http://ajax.googleapis.com/ajax/libs/angularjs/1.5.5/angular.min.js:65:473)

Cause: <button class="md-button" type="button" ng-transclude="" id="test_start_rematch" ng-click="main.currentMatch().startNewMatch()" role="menuitem">

Exception 2:
TypeError: Cannot call method 'remove' of undefined
    at e.onIsOpenChanged (http://ajax.googleapis.com/ajax/libs/angular_material/1.1.0-rc4/angular-material.min.js:14:523)
    at http://ajax.googleapis.com/ajax/libs/angular_material/1.1.0-rc4/angular-material.min.js:13:30425
    at http://ajax.googleapis.com/ajax/libs/angular_material/1.1.0-rc4/angular-material.min.js:7:13375
    at Array.forEach (native)
    at o (http://ajax.googleapis.com/ajax/libs/angular_material/1.1.0-rc4/angular-material.min.js:7:13355)
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.5.5/angular.min.js:158:166
    at e (http://ajax.googleapis.com/ajax/libs/angularjs/1.5.5/angular.min.js:45:350)
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.5.5/angular.min.js:48:275

I have code that automatically reverses a minified JS exception to the non-minified version,
BUT your minified files are missing sourceMappingURL, e.g., 
//# sourceMappingURL=angular.min.js.map

I'll open another bug for that :)

E.g., my tool reversed this line:
    at Object.instantiate (http://ajax.googleapis.com/ajax/libs/angularjs/1.5.5/angular.min.js:41:473)
to:
    at (unknown) (angular.js:4680:13)
but it can't reverse angular-material.min.js due to the missing sourceMappingURL:

TypeError: Cannot set property '$window' of null
    at o (http://ajax.googleapis.com/ajax/libs/angular_material/1.1.0-rc4/angular-material.min.js:8:2859)
    at new <anonymous> (<anonymous>:6:27)
    at (unknown) (angular.js:4680:13)
    at Object.n [as attach] (http://ajax.googleapis.com/ajax/libs/angular_material/1.1.0-rc4/angular-material.min.js:8:2751)
    at Object.attach (http://ajax.googleapis.com/ajax/libs/angular_material/1.1.0-rc4/angular-material.min.js:8:1937)
    at d (http://ajax.googleapis.com/ajax/libs/angular_material/1.1.0-rc4/angular-material.min.js:9:219)
    at (unknown) (angular.js:9694:8)
    at invokeLinkFn (angular.js:9093:10)
    at (unknown) (angular.js:8397:12)
    at (unknown) (angular.js:9088:23)

**Comment by yoav-zibin** [comment] 2016-04-28 15:18
Exception 3:
	Error: [$rootScope:inprog] http://errors.angularjs.org/1.5.5/$rootScope/inprog?p0=%24digest
http://ajax.googleapis.com/ajax/libs/angularjs/1.5.5/angular.min.js:6:417
m@http://ajax.googleapis.com/ajax/libs/angularjs/1.5.5/angular.min.js:137:224
$apply@http://ajax.googleapis.com/ajax/libs/angularjs/1.5.5/angular.min.js:145:161
http://ajax.googleapis.com/ajax/libs/angularjs/1.5.5/angular.min.js:272:452
Qf@http://ajax.googleapis.com/ajax/libs/angularjs/1.5.5/angular.min.js:37:37
d@http://ajax.googleapis.com/ajax/libs/angularjs/1.5.5/angular.min.js:36:487
dispatchEvent@[native code]
o@http://ajax.googleapis.com/ajax/libs/angular_material/1.1.0-rc4/angular-material.min.js:7:20522
http://ajax.googleapis.com/ajax/libs/angular_material/1.1.0-rc4/angular-material.min.js:7:16586
end@http://ajax.googleapis.com/ajax/libs/angular_material/1.1.0-rc4/angular-material.min.js:7:21020
i@http://ajax.googleapis.com/ajax/libs/angular_material/1.1.0-rc4/angular-material.min.js:7:21853
f@http://ajax.googleapis.com/ajax/libs/angular_material/1.1.0-rc4/angular-material.min.js:7:22054
Qf@http://ajax.googleapis.com/ajax/libs/angularjs/1.5.5/angular.min.js:37:37
d@http://ajax.googleapis.com/ajax/libs/angularjs/1.5.5/angular.min.js:36:487
setAttribute@[native code]
attr@http://ajax.googleapis.com/ajax/libs/angularjs/1.5.5/angular.min.js:191:394
http://ajax.googleapis.com/ajax/libs/angularjs/1.5.5/angular.min.js:193:221
$set@http://ajax.googleapis.com/ajax/libs/angularjs/1.5.5/angular.min.js:85:186
http://ajax.googleapis.com/ajax/libs/angularjs/1.5.5/angular.min.js:261:107
http://ajax.googleapis.com/ajax/libs/angularjs/1.5.5/angular.min.js:85:264
q@http://ajax.googleapis.com/ajax/libs/angularjs/1.5.5/angular.min.js:7:359
$set@http://ajax.googleapis.com/ajax/libs/angularjs/1.5.5/angular.min.js:85:241
http://ajax.googleapis.com/ajax/libs/angularjs/1.5.5/angular.min.js:79:276
$digest@http://ajax.googleapis.com/ajax/libs/angularjs/1.5.5/angular.min.js:142:307
$apply@http://ajax.googleapis.com/ajax/libs/angularjs/1.5.5/angular.min.js:145:256
l@http://ajax.googleapis.com/ajax/libs/angularjs/1.5.5/angular.min.js:97:61
H@http://ajax.googleapis.com/ajax/libs/angularjs/1.5.5/angular.min.js:101:191
onload@http://ajax.googleapis.com/ajax/libs/angularjs/1.5.5/angular.min.js:102:230

**Comment by ThomasBurleson** [comment] 2016-04-29 12:14
Closing this issue due to insufficient information. Please resubmit with:

----
Required
----

**Behavior**:
-  What is the issue? * 
-  What is the expected behavior? 

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue :
-  Details: 

**Angular Versions**: *
-  Angular Version: 
-  Angular Material Version: 

**Additional Information**:
-  Browser Type: *
-  Browser Version: *
-  OS: *
-  Stack Traces: 

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

**Closed by ThomasBurleson** 2016-04-29 12:14 UTC

**Comment by yoav-zibin** [comment] 2016-04-29 13:30
The entire stack trace is ONLY angular and angular-material code (the stack trace doesn't include my code at all). So it's 100% an issue with angular/material code. I'm happy to investigate it, but because of https://github.com/angular/material/issues/8246, I can't decode the material stack trace (only the angular one)...

I'm especially familiar with the common "$rootScope:inprog" error --- it's coming from using $apply when there is a digest cycle going, and the fix is really simple: use "safeApply" instead of $apply, see:
http://stackoverflow.com/questions/22733422/angularjs-rootscopeinprog-inprogress-error

I get about 5 bugs like that ("$rootScope:inprog") a day in my prod code (and I have only ~50,000 app installs for our games), so it's rare but it happens every day :)

**Comment by yoav-zibin** [comment] 2016-05-06 13:22
BTW, if anyone encounters this issue, the workaround is to monkey-patch angularjs to avoid these inprog errors like this:


  // angular-material has a ton of
  // Error: [$rootScope:inprog] http://errors.angularjs.org/1.5.5/$rootScope/inprog?p0=%24digest
  // see: https://github.com/angular/material/issues/8245
  $provide.decorator('$rootScope', [
    '$delegate', function($delegate: any) {
      $delegate.unsafeOldApply = $delegate.$apply;
      $delegate.$apply = function(fn: any) {
        var phase = $delegate.$$phase;
        if (phase === "$apply" || phase === "$digest") {
          if (fn && typeof fn === 'function') {
            fn();
          }
        } else {
          $delegate.unsafeOldApply(fn);
        }
      };
      return $delegate;
    }
  ]);
