### ISSUE TITLE
colors and hues should be available everywhere.

### ISSUE THREAD

**Issue by SanderElias** [angular/material#1269] opened 2015-01-23 06:33 UTC
I created [this sample on plunker](http://plnkr.co/edit/M22sy0AI7Bax3Cop3OmI?p=preview) to demonstrate a few issues I'm having with forms. 

If you look at like 24 of index.html in my sample, you see there is a heading there. This heading is not visible in the page, because I don't know how to set the background color according to the current selected theme/colorpallete. I added an md-hue-1 to the class-list as well as an attribute, but it is not giving the result I need.

This is also mentioned in #537, but I still could not find a solution to it.

**Comment by SanderElias** [comment] 2015-01-26 14:12
I took my solution from #537. and rewrote it a bit so it will work with the new $mdThemingProvider.
For anybody that need something similar, have a look at my mdColors module. It's available in [this plunker](http://plnkr.co/edit/SHkXcAQDNPHWloBnVxrw?p=preview)

This will serve my needs for now, but it still feels awkward that I have to go trough those lengths just to be able to get my hands on the selected color palette. 
I still feel like I somehow miss the obvious!

**Comment by iRouge** [comment] 2015-01-27 16:50
Sander, I share your feelings, your concerns... and your solution !

Thanks a lot

**Comment by SanderElias** [comment] 2015-01-29 13:08
@iRouge I began to believe I was to only one ;)

**Comment by ThomasBurleson** [comment] 2015-02-17 12:52
@SanderElias - I think we should include a version of your **colors.js** and publish a service `$mdColors` service for easy color lookups.
@rschmukler - thoughts ?

**Comment by SanderElias** [comment] 2015-02-17 13:53
@ThomasBurleson I would like that! Should I add support for md-hue-x and so on too?

**Comment by ThomasBurleson** [comment] 2015-02-17 18:10
@SanderElias - let's start with a simple, clean API for the initial work.
Can you create the $mdColors service and submit a PR ? Thx is advance.

**Comment by jonnysamps** [comment] 2015-02-17 19:50
I believe I have a pretty solution for color lookups: checkout my plunkr: http://plnkr.co/edit/gBDV2ABghTMqqs5YaElB?p=preview

**Comment by SanderElias** [comment] 2015-02-19 10:07
@marcysutton I'm preparing an PR, as it looks now, I will be done by the end of the day.

**Comment by SanderElias** [comment] 2015-02-21 08:30
@marcysutton I created a new branch, its in PR #1599. Somehow it would not let me update my other PR

**Comment by mtraynham** [comment] 2015-03-08 03:08
This is awesome! +1

**Comment by rschmukler** [comment] 2015-04-01 21:00
@SanderElias finally got to reviewing the PR. I want to move it back a bit as I want to extend the API to make the following possible:

- ability to lookup a color for a theme. eg. `$mdColors.getTheme('default').primary.['hue-1']`. This might get moved into `$mdColors.getColor('default', 'primary', 'hue-1'). This would return an object with properties expressing the color and the contrast in rgba, `{value: 'rgba(...)', contrast: 'rgba(...)'}`. Specifically this will help with [#2118]
- ability to dynamically generate stylesheets for more than one palette, and follow the `md-THEME_NAME-theme .md-primary-default-fg` for selectors. This feels more consistent with how the framework on the whole works, and ideally we would allow for loading multiple themes. eg. `$mdColors.generateColorCssForTheme('myOtherTheme')`.
- Consider moving it all into `$mdTheming` as otherwise the distinction might be confusing / lots of shared logic.
- Add proper tests for everything mentioned above

I apologize on the massive delay on this. I don't think I will have time to do all of this until after `0.10.0` ships.

**Comment by SanderElias** [comment] 2015-04-02 06:42
@rschmukler. I agree that solving #2118 will make color handling a lot easier. It is the sole reason for the whole copying and parsing that I do in the config function. 

If you like, I can switch the whole thing over to keep/utilize rgba color/colorcontrast pairs.
Also, the possibility to generate more then 1 palette is something I can create easily. It isn't in because @ThomasBurleson asked me to keep it simple.

I agree that this service should merge with $mdTheming, I kept it separate so I could work on it without messing up existing stuff ;) We can merge it into $mdTheming as soon as we have an complete solution.

**Comment by SanderElias** [comment] 2015-04-02 06:50
@rschmukler Have been thinking about the css. I assume you only want the colors of the active theme generated? (otherwise it might be a _lot_ of css to generate!)
To keep the usage simple I would generate the colors like (sass-like nested sample)
```css
md-primary {
   md-color-fg-400: rgba(1,2,3,.8)
   md-color-bg-400: rgba(1,2,3,.8)
   ...
}
md-accent {
   md-color-fg-400: rgba(1,2,3,.8)
   md-color-bg-400: rgba(1,2,3,.8)
   ...
}
```

that way it's easy to use every available color, and keep the length of the classnames a bit more in control.
But I'm open for suggestions.

**Comment by gkalpak** [comment] 2015-04-02 10:16
Keep in mind that multiple themes can be "active" at a time.

**Comment by SanderElias** [comment] 2015-04-02 11:17
@galpak, Are you sure? As far as I see it, the $mdTheming provider can provide just 1 theme. A theme consists out of 4 color palettes (primary,accent,warn and background). It support for loading your own colors into the palettes, and you can even provide your own palettes, but there is only 1 theme active at a time. All this can only be done during config, so there isn't much change that it's changing during runtime. It can be that I missed something, would you then be so kind to point me to it?

**Comment by SanderElias** [comment] 2015-04-02 11:26
As @gkalpak pointed out, there can be multiple themes active at 1 time. I can add support for this, and generate the needed CSS. However, I would suggest that if you want multiple themes, you kick off generating the css for each extra theme by hand. Each theme will add quite some CSS rules, and changes are, you won't need those for the added themes. So it will be lighter for memory and runtime if we only generate this stuff on request.
Awaiting your comments..

**Comment by rschmukler** [comment] 2015-04-02 15:10
@SanderElias agreed that kicking off CSS generation should be done on a per-theme basis. I would even consider making that the case for the `default` theme since, ideally, `$mdColor` could also be used to just get colors

**Comment by SanderElias** [comment] 2015-04-03 06:26
@rschmukler I think we are (mostly) on the same page. 
I think the 'default' theme can do without nesting. That would make more sense to me. Most users will go for 1 default theme, so why add the requirement of a nesting element just to set a default? Same goes for the primary color, that can be implied too.
I'll write out a small part of the actual css, to make sure we are talking the same language. (this is what needs to be generated anyway!)

```css
/* default theme is implied*/
/* Primary is implied */
.md-color-fg-100 {color: #574EF5; }
.md-color-bg-100 {background-color: #574EF5; }

.md-warn .md-color-fg-100 ,.md-warn.md-color-fg-100 {color: #FC0366; }
.md-warn .md-color-bg-100 ,.md-warn.md-color-bg-100{background-color: #FC0366; }

/*for secondary themes */
.md-someName-theme .md-color-fg-100 {color: #03FC6B; }
.md-someName-theme .md-color-bg-100 {background-color: #03FC6B; }

.md-someName-theme .md-warn .md-color-fg-100,.md-someName-theme .md-warn.md-color-fg-100  {color: #ff0; }
.md-someName-theme .md-warn .md-color-bg-100,.md-someName-theme .md-warn.md-color-bg-100  {background-color: #ff0; }
```
[In action in this plunk](http://plnkr.co/edit/BKjxy2TgIXiSrcS3PFRg?p=preview)

Is that in line on how you where thinking? It also becomes clear why I don't want to generate the alternate theme's css by default. Those extra style-sheets will add quite some load.

While thinking about this, it seems to make sense to generate the default-primary palette css-rules on init, and the rest on request, or do you think that's confusing?

**Comment by rschmukler** [comment] 2015-04-05 22:09
@SanderElias exactly! Your css look great to me. 

Regarding the rules on init, I could argue either way. I think default on init seems fair. We'll just have to document that people will need to explicitly load the non-default themes. Thanks again for all of your contributions!

**Comment by SanderElias** [comment] 2015-04-08 14:55
@rschmukler I think we a re both in a wait state now, is there any progress? I'm waiting to see what happens with #2118, if that clears, I can code this right away. If not, I can solve #2118 with an update of mdColors. But I can't decide what needs to be done there alone!

**Comment by ptrenery** [comment] 2015-04-10 15:47
@SanderElias Quick question. I have a saas product that will allow customers to customize the colors on the site to match their own branding. Will the new functionality ($mdColors) allow me to change palettes within a theme, as well as colors within palettes at run-time rather than config time? Thanks for your work.

**Comment by Frank3K** [comment] 2015-04-10 15:59
I doubt it will, but let's wait for @SanderElias to answer.

I have a similar use case; if the new functionality ($mdColors) does not provide this, this would be a good feature request in the form of a separate issue.

**Comment by SanderElias** [comment] 2015-04-10 16:01
@ptrenery Not right now. Colors are extracted from the themes that are already available. There is no way to write those back.
However, you can modify the colors inside, and use those to display color swatches, up them, and write out a new theme as your are ready for it. Then you can load the custom theme at the next invcation of your app (themes are loaded during config)
Does that help a bit?

**Comment by SanderElias** [comment] 2015-04-10 16:06
@ptrenery @Frank3K Would a palette editor do? so you can easily build your own themes?

**Comment by ptrenery** [comment] 2015-04-10 16:25
That sounds pretty close. If you could build a theme dynamically and apply it to the page, that would be most of it. For my app at least, I only really need one theme at any one time and I'd prefer not to create the overhead of having lots of themes. I'd ideally like to be able to dynamically set palettes within the current theme or even create custom palettes entries on the fly, set them in the current theme then apply it to the page. Basically I'd like all the flexibility of $mdThemingProvider which can do all this but at run-time rather than config time. I know I'm not asking for much.

**Comment by SanderElias** [comment] 2015-04-10 16:35
Well, I the building part is easy. Dynamically applying it to the page is
not so. Problem is, that MD itselfs get configured during the config phase.
MD parts are using those internal colors, and not the ones I generate CSS
for.
So, building a theme is easily possible, and displaying the new colors too,
however in the current situation I can't activate the new theme
dynamically, you need a page-refresh for that. (I can force the refresh
using code... hmmm)

**Comment by Frank3K** [comment] 2015-04-10 16:52
A page refresh for a theme switch isn't a very big problem if you ask me. 

The problem is that, since you need to choose a theme in the config part, you can not 'retrieve' the theme of the user using the `$http` service.

**Comment by SanderElias** [comment] 2015-04-10 16:54
there are ways around that. I'll have dealt with those issues before.
Depends on what you need when too!

2015-04-10 18:52 GMT+02:00 Frank <notifications@github.com>:

**Comment by ptrenery** [comment] 2015-04-10 16:56
@Frank3K  That's a good point Frank. In my implementation, I redirect to a page without material components. I run the $http. I would then set up the theme, palettes, colors etc. Then go back to the original url. Assuming the $http request is relatively quick, it's an ok user experience.

**Comment by SanderElias** [comment] 2015-04-10 16:59
@ptrenery, would in not be simpler to do an server side include of the
theme?

2015-04-10 18:57 GMT+02:00 ptrenery <notifications@github.com>:

**Comment by ptrenery** [comment] 2015-04-10 17:01
@SanderElias Probably would be quicker. Not a bad idea. That would help with initialization for sure.

**Comment by mprentic-harris** [comment] 2015-04-30 14:21
Lots of good discussion here. We're also building a SaaS product that needs to be able to change and apply themes on the fly. It sounds like we're getting there, unfortunate that it will be after 0.10.0.

**Comment by plato-cambrian** [comment] 2015-05-26 15:30
I want to color a list item like this, will this WIP help me?
```
<md-list>
  <md-list-item
    class="md-1-line"
    ng-repeat="a in b"
    ng-class="{'md-primary': a._id == getGlobalSelectedId()}"
  >
    <span>{{a.name}}</span>
  </md-list-item
</md-list>
```

**Comment by SanderElias** [comment] 2015-05-26 15:33
@plato: Well, if you replace md-primary with a hue or color out of the
palette it will!
md-primary does not mean anything on its own. (as a class name)

2015-05-26 17:31 GMT+02:00 plato <notifications@github.com>:

**Comment by plato-cambrian** [comment] 2015-05-26 18:47
@SanderElias Thanks for the comment. I was going by the demo for md-button on the theming documentation. I'm not sure what the correct "hue or color" class is, I tried `md-color-bg-100` but the spans are still black and my inspector doesn't show any rules being applied. I also tried to make a plunkr but I can't get it to load angular at all. http://plnkr.co/edit/sv5Vh257HXKOjnFgYC89?p=preview

1. Does your solution work on current release?
2. Are there existing classes I can use to style spans, if so can you give an example?

**Comment by kenng** [comment] 2015-05-30 01:08
I am using the v0.9.4, when I looked at the start of html file, there are a bunch of inline style has been generated. I thought, there are really a lot! Is there any way to reduce it? 

```html
     <head>
     <style type='text/css'>md-bottom-sheet.md-default-theme.md-list md-list-item...</style>
     <style type='text/css'>md-bottom-sheet.md-default-theme.md-hue-1.md-list md-list-item...</style>
     <style type='text/css'>md-bottom-sheet.md-default-theme.md-hue-2.md-list md-list-item..</style>
     <style type='text/css'>md-bottom-sheet.md-default-theme.md-hue-3.md-list md-list-item...</style>

     <style type='text/css'>a.md-button.md-default-theme.md-fab...</style>
     <style type='text/css'>a.md-button.md-default-theme.md-hue-1.md-fab...</style>
     <style type='text/css'>a.md-button.md-default-theme.md-hue-2.md-fab..</style>
     <style type='text/css'>a.md-button.md-default-theme.md-hue-3.md-fab...</style>

     <style type='text/css'>a.md-button.md-default-theme.md-warn...</style>
     <style type='text/css'>a.md-button.md-default-theme.md-hue-1.md-warn...</style>
     <style type='text/css'>a.md-button.md-default-theme.md-hue-2.md-warn..</style>
     <style type='text/css'>a.md-button.md-default-theme.md-hue-3.md-warn...</style>

     <style type='text/css'>md-autocomplete.md-default-theme..</style>
     <style type='text/css'>md-autocomplete.md-default-theme.md-hue-1...</style>
     <style type='text/css'>md-autocomplete.md-default-theme.md-hue-2...</style>
     <style type='text/css'>a.md-button.md-default-theme.md-hue-3.md-warn...</style>
```

I believe they generated from this line: 

```javascript
angular.forEach(color.hues, function(hueValue, hueName)
  // Object {default: "500", hue-1: "300", hue-2: "800", hue-3: "A100"
```

**Comment by mprentic-harris** [comment] 2015-06-01 16:50
@plato-cambrian did you try `md-hue-1` or `md-hue-2` or `md-hue-3` etc?

**Comment by SimeonC** [comment] 2015-06-03 01:48
I've created a very simplistic shim that might help some people in the mean time, it's just got basic `.md-fg` and `.md-bg` that can be used like in the md-button. IE `.md-primary.md-fg` will apply the primary color to the foreground.

Here's the gist: https://gist.github.com/SimeonC/1f6b6e52c9b14c4c7b63

**Comment by dynameis** [comment] 2015-06-03 17:54
@SimeonC 's code not work for me ,
so i create a moudule
<pre>
(function () {
    "use strict";
    angular
        .module('custiom.material', ['material.core'])
        .directive('cMdThemeFg', ["$mdTheming", function ($mdTheming) {
            return {
                restrict: 'A',
                link: postLink
            };
            function postLink(scope, element, attr) {
                $mdTheming(element);
                element.addClass('c-md-fg');
            }

        }])
        .directive('cMdThemeBg', ["$mdTheming", function ($mdTheming) {
            return {
                restrict: 'A',
                link: postLink
            };
            function postLink(scope, element, attr) {
                $mdTheming(element);
                element.addClass('c-md-bg');
            }
        }]);
})();
</pre>
and append
<pre>
.c-md-fg.md-THEME_NAME-theme.md-primary {    color: '{{primary-color}}'; } .c-md-fg.md-THEME_NAME-theme.md-accent {    color: '{{warn-color}}'; } .c-md-fg.md-THEME_NAME-theme.md-accent {    color: '{{warn-color}}'; } .c-md-bg.md-THEME_NAME-theme.md-primary {    background-color: '{{primary-color}}'; } .c-md-bg.md-THEME_NAME-theme.md-accent {    background-color: '{{warn-color}}'; } .c-md-bg.md-THEME_NAME-theme.md-accent {    background-color: '{{warn-color}}'; }
</pre>
into angular-material.js at 13783 line 
<pre>
angular.module("material.core").constant("......  HERE")
</pre>
then i can simply apply c-md-theme-fg and/or c-md-theme-bg to element to apply theme colors
like
<pre>
 &lt;div c-md-theme-bg class="md-primary md-hue-3"&gt;dasdasdasd&lt;/div&gt;
    &lt;span c-md-theme-bg class="md-primary"&gt;test&lt;/span&gt;
</pre>
it work great, 
but i don't really want to modify angular-material.js
anyone can help?

ps: sorry about english, come from Taiwan :)

**Comment by Schnueggel** [comment] 2015-06-13 18:34
I tried to overwrite the $MD_THEME_CSS constant of material.core module and just appending my styles. But no luck.

**Comment by Schnueggel** [comment] 2015-06-13 19:07
When I copy the $MD_THEME_CSS string from angular-material.js into a file and add my rules it works

```javascript
var myrule = require('./myfile-with-$MD_THEME_CSS');
MyModule.constant('$MD_THEME_CSS', myrule);
```

**Comment by senthilprabhut** [comment] 2015-07-03 17:06
I fixed @SimeonC's code to get the theme colors working. Added code for border-color as well.
https://gist.github.com/senthilprabhut/dd2147ebabc89bf223e7

**Comment by TitForTat** [comment] 2015-07-14 16:42
Decided to take a stab at it: https://gist.github.com/TitForTat/b5978c412fe9eb8357b7

use it like...

  <md-button md-style-color="{'background-color': 'hue-1'}">My Button</md-button>
  <md-button md-style-color="{'background-color': '100'}">My Button</md-button>
  <md-button md-style-color="{'background-color': 'warn.hue-1'}">My Button</md-button>
  <md-button md-style-color="{'background-color': 'warn.100'}">My Button</md-button>
  <md-button md-style-color="{'background-color': 'green.100'}">My Button</md-button>

...passing an object where keys will be css properties and values are strings as [pallete].[hue]
Just don't do "green.hue-1" (mixing up pallete name and hue number). it will default to hue 500.
theres probably a better way to use $mdThemingProvider on a directive, but this will do the trick..

**Comment by rschmukler** [comment] 2015-07-20 14:49
@TitForTat really nice approach. Very simple.

**Comment by dh94** [comment] 2015-07-25 16:22
in addition to @TitForTat 
in my use case i had a costume palette defined as the default theme
and that caused an exception, instead of using <code>$mdColorPalette</code>
I kept <code> $mdThemingProvider._PALETTES</code> which contains all the palettes including costume ones
,forked the gist and updated it
https://gist.github.com/dh94/517187e03fdde3c18103

usage stays the same as in @TitForTat post

**Comment by clshortfuse** [comment] 2015-07-25 23:01
Just use $mdColorPalette

I added it to my $rootScope for global use.

.run(function ($rootScope, $mdColorPalette) {
        $rootScope.getMaterialColor = function (base, shade) {            
            var color = $mdColorPalette[base][shade].value;
            return 'rgb(' + color[0] + ',' + color[1] + ',' + color[2] + ')';
        };
});

**Comment by dh94** [comment] 2015-07-31 13:35
@clshortfuse cool function, but i dont think it'll work with costume palettes because mdColorPalette is a constant that doesn't contain costume defined palettes

**Comment by sovanna** [comment] 2015-08-03 10:23
@ThadeuLuz 404 on the gist..

**Comment by ThadeuLuz** [comment] 2015-08-03 14:58
@sovanna sorry about that. fixed.

**Comment by sovanna** [comment] 2015-08-03 15:03
@ThadeuLuz no worries ;) by the way, thank a lot for the gist, I use it in my module and it works perfectly ;)

**Comment by naomiblack** [comment] 2015-08-14 21:24
This is unfortunately more work than we can address before 1.0. However we will continue the discussion.

**Comment by joaogarin** [comment] 2015-09-12 10:22
The solution with $mdColorPalette works nicely!;) Hope to see it improved in the 1st beta.

**Comment by BoLaMN** [comment] 2015-09-12 14:39
I thought i would share my version of handling this here https://gist.github.com/BoLaMN/5d3543dc522b35f631de

generates inline styles for each theme and contrasting color as well to handle the background vs text color 

#how to use 

```html
<!-- Red Background, White Text -->
<md-button class="md-warn-default background">My Button</md-button>
<!-- Red Background With hue-2, White Text -->
<md-button class="md-warn-hue-2 background">My Button</md-button>
<!-- Pink Text -->
<md-button class="md-accent-default text">My Button</md-button>
<!-- Pink Background, White Text -->
<md-button class="md-accent-default background">My Button</md-button>

<!-- md-style type object -->
<md-button md-style="{'background-color': 'hue-1'}">My Button</md-button>
<md-button md-style="{'background-color': '100'}">My Button</md-button>
<md-button md-style="{'background-color': 'warn.hue-3'}">My Button</md-button>
<md-button md-style="{'background-color': 'accent.400'}">My Button</md-button>
<md-button md-style="{'background-color': 'green.900'}">My Button</md-button>
```

**Comment by bathos** [comment] 2015-10-12 07:30
[Yet another take](https://gist.github.com/bathos/7ecf15829c0c615d5c97), based on BoLaMN's & others examples. This only adds new classes, .text and .background corresponding to every intention, hue and theme combo, and including the appropriate contrast color when using .background.

**Comment by PieterGoethals** [comment] 2015-11-16 10:54
Been toying around with the same issue last weekend.

I got inspired by SanderElias'es work here:
https://github.com/angular/material/issues/1269

I particular like the way how he generates css once, 
after which no js burden is placed on the browser.

My major issues with his code was how he uses palette's 
and specific hues instead of themes. 

I dont want classes like 'md-fg-100', I want 'md-bg-primary'.

Here is my take on it:

http://plnkr.co/edit/QHIZgiOhhffLF0uQXkFb?p=preview

The first block shows all classes using the default theme.
The second block shows how all classes change using a specific theme.

In your example you could use the class md-bg-primary,
which would also apply the default foreground color.

The theme-specific example does assume the class 'md-theme-theme' 
gets applied either to the element itself, or an ancestor of the element.
Angular Material does this on md- elements, however on others 
you might have to do this yourself.

Unfortunately I'm rather new to angular, so I couldn't make
my code integrate as nicely as he did. I could copy-paste 
part of his code, and probably get it to work, but i'm not 
fond of using code I don't understand.

**Comment by manish2535** [comment] 2016-02-04 19:19
Any news when or if this is going to be natively available?

**Comment by lobo-tuerto** [comment] 2016-02-29 15:02
Is `$mdColor` service coming to Angular Material?

**Comment by Kratos-SA** [comment] 2016-03-02 09:04
+1

**Comment by arthurspa** [comment] 2016-03-03 18:18
+1

**Comment by noilly** [comment] 2016-03-06 05:03
+1

**Comment by h4x3rotab** [comment] 2016-03-07 02:42
+1

**Comment by steveg3003** [comment] 2016-03-08 19:23
+1

**Comment by j-hogue** [comment] 2016-03-09 20:48
+1

**Comment by jfcere** [comment] 2016-03-16 19:43
+1

**Comment by super-coder** [comment] 2016-03-20 12:07
but palettes including custom are actually available at .config
`$mdThemingProvider._PALETTES;` 
have a look http://codepen.io/anon/pen/qZrRNy, i am just using a global variable, may be someone can improve the codepen?

**Comment by patorjk** [comment] 2016-03-23 19:33
+1

**Comment by dongorous** [comment] 2016-03-28 13:10
+1

**Comment by sandronm** [comment] 2016-03-29 15:58
+1

**Comment by Schlesiger** [comment] 2016-04-02 21:05
+1

**Comment by lukemiller** [comment] 2016-04-05 19:45
+1

**Comment by rguruprakash** [comment] 2016-04-08 06:58
+1

**Comment by happy-ali** [comment] 2016-04-08 10:03
+1

**Closed** 2016-04-12 22:10 UTC
Labels: for: internal contributor, type: build, type: enhancement, type: feature

**Comment by homerjam** [comment] 2016-04-14 11:55
+1

**Comment by EladBezalel** [comment] 2016-04-14 11:58
@homerjam you can have this feature in 1.1.0-rc3

**Comment by homerjam** [comment] 2016-04-14 12:04
Thanks - just had to refresh the docs! 😊

**Comment by lobo-tuerto** [comment] 2016-04-14 13:41
The `mdColors` directive is listed in the documentation, but the `$mdColors` service isn't.

**Comment by EladBezalel** [comment] 2016-04-14 16:47
#8036 :)

**Comment by Rahul-Giri** [comment] 2016-07-13 14:07
+1

**Comment by EladBezalel** [comment] 2016-07-13 17:39
@Rahul-Giri thisis already in check [here](https://material.angularjs.org/latest/demo/colors)
