### ISSUE TITLE
chips(autocomplete): closes when scrollbar is clicked

### ISSUE THREAD

**Issue by opozo** [angular/material#11962] opened 2020-07-16 00:27 UTC
This issue #4625 is now happening in Chrome, assuming #11625 generated this regression bug.

AngularJS Version: 1.6.4
AngularJS Material Design Version: 1.1.20
OS: macOS
Browser: Chrome
Screencast: https://drive.google.com/file/d/1xifHh-qJw2TPc6jdOFVz-DvOu0ECvn5i/view

**Comment by Splaktar** [comment] 2020-07-17 21:43
Can you reproduce this on https://material.angularjs.org/1.1.24/demo/autocomplete? I can't using macOS Catalina.

What are you scrolling settings? I tried all of them on the docs site and couldn't reproduce this.
![Screen Shot 2020-07-17 at 17 40 34](https://user-images.githubusercontent.com/3506071/87832808-ca982c80-c854-11ea-9f8f-def01841a8dc.png)

Does your app have some custom scrollbar treatment? It looks like it does, likely to do [this](https://github.com/angular/material/issues/5064). That might be causing the problem.

**Comment by opozo** [comment] 2020-07-22 20:23
I removed custom scrollbar styles, but the issue is still happening: 

Screencast: https://drive.google.com/file/d/1J1ihN3Wjok88_f1TIDgZPZWI0Kc0E9wf/view

I was not able to reproduce the issue on https://material.angularjs.org/1.1.20/demo/autocomplete, I'm using macOS Mojave, this is my scroll bar settings:

![scroll-bar-setting](https://user-images.githubusercontent.com/29585940/88224871-78715580-cc1e-11ea-92d2-f6421e609d57.png)

**Comment by Splaktar** [comment] 2020-07-29 19:29
OK, I was able to create an Optimize account and find that screen. I can indeed reproduce the issue there in the app (using AngularJS Material 1.1.20).

I also noticed that this is an `md-chips` that has an `md-autocomplete` inside of it. I tried that in a [CodePen](https://codepen.io/Splaktar/pen/XWXLjPY) but was not able to reproduce the issue.

I'll try to see if the dialog that contains the autocomplete is causing the problem next.

**Comment by Splaktar** [comment] 2020-07-29 20:16
I can confirm that the click event is causing the autocomplete's input to get blurred. This doesn't happen in my CodePen, but does happen in the app.

**Comment by opozo** [comment] 2020-07-29 20:45
Maybe this commit might have caused the issue: 

https://github.com/angular/material/commit/5b0c9ba9e0e5313925f6a27390559f32028fd95b#diff-dfc7d490c731a45e66ad22d8efb7456d

**Comment by Splaktar** [comment] 2020-07-29 20:49
I managed to create a [CodePen](https://codepen.io/Splaktar/pen/VweJmQj?editors=1010) with a chips autocomplete in a dialog, but I'm also not able to reproduce the issue there.

Could you possibly fork and tweak it to reproduce the issue? I don't know what options you used for `$mdDialog.show`, etc.

**Comment by Splaktar** [comment] 2020-07-29 20:52
> This commit might have caused the issue:
> 
> [5b0c9ba#diff-dfc7d490c731a45e66ad22d8efb7456d](https://github.com/angular/material/commit/5b0c9ba9e0e5313925f6a27390559f32028fd95b#diff-dfc7d490c731a45e66ad22d8efb7456d)

The issue is reproducible in AngularJS Material 1.1.20 and that commit didn't go in until v1.1.22. It's possible that that commit could fix this issue, but I don't have a reproduction, so I can't check that.

**Comment by Splaktar** [comment] 2020-09-20 23:01
Closing as unable to reproduce. I'm happy to re-open if a demo reproduction can be provided.

**Closed by Splaktar** 2020-09-20 23:01 UTC
Labels: g3: reported, needs: demo, os: macOS, resolution: can't reproduce
