### ISSUE TITLE
Keyboard focus outlines remain, intended?

### ISSUE THREAD

**Issue by Bodom78** [angular/material#4732] opened 2015-09-20 08:45 UTC
Example, If I use the keyboard to tab through a signin form to get to the button this triggers the outlines on all interactable elements.

These then remain for the remainer of the user experience.

I was wondering if this is the intended behaviour?

**Comment by topherfangio** [comment] 2015-09-21 09:29
Can you possibly provide a demo or some instructions on how to reproduce this on the demo site?

Also, what browser are you using? When I tab through input elements, they do not receive the `outline` styles as we have removed those.

**Comment by Bodom78** [comment] 2015-09-22 00:39
Here is a screen shot of the outline from the button demo section of the material site showing the outline. Using the latest Firefox 40.0.3

![outline](https://cloud.githubusercontent.com/assets/139152/10008735/dc5c22e2-6115-11e5-93b2-0f1e39893dfb.jpg)

I can confirm that there are no outlines in Chrome 45 or IE11

**Comment by marcysutton** [comment] 2015-09-22 18:27
This is expected behavior. Firefox adds a default outline that helps keyboard users see where they are on a page. Recommended this stay as-is.

**Comment by topherfangio** [comment] 2015-09-22 18:38
@marcysutton I believe he was saying that as he tabbed through, the outline was staying even if focus moved to something else.

@Bodom78 Is this correct? I cannot reproduce this on Firefox 40.0.3.

**Comment by marcysutton** [comment] 2015-09-22 18:53
Buggy focus ring persistence would be a problem. However, I also couldn't repro it in FF on Mac or Windows. Any more details you can provide will help!

It should be noted there are color contrast issues with buttons in Material Design that make them difficult to see as you TAB with the keyboard. The dotted outline in Firefox helps users with that problem...coincidentally, a popular browser for accessibility. Granted, the style is different than other browsers, but in this case it really helps keyboard users. http://webaim.org/projects/screenreadersurvey5/#browsers

**Comment by Bodom78** [comment] 2015-09-23 00:35
Sorry, I should have explained the scenario better. 

Now I believe it might be an issue with the menu component after using the keyboard for navigation.

* User tabs at some point in the application and accessibility outlines appear on the buttons.
* Continue to use application with mouse.
* Later in the application they open a menu via a mouse click, the focused menu item will have the outline.

You can replicate on the angular demo site in Firefox.
* From any page tab to trigger outlines on an element.
* Go to the menu demo page and open one with the mouse. It will have outlines like the image below.
* This remains the case from when keyboard navigation is used until the page is refreshed.

![outline2](https://cloud.githubusercontent.com/assets/139152/10035509/5589cdfe-61de-11e5-8767-dc273eb9bd0e.jpg)

Also this is not the case with a Select component, it has no outlines after the same scenario.

**Comment by topherfangio** [comment] 2015-09-23 14:50
Just tested, and I definitely see the issue; although I'm not entirely sure the best course of action. Regardless, we should probably make all of the elements behave the same way.

**Comment by ThomasBurleson** [comment] 2016-04-28 20:27
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).

**Closed** 2016-04-28 20:26 UTC
Labels: needs: investigation, priority: low
