### ISSUE TITLE
menu: elements disappear when not in focus on IE 11

### ISSUE THREAD

**Issue by MustafaASK** [angular/material#11226] opened 2018-04-11 09:35 UTC
### Bug, feature request, or proposal:
menu items, in IE11, when not in focus are not visible, sometimes (screenshot attached). They appear only when hovered upon.

### What is the expected behavior?
All menu items should be visible even when not in focus.

### What is the current behavior?
menu items, in IE11, when not in focus are not visible, sometime

### Which versions of AngularJS, Material, OS, and browsers are affected?
Angular JS 1.6.9
Angular Material 1.1.8

### Is there anything else we should know? Stack Traces, Screenshots, etc.
Screenshot attached.
![ie flickering issue](https://user-images.githubusercontent.com/31955617/38608882-3e186eb0-3d9a-11e8-9826-8b9e6cf7643c.png)

**Comment by svenank3r** [comment] 2018-08-30 10:49
I cannot provide consistent reproduction steps. I tried to create a JsFiddle/CodePen/etc... but they all don't work in IE11 or don't support IE11 anymore.

All I can say is that i can still reproduce the problem in my application. The only case where the menu does work (and gives similair results to yours), is if the md-menu is used within a md-list.

I am using Angular 1.7.2 and Angular Material 1.1.10 right now.

**Comment by Splaktar** [comment] 2018-08-30 17:15
Thank you for the feedback.

FYI: You can create a CodePen with Chrome and then view the Debug mode in IE11 for testing.

**Comment by svenank3r** [comment] 2018-08-30 21:08
Created a CodePen with Debug mode, but couldn't reproduce the issue.

I could however (sort of) reproduce the issue on the material website (in IE11). I switched to the 1.1.6 version, opened the demo of the menu and pressed the menu of the first example. Resulting in the following: 

![image](https://user-images.githubusercontent.com/16895047/44879073-e9b16380-aca8-11e8-82d2-7838d170c864.png)

I can reproduce the issue within release 1.1.6, 1.1.7 and 1.1.8. Once you move your mouse/hover over the menu items, they will all appear and the problem will be unable to reproduce unless you change to one of the other mentioned versions.

Maybe in this way you will be able to reproduce the problem.

**Comment by ShaikASK** [comment] 2018-09-07 12:52
Thanks  @svenank3r & @Splaktar .
The temporary fix (disabling the transition) works great.

**Comment by Splaktar** [comment] 2018-09-18 00:32
@MustafaASK and @svenank3r can you please provide your version of Windows and IE11?

**Comment by svenank3r** [comment] 2018-09-18 07:31
- IE11 version 11.0.9600.19078
- Windows version: 8.1 Enterprise / Version 6.3 (Build 9600)

**Comment by Splaktar** [comment] 2018-09-18 21:30
Here's the latest IE11 patched version that is on Windows 10 now:
IE Version: 11.285.17134.0
Update Version: 11.0.85 ([KB4457426](https://support.microsoft.com/en-us/help/4457426/cumulative-security-update-for-internet-explorer)) from 9/11/2018

I'm not exactly sure at what point this was fixed in IE11, but it appears that it might have been fixed sometime in the last few years.

Is anyone seeing this problem running Windows 10? If so, can you please post your IE and Update version?

**Comment by Splaktar** [comment] 2019-02-15 17:21
This looks like it's specific to very old EOL'd versions of IE11. A workaround is provided and patches to IE11 are available for non-EOL'd versions of Windows. Closing as no feedback has been provided and the workaround seems to be acceptable.

**Closed by Splaktar** 2019-02-15 17:21 UTC
Labels: P4: minor, browser: IE, for: external contributor, needs: feedback, resolution: can't reproduce, type: bug

**Comment by grokgit** [comment] 2019-09-10 14:50
I noticed that problem occurs when right scroll is enabled on IE11 for example when page is too long to fit in window height.

IE11 version: 11.1268.16299.0
Win10 version: 10.0.16299 Build 16299

Thank you svenank3r. Turning off the transition improved visibility of items in menu.
