### ISSUE TITLE
md-icon inside of md-fab with md-font-icon is vertically off center.

### ISSUE THREAD

**Issue by c89memcpy** [angular/material#2603] opened 2015-04-28 18:46 UTC
An md-icon within an FAB md-button as shown below is not vertically center. The icon drops to the bottom of the FAB.
```html
<md-button class="md-fab">
  <md-icon md-font-icon="mdi-content-forward"></md-icon>
</md-button>
```

This seems to be a regression possibly related to #1504.
This is demonstrated in the following plunker.
http://run.plnkr.co/plunks/uPaYU3yQEJFD0ItaeZfZ

**Edit**: The version I am testing with is 0.9.0-rc2

**Comment by ThomasBurleson** [comment] 2015-04-28 19:54
Duplicate of #2597

**Closed by ThomasBurleson** 2015-04-28 19:54 UTC
