### ISSUE TITLE
md-sidenav possibility to push the main content instead of covering it

### ISSUE THREAD

**Issue by herbalizer404** [angular/material#6975] opened 2016-02-02 13:31 UTC
I'm trying to change the sidenav behavior, to push the main content instead of covering it.
When I put the position of the sidenav in relative en display:none the backdrop, I almost have the behavior I'm looking for, but the animation is laggy. Do you have a solution for that, or do you have planned to choose type of behaviour for sidenav. Thx

**Comment by DevVersion** [comment] 2016-02-02 13:36
That's a duplicate of 2208

**Closed** 2016-02-04 16:50 UTC
