### ISSUE TITLE
Style issue on md-chips

### ISSUE THREAD

**Issue by rahulgnair** [angular/material#2095] opened 2015-03-31 06:35 UTC
Style issues on md-chips demo page closable chips
https://material.angularjs.org/#/demo/material.components.chips 
![screenshot from 2015-03-31 12 00 06](https://cloud.githubusercontent.com/assets/3088601/6913460/2c2bb67c-d79e-11e4-9c26-76430a6b993c.png)

**Comment by styx** [comment] 2015-03-31 07:07
Duplicate of #2081

**Closed** 2015-03-31 21:57 UTC
