### ISSUE TITLE
placeholder autocomplete not working fine. it's hiden

### ISSUE THREAD

**Issue by AdwardNguyen** [angular/material#9680] opened 2016-09-23 10:32 UTC
**i used lasted material and angular js v1.5.x, i try and config by css but placeholder not showing. 
when i press Ctrl+A, i can see it, please fix it**
![aaa](https://cloud.githubusercontent.com/assets/22392606/18783030/1bbea1f4-81bc-11e6-9747-fa95e44dba3d.png)

````
<style type="text/css">
     md-autocomplete md-autocomplete-wrap input::-moz-placeholder,
    md-autocomplete md-autocomplete-wrap input:-moz-placeholder,
     md-autocomplete md-autocomplete-wrap input::-webkit-input-placeholder {
        color: red; margin:0; text-align:left; padding:0; display:normal; opacity:1; flex:none; vertical-align:text-top;
    }

    md-autocomplete md-autocomplete-wrap input {
        color: green;
    }
</style>
<!--<div layout="column" ng-cloak class="md-autocomplete-suggestions-container" >-->
        <md-autocomplete md-selected-item="selectedItem"
                         md-search-text-change="searchTextChangesearchText"
                         md-search-text="searchText"
                         md-selected-item-change="selectedItemChange(item)"
                         md-items="item in querySearch(searchText)"
                         md-item-text="item[displayProperty]"
                         md-min-length="0" placeholder="Test" aria-disabled="false" md-menu-class="autotest-md">
            <md-item-template>
                <!--<span md-highlight-text="ctrl.searchText" md-highlight-flags="^i">{{item.TenBacSi}}</span>-->
                <span md-highlight-text="ctrl.searchText" md-highlight-flags="^i">{{item[displayProperty]}}</span>
            </md-item-template>
        </md-autocomplete>
<!--</div>-->`

**Comment by DevVersion** [comment] 2016-09-23 13:40
Closing this issue due to insufficient information. Please resubmit with:

----
Required
----

**Behavior**:
-  What is the issue? * 
-  What is the expected behavior? 

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue :
-  Details: 

**Angular Versions**: *
-  Angular Version: 
-  Angular Material Version: 

**Additional Information**:
-  Browser Type: *
-  Browser Version: *
-  OS: *
-  Stack Traces: 

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

**Closed by DevVersion** 2016-09-23 13:40 UTC

**Comment by omprakash-sit** [comment] 2019-08-26 11:06
> md-autocomplete-suggestions-container

I am also facing same problem & unable to change placeholder color.
I added background-color to .md-autocomplete-suggestions-container class, It's done, placeholder working fine. :)

**Comment by Splaktar** [comment] 2019-08-29 16:47
@omprakash-sit this issue has been closed for 3 years. Please open a new issue with a reproduction.
