### ISSUE TITLE
docs: Directives links to demos removed

### ISSUE THREAD

**Issue by epelc** [angular/material#1312] opened 2015-01-27 20:54 UTC
The links to the demo pages for all the directives were removed. Can we get them back? They are really helpful to jump around quickly. Also note the links for demos to their directives are there still.

![image](https://cloud.githubusercontent.com/assets/5204642/5926951/feb6f19e-a63c-11e4-968b-ceca0a508e92.png)

**Comment by ilanbiala** [comment] 2015-01-27 21:21
I think it makes much more sense to combine the directive and demo pages into one, but that may have to happen at a later point.

**Comment by epelc** [comment] 2015-01-27 21:29
@ilanbiala I was also just thinking about that. But I figured it'd take a bit and it'd be nice if we could get this back as I imagine it's just part of a template so it should be simple/quick.

**Comment by marcysutton** [comment] 2015-01-27 21:37
That is a bug. The demo buttons should still be there.

**Comment by ilanbiala** [comment] 2015-01-27 21:37
@epelc yep for now we should add the button back, but for 1.0.0 or before, we should really make each the docs code + demo in one place.

**Comment by marcysutton** [comment] 2015-01-27 21:41
@ilanbiala the demos are separate on purpose and are not going to be merged into the API. They exist for non-technical consumers, because not everyone who looks at the docs site is a developer (believe it or not).

**Comment by marcysutton** [comment] 2015-01-27 21:42
Actually there is another pull request about to be merged that will update the buttons. Not a bug.

**Closed** 2015-01-27 21:42 UTC

**Comment by ilanbiala** [comment] 2015-01-27 22:05
@marcysutton can you provide a link here to that PR?

**Comment by marcysutton** [comment] 2015-01-27 22:34
@ilanbiala these decisions are the result of a dedicated research and UX phase. I appreciate your enthusiasm, but the docs information architecture will continue to be handled by the Angular Material team. 

The remaining PR is https://github.com/angular/material/pull/1196.

**Comment by marcysutton** [comment] 2015-01-27 23:02
Fixed in f32a5958e3797aaa7b312470ce0473adc72562b9.
