### ISSUE TITLE
md-datepicker doesn't line up with other form elements in layout="row" container

### ISSUE THREAD

**Issue by calebegg** [angular/material#4630] opened 2015-09-14 18:12 UTC
Demo: http://codepen.io/calebegg/pen/KdVWrx

**Comment by EladBezalel** [comment] 2015-09-15 17:36
related #3234

**Comment by jelbourn** [comment] 2015-09-15 17:53
Closing as a dupe of #3234 (which covers all of the form elements lining up).

**Closed by jelbourn** 2015-09-15 17:53 UTC
Labels: reported by Googler
