### ISSUE TITLE
md-autocomplete not showing some suggestions

### ISSUE THREAD

**Issue by wil93** [angular/material#5606] opened 2015-11-07 17:27 UTC
It worked correctly with 1.0.0-rc2:

![old](https://cloud.githubusercontent.com/assets/1285361/11016294/f1a016dc-857c-11e5-95ad-37b4695dd29e.png)

Now I upgraded to 1.0.0-rc3 and it doesn't show some suggestions:

![new1](https://cloud.githubusercontent.com/assets/1285361/11016301/1f510550-857d-11e5-8b68-e3f447a4eb81.png)

After scrolling a bit, more suggestions appear:

![new2](https://cloud.githubusercontent.com/assets/1285361/11016302/279ea55a-857d-11e5-93b6-5cf980ef7110.png)

**Comment by gpopovic** [comment] 2015-11-07 17:53
+1

**Comment by Patrik-Lundqvist** [comment] 2015-11-09 13:19
Yeah, I'm having this problem too

**Comment by idoo** [comment] 2015-11-09 13:27
Temporary fix for this problem is:
```
.md-virtual-repeat-container.md-autocomplete-suggestions-container
  height: 120px
```

**Comment by hillerstorm** [comment] 2015-11-09 13:37
Fixed by reverting 330419b

issue: #5561 

How could this even get merged without checking first?
That PR in it's entirety was awful... suggestions for changes without anything being done, still gets merged.

**Comment by kseamon** [comment] 2015-11-09 17:26
This isn't reproducing for me on the Autocomplete demo page. Can someone post an example?

**Comment by kseamon** [comment] 2015-11-09 17:37
Question for those affected by this: Is your autocomplete in an ng-hide? If so, #5579 should fix it.

**Comment by hexadecy** [comment] 2015-11-09 21:36
1.0.0-rc3
Autocomplete > Inside Dialog
There is only 3 items displayed at a time.

**Comment by wil93** [comment] 2015-11-10 03:50
@kseamon: my autocomplete is not *in* an ng-hide, but it's *beside* one.

**Comment by blootch** [comment] 2015-11-11 01:01
@kseamon here is gif to reproduce. Try to resize you window and focus on the autocomplete input.

https://cloud.githubusercontent.com/assets/6443098/11017356/b4672164-859c-11e5-92f9-343cc5c9fe85.gif

**Comment by kseamon** [comment] 2015-11-11 17:03
@blootch Thanks - that tells me exactly what I need actually.

**Comment by kseamon** [comment] 2015-11-11 17:19
Ok, made a tweak to #5579 and it fixes this issue.

**Comment by thomasrye** [comment] 2015-11-11 21:46
@idoo That temporary fix is not working for me.

**Comment by kseamon** [comment] 2015-11-11 21:58
Actually it's still busted inside of dialogs... back to investigating...

**Comment by blootch** [comment] 2015-11-12 20:52
@kseamon with pleasure. I think this issue has something to do with md-virtual-repeat.

**Comment by wil93** [comment] 2015-11-15 16:32
I confirm this is fixed in 1.0.0-rc4

**Comment by gabguy** [comment] 2015-11-17 06:39
The issue is still here in 1.0.0-rc4

**Comment by lillylykho** [comment] 2015-11-17 06:41
+1 
not working for me in 1.0.0-rc4

**Comment by gligoran** [comment] 2015-11-18 10:41
+1 The issue still here in 1.0.0-RC4.

**Comment by kseamon** [comment] 2015-11-20 16:42
I'm not seeing it in rc4. Those who are seeing it: what browser are you using? Are you just looking at the demo page, or some other page? If another page, what other libraries are you using?

**Comment by gabguy** [comment] 2015-11-22 08:35
@kseamon Go into https://material.angularjs.org/latest/demo/autocomplete and search for 'California', then 'Shift'+'Home' to mark the intire word and press 'Delete', you will see the issue...

**Comment by wil93** [comment] 2015-11-23 00:07
I managed to reproduce this (and I actually found it easier to reproduce *without* the "Simulate query" option).

This is what I see when I reproduce the bug:
![bug](https://cloud.githubusercontent.com/assets/1285361/11327189/8af0f178-917e-11e5-8452-8bf3cb5de6f8.png)

As you can see there are only 4 virtual-repeat elements, when 5 are needed.

This, instead, is what I see when I don't reproduce it (or when I reproduce it *and then* resize the window a bit, and "California" magically appears):
![no bug](https://cloud.githubusercontent.com/assets/1285361/11327190/8f307fc4-917e-11e5-871c-ebfecfac4090.png)

Now there are 6 elements.

**Comment by kseamon** [comment] 2015-11-25 16:27
Ok, this takes care of the version of the bug as described by @gabguy and @wil93. Closing, but let me know if you find yet another case of it.

**Closed by kseamon** 2015-11-25 16:27 UTC
