### ISSUE TITLE
fix(tabs, select): broken on accent colors

### ISSUE THREAD

**Issue by EladBezalel** [angular/material#9324] opened 2016-08-17 00:21 UTC
## mdTabs
![tabs](https://i.gyazo.com/0f3e188c4dd2551f9f695969a0bf359b.png)
## mdSelect
- label has primary color
- selected item has primary color

> can't provide pictures, based on input focus

**Comment by clshortfuse** [comment] 2016-09-17 05:08
I was going about fixing these colors and then came to a realization.

I think `md-tabs` should work like `md-toolbar`, meaning if you use `md-primary`, `md-accent`, or `md-hue`, you should have a colored bar. Right now, everything defaults to white/transparent.

Ideally speaking, we should allow users to do write this

```
<md-toolbar class="md-accent">...</md-toolbar>
<md-tabs class="md-accent"> ...
```

to achieve this
![screenshot 2016-09-17 at 1 06 50 am](https://cloud.githubusercontent.com/assets/9271155/18606089/08148360-7c73-11e6-92e5-8238b4e4a7b3.png)

**Comment by clshortfuse** [comment] 2016-10-14 01:08
Closing this since it only appears reproducible with custom CSS.

**Closed by clshortfuse** 2016-10-14 01:08 UTC
Labels: needs: demo, P1 - Broken Renders / Major Use Cases, resolution: can't reproduce, ui: theme
