### ISSUE TITLE
Missing accordion/collapsible service

### ISSUE THREAD

**Issue by diogodomanski** [angular/material#3532] opened 2015-07-01 14:19 UTC
It would be great to have services that allow us to create collapsible elements (like accordions or any other content) as Bootstrap (http://getbootstrap.com/javascript/#collapse) and Materialize (http://materializecss.com/collapsible.html).

**Comment by marcysutton** [comment] 2015-07-01 16:58
This is a duplicate of #1861, a feature that has been discussed but isn't a priority for 1.0. Closing.

**Closed by marcysutton** 2015-07-01 16:58 UTC
