### ISSUE TITLE
List Controls Demos don't have scroll when opened in codepen

### ISSUE THREAD

**Issue by super-coder** [angular/material#7216] opened 2016-02-19 18:57 UTC
http://codepen.io/anon/pen/QyRZpM
i checked both Chrome and Firefox 
![image](https://cloud.githubusercontent.com/assets/2155554/13185750/a1fe7ad2-d73a-11e5-8ec5-781a9fe84292.png)

**Comment by DevVersion** [comment] 2016-02-20 13:16
Can reproduce, just wan't to summarise:
-  Codepen demos from **HEAD** are not affected, because the `demo.css`script is not injected probably.
- Relases are affected, because the `demo.css` is referenced / injected correctly. 

For example in HEAD builds the `docs.css` will be injected using the current commit SHA and not the latest release tag. (Like so - https://material.angularjs.org/master-9e7937e/docs.css)

So the actual problem on releases' demo is:
```
body {
  overflow: hidden;
  max-width: 100%;
  max-height: 100%;
}
```

I'm not sure why the `overflow` property was added.
cc @EladBezalel

**Closed** 2016-02-25 17:07 UTC
Labels: ui: CSS
