### ISSUE TITLE
ng-click affects list item style

### ISSUE THREAD

**Issue by amitport** [angular/material#3373] opened 2015-06-20 13:52 UTC
While experimenting with the [list example](https://material.angularjs.org/latest/#/demo/material.components.list) I've noticed that removing ng-click handler from `md-list-item` messes up the styling - 

Concretely, secondary button is miss-aligned in the 'avatar with secondary action button' example.

**Comment by topherfangio** [comment] 2015-09-04 19:42
Indeed, without the `ng-click`, the icon does not get wrapped with a button and the styling is a bit off. Out of curiosity, what is the use-case for the icon without a button?

**Comment by topherfangio** [comment] 2015-09-04 19:44
Just saw, this is a duplicate of #3176. Closing in favor of that one which has a codepen.

**Closed by topherfangio** 2015-09-04 19:44 UTC
Labels: priority: low, ui: CSS
