### ISSUE TITLE
mdautocomplete searchText model always trimed

### ISSUE THREAD

**Issue by bayucandra** [angular/material#7828] opened 2016-04-01 01:47 UTC
Hi, i wonder why when i get value from searchText model at mdAutoComplete always trimmed. Actually i need untrimmed value for programmatically check if user type space at the end of input field with ng-keyup directive
Can i get untrimmed value of searchText?

**Comment by DevVersion** [comment] 2016-04-01 09:13
Duplicate of #7140 and related to #4492

**Closed by DevVersion** 2016-04-01 09:13 UTC
