### ISSUE TITLE
defineTheme: custom palettes cannot be used

### ISSUE THREAD

**Issue by 0101adm** [angular/material#10341] opened 2017-01-31 20:24 UTC
**Actual Behavior**:
 -  `What is the issue? *`
custom palettes (created at config block, asynchronously) cannot be assigned asynchronously using defineTheme (at run block).
 -  `What is the expected behavior?`

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
 -  `Details:`

**Angular Versions**: *
 -  `Angular Version:` 1.5.8
 -  `Angular Material Version:` 1.1.3

**Additional Information**:
 -  `Browser Type: *`
 -  `Browser Version: *`
 -  `OS: *`
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by Splaktar** [comment] 2018-08-17 08:42
Closing as duplicate of https://github.com/angular/material/issues/10335.

**Closed by Splaktar** 2018-08-17 08:42 UTC
Labels: resolution: duplicate
