### ISSUE TITLE
Templates for angular-material?

### ISSUE THREAD

**Issue by vijayrawatsan** [angular/material#4608] opened 2015-09-12 20:39 UTC
Are there any website/admin templates using angular-material framework. For example templates using bootstrap are available.

**Comment by idpokute** [comment] 2015-09-13 03:36
If you are not looking for free, there are several admin templates such as following: 
http://themeforest.net/item/materil-angular-material-design-admin-template/11062969

**Comment by vikasprogrammer** [comment] 2015-09-13 07:08
You can try here as well - https://www.xtendify.com/en/templates/angularjs-material/

**Comment by vijayrawatsan** [comment] 2015-09-13 11:03
Thanks guys, but these are very few to choose from. Plus the themeforest one includes bootstrap and jquery as well.

**Comment by carlosafonso** [comment] 2015-09-13 11:18
This one is also built over angular-material. It also comes with some custom components built on top of it:

http://triangular.oxygenna.com/#/dashboards/analytics

**Comment by ThomasBurleson** [comment] 2015-09-13 15:45
@here - Please continue conversation in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial). 

This is a duplicate of  #4473

**Closed by ThomasBurleson** 2015-09-13 15:45 UTC
