### ISSUE TITLE
broken list area from input text field in md-autocomplete

### ISSUE THREAD

**Issue by nikhilbytes** [angular/material#8109] opened 2016-04-19 12:23 UTC
https://material.angularjs.org/latest/demo/autocomplete

this issue is related to demo of md-autocomplete. if one clicks on text  box and type something , one list populates the data to auto-complete the word , now click on text box and mouse wheel down without shaking your mouse pointer from text box. you will get a broken list populating data far down from text box.
![image](https://cloud.githubusercontent.com/assets/16681835/14638965/9815f9e0-0657-11e6-8a1f-96891c046e52.png)

**Comment by DevVersion** [comment] 2016-04-19 13:05
@nikhilbytes This seems to be a duplicate of #5890. 

If I'am wrong with marking this as a duplicate, please let me know and I will reopen the issue.

**Closed by DevVersion** 2016-04-19 13:05 UTC
