### ISSUE TITLE
UX on Windows Phone

### ISSUE THREAD

**Issue by mbeckenbach** [angular/material#1905] opened 2015-03-14 07:27 UTC
I tried out the demo pages on a Lumia 930.
One of worst UX I have ever experienced. 

Don't know if its only the demo pages or the library. Everything is slow. Real slow.

Phone gets real hot after a while. So CPU usage must be high. 

Scrolling is almost impossible as the screen jumps up and down without any logic. 

Touch gestures like swipe left or right in the tabs sometimes work. Sometimes cause history back. Sometimes do nothing. 

Some of the demo input fields cannot be focused. 

Grid list shows... Nothing. 

If you don't have a WP for testing get one and try it. Don't think that is what the UX should be like.

This project is awesome. But we cannot create web apps that don't run on the most common phones. And yes: I know lots of people with windows phones already. :)

**Comment by mbeckenbach** [comment] 2015-03-14 07:30
Ah. One more thing: The dialog modal is not very phone friendly. It should be displayed fixed to the top or even better full screen on a phone.

**Comment by naomiblack** [comment] 2015-03-16 18:12
This is a tough problem for us to solve -- we don't have anyone on the core team who is super familiar with Windows Phone OS and how we might resolve these issues. I would welcome someone from the community with experience who would be interested in diving into these issues and proposing some solutions. We're currently focusing on WebKit support / Android and iOS because the number of users is so much larger, but this is an area I would be happy to do better on for Microsoft devices.

**Comment by mbeckenbach** [comment] 2015-03-17 07:08
As far as I understand what MS said, it is using the same internet explorer as Surface does on the desktop. I have a Surface RT 1 here. Let me have a look if it behaves similar. 

WP's market share is around 10% in Europe. But that's millions of users. So Angular material should work there.

Has anyone tried if its just the docs and demo page? What I've seen was that the CPU usage was very high. So maybe the demo page is simply to complex for the phone?

Unfortunately I don't have an iPhone or android here. But I have three different windows phones here from different generations for testing if you need more feedback.

**Comment by mpiasta-ca** [comment] 2015-03-26 00:08
It's slow even on Nexus 5 and iPhone 6 too lol (at least when testing the website http://material.angularjs.org). Our team is also weary of committing to the project because of the slow performance right now. It's much too slow in the current form.

**Comment by marcysutton** [comment] 2015-03-30 21:54
A big performance improvement landed a few days ago, something to keep in mind: https://github.com/angular/material/issues/1989

**Comment by fals** [comment] 2015-05-14 14:38
I had the same issue acessing from Lumia 830. The site performance kills the phone.

**Comment by zikzxak** [comment] 2015-05-17 08:22
It's kind of awkward to develop a website that doesn't work on every phone. Here in Finland WP market share is over 20% (over 50% in business phones). Support needed asap :/

**Comment by mbeckenbach** [comment] 2015-05-20 14:08
I did some testing in the last days. With the current master it got better. But there are strange issues regarding tabs and dynamic content height. Still not the best UX on WP. Germany is only at arround 7% with WP but it's getting more every quarter

**Comment by mpiasta-ca** [comment] 2015-05-20 18:01
@mbeckenbach We shouldn't spend time improving Windows mobile performance, because then users might mistaken it for a serious smartphone device /troll

Android and iOS accounted for [96.3% of the smartphone market](http://www.idc.com/getdoc.jsp?containerId=prUS25450615) in 2014. If you buy a Windows device, you're on your own! lol

Supporting Windows and Blackberry is equivalent to throwing money in a shredder.

**Comment by ThomasBurleson** [comment] 2015-05-20 19:02
@mpiasta-ca - Angular and Angular Material has a published [Code of Conduct](https://github.com/angular/code-of-conduct/blob/master/CODE_OF_CONDUCT.md) Plz do not submit such comments on this repository. Even if intended as humorous, the above comments can be interpreted as otherwise.

**Comment by renato04** [comment] 2015-05-21 13:48
I just have started to develop an app and it has an acceptble performance on  windows phone devices for now.

**Comment by justingrayston** [comment] 2015-05-21 15:32
Tested the demo site a little on a Lumia 735 the other day. Seemed ok to
me. Will do some more tomorrow and log anything specific.

**Comment by justingrayston** [comment] 2015-06-04 01:24
Added #3110 showing demo site side nav performance issues.

**Comment by chuckamus-prime** [comment] 2015-07-16 20:01
Same with IE on windows 8.1, the demo site demo's very poorly. The performance issue can be seen in the number of JS issues that show up using IE's developer tools. It explodes! likely the cause of the slowdown/overheating with the phone. I need this fixed too, both for the phone and for IE on the desktop. I dont know how it can be said to support n-1 browser versions when the css is !terribly broken! for IE on windows 8.1.

**Comment by karneaud** [comment] 2015-07-22 21:12
i have a lumina windows phone 8.1.  works cool but experiencing bugs with checkbox and misc. angular attributes

**Comment by ThomasBurleson** [comment] 2015-09-04 18:05
This has become a general dumping ground... please submit concise individual issues.

**Closed** 2015-09-04 18:05 UTC
Labels: type: performance

**Comment by karneaud** [comment] 2015-09-05 13:28
The framework doesn't work on Windows Phone....how concise do we need to be again?

**Comment by maciejpuchala** [comment] 2016-01-28 15:48
When do you think it would be works on Windows Phone? We started project, without knowledge that it does not work and this is a hugh problem for us now. Does any one know some solutions to fix this shit on WP?
