### ISSUE TITLE
mobile devices: Can't close md-autocomplete on without selecting an item and input remains focused on outside touch.

### ISSUE THREAD

**Issue by robert-maftei** [angular/material#7594] opened 2016-03-16 16:05 UTC
The autocomplete won't close on touch outside the autocomplete menu. The only way to close the autocomplete is to select an item.

This issue also appears on inputs, the focus remains on the input even if you touch an outside area.

To reproduce (tested in chrome emulator and on android 5.0):
Open angular material website in chrome emulator:
https://material.angularjs.org/latest/demo/autocomplete
https://material.angularjs.org/latest/demo/input

**Comment by topherfangio** [comment] 2016-03-16 18:22
Duplicate of #7419.

**Closed by topherfangio** 2016-03-16 18:22 UTC
