### ISSUE TITLE
press enter key will add empty chip in md-autocomplete inside md-chips

### ISSUE THREAD

**Issue by qjlee** [angular/material#4087] opened 2015-08-10 22:24 UTC
Go to section "Use md-autocomplete to build an ordered set of chips." on the latest release demo site ( https://material.angularjs.org/0.10.1-rc5/#/demo/material.components.chips)

Enter 'b' in the textbox, there are two items showing up in the autocomplete dropdown, use keyboard to navigate to the any of the items in the dropdown and press enter key and an empty chip will be added to the chips control.

![angular_material_-_demos___chips](https://cloud.githubusercontent.com/assets/75322/9185803/14aef878-4013-11e5-9c0e-3668bb83c424.png)
![angular_material_-_demos___chips2](https://cloud.githubusercontent.com/assets/75322/9185804/14b6dee4-4013-11e5-9098-6f693b9a8b2b.png)

**Comment by qjlee** [comment] 2015-08-10 22:38
seems like a duplicate of https://github.com/angular/material/issues/3900

**Comment by typotter** [comment] 2015-08-12 00:08
Dupe of #3475

**Closed by typotter** 2015-08-12 00:08 UTC
