### ISSUE TITLE
Contact Chips: filter-selected doesn't work

### ISSUE THREAD

**Issue by alphatwit** [angular/material#4101] opened 2015-08-11 18:30 UTC
In the contact chip demo, even with filter-selected="true", I still see selected contacts in the auto-complete menu.

Unless I missed the purpose, I expected that, once "Marina Augustine" is selected, that "Marina Augustine" will no long appear in the auto-complete dropdown list.

**Comment by topherfangio** [comment] 2015-09-04 16:20
Closing in favor of duplicate of #4131, which has more discussion. Please add any new comments to that issue.

**Closed by topherfangio** 2015-09-04 16:20 UTC
