### ISSUE TITLE
Menu freezes whole app on Chrome

### ISSUE THREAD

**Issue by yoorek** [angular/material#5178] opened 2015-10-15 09:31 UTC
angular-material 0.11.4, Chrome  45.0.2454.101, Mac OS X 10.11

1. go to: https://material.angularjs.org/latest/demo/menu
2. click on any menu e.g phone - it opens but whole app stops responsing (scrolling, clicking, nothing works), no error in console

FF, Safari, Canary works OK

**Comment by ThomasBurleson** [comment] 2015-10-15 09:39
@rschmukler - I wonder if this is a scroll-mask issue ?

**Comment by kschwidder** [comment] 2015-10-15 13:52
Can not reproduce on my machine with the same setup. it works as expected

**Comment by ThomasBurleson** [comment] 2015-10-15 14:31
@kschwidder - Thx Kai.

**Comment by e-oz** [comment] 2015-10-15 14:35
Chrome Version 46.0.2490.64 beta (64-bit), OS X 10.11, can't reproduce

**Comment by ThomasBurleson** [comment] 2015-10-15 14:43
@e-oz - Thx Evgeniy. 

Closing.

**Closed** 2015-10-15 14:43 UTC
Labels: resolution: can't reproduce
