### ISSUE TITLE
md-autocomplete sets inline styles on body 

### ISSUE THREAD

**Issue by marino-oneshoe** [angular/material#3409] opened 2015-06-23 07:42 UTC
If you use md-autocomplete you get an extra scrollbar (overflow-y: scroll-y). When you don't have a scrollbar like on the angular material demo page you get one. 

It's maybe better to set a class on the body instead of inline styling. This way you can overwrite this a lot better. i'm not completely sure why this is implemented but i'm sure there is a reason behind this. 

When you do get a scrollbar the width of md-item-template could be rendered wrong. This happens when you use a autocomplete with flexible width and reacts on the full width. In other words it's exactly the width of scrollbar. 

![screen shot 2015-06-23 at 09 36 38](https://cloud.githubusercontent.com/assets/10463804/8301115/80ea86f0-198b-11e5-989d-da87e52d3d73.png)

![md-autocomplete-issue](https://cloud.githubusercontent.com/assets/10463804/8300852/7d8352aa-1989-11e5-9905-ac09b3686ed9.jpg)

**Comment by robertmesserle** [comment] 2015-06-26 15:41
This was a temporary bug and should have been resolved in master - can you confirm that this is still broken on HEAD?

**Comment by robertmesserle** [comment] 2015-06-26 15:42
Closing for now, unable to reproduce - will re-open on update.

**Closed by robertmesserle** 2015-06-26 15:42 UTC

**Comment by marino-oneshoe** [comment] 2015-06-29 09:08
No still happens in master.
or is the https://material.angularjs.org/ is out of date?

OSX: Yosimite
Version: 10.10.3

Chrome Version 43.0.2357.130 (64-bit)

If you testing on a mac you have to connect a mouse, or change the the settings on your mac:
![howto-always-show-scroll-bars-mac-os-x](https://cloud.githubusercontent.com/assets/10463804/8404644/d51140e4-1e4e-11e5-83fa-43574b6ae48f.jpg)


for example:
https://material.angularjs.org/latest/#/demo/material.components.menu
![screen shot 2015-06-29 at 11 00 59](https://cloud.githubusercontent.com/assets/10463804/8404559/29fba0fa-1e4e-11e5-8ac5-3e48f1fa5703.png)

**Comment by marino-oneshoe** [comment] 2015-06-29 09:14
sorry my bad!

Different issue... autocomplete seems to be fixed!
Other elements like md-menu still has this issue. But use issue:  
https://github.com/angular/material/issues/3432
to avoid duplicates

**Comment by jayakrishnapulipati** [comment] 2017-11-09 13:27
Plz refer this 
https://github.com/angular/material/issues/10952

by setting the height as **AUTO** works perfectly :)

**Comment by jalchr** [comment] 2017-12-15 11:59
As @jayakrishnapulipati said making this in my css, fixed it 
```
body {
    height: auto;
}
```
