### ISSUE TITLE
FAB-toolbar should be shown on mouseenter md-fab-trigger only

### ISSUE THREAD

**Issue by lizatop** [angular/material#3314] opened 2015-06-17 08:34 UTC
If you want to use the FAB-toolbar as an actual floating button, meaning you want to let it float above other content, it's not really practical. 

The fact that the toolbar is triggered by a mouseenter of the md-fab-toolbar makes it impossible to, for instance, click links that are in the content underneath the md-fab-toolbar. As soon as you get anywhere near that link with your mouse, the toolbar appears, blocking access to the link.

It would be a lot better if the toolbar is actually triggered by a mouseenter of the md-fab-trigger.

**Comment by xforceco** [comment] 2015-06-17 11:21
I agree and it is similar when it comes to fab speed dial

**Comment by seishin4real** [comment] 2015-06-17 11:36
I agree!

**Comment by mukilane** [comment] 2015-06-17 15:32
Possible duplicate of #3214

**Comment by topherfangio** [comment] 2015-06-23 17:42
@lizatop Can you please look at [my comment on #3214](https://github.com/angular/material/issues/3214#issuecomment-114572940) and see if the proposed solution will solve this issue? If so, I will close this in favor of the other issue.

**Comment by lizatop** [comment] 2015-06-23 18:33
Thank you for your response Topher.
Your proposed solution seems to solve my issue, so you can close it.

2015-06-23 19:43 GMT+02:00 Topher Fangio <notifications@github.com>:

**Comment by topherfangio** [comment] 2015-06-23 19:29
Closing in favor of #3214.

**Closed by topherfangio** 2015-06-23 19:29 UTC

**Comment by lanmower** [comment] 2015-08-20 11:26
This issue should not have been closed, #3214 does not solve the problem that is presented here, the complaint is that its not just the trigger that is a hit area, its the invisible children that also act as a hit area.

**Comment by lanmower** [comment] 2015-08-20 11:27
Please re-open this issue, since #3214 is a separate and unrelated matter.

**Comment by topherfangio** [comment] 2015-08-20 13:31
@lanmower I think we may need to create a separate issue as this was indeed closed. If you look at the latest version of the demos (https://material.angularjs.org/HEAD/#/demo/material.components.fabToolbar) you will see that you must click on the trigger to open it (clicking/hovering anywhere else does nothing).

However, I did notice that you cannot click things underneath the toolbar as it "pre-allocates" the necessary space for the expansion. I think this is a separate issue and something that should definitely be fixed. If this is what you are referring to, would you mind opening a new issue and tagging me in the description?

**Comment by lanmower** [comment] 2015-08-20 13:51
Yes! thank you for the response, I'm on it! :)
