### ISSUE TITLE
md-autocomplete: multiple calls of md-selected-item-change and md-search-text-change

### ISSUE THREAD

**Issue by divashutin** [angular/material#4919] opened 2015-09-29 17:17 UTC
I'm running into the following case - when you remove selection in autocomplete and try to reopen it - extra event is fired for setting the changed item. Moreover when I do a simple $watch on binding value I see that on item removal the value is set to null first, and then to undefined. When I click autocomplete it's set from undefined back to null.

This is reproduced on Basic Usage example from spec (made a codepen copy https://codepen.io/anon/pen/wKoOQE)

Steps performed:
1) click autocomplete
  Console output:
    Text changed to
2) click any item in opened list (for example, "Alaska")
  Console output:
    Item changed to {"value":"alaska","display":"Alaska"}
3) click on black space to ensure that focus is out
4) click "x" icon to remove selection
  Console output:
    Text changed to 
    Item changed to undefined
    Item changed to undefined
5) click on black space to ensure that focus is out
6) click autocomplete to open list
  Console output:
    Text changed to 
    Item changed to undefined

The full console output is:
Text changed to 
Item changed to {"value":"alaska","display":"Alaska"}
Text changed to 
Item changed to undefined
Item changed to undefined
Text changed to 
Item changed to undefined

**Comment by robertmesserle** [comment] 2015-11-23 19:37
Duplicate of #3003

**Closed by robertmesserle** 2015-11-23 19:37 UTC
Labels: reported by Googler
