### ISSUE TITLE
md-checkbox no check visible inside table

### ISSUE THREAD

**Issue by icchio** [angular/material#4093] opened 2015-08-11 14:12 UTC
Hello,
i'm trying to use md-checkbox inside a table:
![schermata 2015-08-11 alle 16 03 56](https://cloud.githubusercontent.com/assets/9406133/9199430/9a296ef0-4042-11e5-8940-2df6baabe750.png)
it doesn't show the mark inside when checked....is just my problem or someone else has the same issue? 
Thank You

**Comment by topherfangio** [comment] 2015-11-03 15:38
Are you still seeing this in master? If so, can you please provide a Codepen to show us the issue?

**Comment by topherfangio** [comment] 2015-11-23 15:58
Please provide a Codepen so that we know whether or not this is still a reproducible issue.

**Comment by ThomasBurleson** [comment] 2016-04-25 22:24
Closing this issue due to insufficient information. Please resubmit with:

----
Required
----

**Behavior**:
-  What is the issue? * 
-  What is the expected behavior? 

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue :
-  Details: 

**Angular Versions**: *
-  Angular Version: 
-  Angular Material Version: 

**Additional Information**:
-  Browser Type: *
-  Browser Version: *
-  OS: *
-  Stack Traces: 

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

**Closed by ThomasBurleson** 2016-04-25 22:24 UTC
Labels: - In Progress, needs: demo, needs: investigation, P4 - Reported By or General PRs/Errors or Edge Cases, ui: CSS, ux: integration
