### ISSUE TITLE
md-autocomplete sets selected-item to null on second load

### ISSUE THREAD

**Issue by map7** [angular/material#7567] opened 2016-03-15 03:40 UTC
I'm using Angular-Material 1.0.6 (also found this bug on 1.1.0rc1) with AngularJS 1.5.0

When I navigate through AngularJS routes to my edit form I have a debtor autocomplete box with the following

```
<md-autocomplete flex="20" required
           md-input-id="invoice_debtor"
           md-input-minlength="2"
           md-input-maxlength="18"
           md-selected-item="invoice.debtor"
           md-search-text="searchText"
           md-items="debtor in debtors"
           md-item-text="debtor.fullname"
           md-floating-label="Debtor">
           <md-item-template>
           <span md-highlight-text="debtor.fullname">{{debtor.fullname}}</span>
           </md-item-template>
           </md-autocomplete>
```

On the very first load this works perfectly, and redirects me to the invoice listing. If I select that invoice again then this md-autocomplete will clear my invoice object when loaded, so I cannot edit the invoice. If I use the following for my autocomplete instead everything works fine.

```
     <md-input-container  class="md-block input_font">
        <label>Debtor</label>
        <input ng-model="invoice.debtor"
               typeahead-on-select="change_debtor()"
               typeahead="debtor as debtor.fullname for debtor in debtors | filter:{fullname: $viewValue} | limitTo:10"
               ng-blur="validate_debtor()"
               focus-me>
      </md-input-container>
```

Problem with this is it's using the typeahead plugin instead of the built in material autocomplete.

**Comment by topherfangio** [comment] 2016-03-16 19:28
Can you please provide a Codepen that demonstrates the issue? It is very hard to track down issues based on small snippets of code because we will have a hard time reproducing the exact situation :smile:

**Comment by ksgupta** [comment] 2016-04-07 00:40
+1

**Comment by ThomasBurleson** [comment] 2016-04-25 22:09
Closing this issue due to insufficient information. Please resubmit with:

----
Required
----

**Behavior**:
-  What is the issue? * 
-  What is the expected behavior? 

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue :
-  Details: 

**Angular Versions**: *
-  Angular Version: 
-  Angular Material Version: 

**Additional Information**:
-  Browser Type: *
-  Browser Version: *
-  OS: *
-  Stack Traces: 

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

**Closed by ThomasBurleson** 2016-04-25 22:09 UTC
Labels: - In Progress, needs: demo
