### ISSUE TITLE
disabled fieldset does not affect md inputs

### ISSUE THREAD

**Issue by breandr** [angular/material#2299] opened 2015-04-13 21:34 UTC
Standard field inputs become disabled if their parent fieldset is disabled. This is not true for mdSwitch, and mdSelect. I haven't tested the others, but I'm assuming they have the same issue. I'm using version 0.8.3.

**Comment by marcysutton** [comment] 2015-05-20 18:57
Closing as duplicate of https://github.com/angular/material/issues/2417.

**Closed by marcysutton** 2015-05-20 18:57 UTC
