### ISSUE TITLE
autocomplete: clearing the input disables displaying the dropdown on focus

### ISSUE THREAD

**Issue by jul1ans** [angular/material#10283] opened 2017-01-19 13:21 UTC
**Actual Behavior**:
 -  `What is the issue? *` When I close the keyboard on android devices and then clear the autocomplete input (clicking the x), I can't open the dropdown again. Only if I type something, the dropdown opens again.
 -  `What is the expected behavior?` After clearing the input and clicking again inside the input, the dropdown with all results should open. 

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` This also happens with the basic usage demo https://material.angularjs.org/latest/demo/autocomplete
 -  `Details:` Click inside the input
Select something
Close the keyboard 
Click the X / Clear the result
Click inside the input again

**Angular Versions**: *
 -  `Angular Version:` 1.5.8
 -  `Angular Material Version:` 1.1.1

**Additional Information**:
 -  `Browser Type: *` Chrome for Android
 -  `Browser Version: *`  tested on 52 and 55
 -  `OS: *` Android 6.0
 -  `Stack Traces:`

**Comment by Splaktar** [comment] 2018-02-27 20:12
I can reproduce on the latest docs site (1.1.7).

**Comment by mjgerace** [comment] 2018-06-01 22:32
This occurs for me as well. Any workarounds?

**Comment by AndrusovaK** [comment] 2018-10-30 15:31
Hi, I need your help.
I tried to use possible fix from https://github.com/angular/material/issues/10834#issue-248001061 with 1.1.10 locally, but it doens't work for me.

After clearing the input I can't even make input focused again and so I can't type anything to make it work.
Input become focused only if I use long press (as if I want to highlight text). But in this case keyboard is not shown.

Is it the same issue or a different one?

**Comment by Splaktar** [comment] 2018-11-01 20:42
I've got a fix for the [related issue](https://github.com/angular/material/issues/10834) in PR https://github.com/angular/material/pull/11500. However, testing on Android shows that the fix for that issue doesn't help with this Chrome for Android issue.

After testing this some more on Chrome for Android 70, I found that it's hard to get the autocomplete in the Basic Demo usage to focus and/or open the drop down at all. This applied to AngularJS Material 1.1.5, 1.1.10, HEAD, and another branch where I merged in all of the open autocomplete a11y PRs.

This doesn't appear to affect autocompletes that use `md-floating-label`. These are wrapped in an `md-input-container` while non-floating label autocompletes are not.

I am able to get focus on the autocomplete and open the dropdown if I long press or sometimes when I double tap. However, focus should happen with a single tap.

**Comment by AndrusovaK** [comment] 2018-11-09 15:52
@Splaktar thanks for your reply!

 I'll try to use autocomplete with `md-floating-label` for now.

**Comment by AndrusovaK** [comment] 2018-11-13 15:31
Hi, @Splaktar!
I've tried to use `md-floating-label` autocomplete with `md-clear-button="true"` and `md-min-length="0"` attributes. In this configuration it has same focus problems on Android as regular autocomplete, unfortunately.

I tested it with 1.1.10 and HEAD, here is [example](https://codepen.io/andrusova_k/full/MzJrdW/) from demo page with `md-clear-button="true"` and `md-min-length="0"` attributes.

**Comment by Splaktar** [comment] 2019-09-08 22:27
@AndrusovaK I tried your CodePen with Chrome 76 and Android 9 and I was unable to reproduce any focus issues.

Additionally, the changes in PR https://github.com/angular/material/pull/11782 appear to have fixed these issues. I can verify that these issues still exist in [1.1.20](https://material.angularjs.org/latest/demo/autocomplete) and not in [HEAD](https://material.angularjs.org/HEAD/demo/autocomplete). This will be part of the `1.1.21` release.

**Closed by Splaktar** 2019-09-08 22:27 UTC
Labels: P1: urgent, browser: Android, g3: sync, needs: investigation, type: bug, ux: polish
