### ISSUE TITLE
md-maxlength doesn't update immediately if model content is updated in javascript

### ISSUE THREAD

**Issue by Sam-Davis** [angular/material#1870] opened 2015-03-11 10:15 UTC
Steps to reproduce: 
1. create a textarea with md-maxlength="500" ng-model="modelitem.description"
2. create a button with a function that updates modelitem.description to be null

issue - the couter of characters used next to the text area will not update, it will stay as 32/500 for example. It will only update once the user starts typing again. 

This is in version 0.7.1

**Comment by bradmartin** [comment] 2015-07-09 14:25
+1 still present in current master.

**Comment by gauravbhavsar** [comment] 2015-08-24 11:53
+1

**Comment by gauravbhavsar** [comment] 2015-08-24 13:07
here is the [plunker](http://plnkr.co/edit/cUZO9yQOvZKsGz9h0fYU?p=preview) for work around.

**Comment by scspijker** [comment] 2015-09-07 15:37
:+1:  Still not working. If like me, you have a clearForm function, you might not want the watch from gauravbhavsar's example. Simply make your md-maxlength get the length from your controller:

    <input type="text" ng-model="ctrl.description" md-maxlength="ctrl.maxLengthDescription">

And then in your clearForm() method, reset the maxLength (like the watch does):

    _clearForm(form) {
      this.description = "";

      // Known issue, md-maxlength does not update on model change
      // https://github.com/angular/material/issues/1870
      this.maxLengthDescription = 500;
      $timeout(function () {
        this.maxLengthDescription = 30;
      })

      form.$setPristine();
      form.$setUntouched();
    }

**Comment by andrew-cunliffe** [comment] 2015-11-20 15:51
:+1: 

An easy work around for this is to also include the ng-maxlength attribute like so...

```
    <md-input-container>
        <label>Description</label>
        <textarea name="description"
                  required="required"
                  md-maxlength="500"
                  ng-maxlength="500"
                  ng-model="ctrl.summaryDescription"></textarea>

        <div ng-messages="form.description.$error">
            <div ng-message="required">Description is required</div>
            <div ng-message-exp="['md-maxlength', 'maxlength']">Description is too long</div>
        </div>
    </md-input-container>
```

... this appears to 'work' better however introduces / highlights another issue that I have raised here #5853

**Comment by claire921** [comment] 2016-03-18 18:26
+1

**Comment by sunil-ideas2it** [comment] 2016-03-21 10:52
Anyone got this thing fixed. I am facing the same issue

**Comment by scspijker** [comment] 2016-04-29 06:57
@ThomasBurleston this is fixed in a new release?

**Comment by steve-mcqs** [comment] 2016-05-05 11:21
Still happening for me.

**Comment by DevVersion** [comment] 2016-05-05 11:47
@steve-mcqs This issue was closed by our [Spring Cleaning](https://groups.google.com/forum/#!topic/ngmaterial/3Ip9nd68bfk).

But as I'm able to reproduce that bug, I'll reopen that issue.

**Comment by pawelbujna** [comment] 2016-08-30 06:29
Ok, I don't know if it helps You, but for me fix like this works:

>angular.element('#html-element-' + name).triggerHandler('input'); 

This is a part of directive so thats the reason i use name variable. You just have to trigger(Handler) input event.

**Comment by besharati-behzad** [comment] 2016-09-16 05:43
I wrote a simple code that could solve this problem

**in your view:**
md-maxlength="vmCtrl.getMaxLen(30)"

**in your controller:**

var fakeMaxLen;
vmCtrl.getMaxLen = function (value) {
      if (fakeMaxLen)
            return fakeMaxLen;
      return value;
 };

// call this function after your data model was changed and you need to update char counter
function callMeWhenYouNeedToResetCharCounter(){
        fakeMaxLen = 100000;
        $timeout(function(){
              fakeMaxLen =undefined;
              vmCtrl.form.$setPristine();
              vmCtrl.form.$setUntouched();
        });
}

// you can disable animation of .md-errors-spacer class and set visibility to hidden, when process started
// and return back to original state after the process finalized (in timeout function)
// it's just for smoother working and prevent char counter flickering

**Closed** 2016-10-14 17:23 UTC
Labels: has: Pull Request, priority: low
