### ISSUE TITLE
md-switch ripple turns on when window gets focus

### ISSUE THREAD

**Issue by jsr6720** [angular/material#7837] opened 2016-04-01 13:10 UTC
Browser Chrome Canary: Version 51.0.2696.0 canary (64-bit)
Manufacturer............Hewlett-Packard
Model...................HP EliteDesk 800 G1 SFF
OS Version..............Windows 7

Steps to reproduce:
1. Open two chrome windows side by side.
2. Go to https://material.angularjs.org/latest/demo/switch in one of them
3. Click on any enabled switch element (must be switch, not associated label)
4. Click to focus on other browser window
5. click back on original window

See below image. "Switch 1" has ripple even though my mouse is not near the toggle.

![image](https://cloud.githubusercontent.com/assets/502432/14207598/22387a8a-f7e9-11e5-9bcb-b5359a58298a.png)

**Comment by DevVersion** [comment] 2016-04-01 13:45
This is actually not an issue, the focus on the switch is just restored by the browsers behavior.

**Comment by jsr6720** [comment] 2016-04-05 14:18
@DevVersion Can you please re-open this issue. This ripple effect occurs even on the 'no ripple' boolean

See screen shot

![image](https://cloud.githubusercontent.com/assets/502432/14284963/c41995ba-fb17-11e5-83cd-03f24ffdd89c.png)

**Comment by DevVersion** [comment] 2016-04-05 14:26
@jsr6720 Please explain, how we can reproduce that *bug*? I'm not able to reproduce it by your steps above.

**Comment by jsr6720** [comment] 2016-04-05 14:50
Same steps as above. I just confirmed in Google Canary
1. Go to  https://material.angularjs.org/latest/demo/switch
2. Click the TOGGLE next to "no Ink" label
3. Open new blank tab
4. Switch back to tab with demo in it.

![image](https://cloud.githubusercontent.com/assets/502432/14286157/1bdadada-fb1c-11e5-88a6-9b074b29bea4.png)

**Comment by jsr6720** [comment] 2016-04-05 20:33
@DevVersion do you still need more information? This is impacting our implementation of md-switch @Paychex

**Comment by DevVersion** [comment] 2016-04-06 04:58
@jsr6720 I will investigate today and look for the correct behavior. Thanks for explanation.

**Comment by DevVersion** [comment] 2016-04-06 15:11
@jsr6720 Just investigated again at this issue. And it's still not an issue. It's also not a ripple, it's just a focus effect, which is added for Keyboard Interaction / a11y. 

The focus effect is always showing, because the browser restores the focus back to the last element. (and that was obviously the switch).

**Comment by angryfatkid** [comment] 2016-04-06 17:32
@DevVersion I can repro this with Chrome.  It happens in both states.  (Note: We also see this on button icons)

1. Set a switch
2. Create a new tab
3. Return to tab with switch

![switch issue](https://cloud.githubusercontent.com/assets/10525022/14326432/30f81ade-fbeb-11e5-8461-93ef28530828.PNG)

**Comment by roytz** [comment] 2016-04-07 06:46
As long as we don't have an option (or attribute) to set this focus off this is a bug.. I don't think we should see the background animation after switching windows..

**Comment by angryfatkid** [comment] 2016-04-07 15:55
Here is behavior we are seeing on the icon button.  Our users asked about it day one of release.  It is really annoying.
![highlight bug](https://cloud.githubusercontent.com/assets/10525022/14357667/db5eeb4a-fca6-11e5-8686-9b7b955ffa97.png)

**Comment by DevVersion** [comment] 2016-04-07 16:06
@angryfatkid @roytz I can now reproduce your issue. I will provide a fix as soon as possible.

**Comment by DevVersion** [comment] 2016-04-07 16:42
- The issue is, we're always applying the focus effect, when there was no click for `100ms`. That means, if you switch the browser tabs, then there will be no click triggered on the button.. only a focus event (which adds the focus effect)

So, we need a way to detect the last interaction type. A PR is already pending - #5589, which means, that this issue is currently blocked.

cc. @ThomasBurleson

**Comment by angryfatkid** [comment] 2016-04-08 17:17
@DevVersion Thanks!

**Comment by DevVersion** [comment] 2016-05-27 07:44
This issue will be deprecated soon. The actual issue will be tracked in #7963

**Comment by ThomasBurleson** [comment] 2016-06-01 23:58
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Closed** 2016-06-02 01:55 UTC
Labels: needs: merge, ui: focus

**Comment by ThomasBurleson** [comment] 2016-06-02 07:03
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.

**Comment by DevVersion** [comment] 2016-10-26 14:07
Note: This has been solved in `master` now https://material.angularjs.org/HEAD/demo/switch
