### ISSUE TITLE
docs(progressLinear): sideNav constant flickering

### ISSUE THREAD

**Issue by eshell** [angular/material#8282] opened 2016-04-30 02:01 UTC
https://material.angularjs.org/latest/demo/progressLinear

Ubuntu 16, Google Chrome.

While viewing this particular demo, if I scroll up and down a few times it causes major flickering in the sidenav. Does the same for progressCircular demo. The other demos do not seem to cause this.

**Comment by RolandHeath** [comment] 2016-05-03 01:11
I'm on fedora 22, chrome 50.0.2661.75 (64-bit), trying (and failing) to replicate.
Do you see this when scrolling the sidenav, or when scrolling the demo? Which version of chrome are you using?

**Comment by eshell** [comment] 2016-05-03 02:15
Version 50.0.2661.94 (64-bit)

It seems to be happening while moving the mouse around a lot and not the scrolling itself. Load the page, move the mouse quickly up and down the sidebar links a few times and that's when the flickering occurs. after a while it will stop, then if i close and re-open the demo links, repeat, it starts flickering again.

**Comment by crisbeto** [comment] 2016-05-03 05:34
I haven't tried setting up Ubuntu to reproduce this yet, but are you sure it's not an issue with your video drivers? Also it would be nice if you could record a short video of the flickering so we know what we're looking for.

**Comment by eshell** [comment] 2016-05-03 14:06
https://youtu.be/RXD5Q5RQkL4

I don't think its my drivers... never had a problem with any other sites. Play wow at 100fps on high settings. I don't know.

**Comment by crisbeto** [comment] 2016-05-03 14:08
I see what you mean. I'll try setting up Ubuntu to reproduce it.

**Comment by eshell** [comment] 2016-05-05 12:31
also happens at materializecss progress demo: http://materializecss.com/preloader.html

**Comment by crisbeto** [comment] 2016-05-05 13:30
Just installed Ubuntu on a VM, but I still couldn't reproduce it neither on 1.0.8 nor 1.1. I'm running Ubuntu 16.04 and Chrome 50.0.2661.94.

**Comment by eshell** [comment] 2016-05-05 18:30
looks like it just may be my drivers then. i have no idea how to test that though.

**Comment by crisbeto** [comment] 2016-05-05 19:38
I'll close this one for now, but it can always be re-opened if something new comes up.

**Closed by crisbeto** 2016-05-05 19:38 UTC
Labels: needs: investigation, P4 - Reported By or General PRs/Errors or Edge Cases
