### ISSUE TITLE
md-select-label not correctly set

### ISSUE THREAD

**Issue by markscholtz** [angular/material#1942] opened 2015-03-17 17:07 UTC
When creating a list and model bound to an md-select, the md-select-label is not populated correctly when this is done asynchronously. 

See [this pen](http://codepen.io/markscholtz/pen/vEQaeM?editors=101) for an example of the issue.

**Comment by marcysutton** [comment] 2015-03-17 19:09
There are also accessibility label issues with select, captured in https://github.com/angular/material/issues/1893.

**Comment by rschmukler** [comment] 2015-03-25 22:10
The issue is that with non-primitive values (ie. `ng-model` is an object), select can't really guess how to render them.

@markscholtz what do you think about the idea having an attribute of `md-bootstrap-selected-value="str"`. This way, the developer can specify something before the options have loaded.

**Comment by mathieubrun** [comment] 2015-03-30 14:56
It appears for primitive values as well : http://codepen.io/anon/pen/wBOQrR

Is there a workaround ?

**Comment by markscholtz** [comment] 2015-04-06 20:28
Hey @rschmukler, thanks for looking into this!

In my case ng-model is a primitive. 

I do remember trying to set `md-select-label` manually (which I think I'd have to do if I bound an object to ng-model) and I don't recall seeing this issue. I can confirm this with another example, but in this case I would expect my original Pen to render correctly without needing to add any other attributes to the md-select.

**Comment by rschmukler** [comment] 2015-06-11 19:59
This issue is resolved on master. Must've missed adding the closing tags. Codepen's working as intended above.  Closing.

**Closed by rschmukler** 2015-06-11 19:59 UTC
Labels: bug, G
