### ISSUE TITLE
Datepicker Issues (Release 1.0.2) #6725

### ISSUE THREAD

**Issue by sudharsanmit** [angular/material#6761] opened 2016-01-19 18:31 UTC
Pinned to #6725 . On request of asignee, splitting the issues into multiple tickets.
Standard Day Picker:
Issue 9:
Can see no dates later than Mar 2099 on calendar either thru keyboard scroll or a date input and a calendar open. So, the calendar supports only max 83 years!!

**Comment by jelbourn** [comment] 2016-01-19 19:49
Dupe of #6397

**Closed by jelbourn** 2016-01-19 19:49 UTC

**Comment by sudharsanmit** [comment] 2016-01-19 20:34
@jelbourn Not a duplicate of #6397 which refers to min date and there is no mention of the 83 year limitation of the calendar. 

Kindly re-oepn. @ThomasBurleson
