### ISSUE TITLE
md-select focus issues with md-select-header

### ISSUE THREAD

**Issue by jayeshanandani** [angular/material#9548] opened 2016-09-08 06:43 UTC
**Actual Behavior**:
-  `What is the issue? *` If you look at demo of the md-select-header, on opening the dropdown it gets focused properly to element that is present in md-select at top. But if you scroll down on page in such a way that (depicted in picture attached), the focus is not on md-select-header present at top instead it gets to element of select.
-  `What is the expected behavior?` Focus should always be on top element rather then scrolling down the behavior.

**CodePen** (or steps to reproduce the issue): *
-  `CodePen Demo which shows your issue:` Angular Material Website
-  `Details:` 

**Angular Versions**: *
-  `Angular Version:` 1.5.x
-  `Angular Material Version:` 1.1.1

**Additional Information**:
-  `Browser Type: *` Chrome
-  `Browser Version: *` Latest
-  `OS: *` MAC
-  `Stack Traces:`

![image](https://cloud.githubusercontent.com/assets/3860787/18339536/b1be123a-75bd-11e6-9ade-42a8914db319.png)

---

Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
>   Add more lines if needed.

**Comment by jayeshanandani** [comment] 2016-10-28 09:35
Related to #9146 #9669

**Comment by Splaktar** [comment] 2018-02-27 21:01
Closing as duplicate of https://github.com/angular/material/issues/9146.

**Closed by Splaktar** 2018-02-27 21:01 UTC
Labels: resolution: duplicate
