### ISSUE TITLE
md-select - you cannot use dynamic value for the label/placeholder

### ISSUE THREAD

**Issue by lukaszwado** [angular/material#4304] opened 2015-08-24 11:35 UTC
When use an data to put in the label and data are loaded later than directive was compiled label will not be refreshed. Example:

http://stackoverflow.com/questions/32180258/dynamic-labels-in-angular-material-mdselect

**Comment by rschmukler** [comment] 2015-09-10 16:52
Duplicate of #3909

**Closed by rschmukler** 2015-09-10 16:52 UTC
Labels: priority: medium
