### ISSUE TITLE
md-button fab style using ng-href causes misalignment of icon

### ISSUE THREAD

**Issue by asans** [angular/material#2584] opened 2015-04-27 19:53 UTC
When using md-button as a fab button and using ng-href, the icon inside the fab button is not longer vertically centered.

ng-href causes the md-button to use <a> link element instead of <button> element, which is likely what's causing the issue.

Here's how the fab button looks when ng-href is provided:

![screenshot](https://cloud.githubusercontent.com/assets/17964/7356363/678e31a6-ecdc-11e4-9d55-04727c6abbad.jpg)

**Comment by asans** [comment] 2015-04-27 19:54
This happens in v0.9.0-rc1-master-aff50d5

**Comment by marcysutton** [comment] 2015-04-27 20:45
Hi, please provide a Codepen or Plunker that demonstrates this issue. Thanks!

**Comment by epelc** [comment] 2015-04-28 13:13
This doesn't affect me but it seems to work fine on master.

http://plnkr.co/edit/84vsDgrZuYWHbAfzDLa5?p=preview

**Comment by jgoux** [comment] 2015-04-28 15:05
I can confirm the issue with webfont icons and md-button.
Here is an example : http://codepen.io/jgx/pen/qdEQYK

**Comment by asans** [comment] 2015-04-28 15:33
The bug I have is not what @jgoux described, but can be reproduced with his codepen code by adding the following fab button to his code:

```
  <md-button ng-href="test" class="md-fab md-fab-bottom-right">
    <md-icon md-font-icon="wi wi-umbrella"></md-icon>
  </md-button>
```

This reproduces the exact issue that I'm having when I use his fixed styles.  My icon shows up on the top of the icon instead of on the bottom.

**Comment by ThomasBurleson** [comment] 2015-04-28 16:14
Duplicate of #2597

**Closed by ThomasBurleson** 2015-04-28 16:14 UTC
Labels: Demo Needed
