### ISSUE TITLE
Angular-material not compatible with Angular 1.4.1

### ISSUE THREAD

**Issue by sethx** [angular/material#3325] opened 2015-06-17 13:23 UTC
After upgrading angular and angular-animate to 1.4.1 i get a lot of errors in my console, and things behave quite oddly.

http://postimg.org/image/vpvt98jjf/ for a screenshot of my console.

**Comment by nomack84** [comment] 2015-06-17 13:55
Well, the `$animate` service was completely refactored, so this is normal.

**Comment by sethx** [comment] 2015-06-17 14:03
And that's why i want to open an issue about this.

**Comment by gkalpak** [comment] 2015-06-17 14:04
Possible duplicate of #3280.

**Comment by jlmagee** [comment] 2015-06-17 15:33
@nomack84 There are no commits to indicate significant changes in $animate in 1.4.1

**Comment by csvan** [comment] 2015-06-17 16:04
Confirming this. md-tabs among other things have gone completely bonkers after upgrading to 1.4.1 (content not scrolling, dead animations etc).

**Comment by ShahZafrani** [comment] 2015-06-17 16:46
@csvan I am having the same problem. Only 2 out of 3 tabs on my md-tabs element are showing. My md-select has also gone bonkers.

**Comment by ThomasBurleson** [comment] 2015-06-17 17:29
@matsko - FYI, it appears that 1.4.1 is causing issues with Angular Material.

**Comment by mprokopowicz** [comment] 2015-06-17 18:13
Guys, I think it can be related to #3315

**Closed** 2015-06-17 22:27 UTC

**Comment by ThomasBurleson** [comment] 2015-06-17 22:29
Thx to @mprokopowicz  for the code fixes in mdUtils.
> BTW, @mprokopowicz what process did you use to track the issue source back to `initOptionalProperties()`?
