### ISSUE TITLE
mdAutocomplete: error ngMessages are not shown correctly when md-floating-label is set

### ISSUE THREAD

**Issue by cairomax** [angular/material#8200] opened 2016-04-25 10:50 UTC
Here is a demo:
http://codepen.io/cairomassimo/pen/wGEKPZ

The "Required" error message is not hidden when the field is not in error state, and appears larger.

Workaround: adding the `md-input-message-animation` class to the `ng-message` element fixes this problem.

It seems to have been broken in pull 5637. See this comment:
https://github.com/angular/material/pull/5637#issuecomment-214044391

**Comment by DevVersion** [comment] 2016-04-25 11:00
Duplicate of #7477

**Closed by DevVersion** 2016-04-25 11:00 UTC
