### ISSUE TITLE
mdList Height unnecessary

### ISSUE THREAD

**Issue by alinleonard** [angular/material#8876] opened 2016-06-27 23:18 UTC
**Actual behavior**:
-  What is the issue? 
**WORKING ON FIREFOX** ( NOT WORKING FOR CHROME AND SAFARI )
On a simple mdList at every ListItem it fills the window height with unnecessary space
![capture1](https://cloud.githubusercontent.com/assets/9429650/16398836/31fc2de0-3cd6-11e6-8aee-8e112afc1ad2.PNG)

-  What is the expected behavior?
On 1.0.9 works correctly
![capture](https://cloud.githubusercontent.com/assets/9429650/16398855/6144d444-3cd6-11e6-9b32-9cf41625e2ac.PNG)

**Angular Versions**: 
-  Angular Version: 1.5.3
-  Angular Material Version: 1.1.0-rc2

**Additional Information**:
-  Browser Type: Chrome
-  OS: Windows 10

**Comment by DevVersion** [comment] 2016-06-28 12:24
This should be fixed in `v.1.1.0-rc.5` or `master`.

Please create a demo and confirm. If the issue is still showing up, I'll reopen the issue.

Thanks

**Closed** 2016-06-28 12:24 UTC
