### ISSUE TITLE
md-fab-dial: click event not recognized correctly

### ISSUE THREAD

**Issue by kschwidder** [angular/material#5243] opened 2015-10-18 21:37 UTC
With latest DEMO-HEAD a double click of a md-fab-dial does not recognize correctly a later click event.
In another case the fab-dial immediately opens and closes on a first click.

The current change of the gesture seems to break the behaviour.

Tested on CHROME

**Comment by dohomi** [comment] 2015-10-20 09:17
+1 I see the same problem in current 0.12.0-rc1. Sometimes double click sometimes single click is needed.

**Comment by HBO2** [comment] 2015-10-21 20:38
+1 also a problem in 1.0.0-rc1 After first click it opens and closes and from that point the behaviour is like expected. A click outside the FAB area will it's start all over again.

**Comment by pzmosquito** [comment] 2015-10-22 04:47
+1 the behavior is very inconsistnent

**Comment by sfaizanh** [comment] 2015-10-25 10:43
+1 double click to open for the first time, when i clicked on action button same behavior occur, have to double click on fab icon again to open. [1.0.0-RC1] Tested on Chrome Version 46.0.2490.80 (64-bit)

**Comment by sebakerckhof** [comment] 2015-10-28 19:02
The problem seems to be that sometimes the click event fires twice. So it quickly toggles open state and goes back to the original state.
I've modified the plunkr from the docs so it shows the open state in the console: http://codepen.io/anon/pen/qOYKLQ

Sometimes one click triggers 2 state changes...

If you play around with it a lot, you'll notice that it seems to happen completely random

**Comment by topherfangio** [comment] 2015-10-29 18:32
@all Can you please verify if this is still an issue in master?

We pushed a fix last night (https://github.com/angular/material/commit/32c0fe1891eb658bc57082de0c836c98e99c22cf) and the codepen that @sebakerckhof appears to be working properly (the codepen unfortunately uses a bad URL that always points to the HEAD version of our files; this issue should be fixed in the next release).

**Comment by sebakerckhof** [comment] 2015-10-29 18:41
Ah, that's why I couldn't reproduce it on my other PC this morning, I've been clicking like crazy for 10 minutes :p. Anyway, seems fixed.

**Comment by kschwidder** [comment] 2015-10-29 19:00
@topherfangio Has something changed to open/close the fab-dial ? Now the fab-dial is always open and does not close when clicked.

        <md-fab-speed-dial md-open="uiDial.isOpen" md-direction="right"
                           ng-class="uiDial.selectedMode">
            <md-fab-trigger>
                <md-button md-theme="light-green" class="md-fab md-raised cs-button-new md-mini" aria-label="More">
                    <img src="template/icons/view/ic_more_vert_black_24dp.png">
                    <md-tooltip>{{'TOOLTIP_MENU' | translate}}</md-tooltip>
                </md-button>
            </md-fab-trigger>
            <md-fab-actions>
                <md-button md-theme="light-green" aria-label="{{'PROJECT_CREATE' | translate}}"
                           class="md-fab md-raised md-mini" aria-label="Create project"
                           create-project
                           target="'index.project.engage'">
                    <img src="template/icons/view/ic_book_add_black_24dp.png">
                    <md-tooltip>{{'TOOLTIP_LEADS_ADD' | translate}}</md-tooltip>
                </md-button>
                <md-button md-theme="light-green" ng-click="" gantt-project-list
                           aria-label="{{'PROJECT_GANTT' | translate}}" class="md-fab md-raised md-mini">
                    <img src="template/icons/navigation/ic_dashboard_black_24dp.png">
                    <md-tooltip>{{'TOOLTIP_LEADS_GANTT' | translate}}</md-tooltip>
                </md-button>
                <md-button md-theme="light-green" aria-label="{{'USER_SEARCH' | translate}}"
                           class="md-fab md-raised md-mini" aria-label="Search User"
                           search-user>
                    <img src="template/icons/view/ic_user_search_black_24dp.png">
                    <md-tooltip>{{'TOOLTIP_LEADS_USER_SEARCH' | translate}}</md-tooltip>
                </md-button>
            </md-fab-actions>
        </md-fab-speed-dial>

**Comment by kschwidder** [comment] 2015-10-29 19:03
In addition the HEAD version of the demo page does not react on the open selection of the fab-dial too.
Something seems to be broken too.

**Comment by topherfangio** [comment] 2015-10-29 20:55
@sebakerckhof I am investigating the issue with the "Open" radio button not working.

@kschwidder Can you post a simple Codepen that shows what you mean? You're saying that the FAB is locked open?

**Closed** 2015-10-29 22:53 UTC

**Comment by sebakerckhof** [comment] 2015-10-30 08:27
@topherfangio I see you swapped the radio buttons for a checkbox, is there any particular reason for this? Because now there's another error with radio buttons: http://codepen.io/anon/pen/qOYKLQ

If the state is `open` and you click the `open` radio button once, the fab dial closes.

**Comment by topherfangio** [comment] 2015-10-30 16:04
I did indeed change it to a checkbox intentionally. It was always intended that if you clicked off of the speed dial, it would close it. However, this wasn't working in all browsers, so we fixed this.

Unfortunately, this means that when you click something that modifies the state of the speed dial it still closes because you clicked off of the speed dial.

We're talking about adding a `md-locked-open` directive or something similar to a variety of components so that you can 100% control the open/closed state, but we haven't decided if it is warranted and if it will happen before v1.

Do you have a use-case for opening the speed dial programmatically and this is causing an issue?

**Comment by kschwidder** [comment] 2015-10-30 17:03
I am using the md-Open Attribute which controls the Fab-dial until 0.11.x properly. Has the behaviour changed ? If so we urgently Need a documentation hint too.

**Comment by sebakerckhof** [comment] 2015-10-30 17:58
@topherfangio No use case in mind, just wondering since the demo for fab toolbar wasn't changed, created a PR for that one.

**Comment by clagosarias** [comment] 2019-03-14 09:31
I know it's been ages & this is far more than deprecated but... I ran into a similar issue. I had a button with a `ng-click="toggleFAB()"` that was doing a `$('md-fab-trigger').click()`. Everything worked great, except when I clicked an md-fab-action everything would close but then you would need two clicks to open it again.


Long story short, if you have the chance to modify your vendor Angular-material library you need to comment the `focusout` accessibility function in `fabSpeedDial/fabController.js`.

`      if (event.type == 'focusout' && !closeTimeout) {`
`        // closeTimeout = $timeout(function() {`
`        //   vm.close();`
`        // }, 100, false);`
`      }`

**Comment by Splaktar** [comment] 2019-03-14 19:25
@clagosarias if you can provide a reproduction, please open a new issue with a CodePen demo. If you have a fix, please submit a PR that references that issue. This issue was fixed 4 years ago, so it's probably not too relevant anymore.
