### ISSUE TITLE
Dragging md-switch does not behave like expected.

### ISSUE THREAD

**Issue by motabass** [angular/material#9062] opened 2016-07-18 10:44 UTC
**Actual Behavior**:
 -  `What is the issue? *`
When Dragging the switch (on and off) and doing mouse-up outside the md-switch element, the switch gets animated but state doesn't change. Furthermore dragging an activated switch (swipe right) deactivates the switch because it fires "click" event.
 -  `What is the expected behavior?`
State changes when dragging "ends" outside Element.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` Use Demo

**Angular Versions**: *
 -  `Angular Version:` 1.5.6
 -  `Angular Material Version:` 1.1.0-rc.5

**Additional Information**:
 -  `Browser Type: *` Chrome
 -  `Browser Version: *`  51.0.2704.106 m
 -  `OS: *` Windows 10
 -  `Stack Traces:`

**Comment by DevVersion** [comment] 2016-07-18 11:27
This should be fixed within `master`
> https://material.angularjs.org/HEAD/demo/switch

**Comment by DevVersion** [comment] 2016-07-18 17:43
Just confirmed again, since I was unsure about the details of your issue. This is fixed.

**Closed by DevVersion** 2016-07-18 17:43 UTC
Labels: needs: feedback
