### ISSUE TITLE
md-autocomplete: Should create an ellipsis before the x icon

### ISSUE THREAD

**Issue by epelc** [angular/material#2578] opened 2015-04-27 15:26 UTC
`md-autocomplete` should handle longer text better. Right now it just keeps showing it behind the x icon. Perhaps it could create an ellipsis before the x icon or at least no go behind the icon.

![image](https://cloud.githubusercontent.com/assets/5204642/7350942/3771a5cc-ecd0-11e4-8294-e7106a27506e.png)

**Comment by jgoux** [comment] 2015-04-28 06:48
I think it's a duplicate of this issue : https://github.com/angular/material/issues/2193

**Comment by epelc** [comment] 2015-04-28 13:02
@jgoux They are very similar but I'll keep this open to document the text going behind the x.

**Closed** 2015-05-30 01:55 UTC
