### ISSUE TITLE
.md-errors-spacer visible on toolbar

### ISSUE THREAD

**Issue by pc3b3r** [angular/material#6338] opened 2015-12-16 08:56 UTC
Consider this CodePen:

http://codepen.io/pc3b3r/pen/obbdgY

the .md-errors-spacer element is visible even if there are no errors/hints.

**Comment by xplodwild** [comment] 2015-12-16 09:22
Duplicate of #6214

**Comment by stewones** [comment] 2015-12-16 17:35
+1

**Comment by topherfangio** [comment] 2016-01-06 17:55
Work is currently being done in #6209 to address this.

**Comment by mathiasmoeller** [comment] 2016-01-12 16:00
+1

**Comment by elekzalan** [comment] 2016-03-23 13:26
+1

**Comment by ThomasBurleson** [comment] 2016-04-28 19:46
This issue is closed as part of our deprecation effort.
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).

**Closed by ThomasBurleson** 2016-04-28 19:46 UTC
Labels: - Breaking Change, P1 - Broken Renders / Major Use Cases
