### ISSUE TITLE
md-select strange behavior on ng-model since 0.11.0 | ADDED plunker EXAMPLE

### ISSUE THREAD

**Issue by mm360** [angular/material#4664] opened 2015-09-16 14:03 UTC
Hi,
if we set a string "001" as one of the values in md-select and then click on select to change the value, the model trasform "001" to 1 (in ng-model + view).
The same data with version 0.10 was ok.

with material 0.10.0 -> OK
http://plnkr.co/edit/JuPbfwRnPRHAd9pUAM9U?p=info

with material 0.11.0 -> KO
http://plnkr.co/edit/sJILIrehFcrigQr8ajGF?p=info

Thanks

**Comment by rschmukler** [comment] 2015-09-28 15:47
Duplicate of #4615. Closing.

**Closed by rschmukler** 2015-09-28 15:47 UTC
