### ISSUE TITLE
data-ng-click doesn't work on md-list-item

### ISSUE THREAD

**Issue by stuartm** [angular/material#7463] opened 2016-03-08 17:25 UTC
data-ng-click doesn't work, changing it to ng-click however does.

The data- prefixes are required if you run your project through HTML validation tools - https://docs.angularjs.org/guide/directive#normalization

**Comment by DevVersion** [comment] 2016-03-08 18:02
Yes, this is a known issue and there's already a previous issue. So I'll close this as a duplicate of #4392

**Closed by DevVersion** 2016-03-08 18:02 UTC

**Comment by stuartm** [comment] 2016-03-08 18:04
Apologies, I didn't find the earlier issue when searching
