### ISSUE TITLE
fab-toolbar: links in FAB toolbar disappear and fab-trigger becomes unresponsive when we open site in two tabs

### ISSUE THREAD

**Issue by sandeepmhaske** [angular/material#11834] opened 2020-01-03 12:13 UTC
### What is the expected behavior?
The links in FAB toolbar should not disappear and Fab-trigger should be clickable when we open site in two tabs of same browser.

### What is the current behavior?
The links in FAB toolbar are disappear and Fab-trigger is not clickable  when we open site in two tabs of same browser.

##### Detailed Reproduction Steps: 
1) Open the site in two tabs of same browser.
2) Click on fab toolbar icon of site opened in first tab.
3) Click on fab toolbar icon of site opened in second tab.
4) Go back to first tab and you will observed that links in fab toolbar are disappeared.
5) Go back to second tab and will observed same issue.
6) Also the fab trigger will be observed unresponsive at the end.

### Which versions of AngularJS, Material, OS, and browsers are affected?
AngularJS 1.5.5 
Material 1.0.7
OS - Windows 8
Browser - Chrome

Please refer below link to reproduce the issue:
https://material.angularjs.org/latest/demo/fabToolbar

### Is there anything else we should know? Stack Traces, Screenshots, etc.
PFB screenshots:

Before switching between two tabs:
![fabtoolbar_beforetabswitch](https://user-images.githubusercontent.com/32016266/34986644-36262fe8-fade-11e7-99e5-828a9e59f278.jpg)

After switching between two tabs: 
![fabtoolbar_aftertabswitch](https://user-images.githubusercontent.com/32016266/34986643-35fbdfd6-fade-11e7-8f01-f7e056c4f3b9.jpg)

**Comment by Splaktar** [comment] 2020-01-06 04:39
Closing as a duplicate of https://github.com/angular/material/issues/11071.

The issue matching the reproductions provided so far is https://github.com/angular/material/issues/11760.

**Closed by Splaktar** 2020-01-06 04:39 UTC
