### ISSUE TITLE
mdSelect: ngDisabled prevents options from displaying

### ISSUE THREAD

**Issue by ngraef** [angular/material#1674] opened 2015-02-25 23:55 UTC
Using `ngDisabled` to conditionally disable an `mdSelect` prevents the options from displaying when the select is enabled. Even `ng-disabled="false"` breaks it.

Sample: http://codepen.io/anon/pen/EaRxXa?editors=101

(Related to #1624)

**Comment by ngraef** [comment] 2015-02-26 00:01
Also related to #1646 (or possibly the same issue?). I missed that in my initial search.

**Comment by rschmukler** [comment] 2015-02-27 21:54
Closing as a duplicate of #1646

**Closed by rschmukler** 2015-02-27 21:54 UTC
