### ISSUE TITLE
Datepicker is not scrolling automatically on Firefox

### ISSUE THREAD

**Issue by mjeanroy** [angular/material#10142] opened 2016-12-15 13:50 UTC
**Actual Behavior**:
 -  `What is the issue? *`

The current datepicker does not scroll automatically to the correct month when a date is selected and a max date is set (the problem does not appear with Chrome) and if the datepicker is inside a dialog (everything seems ok outside dialog).

 -  `What is the expected behavior?`

The datepicker should scroll correctly to the appropriate month.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` http://codepen.io/anon/pen/woQmZO?editors=1010
 -  `Details:`

**Angular Versions**: *
 -  `Angular Version:` 1.5.6
 -  `Angular Material Version:` 1.1.1

**Additional Information**:
 -  `Browser Type: *` Firefox
 -  `Browser Version: *` 50.0.2
 -  `OS: *` MacOS (reproduced on Windows and Linux Debian)
 -  `Stack Traces:` None.

----

I tried to debug a lot, and it seems that the problem comes from this [`floor`](https://github.com/angular/material/blob/v1.1.1/src/components/virtualRepeat/virtual-repeater.js#L395) approximation on the `virtual-repeat` container (i.e If I remove `Math.floor , everything is perfect).

Why is a `floor` operation needed? Do you think I can have a workaround until this bug is fixed and available in a new version?

Thank you very much for your help.

**Comment by mjeanroy** [comment] 2016-12-15 14:44
I forgot, here are the screenshots of the problem:

What happens :

<img width="620" alt="screen shot 2016-12-15 at 14 40 08" src="https://cloud.githubusercontent.com/assets/1067361/21228231/55627d92-c2dd-11e6-8258-3a975e1187dd.png">

What should happens:

<img width="556" alt="screen shot 2016-12-15 at 14 40 19" src="https://cloud.githubusercontent.com/assets/1067361/21228237/5c3c7cbc-c2dd-11e6-8154-3c43ea493edd.png">

**Comment by topherfangio** [comment] 2017-01-04 22:19
I can't seem to reproduce this in Firefox 49.0.2 or after upgrading to 50.1.0.

Is this still happening for you after you upgrade? I'm wondering if it was just a glitch in that version of Firefox.

**Comment by mjeanroy** [comment] 2017-01-05 08:31
Hi @topherfangio,

Thanks for your answer.
I confirm I still reproduce it with 50.1.0. My OS is OSX 10.11.6 (El Captain) but I saw the same problem on Linux and Windows 10. I did not test with Firefox 49, so I can't tell you if it worked with this version.

Did you test with the codepen I wrote?

Note that the problem does not appear if:
- The datepicker is not in a modal,
- The selected date is not "before" the current week.

**Comment by topherfangio** [comment] 2017-02-03 22:33
Hi @mjeanroy,

I did indeed test your Codepen on both my mac and my Windows 10 machine (and just tested again) and still cannot reproduce.

That said, we just released version 1.1.3 which had some fixes for the Datepicker. You might try upgrading to see if that fixes your problem.

**Comment by henrymana** [comment] 2017-03-17 23:00
I see the same behavior with 1.3 in my development environment. But unfortunately I haven't identified the reason yet.

I did notice that when using chrome 56.0.2924.87 (64-bit) one of the embedded demos behaves different from the same codepen demo.

https://material.angularjs.org/latest/demo/datepicker

Notice it does not scroll to today's date (march 17th)

![image](https://cloud.githubusercontent.com/assets/17223208/24065739/94c24626-0b2a-11e7-8d6f-ee99b3c76a7d.png)

but the one on the codepen does:

![image](https://cloud.githubusercontent.com/assets/17223208/24065748/a3f77512-0b2a-11e7-9184-a3251cdcb59d.png)


Is there a way to programmatically scroll the datepicker to a specific date? Thank you.

**Comment by henrymana** [comment] 2017-03-18 18:37
This may be a duplicate https://github.com/angular/material/issues/9952

**Comment by henrymana** [comment] 2017-03-18 22:01
master seems to be fixed... https://material.angularjs.org/HEAD/demo/datepicker 

perhaps this fixed the issue: https://github.com/angular/material/issues/10144

**Comment by topherfangio** [comment] 2017-03-21 18:06
Indeed; I'm going to mark this as a duplicate of #9952. We *might* reopen that one as a few people are still having trouble, but it might be an isolated case. Waiting to hear more.

**Closed by topherfangio** 2017-03-21 18:06 UTC
Labels: needs: feedback
