### ISSUE TITLE
Directive for menu ? (as seen in documentation ?)

### ISSUE THREAD

**Issue by warpdesign** [angular/material#3273] opened 2015-06-15 16:25 UTC
Is there a directive for the navigation found on the left (see: https://material.angularjs.org) ?

**Comment by sup3rb0wlz** [comment] 2015-06-15 16:56
I think your looking for "SideNav" 
Demo:
https://material.angularjs.org/0.10.0-rc4/#/demo/material.components.sidenav
Directive:
https://material.angularjs.org/0.10.0-rc4/#/api/material.components.sidenav/directive/mdSidenav
Service:
https://material.angularjs.org/0.10.0-rc4/#/api/material.components.sidenav/service/$mdSidenav

**Comment by plato-cambrian** [comment] 2015-06-15 17:39
Here's the actual html source for the docs sidenav: https://github.com/angular/material/blob/19ad66d1a5954296de68d3f85d78a3522ff488e5/docs/config/template/index.template.html#L16

**Comment by warpdesign** [comment] 2015-06-16 08:34
Actually I meant the sort of tree view, that allows to navigate between each doc's chapter, not the "SideNav".

I fired up the inspector, and didn't notice any directive. Looks like it was hand coded.

**Comment by sup3rb0wlz** [comment] 2015-06-16 14:40
Ahhhh I see. 
Here is the html for it. As you can see ng repeats are used mostly. So I'd guess the menu is in json somewhere. At a glance I'm not quite sure how it works. Set up some breakpoints in the page in chrome to try to figure it out. It's kinda fun to see how people code that type of stuff, well I think it is anyways. 
```
<md-content flex role="navigation">
      <ul class="docs-menu">
        <li ng-repeat="section in menu.sections" class="parent-list-item {{section.className || ''}}" ng-class="{'parentActive' : isSectionSelected(section)}">
          <h2 class="menu-heading md-subhead" ng-if="section.type === 'heading'" id="heading_{{ section.name | nospace }}">
            {{section.name}}
          </h2>
          <menu-link section="section" ng-if="section.type === 'link'"></menu-link>

          <menu-toggle section="section" ng-if="section.type === 'toggle'"></menu-toggle>

          <ul ng-if="section.children" class="menu-nested-list">
            <li ng-repeat="child in section.children" ng-class="{'childActive' : isSectionSelected(child)}">
              <menu-link section="child" ng-if="child.type === 'link'"></menu-link>

              <menu-toggle section="child" ng-if="child.type === 'toggle'"></menu-toggle>
            </li>
          </ul>
        </li>
      </ul>
    </md-content>
```

**Comment by Eksrow** [comment] 2015-06-16 15:06
I think he's referring to the expando feature(https://github.com/angular/material/issues/985).
A lot of people are looking forward to this.(patiently waiting for it myself also).

**Comment by plato-cambrian** [comment] 2015-06-16 16:29
@sup3rb0wlz @warpdesign Here's where the menu scope object is set up in js https://github.com/angular/material/blob/b974f8616d8e403b4e20bcf3684d30532f4f749f/docs/app/js/app.js#L134

**Comment by rschmukler** [comment] 2015-06-28 19:14
Closing as a duplicate of the expando feature, which is slated for 0.11 right now.

**Closed by rschmukler** 2015-06-28 19:14 UTC
