### ISSUE TITLE
MatTable inside MatTable with expandable columns

### ISSUE THREAD

**Issue by alexmitu** [angular/material#11882] opened 2020-03-18 15:42 UTC
Hello.
I have today upgraded the application to Angular 9 and I've noticed some strange behavior. Whenever I'm adding a table inside a mat expandable column, I'm getting an error "ERROR
Error: Duplicate column definition name provided: "name1"."

I have attached two stackblitz links to show the error:
On Angular 8.2:
https://stackblitz.com/edit/angular-wpefut
On Angular 9:
https://stackblitz.com/edit/angular-adqf7a

Same code, different angular versions.

**Comment by codymikol** [comment] 2020-03-18 17:20
Please submit Angular Material questions [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/components/issues ). This repo is for AngularJS Material.

**Comment by Splaktar** [comment] 2020-03-18 17:35
Duplicate of https://github.com/angular/components/issues/18768.

**Closed by Splaktar** 2020-03-18 17:35 UTC
