### ISSUE TITLE
md-tabs md-tab affecting scrolling behavior with ace code editors

### ISSUE THREAD

**Issue by bfalzarano** [angular/material#10442] opened 2017-02-26 09:32 UTC
**Actual Behavior**:
 -  `What is the issue? ` weird auto scrolling behavior when code editors are placed inside a md-tab and you try to select or edit text within the code editors.  Specifically, there are 4 ace code editors inside of md-tab.  if I scroll down to code editor4 and select some text in editor4 the browser window auto scrolls up to code editor1.  
 -  `What is the expected behavior?`  The browser window should not auto scroll up to editor1 when the user clicks in editor 4 to edit or select text.  If I remove the code editors from md-tab then the code editors work fine.  This is only happening when I place the code editors in md-tab

**Plunker** which shows the issue: https://plnkr.co/DgnxFYymmcvLb9vE9Tb2

 -  `Details`: scroll down to editor4 and as soon as you click inside editor4 to select or edit text you are auto scrolled up to editor1.  Now if you click on the `toggle view` button at the top of the page then the code editors are not placed inside any tabs and the code editors work fine. 

**Angular Versions**:
 -  `Angular Version:` tried several different versions from v1.3.7 to v1.6.1 
 -  `Angular Material Version:` tried several different versions from 1.1.0 to 1.1.3

**Additional Information**:
 -  `Browser Type:` Chrome and FireFox  
 -  `Browser Version:` Chrome 56.0.2924.87 FireFox 46.0.1
 -  `OS:` OSX 10.10.5
 -  `Stack Traces:`

**Comment by bfalzarano** [comment] 2017-02-26 18:43
**quick update:**  so I figured out a workaround using `md-nav-bar` and `md-nav-item` instead of `md-tabs` and `md-tab`  Can anyone provide some details as to why the auto scroll issue occurs using `md-tabs` and `md-tab`? thanks

In the Plunker demo below click on `toggle view` button and you will see that the auto scrolling does not occur when using `md-nav-bar` and `md-nav-item` workaround.

Plunker demo is here:  https://plnkr.co/ZScWItS5UQal1ZKFBB3d

**Comment by hamzahamidi** [comment] 2018-02-06 12:09
I have the same issue issue using Angular5 & can't seem to reproduce it!

**Comment by Splaktar** [comment] 2018-02-11 04:13
@hamzahamidi this repo is for AngularJS Material. Please see https://github.com/angular/material2 for Angular Material (for Angular v4/v5+).

**Comment by Splaktar** [comment] 2018-02-11 04:20
`md-tabs` are designed to hold small, basic templates. Adding in multiple code editors or tables to an `md-tab` will lead to issues with scrolling and performance. 

For anything more significant (like long forms, tables, code editors, etc) in addition to 'page level navigation', then `md-nav-bar` should be used instead. This is briefly mentioned in the [docs](https://material.angularjs.org/latest/api/directive/mdTabs) but it could be stated a little more clearly.

I'm glad that you found your way to the proper solution. Closing this as it is working as intended.

**Closed by Splaktar** 2018-02-11 04:20 UTC
