### ISSUE TITLE
md-colors is broken with default theme in dialog

### ISSUE THREAD

**Issue by mohammadrafigh** [angular/material#10276] opened 2017-01-18 22:06 UTC
**Actual Behavior**:
 -  `What is the issue? *`

 using md-colors with default theme inside dialog throws this in **1.1.3**:
`mdColors: couldn't find '' in the palettes.`

 -  `What is the expected behavior?`
the default color palette should be applied with warning color.

**CodePen** (or steps to reproduce the issue): *

[CodePen](http://codepen.io/lost_semicolon/pen/appyEG)

**Angular Versions**: *
 -  `Angular Version:` 1.3.20, 1.5.8, 1.5.11
 -  `Angular Material Version:` release: version 1.1.3

**Additional Information**:
 -  `Browser Type: *` Chromium
 -  `Browser Version: *` 55.0.2883.87
 -  `OS: *` Ubuntu 16.10
 -  `Stack Traces:` `mdColors: couldn't find '' in the palettes.`

**Comment by Schweigi** [comment] 2017-02-11 19:37
It's definitely broken since Angular-Mateiral v1.1.3. Adding the term `default` as prefix to the color will work as a workaround in the meantime.

Example:
`md-colors="{color:'warn'}"` => `md-colors="{color:'default-warn'}"`

**Comment by imjoeco** [comment] 2017-03-12 15:28
I'm having a similar issue with md-colors on cards in dialog which I am unable to reproduce on codepen but I'm assuming it's related. The primary difference I'm having is that all themes other than 'deep-purple' are functioning fine for code identical to the following demo (in the demo, no theme works in dialogs as @mohammadrafigh pointed out). 

Demo: [CodePen](http://codepen.io/anon/pen/GWmwPz)

The error being thrown when 'deep-purple' is used is: 
<pre>Cannot read property 'value' of undefined
(anonymous) @ app.js:31882
applyThemeColors @ app.js:12594
(anonymous) @ app.js:26370
$digest @ app.js:34284
$apply @ app.js:34388
(anonymous) @ app.js:36847
defaultHandlerWrapper @ app.js:27520
eventHandler @ app.js:27512'</pre>

Browser: Chrome Version 56.0.2924.87 (64-bit)
OS: Ubuntu 16.04

**Comment by jbabaei** [comment] 2017-07-01 16:26
Excellent. very good

**Comment by kylekatarnls** [comment] 2017-08-03 12:38
If it can help to debug, I added a breakpoint here:
```jsfunction applyThemeColors(element, colorExpression) {
      try {
        if (colorExpression) {
          // Assign the calculate RGBA color values directly as inline CSS
           element.css(interpolateColors(colorExpression));
        }
      } catch (e) {
        $log.error(e.message);
      }

    }```
colorExpression = `primary` in the page.
colorExpression = `-primary` in the dialog.

**Comment by codymikol** [comment] 2018-01-18 16:28
This is definitely still an issue, any updates on this?

**Comment by codymikol** [comment] 2018-01-18 19:29
I made a PR https://github.com/angular/material/pull/11078

For anyone looking for a workaround to this issue, if you set the md-theme property inside of your dialog content to either default or the specific theme you want to use, this will stop md-colors from breaking.

**Comment by Splaktar** [comment] 2018-03-01 04:35
Updated [CodePen](https://codepen.io/Splaktar/pen/BYMwdw) for 1.1.7. Issue still occurs.

**Comment by thorvx** [comment] 2018-03-14 15:43
Same issue.

Related issue: https://github.com/angular/material/issues/525

**Comment by Splaktar** [comment] 2018-03-15 01:02
The PR to fix this is going through the presubmit process (there was unfortunately a delay in that process) and then hopefully it will pass and be able to be merged.

**Closed** 2018-03-16 18:04 UTC
Labels: - Lots of Comments, P2: required, has: Pull Request, severity: regression, type: bug, ui: theme

**Comment by akvaliya** [comment] 2018-04-09 16:25
@Splaktar Is this issue resolved yet? I am facing it when dynamic theme is generated.

**Comment by codymikol** [comment] 2018-04-10 00:14
@akvaliya This was fixed in 1.1.8

**Comment by garretwilson** [comment] 2018-04-17 16:42
I just ran into this with AngularJS 1.6.4. `"{color:'accent'}"` seems to work on the main page, but in an mdDialog I had to use `"{color:'default-accent'}"` to get it to work.

**Comment by Splaktar** [comment] 2018-04-17 18:48
@garretwilson which version of AngularJS Material are you using?

**Comment by Splaktar** [comment] 2018-04-17 19:05
@garretwilson this is fixed in 1.1.8. Here's the [CodePen above updated for 1.1.8](https://codepen.io/Splaktar/pen/GdKwYM) that shows this working without the need to add `default-`.

**Comment by garretwilson** [comment] 2018-04-17 20:36
Ah, I'm using 1.1.3. Thanks for the info; we'll update in our next iteration.

**Comment by garretwilson** [comment] 2018-04-19 17:42
Yep, v1.1.8 seems to have fixed it, thanks.
