### ISSUE TITLE
Somewhere in md-select scope picks up outside parameters

### ISSUE THREAD

**Issue by gleno** [angular/material#6569] opened 2016-01-06 21:14 UTC
opts, in the following snippet (taken from 1.0.1) seems to pickup 'mode' from above scope, and get confused. For now, I'll workaround with ng-init="mode = null" on the parent md-input-container.
    
    self.selectedLabels = function(opts) {
      opts = opts || {};
      var mode = opts.mode || 'html';
      var selectedOptionEls = $mdUtil.nodesToArray($element[0].querySelectorAll('md-option[selected]'));
      if (selectedOptionEls.length) {
        var mapFn;

        if (mode == 'html') {
          mapFn = function(el) { return el.innerHTML; };
        } else if (mode == 'aria') {
          mapFn = function(el) { return el.hasAttribute('aria-label') ? el.getAttribute('aria-label') : el.textContent; };
        }
        return selectedOptionEls.map(mapFn).join(', ');
      } else {
        return '';
      }
    };

**Comment by ThomasBurleson** [comment] 2016-01-13 02:47
duplicate of issue filed by @jelbourn

**Closed by ThomasBurleson** 2016-01-13 02:47 UTC
