### ISSUE TITLE
Fab toolbar is not opening properly.

### ISSUE THREAD

**Issue by andrewyoung1991** [angular/material#5720] opened 2015-11-13 22:51 UTC
Hi my html looks like this

``` html
        <md-fab-toolbar md-open="false" md-direction="left">                                                                           
          <md-fab-trigger>
            <md-button class="md-fab md-accent">
              <md-icon>keyboard_arrow_left</md-icon>
            </md-button>
          </md-fab-trigger>
          <md-toolbar>
            <md-fab-actions class="md-toolbar-tools">
              <md-button ng-hide="vm.testingWebcam" ng-click="vm.testWebcam()">
                <md-tooltip>Test Your Webcam</md-tooltip>
                <md-icon>videocam</md-icon>
              </md-button>
            </md-fab-actions>
          </md-toolbar>
        </md-fab-toolbar>
```

when i toggle the toolbar the toolbar background is transparent and the icons are squished into the fab trigger and unclickable... what gives?

![screenshot from 2015-11-13 14-29-38](https://cloud.githubusercontent.com/assets/5006182/11159382/c3943b38-8a13-11e5-8443-78e020fb2fc2.png)

**Comment by EladBezalel** [comment] 2015-11-16 19:23
I copied pate your code into a codepen and it seemed to work, can you please put a codepen with your problem so we can investigate more?

**Comment by EladBezalel** [comment] 2015-11-17 23:55
Closing this for now, if it's still happening please provide a codepen and i will reopen this issue.

**Closed by EladBezalel** 2015-11-17 23:55 UTC
Labels: needs: demo, needs: more info

**Comment by DmitryEfimenko** [comment] 2015-12-22 23:22
It happens to me too. I can't reproduce issue on plunker, but I think it has to do with a combination of plugins installed.
I am making an app using meteor. I installed meteor packages `angular-meteor`, (which uses angular 1.3.1 - I thought this might be an issue, but downgrading version on plunker to 1.3.15 does not show the issue), and `angular:angular-material` (which uses version 1.0.1).

Also, what might be a symptom, but not the cause is that if `<md-fa-trigger>` contains `<md-buttom>` with `<md-icon>` inside, I see error thrown: `Cannot read property 'element' of undefined` in the following method in `angular-material.js`:
```javascript
function isIcon(target) {
     return angular.isDefined(target.element) && angular.isDefined(target.config);
}
```
However, swapping `<md-icon>` with some text gets rid of that issue.

Sorry I can't provide more details... I know this is not really helpful for issue reproduction.

@andrewyoung1991, did you figure out what was the issue in your case or found a workaround?

**Comment by andrewyoung1991** [comment] 2015-12-23 02:43
@DmitryEfimenko , sorry i haven't found a work around unfortunately. i have the same issue with fab toolbar and fab speed dial.
