### ISSUE TITLE
md-grid-list - Quirk behavior when using md-row-height="fit"

### ISSUE THREAD

**Issue by yccteam** [angular/material#1790] opened 2015-03-05 01:21 UTC
Hi,
Here's the issue piece of HTML:
```
<!-- create a 4 colums grid list -->
<md-grid-list 
              md-cols="4" 
              md-gutter="1rem" 
              md-row-height="fit"
              flex>
<!-- show the filtered list -->
  <md-grid-tile
                md-colspan="1"
                ng-repeat="customer in customers.data| filter:{state: true} | filter : customers.search | slice : customers.begin : constants.settings.limitSearchResults ">
                <ng-include class="customerCardWrapper" src="'partials/customers/customerCard.html'"></ng-include>
    </md-grid-tile>
</md-grid-list>
```
The first page with full data loads fine with ```constants.settings.limitSearchResults``` cells that look really nice (it's kind of like using ```limitTo``` only that I can paginate through the data).  Now I paginate to the second page to see the rest of the data. When I get there I have only 1 result, which is the expected result. 
The problem: this one result now fits in height to the whole container.  This creates a quirky feeling.  Any idea how to solve this without setting constant heights to the rows?

**Comment by shyndman** [comment] 2015-03-05 01:39
hey yccteam,

Would it be so bad to use fixed height? When you see that you have one row of data, set the `md-row-height` to a fixed height value, otherwise leave it in `"fit"`.

**Comment by shyndman** [comment] 2015-03-05 01:41
something like 

```html
<md-grid-list
  md-row-height="{{ results.length <= 4 ? '250px' : 'fit' }}">
...
</md-grid-list

**Comment by shyndman** [comment] 2015-03-11 17:50
@yccteam Was my solution acceptable? 

This is not a bug in the grid list, so I'm closing the issue.

**Closed by shyndman** 2015-03-11 17:50 UTC

**Comment by yccteam** [comment] 2015-03-12 07:56
Hi,
Yea, your solution works. There is the issue of filtering big data, but I resort to server filtering for this case so the problem is solved.

**Comment by ThomasBurleson** [comment] 2015-03-12 12:34
@yccteam - A classic mistake is to deliver a large data set directly to the view for binding and rendering. The Controller/$scope features allows developers to prepare **view models** which may contain only portions of large data sets.
