### ISSUE TITLE
Auto complete results section not hiding upon clicking elsewhere on the Page in Ipad

### ISSUE THREAD

**Issue by jithureddy** [angular/material#10521] opened 2017-03-21 09:12 UTC
**Actual Behavior**:
 -  `When user enters anything in auto-complete search, the results will be shown, and if user clicks anywhere else on the page the result section will be disappeared, But in the case of Ipad the autocomplete results section not getting hidden because of which the rest of the page becomes unresponsive*`
 -  `The results dropdown/section need to be removed after user selects anything on the page`

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
 -  `Details:`

**AngularJS Versions**: *
 -  `AngularJS Version: - 1.5.8`
 -  `AngularJS Material Version:1.1.0`

**Additional Information**:
 -  `Browser Type: Chrome`
 -  `Browser Version: 56`
 -  `OS: iOS, v7`
 -  `Stack Traces:`

**Comment by Tenbrink** [comment] 2017-04-05 07:43
+1

**Comment by Splaktar** [comment] 2018-02-11 02:56
Duplicate of #10518.

**Closed by Splaktar** 2018-02-11 02:56 UTC
Labels: resolution: duplicate
