### ISSUE TITLE
Some md-icons don't show in iOS WKWebKit

### ISSUE THREAD

**Issue by jpike88** [angular/material#7200] opened 2016-02-18 06:56 UTC
This only happens in WKWebKit in iOS Safari, and seems limited to one particular icon.

It's in an md-button sitting in an md-toolbar. Oddly, it does NOT occur in the simulator, just in an actual device.

Here is the code:
```

<md-button aria-label="Open phone interactions menu" class="md-icon-button option-menu-button" ng-click="ctrl.openOptions($mdOpenMenu, $event)">
        <md-icon md-menu-origin md-svg-icon="navigation:more_vert"></md-icon>
      </md-button>

```

Strangely, it also doesn't work with md-svg-icon="navigation:more_horiz".

However, some different icons work:
```
        <md-icon md-menu-origin md-svg-icon="navigation:menu"></md-icon>
        <md-icon md-menu-origin md-svg-icon="navigation:apps"></md-icon>
        <md-icon md-menu-origin md-svg-icon="navigation:arrow_drop_up"></md-icon>
```  

I think this is an issue specific to the more_vert and more_horiz icons, perhaps to do with their irregular dimensions?

Using a PNG background for now.

**Comment by Frank3K** [comment] 2016-02-18 16:40
Can you include a link to the used SVG?

**Comment by ThomasBurleson** [comment] 2016-04-25 22:12
Closing this issue due to insufficient information. Please resubmit with:

----
Required
----

**Behavior**:
-  What is the issue? * 
-  What is the expected behavior? 

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue :
-  Details: 

**Angular Versions**: *
-  Angular Version: 
-  Angular Material Version: 

**Additional Information**:
-  Browser Type: *
-  Browser Version: *
-  OS: *
-  Stack Traces: 

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

**Closed by ThomasBurleson** 2016-04-25 22:12 UTC
Labels: needs: demo
