### ISSUE TITLE
md-menu-bar component doesn't support md-button

### ISSUE THREAD

**Issue by 4jader79** [angular/material#7231] opened 2016-02-22 12:10 UTC
```html
<md-menu-bar role="menubar" class="headerbar3">
	<md-menu>
		<md-button aria-label="TEST" class="md-icon-button" ng-click="$mdOpenMenu($event)">
			TEST
		</md-button>
	</md-menu>
</md-menu-bar>
```

**The above example result in the following error message:**

```bash
Error: menuEl.querySelector(...) is null
compile/<@http://localhost:8080/visualPolCity/resources/app/js/vendor/angular-material.js:23033:13
forEach@http://localhost:8080/visualPolCity/resources/app/js/vendor/angular.js:336:11
compile@http://localhost:8080/visualPolCity/resources/app/js/vendor/angular-material.js:23029:7
applyDirectivesToNode@http://localhost:8080/visualPolCity/resources/app/js/vendor/angular.js:8069:22
compileNodes@http://localhost:8080/visualPolCity/resources/app/js/vendor/angular.js:7598:15
compileNodes@http://localhost:8080/visualPolCity/resources/app/js/vendor/angular.js:7610:15
compile@http://localhost:8080/visualPolCity/resources/app/js/vendor/angular.js:7505:15
applyDirectivesToNode@http://localhost:8080/visualPolCity/resources/app/js/vendor/angular.js:7981:33
compileNodes@http://localhost:8080/visualPolCity/resources/app/js/vendor/angular.js:7598:15
compileTemplateUrl/<@http://localhost:8080/visualPolCity/resources/app/js/vendor/angular.js:8490:38
processQueue@http://localhost:8080/visualPolCity/resources/app/js/vendor/angular.js:14745:28
scheduleProcessQueue/<@http://localhost:8080/visualPolCity/resources/app/js/vendor/angular.js:14761:27
$RootScopeProvider/this.$get</Scope.prototype.$eval@http://localhost:8080/visualPolCity/resources/app/js/vendor/angular.js:15989:16
$RootScopeProvider/this.$get</Scope.prototype.$digest@http://localhost:8080/visualPolCity/resources/app/js/vendor/angular.js:15800:15
$RootScopeProvider/this.$get</Scope.prototype.$apply@http://localhost:8080/visualPolCity/resources/app/js/vendor/angular.js:16097:13
done@http://localhost:8080/visualPolCity/resources/app/js/vendor/angular.js:10546:36
completeRequest@http://localhost:8080/visualPolCity/resources/app/js/vendor/angular.js:10744:7
requestLoaded@http://localhost:8080/visualPolCity/resources/app/js/vendor/angular.js:10685:1
```

`<md-menu-bar role="menubar" class="headerbar3">`

**The problem in located into the attached image**
_( Solution should be: menuEl.querySelector('md-button,button,a') )_

![image](https://cloud.githubusercontent.com/assets/2410173/13217815/8ff12308-d965-11e5-999a-088a8d4b8279.png)

**Comment by lucasbento** [comment] 2016-03-19 18:37
+1
Getting the same error here, still working though.

**Comment by MarcLoupias** [comment] 2016-04-13 13:14
There is no issue in `<md-menu>`, only in `<md-menu-bar>`.

**Comment by paveleremin** [comment] 2016-05-04 16:21
the same situation with:
```
<md-toolbar>
  <md-menu-bar>
    <md-menu>
      <md-button>
```

**Comment by topherfangio** [comment] 2016-05-09 16:33
Sorry; didn't realize this was a duplicate of #6802 which already has PR #8242.

**Closed by topherfangio** 2016-05-09 16:33 UTC
Labels: P1 - Broken Renders / Major Use Cases
