### ISSUE TITLE
Odd animation behavior of ng-messages inside md-input-container

### ISSUE THREAD

**Issue by d3lm** [angular/material#7386] opened 2016-03-03 02:21 UTC
I have just noticed that ng-messages behaves strange inside md-input-container. So, whenever a field inside an md-input-container is validated, assuming that ng-messages is placed inside md-input-container, and you type fast enough, you can see the error messages a dozen of times. So in my case I have an input field that is required. For example you type a letter and immediately delete it again (to trigger the required error). This _error_ / behavior can also be seen in the official documentation, if you scroll down to the first section "Errors"

https://material.angularjs.org/latest/demo/input

This might also be an error concerning ngMessages, and not completely related to the md-input-container. However, this does not occur when using ng-messages outside md-input-container. Each `ng-message` has a CSS transition which might be causing this behavior.

**Comment by kvetis** [comment] 2016-03-16 16:16
You can add `ng-model-options={debounce: 300}` as a workaround.

**Comment by topherfangio** [comment] 2016-03-24 19:29
Duplicate of #6265.

**Closed by topherfangio** 2016-03-24 19:29 UTC
