### ISSUE TITLE
md-select with scrollbars auto closing

### ISSUE THREAD

**Issue by bijoux** [angular/material#4078] opened 2015-08-10 10:38 UTC
current head, the issue is present in both latest chrome and firefox.
To reproduce, go to the select demo page, open an md-select with a scrollbar, and try to scroll down.

**Comment by viztastic** [comment] 2015-08-13 00:29
For me the issue is with both version 10.0 and 10.1

I have an md-select. Appears fine on the page. And it also behaves fine when in large or medium screen mode:

http://screencast.com/t/k0rrG0Iu3EO

When I srhink the screen to a mobile width, and then click on md-select. It hides the page scroll bars and I can't seem to click out of the md-select or scroll up/down the page (even with the mouse scroll wheel)

http://screencast.com/t/RWhz8rGcKTvH

**Comment by viztastic** [comment] 2015-08-13 00:37
Also worth noting, that when I resize the screen to desktop.. everything is still frozen (no scroll bars and select is still open).

**Comment by AleksueiR** [comment] 2015-08-14 15:03
+1

**Comment by rschmukler** [comment] 2015-09-10 16:39
Closed by #4229

**Closed by rschmukler** 2015-09-10 16:39 UTC
