### ISSUE TITLE
Can't use static md-chips with ng-repeat

### ISSUE THREAD

**Issue by calebegg** [angular/material#5709] opened 2015-11-12 22:57 UTC
Demo: http://codepen.io/calebegg/pen/yYGbvR
Error: `TypeError: Cannot read property 'insertBefore' of null` (in console)

**Comment by braintapper** [comment] 2015-11-19 23:12
+1

**Comment by lasdjs** [comment] 2015-11-29 21:36
+1 I have the same issue

**Comment by rwillmer** [comment] 2015-12-07 13:05
Duplicate of #2829 

There's a work-around described in that closed ticket.

**Comment by topherfangio** [comment] 2016-01-06 19:26
At this point, I don't believe we can easily support this request for 1.x.

We are, however, looking at adding a bit more functionality to chips (via #5799) so that you can use the workaround without necessarily having to use the `readonly` attribute which causes issues for some users.

In the meantime, I am going to mark this for consideration in 2.0 so that we will remember to take this into account when we update the component.

**Comment by ThomasBurleson** [comment] 2016-04-28 20:23
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).

**Closed by ThomasBurleson** 2016-04-28 20:23 UTC
Labels: P4 - Reported By or General PRs/Errors or Edge Cases
