### ISSUE TITLE
Online Docs are not rebuilding

### ISSUE THREAD

**Issue by ThomasBurleson** [angular/material#1347] opened 2015-01-30 17:00 UTC
Material.Angularjs.org docs are not rebuilding; since doc redesigns and mdGesture additions.

**Comment by epelc** [comment] 2015-01-30 17:56
This is probably the cause for #1346 if the bower deployments are automated.

**Comment by marcysutton** [comment] 2015-01-30 21:38
The docs should be fixed now.

**Closed by marcysutton** 2015-01-30 21:38 UTC
Labels: bug, build
