### ISSUE TITLE
mdMenu : nested menu doesn't show when 2 nested menu in a row

### ISSUE THREAD

**Issue by jdemaire** [angular/material#7019] opened 2016-02-04 13:41 UTC
Whith 2 nested menu in a row, the 2nd one doesn't show on mouse over (after first one has been opened) 
Menu I tested :
`          <md-menu>
            <button ng-click="$mdOpenMenu()">Menu</button>
            <md-menu-content>
              <md-menu-item>
                <md-menu>
                  <md-button ng-click="$mdOpenMenu()">item1</md-button>
                  <md-menu-content>
                    <md-menu-item><md-button>subitem 1-1</md-button></md-menu-item>
                    <md-menu-item><md-button>subitem 1-2</md-button></md-menu-item>
                  </md-menu-content>
                </md-menu>
              </md-menu-item>
              <md-menu-item>
                <md-menu>
                  <md-button ng-click="$mdOpenMenu()">item2</md-button>
                  <md-menu-content>
                    <md-menu-item><md-button>subitem 2-1</md-button></md-menu-item>
                    <md-menu-item><md-button>subitem 2-2</md-button></md-menu-item>
                  </md-menu-content>
                </md-menu>
              </md-menu-item>
            </md-menu-content>
          </md-menu>
`
I fixed it in my local version by removing the else at line 21740 
`else if (nestedMenu && !nestedMenu.isOpen && nestedMenu.open) {`
My Angular Material version : 
 * Angular Material Design
 * https://github.com/angular/material
 * @license MIT
 * v1.0.4
 *

**Comment by daviian** [comment] 2016-02-04 16:23
Funny to see that someone has exactly the same problem at the same time ;-)

So I can confirm this issue.

**Comment by DevVersion** [comment] 2016-02-27 18:19
Closing this as a dupe of #6685

**Closed by DevVersion** 2016-02-27 18:19 UTC
