### ISSUE TITLE
dialog: after scrolling, dialog appears off screen on the second time opened

### ISSUE THREAD

**Issue by Egorby** [angular/material#10930] opened 2017-10-08 11:38 UTC
**Actual Behavior**:
 -  `What is the issue? *` $mdDialog on mobile dialog out of screen, when you open second time
 -  `What is the expected behavior?` modal not on screen

**CodePen** (or steps to reproduce the issue): *
 - Scroll body
 -  Open modal first time:

.md-dialog-container:
 -  Open modal first time:
in-line styles: top: 885px; height: 628px;
 -  Open same modal second time (no need to scroll again)
in-line styles: top: 1770px; height: 628px;

top for second click changed twice - and now modal out of screen

**AngularJS Versions**: *
 -  `AngularJS Version:` 1.6.6
 -  `AngularJS Material Version:` 1.1.5

**Additional Information**:
 -  `Browser Type: *` Mobile
 -  `Browser Version: *` 11
 -  `OS: *` iOS 11

----

**Comment by fetters5** [comment] 2017-10-09 19:23
If you rotate the device does the modal come back on the screen?

**Comment by Egorby** [comment] 2017-10-09 20:19
When you rotate device dialog take all screen, when you rotate back it showing not on centre.

**Comment by scriptsure** [comment] 2017-10-17 01:57
ditto on this... +1

**Comment by noamamit92** [comment] 2017-10-30 08:01
+1 - this is hitting us hard on production

**Comment by noamamit92** [comment] 2017-10-30 08:01
Did anyone find a workaround?

**Comment by Egorby** [comment] 2017-10-30 08:12
Please fix this issue. Super important. Yes when device rotated modal back but not in center, after you rotate back modal still not centered.

**Comment by fetters5** [comment] 2017-10-30 16:17
I used the following as a workaround which worked in my case but definitely not ideal

    .md-dialog-container {
      height: 100% !important;
      position: fixed !important;
      top: 0px !important;
    }

**Comment by noamamit92** [comment] 2017-11-01 14:20
@fetters5 - thanks for the workaround

**Comment by pankajjain1** [comment] 2017-11-02 21:27
Its impacting us also when this will be fixed?

**Comment by TorzuoliH** [comment] 2018-01-03 16:20
@fetters5 this _fix_ is well working, thanks a lot!

**Comment by Splaktar** [comment] 2018-03-16 05:54
Closing as a duplicate of https://github.com/angular/material/issues/10675.

**Closed by Splaktar** 2018-03-16 05:54 UTC
Labels: browser: iOS, for: external contributor, needs: demo, resolution: duplicate
