### ISSUE TITLE
Can't scroll md-content with arrow keys or space bar

### ISSUE THREAD

**Issue by calebegg** [angular/material#3237] opened 2015-06-11 21:33 UTC
This is unfortunate but probably unavoidable when the md-content is embedded in the page, but it's pretty unacceptable when it's being used as the entire content of the page, like on https://material.angularjs.org

**Comment by marcysutton** [comment] 2015-06-12 18:56
This is a duplicate of https://github.com/angular/material/issues/2961.

**Closed by marcysutton** 2015-06-12 18:56 UTC
