### ISSUE TITLE
md-tooltip work in v1.1.0 but not work in v1.1.6

### ISSUE THREAD

**Issue by mohsensaremi** [angular/material#11085] opened 2018-01-21 07:13 UTC
md-tooltip directive not work in latest version v1.1.6 but in old version (v1.1.0) it works perfectly

**Comment by Splaktar** [comment] 2018-01-21 08:24
Thank you for taking the time to submit this issue. However it does not follow our required issue template. 

Please file a new issue that follows the template. This gives the team the information needed to investigate the bug or prioritize the feature.

You can see the tooltips working on the demo site which is running 1.1.6 here: https://material.angularjs.org/latest/demo/tooltip

Please also check that your issues isn't a duplicate of an open issue like https://github.com/angular/material/issues/10543.

**Closed by Splaktar** 2018-01-21 08:24 UTC
