### ISSUE TITLE
md-menu has a problem top when inside a toolbar

### ISSUE THREAD

**Issue by pierrybos** [angular/material#6080] opened 2015-12-04 13:42 UTC
Hi all, Someone has this problem?

http://codepen.io/anon/pen/jWOyGE

I identify on 
material/src/components/menu/js/menuServiceProvider.js

```javascript
392 . function calculateMenuPosition(el, opts) {

(...)

405.      var bounds = {
406.        left: boundryNodeRect.left + MENU_EDGE_MARGIN,
407.        top: Math.max(boundryNodeRect.top, 0) + MENU_EDGE_MARGIN,
408.        bottom: Math.max(boundryNodeRect.bottom, Math.max(boundryNodeRect.top, 0) + boundryNodeRect.height) - MENU_EDGE_MARGIN,
409.        right: boundryNodeRect.right - MENU_EDGE_MARGIN
410.      };
```

if change 407: to:
```javascript
       top: Math.max(boundryNodeRect.top, 0) + MENU_EDGE_MARGIN,
```

from:
```javascript
       top: Math.max(boundryNodeRect.top, 0), //  + MENU_EDGE_MARGIN,
```

This solve my problem, but isn't a graceful solution.
Anyway to identify is inside a toolbar and do other rule?

Only me with this problem or i can try help solving this?

**Comment by 0101adm** [comment] 2015-12-04 15:28
dupe of 6073

**Comment by rudzikdawid** [comment] 2015-12-04 18:45
+1

**Comment by ThomasBurleson** [comment] 2015-12-07 20:39
Duplicate

**Closed by ThomasBurleson** 2015-12-07 20:39 UTC
