### ISSUE TITLE
mdSelect scrolls the window to the top

### ISSUE THREAD

**Issue by tanwaniniranjan** [angular/material#1721] opened 2015-02-28 19:39 UTC
mdSelect scrolls the window to the top, when the user clicks on any select box for the first time

Please consider fixing this, since this could be really annoying on a form driven web application.

Thank you!

**Comment by mckenzielong** [comment] 2015-03-02 15:11
I think this is a duplicate of #1648

**Comment by rschmukler** [comment] 2015-03-02 21:59
Closing as duplicate of #1648

**Closed** 2015-03-25 16:23 UTC
