### ISSUE TITLE
Time picker needed

### ISSUE THREAD

**Issue by jpike88** [angular/material#7326] opened 2016-02-29 06:17 UTC
Take a look at this, he's built off angular material and it might be useful for time selections
https://github.com/logbon72/angular-material-datetimepicker

**Comment by DevVersion** [comment] 2016-02-29 06:24
This is a dupe of #5029

**Closed** 2016-02-29 06:24 UTC

**Comment by jpike88** [comment] 2016-02-29 06:30
It might be a dupe issue, but that link shows a pretty impressive implementation. I'll post it in the other one

**Comment by DevVersion** [comment] 2016-02-29 06:33
Yeah, that's great, everything you wan't to pin to the Timepicker should be done in #5029.
