### ISSUE TITLE
Toolbar title font weight

### ISSUE THREAD

**Issue by ivan7237d** [angular/material#4381] opened 2015-08-31 00:09 UTC
From this page:

https://www.google.com/design/spec/layout/structure.html#structure-toolbars

it looks like font-weight of the title (h1, h2, h3) in md-toolbar should be 500 (like .md-title), but currently is regular.

**Comment by topherfangio** [comment] 2015-11-04 02:28
I think this needs a tad bit of discussion. Currently, it does work exactly as intended...unless, you put everything in the `<div class="md-toolbar-tools">` which overrides this and sets it to regular font weight.

Here is an example of it working as intended (note how I'm not using the `md-toolbar-tools` class):

```html
<md-toolbar layout="row">
  <md-button class="md-icon-button md-indent" aria-label="Settings">
    <md-icon md-svg-icon="img/icons/menu.svg"></md-icon>
  </md-button>

  <h3>Basic Toolbar</h3>

  <span flex></span>

  <md-button class="md-icon-button" aria-label="Favorite">
    <md-icon md-svg-icon="img/icons/favorite.svg" style="color: greenyellow;"></md-icon>
  </md-button>
</md-toolbar>
```

@ThomasBurleson Any thoughts on this? The `md-toolbar-tools` class isn't documented, but it's used in all of our examples. Should we update the class styles for it?

**Comment by topherfangio** [comment] 2015-11-04 23:55
It looks like there might be a slight discrepancy in the [toolbar spec](https://www.google.com/design/spec/layout/structure.html#structure-toolbars).

<img width="801" alt="screen shot 2015-11-04 at 1 42 31 pm" src="https://cloud.githubusercontent.com/assets/54370/10955860/2ea865e0-8314-11e5-95c5-e4edbd4ab256.png">

All of the images for the toolbars (the blue one) appear to use a font weight of 500 for the title, but the site (the maroon one) itself uses font weight 400 for it's title.

@joeyperson Do you know which one is official? @jelbourn said you might be able to provide some input.

**Comment by ThomasBurleson** [comment] 2016-04-28 20:24
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).

**Comment by ThomasBurleson** [comment] 2016-04-28 20:26
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).

**Closed by ThomasBurleson** 2016-04-28 20:26 UTC
Labels: - Easy fix, needs: investigation, priority: low, ui: CSS
