### ISSUE TITLE
$mdSideNav prevent scrolling on element other than parent on open.

### ISSUE THREAD

**Issue by w2w-minjer** [angular/material#8634] opened 2016-06-03 09:27 UTC
**Actual behavior**:
-  When my sideNav is open, i can scroll thru its content, when i reach the end of the content of the sideNav, the main-content starts to scroll *
-  I dont want the main-content to scroll when i have a sideNav open.

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue : http://codepen.io/Donniewiko/pen/OXVXjm/
-  Details: When you click on the Button, a sideNav will open. Scrolling isn't prevented on the main content so you can scroll all you want, which isnt expected or wanted. On row 3 I've placed a div which re-creates the problem. In our scenario this div is actually an ngInclude.

**Angular Versions**: *
-  Angular Version: 1.4.8
-  Angular Material Version: 1.0.0

**Additional Information**:
-  Browser Type: all major browsers.*
-  Browser Version: latest*
-  OS: all (both mobile and desktop)*
-  Stack Traces:

I have narrowed the issue down to the method DisableParentScroll: https://github.com/angular/material/blob/master/src/components/sidenav/sidenav.js#L350

In the pen, the parent element of the sideNav is div#troubleBringer. So when i open the sideNav the div will get overflow:hidden. But i want the parent of the parent (md-content) to get overflow:hidden;

I have tried to create my own solution to this issue. I tried to use the $mdSidenav(id).isOpen(); method. But this resulted in unwanted side effects.

---
# Possible solution:

I have little knowledge of pull requests. But i want to propose a solution:
Create an attribute on the sideNav which can be used to provide an alternate element to disable the scroll.
Here is how i fixed it:
SideNav.js:

in the [postLink](https://github.com/angular/material/blob/master/src/components/sidenav/sidenav.js#L255):

    ...
    var preventScrollElement = element.parent();

    if (attr.preventScrollTarget) {
       var domElement = document.querySelectorAll(attr.preventScrollTarget);

       if (domElement.length !== 1) {
          $log.error(attr.preventScrollTarget + " target should target exactly 1 element. " + domElement.length + " elements found!");
       }

       preventScrollElement = angular.element(domElement);
    }
    ...

And the method [DisableParentScroll](https://github.com/angular/material/blob/master/src/components/sidenav/sidenav.js#L350):

      function disableParentScroll(disabled) {
      if ( disabled && !lastParentOverFlow ) {

         lastParentOverFlow = preventScrollElement.css('overflow');
         preventScrollElement.css('overflow', 'hidden');

      } else if (angular.isDefined(lastParentOverFlow)) {

        preventScrollElement.css('overflow', lastParentOverFlow);
        lastParentOverFlow = undefined;

      }
    }

then you can set the attribute on the sideNav like this:

    <md-sidenav prevent-scroll-target="#mainContent" class="md-sidenav-right md-whiteframe-4dp" md-component-id="right">

**Comment by BamiGorengo** [comment] 2016-07-26 09:24
anything new about this? i got the same problem:

URL to my Live Demo Page: http://thommessen.upperyard.de/#/
Codepen: http://codepen.io/BamiGorengo/pen/GqdVLz
Video of the bug: https://youtu.be/IO5H_3OLWaM

**Comment by crisbeto** [comment] 2016-08-05 14:42
@w2w-minjer I've been looking into this, but there's no reliable way of disabling all of the scrolling once you reach the end. The scroll event doesn't have `preventDefault` so the only option is to use the `wheel` which works fine if you're only using a mouse, but doesn't help if the user scrolls through the keyboard or by click the middle mouse button.

An alternative can be to add `overflow: hidden`, but this can cause the content to jump on Windows where the scrollbar modifies the element dimensions. 

Another issue with this is that we need to measure the `scrollTop` for each pixel being scrolled. The problem is that `scrollTop` triggers a reflow which can be bad for performance on IE and mobile devices.

[Here's what I have until now.](http://codepen.io/crisbeto/pen/AXdEZq) I'll close the issue since it doesn't seem to be very doable, but we can always re-open it if there are any better suggestions for solving it,

@BamiGorengo your issue seems to be unrelated to this one, but I couldn't reproduce it from your codepen.

**Comment by w2w-minjer** [comment] 2016-08-08 06:06
Thanks for looking into this @crisbeto.
I wonder what was wrong with my proposed solution, since it does fix the issue i encoutered, plus adds some extra functionality. I basicly used the (already) built in solution of the _disableParentScroll_ 
Perhaps i failed to explain my issue, or you misunderstood it. I have no need for disabling any random element. Just the element behind the open sidenav.

Kind regards,
Jeroen

**Comment by crisbeto** [comment] 2016-08-08 06:27
@w2w-minjer My impression was that you wanted to prevent the window scroll once the user scrolls to the bottom/top of the sidenav. After reading through it again, it seems reasonable.

**Comment by BamiGorengo** [comment] 2016-08-08 08:00
@crisbeto i uploadet a video on youtube, there you can see the problem. i fix it with

`<meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no" />`

But that do only that the Browser dont resize. in the moment where i open the right sidenav i can scroll out of page. its pretty ugly.

**Closed** 2016-08-23 17:37 UTC
Labels: has: Pull Request, P2 - Planned Work / Team PRs
