### ISSUE TITLE
Datepicker jumps to top of page

### ISSUE THREAD

**Issue by PhilipAdservice** [angular/material#11190] opened 2018-03-26 06:57 UTC
### Bug, feature request, or proposal:
When closing the datepicker, that is clicking outside of the dialog or choosing a date, causes the user to be scrolled to the top of the page.

### What is the expected behavior?
To not move the body scroll

### What is the current behavior?
Jumps to the top of the page

### What is the use-case or motivation for changing an existing behavior?
It's not very user-friendly to use the datepicker when the user always scrolls to the top of the page  

### Which versions of AngularJS, Material, OS, and browsers are affected?
"angular": "1.6.9"
"angular-material": "^1.1.8"
"moment": "^2.11.2"
"angular-animate": "^1.6.9"
"angular-aria": "^1.6.9"
"angular-cookies": "^1.6.9"
"angular-messages": "^1.6.9"
"angular-resource": "^1.6.9"
"angular-sanitize": "^1.6.9"
"angular-new-router": "^0.5.3"
"angular-bootstrap": "^1.1.2"
...
Using Goole Chrome 
Wokring on a PC running Windows 7

**Comment by Splaktar** [comment] 2018-03-26 09:00
This should have been fixed in AngularJS Material 1.1.5 via https://github.com/angular/material/pull/10549. We really need a CodePen that reproduces this issue to be able to look into it further.

**Comment by Splaktar** [comment] 2018-03-26 09:02
I am also unable to reproduce this on the [datepicker docs](https://material.angularjs.org/latest/demo/datepicker) page for 1.1.8.

**Closed** 2018-03-26 09:03 UTC
Labels: needs: demo, resolution: can't reproduce

**Comment by PhilipAdservice** [comment] 2018-03-26 09:05
Hi

I found a fix for it in another thread containing the same issue.

body {
    height: 100%;
    width: 100%;
    overflow: hidden;
}

.containerDiv {
    height: 100%;
    width: 100%;
    overflow-y: scroll;
}

Where the containerDiv contains all your content.
