### ISSUE TITLE
datepicker: sharing a Date as ng-model between a Datepicker and input[type="time"] resets the time value

### ISSUE THREAD

**Issue by ba55ie** [angular/material#12052] opened 2020-12-08 11:45 UTC
## Demo and steps to reproduce the issue

**Demo URL (required)***:  https://stackblitz.com/edit/angularjs-material-blank-slwfkp?file=app/app.template.html

#### Detailed Reproduction Steps
1. Open demo url.
1. Edit the time of the "shared time" field.
1. The time value will be reset when you `focus` or `blur` the time field as you can see in the displayed date string.

### Explain the expected behavior
1. The time value should be updated like in the "single time" field.

### Explain the current behavior
I think this bug is introduced in version `1.1.25` (it worked in `1.1.24`) with the Datepicker GMT timezone fixes.

### Discuss the use-case or motivation for changing the existing behavior

It's a regression bug discovered after upgrading angular-material from `1.1.24` to `1.2.1`.

### List the affected versions of AngularJS, Material, OS, and browsers

- AngularJS: 1.8.2
- AngularJS Material: 1.2.1 (since 1.1.25?)
- OS: Mac OS Big Sur
- Browsers: Chome 87, Firefox 83, Safari 14.01
- Screen Readers:

**Comment by Splaktar** [comment] 2020-12-09 13:28
Fixed in https://github.com/angular/material/commit/b406623f08cd229ea76cc06298eea764bd51ab84 which will be part of `1.2.2`.

**Comment by Splaktar** [comment] 2020-12-09 13:29
Duplicate of https://github.com/angular/material/issues/12026.

**Closed by Splaktar** 2020-12-09 13:29 UTC
Labels: resolution: duplicate, type: bug

**Comment by ba55ie** [comment] 2020-12-10 08:29
Thanks 👍
