### ISSUE TITLE
It is very difficult to select older dates using md-datepicker

### ISSUE THREAD

**Issue by gabguy** [angular/material#5105] opened 2015-10-12 06:41 UTC
Let's say I want to select 5.5.1965 as a date, I need to scroll up to year 1965 (which takes a long time).

maybe add a button to select only the year from a list of available years?

**Comment by yxh10** [comment] 2015-10-14 10:26
+1, the current version of datepicker is not suitable for input date of birth. Need a better way to change year, month, date easily. Thanks!

**Comment by merqurio** [comment] 2015-10-18 17:06
+1 @gabguy idea sounds good

**Comment by merqurio** [comment] 2015-10-18 17:11
Maybe an implementation like https://github.com/bendavis78/paper-date-picker can be inspiring. I would love to help with that, but I don't get how the actual component is created (I'm not used to Angular)

**Comment by radulucaciu** [comment] 2015-10-19 14:55
+1, at the moment it's very hard to use

**Comment by macdasi** [comment] 2015-10-25 08:51
+1

**Comment by oreyan** [comment] 2015-10-25 08:51
+1

**Comment by ivan7237d** [comment] 2015-10-25 23:15
Here's my understanding: a date picker is useful when the user needs to see the calendar (e.g. buying airplane tickets), but when he enters a date of birth, it doesn't matter what day of the week that date is, and displaying the calendar would only take away from UX. So for example Google and Facebook have simpler inputs on their sign up pages:

Google:
<img width="350" alt="screen shot 2015-10-25 at 6 34 35 pm" src="https://cloud.githubusercontent.com/assets/9092817/10718371/7995de36-7b47-11e5-8209-5d56d744ca0a.png">

Facebook:
<img width="366" alt="screen shot 2015-10-25 at 6 38 13 pm" src="https://cloud.githubusercontent.com/assets/9092817/10718376/9d50ad56-7b47-11e5-897c-ac443681edab.png">

The tricky part is i18n, because not only month names, but the order of inputs is different for different locales:

Russian Google:
<img width="342" alt="screen shot 2015-10-25 at 6 56 32 pm" src="https://cloud.githubusercontent.com/assets/9092817/10718494/af0bcbf4-7b4a-11e5-89d0-8df47f2dacc2.png">

UK Facebook:
<img width="353" alt="screen shot 2015-10-25 at 7 10 09 pm" src="https://cloud.githubusercontent.com/assets/9092817/10718550/11475de6-7b4c-11e5-9855-be7ef71a3271.png">

I think it would be pretty cool if such component was added to Angular Material - the use-case is so common and should be easy to implement now that localization has been dealt with in the regular date picker.

**Comment by lillylykho** [comment] 2015-10-28 09:42
+1

**Comment by jelbourn** [comment] 2015-11-02 19:14
Dupe of #4251

**Closed by jelbourn** 2015-11-02 19:14 UTC
