### ISSUE TITLE
md-tabs: text turns to dots on small screen on IE11

### ISSUE THREAD

**Issue by Oneril** [angular/material#11366] opened 2018-07-10 16:12 UTC
__Actual Behavior:__
When number of tabs exceeds the horizontal space tabs label are cut and dots appear.

__CodePen (or steps to reproduce the issue):__
* https://codepen.io/anon/pen/LBYrWL
* Resize your browser and see when the the dots appear

__AngularJS Versions:__
* AngularJS Version: 1.6.7
* AngularJS Material Version: 1.1.10

__Additional Information:__
* Browser Type: IE
* Browser Version: 11

**Comment by Splaktar** [comment] 2018-07-10 20:45
Dupe of https://github.com/angular/material/issues/10406.

**Closed by Splaktar** 2018-07-10 20:45 UTC
Labels: resolution: duplicate

**Comment by Oneril** [comment] 2018-07-11 08:16
Weird I couldn't find it yesterday... Sorry for that ;)
