### ISSUE TITLE
md-scroll-shrink: vertical scroll

### ISSUE THREAD

**Issue by mramanauskas** [angular/material#5264] opened 2015-10-20 05:10 UTC
When md-toolbar is used with md-scroll-shrink and md-content has flex attribute to fill screen height, vertical scroll appears and bottom content is cut.

Codepen: http://codepen.io/anon/pen/wKPbEm

**Comment by topherfangio** [comment] 2015-12-02 18:21
We'll look into the root cause of this.

In the mean time, try wrapping it in another `<div>` with the flex properties like so:

http://codepen.io/topherfangio/pen/jWNZXo?editors=100

**Comment by mramanauskas** [comment] 2015-12-16 11:38
Wrapping in another div breaks md-toolbar scroll shrink. Vertical scroll appears only when using md-scroll-shrink.

**Comment by ThomasBurleson** [comment] 2016-04-28 20:26
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).

**Closed by ThomasBurleson** 2016-04-28 20:26 UTC
Labels: P4 - Reported By or General PRs/Errors or Edge Cases

**Comment by biomassives** [comment] 2016-04-28 20:33
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (507/500 (101%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext4.iad.github.net ([192.30.252.195]:56251 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by ps5.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1avsbz-000KzZ-AZ
	for greg@biomassiv.es; Thu, 28 Apr 2016 15:32:35 -0500
Date: Thu, 28 Apr 2016 13:32:08 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1461875528;
	bh=8vz9ZUr/H1z+Fhs/OfjHDioLhWDke8BVVE9xho4TV5A=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=I8rXMSX8M0PAK+iUJH0BeFRh3S/z+wLwclL69RW1uta16vrrRs0KynpaQjsPEimoM
	 cPhEHjjSY+9sKdNftmacqkir4kGD2t754Tmvkd/dhXsICsPn4M/Zj5uo8x11YYpEp8
	 YWp3jiO9/ANZPiTRFn4xWwhpwIeGQ/zcdd5Ql0d0=
