### ISSUE TITLE
Subheader shaking

### ISSUE THREAD

**Issue by olegweb** [angular/material#8355] opened 2016-05-05 17:23 UTC
#5483

**Comment by RolandHeath** [comment] 2016-05-06 01:26
Neither this issue nor the one it references provide any meaningful information on how to replicate this. 

If there are codepens or similar from related issues, it might be good to bring them together into one place here, so all the information is in a single, open issue.

**Comment by olegweb** [comment] 2016-05-06 10:26
Ok. Bug in all versions after 0.10.1
#5862 - bug preview
How to replicate: open https://material.angularjs.org/latest/demo/subheader and scroll.
Replicated in chrome on PC, Android. Especially on "slow" PC.
Doesn't check it on IOS.

**Comment by RolandHeath** [comment] 2016-05-09 01:06
@olegweb Thanks - hopefully we'll see a bit of work on this now. 
I think this was introduced in 0.11, (I couldn't replicate on 0.10.1, but the behaviour on 0.11 was very obvious) by commit [27ea0c9](https://github.com/angular/material/commit/27ea0c93).

I suspect there has been a partial fix since then, whether intentional or not.

**Comment by ThomasBurleson** [comment] 2016-06-02 06:44
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.

**Comment by NickBolles** [comment] 2016-06-10 01:31
This really should be taken care of... It is extremely janky and it was perfect before v0.11

**Comment by PranayShah** [comment] 2016-08-25 06:22
Can someone please have a look at this? The issue is not so obvious till for smaller width subheaders, but becomes a real pain otherwise.

**Comment by DevVersion** [comment] 2016-08-25 10:40
@PranayShah We are working on some improvements for the stickiness of the `md-subheader`.

> See #9361

**Comment by DevVersion** [comment] 2016-09-01 21:23
Going to merge this issue now into #9361, since on major reason of re-implementing the `$mdSticky` service is to reduce the shaking.

**Closed by DevVersion** 2016-09-01 21:23 UTC
Labels: P2 - Planned Work / Team PRs
