### ISSUE TITLE
md-tabs pagination fails on Safari

### ISSUE THREAD

**Issue by elliottbrookssky** [angular/material#3271] opened 2015-06-15 15:18 UTC
On mobile or desktop Safari, pagination behaviour of md-tabs fails.

See this example from the demo site:

![md-tabs-safari](https://cloud.githubusercontent.com/assets/8545859/8163309/35cb37da-137a-11e5-8b2d-178cf4f88f17.gif)

The chevron icons respond to user interaction, but the tab headers do not move. It's possible to access the hidden tabs through keyboard commands or swiping (if enabled).

**Comment by robertmesserle** [comment] 2015-06-16 22:14
@elliottbrookssky Is this still an issue in 0.10.0?  This should have been resolved in 0.10.0 and I am currently unable to reproduce this issue.

**Comment by robertmesserle** [comment] 2015-06-16 22:15
Closing for now, please reply if this is still an issue and I will re-open.

**Closed by robertmesserle** 2015-06-16 22:15 UTC

**Comment by elliottbrookssky** [comment] 2015-06-19 08:58
Seems to work in 0.10.0 now, yep!
