### ISSUE TITLE
md-select scrolling on click

### ISSUE THREAD

**Issue by moeduffdude** [angular/material#1783] opened 2015-03-04 14:34 UTC
apologies for the poor descriptive title
when md-select is hidden from view, initial click on md-select causes window to scroll (sometimes locking scrolling entirely)

http://codepen.io/anon/pen/MYBQWb

**Comment by mrmarktyy** [comment] 2015-03-05 04:35
+1

**Comment by adonix** [comment] 2015-03-05 05:26
+1

**Comment by mrmarktyy** [comment] 2015-03-05 05:30
I reckon it's a duplicate of #1648

**Comment by bvaughn** [comment] 2015-03-28 00:12
It does sound like a dup of #1648, which has apparently been fixed (but not yet released). Sounds like 0.8.4 will supposedly have this fix in it.

**Comment by marcysutton** [comment] 2015-04-01 00:18
Closing as a duplicate. The fix will be out in 0.9.0.

**Closed by marcysutton** 2015-04-01 00:18 UTC
