### ISSUE TITLE
feat: calendar events enhancement

### ISSUE THREAD

**Issue by artemgrygor** [angular/material#7444] opened 2016-03-07 14:46 UTC
Hey,
Are we going to implement the calendar directive? I mean not a date-picker but a whole one, with month and week views, a new event addition.
Thanks

**Comment by DevVersion** [comment] 2016-03-07 17:18
Maybe a duplicate of #4251, since the `md-datepicker` is using the `md-calendar`, which will hold the year / month selection.

**Comment by artemgrygor** [comment] 2016-03-07 17:23
Oh, didn't know that md-calendar is a part of material toolkit. Thanks

**Comment by jayeshanandani** [comment] 2016-03-14 03:24
Can we close this, since this has already been answered?

**Comment by DevVersion** [comment] 2016-03-14 13:53
I decided to keep this open, because @artemgrygor requested a feature to add events into the calendar.

**Comment by topherfangio** [comment] 2016-03-17 21:41
I think if someone needs events, they will need a more robust calendar like FullCalendar (http://angular-ui.github.io/ui-calendar/ if you want an Angular wrapper).

At the point, I don't think I would anticipate this in the 1.x series; so I'm going to mark it as a 2.0 consideration.

**Comment by ThomasBurleson** [comment] 2016-04-20 19:04
Will not fix.

**Closed by ThomasBurleson** 2016-04-20 19:04 UTC
Labels: needs: team discussion, type: enhancement
