### ISSUE TITLE
ng-messages with md-select not working correctly

### ISSUE THREAD

**Issue by dohomi** [angular/material#6124] opened 2015-12-07 15:59 UTC
Hi

in the current ```rc-6```the ```md-select```in combination with ```ng-messages```is not working correctly:

https://material.angularjs.org/latest/demo/select

The last example shows the overlaying issue if you press the clear button.

**Comment by topherfangio** [comment] 2015-12-07 20:52
Based on the following screenshot, I think it's an issue with floating label, not necessarily the messages. As far as I can tell, the "Required" message is in the correct place.

<img width="460" alt="screen shot 2015-12-07 at 2 51 23 pm" src="https://cloud.githubusercontent.com/assets/54370/11639359/017d5240-9cf2-11e5-90f4-defc0a3d13dd.png">

@ThomasBurleson Can you double check my thoughts above and prioritize this one?

**Comment by topherfangio** [comment] 2015-12-07 20:54
Sorry, just noticed this looks like a duplicate of #6122 which has a PR available. Closing in favor of that issue.

**Closed by topherfangio** 2015-12-07 20:54 UTC
