### ISSUE TITLE
Angular MD 0.11.1 update md-virtual-repeat model

### ISSUE THREAD

**Issue by jabbottn** [angular/material#4589] opened 2015-09-11 14:18 UTC
When I change the data behind an md-virtual-repeat model (that is md-on-demand) nothing happens. I would expect the data to refresh. Example: resorting a list or filtering a list doesn't seem to work. Is this a bug or is there a to tell the list to update. I tried $scope.$digest but no dice.

**Comment by kseamon** [comment] 2015-11-02 22:21
Dupe of #4417

**Closed by kseamon** 2015-11-02 22:21 UTC
