### ISSUE TITLE
menu: refreshing problem

### ISSUE THREAD

**Issue by Samerkassem** [angular/material#11750] opened 2019-06-21 15:00 UTC
The problem is that my `md-menu` is "refreshing" (not flickering) in a strange way,  I am using `$interval` to check for new records in DB. This `md-menu` is for notifications.

To understand visually what it is like check this animated gif:

https://im3.ezgif.com/tmp/ezgif-3-905fb20d2eb1.gif 

There are only 3 notifications in DB, but it's like the `ng-repeat` is "doubling items" on every refresh before displaying stuff correctly.

I have tried `ng-show` and `ng-if` on `md-menu` element and some of its children, nothing worked. I have also tried `ng-cloak` everywhere.

Here's the html code:

```html
<span  class="SminiRedCircle" style="color:yellow; padding-top:1px"
            ng-show="ctrl.unreadCount > 0">{{ctrl.unreadCount}}</span>
<md-menu>
  <md-button
    aria-label="Notifications"
    class="md-icon-button md-small"
    ng-click="ctrl.openMenu($mdMenu, $event)">
    <md-icon
      style="line-height: 17px"
      md-font-icon="fa fa-bell"></md-icon>
  </md-button>

  <md-menu-content  width="4" style="margin-top:25px"
  ng-show="ctrl.notifications.length>0">
    <md-menu-item ng-class={notRead:!note.timeRead}
                                 ng-repeat="note in ctrl.notifications">
      <md-button 
      ng-if="ctrl.notifications.length>0 "
      ng-click="ctrl.gotoNotificationTarget(note)">
        <md-icon
          md-font-icon="fa fa-external-link"
          md-menu-align-target=""
        ></md-icon>
        {{ note.subject }}
      </md-button>
    </md-menu-item>
    
  </md-menu-content>
</md-menu>
```

and here's the relevant js code of the component, notice how I am calling `this.getNotification()` every 5s

```js
    this.getNotifications = async function(){
        try{
            this.notifications = [];
            let response = await $http.post('/notifications/myNotifications', {});
            var apiRet = response.data;
            if (!apiRet.isSessionValid) {
                //$location.path("/login");
                return;
            }
            if (apiRet.isError || !apiRet.isSuccessful) {
                $location.path("/error/There was an error notifications");
                return;
            }
            if (!apiRet.isAllowed) {
                $scope.message = "You do not have permission to view notifications";
                return;
            }
            this.newNotifications = apiRet.data;
            this.notifications = apiRet.data;
            console.log(this.wait)
            this.unreadCount = this.notifications.reduce( (total, current)=>{
                if (current.timeRead){
                    return total;
                } else {
                    return total + 1;
                }
            }, 0);
         
            $scope.$apply();
         
        } catch (error){
            console.log(error);
            $location.path("/error/There was an error");
        }
    };

    this.getNotifications();

    this.interval = $interval(()=>{
       this.getNotifications();
   }, 5000);
```

How to prevent this strange behavior? even instant flickering would be much better than this.

It looks like a bug to me.

**Comment by Splaktar** [comment] 2019-06-22 07:21
Thank you for taking the time to submit this issue. However it does not follow our **required** issue template. Please provide a demo reproduction along with reproduction steps.

Please file a new issue that follows the template. This gives the team the information needed to investigate the bug or prioritize the enhancement.

# CodePen and steps to reproduce the issue:
#### [CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd) which demonstrates the issue: 


#### Detailed Reproduction Steps: 
1. 
1. 

### Which versions of AngularJS, Material, OS, and browsers are affected?
- AngularJS: 1.
- AngularJS Material: 1.
- OS: 
- Browsers:

**Comment by Splaktar** [comment] 2019-07-21 23:12
Closing due to lack of information.

**Closed by Splaktar** 2019-07-21 23:12 UTC
Labels: needs: demo, needs: more info
