### ISSUE TITLE
list: On Enter List with Primary action and Secondary action calling function twice

### ISSUE THREAD

**Issue by gauravlodha** [angular/material#11756] opened 2019-06-27 08:13 UTC
## Bug, enhancement request, or proposal:
Bug

# CodePen and steps to reproduce the issue:
#### [CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd) which demonstrates the issue: 
Issue exist on https://material.angularjs.org/latest/demo/list itself

#### Detailed Reproduction Steps: 
1. Go to Secondary Buttons by using tab
2. Hit Enter on the primary action button
3. Primary action executes twice
4. Now go to secondary action using tab
5. first primary action getting called and after that secondary action

### What is the expected behavior?
If the user hit enter on primary action then it should execute one time
and If the user hit enter on secondary action it should execute the only secondary action

### What is the current behavior?
For primary action: Primary action executes twice
For secondary action: first primary action getting called and after that secondary action

### Which versions of AngularJS, Material, OS, and browsers are affected?

- AngularJS: 1.7.8
- AngularJS Material: 1.1.19
- OS: Windows 10
- Browsers: Chrome
 
### Is there anything else we should know? Stack Traces, Screenshots, etc.
It was working till version 1.1.6

**Comment by Splaktar** [comment] 2019-06-30 10:23
Yep, this looks to be a regression introduced in 1.1.7 (https://material.angularjs.org/1.1.7/demo/list) which is really strange since `md-list` didn't really have any significant changes between `1.1.2` and `1.1.11`.

PR https://github.com/angular/material/pull/11539 fixed an regression in `1.1.0` that made it impossible to click on a secondary action. That fix is in `1.1.13`.

**Comment by Splaktar** [comment] 2019-09-30 22:51
I'm going to wait for a few other `md-list` PRs to go through before I revisit this again
- https://github.com/angular/material/pull/11802
- https://github.com/angular/material/pull/11803
- https://github.com/angular/material/pull/11806

**Comment by Splaktar** [comment] 2020-03-11 18:57
This regression was caused by [ng-aria adding an extra keydown handler to ng-click](https://docs.angularjs.org/api/ngAria#usage). It was caused by PR https://github.com/angular/angular.js/pull/14065 released in AngularJS [`1.6.0`](https://github.com/angular/angular.js/blob/master/CHANGELOG.md#bug-fixes-22).

**Closed** 2020-03-13 17:23 UTC
Labels: P1: urgent, a11y, has: Pull Request, hotlist: Angular 1.6 support, severity: regression, type: bug
