### ISSUE TITLE
#698 If is opened a second dialog, the first one closes automatically. 

### ISSUE THREAD

**Issue by cristian1975** [angular/material#12120] opened 2021-09-03 10:53 UTC
Hi , is worth mention on bug #698 to work fine and dont close the first dialog on opening the second ,the first dialog must not contains a form with (ngsubmit)="submitMethod()" or have a save button with type="submit" , instead must have a save button with  type="button" and  a (click) event that save the form data.

**Comment by cristian1975** [comment] 2021-09-03 11:08
In first dialog this code will cause to close the first dialog when open the second dialog:
 <form [formGroup]=''form" (ngSubmit)="submit(form)">
   <button (click)="openSecondDialog()" ></button>
   <button type="submit" >Save</button>
</form>

The working example that not close first dialog:
 <form [formGroup]=''form" >
   <button (click)="openSecondDialog()" ></button>
   <button type="button" (click)="submitMethod(form)" >Save</button>
</form>

It will help other people from digging for hours to see  the cause.

**Comment by Splaktar** [comment] 2021-11-18 21:59
OK, thank you for sharing that workaround Cristian. However, I'm going to close this since there isn't a StackBlitz reproduction that can be used to debug this, plus there seems to be a workaround.

**Closed by Splaktar** 2021-11-18 21:59 UTC
Labels: type: bug, needs triage
