### ISSUE TITLE
Input validation broken when using a validator plus `required`

### ISSUE THREAD

**Issue by artoale** [angular/material#6812] opened 2016-01-22 13:10 UTC
As per this pen: http://codepen.io/anon/pen/vLdORp.
I've changed one of the demo example to include a field which is both required and must be a valid email.
If you type something which is not a valid email the error appears correctly, but if you then clear the input field, the item remains red (correctly), but the "required" error message doesn't show up.

Also the opposite is true: if you immediately blur the field (getting the "required error correctly) and then you type an invalid email address, it still shows the red bar, but no error message.

**Comment by artoale** [comment] 2016-01-22 14:55
I've just realized this also happen by simply removing `md-auto-hide="false"` from all multi-message example on the live doc. A possible workaround: 
```html
 <div ng-messages="projectForm.clientEmail.$error" role="alert" md-auto-hide="false" ng-show="projectForm.contact_email.$touched">
```

**Comment by topherfangio** [comment] 2016-02-05 00:13
Duplicate of #6399.

**Closed by topherfangio** 2016-02-05 00:13 UTC
Labels: P4 - Reported By or General PRs/Errors or Edge Cases
