### ISSUE TITLE
md-autocomplete drop down behavior

### ISSUE THREAD

**Issue by WieldSoftwareDevelopement** [angular/material#4343] opened 2015-08-26 21:42 UTC
This ticket applies to release: 0.10.1-master-97a8f6d

First off I noticed the performance is really fast now that auto complete us using virtual repeat internally. Kudos on that!

Though there is still some funny behavior with the drop down portion.  All of these examples are repeatable on the current head documentation site.

This bad drop down behaviour is related entirely to making a selection.  If you make a choice and md-not-found is present then you get a message in the drop down stating that no results are found for that selection.  Which is strange, because I just picked it!  If md-not-found is not present the drop down area is empty but does not disappear after a selection is made.

**Comment by hannupekka** [comment] 2015-08-27 06:13
+1 for this. Below is a screenshot from the CodePen showing "Basic Usage" demo of md-autocomplete:
<img width="1276" alt="screenshot 2015-08-27 09 11 43" src="https://cloud.githubusercontent.com/assets/4472477/9513730/cea2e138-4c9b-11e5-9559-4a18ed2b18ef.png">

**Comment by kuhnroyal** [comment] 2015-08-27 10:05
+1
Commented on the commit (https://github.com/angular/material/commit/f81719363d0445aa6dc393ba42631a3ba7d77071) yesterday but an issue is probably better.
@kseamon @ThomasBurleson could you please have a look.

**Comment by ngraef** [comment] 2015-08-27 14:00
Duplicate of #4309

**Comment by mohitadwani** [comment] 2015-08-28 08:32
+1

**Comment by kuhnroyal** [comment] 2015-09-02 10:58
This is now working again in master.

Before the virtual-repeat rework of md-autocomplete, I was able to defined a custom size of the drop down menu, this is no longer working. The `md-menu-class` should probably be set onto the `md-virtual-repeat-container` so that custom styling can be achieved?!

**Closed** 2015-09-10 17:14 UTC
