### ISSUE TITLE
Demos don't work on iPhone 4, iOS 7.1.2 both in Safari and Chrome 47

### ISSUE THREAD

**Issue by super-coder** [angular/material#6678] opened 2016-01-14 08:30 UTC
I am not sure what n-1 browser support mean in this case, but Menu doesn't scroll and demos don't work on the iPhone 4. Like nothing works basically
![2016-01-14 11 18 10](https://cloud.githubusercontent.com/assets/2155554/12319243/0b8e628c-bab2-11e5-855c-cc191ad3110f.png)
![2016-01-14 11 15 32](https://cloud.githubusercontent.com/assets/2155554/12319245/0d3b0c98-bab2-11e5-9ba2-8f687365bbad.png)
![image](https://cloud.githubusercontent.com/assets/2155554/12319261/23d754a2-bab2-11e5-99bc-6bf335d09409.png)

**Comment by DevVersion** [comment] 2016-01-14 15:35
This is issue is a dupe of #6573

**Comment by super-coder** [comment] 2016-01-14 19:31
not only

**Comment by DevVersion** [comment] 2016-01-14 19:35
Can you please provide more information, instead of just denying. The `md-card` issue on iOS is related to #6573 - Cards is related to the `Flexbox` Layout. About your scrolling, I can't reproduce that. It's working on the latest Safari.

**Comment by super-coder** [comment] 2016-01-14 19:40
i have an iphone 4 and 
1) I can't scroll left menu
2) text doesn't wrap in grey boxes 

for a start

**Comment by DevVersion** [comment] 2016-01-14 19:44
Good... Problem 2, will be handled in #6573.

**Comment by mprentic-harris** [comment] 2016-01-14 20:00
@super-coder n-1 means that the current version and previous version are supported. This means Safari 9 (current) and 8 are supported. Safari 7 in iOS 7.1.2 is not supported.

**Comment by super-coder** [comment] 2016-01-14 20:02
@mprentic-harris but what about Chrome 47? It also doesn't work

**Comment by mprentic-harris** [comment] 2016-01-14 21:58
@super-coder Chrome on iOS has to use the same Safari webkit engine due to Apple restrictions. So only the Safari/iOS version matter.

**Comment by DevVersion** [comment] 2016-01-21 15:33
Should be fixed in #6765

**Closed** 2016-01-21 21:54 UTC
Labels: P3 - Docs / Demos / Internal Contrib
