### ISSUE TITLE
Subheader calls constructor of children twice

### ISSUE THREAD

**Issue by Remco75** [angular/material#10158] opened 2016-12-20 15:29 UTC
**Actual Behavior**:
 -  `When using md-subheader and transcluding custom components the constructor of the class is called twice *`
 -  `It should be called once`

**CodePen** (or steps to reproduce the issue): *
 -  `<md-subheader><my-custom-component></my-custom-component></md-subheader>`
 -  `log something in the constructor of the controller: it will appreat twice in the log:`

**Angular Versions**: *
 -  `Angular Version:1.5.9`
 -  `Angular Material Version:1.1.1`

**Additional Information**:
 -  `Browser Type: *`
 -  `Browser Version: *`
 -  `OS: *`
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by Remco75** [comment] 2017-01-06 13:51
ok, is there an issue number also known? then I can subscribe

**Comment by ThomasBurleson** [comment] 2017-01-06 14:26
@DevVersion - do we have an previous issue existing for this known code issue ?

**Comment by DevVersion** [comment] 2017-01-06 14:29
@ThomasBurleson We had a lot issues about similar things, that the `ng-repeat` is called twice for example.

This is caused by the sticky clone elements we compile at runtime. We have a big issue for this https://github.com/angular/material/issues/9361

**Comment by Splaktar** [comment] 2018-11-21 00:50
Closing this as it's tracked in https://github.com/angular/material/issues/9361.

**Closed by Splaktar** 2018-11-21 00:50 UTC
