### ISSUE TITLE
md-autocomplete with enabled (ajax) query does not work on mobile

### ISSUE THREAD

**Issue by leibler** [angular/material#4963] opened 2015-10-01 13:38 UTC
Tested on android 4.3, android 4.4 and android 5.0 using chrome mobile:
Open https://material.angularjs.org/HEAD/#/demo/material.components.autocomplete
In "Basic Usage" example check [X] "Simulate query results?"
Start typing in Field a ... the Dropdown loads and displays state list starting with "a"
Now type l ... the Dropdown loads again and displays state list starting with "l" 
The first "a" is cleared.
So searching does not work on mobile because md-autocomplete only uses last character.

See screenshot 1 with starting 'a'
![screenshot_2015-10-01-15-35-32](https://cloud.githubusercontent.com/assets/4221541/10222098/744d44e4-6852-11e5-806a-1d2fdc0ca661.png)
Now type 'l' and see screenshot 2:
![screenshot_2015-10-01-15-35-38](https://cloud.githubusercontent.com/assets/4221541/10222106/806b582e-6852-11e5-926c-903d3a1c7fb8.png)

**Comment by topherfangio** [comment] 2015-10-01 15:18
Duplicate of #4669.

**Closed by topherfangio** 2015-10-01 15:18 UTC
