### ISSUE TITLE
md-list-item doesn't recognize data-ng-click

### ISSUE THREAD

**Issue by dietergeerts** [angular/material#4392] opened 2015-08-31 19:27 UTC
it does recognize ng-click, but not data-ng-click. Strange, as Angular can use them interchangeable.

**Comment by marcysutton** [comment] 2015-10-12 17:10
Can you provide a demo showing your markup? List items by themselves are not interactive, while list controls do some fancy things behind the scenes. More info about which element should be clickable will help to debug. Thanks.

**Comment by jpittenger** [comment] 2015-10-19 18:15
I've added a jsbin example here:

https://jsbin.com/kuhorufola/5/edit?html,js,output

**Comment by topherfangio** [comment] 2015-11-23 15:45
Note to self: can still reproduce on RC4 or greater.

**Comment by tarlepp** [comment] 2015-11-29 10:43
Yeah I noticed this too yesterday. It's weird that UI seems to be working as excepted with ```data-ng-click``` but it won't fire that click event.

**Comment by DevVersion** [comment] 2015-11-29 12:01
I created a fix for that -> see #5976

**Comment by Magador** [comment] 2016-07-21 12:24
Fixed in b3e401a70777b924dcb69c6fe4dd2e6c6cf19707

**Comment by DevVersion** [comment] 2016-07-21 13:12
Thanks for the ping @Magador

**Closed by DevVersion** 2016-07-21 13:12 UTC
Labels: needs: merge, priority: low, severity: inconvenient
