### ISSUE TITLE
Multiple tabs with a md-autocomplete element

### ISSUE THREAD

**Issue by trazek** [angular/material#3425] opened 2015-06-23 18:32 UTC
The situation is if we have 2 tabs (example: tab-a and tab-b) and each have a `md-autocomplete` element, the following bug happens:

The user views tab-a; everything is fine.
The user clicks and navigates to tab-b; everything is fine.
The user navigates back to tab-a; An extra `<ul>` with class, `md-auto-suggestions` is created and when the user types in the search box, an extra suggestion box appears near the top of the page. 

It seems when switching tabs, the original suggestion box is being restored along with a newly created one. Has anyone else encountered this problem?

**Comment by robertmesserle** [comment] 2015-07-16 17:23
I believe this has already been resolved, closing the issue.  If it is not resolved, please add a CodePen demonstrating this issue against HEAD.  (I tried to create a CodePen, but was unable to reproduce this issue with the latest code.)

**Closed by robertmesserle** 2015-07-16 17:23 UTC

**Comment by trazek** [comment] 2015-08-16 02:34
Indeed appears fixed. Thanks for looking into this
