### ISSUE TITLE
md-contact-chips does not trigger ng-change

### ISSUE THREAD

**Issue by alcfeoh** [angular/material#3145] opened 2015-06-06 00:09 UTC
When using md-contact-chips , changes to the model do not trigger ng-change. This works well with other material design components so I was expecting it to work with md-contact-chips.

**Comment by typotter** [comment] 2015-08-10 16:33
duplicate of #3857

**Closed by typotter** 2015-08-10 16:33 UTC

**Comment by vishal41190** [comment] 2015-10-15 22:03
+1
