### ISSUE TITLE
autocomplete results container height is not ok with a query ( after clear() )

### ISSUE THREAD

**Issue by NicolasBlois** [angular/material#6197] opened 2015-12-09 12:43 UTC
![ezgif-820990270](https://cloud.githubusercontent.com/assets/6443098/11685658/f8060272-9e7a-11e5-8f2f-d3facca0467b.gif)

**Comment by alexkb** [comment] 2015-12-11 01:39
+1

Confirming issue is in Chrome & Firefox but not IE10/IE11.

**Comment by blootch** [comment] 2015-12-15 12:58
@kseamon @ThomasBurleson

**Comment by rfuhrer** [comment] 2015-12-15 21:07
+1
seems to be some sort of race condition because I can cause the cause the issue on https://material.angularjs.org/latest/demo/autocomplete in the custom template section just by picking one and then clearing it multiple times.  It breaks about 95% of the time within 4 select and clears, sometimes it only takes one.

**Comment by jameswyse** [comment] 2015-12-24 04:07
:+1: Seeing this in 1.0.1

**Comment by GavinPalmer1984** [comment] 2016-01-08 18:52
+1
nice GIF by the way (never seen that used in a bug report and I am curious how you did it)

**Comment by NicolasBlois** [comment] 2016-01-09 14:57
@GavinPalmer1984 : I used a screen recorder (kazam on ubuntu) then I convert it to gif
@ThomasBurleson https://github.com/angular/material/pull/6346/files this resolves this issue for me.

**Comment by ThomasBurleson** [comment] 2016-04-19 19:38
Already fixed in HEAD.

**Closed by ThomasBurleson** 2016-04-19 19:38 UTC
Labels: needs: merge, P1 - Broken Renders / Major Use Cases
