### ISSUE TITLE
md-autocomplete not firing focus events. 

### ISSUE THREAD

**Issue by dmackerman** [angular/material#4095] opened 2015-08-11 15:32 UTC
Angular `1.4.3` and Material `0.10.1-rc5`.

I've copied the examples for `mdAutocomplete` directly in my application and am seeing some weird issues.

For whatever reason, when the field is focused - *not having typed anything yet* - no events (and therefore no classes) are added, so the menu doesn't show "all" results.  In the docs, the `md-menu-shown` class is added to the `md-autocomplete-wrap` element on mouse focus.

This may be related to https://github.com/angular/material/issues/4046, but I can't say for sure.  This happens to me everywhere, not just confined to inside an `mdDialog`.

I can't seem to get it to reproduce on Codepen or in the docs application, so i'm not sure why this is happening. The autocomplete works as expected once keystrokes are entered, but it's pretty broken behavior to not show "all" results on focus if the entire array is available on scope.

**Comment by elubin** [comment] 2015-08-11 21:53
Ditto.  Weird focus events with md-autocomplete on an md-dialog inside md-chips.  (although i'm not sure that has anything to do with it, but it makes seeing the issue easier)  In my case, the issue is because md-min-length="0" because i wanted to show all 9 options to the user immediately instead of making them select one.

http://jsfiddle.net/5m9rpcrn/

(added the same note to 4046)

**Comment by robinsving** [comment] 2015-08-17 11:22
@dmackerman I am seeing the same issues with md-autocomplete. 
On initial focus, nothing is added.
Upon typing anything in the field the (filtered) list is shown, and when removing all input, then blurring and *then* refocusing it now shows the entire list as it should.
Console logging shows that the filtering function is not triggered on first focus
[When using Codepen](http://codepen.io/anon/pen/ZGNpmq?editors=101), however, the error is not reproducible - here it works as intended.

My angular-materials version comes from npm, version 0.10.1

**Comment by dmackerman** [comment] 2015-08-18 14:01
Glad others are seeing this.

**Comment by Alex-iFactory** [comment] 2015-08-21 04:03
+1

**Comment by topherfangio** [comment] 2015-10-01 05:31
I just pushed PR #4958 which fixes many issues and I will post an update here once it is merged asking if you can retest against that version.

**Comment by dmackerman** [comment] 2015-10-01 15:20
Thanks @topherfangio. Will check it out again once it's merged.

**Comment by topherfangio** [comment] 2015-10-08 15:05
@dmackerman PR #4958 has been merged, can you please test again?

**Comment by spoco2** [comment] 2016-02-22 02:20
Still has this issue.

On top of that doesn't trigger ng-blur put on component either.

**Comment by topherfangio** [comment] 2016-02-22 17:09
@spoco2 - I have updated the above Plunker to use the latest versions of Angular 1.3.x and Material 1.0.x and it seems to be working as desired: http://jsfiddle.net/skct9Ly9/

Can you tell us a bit more what your exact issue is and what versions you are using?

**Closed** 2016-04-28 20:24 UTC
Labels: priority: low
