### ISSUE TITLE
Slider display bugs when slider is hidden on page load

### ISSUE THREAD

**Issue by julbr** [angular/material#1328] opened 2015-01-29 04:45 UTC
When a slider is inside div that is hidden by default using ng-hide, then on ng-show of the div, the slider display is buggy.
[Here is the plunker that reproduces the issue.](http://plnkr.co/edit/QOPlXogcRcEXdFv7tZIt?p=preview)

**Comment by PaulMougel** [comment] 2015-01-29 09:12
Duplicate of #1210.
This is fixed in master by 41c2d65d2d4344687959c0d13c2cf48b0c90a880

**Closed** 2015-03-10 14:45 UTC
