### ISSUE TITLE
md-autocomplete items always are spoken as `Status` by ChromeVoxNext when focused.

### ISSUE THREAD

**Issue by cai-feng** [angular/material#11003] opened 2017-12-05 21:35 UTC
md-autocomplete items always are spoken as `Status` by ChromeVoxNext when focused, while the JAWS does speak them correctly.

**Comment by Splaktar** [comment] 2018-08-11 20:16
Closing as duplicate of https://github.com/angular/material/issues/10896.

**Closed by Splaktar** 2018-08-11 20:16 UTC
Labels: P1: urgent, a11y, reported by Googler, resolution: duplicate
