### ISSUE TITLE
md-select doesn't flex

### ISSUE THREAD

**Issue by stevenmiles** [angular/material#3167] opened 2015-06-08 14:58 UTC
The contents of the md-select directive doesn't fill it's container when flex is used on the md-select. The md-select tag in the DOM itself seems to flex, but its content doesn't. 

http://codepen.io/stevenmiles/pen/jPmxGw

**Comment by dillyboy** [comment] 2015-06-11 07:05
Yes, so they take the code which works properly in the previous version and mess it up. To correct issuse I used style="width:100%" on the md-select-label.

**Comment by chinnichaitanya** [comment] 2015-06-11 07:19
@dillyboy It is not that they do it on purpose. Please understand that they are providing more enhancements and in the process, somethings might break.
It is not like they are messing things.

**Comment by dillyboy** [comment] 2015-06-11 08:03
Yes true and I appreciate all the extra effort,but its not the first time we have to update our company Apps because of errors in the new version like this. About 30 apps.

**Comment by rhnatiuk** [comment] 2015-06-22 07:43
md-select is rather completely broken in IE11 - it is not auto-sized (flex doesn't work), scroll-bars appear on parent containers, list is wrongly positioned, etc. Looks like a lot of regression bugs are back.

**Comment by kitensei** [comment] 2015-06-22 08:04
same problem with md-select on both chrome and firefox, the "click" handle is flex, but not the display.

**Comment by wenbolovesnz** [comment] 2015-06-22 08:26
I had the same problem. But I was able to work around it by add an
additional style to set the width as 100% on md-select.

**Comment by ngraef** [comment] 2015-06-25 17:38
Related: #3055

**Comment by ngraef** [comment] 2015-07-13 15:27
Fixed by 14786283200a5e488742a7d9598cf2fe75cfd2d2

**Closed** 2015-07-13 19:23 UTC
