### ISSUE TITLE
long textarea inside md-input-container on iOS jumps

### ISSUE THREAD

**Issue by eb-clickfusion** [angular/material#10529] opened 2017-03-23 19:58 UTC
**Actual Behavior**:
 -  `What is the issue? *`
when a textarea contains a lot of text and the user focuses on the textarea, somewhere near the bottom, once you begin typing the browser jumps up to the top of the textarea so you can't see what you're writing
 -  `What is the expected behavior?`
the browser should not jump to the top if you're changing text near the bottom, it should stay in the same position.

**CodePen** (or steps to reproduce the issue): *
 -  `Details:`
This can be replicated on the angular material site on the input demo page. If you type a lot of text in the biography textarea, lose focus, then re-focus at the bottom of the textarea and begin typing.

**AngularJS Versions**: *
 -  `AngularJS Version:`
1.6.3
 -  `AngularJS Material Version:`
1.1.3

**Additional Information**:
 -  `Browser Type: *` Safari
 -  `Browser Version: *` 10.0
 -  `OS: *` iOS 10.2.1

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by Splaktar** [comment] 2018-01-21 08:35
Duplicate of https://github.com/angular/material/issues/3070.

**Closed by Splaktar** 2018-01-21 08:35 UTC
Labels: resolution: duplicate
