### ISSUE TITLE
md-datepicker changes format while manually entering date

### ISSUE THREAD

**Issue by AshwanKumar** [angular/material#7458] opened 2016-03-08 14:13 UTC
Hi Team,

We are using angular material components in our project and for having customized dates we used angular material date picker in localized date format

For Example if we change the local language in chrome to German then the date format will be d.m.yyyy,so when user manually change the date value through keyboard then the format of date picker changes to m.d.yyyy i.e if the date is 8.3.2016(8th march 2016) then if we change the date to 8.2.2016 using keyword the date in calender is 2nd august 2016

Here are screenshot which demostrates following issue.

![untitled1](https://cloud.githubusercontent.com/assets/17707222/13603792/aff140f0-e565-11e5-8bbb-b549ed31e761.png)

![untitled2](https://cloud.githubusercontent.com/assets/17707222/13603803/bf6ebf58-e565-11e5-878b-ef12f07f23a3.png)

We even tried $mdDateLocaleProvider,but didnt get any solution through it as we need to maintain date in localize format which different from browsers and also with browser's language settings as well.

Thanks & Regards,
Ashwan Kumar Siddireddi
ashwan.s.91@gmail.com

**Comment by topherfangio** [comment] 2016-03-21 22:41
Closing as duplicate of #7404, but huge thanks for describing the issue and providing screenshots! I have reprioritized the older issue.

**Closed by topherfangio** 2016-03-21 22:41 UTC
Labels: P1 - Broken Renders / Major Use Cases
