### ISSUE TITLE
md-autocomplete does not work with ng-messages validation

### ISSUE THREAD

**Issue by MetalHexx** [angular/material#3401] opened 2015-06-22 20:48 UTC
As per issue #1780, ng-messages still fails to fire on md-autocomplete directives.

I've tried using the "name", "input-name", and "md-input-name" attribute on the md-autocomplete element and of course added a required attribute.

After trying to submit the form to save, the md-autocomplete form element does not show up as member on the $scope.form object.  Oddly enough, the $scope.form.$valid == false if you check it.  It just doesn't render the ng-message.  

The code pen linked off the autocomplete demo site also does not work.  I had to save it to share it:
http://codepen.io/MetalHexx/pen/qdVBLa

**Comment by MetalHexx** [comment] 2015-06-22 20:52
For those who still want to use the autocomplete control bundled with angular-material, You can add an input element below the autocomplete and add an ng-hide="true" to hide the control.  The ng-message will still render and appear to refer to the md-autocomplete control.

**Comment by caok2709** [comment] 2015-06-22 22:09
+1

**Comment by vicky-gonsalves** [comment] 2015-06-25 10:46
+1

**Comment by robertmesserle** [comment] 2015-06-26 15:52
Sorry guys, this was broken right before I was out for a little over a week and went entirely too long without being addressed.  Fixing this now.

**Comment by MetalHexx** [comment] 2015-06-28 01:36
Thanks for the quick turnaround, robert!  When will this fix be live?

**Comment by vicky-gonsalves** [comment] 2015-06-29 05:10
@robertmesserle Thanks for the quick fix. Hoping to get it live soon.

**Comment by prxg22** [comment] 2015-08-10 13:46
Hey @robertmesserle, any idea when this feature will be live?? thanks (:

**Comment by iamryandrake** [comment] 2016-02-03 23:19
Hey @robertmesserle , when will this be live?

**Comment by czery** [comment] 2016-02-18 16:22
Hey there, also would love to see this live. Any assumption? @robertmesserle

**Comment by SelmanAY** [comment] 2016-03-08 21:44
+1

**Comment by eniniz** [comment] 2016-03-23 10:27
+1

**Comment by alois-wever** [comment] 2016-03-23 12:42
+1

**Comment by jojogeyer** [comment] 2016-03-23 12:42
+1

**Comment by bakhlov** [comment] 2016-03-23 20:36
+1

**Comment by shrutiaggarwal3012** [comment] 2016-04-10 15:41
+1

**Comment by piyushchauhan2011** [comment] 2016-04-19 07:12
Using `ng-form` instead of `form`, `ng-messages` with autocomplete doesn't work

**Comment by alois-wever** [comment] 2016-04-19 07:51
Hi @piyushchauhan2011 ,  

The `ng-form` directive is not a replacement for the `form` tag. In the docs they say:
> The purpose of ngForm is to group controls, but not to be a replacement for the <form> tag with all of its capabilities (e.g. posting to the server, ...).

So use your `ng-form` nested into a form tag, and everything should works as expected.

**Comment by iamryandrake** [comment] 2016-04-29 03:59
This is still an issue where validations do not fire.

**Comment by sebasecheverry** [comment] 2016-05-03 21:47
The issue still presents in the actual version, I'm using  version v1.0.6, but it does'nt work correctly for md-select as it doesn't shows the redline. But actual version does show it for md-select.

however is not working correctly for autocomplete

**Comment by stephengardner** [comment] 2016-05-07 07:51
+1

**Comment by tom94zoe** [comment] 2016-06-07 08:12
+1

**Comment by che85** [comment] 2016-06-14 15:27
+1

**Comment by vinhnghi223** [comment] 2016-08-15 12:16
+1

**Comment by alegadpen** [comment] 2016-09-26 19:59
+1

**Comment by Jpatrick2zo** [comment] 2016-10-19 19:35
+1

**Comment by ThomasBurleson** [comment] 2016-10-19 22:37
Based on community votes: re-opening.

**Comment by topherfangio** [comment] 2016-10-20 14:38
Closing as duplicate of https://github.com/angular/material/issues/9468. Discussing with @crisbeto on who will own.

**Closed by topherfangio** 2016-10-20 14:38 UTC
Labels: type: enhancement

**Comment by mohitangiras** [comment] 2018-07-21 07:32
<div layout="row" layout-align="space-between"
                     	class="myContainer" ng-init="$watch('innerIndex=$index')">

then use innerIndex inside the container. This works for me
