### ISSUE TITLE
New Data Tables

### ISSUE THREAD

**Issue by calebeaires** [angular/material#2353] opened 2015-04-16 12:38 UTC
Google has release Data Tables to its android sdk. Will it be supported on Material Angular?

Reference: http://www.google.com/design/spec/components/data-tables.html#

**Comment by dmackerman** [comment] 2015-04-16 12:40
I'd think maybe at a base level they would in terms of styles and whatnot, but adding in complex sorting / filtering is probably out of scope. I could be wrong though. :smile:

**Comment by Angularjschile** [comment] 2015-04-16 12:47
+1

**Comment by victormacae** [comment] 2015-04-16 13:29
+1

**Comment by skolade** [comment] 2015-04-16 13:30
+1

**Comment by dongmingliy** [comment] 2015-04-16 14:02
+1

**Comment by ask007java** [comment] 2015-04-16 14:32
+1

**Comment by lothargrieb** [comment] 2015-04-16 15:46
+1

**Comment by ThomasBurleson** [comment] 2015-04-16 15:51
Duplicate of #796

**Closed by ThomasBurleson** 2015-04-16 15:51 UTC

**Comment by davidpp** [comment] 2015-06-10 04:19
Trying to figure out if tables are supported.  This issue has been closed because it's a duplicate of #796, but #796 is closed because of #2353 (this issue).  Catch 22? :)

**Comment by rudzikdawid** [comment] 2015-07-21 08:55
+1

**Comment by 4z8397qju3k7** [comment] 2015-07-29 00:29
+1

**Comment by pbaris** [comment] 2015-08-01 14:34
+1
