### ISSUE TITLE
md-input-container height issues in 1.0.0-rc2

### ISSUE THREAD

**Issue by hodeyp** [angular/material#5463] opened 2015-10-30 19:27 UTC
17797f001533288560854b04de81f53c552d2a80 has broken input alignment - I see there is a new md-block class to make the md-input-container fill the parent element but the ng-messages section is causing height changes when the input changes from valid to error.

**Comment by houmark** [comment] 2015-10-31 04:04
Related to #5298

**Comment by robertmesserle** [comment] 2015-11-02 20:18
Can you confirm that this is still broken in master?  I believe this should be fixed but not released yet.

**Comment by robertmesserle** [comment] 2015-11-02 20:20
Ah, nevermind - just checked against the latest and this is still an issue.

**Comment by robertmesserle** [comment] 2015-11-02 20:21
Closing as a duplicate of #5462

**Closed by robertmesserle** 2015-11-02 20:21 UTC
Labels: ux: integration
