### ISSUE TITLE
mdDatepicker calendar opens up to wrong view

### ISSUE THREAD

**Issue by ppham27** [angular/material#10144] opened 2016-12-15 19:52 UTC
**Actual Behavior**:
 -  `What is the issue? *` When I click on the datepicker, the calendar view shows the wrong month.
 -  `What is the expected behavior?` It should open up to the currently selected date or the current date.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` https://material.angularjs.org/latest/demo/datepicker
 -  `Details:` Here's a video, https://youtu.be/N3EK1ByvhV0

**Angular Versions**: *
 -  `Angular Version:` 1.5.9
 -  `Angular Material Version:` 1.1.1

**Additional Information**:
 -  `Browser Type: *` Chrome
 -  `Browser Version: *` 55
 -  `OS: *` Ubuntu 12.04
 -  `Stack Traces:` N/A

I should note that this problem doesn't occur in OS X. It also only occurs on the Angular Material Demo page, but works fine in the CodePen.

**Comment by jsgoupil** [comment] 2016-12-15 21:41
I see the same problem with Angular Material 1.0.6. It actually scrolls to April 2017 for me.

**Comment by xxmuaddib** [comment] 2016-12-16 07:29
I have created a plnkr with a similiar problem. md-datepicker doesn't even render.

- Angular Version: 1.6.0
- Angular Material Version: 1.1.1
- Google Chrome Version: 54

[https://plnkr.co/edit/4YBK4Eb8LVNeQbH5wIac](https://plnkr.co/edit/4YBK4Eb8LVNeQbH5wIac)

**Comment by rhinoceraptor** [comment] 2016-12-16 18:21
I have this problem with:

- Angular 1.5.9
- Angular Material 1.1.1
- Chrome 55
- OS: macOS 10.12.1

**Comment by DAquilina** [comment] 2016-12-20 16:07
Confirming same problem:

- Angular 1.5.8
- Angular Material 1.1.1
- Chrome 55.0.2883.87 (64-bit)
- Ubuntu 16.04.1 LTS

Note that this issue does not seem to occur in Firefox.

**Comment by julioponce** [comment] 2016-12-21 18:38
Same issue with:

Angular: 1.5.8
Material: 1.1.0
Browser: Chrome 55.0.2883.95 (64-bits)
Mac OS X El Capitan 10.11.6

**Comment by Dinosys** [comment] 2016-12-22 08:26
Same issue with:

Angular: 1.5.8
Material: 1.1.1
Browser: Chrome 55.0.2883.87
OS: Windows 10

Adding: 
It always seems to scroll two months too far. Right now the selected date is 22-12-2016, it will scroll to Februari 2017 when opened. If you change the date to 22-02-2017 and then open it will scroll to April 2017

**Comment by paynam** [comment] 2016-12-22 21:38
Confirming same issue:

Angular. 1.5.10
Material: 1.1.1
Browser: Chrome 56.0.2924.28 beta (64-bit)
OS: Windows 10

If I resize the browser window or scroll the md-content a little bit the issue disappears.

**Comment by kc1116** [comment] 2016-12-23 17:00
Has anyone been able to fix this problem?

**Comment by ppham27** [comment] 2016-12-25 01:45
I submitted a pull requests that should fix the issue. Please try the below CodePens below to see if it fixes it for you.

CodePens:
- [Broken Datepicker](http://codepen.io/phillypham/pen/gLJXgY)
- [Fixed Datepicker](http://codepen.io/phillypham/pen/xRNPdJ)

**Comment by jsgoupil** [comment] 2016-12-28 02:05
@ppham27 Your patch seems to work with 1.1.1, but not with 1.0.6.

I'm not expecting to make it work with that old of a version, but letting people know that if they take only his change in their version, it might not work.

**Comment by czesiu** [comment] 2017-01-16 08:17
Same issue (version 1.1.1 - before fix):
- Angular 1.5.5
- Angular Material 1.1.1
- Chrome 55.0.2883.87
- OS: Windows 10

Codepen: http://codepen.io/czesiu/pen/dNpdWO

I tired to fix this and for me works commenting this line: https://github.com/angular/material/blob/master/src/components/virtualRepeat/virtual-repeater.js#L357

**Comment by ernsheong** [comment] 2017-01-24 04:08
Any patch release soon? Or otherwise, a pointed on how we can point to master and get the latest code using npm is appreciated

**Comment by topherfangio** [comment] 2017-01-30 19:56
@ernsheong With NPM, just update your `package.json` to specify `angular-material#master`. That should grab the latest.

**Comment by nganbread** [comment] 2017-02-19 20:33
This is ~~~a bit~~~ very gross, but while we wait for the PR to be merged, I've done the following

``` javascript
angular.module("material.components.virtualRepeat")._invokeQueue[1][2][1]().controller.prototype.virtualRepeatUpdate_ = function (items, oldItems) {
        this.isVirtualRepeatUpdating_ = true;

        var itemsLength = items && items.length || 0;
        var lengthChanged = false;

        // If the number of items shrank, keep the scroll position.
        if (this.items && itemsLength < this.items.length && this.container.getScrollOffset() !== 0) {
            this.items = items;
            var previousScrollOffset = this.container.getScrollOffset();
            this.container.resetScroll();
            this.container.scrollTo(previousScrollOffset);
        }

        if (itemsLength !== this.itemsLength) {
            lengthChanged = true;
            this.itemsLength = itemsLength;
        }

        this.items = items;
        if (items !== oldItems || lengthChanged) {
            this.updateIndexes_();
        }

        this.parentNode = this.$element[0].parentNode;

        if (lengthChanged) {
            this.container.setScrollSize(itemsLength * this.itemSize);
        }

        var cleanupFirstRender = false, firstRenderStartIndex;
        if (this.isFirstRender) {
            cleanupFirstRender = true;
            this.isFirstRender = false;
            firstRenderStartIndex = this.$attrs.mdStartIndex ?
                this.$scope.$eval(this.$attrs.mdStartIndex) :

                this.container.topIndex;
            this.container.scrollToIndex(firstRenderStartIndex);
        }


        // Detach and pool any blocks that are no longer in the viewport.
        Object.keys(this.blocks).forEach(function (blockIndex) {
            var index = parseInt(blockIndex, 10);
            if (index < this.newStartIndex || index >= this.newEndIndex) {
                this.poolBlock_(index);
            }
        }, this);

        // Add needed blocks.
        // For performance reasons, temporarily block browser url checks as we digest
        // the restored block scopes ($$checkUrlChange reads window.location to
        // check for changes and trigger route change, etc, which we don't need when
        // trying to scroll at 60fps).
        this.$browser.$$checkUrlChange = angular.noop;

        var i, block,
            newStartBlocks = [],
            newEndBlocks = [];

        // Collect blocks at the top.
        for (i = this.newStartIndex; i < this.newEndIndex && this.blocks[i] == null; i++) {
            block = this.getBlock_(i);
            this.updateBlock_(block, i);
            newStartBlocks.push(block);
        }

        // Update blocks that are already rendered.
        for (; this.blocks[i] != null; i++) {
            this.updateBlock_(this.blocks[i], i);
        }
        var maxIndex = i - 1;

        // Collect blocks at the end.
        for (; i < this.newEndIndex; i++) {
            block = this.getBlock_(i);
            this.updateBlock_(block, i);
            newEndBlocks.push(block);
        }

        // Attach collected blocks to the document.
        if (newStartBlocks.length) {
            this.parentNode.insertBefore(
                this.domFragmentFromBlocks_(newStartBlocks),
                this.$element[0].nextSibling);
        }
        if (newEndBlocks.length) {
            this.parentNode.insertBefore(
                this.domFragmentFromBlocks_(newEndBlocks),
                this.blocks[maxIndex] && this.blocks[maxIndex].element[0].nextSibling);
        }


        if (cleanupFirstRender) {
            this.container.scrollToIndex(firstRenderStartIndex);
        }


        // Restore $$checkUrlChange.
        this.$browser.$$checkUrlChange = this.browserCheckUrlChange;

        this.startIndex = this.newStartIndex;
        this.endIndex = this.newEndIndex;

        this.isVirtualRepeatUpdating_ = false;
    };
```

**Comment by shardool** [comment] 2017-02-22 02:18
did we get this fixed yet ? Please let me know, if there is a quick way around this ?

**Comment by julioponce** [comment] 2017-02-22 04:19
This is not the best solution but a quick fix, just reseting the scroller to 0 to keep the top of the scroll in hideVerticalScrollbar function:

```
CalendarCtrl.prototype.hideVerticalScrollbar = function(childCtrl) {
...
...
var scroller = childCtrl.calendarScroller;
scroller.scrollTop = 0;
...
...
};
```

**Comment by umairfarooq** [comment] 2017-02-25 12:37
I have pulled the master code using bower install angular-material#master --save command but I am experiencing same problem and the datepicker is showing 3 months in future upon opening. 

Can anyone help me in that ?

**Comment by cisvanammel** [comment] 2017-03-02 12:32
This issue still seems to occur if the datepicker is used inside an md-dialog that has a height lower than the height of the datepicker.

**Comment by cisvanammel** [comment] 2017-03-02 15:06
In my application, the issue still occurs when the md-min-date is set. When I use md-date-filter instead of the md-min-date it works.

**Comment by ernsheong** [comment] 2017-03-03 09:59
The issue is still occuring in master branch.

**Comment by lobo-tuerto** [comment] 2017-03-09 22:50
I'm seeing this problem on:

Angular: 1.6.0.
Angular Material: 1.1.1.

**Comment by Yaroslav-Pryadunov** [comment] 2017-03-10 13:40
I'm seeing this problem on:

Angular: 1.6.2.
Angular Material: 1.1.3.

**Comment by mike-fastpay** [comment] 2017-03-10 21:27
Agreed with @Yaroslav-Pryadunov we are experiencing the same on Angular Material 1.1.3 with Angular 1.6.2. We did have Angular Material 1.1.1 and I upgraded to 1.1.3. with the issue still persisting. 

This happens when the min and max dates are set to values greater than a year in both directions. If the min and max are less than a year from the selected date the picker works fine and scrolls to the model's set date on open.

**Comment by felipepalazzo** [comment] 2017-03-13 18:48
I'm seeing this problem on:

Angular: 1.6.1.
Angular Material: 1.1.3.

**Comment by topherfangio** [comment] 2017-03-21 18:05
@ernsheong Can you provide a Codepen against the master branch that reproduces this? Also, what browser/version are you using?

**Comment by lobo-tuerto** [comment] 2017-03-21 18:07
@topherfangio I think you can observe this behaviour in the Angular Material demo: https://material.angularjs.org/latest/demo/datepicker 

Try opening the one that says: "Custom calendar trigger".

**Comment by topherfangio** [comment] 2017-03-21 21:56
@lobo-tuerto: Indeed! Thanks for showing me which one; I hadn't clicked on that one yet :-)

**Comment by ernsheong** [comment] 2017-03-23 13:14
Here's a clue:

If the body scroll is 0, datepicker works just fine:
 
<img width="875" alt="screen shot 2017-03-23 at 9 11 51 pm" src="https://cloud.githubusercontent.com/assets/1343284/24249262/8fc7ca50-100d-11e7-9116-4ea86be4bf31.png">

If body scroll is > certain threshold (itemSize?), datepicker scrolls away from selection:

<img width="865" alt="screen shot 2017-03-23 at 9 12 16 pm" src="https://cloud.githubusercontent.com/assets/1343284/24249294/a7bf4840-100d-11e7-872d-eac3394710c1.png">

**Comment by ekarudianto** [comment] 2017-03-24 03:20
I'm seeing this problem on:

Angular: 1.6.1.
Angular Material: 1.1.1.

**Comment by QiaoyuanMaxDeng** [comment] 2017-03-25 14:37
I'm seeing this problem on:

Angular: 1.6.3.
Angular Material: 1.1.3.

Please help us. Thanks

**Comment by topherfangio** [comment] 2017-03-31 00:38
@ekarudianto @QiaoyuanMaxDeng Can you please test [this PR](https://github.com/angular/material/pull/10537) from @ernsheong to verify that it fixes your problem?

**Closed** 2017-04-21 22:16 UTC
Labels: needs: investigation, P1 - Broken Renders / Major Use Cases

**Comment by DAquilina** [comment] 2017-07-04 18:35
So will this be update be release with 1.1.5?
