### ISSUE TITLE
mdDatepicker date range validation bug

### ISSUE THREAD

**Issue by latata** [angular/material#5546] opened 2015-11-04 15:38 UTC
There is a validation bug in datepicker. Mindate/maxdate errors are not passed to $error field in form/ngModelController object.

**Comment by PawelOwczarekFalcon** [comment] 2015-11-05 15:34
yeah, you have right, I can't validate form properly, i have to do hacks

+1 to fix

**Comment by jelbourn** [comment] 2015-11-05 17:34
Dupe of #4986

**Closed by jelbourn** 2015-11-05 17:34 UTC
