### ISSUE TITLE
md-list feature request : multiple secondary items

### ISSUE THREAD

**Issue by hodeyp** [angular/material#2595] opened 2015-04-28 11:47 UTC
I have a need to display multiple checkboxes per item in an md-list. At present the checkboxes remove the text and align them all to sit on top of each other. Please allow for multiple checkboxes

**Comment by rschmukler** [comment] 2015-05-19 22:52
@ThomasBurleson can you coordinate with the UX team on this? Pseudo-duplicate of part of #2819, specifically the multiple checkboxes in a list item. Would be good to get clarification on UX's stance.

**Comment by hodeyp** [comment] 2015-06-04 18:31
an example of this feature in action using google inbox, I think this would be a super useful feature to add...

![screen shot 2015-06-04 at 19 29 38](https://cloud.githubusercontent.com/assets/1916471/7991470/3b0fff56-0af0-11e5-98e1-918795e9267f.png)

**Comment by miclaus** [comment] 2015-07-28 12:17
+1

**Comment by offminded** [comment] 2015-07-28 14:19
+1

**Comment by JuHwon** [comment] 2015-07-29 11:31
+1

**Comment by AleksueiR** [comment] 2015-08-07 15:16
+1

**Comment by eXaminator** [comment] 2015-08-15 07:29
+1

**Comment by george3447** [comment] 2015-08-22 16:38
+1

**Comment by tiago3613** [comment] 2015-08-23 19:52
+1

**Comment by asm0dey** [comment] 2015-08-24 07:38
:+1:

**Comment by douwevdijk** [comment] 2015-08-25 18:48
+1

**Comment by srikrishnacj** [comment] 2015-08-26 07:18
+1

**Comment by iskuda** [comment] 2015-08-27 09:50
+1

**Comment by colinskow** [comment] 2015-09-05 09:36
+1

**Comment by ThomasBurleson** [comment] 2015-09-05 12:06
We recognize that this enhancement is an important feature improvement. With our push for a v1.0 MVP, this simply must wait until a post 1.0 release. Thank you.

**Comment by miclaus** [comment] 2015-10-14 06:16
In the meantime one could position the buttons right to the list items and style accordingly and maybe use `md-ink-ripple` for more fancy .

**Comment by sisu4u** [comment] 2015-12-03 12:04
+1

**Comment by miclaus** [comment] 2015-12-05 13:13
#5958 seems good, but isn't this solved already ?

**Comment by 8cells** [comment] 2015-12-30 07:47
+1

**Comment by fincha** [comment] 2016-01-18 13:21
+1

**Comment by 7ebra** [comment] 2016-01-26 15:19
+1

**Comment by darkmavis1980** [comment] 2016-01-27 16:44
+1

**Comment by jaggedsoft** [comment] 2016-01-31 01:55
+1

**Closed** 2016-02-01 22:03 UTC
Labels: needs: UX team review

**Comment by timmyrosen** [comment] 2016-02-08 15:02
+1
