### ISSUE TITLE
select: options are always read as "checked" with JAWS

### ISSUE THREAD

**Issue by jelbourn** [angular/material#10969] opened 2017-11-03 17:50 UTC

**Comment by benjiallen** [comment] 2017-12-28 14:07
Adding more detail.

* Component with issue
    - `<md-select>`
* Overview of the Issue
    - Select options are always read as "checked" with JAWS
* AngularJS Material Version
    - 1.1.5
* Browsers and Operating System
    - I can reproduce on Windows 7, IE11, JAWS 17.0.2619
* Reproduce the Error
    - Visit https://material.angularjs.org/latest/demo/select and interact with the select menu with JAWS
* Related Issues
    - #10748

**Comment by Splaktar** [comment] 2018-02-18 07:22
Related to https://github.com/angular/material/issues/10748.

**Comment by Splaktar** [comment] 2019-06-20 08:51
Closing as a duplicate of https://github.com/angular/material/issues/10748.

**Closed by Splaktar** 2019-06-20 08:51 UTC
Labels: P1: urgent, a11y, g3: reported, g3: sync, type: bug
