### ISSUE TITLE
md-virtual-repeat not displaying all data when using a very high number of rows

### ISSUE THREAD

**Issue by Sam-Davis** [angular/material#5206] opened 2015-10-16 12:54 UTC
I was testing the ng-virtual-repeat to display 1 million rows: http://codepen.io/anon/pen/KdyKzP

However, as you can see from the example, only the first 559,000 rows are displayed.

**Comment by Soulcyber** [comment] 2015-10-16 14:28
Nobody in the world will show 1 million rows in an HTML page, there are problems and features more important to implement right now IMO

**Comment by kseamon** [comment] 2015-11-25 16:06
I think the browsers impose some limit on scroll height. My guess is that's the issue as the mathy aspect of it should be fine until we reach 2^53 pixels in height/width.

@jelbourn You ran into some similar problems with the Date Picker. Can you comment on this and close it if you think the problem is not worthwhile and/or not reasonably fixable? Thanks.

**Comment by jelbourn** [comment] 2015-11-25 17:41
Thee is [some code](https://github.com/angular/material/blob/master/src/components/virtualRepeat/virtual-repeater.js#L208) in virtual repeat that is supposed to handle this to an extent already. We should look into this, but I'm marking it as low priority for now.

**Closed** 2016-04-28 20:23 UTC
Labels: priority: low
