### ISSUE TITLE
add floating label to md-select

### ISSUE THREAD

**Issue by hodeyp** [angular/material#1586] opened 2015-02-20 10:06 UTC
When an md-select has a value, the placeholder should be used as a floating label to keep consistent with the md-input directive

**Comment by vapakule** [comment] 2015-02-20 10:38
Regarding to <a href="http://www.google.com/design/spec/components/menus.html#menus-behavior">behavior</a> of this material element, this kind of menus appear above all other in-app elements and floating labels relevant only for input elements. For more understanding look into "Do not" section in component behavior.

**Comment by marcysutton** [comment] 2015-02-20 19:00
Actually I think it should be an option. If you look at the [single-line text fields](https://www.google.com/design/spec/components/text-fields.html#text-fields-single-line-text-field) example in the design spec, there are selects both with and without floating labels. Perhaps an explicit `<md-select-label>` could float, and a placeholder attribute would not?

**Comment by hodeyp** [comment] 2015-02-20 19:05
I'd almost suggest the other way round @marcysutton. If a placeholder is defined within the <md-select> this is the default value displayed when nothing has been selected. the <md-select-label> is used when you want to translate a key/value pair from key to value.

e.g, in a simple <md-select placeholder="Country"> when nothing has been selected the placeholder shows 'Country', when a value has been selected the placeholder floats and the selected value (or <md-select-label>) is displayed in the main content section.

**Comment by vapakule** [comment] 2015-02-20 19:50
It seems to me you're referring to the label to be on top of the selected option,as shown here: <a href="http://www.google.com/design/spec/components/menus.html#menus-simple-menus">Simple menus</a>
But if you need a simple ```<label>``` inside the md-select, try the second example at <a href="https://material.angularjs.org/#/demo/material.components.select">material.angularjs.org</a>:
```<md-optgroup label="Country">```
Otherwise, in floating label case,  this conflicts specification which states - "Do not display a duplicate of the selected menu item"

**Comment by vapakule** [comment] 2015-02-20 20:09
But anyway, you describing different element. As stated in the specification "Menus are positioned over their emitting elements such that the currently selected menu item appears on top of the emitting element. " . And floating label will not be visible until the menu is open. The element you looking for is the label and the predefined option below.

**Comment by hodeyp** [comment] 2015-02-20 20:24
I think we may be talking at cross purposes, so here is an example. Imagine an app where a user is arranging travel and they have to select the departure and arrival countries...

![screenshot](https://cloud.githubusercontent.com/assets/1916471/6308631/b1585db6-b93d-11e4-9881-776a1d7e7bca.png)

Once the countries are both selected it is no longer clear to the user which is the departure and which is th arrival country as the labels (placeholders) are no longer visible...

![screenshot](https://cloud.githubusercontent.com/assets/1916471/6308681/369ccd18-b93e-11e4-91e6-39a4ec698fd0.png)

Once an option has been selected, it would be great for the placeholder to float in the same way as the md-input-container to make it clear to users what the field is they have selected

**Comment by vapakule** [comment] 2015-02-20 20:48
In most cases, these elements have a label or icon on the sides. Or in another case, the input field that indicates the purpose of adjacent elements. The input "New York" represents value in select-box.
![md-select](https://cloud.githubusercontent.com/assets/1689587/6308938/32f435f8-b951-11e4-87b2-e2ce2c8e4ded.png)
Speaking specifically about the material components. For those occasions when we need to show at once the category/type name and value, you must use another element which has a different look, but performs much the same function:
![md-select-combo](https://cloud.githubusercontent.com/assets/1689587/6309099/809c7dc8-b952-11e4-9c1a-21591cec225e.png)

**Comment by sebastiengiroux** [comment] 2015-02-20 23:17
I agree with @marcysutton that it should be an option.  

When used within a form as a <select>, a floating label is necessary so that it looks like other <input> element within the form.

However, when used as a "menu" (e.g.: in a toolbar), a floating label might not be necessary.

**Comment by hodeyp** [comment] 2015-02-21 08:30
@sebastiengiroux - thanks, this is exactly what is needed. To make a form consistent it should be possible to put a floating label on the md-select directive. 

One thing to highlight though with regards to @marcysutton suggestion.

the md-select-label is a great tool to transform the displayed value, I would suggest this is only ever used to display the selected value, transformed as required. The placeholder attribute on the md-select itself it the one to float as this is what describes the content of the select.

**Comment by mtraynham** [comment] 2015-02-21 22:00
+1 Select and it's multiple variant, are common form items.  It would be nice to have the consistent floating label to match inputs and 100% width.  I imagine it could be accomplished by a wrapper div, similar to how the md-input-container interacts with md-input.

**Comment by ask007java** [comment] 2015-02-21 22:28
+1

**Comment by sebastiengiroux** [comment] 2015-02-22 15:30
I agree with @hodeyp that "the md-select-label is a great tool to transform the displayed value".

I think that we could achieve the floating label by wrapping the "md-select" within a "md-input-container" (as mentioned by @mtraynham), and still keep the "md-select-label".

**Comment by Splaktar** [comment] 2015-02-24 15:24
Good discussion here. We certainly need to have our selects in forms with inputs and they should be able to be side-by-side with a similar look.

**Comment by Toilal** [comment] 2015-02-25 15:10
It would be great to also have a way to make an input looking like `md-autocomplete`, with the clear button on the right, but without actually using the auto complete features. Or simply make `md-autocomplete` working when `md-items` is not defined ...

It could be used for example to filter elements in a list, or others features where an input is used outside of an usual form.

**Comment by ask007java** [comment] 2015-02-25 18:46
When is this enhancement getting released? Any idea ?

**Comment by mzbyszynski** [comment] 2015-02-26 16:35
As a temporary workaround to the floating label issue, I was able to get md-select to look similar to an input with a value inside of `md-input-container` using the master branch by adding this css to my application:

```css
md-input-container > md-select {
  flex: 1;
  order: 2;
  margin: 0;
}
```

And adding the `md-input-has-value` class to the `md-input-container`:

```html
<md-input-container class="md-input-has-value">
  <label>Something</label>
  <md-select>...</md-select>
</md-input-container>
```

It doesn't perform the animations when a select has no value and I haven't tried integrating `ng-messages` yet, but this is something anyway.

**Comment by mtraynham** [comment] 2015-02-26 19:00
@mzbyszynski Thanks for alluding to that.  To expand on your temporary workaround, you could probably `ng-class` the `md-input-has-value` which is only enabled when you have a value set.  Maybe something like:

```
<md-input-container ng-class="{'md-input-has-value': foo.bar}">
  <label>Something</label>
  <md-select ng-model="foo.bar">...</md-select>
</md-input-container>
```

I'm under the impression that `md-select` could rely on `md-input-container` as a `required` parent controller, just as `input` and `textarea` do.  The main difference here is the existence of `md-select-label` and if that's actually necessary, compared to using the standard `label`.
https://github.com/angular/material/blob/master/src/components/select/demoBasicUsage/index.html#L15

**Comment by mtraynham** [comment] 2015-02-26 19:48
Also one thing to point out, the animation is probably unnecessary because the menu pop-up will cover the full length of the form field.

I altered @mzbyszynski's solution to get it working.  One unresolved issue, when no value is selected, the `md-input-label` has to have a value to retain height (with an inserted <span>).  I just set the value to empty.

```
// less here
md-input-container {
    // largely copied from md-input
    md-select {
        -webkit-flex: 1;
        -ms-flex: 1;
        flex: 1;
        -webkit-order: 2;
        -ms-flex-order: 2;
        order: 2;
        display: block;
        background: none;
        padding: 11px 2px 1px;
        border-width: 0 0 1px 0;
        line-height: 26px;
        -ms-flex-preferred-size: 26px;
        border-radius: 0;
        margin: 0;
    }
    &.md-input-has-value {
        md-select {
            padding: 0px 2px 1px;
        }
    }
}
```
```
            <md-input-container ng-class="{'md-input-has-value': user.roles && user.roles.length}">
                <label>Roles</label>
                <md-select multiple ng-model="user.roles" placeholder="Roles">
                    <md-select-label>{{ user.roles.length ? user.roles.join(', ') : '' }}</md-select-label>
                    <md-option ng-value="role" ng-repeat="role in roles">{{ role }}</md-option>
                </md-select>
            </md-input-container>
```

**Comment by pvsilvestrin** [comment] 2015-02-28 04:42
@mzbyszynski I am trying the workaround suggested, but the label is under the md-select. Here a plunker  http://plnkr.co/edit/aBdqOHKnbw1tkpcWCusI?p=preview
Could you help me to solve it?

**Comment by leeyeh** [comment] 2015-02-28 10:05
Looking forward to a milestone.

**Comment by mtraynham** [comment] 2015-03-01 03:20
@pvsilvestrin http://plnkr.co/edit/fqEfSUXWuroNAO0UbA5O?p=preview

You forgot to include the stylesheet.  I've made some minor changes:
- Angular 1.3.14
- Angular-Material master
- Added a input field for comparison
- Altered the stylesheet with the suggestions I provided above.

As I mentioned, you need to have the `md-select-label` return empty values so it keeps the height of the span.

**Comment by jadrake75** [comment] 2015-03-01 16:17
I have had issued putting md-selects inside the md-input-containers.  The solution I came up with is a simple directive that I put on the wrapping div of the label/md-select that accomplishes the same thing.... I can share if desired.

**Comment by chenzhenxi** [comment] 2015-03-10 02:42
+1

**Comment by JoeyHoutenbos** [comment] 2015-03-30 14:43
+1

**Comment by demisx** [comment] 2015-04-01 00:21
+1

**Comment by Purpwood** [comment] 2015-04-15 09:34
+1

**Comment by richardlt** [comment] 2015-04-15 15:14
+1

**Comment by 111crb111** [comment] 2015-04-17 12:04
Still not the same as normal input label. Hope somobody working on this  :)

**Comment by TalPasi** [comment] 2015-05-08 14:57
+1

**Comment by wlingke** [comment] 2015-05-09 23:33
+1

**Comment by bopm** [comment] 2015-05-11 14:44
:+1:

**Comment by webley** [comment] 2015-05-18 07:55
+1

**Comment by shprink** [comment] 2015-05-19 15:20
+1

**Comment by gpopovic** [comment] 2015-05-24 17:44
+1

**Comment by trsrm** [comment] 2015-05-25 11:39
+1

**Comment by MagicIndustries** [comment] 2015-05-26 05:29
Is somebody currently working on this? I need it for a project at the moment so I'm looking through the code and trying to see how I can copy the input label functionality across to select, but it would help if there was someone I could chat through the implementation with, then I'd be happy to put a pull request in.

**Comment by rschmukler** [comment] 2015-05-26 16:52
@MagicIndustries I plan on getting it into 0.10.0 but I haven't started it quite yet. The big thing is that I want to depreciate the custom `md-select-label` (see #2684) - the select should always just use the `element.textContent` of the selected option. I then want to make it so that you can use either the `label` attribute or `<label>` element in the md-select to specify the floating label.

ie. a select with a placeholder and a label could look like either of these:

```html
<md-select ng-model="state" placeholder="Not specified" label="Favorite State">
  <md-option>CA</md-option>
  <md-option>NY</md-option>
  <md-option>WI</md-option>
</md-select>
```

```html
<md-select ng-model="state" placeholder="Not specified">
  <label>Favorite State</label>
  <md-option>CA</md-option>
  <md-option>NY</md-option>
  <md-option>WI</md-option>
</md-select>
```

Ultimately they should both compile into a `<label class="md-floating-select-label">`. Let me know if you plan on taking it on and I wont work on it myself, otherwise, that's what I plan on doing :P

**Comment by MagicIndustries** [comment] 2015-05-28 00:17
@rschmukler Thanks very much for that. I figured the md-select-label would need to go. I'll have a play with it and once I figure out exactly how the input component is doing it I'll see if I can carry it across :)

**Comment by NeoRyu777** [comment] 2015-05-28 17:25
@rschmukler @MagicIndustries I also need this for a project - my project has many, many forms involved in it and having the floating label would make it it align well with my other input objects. 

I'm going to be playing with it a bit myself, but due to project constraints I probably won't be finished by the time you are. I'll let you know if I figure it out, but would you mind doing the same?

**Comment by kuhnroyal** [comment] 2015-05-28 23:42
I am currently using this SCSS-workaround to make it work and be well aligned with other form fields:

```css
md-input-container {
  md-select {
    margin-top: 0 !important;
    -webkit-flex: 1;
    -ms-flex: 1;
    flex: 1;
    -webkit-order: 2;
    -ms-flex-order: 2;
    order: 2;
  }
}

md-input-container.md-default-theme .md-input {
 // see https://github.com/angular/material/issues/2914 
  border-style: solid;
}

.md-select-label {
  padding-top: 12px !important;
  height: 30px;
}
```

**Comment by NeoRyu777** [comment] 2015-05-29 02:40
Thanks for the SCSS. I've been experimenting with it myself and while I think I've got it it's good to compare with others who may have thought of more than me. I'll share mine when I return to work tomorrow. 


Robin Hathaway


Sent from Yahoo Mail on Android

**Comment by MagicIndustries** [comment] 2015-05-29 03:17
Lovely, thanks for the scss guys. I'll come back with whatever I end up with.

**Comment by NeoRyu777** [comment] 2015-05-29 16:42
Hey guys. As promised, here's what I'm using:

```SCSS
md-input-container {
    md-select {
        -webkit-flex: 1;
        -ms-flex: 1;
        flex: 1;
        -webkit-order: 2;
        -ms-flex-order: 2;
        order: 2;
        display: block;
        background: none;
        border-width: 0 0 1px 0;
        line-height: 26px;
        -ms-flex-preferred-size: 26px;
        border-radius: 0;
        margin: 0;
        padding-top: 4px;

        md-select-label{
            color: black;
        }
    }
    md-select-label {
        padding-top: 4px;
        font-size: 0.75em;
        color: rgba(0,0,0,0.54);
    }
}
```

And here's what I use in my html page:

```HTML
<md-input-container flex>
    <md-select-label>Foo</md-select-label>
    <md-select ng-model="fooModel">
         <md-option ng-repeat="foo in fooList">{{foo}}</md-option>
    </md-select>
</md-input-container>
```

Seems to be lining up pretty well, and it's got the right colors for the hover text and "selected" text too. I'm aware of course that the eventual intent is to depreciate `<md-select-label>`, but for the moment `<md-input-container>` apparently likes that more than using `<label>` with an `<md-select>` tag. 

Working on wrapping `<md-input-container>` and `<md-select>` into a custom directive, and I'll let you know how it goes. 

I'll happily take any opinions you have - any help at all is appreciated. I'm still fairly new to material design and angular - I've only known of their existence for about a month and a half, and I got thrown into the deep end on this project.

**Comment by MagicIndustries** [comment] 2015-06-03 04:04
@rschmukler Working on this now - to make it work in a similar fashion, I'm not sure whether it's best to just try to fit the label stuff in, or modify md-select so it works more like input. IE change it to be just select so it overrides a normal select and can fall back to normal select if it's not in an md-input-container for example?

Everything else would remain the same, we'd just change the name of the primary directive, and require an md-input-container the same way the input directive does. Then replace the md-select code that handles label and placeholder code with the equivalent from the input directive. 

Does that sound about right? Or should I be aiming for a smaller change?

**Comment by nantunes** [comment] 2015-06-03 11:05
Hi @MagicIndustries 

I followed that approach in a project that needed the feature (not only the floating label but also the md-has-value). So I think that making the select similar to a regular input is the way to go.

You can find my work here: https://github.com/nantunes/material/tree/md-select-has-value

I didn't make pull request because I'm on a deadline on my project, so I didn't have time for cleanup and tests. Maybe you can contribute to that branch, or only have a peek.

**Comment by NeoRyu777** [comment] 2015-06-03 11:59
I concur with this approach as well. I believe it makes the most sense, and makes it fall in line with the input directive, making the material design directives consistent and easy to use.

**Comment by forcewill** [comment] 2015-06-08 09:44
+1

**Comment by MagicIndustries** [comment] 2015-06-09 07:20
Thanks for the input @nantunes, I'd actually forgotten all about the readonly aspect too.

@rschmukler I had it almost working until I realised we're always going to need two labels, because one is still used for display to essentially "fake" the select box. Currently the md-select-label gets it's text changed to the text from the selected option.

So what I'm trying to do now is:
Require md-input-container (working)
Select initially renders with the label in placeholder location
Selection of the select box makes the label transition to the smaller version ala the text input
Deselection of the select box without making a choice makes the label transition back to placeholder ala the text input
Selection of a select menu option leaves the label where it is in the transitioned state, and adds a new label (maybe md-select-label) *inside* the md-select which then makes it look like a normal select with a selected option.

My thinking is it will be easiest to leave the label working as is, and modify the md-select internals to not add a placeholder to begin with if there's no selected option, but once one is selected append an md-select-label within the md-select which then becomes the "placeholder".

Does this make sense? I know you said you wanted to depreciate the md-select-label, so I wanted to check if this makes md-select-label still usable, or if you'd prefer to go with the above approach but make the "inner" placeholder/label a label as well.

Clear as mud? :)

**Comment by chriseyhorn** [comment] 2015-06-10 15:01
Looking forward to this enhancement.

**Comment by Schweigi** [comment] 2015-06-10 21:12
+1 for this enhancement

**Comment by SergeyBukhman** [comment] 2015-06-11 07:30
+1

**Comment by slash13** [comment] 2015-06-11 08:54
+1

**Comment by gpopovic** [comment] 2015-06-15 13:20
+1

**Comment by adrianandreias** [comment] 2015-06-15 15:34
:+1: for consistency with input box label

**Comment by Codicode** [comment] 2015-06-17 11:19
+1

**Comment by MagicIndustries** [comment] 2015-06-17 11:56
There's a pull request in for this now https://github.com/angular/material/pull/3307

**Comment by vasanthB5** [comment] 2015-06-22 11:09
Hi guys. I have one small but severe doubt..
while using 
<md-input-container>
      <md-select placeholder="" ng-model="">
               <md-option value='2'>Conversions</md-option>
                <md-option value='1'>Clicks</md-option>
       </md-select>
</md-input-container>

this works fine...but when i am scrollong and selecting the input it is beig gradually displayed on top and it is changing (the selectable box)...please help me.

**Comment by vasanthB5** [comment] 2015-06-22 12:10
Hi guys. I have one small but severe doubt..
while using 
md-input-container
md-select
md-option x /md-option
md-option x /md-option
/md-select
/md-input-container

this works fine...but when i am scrolling and selecting the input it is being gradually displayed on top and it is changing (the selectable box)...please help me.

**Comment by vasanthB5** [comment] 2015-06-22 12:12
I able to fix it by giving height:auto to the body...but we open the md-select in the browser I am able to scroll. but that should not happen right..when we click on it , it shold not allow srolldown and up ...please help

**Comment by ilianaza** [comment] 2015-06-22 20:52
+1

**Comment by vasanthB5** [comment] 2015-06-23 04:48
I am new what you mean by +1, are you adding this issue?

**Comment by demisx** [comment] 2015-06-23 05:42
@vasanthB5 this means plus one vote to have the issue resolved.

**Comment by NeoRyu777** [comment] 2015-06-23 05:44
I understand it to mean "I too am experiencing this issue and would like it fixed if at all possible"

Sent from Yahoo Mail on Android

**Comment by ilianaza** [comment] 2015-06-24 03:01
@vasanthB5 Yes, +1 to resolve this issue.

**Closed** 2015-06-25 17:13 UTC
Labels: enhancement

**Comment by jmcpeak** [comment] 2015-06-28 18:15
+1

**Comment by rschmukler** [comment] 2015-06-28 19:46
@jmcpeak it's on master!

**Comment by jmcpeak** [comment] 2015-06-29 00:22
Looks great - thanks

**Comment by Z3V0K0D3** [comment] 2015-06-29 00:45
+1

**Comment by vasanthB5** [comment] 2015-06-29 09:40
Hi guys..can you please tell me should I download any thing that rschmukler had done..to check whether its working or not?

**Comment by vasanthB5** [comment] 2015-06-29 09:41
or should go with what he had stated to do..

**Comment by Ugoku** [comment] 2015-06-29 10:09
Download the latest master and try that. Looks great @rschmukler !

**Comment by vasanthB5** [comment] 2015-06-29 10:17
Can I get the complete min.js / min.css so that I can test it on my side..

**Comment by Ugoku** [comment] 2015-06-29 11:35
If you use [Bower](http://bower.io/) to get the package (use "master" as version), it will include the minified JS/CSS.

**Comment by rschmukler** [comment] 2015-06-30 20:41
Bower is indeed the best way to grab the latest. Big ups to @MagicIndustries for all of his work on this! Thanks again.

**Comment by NeoRyu777** [comment] 2015-06-30 21:01
I just installed the master version of angular-material, and I'm having a bit of trouble. 

Previously, the `<md-select>` responded perfectly well to flex, extending the underline all the way across the space allocated by flex. Now it doesn't. What happened? And is there a workaround?

**Comment by ngraef** [comment] 2015-06-30 21:07
@NeoRyu777 that is a separate issue. #3055, #3167 and a couple others

**Comment by NeoRyu777** [comment] 2015-06-30 21:11
@ngraef Thanks, I'll go ahead and put those on my watch list.

**Comment by vasanthB5** [comment] 2015-07-01 12:07
Due to some access restrictions I cannot install node and npm and all....please can anyone tell to get the .min.js/.min.css for this material design updated so that I can just include them and try..:(

**Comment by kuhnroyal** [comment] 2015-07-01 13:30
You can get the latest builds here: https://github.com/angular/bower-material

**Comment by no-more** [comment] 2015-07-02 15:27
Hi,

In the previous version it was possible to define a custom displayed label. That was useful for multiple select options. Because I don't want the text to enlarge, but instead have a label like : 'selection: 2'.

Is there another way to achieve this with the new implementation?

I have also an issue, I can have the select to fill the space of the input-container.

Thanks a lots it's a great job, I really appreciate the new render.

**Comment by Splaktar** [comment] 2015-07-03 00:28
@no-more this issue is closed. You should reference it from a post on the [forums](https://groups.google.com/forum/#!forum/ngmaterial) for your questions. Someone there should be able to help you with this. It would be great if you could also provide a CodePen or Plunker that demonstrates the issue.

**Comment by dholcombe** [comment] 2015-07-15 22:02
I did what @mzbyszynski mentioned on Feb 26. This allows both the code for a select and the rendered page to look very much like a regular input.

**Comment by VaibhavSri198925** [comment] 2015-09-03 07:49
I am also facing this problem how to over come of this problem. I used your techniques but when i applied your code into mine then page collapse with each field

![probelm2](https://cloud.githubusercontent.com/assets/14105828/9653033/4a0e128c-523e-11e5-95c4-ade2a29acd96.png)
![problem](https://cloud.githubusercontent.com/assets/14105828/9653034/4a11eeac-523e-11e5-8f41-f111ea2a524f.png)

**Comment by VaibhavSri198925** [comment] 2015-09-03 07:50
What i have to Pass?
To Solve Out this Problem
