### ISSUE TITLE
list item appending extra flex div

### ISSUE THREAD

**Issue by ccheinemann** [angular/material#8264] opened 2016-04-28 20:03 UTC
Begining with commit [9bb78e06107de7ada8a9251e3100eff747d8329e](https://github.com/angular/material/commit/9bb78e06107de7ada8a9251e3100eff747d8329e#diff-91cb1c9177d2dc2c2ab4b56e20acc043) list item only gets half of the available space due to a <div flex></div> being appended.

I think the key to the use case is a list item is more like a content for the full space available.  The change added another div that effectively takes half the space.

This is how we were using the list item.  
`<md-list-item class="md-3-line" ng-repeat="message in section.messages track by $index">`
`            <div flex layout="column">`
`              <div layout="row" flex >`
`                <div layout="column" layout-align="center start" >`
`                  <h3 >{{message.title}}</h3>`
`                  <div>{{message.formType}}</div>`
`                </div>`
`                <div flex="15" >`
`                  <h2 class="badge">{{message.forms.length}}</h2>`
`                </div>`
`              </div>`
`              <table class='table table-bordered table-hover'>`
`                  <tbody>`
`                      <tr ng-repeat='formentry in message.forms track by $index'>`
`                          <td><a href='{{formentry.url}}'>{{formentry.title}}</a></td>`
`                          <td>{{formentry.author}}<br />{{formentry.created | date}}</td>`
`                          <td ng-class='itemcolor(formentry)'>{{formentry.ageInDays}} Days Out of Compliance</td>                          `
`                      </tr>`
`                  </tbody>`
`              </table>`
`            </div>`
`        </md-list-item>`

**Comment by DevVersion** [comment] 2016-04-28 20:42
Duplicate of #7976

**Closed by DevVersion** 2016-04-28 20:42 UTC
