### ISSUE TITLE
version 0.9.3: goog is not defined

### ISSUE THREAD

**Issue by Windfarer** [angular/material#2859] opened 2015-05-15 04:10 UTC
I updated material by bower, but there's an error in console:
```
Uncaught ReferenceError: goog is not defined
```

**Comment by YogurtShen** [comment] 2015-05-15 06:25
got the same problem
I removed line7~line43
`
goog.provide('ng.ngMaterial');
goog.require('ng.material.components.autocomplete');
goog.require('ng.material.components.backdrop');
goog.require('ng.material.components.bottomSheet');
goog.require('ng.material.components.button');
goog.require('ng.material.components.card');
goog.require('ng.material.components.checkbox');
goog.require('ng.material.components.chips');
goog.require('ng.material.components.content');
goog.require('ng.material.components.dialog');
goog.require('ng.material.components.divider');
goog.require('ng.material.components.gridList');
goog.require('ng.material.components.icon');
goog.require('ng.material.components.input');
goog.require('ng.material.components.list');
goog.require('ng.material.components.progressCircular');
goog.require('ng.material.components.progressLinear');
goog.require('ng.material.components.radioButton');
goog.require('ng.material.components.select');
goog.require('ng.material.components.sidenav');
goog.require('ng.material.components.slider');
goog.require('ng.material.components.sticky');
goog.require('ng.material.components.subheader');
goog.require('ng.material.components.swipe');
goog.require('ng.material.components.switch');
goog.require('ng.material.components.tabs');
goog.require('ng.material.components.toast');
goog.require('ng.material.components.toolbar');
goog.require('ng.material.components.tooltip');
goog.require('ng.material.components.whiteframe');
goog.require('ng.material.core');
goog.require('ng.material.core.gestures');
goog.require('ng.material.core.theming');
goog.require('ng.material.core.theming.palette');
goog.require('ng.ng');
goog.require('ng.ngAnimate');
goog.require('ng.ngAria');
`
and the last line 
`ng.ngMaterial = angular.module("ngMaterial");`

which looks working fine then
Is that correct?

**Comment by yarl** [comment] 2015-05-15 09:09
Duplicate of #2858

**Closed** 2015-05-15 14:10 UTC
