### ISSUE TITLE
Angular materials md-slider aria-valuenow picking up value from max attribute

### ISSUE THREAD

**Issue by ryanki1** [angular/material#4859] opened 2015-09-27 16:53 UTC
Hi 

I'm using the md-slider, version 0.11.0, in angular 1.3.4 to display incoming quote information every 2 seconds for example. It appears that the slider after a variable number of displays eventually reaches a point where the aria-valuenow gets set to the max value of the previous display, rather than the incoming ask_start value. Let me explain further..

Here's the HTML:

```HTML
<md-slider flex="" ng-model="qBox['ask-start']" ng-disabled="true" min="0" max="177" aria-label="ask" id="slider.ask" class="md-slider-ask ng-pristine ng-untouched ng-valid flex ng-isolate-scope md-default-theme" tabindex="0" role="slider" aria-valuemin="0" aria-valuenow="56" aria-valuemax="177" aria-disabled="true" disabled="disabled" aria-invalid="false">
  <div class="md-slider-wrapper">
    <div class="md-track-container">
      <div class="md-track"></div>
      <div class="md-track md-track-fill" style="width: 31.6384%;"></div>
      <div class="md-track-ticks"></div>
    </div>
    <div class="md-thumb-container" style="left: 31.6384%;">
      <div class="md-thumb"></div>
      <div class="md-focus-thumb"></div>
      <div class="md-focus-ring"></div>
      <div class="md-sign"> <span class="md-thumb-text">56</span> </div>
      <div class="md-disabled-thumb"></div>
    </div>
  </div>
</md-slider>
```

Here's the json  that goes with it:
```JSON
{
  "direction": 1,
  "quote-date-time": "18:28:35",
  "price-min": 1.45228,
  "price-min-string": "1.45228",
  "price-max": 1.47,
  "price-max-string": "1.47000",
  "price-range": 177,
  "trading-size-string": 122,
  "ask-price": 1.45959,
  "sell-price": 1.46488,
  **"ask-start": 73,**
  "sell-start": 126,
  "ask": 595.9,
  "ask-string": "595.9",
  "sell": 648.8,
  "sell-string": "648.8",
  "current-spread-string": "52.9"
}
```
Here's the previous raw data that got displayed by the slider:
```JSON
{
  "direction": -1,
  "quote-date-time": "18:28:34",
  "price-min": 1.45525,
  "price-min-string": "1.45525",
  "price-max": 1.46087,
  "price-max-string": "1.46087",
  **"price-range": 56,**
  "trading-size-string": 87,
  "ask-price": 1.45684,
  "sell-price": 1.46068,
  "ask-start": 16,
  "sell-start": 54,
  "ask": 568.4,
  "ask-string": "568.4",
  "sell": 606.8,
  "sell-string": "606.8",
  "current-spread-string": "38.4"
}
```
The price-range attribute is bound to the max attribute of the slider, as here shown using Jade notation:
```JADE
md-slider(flex ng-model="qBox['ask-start']" ng-disabled="true" min="0" max="{{qBox['price-range']}}" aria-label="ask" id="slider.ask" class="md-slider-ask")
```
In the current display price-range or rather 177 is being correctly bound, but as already pointed out the aria-valuenow instead of being 73 is 56, the max value of the previous showing.

Here's the entire controller code that sets up the qBox object prior to binding:
```JAVASCRIPT
function showQuote(data) {
      var date = new Date();
      const quoteZoom = 100000;
      const quotePipsWindow = -4;
      const quotePipsFinder = 10;

      var quote = data.data;
      var time = [date.getHours().toString(), date.getMinutes().toString(), date.getSeconds().toString()];
      var paddedTime = _.map(time,
        function(term) {
          var ret = ('00'.concat(term)).substr(-2);
          return ret;
        });

      var qBox = {};
      $scope.qBox = qBox; // Reset
      qBox.direction = midPriceAvgDirection(quote.price_min, quote.price_max);
      qBox['quote-date-time'] = paddedTime.join(':');
      qBox['price-min'] = quote.price_min;
      qBox['price-min-string'] = qBox['price-min'].toFixed(5);
      qBox['price-max'] = quote.price_max;
      qBox['price-max-string'] = qBox['price-max'].toFixed(5);
      qBox['price-range'] = Math.round(quote.price_max * quoteZoom / quotePipsFinder - quote.price_min * quoteZoom / quotePipsFinder);
      qBox['trading-size-string'] = quote.trading_size; // Seems to be a bug when this is set last - infects slider values
      qBox['ask-price'] = quote.ask_price;
      qBox['sell-price'] = quote.sell_price;
      qBox['ask-start'] = Math.round((quote.ask_price * quoteZoom / quotePipsFinder) - (quote.price_min * quoteZoom / quotePipsFinder));
      qBox['sell-start'] = Math.round((quote.sell_price * quoteZoom / quotePipsFinder) - (quote.price_min * quoteZoom / quotePipsFinder));
      qBox.ask = (qBox['ask-price'] * quoteZoom).toString().substr(quotePipsWindow) / quotePipsFinder;
      qBox['ask-string'] = qBox.ask.toFixed(1);
      qBox.sell = (qBox['sell-price'] * quoteZoom).toString().substr(quotePipsWindow) / quotePipsFinder;
      qBox['sell-string'] = qBox.sell.toFixed(1);
      qBox['current-spread-string'] = (qBox.sell - qBox.ask).toFixed(1);
      console.log(JSON.stringify(qBox));
      $scope.qBox = angular.copy(qBox);
    }
```

**Comment by jelbourn** [comment] 2015-09-28 18:15
Literal dupe of #4860

**Closed by jelbourn** 2015-09-28 18:15 UTC
