### ISSUE TITLE
wrap md-datepicker into a container

### ISSUE THREAD

**Issue by Thomas-P** [angular/material#5310] opened 2015-10-22 10:10 UTC
Hi,

would it be possible to put md-datepicker also in a container, like md-input-container?
If we use ng-messages, the membership would clearly recognizable.

**Comment by Malusia** [comment] 2015-10-26 09:12
+1

**Comment by aguzubiaga** [comment] 2015-10-26 20:39
+1

**Comment by jelbourn** [comment] 2015-11-02 18:30
Dupe of #4233

**Closed by jelbourn** 2015-11-02 18:30 UTC
