### ISSUE TITLE
(md-select) if used in custom md-dialog options pane stays open when dialog is closed

### ISSUE THREAD

**Issue by marshfire** [angular/material#1641] opened 2015-02-24 18:38 UTC
I have a custom dialog using the md-dialog service which contains a md-select element. If I open the options to select something, but do not select, and I click outside the dialog, then the dialog closes and the selection list stays open until I reload the page. 

Select list:

![image](https://cloud.githubusercontent.com/assets/681471/6356153/bcbf8988-bc5b-11e4-8ba9-fa50b6ddb34a.png)

Options remaining:
![image](https://cloud.githubusercontent.com/assets/681471/6356245/5af1c5a8-bc5c-11e4-97e4-b2aa457ea95b.png)

Also, maybe a second bug, when the browser is resized while the options are open, they are not updated to the new position.

**Comment by rschmukler** [comment] 2015-02-24 19:40
Looks like a duplicate of #1577. Are you running off of master or on 0.8.0? If on 0.8.0, it should be resolved with the code in master, which will be published shortly.

**Comment by marshfire** [comment] 2015-02-24 20:11
Yeah, looks to be a dupe. I was reading your commit comments right afetr I issued this ;-) I will recheck with the next release.

**Comment by rschmukler** [comment] 2015-02-25 15:03
Closing as a duplicate. Will make a new issue for resize

**Closed by rschmukler** 2015-02-25 15:03 UTC
