### ISSUE TITLE
Bug in Icon buttons in the official site

### ISSUE THREAD

**Issue by chinnichaitanya** [angular/material#4244] opened 2015-08-19 18:17 UTC
I get this error 
`Uncaught TypeError: Cannot read property 'prop' of null` on clicking any *icon button* in the [official site](https://material.angularjs.org/HEAD/#/demo/material.components.button) in current master branch.

Also, the alignment seems to be gone again. https://github.com/angular/material/issues/4130

**Browser** - Chromium 43.0

Screen shot below
![2015-08-19-234135_1366x768_scrot](https://cloud.githubusercontent.com/assets/6941024/9364885/2ff5cc46-46cc-11e5-8f24-4ec46a048503.png)

**Comment by ThomasBurleson** [comment] 2015-08-19 18:58
@robertmesserle  - Potential **ripple.js** issue in `handleMousedown( )`. Unable to reproduce with local build.

**Comment by Frank3K** [comment] 2015-08-19 19:12
I think the error is at [line 155 of ripple.js (be4311ac7e)](https://github.com/angular/material/blob/be4311ac7e1795a3c7f9b6ea4953aa9e4c3bb501/src/core/services/ripple/ripple.js#L155). `this.container` is undefined there.

**Comment by robertmesserle** [comment] 2015-08-19 19:29
That shouldn’t be an issue anymore as container is a getter now

**Comment by ThomasBurleson** [comment] 2015-08-19 22:38
@Frank3K  - can you confirm this is fixed in the latest snapshot/master codebase ?

**Comment by bradmartin** [comment] 2015-08-20 03:54
Couple of other issues ( #4224 & #4213 ) open related to this specific bug.

**Comment by bradmartin** [comment] 2015-08-20 03:59
* v0.10.1-master-8c71d0c
issue is present, just pulled from bower.  Line 2970 angular-material.js throws the error. container is null.

Line 3017 of angular-material.js - InkRippleCtrl.prototype.createRipple. That's all the time I have tonight to provide some insight. I believe one of the other issues open reports other instances of the ripple not functioning normally.

**Comment by mckenzielong** [comment] 2015-08-20 04:22
This is fixed in master.  https://github.com/angular/material/commit/be4311ac7e1795a3c7f9b6ea4953aa9e4c3bb501 / valueOnUse code fixes it.  

@ThomasBurleson Seems like the docs site hasn't been refreshed in a couple days though... did something break a build process somewhere?  See: https://cdn.gitcdn.xyz/cdn/angular/bower-material/master/angular-material.js

Working plunk: http://plnkr.co/edit/f1ldRIpxWp7vEwEe5zjZ?p=preview

**Comment by Frank3K** [comment] 2015-08-20 11:46
The ripple works for me in the Plunker by @mckenzielong. It indeed seems like the docs site does not use the latest version of material.

**Comment by bradmartin** [comment] 2015-08-20 11:52
Or bower at the time I commented few hours ago

**Comment by ThomasBurleson** [comment] 2015-08-20 13:53
@mckenzielong - The docs https://material.angularjs.org/HEAD/#/ appear to be stale. We are aware of this and how to have this resolved today.

**Comment by bradmartin** [comment] 2015-08-21 15:50
Seems to be fixed, bower pulled the latest commit.

**Comment by robertmesserle** [comment] 2015-08-31 17:38
This is resolved now that the docs site is building again.

**Closed by robertmesserle** 2015-08-31 17:38 UTC
Labels: needs: investigation, ui: ink
