### ISSUE TITLE
md-input clear button

### ISSUE THREAD

**Issue by ismarslomic** [angular/material#2802] opened 2015-05-11 08:35 UTC
I would to have an clear button visible when entering md-input of type search. Button should be displayed to the right and within search field itself

**Comment by marcysutton** [comment] 2015-05-13 18:17
Have you taken a look at mdAutocomplete? @robertmesserle I wonder if the `input` in autocomplete should have `type="search"`.

**Comment by ThomasBurleson** [comment] 2015-05-13 18:22
@marcysutton for `<md-autocomplete>` adding a `type="search"` seems like a good idea.

**Comment by robertmesserle** [comment] 2015-05-13 18:40
Totally agreed.  Will make that change.

**Comment by marcysutton** [comment] 2015-05-13 19:44
Closing as duplicate of https://github.com/angular/material/issues/2699.

**Closed by marcysutton** 2015-05-13 19:44 UTC

**Comment by EdgarArguelles** [comment] 2015-07-09 16:32
I have a directive that could hep

http://plnkr.co/edit/Dje0l1?p=preview

**Comment by cmacdonnacha** [comment] 2016-03-22 14:15
So is the "clear" icon displayed on an input of type search now? Trying to achieve something like this:

![image](https://cloud.githubusercontent.com/assets/9777763/13954386/75ab1c12-f038-11e5-91e8-54a60cdcbd60.png)

**Comment by cmacdonnacha** [comment] 2016-03-30 10:20
I tried using the **autocomplete** component and it does display the "clear" button. However, I want to have "md-input" styling rather than the autocomplete styling without the floating label. I think there should be an attribute added to determine if the clear icon should be displayed for **md-input** components.
