### ISSUE TITLE
bug: when dataset for ng-repeat of md-list-item changes, new elements are rendered before old elements are removed

### ISSUE THREAD

**Issue by HenrikBechmann** [angular/material#2911] opened 2015-05-19 19:02 UTC
When adding and removing items from dataset for ng-repeat of md-list-item (for, say, scrolling), the added items are first rendered, with the removed items still showing, and then a second render occurs to remove the old items. This has the effect of on-screen 'jumping'. This does not occur with grid-tiles, nor with table rows.

You can see this effect here: http://mustertools.net/demos/listdemo/

Select the 'list' format, then push a pagination button at the bottom (hit 'toggle overview' at top to dismiss the prose). observe that list items briefly appear then disappear at the bottom of the list when a pagination button is hit (say next item or next page)

Select 'grid' or 'table' format. then hit a pagination button and observe that the brief echo of the old items does *not* occur.

**Comment by rschmukler** [comment] 2015-05-19 20:43
Thanks for reporting! This looks like a duplicate of [#2906]. Please follow that issue for updates. Closing.

**Closed by rschmukler** 2015-05-19 20:43 UTC
