### ISSUE TITLE
select: dropdown position is wrong in iOS Safari

### ISSUE THREAD

**Issue by pavelsl** [angular/material#11382] opened 2018-07-23 09:44 UTC
## Bug:

# CodePen and steps to reproduce the issue:
#### Detailed Reproduction Steps: 
1. Clear device browser cache and data
2. Open jsbin link
3. Scroll a page down 
4. Open dropdown

### What is the expected behavior?
md-select dropdown in place

### What is the current behavior?
md-select dropdown is not in place

### Which versions of AngularJS, Material, OS, and browsers are affected?

- AngularJS: 1.6.8
- AngularJS Material: 1.10.0
- OS: iOs 11.x
- Browsers: Safari
 
### Is there anything else we should know? Stack Traces, Screenshots, etc.
Some times issue is not reproducible but after clearing cache it present again. It's really not too hard to reproduce.

![img_0081](https://user-images.githubusercontent.com/6347118/43070765-5c6539b8-8e79-11e8-9eab-f7b34852448e.png)
![img_0082](https://user-images.githubusercontent.com/6347118/43073856-b63ce0b2-8e83-11e8-8fdd-c30a0f0448ed.png)

**Comment by pavelsl** [comment] 2018-07-23 10:08
@Splaktar Might this will be interesting for you.

**Comment by pavelsl** [comment] 2018-07-24 13:13
It would be great to have any method to trigger recalculation of md-select dropdown position.

**Comment by codymikol** [comment] 2018-07-26 13:45
This seems to work fine for me on iOS 11.x

![image](https://user-images.githubusercontent.com/13606342/43266096-794006f8-90b8-11e8-9bd7-d9a225235316.png)

**Comment by Splaktar** [comment] 2018-07-30 07:08
@pavelsl Can you please provide the device model? iPhone 5, 8, X, etc.

**Comment by pavelsl** [comment] 2018-07-30 09:23
@Splaktar 
I believe any not the newest device (which is slower than iPad Pro @codymikol's ) as the issue.

I have two iPad's mini.
Exact iOs version of iPad mini #1 is v10.1.1 & iPad mini #2 is v11.3. And the issue is reproducible on both of them. Screenshots are taken on v10.1.1

Can check on old iPad 2 as well which has iOs v9.x
----
I was able to fix this by additional position check which happen with 1-2s delay. But it seems that calculation position logic doesn't work well on these. Not sure because of logic issue, or device mobile safari glitches.

**Comment by Splaktar** [comment] 2018-07-31 00:59
I tested on an iPad Air simulator with iOS 11.4 and I was not able to reproduce these issues. Unfortunately I don't have any iOS devices to test against.

I don't think that testing on an iOS 9 device is worthwhile since we don't suppport iOS 9 at this time. You can find some details about browser support [here](https://material.angularjs.org/HEAD/#browser-support).

If you can test a fix locally and verify that it solves the issue, I would be happy to review the PR.

**Comment by pavelsl** [comment] 2018-07-31 06:56
@Splaktar (comment could be ignored, nothing important here)
I meant i have my own workaround which doesn't fix positioning logic issue (md-select issue or iOS issue) that's not something to be merged. I have wrote standalone directive that checks whether dropdown was placed too far in iOS and fixes it's position if it is.

Have you ever seen bugs which doesn't exist in simulator but exist in real device? I used to fix something i see in simulator when it didn't exist in real device and vice versa, now i only use real devices for testing (real PC for IE tests and real iOS/Android devices, only use dev tools emulation too check breakpoints appearance). 

I understand that it's quite a problem to get all devices with all the versions. But the thing is that something what exist in real device can absent in simulators (whatever iOS or virtual machine with IE).

**Comment by Splaktar** [comment] 2018-08-01 01:58
Yes, I have seen issues that appear in simulators but not real devices and vice versa. That's why I was asking for someone with a real device to come up with a fix for this and verify it on their device.

If someone in the US wanted to send me a device with this issue, I would be happy to work on the fix and then send the device back. However, I won't be able to acquire all of the devices that this project supports in order to fix specific issues.

**Comment by SergioFernandez-Mirada** [comment] 2019-01-25 11:07
Reproduced the same bug in iPhone 6 with iOS 11.3 (Safari browser), iPhone X with iOS 12.0.1 (Safari browser) and iPad Pro with 11.4.1 (safari browser). It only happens using Safari.

It seems like the problem appears when the screen has been scrolled down. When clicking the md-Select, the options dropdown emerges up the screen, non in the right position.

**Comment by pavelsl** [comment] 2019-01-25 12:57
I have fixed it using 1s timeout adjusting position with separate piece of JS which has no access to material context. Just attach your own handler and do fixing of all dropdowns yourself (
Have no idea whether it was fixed or not in newer version neither intention to check :)

**Comment by Splaktar** [comment] 2019-01-25 22:47
I have an iPad now, so I will try to reproduce this on a real device.

Related issue: https://github.com/angular/material/issues/11345

**Comment by SergioFernandez-Mirada** [comment] 2019-01-28 13:46
Thank you @Splaktar , waiting for your answer.

**Comment by xr0master** [comment] 2019-02-10 14:07
+1 have issue in ipad too.
However I have the options on top of viewport all time. Looks like the scroll works but the element position from top doesn't...
"browser": "chrome",
"angular-material": "1.1.12",
"angular": "1.7.6",

**Comment by SergioFernandez-Mirada** [comment] 2019-02-11 11:01
Yes, I said it was only reproduced on Safari because I did not use Chrome or Mozilla on iOS devices. But the bug appears on every browser. Any solution @Splaktar ??

**Comment by xr0master** [comment] 2019-02-11 12:44
BTW: Looks like i got it. The issue I have on ipad and ipad pro too.
If use timeout, it will fix the possition. So issue is that the calculation of position started too fast, and in slow devices (aka tablet) it creates this issue. IMO

`this.$onInit = function $onInit() {
    $timeout(function() {
        $($window).trigger('resize');
    }, 5000);
};`

**Comment by SergioFernandez-Mirada** [comment] 2019-02-11 13:03
I will try your solution. Thanks @xr0master

**Comment by SergioFernandez-Mirada** [comment] 2019-02-14 11:43
It did not work, the **bug remains** in the md-select.

**Comment by lechuckcaptain** [comment] 2019-02-15 23:14
> I have fixed it using 1s timeout adjusting position with separate piece of JS which has no access to material context. Just attach your own handler and do fixing of all dropdowns yourself (
> Have no idea whether it was fixed or not in newer version neither intention to check :)

Would you be so kind to post an example of the workaround?

**Comment by lechuckcaptain** [comment] 2019-02-16 17:39
> > I have fixed it using 1s timeout adjusting position with separate piece of JS which has no access to material context. Just attach your own handler and do fixing of all dropdowns yourself (
> > Have no idea whether it was fixed or not in newer version neither intention to check :)
> 
> @pavelsl, would you be so kind to post an example of the workaround?

I just implemented an example based on @xr0master proposal: [JSBin demo workaround](https://jsbin.com/nosihid/edit?html,output)
Could you be so kind to confirm that the workaround does solve the issue for everyone?

**Comment by xr0master** [comment] 2019-02-17 09:41
just a fix for all application

```js
angular.module('app').run(['$timeout', '$mdDialog', '$mdSelect', '$window'],
    function($timeout, $mdDialog, $mdSelect, $window) {
        function appendResizeForShow(oldFunc) {
            return function() {
                $timeout(function() {
                    $window.dispatchEvent(new Event('resize'));
                }, 500);

                return oldFunc.apply(null, arguments);
            };
        }

        // you need to implement it, if you want. I no need to run this fix for desktop
        if (device !== DESKTOP) {
            $mdDialog.show = appendResizeForShow($mdDialog.show);
            $mdSelect.show = appendResizeForShow($mdSelect.show);
        }
    });

**Comment by lechuckcaptain** [comment] 2019-02-18 14:59
@xr0master the provided piece of code is not working for me. Could you be so kind to provide a working example to check if I'm integrating properly your fix?

**Comment by xr0master** [comment] 2019-02-18 15:37
@lechuckcaptain Yep, a small typo. Fixed. Thanks

**Comment by lechuckcaptain** [comment] 2019-02-18 17:48
@xr0master thank you, I can see some results now. Unfortunately it seems on my side that the workaround doesn't work 100% of the times and the final result is pretty far from what we have on desktop and android browser. Can you confirm it?

@Splaktar please have a look at the following screenshots of the same site (sorry for the blur), just to have a more tangible idea about what is happening. Please let me know if I can help someway on the troubleshooting, or if you have a better idea for the workaround.

On Android (Chrome browser):
<img width="200" alt="android_1" src="https://user-images.githubusercontent.com/341895/52967753-4f0a2580-33ab-11e9-8661-cc223d4dba41.png"> <img width="200" alt="android_2" src="https://user-images.githubusercontent.com/341895/52967752-4f0a2580-33ab-11e9-96ef-24addc1df287.png">

On iOS (Safari browser):
<img width="200" alt="ios_1" src="https://user-images.githubusercontent.com/341895/52967751-4f0a2580-33ab-11e9-8c68-f4d608f59994.png"> <img width="200" alt="ios_2" src="https://user-images.githubusercontent.com/341895/52967750-4f0a2580-33ab-11e9-849f-62be2ed739ab.png">

**Comment by lechuckcaptain** [comment] 2019-02-18 18:09
> @xr0master thank you, I can see some results now. Unfortunately it seems on my side that the workaround doesn't work 100% of the times and the final result is pretty far from what we have on desktop and android browser. Can you confirm it?

I managed to have more consistent results, forcing the viewport to `user-scalable=no`, I hope this can be helpful 😃

**Comment by Splaktar** [comment] 2019-06-06 01:47
OK, I can reproduce this on iPad Safari the second `md-select` that is opened in each demo had the panel detached from the `md-select`.

I [updated the third example](https://output.jsbin.com/tehemen) to AngularJS 1.7.8 and AngularJS Material 1.1.19 and the issue is still reproducible.

**Comment by Splaktar** [comment] 2019-06-06 02:04
I put together a demo of this in the AngularJS Material docs and deployed it for testing (https://angularjsmaterial.dev/demo/select#basic-usage) and I'm not able to reproduce it there. I checked for CodePen demos in this thread, but it seems like all of the reproductions are in JSBin. Is this possibly just an issue with JSBin? Can anyone reproduce the issue on the test docs site (linked above)?

**Comment by Splaktar** [comment] 2019-06-06 04:55
If anyone can provide a reproduction that will work in CodePen and on our docs site, I'll take another look at this after PR https://github.com/angular/material/pull/11739 gets merged.

**Comment by xaun** [comment] 2019-09-27 06:54
@Splaktar Please fix this in 1.1.21 🙏 Causing issues for me on production (angular 1.6.1 md 1.1.20) .. Using @xr0master's fix which SEEMS to be working for now thankfully...

**Comment by Splaktar** [comment] 2019-09-27 11:03
@xaun I'm currently looking for an updated CodePen or GitHub reproduction as I've had problems reproducing this issue (thus I can't debug it).

This is also blocked by a couple major select PRs that need to get in first
- https://github.com/angular/material/pull/11761
- https://github.com/angular/material/pull/11771

**Comment by Splaktar** [comment] 2020-11-15 03:33
This is no longer blocked by other `md-select` PRs. 

That said, the requested demo in CodePen, StackBlitz, or GitHub has not been provided. So this is still looking like a JSBin issue until we have some evidence otherwise.

I'll leave this open for feedback for another week or so. If an updated reproduction isn't available at that time, I'll close this.

**Closed** 2021-06-03 21:25 UTC
Labels: - Lots of Comments, P3: important, needs: demo, needs: feedback, os: iOS
