### ISSUE TITLE
tooltip: position with scrolled content is wrong

### ISSUE THREAD

**Issue by nestorbritez** [angular/material#5430] opened 2015-10-29 14:08 UTC
md-tooltip is not working properly when scrolling or is close to the edge of the page.

![tooltip2](https://cloud.githubusercontent.com/assets/2065058/10820619/e91b9ef2-7e2c-11e5-972d-07f416a38235.gif)
![tooltip1](https://cloud.githubusercontent.com/assets/2065058/10820620/e91ced20-7e2c-11e5-9234-391f151c5209.gif)

**Comment by topherfangio** [comment] 2015-10-29 17:32
Can you please tell us what version you are using and ideally provide a Codepen which demonstrates the issue so that we can debug it?

**Comment by nestorbritez** [comment] 2015-10-30 15:32
@topherfangio You can use the official site to test it

**Comment by ThomasBurleson** [comment] 2015-10-30 16:04
In Tooltip Demo page, scroll the page so the content moves up 15px. Hovers over the **View Source** or the **Edit on CodePen** buttons does NOT set the Tooltip position properly.

**Comment by dohomi** [comment] 2015-10-30 16:54
This might be a duplicate of https://github.com/angular/material/issues/5175 

In all scrolling containers the tooltip are misplaced way much to the top since ```1.0.0-rc1```

**Comment by SanderElias** [comment] 2015-11-03 14:30
Duplicate/varioation of #2791. Closed to concentrate discussion in there

**Closed by SanderElias** 2015-11-03 14:30 UTC
Labels: priority: critical, type: bug, ui: layout
