### ISSUE TITLE
mdToolTip with mdFabSpeedDial : mdVisible not working after hovering the action item

### ISSUE THREAD

**Issue by solomongracio** [angular/material#7962] opened 2016-04-09 08:32 UTC
Hi,

I am trying to implement a speed Dial implementation with tooltips. I want to make all the tooltips of the actions to visible when the speed dial opens. I achieved this with md-visible =true  in tooltip as mentioned in fabSpeedDial demo.

But the problem is once the action item is hovered , tooltip for that item is not visible even when  md-visible attribute is set to true. I found the same problem exist in fabSpeedDial demo also.

**Comment by topherfangio** [comment] 2016-04-11 19:29
I believe this is a duplicate of #7300. If not, please comment and I can reopen.

**Closed by topherfangio** 2016-04-11 19:29 UTC
