### ISSUE TITLE
md-menu Firefox 40, menu not closing when clicking outside of it

### ISSUE THREAD

**Issue by m0g** [angular/material#3438] opened 2015-06-24 11:56 UTC
On the latest angular-material (v0.10), 
the new md-menu doesn't close when clicking outside of the dropdown. 

This issue doesn't happen on Chrome.

**Comment by mukilane** [comment] 2015-06-24 12:27
Duplicate of #3411 
Pls close.

**Comment by rschmukler** [comment] 2015-07-09 16:17
Fixed in master

**Closed by rschmukler** 2015-07-09 16:17 UTC
