### ISSUE TITLE
md-select sometimes not worked

### ISSUE THREAD

**Issue by uxitten** [angular/material#8105] opened 2016-04-19 09:32 UTC
i used md-select but sometimes not worked
and error with this message when click on items

TypeError: Cannot read property '$viewValue' of undefined
TypeError: Cannot read property 'selectedLabels' of undefined

![2](https://cloud.githubusercontent.com/assets/1549069/14634477/5b6b1c52-0637-11e6-9a7f-d8f8a054115b.PNG)

**Comment by uxitten** [comment] 2016-04-19 10:19
i fixed 

change

`require: ["mdOption", "^^mdSelectMenu"],`

to

`require: ["^?mdOption", "^?mdSelectMenu"],`

**Comment by ThomasBurleson** [comment] 2016-04-20 19:26
Closing this issue due to insufficient information. Please resubmit with:

----
Required
----

**Behavior**:
-  What is the issue? * 
-  What is the expected behavior? 

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue :
-  Details: 

**Angular Versions**: *
-  Angular Version: 
-  Angular Material Version: 

**Additional Information**:
-  Browser Type: *
-  Browser Version: *
-  OS: *
-  Stack Traces: 

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

**Closed by ThomasBurleson** 2016-04-20 19:26 UTC
