### ISSUE TITLE
md-autocomplete watch item expression

### ISSUE THREAD

**Issue by andreifloroiu** [angular/material#9624] opened 2016-09-16 09:51 UTC
Hello,

**Intro**:
Have about a month since working with NG and Angular Material. I am familiar with MVVM from previous work. I use md-autocomplete a lot as I find it very elegant for selections. For veterans my issue must be obvious. But, in the spirit of convention and patterns md-autocomplete does not behave the same as other inputs and NG UIs (such as Kendo) hence it was harder to spot.

**About Issue and Model**:
 - I use $scope for binding (e.g. $scope,model), not controller.
 - My models are complex and nested. This is how they come from the backend. md-autocomplete is usually bound to the leaf properties.
 - Models are loaded at the end of the controller factory function using a custom $http service, so as you can imagine, the view loads ahead and the model is not on the $scope until it is retrieved from service. And this is the source of the problem: model is undefined on $scope until it is retrieved and md-autocomplete does not recover from that. All the other controls go on after model is loaded. There is no output on the console, the search works but it doesn't bind anything on the model (doesn't bind selection or search text). 
- Unlike other frameworks I used to work with, I have to admit I didn't put much thought as to what happens behind the scenes in NG or Angular Material, so I might be wrong.

**Workaround**
 - Have an `ng-if="model"` (preferably on the `form` tag) over everything.

**Suggestion**
- Behavior should be that it either works or it doesn't work at all. A console warning/error would be appreciated to let us know. Now I have to correct dozens of views :(

**Angular Versions**: *
 -  `Angular Version:` 1.5.8
 -  `Angular Material Version:` 1.1.1

**Additional Information**:
 -  `Browser Type: *` SRWare Iron (Chromium)
 -  `Browser Version: *` 46.0.2450.0
 -  `OS: *` Windows 10 x64
 -  `Stack Traces:` -no need-

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by DevVersion** [comment] 2016-09-16 20:22
I think this is definitely a reasonable request, need to make sure that we don't increase the watchers unnecessarily- Will take a closer look at this soon.

**Comment by DevVersion** [comment] 2016-09-17 14:14
So I took another look at this issue, and I'm a bit confused about the `ng-model` you mentioned all the time. We don't support the `ng-model` attribute on the autocomplete.

There are two other model-likes supported

- `md-search-text`
- `md-selected-item`

Please provide a demo if possible or share more information and some code snippets.

**Comment by andreifloroiu** [comment] 2016-09-17 14:52
Hello Paul,

I never mentioned ng-model. I use the two directives you mentioned:
- md-search-text
- md-selected-item

The issue I mentioned is occurring when model (which is resolved late) has initial values for autocomplete but they are not shown, nor will autocomplete ever bound to the model, visually it still works but nothing changes behind.

I am away for the weekend.

Cheers,
AF

**Comment by DevVersion** [comment] 2016-09-17 14:59
I see, it's the description which often mentioned the `models` and led me to the `ng-model` theory.

While playing with the autocomplete demos, and trying to reproduce the issue I had no success.

A codepen is greatly appreciated if you have time after the weekend ;)

**Comment by andreifloroiu** [comment] 2016-09-20 11:51
Hi Paul,

You are right, I can't seem to be able to reproduce it on codepen. Could it be because I use ng-routing and templateUrls for each main controller? The problem I have manifests itself only on controllers instantiated by routing and does not appear on subcontrollers (the ones that handle operations on child models), hence the conclusion for which I started this issue - child controllers had an ng-if="childModel" and the workaround I presented fixed the issue for main controllers as well. 

So, I think it may be such an isolated issue that it does not need further follow up. Your decision. I don't have the time to invest in it anymore.

[Here is the codepen which proves nothing, only that md-autocomplete works well with lazy models and their nested properties...](https://codepen.io/andreifloroiu/pen/dppGQW)

Thank you for your help,
AF

**Comment by DevVersion** [comment] 2016-09-22 15:29
It shouldn't relate to `ng-route` or the use of `templateUrl`'s instead.

Hm, As is seems to work on Codepen and I'm was not able to reproduce it in any other way, I'm going to close this issue for now.

We will reopen if there is a demo, which shows that issue :) Thanks.

**Closed by DevVersion** 2016-09-22 15:29 UTC
Labels: needs: more info
