### ISSUE TITLE
Angular Material breaks form ng-submit via enter/go button on iOS

### ISSUE THREAD

**Issue by wlingke** [angular/material#3990] opened 2015-08-02 22:24 UTC
If you have a form with ng-submit, pressing enter on a iOS device (with both chrome and safari), will not trigger the ng-submit function. This works as expected with angularjs alone but with the addition of angular material, it no longer works.

Working (without ngMaterial)
http://embed.plnkr.co/Cs3QTjaN6GdnfL1vOKNl/preview

Not working (with ngMaterial)
http://embed.plnkr.co/F0qVeaIxNnBlLHgVKQ5Z/preview

**Comment by julienpa** [comment] 2015-08-14 17:18
I think I have the same issue when trying to submit a form with Angular (1.4.3) and Angular Material (0.10.1) by pressing enter: the ng-submit is not triggered, whereas it works well when there is a simple `md-button` inside the form

**Comment by mackelito** [comment] 2015-09-30 12:32
+1.. 
Same issue here, using angular 1.4.5, Materials 0.10.1

**Comment by aogut** [comment] 2015-10-26 22:05
+1
it worked for me on 0.11.2 but broke on 1.0

**Comment by jamalx31** [comment] 2015-11-01 13:57
+1

**Comment by tonyawad88** [comment] 2015-11-17 21:29
+1

**Comment by topherfangio** [comment] 2015-11-23 16:33
I definitely see the issue within the Plunkr; however, when I extracted it into a simple HTML file on my own iPad to reproduce, the issue disappears. I am running iOS 9, so perhaps that is part of the difference?

Note that the Plunkr fails on Chrome on desktop as well as iOS.

Can someone double-check my code below and let me know if there is something specific you are doing to reproduce, or if it's only a particular version of iOS, because it appears to be working to me?

_P.S. I've added a comment for testing against master as well to see if it was fixed, but I can't reproduce with either of them loaded._

```html
<!doctype html>
<html>
  <head>
    <script src="http://ajax.googleapis.com/ajax/libs/angularjs/1.3.15/angular.min.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/angularjs/1.3.15/angular-animate.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/angular-material/0.10.0/angular-material.js"></script>
    <!--
    <script src="https://material.angularjs.org/HEAD/angular-material.min.js"></script>
    //-->
  </head>

  <body ng-app="app">
    <div ng-controller="Ctrl">

      <form name="testForm" ng-submit="submit(test)">
        <input type="text" ng-model="test">
        <input type="submit">
      </form>

    </div>

    <script typ="text/javascript">
      angular.module('app', ['ngAnimate'])
      .controller('Ctrl', function Ctrl($scope) {
        $scope.submit = function(value){
          alert(value)
        }
      })
    </script>
  </body>
</html>
```

**Comment by mjaverto** [comment] 2015-11-23 16:56
+1 same problem here:

iOS 9.1 (13B143) on an iPhone 5 (Model A1429)

**Comment by mjaverto** [comment] 2015-11-23 16:57
Also problem in iOS Simulator for iPhone 6, iOS 9.1 (13B137)

**Comment by rjdavis3** [comment] 2015-11-23 17:03
+1 seeing same issue as @mjaverto

**Comment by topherfangio** [comment] 2015-11-23 17:38
@mjaverto @rjdavis3 Can one of you please provide a simple HTML example like above (i.e. not a Codepen/Plunkr) that demonstrates this? As I said, I am unable to reproduce and need a little bit of help seeing exactly what code makes it break.

Thanks!

**Comment by mjaverto** [comment] 2015-11-24 13:17
@topherfangio sure. I know this is a plunkr but just copy the HTML out easily.

http://plnkr.co/edit/miCYIujo5vwNH0PgbJOE?p=preview

**Comment by topherfangio** [comment] 2015-11-24 16:07
Thanks! I can confirm and will look into it.

**Comment by lewiswharf** [comment] 2015-12-30 21:09
It doesn't appear this was fixed in a 1.0 release candidate. I'm experiencing this problem with the latest version, on Windows 10 desktop chrome version 47.0.2526.106 m.

**Comment by topherfangio** [comment] 2015-12-30 22:01
@lewiswharf Indeed, this is still an open issue on our radar.

**Comment by chrishawn** [comment] 2016-01-08 20:29
add type="submit" to your md-button and it worked for me

**Comment by julienpa** [comment] 2016-01-09 17:31
Indeed, with `type="submit"` and the button inside the `<form>` element, it works for me too

**Comment by lewiswharf** [comment] 2016-01-10 01:20
`type="submit"` worked! Seems logical.

**Comment by jfbloom22** [comment] 2016-01-28 14:50
adding ```type="submit"``` did not help me.  iOS 9.2  AngularMaterial 11.2. 


Working (with 1 input):

```        
    <form ng-submit="login()">
          <md-input-container>
            <label>Email</label>
            <input ng-model="user.email" type="email" >
          </md-input-container>
        </form>
```

Not Working:
```
    <form ng-submit="login()">
        <md-input-container>
            <label>Email</label>
            <input ng-model="user.email" type="email" >
        </md-input-container>

        <md-input-container>
          <label>Password</label>
          <input ng-model="user.password" type="password">
        </md-input-container>
      </form>
```

temporary Solution:
```
<input ng-model="user.password" type="password"  ng-keypress="keyPressed($event)">
```
```
    $scope.keyPressed = function(keyEvent) {
      if (keyEvent.keyCode === 13) {
        cordova.plugins.Keyboard.close();
      }
    };
```

**Comment by oh-wo** [comment] 2016-02-03 08:05
+1

**Comment by linslin** [comment] 2016-03-04 16:58
+1

**Comment by reppners** [comment] 2016-03-08 07:52
+1

**Comment by mseemann-imatics** [comment] 2016-03-10 17:51
+1

**Comment by maenthoven** [comment] 2016-03-30 17:42
+1

**Comment by vikasgulati** [comment] 2016-04-01 15:18
`type="submit"` worked for me on Mac OSX (Chrome).

**Comment by rcheuk** [comment] 2016-04-15 17:40
+1

**Comment by cjardmore** [comment] 2016-05-03 15:39
This may help some who are following this thread.  It appears the plunkr provided by @mjaverto has an 'action' property defined, which appears to break the submit functionality wrapped into the ngForm directive.  Around line 21916 of angular.js (I'm looking at v1.5.5).

**Comment by cjardmore** [comment] 2016-05-03 16:51
It appears this issue may be linked to ios keyboard not firing 'submit' event when 'Enter' key is pressed.

Without additional meditation / testing I can't say I can suggest an approach to solving this.

Just in case my comments are not be relevant to all issues here, here's a little about my env / issue.  I'm debugging an Apache Cordova app.  The behavior I'm trying to achieve is for the 'Enter' key on ios keyboard to submit the form regardless of which input field within the form the cursor is focused on.

Running v1.5.5 angular v1.0.7 material, ios 9.3.1, cordova 6.1.1, cordova-plugin-crosswalk-webview 1.6.1

**Comment by cjardmore** [comment] 2016-05-12 13:23
What I've decided I need to do for the time being is provide 2 different "submit" options.  One 'path' is looking for a 'keyup' event if it's an ios device.  The other is falling back to the normal form submit functionality.  As a precaution, I'm excluding ios devices from the normal submit action to prevent double-submit on ios devices in case a future update fixes this behavior.

The above change required me to add an 'ng-click' event to any buttons that were intended to submit the form.  Again, for all possible actions to submit the form I'm detecting the device (via cordova's device plugin, which provides a 'platform' attribute) to ensure that one path is ios devices only, and the other path is everyone else.

NOTE:  For regular web apps the device detection mentioned above may not be as straightforward or reliable.  In Apache Cordova window.device.platform will equal the exact string 'ios', 'android', etc depending on the device the app is running in.

**Comment by ThomasBurleson** [comment] 2016-06-02 13:57
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.

**Closed** 2017-03-13 19:57 UTC
Labels: for: internal contributor, has: Pull Request, needs: investigation, P1 - Broken Renders / Major Use Cases, type: bug, ux: integration
