### ISSUE TITLE
datepicker: ng-model-options timezone option not handled properly

### ISSUE THREAD

**Issue by JohnPlaisted** [angular/material#10971] opened 2017-11-06 23:20 UTC
**Actual Behavior**:
 -  `What is the issue?` 
The text for the date is correct but the date doesn't show up correctly in the Calendar.  For me the date selected in the calendar is one day behind.  I think this would be the case for users with a local time zone east of UTC. (a negative offset)
 -  `What is the expected behavior? `
The dates should match

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` 
https://codepen.io/johnjplaisted/pen/WXGNBX?editors=1111
 -  `Details:`
The text for the date shows 11/15/2017, but the calendar selects 11/14/2017. 
I think this has to do with timezone adjustments.

**AngularJS Versions**: *
 -  `AngularJS Version:` 1.5.5
 -  `AngularJS Material Version:` 1.1.5

**Additional Information**:
 -  `Browser Type:` Firefox, Chrome
 -  `Browser Version:` 56.0.2 , 61.0.3163.100
 -  `OS:` Windows 7
 -  `Stack Traces:`

**Comment by SocVi100** [comment] 2018-01-04 08:47
This bug is almost a year old, it has a bunch of open issues, it has an approved pull request solving it that's been there since last summer AND NOBODY DOES NOTHING TO MERGE IT.
This project (Angular Material) is the most disastrously managed I've ever seen. To whoever rules this, please consider changing your profession, you'll make a lot of people happy.

**Comment by Splaktar** [comment] 2018-01-05 09:11
Thank you for your contribution!

This is a duplicate of https://github.com/angular/material/issues/10598.

**Closed by Splaktar** 2018-01-05 09:11 UTC
Labels: i18n: localization, needs: investigation, P3: important, type: bug, ux: integration
