### ISSUE TITLE
mdSelect: pre-selected values aren't selected

### ISSUE THREAD

**Issue by EladBezalel** [angular/material#5238] opened 2015-10-18 13:03 UTC
When the model is pre selected from the list, the select not showing it, #1699 was about it and it seemd to be fixed back then.

[codepen from HEAD](http://codepen.io/anon/pen/pjdVoE)

**Comment by unturk** [comment] 2015-10-22 09:03
+1 to that.

As far as i understand, the problem is only with objects. String values are pre-selected just fine.

Here is an example; http://codepen.io/anon/pen/qOxOja

**Comment by willramos** [comment] 2015-10-22 16:09
+ 1

**Comment by berkayakdal** [comment] 2015-10-23 07:39
+1

**Comment by jordanskole** [comment] 2015-11-04 17:59
+1

**Comment by rschmukler** [comment] 2015-11-04 18:06
This is a duplicate of #2862 - please see the resolution in there.

**Closed by rschmukler** 2015-11-04 18:06 UTC
Labels: type: bug
