### ISSUE TITLE
ng-message lays over top of input hints

### ISSUE THREAD

**Issue by tverlihay** [angular/material#8207] opened 2016-04-25 20:46 UTC
If I have a hint and then the validation fires I end up with this:

![unnamed](https://cloud.githubusercontent.com/assets/753006/14798352/379de9a8-0b05-11e6-992d-67f3a3a7ac4c.png)

**Comment by ThomasBurleson** [comment] 2016-04-25 22:02
Closing this issue due to insufficient information. Please resubmit with:

----
Required
----

**Behavior**:
-  What is the issue? * 
-  What is the expected behavior? 

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue :
-  Details: 

**Angular Versions**: *
-  Angular Version: 
-  Angular Material Version: 

**Additional Information**:
-  Browser Type: *
-  Browser Version: *
-  OS: *
-  Stack Traces: 

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

**Closed by ThomasBurleson** 2016-04-25 22:02 UTC

**Comment by LuxDie** [comment] 2016-11-01 19:54
This is happening right now at https://material.angularjs.org/latest/demo/input, "Errors Advanced" section, when using the "showing hints" slider.
Chrome v.54, Windows 10

**Comment by tverlihay** [comment] 2016-11-01 19:57
Good catch, I never got around to creating a demo. Would be nice to get a
fix for this but it seems like they've shut down updates to v 1.1.1.
