### ISSUE TITLE
mdTooltip issues in scrolled content

### ISSUE THREAD

**Issue by houmark** [angular/material#5175] opened 2015-10-14 23:41 UTC
With the most recent refactor of mdTooltip from today (nice new animation btw) the tooltips does not appear when we have scrolled content in an mdList. The tooltip moves more and more up as we scroll and after some scroll the tooltips appear above the viewable area.

**Comment by houmark** [comment] 2015-10-15 20:09
If a bug fix has long expectancy, then maybe the refactor where the animation was changed should be reverted until at proper refactor that keeps the basics working can be done? This was working fine before and I would trade the old animation for a working solution any day of the week :) FWIW...

**Comment by dohomi** [comment] 2015-10-29 09:25
+1 I discover this on every scrolled content like ```md-content[md-scroll-y]```. The tooltips are moving up out of sight and not attached to the element any more

**Comment by SanderElias** [comment] 2015-11-03 14:40
Related/duplicate of #2791 Closed to concentrate discussion in there

**Closed by SanderElias** 2015-11-03 14:40 UTC
Labels: priority: critical, type: bug, ui: CSS
