### ISSUE TITLE
md-fab alignment 

### ISSUE THREAD

**Issue by jainshravan123** [angular/material#8074] opened 2016-04-16 08:43 UTC
<img width="112" alt="screen shot 2016-04-16 at 2 09 05 pm" src="https://cloud.githubusercontent.com/assets/6860473/14580002/e5455120-03dc-11e6-90ba-68c3c941bdfe.png">

Hi Guys,

M using following code for designing of a floating action button. Everything is fine except single one. The content inside the button is not appearing in center. The icon is displaying slightly in upper side. I want to show it with in center of this circular button. Please help me to fix this problem.

<md-button class="md-fab md-fab-bottom-right" aria-label="Add" ng-click="showAdd($event)">
       <ng-md-icon icon="add"></ng-md-icon>
 </md-button>

**Comment by DevVersion** [comment] 2016-04-16 09:48
This may be a duplicate of #8066? - @epelc

**Comment by jainshravan123** [comment] 2016-04-16 09:53
Okay.Thank You. I didn't get that link before.

**Comment by jainshravan123** [comment] 2016-04-16 09:56
I have solved it by adding following attribute  
 style="position: absolute;top: 12%;left: 29%;" 
with md-icon

**Comment by DevVersion** [comment] 2016-04-16 10:01
@jainshravan123 Cool, I will close that issue as a duplicate of #8066. If you have anything related to that issue, please write it there.

**Closed by DevVersion** 2016-04-16 10:01 UTC

**Comment by jainshravan123** [comment] 2016-04-16 10:03
No issue buddy. :)
