### ISSUE TITLE
Contact chips not working

### ISSUE THREAD

**Issue by gevorggalstyan** [angular/material#4553] opened 2015-09-10 21:01 UTC
Contact chips stopped showing contact details in the dropdown list. This was working in version 0.10.1 but is broken in version 0.11.0

Image from Angular Material website demo with selected version 0.10.1
![screen shot 2015-09-11 at 00 58 12](https://cloud.githubusercontent.com/assets/2598355/9800845/66cece92-5820-11e5-87ef-5d8a70613bee.png)

Image from Angular Material website demo with selected version 0.11.0
![screen shot 2015-09-11 at 00 57 29](https://cloud.githubusercontent.com/assets/2598355/9800844/66ccbe40-5820-11e5-9699-2c48b3b9c979.png)

**Comment by topherfangio** [comment] 2015-09-10 21:25
Duplicate of #4390. Fix coming soon.

**Closed by topherfangio** 2015-09-10 21:25 UTC
