### ISSUE TITLE
tabs: high cpu usage with certain styles and tab properties applied

### ISSUE THREAD

**Issue by hitigon** [angular/material#9690] opened 2016-09-24 22:16 UTC
**Actual Behavior**:

With applying some certain CSS styles and properties on md-tabs, md-tabs can consume a lot of CPU resources, directly affecting the performance of web apps and browser. 

**CodePen** : 

An example on Codepen, http://codepen.io/anon/pen/WGpJaO
by changing the tabs' box properties (margin) and setting up `md-center-tabs = true`, the application constantly takes 13%~25% CPU.

I figured out that in tabController.js, 

``` js
  if (ctrl.shouldCenterTabs) {
      var tabWidth = calcTabsWidth(elements.tabs);
      if (totalWidth > tabWidth) {
        $mdUtil.nextTick(updateInkBarStyles, false);
      }
    }
```

if the tabs are centered, there is a process queue that is trying to reposition a selected tab by computing the width. In my case, totalWidth > tabWidth always will be true.

If you notice that in my example, i also set md-no-ink and md-no-ink-bar,  `updateInkBarStyles`  seems not take them under consideration.

I understand this might be a rare case, but I don't think it is ideal to allow `updateInkBarStyles` to process continuously. 

**Angular Versions**: *
-  `Angular Version:`1.5.7, 1.5.8
-  `Angular Material Version:`  1.1.0-rc4, 1.1.1

**Additional Information**:
-  `Browser Type: *` Chrome
-  `Browser Version: *` 53
-  `OS: *` OS X
-  `Stack Traces:` N/A

Thanks!

**Comment by vitaly-t** [comment] 2016-09-26 01:04
I'm running the test, and can't see any CPU spike at all, it's quite flat-lined here.

Windows 10, Chrome 53. Could be OS-X specific?

**Comment by hitigon** [comment] 2016-09-26 01:24
@vitaly-t quite interesting, just tested with a Windows 10 box, not much CPU usage. But OS X and Arch (with Chromium 52) are the same, 10% to 15% CPU usage. If I get ride of either center or the styles, everything becomes normal.

**Comment by crisbeto** [comment] 2016-09-26 06:36
mdTabs does a lot of reflows, especially when you're using it with `md-center-tabs`. This used to be a big problem on IE, however @topherfangio managed to minimise it quite a bit. Here's what the timeline looks like in Chrome. Note that the red marks on top are potential performance bottlenecks.

![mdtabs_test_-_google_chrome_2016-09-26_08-35-28](https://cloud.githubusercontent.com/assets/4450522/18824692/f2ef247c-83bb-11e6-8efb-dee96902d152.png)

**Comment by topherfangio** [comment] 2016-09-28 21:40
I'll take a look and see if we can get this in the 1.1.2 release. At the very least, if you have disabled the ink bar, we definitely shouldn't be doing that calculation.

**Comment by Donniewiko** [comment] 2017-04-19 12:52
I can confirm that this issue still exists in version 1.1.3 and angular 1.6.4

I am running Windows 10

**Chrome 57:** CPU spikes to roughly 30%, input and display lag is horrific.
**FireFox 52:** CPU spikes to roughly 30 - 35% input and display lag is almost none existing

My tabs are being rendered inside a mdDialog with these properties:
`<md-tabs md-dynamic-height md-border-bottom>`

**Comment by xr0master** [comment] 2017-05-09 09:03
angular 1.5.8 has the issue too
Browser: Chrome 58
OS: MacOS
If we turn off the md-center-tabs property, then the CPUs load has been reduced from 40% to 0.1%

**Comment by darrensteadman** [comment] 2017-08-11 16:02
I came across the same problem today in IE 11. (angular 1.5.9 material 1.1.4)

If I have the md-center-tabs set then it kills performance and after doing some investigation in IE 11 profiler it would appear it is happening because updateInkBarStyles is continuously called because totalWidth is always greater than tabWidth.

This seems like a bug as I can't see any way that anything in the updateInkBarStyles would ever make totalWidth less than tabWidth unless a window resize occurred in which case the resize should deal with calling updateInkBarStyles.

**Comment by Splaktar** [comment] 2018-07-20 00:42
PR https://github.com/angular/material/pull/11375 has been submitted with the fix for this issue. My apologies for the lengthy delay in resolving this.

**Closed** 2018-07-29 04:30 UTC
Labels: P1: urgent, has: Pull Request, reported by Googler, severity: performance, type: performance
