### ISSUE TITLE
Dialog on IE 11 - Window 7

### ISSUE THREAD

**Issue by truyet** [angular/material#1415] opened 2015-02-06 20:12 UTC
I'm open site https://material.angularjs.org/#/demo/material.components.dialog and click custom dialog.
dialog is show http://s8.postimg.org/uoq0ae66t/dialog.jpg

**Comment by marcysutton** [comment] 2015-03-16 21:12
Closing as duplicate of #1547

**Closed by marcysutton** 2015-03-16 21:12 UTC
