### ISSUE TITLE
Expand card, inbox style

### ISSUE THREAD

**Issue by ehajredini** [angular/material#1138] opened 2015-01-08 13:53 UTC
Is there any possibility to expand card on click like inbox.google.com, for example

**Comment by PaulMougel** [comment] 2015-01-08 14:02
At the moment, unfortunately no.
Duplicate of #1100.

**Comment by EladBezalel** [comment] 2015-01-08 18:12
you can see there my temporary solution.. iv'e changed it a little since then to act a bit different..
I'm sure soon enough this will be included.

**Comment by ehajredini** [comment] 2015-01-09 14:13
@EladBezalel Thank you. I've seen your solution in Plunker. What have you changed  from there ? Did you published the changes anywhere ?

**Comment by EladBezalel** [comment] 2015-01-09 16:07
@ehajredini sure :smile: I'll update my plunker soon.. I'll let you know!

**Comment by EladBezalel** [comment] 2015-01-09 17:37
@ehajredini Updated! you can review [here](http://embed.plnkr.co/NMvyXBL3FYf2b2XsAlz9)

**Comment by ehajredini** [comment] 2015-01-10 21:38
@EladBezalel Thank you!

**Comment by EladBezalel** [comment] 2015-01-10 22:55
Sure :grin:

**Comment by demisx** [comment] 2015-01-11 18:12
@EladBezalel :+1:

**Comment by EladBezalel** [comment] 2015-01-11 19:26
@ehajredini i think you can close this

**Closed** 2015-01-13 10:42 UTC

**Comment by ivks** [comment] 2015-04-15 05:18
@EladBezalel I am not sure if this is the right place to discuss, i apologize in advance for that. Please post a reference to the right place to post such comments.

I really liked your solution, but I can see one missing feature i.e. the active element top offset.
Here is what I am talking about:
1. Open any of the card.
2. Scroll so that the second item is at the top position of the page.
3. Click on second item.
4. The top area scrolls up and is no more visible and only the end part of the current card is visible.
5. Is there anyway we can handle this offset issue.

One more question, why your solution does not make use of the card element anywhere?

**Comment by EladBezalel** [comment] 2015-04-15 08:22
@ivks feel free to discuss this issue where ever you want :) 
I am very happy that you liked my solution! 

The scenario you've talked about is not possible with this kind of implementation. There is no way to achieve this with css only, to create a 'scroll to item' you need to use javascript therefore a directive for this expandable list. 
I have (in a closed network) a directive implementation of this but not with the suggested feature. 
Also this kind of directive is hard to achieve because the multiple parts of the item (header, description, contact etc..) and a complicated transclution need to be done (I used [ng-multi-transclude] (https://github.com/zachsnow/ng-multi-transclude))  
It is possible but I think the angular-material team should lead this or at least start this effort. 

About the card directive, I didn't used it because the current card directive is not suitable for the expandable list because it has padding and card should never be close to one another, so I used more basic directive..

Feel free to ask more if you'd like! Thanks again :)

**Comment by ivks** [comment] 2015-04-16 05:00
@EladBezalel Thank you so much for your detailed explanation. 
whatever I wanted to know has been answered. :+1: 
Thanks again.

**Comment by Bakirelived** [comment] 2016-07-05 17:39
hey, has the @EladBezalel solution been included in any way? Would this work with the card directive?

**Comment by EladBezalel** [comment] 2016-07-05 21:10
@Bakirelived this was never intended to be included in ngMaterial,
This feature is very user specific therefore i'd suggest you to try and implement it by your-self

**Comment by zegerhoogeboom** [comment] 2016-10-17 17:08
@EladBezalel Hey, did you by any chance continue with the example you posted a couple of months ago? 
Specifically I'm using [md-data-table](https://github.com/daniel-nagy/md-data-table) and would like to achieve the _Google Inbox_ effect of having a table row expand into a card. 

Got any tips/examples that could help me on my way?

**Comment by EladBezalel** [comment] 2016-10-17 17:23
Actually yeah, i have it totally reworked with cool animations and auto height but it's on an offline network..

**Comment by zegerhoogeboom** [comment] 2016-10-17 19:34
@EladBezalel  Thanks, by it being on an "offline network" I suppose you mean it's also proprietary? Posting an example could help me and perhaps many more people :). And my requirements are basically everything from Inbox. Like having a list with selectable items, expand on selection and all of that.

If you aren't able to post an example (maybe later) then still thanks for the reply!

**Comment by EladBezalel** [comment] 2016-10-17 19:49
@zegerhoogeboom I'd probably export it at some point, hope it will be sooner than later! :)

**Comment by zegerhoogeboom** [comment] 2016-10-17 19:54
@EladBezalel Cool, `@zegerhoogeboom` me when you do would be great!

**Comment by Bakirelived** [comment] 2016-11-10 12:04
@EladBezalel that export would be great ;) meanwhile I was trying to work based on your plnkr, but I think it's broken...
