### ISSUE TITLE
<md-select> select dropdown not closing When clicked  anywhere on Screen  ? Not User Friendly 

### ISSUE THREAD

**Issue by prasad47** [angular/material#3701] opened 2015-07-13 10:01 UTC
Hi,
Scenario  Follows :-    

Step 1 : Clicked on Md-select for selecting an Option.
Step  2:  Instantly i decided No to Select Anything .
Step 3 : Clicked Some where on the Screen and Looking to Close Select Popup But Not Happening .

Screen Shot Attached from Documentation
![bug](https://cloud.githubusercontent.com/assets/6585745/8647254/fa502296-2973-11e5-95f1-0b0290690028.png)
 . 

Thanks,
Prasad

**Comment by chucre** [comment] 2015-07-14 02:41
I think this is a duplicate issue with #3704

**Comment by prasad47** [comment] 2015-07-14 03:49
The Example worked for the First Time and Same Persists from Next Try

**Comment by rschmukler** [comment] 2015-08-03 20:01
This is fixed on master. Suspect it was a duplicate of #3704

**Closed by rschmukler** 2015-08-03 20:01 UTC
Labels: needs: review

**Comment by Anujndls** [comment] 2017-07-03 09:24
I am also facing this kind of issue, when I open <md-select> with-in $mdDialog its not closing on-click at dialog body
![abc](https://user-images.githubusercontent.com/11572866/27786592-5ed40e12-5fff-11e7-8cca-e571f12b9f17.png)

Please help me to find the solution..
Thanks,
Anuj

**Comment by kalidasweb** [comment] 2017-07-07 12:55
same issue something wrong with the z-index

**Comment by Anujndls** [comment] 2017-07-07 13:00
when I googled then got a solution and finally it works for me with $mdDialog.
```
$window.addEventListener('click',function(e){
 $mdSelect.hide();
})
```
Please inject $window and $mdSelect in your controller..
Thanks

**Comment by izthuca** [comment] 2017-07-13 02:35
@Anujndls , my select box close immediately after clicking it.

**Comment by izthuca** [comment] 2017-07-13 02:52
I solved this using this code:

```
$mdDialog.show({
            clickOutsideToClose: true,
            onRemoving : function () {
                $scope.beforeClose();
            },
            scope: $scope,
            preserveScope: true
});
$scope.beforeClose = function(){
      $mdSelect.hide();
}
```

**Comment by tonyfa** [comment] 2017-11-11 21:49
this works fine for me, on the controller load event

vm.pressedonce = false;
                    document.body.onclick = function (e) {
                        if (vm.pressedonce)
                            $mdSelect.hide();
                        else
                            vm.pressedonce = true;
                    }

**Comment by keplertwofeek** [comment] 2017-11-13 13:12
I think this two styles below could be a quick fix for this issue

```
.md-select-menu-container {
    z-index: 900;
}

md-backdrop.md-select-backdrop {
    z-index: 899;
}
```

**Comment by tonyfa** [comment] 2017-11-13 22:18
Yep sure does thanks, had the first style not the second. Always prefer to get it working using css thank you
