### ISSUE TITLE
md-tooltip won't scroll down with buttons

### ISSUE THREAD

**Issue by butaixianran** [angular/material#2844] opened 2015-05-14 00:12 UTC
Issue with 0.9.0, works fine with 0.8.3

When using ng-repeat on the container of md-button,  the position of md-tooltip won't work fine.

check this codepen:
[http://codepen.io/butaixianran/pen/pJyWMK](http://codepen.io/butaixianran/pen/pJyWMK)

here is a screenshot:

![2015-05-14 7-54-15](https://cloud.githubusercontent.com/assets/5558722/7623731/ddfb8a6e-fa10-11e4-9cee-b371a6c6e046.jpg)

If ng-repeat is only used on md-button, not it's container, then tooltip will be fine. But for my site, I really need to use ng-repeat on the container.

So, how should I fix this? thanks!!

**Comment by shak18** [comment] 2015-05-14 14:46
i can confirm this issue happening with 0.9, event scrolling a little bit makes it noticiable :S

**Comment by marcysutton** [comment] 2015-05-14 23:18
This sounds like a duplicate of #2791 and possibly #2406.

**Comment by butaixianran** [comment] 2015-05-15 07:39
@marcysutton

I've seen these 2 issues before, look like the same issue, but they don't give a online codepen for testing.

And they seem don't need a solution for now, which I really need...

**Comment by r0b-** [comment] 2015-10-30 15:14
+1 (can't give up on scrolling nor tooltips)

**Comment by SanderElias** [comment] 2015-11-03 14:26
Duplicate of #2791, closed to concentrate discussion in there

**Closed by SanderElias** 2015-11-03 14:26 UTC
Labels: priority: critical
