### ISSUE TITLE
mdDialog: escapeToClose: false; Still closes when escape button pressed

### ISSUE THREAD

**Issue by JasperG** [angular/material#7214] opened 2016-02-19 11:38 UTC
In case an mdDialog is shown, with
`escapeToClose: true`
and is then dismissed, any following next mdDialog with
`escapeToClose: false`
can still be closed when pressing the escape button.

Seems like key handler is not being unset.

Expected behaviour is given only in case the very first mdDialog since pageload is opened with `escapeToClose: false`.

**Comment by DevVersion** [comment] 2016-02-19 16:35
Yes can reproduce, here's a little demo which shows that issue. http://codepen.io/DevVersion/pen/JGqBKG?editors=1011

**Comment by JasperG** [comment] 2016-02-19 16:48
@DevVersion Perfect example, that's exactly what I mean.

**Comment by JasperG** [comment] 2016-02-19 16:51
Possible duplicate of issue [#5153](https://github.com/angular/material/issues/5153),

However, that one may have gone unnoticed.

**Comment by DevVersion** [comment] 2016-02-20 13:05
Got it fixed in #7222.

**Closed** 2016-02-26 00:52 UTC
Labels: needs: merge

**Comment by ORESoftware** [comment] 2018-01-29 23:49
dialog seems to fail to close when

```js
this.dialogRef.close();
```
is called. Should I file a new ticket?

**Comment by Splaktar** [comment] 2018-02-11 05:29
@ORESoftware it looks like you might be referring to Angular Material instead of AngularJS Material (this repo). Please submit Angular Material questions [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/material2/issues).
