### ISSUE TITLE
bug: md-tabs handleSelectedIndexChange undefined error when switching tabs  ng 1.4

### ISSUE THREAD

**Issue by rohanrehman** [angular/material#2214] opened 2015-04-08 21:10 UTC
Using the current online tabs documentation 

TypeError: undefined is not a function
    at Object.handleSelectedIndexChange [as fn] (angular-material.js:12776)
    at Scope.$get.Scope.$digest (angular.js:15216)
    at Scope.$get.Scope.$apply (angular.js:15484)
    at HTMLElement.<anonymous> (angular.js:22657)
    at HTMLElement.eventHandler (angular.js:3197)angular.js:11921 (anonymous function)angular.js:8781 $getangular.js:15234 $get.Scope.$digestangular.js:15484 $get.Scope.$applyangular.js:22657 (anonymous function)angular.js:3197 eventHandler

**Comment by mikhail-eremin** [comment] 2015-04-10 13:29
Got same error after updating to last master version

**Comment by robertmesserle** [comment] 2015-04-12 03:06
@mikhail-eremin @rohanrehman I am not able to recreate this issue:

http://codepen.io/robertmesserle/pen/KwYzKv

Can you please create a CodePen or Plunker demo?

**Comment by mikhail-eremin** [comment] 2015-04-13 09:05
I updated to latest version today and can't reproduce bug now. Looks like problem is gone

**Comment by mikhail-eremin** [comment] 2015-04-13 09:25
I updated to v0.8.3-master-9affd12 and now everything works as expected

**Comment by ThomasBurleson** [comment] 2015-04-13 16:55
Closing as not reproducable.

**Closed by ThomasBurleson** 2015-04-13 16:55 UTC
Labels: bug

**Comment by rohanrehman** [comment] 2015-04-14 02:42
Yes bug is gone now.
