### ISSUE TITLE
Codepen link is broken on main site

### ISSUE THREAD

**Issue by DanielFurmanov** [angular/material#10713] opened 2017-06-02 13:38 UTC
Hello, sorry for posting none-code-related issue, but in docs I am not able to "Edit in codepen". It just opens an https://codepen.io/pen/?  link.     Same in Chrome and Firefox.

**Comment by tilhari95** [comment] 2017-06-05 12:30
same here
+1

**Comment by bonatoc** [comment] 2017-06-09 19:16
same here.

**Comment by ThomasBurleson** [comment] 2017-06-13 14:35
Duplicate of #10692

**Closed by ThomasBurleson** 2017-06-13 14:35 UTC
