### ISSUE TITLE
md-select not align properly using layout-align

### ISSUE THREAD

**Issue by Nextt1** [angular/material#7995] opened 2016-04-12 05:09 UTC
`md-select` is used inside `md-inut-container`. 

http://codepen.io/next1/pen/QNQBYr

![md-select-bug](https://cloud.githubusercontent.com/assets/7522749/14450288/b8a1d214-009a-11e6-8863-3d8803db8d65.png)

In default layout-align it works fine. But Since `input` and `md-select` both are used in `md-input-container` they should align in all the cases.

**Comment by pjwalmsley** [comment] 2016-04-13 14:48
+1

**Comment by DevVersion** [comment] 2016-04-24 08:48
This is caused by #6529 - closing this as a duplicate.

**Closed by DevVersion** 2016-04-24 08:48 UTC
