### ISSUE TITLE
md-slider read-only not working!

### ISSUE THREAD

**Issue by hamidyfine** [angular/material#8808] opened 2016-06-20 10:42 UTC
When I add `ng-disabled="true" md-discrete ng-readonly="readonly"` , to the slider, it just disable it but I want to show the value `( _md-sign),` too. But it's not working.

**Comment by DevVersion** [comment] 2016-06-20 15:46
Closing this issue due to insufficient information. Please resubmit with:

----
Required
----

**Behavior**:
-  What is the issue? * 
-  What is the expected behavior? 

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue :
-  Details: 

**Angular Versions**: *
-  Angular Version: 
-  Angular Material Version: 

**Additional Information**:
-  Browser Type: *
-  Browser Version: *
-  OS: *
-  Stack Traces: 

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

**Closed by DevVersion** 2016-06-20 15:46 UTC
