### ISSUE TITLE
Datepicker not displaying correct date in FireFox

### ISSUE THREAD

**Issue by abartolo** [angular/material#9090] opened 2016-07-20 20:37 UTC
**Actual Behavior**:
 -  `What is the issue? *` 
Datepicker now showing current month(scrolled too far down) when opening in FireFox.
 -  `What is the expected behavior?` 
Expected to open on current month/day based on ng-model passed.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`

JS
---
```
history.startDate = new Date();
history.endDate = new Date();
```

HTML
----
```
<label for="history-enddate">End Date</label>
 <md-datepicker ng-model="history.endDate" layout="row" layout-align="center center" md-placeholder="End Date" ng-change="history.onEndDateChange()" md-min-date="history.startDate"></md-datepicker>
```

 -  `Details:`
![capture](https://cloud.githubusercontent.com/assets/5394228/17002140/f8ddf60a-4e97-11e6-8479-768171889e68.JPG)
![capture2](https://cloud.githubusercontent.com/assets/5394228/17002139/f8d8b1f4-4e97-11e6-9e33-5a727c68ddac.JPG)

**Angular Versions**: *
 -  `Angular Version:` 1.5
 -  `Angular Material Version:` ^1.1.0-rc.5

**Additional Information**:
 -  `Browser Type: *` FireFox
 -  `Browser Version: *` 47.0.1
 -  `OS: *` Windows 7
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by crisbeto** [comment] 2016-07-20 20:58
Works fine for me, based on the code you posted. Can you ad a codepen that demonstrates the issue?

**Comment by abartolo** [comment] 2016-07-21 13:25
@crisbeto I got fustrated trying to set up a codepen that I stopped. I'll get it on that soon.

However good things is I found that if I remove
`md-min-date="history.startDate"`

It works fine. So looks to be if both ng-model and md-min-date are the same this is causing the issue.

but after testing there is no correlation with that.. so just when i add md-min-date opening it in FF shows February next year.

Ill work on the codepen now.

**Comment by abartolo** [comment] 2016-07-21 13:43
@crisbeto CodePen below. You can see that when it opens its like 7 months later.. once u remove the min-date it works fine.

Please see that it works fine in Chrome but not FF.

https://codepen.io/anon/pen/xOWpNz

**Comment by crisbeto** [comment] 2016-07-21 13:54
Thank you, this should be much easier to debug.

**Comment by crisbeto** [comment] 2016-07-21 14:01
@abartolo Actually trying it out with the code in master, it seems like the issue got resolved (most likely with #8987). [Can you try this out and confirm whether the issue is still there.](https://codepen.io/crisbeto/pen/grZvLa)

**Comment by abartolo** [comment] 2016-07-21 14:26
@crisbeto Thanks! Looks to be resolved on codepen. Unfortuntly when I change angular material in my project to master.. it breaks almost everything.

I'll have to wait out until after the RC to see the final outcome.

Thanks for the help I appreciate it.

**Comment by crisbeto** [comment] 2016-07-21 15:25
Alright, I'll close the issue, but feel free to ping me here if the issue is still there after the next release.

**Closed by crisbeto** 2016-07-21 15:25 UTC
Labels: needs: feedback, type: bug
