### ISSUE TITLE
mdMenu: menu not closing on firefox 39 and chrome 

### ISSUE THREAD

**Issue by KReden** [angular/material#3773] opened 2015-07-16 19:51 UTC
Reference Issue: https://github.com/angular/material/issues/3438

This was reported as fixed in master several days ago but as of right now on FF and chrome it is broken again. 

When the menu opens it seems to kill all input for the page. A refresh is needed to recover

**Comment by ThomasBurleson** [comment] 2015-07-17 03:51
@KReden - I am unable to reproduce this with the latest code in master:
https://material.angularjs.org/HEAD/#/demo/material.components.menu.

> FF and Chrome both open and close as expected.

**Comment by KReden** [comment] 2015-07-24 16:41
@ThomasBurleson I updated to 0.10.1-rc3 and I am still getting this bug. I thought it might be something on my end interfering with how mdMenu worked but I can get it to happen on the Angular Material website as well. While trouble shooting I noticed that when the bug happens ```md-clickable``` is not applied to the div containing the menu. See screenshots below:

When working: 
![mdmenu_working](https://cloud.githubusercontent.com/assets/1535122/8879694/a27fc764-31f8-11e5-9792-1ffca9fba516.PNG)

When not working: 
![mdmenu_not_working_desktop](https://cloud.githubusercontent.com/assets/1535122/8879702/af2e2186-31f8-11e5-9bd4-96c5396a1ef3.png)

This also applies to android:
![mdmenu_not_working_mobile](https://cloud.githubusercontent.com/assets/1535122/8879711/bc4f42aa-31f8-11e5-9b06-4b7698c7c7a6.png)

**Comment by clshortfuse** [comment] 2015-07-27 16:59
@KReden see https://github.com/angular/material/pull/3899

It fixes the issue but won't be committed since there's a new animation system being written.

**Closed** 2015-08-06 12:01 UTC
Labels: hotlist: angular-issue, hotlist: animations
