### ISSUE TITLE
tooltip: does not work inside fab-toolbar

### ISSUE THREAD

**Issue by fabioda** [angular/material#7380] opened 2016-03-02 19:43 UTC
I'm using fabToolbar to create a collapsable toolbar with few buttons inside.  If I use md-tooltip on buttons inside the toolbar, all the tooltips get shown on the toolbar's trigger, and not on the single buttons.  I made a codepen with the site's sample to demonstrate the weird behaviour.  It actually differs from what I see in my app, since in my case all tooltips are overlapping and showing when hovering on the trigger, while in the codepen some show then the toolbar is collapsed

http://codepen.io/anon/pen/oxXwNE

**Comment by forfuns** [comment] 2016-03-14 09:10
+1

**Comment by aminahmedkhan** [comment] 2016-05-14 11:59
+1

**Comment by rahulchanglani** [comment] 2016-07-01 15:29
+1

**Comment by apocist** [comment] 2016-08-13 20:52
+1

**Comment by arakno76** [comment] 2017-01-24 09:00
+1

**Comment by Rahul-Sagore** [comment] 2017-09-27 06:03
I have a hack to fix this, not ideal solution but works:
[Codepen Demo](https://codepen.io/rahul-sagore/pen/LzbLPN)
[Stackoverflow Answer - step by step fix](https://stackoverflow.com/questions/41826697/how-to-add-md-tooltip-within-md-fab-toolbar-buttons-in-angular-material-design)

**Comment by Splaktar** [comment] 2020-12-21 05:55
I [updated the CodePen](https://codepen.io/Splaktar/pen/jOMLwrJ) to AngularJS Material 1.2.2 and this issue is still there.

![Screen Shot 2020-12-21 at 00 54 45](https://user-images.githubusercontent.com/3506071/102744209-44ae6f00-4327-11eb-9141-fdf7a89619d0.png)

**Comment by Splaktar** [comment] 2020-12-21 06:00
Closing as a duplicate of https://github.com/angular/material/issues/5124.

**Closed by Splaktar** 2020-12-21 06:00 UTC
Labels: P3: important, resolution: duplicate, type: bug
