### ISSUE TITLE
when I click on a datepicker, it shows a date 3 months ahead

### ISSUE THREAD

**Issue by elad2109** [angular/material#10564] opened 2017-04-04 18:46 UTC
**Actual Behavior**:
 -  `What is the issue? *` when I click on a datepicker, it shows a date 3 months ahead. Even if I choose a today as default date. 

 -  `What is the expected behavior?`
I would like the default displayed date will be "today"
even when the model relevant member is nullable.

you can see the bug happens in the official demo page as well

https://material.angularjs.org/latest/demo/datepicker

**Comment by sdesmond** [comment] 2017-04-07 19:49
Looks like a duplicate of #9952 and #10209

**Comment by Splaktar** [comment] 2018-01-11 09:08
Also duplicate of https://github.com/angular/material/issues/10144. Fixed in 1.1.5.

**Closed by Splaktar** 2018-01-11 09:08 UTC
Labels: resolution: duplicate
