### ISSUE TITLE
Percentage flex in nested layout containers

### ISSUE THREAD

**Issue by wallw-bits** [angular/material#6588] opened 2016-01-07 22:31 UTC
Using percentage flex items like flex="30" do not work properly when nested in layout containers. The [Codepen here](http://codepen.io/anon/pen/QyvyMy) shows the problem on the left and the expected heights of the blue and green divs on the right.

**Comment by epelc** [comment] 2016-01-10 01:41
Possibly a duplicate of #5772

**Closed** 2016-06-02 01:55 UTC
Labels: P2 - Planned Work / Team PRs, ui: flexbox

**Comment by ThomasBurleson** [comment] 2016-06-02 13:27
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
