### ISSUE TITLE
ng-messages does not show message

### ISSUE THREAD

**Issue by amitport** [angular/material#6399] opened 2015-12-19 09:06 UTC
reproduce:

1 - open http://codepen.io/topherfangio/pen/eJpoZN
2 - enter input>5 and focus out => error message appears
3 - clear the input and focus out => expected "required" message _does not_ appear

Note that it seems that the message div is there but stuck on animation. Manually removing it's `md-input-message-animation` class in chrome devtools reveals the message.

**Comment by 0101adm** [comment] 2015-12-19 18:01
+1

**Comment by edgaralves** [comment] 2016-01-04 16:30
+1

**Comment by mpiasta-ca** [comment] 2016-01-07 00:01
I just came across this issue too. Thought I was doing something wrong in my project. So then I went to angular-material demo and replicated it: https://material.angularjs.org/latest/demo/input

Scroll to "Errors" section:
# In the "Description" field, enter a really long string like "This is a long string that exceeds the maximum"
# Now select-all and backspace/delete. Then blur from the field.
# The field is underlined in red because it has "required" error. But the required error message is not appearing.

**Comment by FrancescoRizzi** [comment] 2016-01-07 00:11
But in the same demo block ("Errors"), the very next sample field ("Client Name", required) seems to work?
eg:
focus on it
blur out of it
required error appears (as expected)
focus on it
enter any value
required error already disappear (as expected)
you can even blur out and it's fine.

Could the problem be due to the char counter that appears in both the error scenarios (original code pen Test field, and Description field in the "Errors" demo)?

**Comment by mpiasta-ca** [comment] 2016-01-08 02:00
@FrancescoRizzi, the issue appears when there are multiple ng-message error cases for an input field. The "Client Name" field only has a single ng-message error case. The issue happens when one ng-message is removed/hidden, and another ng-message block is supposed to be displayed; but in this case, the subsequent ng-message block is never displayed.

**Comment by Zacharias3690** [comment] 2016-01-11 17:08
+1, occurs for me when going from one invalid state to another. When going from invalid -> valid -> invalid, messages work as expected.

**Comment by Zacharias3690** [comment] 2016-01-22 16:33
I think I found the problem in input.js Line 642

```javascript
function ngMessageAnimation($animateCss) {
  return {
    enter: function(element, done) {
      var messages = getMessagesElement(element);

      // If we have the md-auto-hide class, the md-input-invalid animation will fire, so we can skip
      if (messages.hasClass('md-auto-hide')) {
        done();
        return;
      }

      return showMessage(element, $animateCss);
    },

    leave: function(element, done) {
      return hideMessage(element, $animateCss);
    }
  }
}
```

When removing one class for another it looks like the md-input-invalid animation isn't called. Removing the if statement (ln 642-645) appears to resolve the issue.

**Comment by topherfangio** [comment] 2016-02-05 00:14
Thanks for the comments everyone. We are working to add some tests to ensure that we properly fix this. Will keep everyone updated with our progress.

**Comment by blackdynamo** [comment] 2016-02-18 21:21
+1

Here is a video actually demonstrating the issue: [video](http://screencast.com/t/PbKmgXZP)

**Comment by topherfangio** [comment] 2016-02-22 22:28
Quick update, we are still working on the proper test structure to make sure we fix this and other input issues and don't introduce regressions in the future. Unfortunately, animation tests are a bit tricky. We should have something soon.

**Comment by 0101adm** [comment] 2016-02-22 22:46
:+1:

**Comment by ad0ran** [comment] 2016-03-31 15:36
+1

**Comment by pochenscala** [comment] 2016-05-04 20:46
+1

**Comment by ThomasBurleson** [comment] 2016-06-01 23:59
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Closed** 2016-06-02 01:55 UTC
Labels: - In Progress, P4 - Reported By or General PRs/Errors or Edge Cases, type: bug

**Comment by ThomasBurleson** [comment] 2016-06-02 13:28
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.

**Comment by bobwah** [comment] 2016-07-06 14:43
Getting really really sick of this kind of action

**Comment by EladBezalel** [comment] 2016-07-06 18:25
@bobwah if you want to solve this bug you are more than welcome to suggest a PR.

**Comment by DevVersion** [comment] 2016-07-06 18:26
@bobwah @EladBezalel The fix was quite often submitted. See for example: https://github.com/angular/material/pull/7583

**Comment by topherfangio** [comment] 2016-07-07 20:30
@bobwah I am updating my branch which has some fixes/tests for this exact issue. Please follow #8864 for updates.

**Comment by bobwah** [comment] 2016-07-08 08:59
Thanks @topherfangio I used the links above to patch the version of material we are using though I am sure at some point this will be updated to take a later version of main and i'll have to do the same again :( I am sad what looks like a good fix you have made cannot quickly be tested and released to main.

**Comment by topherfangio** [comment] 2016-07-08 20:20
@bobwah I too wish it was easier to get into master, but if you look at the code, using Karma to do animation tests is very messy. Our only other option is to use Protractor for those, but while they are elegant, making that work on the CI seems to be pretty difficult and we're not sure if we want to do it.

Ultimately, I think we are going to try to get the fixed in 1.1.0 even if we have to strip the tests out since this seems to clean up the code pretty well.

**Comment by bobwah** [comment] 2016-07-27 08:41
had to change the ngMessageAnimation using the following version of material v1.1.0-rc.5-master-7f01138:

`function ngMessageAnimation($animateCss) {
  return {
    enter: function(element, done) {
      var messages = getMessagesElement(element);
      var inputContainer = getInputElement(element);
      var input =  angular.element(inputContainer[0].querySelector('input'));

      if (messages.hasClass('md-auto-hide') && input.hasClass('ng-untouched')) {
        done();
        return;
      }

      return showMessage(element, $animateCss);
    },

    leave: function(element, done) {
      return hideMessage(element, $animateCss);
    }
  }
}`

**Comment by bobwah** [comment] 2016-07-27 08:57
had to change the ngMessageAnimation using the following version of material v1.1.0-rc.5-master-7f01138: 

```
function ngMessageAnimation($animateCss) {
  return {
    enter: function(element, done) {
      var messages = getMessagesElement(element);
      var inputContainer = getInputElement(element);
      var input =  angular.element(inputContainer[0].querySelector('input'));

      if (messages.hasClass('md-auto-hide') && input.hasClass('ng-untouched')) {
        done();
        return;
      }

      return showMessage(element, $animateCss);
    },

    leave: function(element, done) {
      return hideMessage(element, $animateCss);
    }
  }
}
```

**Comment by NateNjuguna** [comment] 2017-03-10 15:42
I've been bugged bu this but turns out there is a siple logic missing in the if block to skip the message animation.
If I am not wrong we should skip only if the `md-auto-hide` class exists on the **ng-messages** element and there is no `md-input-invalid` on the **md-input-container**. Otherwise the *`md-input-invaid`* animation won't handle our new *`enter`* event since no `md-input-container` class is present in the **md-input-container**. Therefore adding this logic (see code below) will rid ng-messages of the bug.
**PS:** I tested this so I that know it works. I'm also a newbie, so there might be a more efficient way to write this but anyone willing to help submit this can.
```function ngMessageAnimation($animateCss) {
  return {
    enter: function(element, done) {
      var messages = getMessagesElement(element);

      // If we have the md-auto-hide class, the md-input-invalid animation will fire, so we can skip
      if (!getInputElement(element).hasClass('md-input-invalid') && messages.hasClass('md-auto-hide')) { // <= Here
        done();
        return;
      }

      return showMessage(element, $animateCss);
    },

    leave: function(element, done) {
      return hideMessage(element, $animateCss);
    }
  }
}```
