### ISSUE TITLE
.flex-# and flex-gt-# not working in Safari 10.0.3 Material Design v1.1.2 - 1.1.3

### ISSUE THREAD

**Issue by bduebel** [angular/material#10391] opened 2017-02-10 19:43 UTC
**Actual Behavior**:
Flex classes with specified widths do not render correctly in Safari 10.0.3. It appears that the mixin "flex-properties-for-name" is not passing integer values to the flex properties any longer.

 -  `What is the issue? *`
The flex property value for the .flex-50 class is set to  "1 1 100%" since Material Design v1.1.2+. Elements with these values are spanning 100% of the width of the page instead of 50% in Safari 10.0.3.

 -  `What is the expected behavior?`
In Material Design v1.1.0, the flex property value for the .flex50 class was set to "1 1 50%". Elements with these values were spanning 50%, which is the expected behavior in Safari 10.0.3.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` N/A
 -  `Details:` ![screen shot 2017-02-10 at 1 23 49 pm](https://cloud.githubusercontent.com/assets/6600820/22841141/065e0cb2-ef96-11e6-84f0-05ab45f913c0.png)

**Angular Versions**: *
 -  `Angular Version:` 1.6.2
 -  `Angular Material Version:` v1.1.3

**Additional Information**:
 -  `Browser Type: *`Safari
 -  `Browser Version: *`10.0.3
 -  `OS: *`macOS Sierra 10.12.3
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by mgol** [comment] 2017-03-07 18:45
I confirm the issue. FWIW, it works fine in WebKit Nightly r213509 so it must be Material not accounting for a Safari issue that's only fixed in Nightly so far.

**Comment by mgol** [comment] 2017-03-07 18:46
This is a duplicate of #10388, though. Can you close this one?

**Closed** 2017-03-18 20:49 UTC
