### ISSUE TITLE
Autocomplete md-autofocus expression

### ISSUE THREAD

**Issue by gpopovic** [angular/material#4073] opened 2015-08-09 11:19 UTC
It would be nice if md-autofocus would be an expression, instead of boolean (example usage: on big screen autofocus autocomplete field, on small screens don't)

Not sure why but i'm unable to get it working by using md-autofocus="{{expression()}}"

**Comment by ThomasBurleson** [comment] 2015-09-02 02:14
Please provide a CodePen or Plunkr that demonstrates this issue. Here are some starter demo templates that you can use/fork:

*  CodePen template: http://codepen.io/team/AngularMaterial/pen/BNYppz
*  Plunkr template: http://plnkr.co/edit/yP0gB9iTacIQb48thud8?p=preview.

**Comment by robertmesserle** [comment] 2015-09-10 17:37
@gpopovic It should work if you remove the `{{}}` surrounding your expression.  The issue is that `md-autofocus` does expect an expression, so you don't need to wrap the expression.

Closing for now, but if that doesn't work, please reply and I will re-open.

**Closed by robertmesserle** 2015-09-10 17:37 UTC
Labels: needs: demo
