### ISSUE TITLE
Long tooltip clipped for last icon in the toolbar

### ISSUE THREAD

**Issue by iBeliever** [angular/material#4043] opened 2015-08-06 00:42 UTC
When I have a long tooltip on the last icon button in the toolbar, it is clipped. It would probably be a good idea to offset tooltips as necessary near the edges of the browser window so they aren't clipped like this.

<img width="663" alt="lelander_app_tester_and_1__python___users_mspencer_developer_lelander_app-tester__python_" src="https://cloud.githubusercontent.com/assets/3230912/9101239/fcce1940-3ba9-11e5-8506-cbc8cfcc27c9.png">

**Comment by WuDo** [comment] 2015-08-16 14:05
Duplicate of #2037

**Comment by topherfangio** [comment] 2015-09-04 17:37
Closing in favor of #4411 .

**Closed by topherfangio** 2015-09-04 17:37 UTC
