### ISSUE TITLE
md-icon issue. unable to load icon

### ISSUE THREAD

**Issue by ashokkumarsand** [angular/material#4910] opened 2015-09-29 15:31 UTC
There is problem regarding icons. material icons. google fonts css are not work

**Comment by jelbourn** [comment] 2015-10-01 00:12
@ashokkumarsand Without more information it is impossible to know what you are talking about.

**Comment by pipegris** [comment] 2015-10-05 16:55
Hi
I've been having some problems regarding md-icon directive.
I'm using https://materialdesignicons.com/ css font, statically it works, but when I bind a variable to the class name: 
<md-icon md-font-icon="mdi-{{iconName}}" class="mdi"></md-icon>

it won't change the icon because the icon name gets appended to the classes, in Chome Dev Tools I could see that class appended remains even after changing md-font-icon attribute, (eg, bellow example was the result of changing from icon 'plus' to icon 'arrow-back')
<md-icon md-font-icon="mdi-plus" class="mdi ng-scope ng-isolate-scope md-default-theme md-font mdi-arrow-back" aria-hidden="true"></md-icon>
It keeps showing the previous icon, so this behavior is not intuitive, I changed my html removing md-font-icon attribute like this:
<md-icon class="mdi mdi-{{iconName}}"></md-icon> and it finally worked as expected.
Not sure if this is a documentation issue, not sure if this is an issue at all, or just my misunderstanding of the directive usage, but it's probably something someone else has stumbled upon.
Thanks for your awesome work.

**Comment by jelbourn** [comment] 2015-10-05 16:58
@pipegris Could you open a new issue with your problem and possible a CodePen (or similar) of what you're trying to do?

**Comment by programmist** [comment] 2015-10-05 18:48
This is a duplicate of #4961.  Work will continue in that bug.

**Closed by programmist** 2015-10-05 18:48 UTC
Labels: type: bug
