### ISSUE TITLE
MD-Menu-Content not closing when md-menu-item clicked

### ISSUE THREAD

**Issue by jrgleason** [angular/material#7950] opened 2016-04-08 15:02 UTC
I had to fix this by adding the following...

    this.close = function(){
                    $timeout(function(){
                        $mdMenu.hide()
                    })
                    
    }
    ...
    md-menu-item(ng-click="ctrl.close()")

Is there an attribute or something we can add to allow for this to cause it to close?

**Comment by topherfangio** [comment] 2016-04-14 20:20
Can you please provide a Codepen which demonstrates what you are trying to do? The [Basic Usage](https://material.angularjs.org/latest/demo/menu) demo doesn't do anything special and all of it's items close the menu on click.

**Comment by ThomasBurleson** [comment] 2016-04-25 22:08
Closing this issue due to insufficient information. Please resubmit with:

----
Required
----

**Behavior**:
-  What is the issue? * 
-  What is the expected behavior? 

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue :
-  Details: 

**Angular Versions**: *
-  Angular Version: 
-  Angular Material Version: 

**Additional Information**:
-  Browser Type: *
-  Browser Version: *
-  OS: *
-  Stack Traces: 

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

**Closed by ThomasBurleson** 2016-04-25 22:08 UTC
Labels: needs: demo
