### ISSUE TITLE
Toolbar: background colors, scrolling ideas, and more...

### ISSUE THREAD

**Issue by ThomasBurleson** [angular/material#4584] opened 2015-09-11 14:04 UTC
-suggest changing the color of the toolbars to a different color than the widget container. so you can see the scroll shrink and the height of the top toolbar.
-would like to see various scrolling techniques with toolbars. https://spec.googleplex.com/quantum/patterns/scrolling-techniques.html#scrolling-techniques-scrolling
- on mobile, the toolbars are not holding up. titles are too long.

![screen shot 2015-09-11 at 9 04 36 am](https://cloud.githubusercontent.com/assets/210413/9816678/2175e936-5864-11e5-80d8-15ceaf18ec7a.png)

**Comment by EladBezalel** [comment] 2015-10-24 12:13
@ThomasBurleson does the link leads to [here](https://www.google.com/design/spec/patterns/scrolling-techniques.html#scrolling-techniques-scrolling) or it's another version?

**Comment by Splaktar** [comment] 2017-11-21 06:45
This issue is closed as it falls in the "won't fix" category for one or more of the following reasons:

The issue is real, but fixing it is risky for users who depend on the existing behavior.
The issue is real, but it only affects a very small use case.
The issue is real, but it would require significant work to fix, and is less urgent than other needs.

> Pull Requests to resolve this issue may be accepted! Note, however, that Pull Requests with large changes or large scope impacts will be rejected due to stability risks to existing users.

**Closed by Splaktar** 2017-11-21 06:45 UTC
Labels: resolution: won't fix, ux: polish
