### ISSUE TITLE
md-tooltip,if md-visible  is true,the tip is not center

### ISSUE THREAD

**Issue by vanntian** [angular/material#2654] opened 2015-05-01 07:42 UTC
![qq 20150501154112](https://cloud.githubusercontent.com/assets/10600430/7427916/973bf296-f018-11e4-9b0d-59ab24657132.png)

**Comment by naomiblack** [comment] 2015-08-14 21:58
@topherfangio can we still repro in 10.0?

**Comment by topherfangio** [comment] 2015-08-15 22:41
@naomiblack I can't seem to reproduce in the default tooltip demo on our site.

@vanntian Can you possibly provide an update and a demo if this is still breaking? You can easily create a CodePen based off of the demo at https://material.angularjs.org/HEAD/#/demo/material.components.tooltip to test it and then post back here.

**Comment by topherfangio** [comment] 2015-11-02 20:57
I am moving this to a later release since there has been no additional info. Please provide a Codepen and we will investigate sooner.

**Comment by SanderElias** [comment] 2015-11-19 12:50
As there is still no demo, and I couldn't reproduce the issue myself, I did put it on the backlog

**Comment by ThomasBurleson** [comment] 2016-04-25 22:24
Closing this issue due to insufficient information. Please resubmit with:

----
Required
----

**Behavior**:
-  What is the issue? * 
-  What is the expected behavior? 

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue :
-  Details: 

**Angular Versions**: *
-  Angular Version: 
-  Angular Material Version: 

**Additional Information**:
-  Browser Type: *
-  Browser Version: *
-  OS: *
-  Stack Traces: 

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

**Closed by ThomasBurleson** 2016-04-25 22:24 UTC
Labels: - In Progress, needs: demo
