### ISSUE TITLE
md-checkbox with ng-disabled allowing select & deselect

### ISSUE THREAD

**Issue by rtprakash** [angular/material#4879] opened 2015-09-28 18:23 UTC
I am using a md-checkbox with ng-click & ng-checked. When i add ng-disabled, even though it looks like disabled it is allowing to select & deselect the check box.

Please refer the codepen.
https://codepen.io/anon/pen/gaLQyK

I just added ng-disabled="true" to the sample given here(md-checkbox with ng-checked)
https://material.angularjs.org/latest/#/demo/material.components.checkbox

**Comment by jelbourn** [comment] 2015-09-30 18:34
The problem is that the checkboxes in the demo are using `ng-click` to do an additional toggle, separate from the internal click handler that toggles the checkbox. You generally want to avoid duplicating the logic that is contained within the components.

However, [the native checkbox does not fire click events when it is disabled](http://jsbin.com/toralo/edit?html,js,output), so `md-checkbox` should do the same. Fixed in #4939

**Closed** 2015-09-30 22:07 UTC
Labels: priority: high

**Comment by rtprakash** [comment] 2015-10-06 13:19
Thanks

**Comment by anilbhat21** [comment] 2016-07-20 20:04
You can still restrict selecting the checkbox while using ng-click by returning false from the ng-click function based on a condition. For example
<md-checkbox ng-disabled="disableCheckboxCondition" ng-checked="checkboxCheckedCondition" ng-click="clickMethod(item)" ></md-checkbox>

clickMethod = function(item){    
    //To Restrict clicking disabled checkboxes
    if(<<some relevant condition >>){
      return false;
    }
};
