### ISSUE TITLE
md-sidenav content wraps/shrinks during open and close animation

### ISSUE THREAD

**Issue by webmandman** [angular/material#8556] opened 2016-05-26 01:21 UTC
**Actual behavior**:
-  What is the issue? * the content inside md-sidenav wraps with the open and close animation of the sidenav. Since the animation is animating the width that means the content wraps. 
-  What is the expected behavior?

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue : http://codepen.io/anon/pen/BzBmWP
-  Details: However, this example the content does not wrap: http://codepen.io/anon/pen/qNWVVr

**Angular Versions**: *
-  Angular Version: latest
-  Angular Material Version: latest

**Additional Information**:
-  Browser Type: * desktop chrome
-  Browser Version: * latest
-  OS: * windows 7 64-bit
-  Stack Traces:

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by DevVersion** [comment] 2016-06-05 14:04
The problem is, that you open the sidenav with the `md-is-locked-open` attribute, which means that the sidenav will become a static position.

You may have to overwrite your layout to disable wrapping.

**Comment by bradrich** [comment] 2016-06-23 01:41
@webmandman One thing that you could consider is making the md-is-locked-open attribute dynamic. Such as `md-is-locked-open="{{isLockedOpen}}"`. Doing this will cause the sidenav animation to perform as expected. I have found success with this.

**Comment by bradrich** [comment] 2016-06-30 17:04
@webmandman Were you able to try the fix that I mentioned above? If so, was it successful? I am closing this issue as it is more implementation than a Material bug.

Let us know if there are any further problems.

**Closed by bradrich** 2016-06-30 17:04 UTC
