### ISSUE TITLE
inconsistent behaviour of md-input-container label element as between input and md-select

### ISSUE THREAD

**Issue by HenrikBechmann** [angular/material#2915] opened 2015-05-19 21:21 UTC
md-input-container puts the label *above* the field for input field, but *below* the field for select field. Should be one or the other (probably above).

See image below. Can be observed at http://mustertools.net/demos/listdemo/

![2015-05-19 05 12 38 pm](https://cloud.githubusercontent.com/assets/4584381/7714277/66d441a8-fe4b-11e4-85e9-7dfb2e3f5b5e.png)

**Comment by rschmukler** [comment] 2015-05-19 22:46
Duplicate of #1586. Closing.

**Closed by rschmukler** 2015-05-19 22:46 UTC
