### ISSUE TITLE
Autocomplete. Selected item stays on top in mobile chrome

### ISSUE THREAD

**Issue by kamarouski** [angular/material#2755] opened 2015-05-06 14:44 UTC
Hi guys,

Thanks for the tremendous work you are doing bringing Angular Material to life.

I have the issue with autocomplete when sometimes selected item stays on top of things and only page refresh makes it go away. It constantly reproduces on chrome for iPad/Android, sometimes on desktop.

I use version 0.9.0

**Comment by Tyrannmisu** [comment] 2015-05-13 11:52
Also happened  to me once in Firefox but I haven't found a way to reproduce it since.

I'm using md-autocomplete in a dialogue and the selected entry stayed on top of the page after the dialogue was closed, only a refresh solved the problem. It happens very rarely and is hard to reproduce (at least for me).

**Comment by robertmesserle** [comment] 2015-06-08 18:23
Can this still be reproduced with the latest code on https://material.angularjs.org/HEAD/ ?

Closing for now since I'm unable to reproduce, but please comment if it is still an issue and I will reopen.

**Closed by robertmesserle** 2015-06-08 18:23 UTC
Labels: ui - mobile

**Comment by kamarouski** [comment] 2015-06-09 11:42
I'm on 0.9.7 now and haven't seen this issue for a while.
