### ISSUE TITLE
theming: controls within a md-theme container cause memory leaks

### ISSUE THREAD

**Issue by mleibman** [angular/material#11325] opened 2018-06-12 23:23 UTC
## Bug:

All themed controls seem to cause memory leaks when placed in a themed container (i.e. with `md-theme` attribute) that doesn't get disposed of, such as a view that sticks around for a while or a part of the app shell.

### Mechanism of the leak:

All themed controls call `$mdTheming(element)`, which in turn calls `inheritTheme()` and registers a change callback on the theming container. This creates a closure that captures the `el` element:

```javascript
var unwatch = ctrl.registerChanges(function (name) {
  updateThemeClass(name);

  if (!watchTheme) {
    unwatch();
  }
  else {
    el.on('$destroy', unwatch);
  }
});
```

Note that the callback never gets unregistered if it never gets called, which is precisely what happens if the theme is not changed or if it is already resolved. They will stick around and keep a reference to the element until that happens or until the theming container is destroyed.

### [Stackblitz Demo](https://stackblitz.com/edit/angularjs-material-themes-memory-leak) which demonstrates the issue: 
https://stackblitz.com/edit/angularjs-material-themes-memory-leak

#### Detailed Reproduction Steps: 
1. Open the demo page.
1. Either click the "Toggle" button a bunch of times or click "Toggle continuously".

### What is the expected behavior?
The icon nodes (<md-icon>) get properly garbage-collected

### What is the current behavior?
The nodes stick around forever.

![screenshot from 2018-06-12 16-06-09](https://user-images.githubusercontent.com/168725/41321827-900d3f5c-6e5a-11e8-9f4c-684dc03da3ef.png)

You can also observe that the `registeredCallbacks` on the theme controller keeps growing:

![screenshot from 2018-06-12 16-22-34](https://user-images.githubusercontent.com/168725/41322249-d7d1a89e-6e5c-11e8-9fef-3591f6d41e22.png)

### What is the use-case or motivation for changing an existing behavior?
Memory leaks are bad :)

### Which versions of AngularJS, Material, OS, and browsers are affected?

- AngularJS: 1.7.2 (haven't tested prior versions)
- AngularJS Material: 1.1.9 (haven't tested prior version)s
- OS: all 
- Browsers: all (tested in Chrome 67.0.3396.79)

**Comment by Splaktar** [comment] 2018-06-14 08:49
I can certainly reproduce this. I [updated the StackBlitz](https://stackblitz.com/edit/angularjs-material-themes-memory-leak-hvb9ye?file=home%2Fhome.controller.js) to slow down and allow canceling the continuous mode. I also fixed the display of the icon.

**Comment by Splaktar** [comment] 2018-06-14 10:12
It looks like the design of this `registerChanges` function is due to supporting the following two use cases: passing a Promise contains the theme or passing a function that returns the theme.
https://github.com/angular/material/blob/master/src/core/services/theming/theming.spec.js#L843-L862

Changing to something like:
```js
        if (watchTheme) {
          var unwatch = ctrl.registerChanges(function(name) {
            updateThemeClass(name);

            el.on('$destroy', unwatch);
          });
        }
```
Fixes the memory leak when `watchTheme` is `false`, but doesn't help if `true`. It also breaks the above two use cases that depend on `registerChanges` to receive theme name later due to the Promise resolving or Function returning the theme.

**Closed** 2018-06-26 14:24 UTC
Labels: P2: required, has: Pull Request, reported by Googler, severity: memory leak, type: bug, ui: theme
