### ISSUE TITLE
Angular Material Autocomplete in v1.0.6 safe encodes HTML, i.e & to &amp;, and then highlights the encoded characters

### ISSUE THREAD

**Issue by adam-s** [angular/material#7690] opened 2016-03-22 06:25 UTC
Using the most basic setup example, the search queries in the Autocomplete have `&` in them. They are being converted to `&amp;` and then on typing 'a' or 'am' the am in `&amp;` is being shown and highlighted. I'm not sure what is going on. I don't think that the input should be santized and then used in the search.

```
<md-autocomplete-parent-scope md-autocomplete-replace="" class="ng-scope">
    <span md-highlight-text="vm.searchText">5017 - NW 72 AV &<span class="highlight">a</span>mp; # 2200</span>
</md-autocomplete-parent-scope>
```
So if I type an 'm', if there is a 'm' before the & which is santitized in the case there isn't a 'm', it renders correctly. However, in the cases where the only 'm' is in `&amp;` it highlights that 'm'. This is so weird. Here is an image with the output so you can see that if the m exists before the & this problem doesn't happen.

![weird-material](https://cloud.githubusercontent.com/assets/232388/13944031/0e8ca218-efd8-11e5-9bd1-babdae280d80.png)

**Comment by topherfangio** [comment] 2016-03-23 21:16
I just tried to reproduce using the Basic Usage autocomplete demo and I could not. Can you please provide a Codepen that shows the issue?

**Comment by adam-s** [comment] 2016-03-23 21:44
I tried to recreate this in codepen but couldn't. 

The project is at [Trolley Tracker Client](https://github.com/adam-s/trolley-tracker-client). The offending code in question is in the [busStops module](https://github.com/adam-s/trolley-tracker-client/blob/master/client/scripts/modules/busStops/busStops.tpl.html). There is an instance running on Heroku at http://trolley-tracker-client.herokuapp.com/bus-stops.

**Comment by topherfangio** [comment] 2016-03-24 17:54
I looked into this a bit and dug into your code, but I'm not seeing the issue. If you can create a demo in the Codepen, we'll definitely take a look, but without having access to something we can debug and modify, it's really hard to track down issues.

**Comment by adam-s** [comment] 2016-03-24 20:22
I can't recreate the problem in Codepen. I had copied the demo Codepen and ended up with the same problem.

![material-buggy](https://cloud.githubusercontent.com/assets/232388/14029512/ee4bf668-f1d8-11e5-9d55-57718d8da4df.png)

The problem is in [highlightController.js](https://github.com/angular/material/blob/master/src/components/autocomplete/js/highlightController.js) the text is being converted to safe html.

`angular.element('<div>').text('10254 - NW 107 AV & NW 14 ST').html()` becomes "10254 - NW 107 AV &amp; NW 14 ST"

This happens on line 19:

`text = angular.element('<div>').text(state.unsafeText).html()`

Then the HTML of the element is set with the safe sanitized code on line 25:

`$element.html(text.replace(regex, '<span class="highlight">$&</span>'));`

I don't know why this is happening in this case. I literally copied the code pen example to use with my data and it didn't work.

**Comment by topherfangio** [comment] 2016-03-25 19:57
@adam-s Thanks for digging in! It looks like this functionality was added in https://github.com/angular/material/commit/1538ebe9c2d8b9aec84d1f556a9b4cfe5a38dc04.

We should see if we can make the sanitization ignore plain ampersands.

**Comment by ThomasBurleson** [comment] 2016-04-28 19:28
This issue is closed as part of our deprecation effort. 
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).

**Closed by ThomasBurleson** 2016-04-28 19:28 UTC
Labels: P4 - Reported By or General PRs/Errors or Edge Cases
