### ISSUE TITLE
CMD+X, CMD+Z shortcuts scroll textarea

### ISSUE THREAD

**Issue by billsaysthis** [angular/material#11058] opened 2018-01-09 18:10 UTC
### Bug, feature request, or proposal:
Bug

### What is the expected behavior?
Visible portion of textarea should remain unchanged after using keyboard shortcuts.

### What is the current behavior?
Visible portion of textarea changes after using keyboard shortcuts. Specifically, if textarea height is greater than visible space (textarea _viewport_) and user presses either of these shortcuts, the textarea viewport is scrolled to the top. Note that the cursor position is correct and if the user presses any key the viewport is correctly reset.

##### Detailed Reproduction Steps: 
* Add a textarea which auto-grows to a form (ours' are inside md-input-containers inside forms). 
* Enter more text than can be visible at one time
* Select some text inside the textarea towards the end of the content (so that the top of the textarea isn't visible)
* Press CMD-X to cut the selected text

### Which versions of AngularJS, Material, OS, and browsers are affected?
We see this on all (recent version) browsers. We use Angular Material 1.1.4

**Comment by Splaktar** [comment] 2018-01-21 08:36
Duplicate of https://github.com/angular/material/issues/3070. Please add any specific details that you have observed to that issue if they are not already captured there.

**Closed by Splaktar** 2018-01-21 08:36 UTC
Labels: resolution: duplicate
