### ISSUE TITLE
md-toast should have position: fixed

### ISSUE THREAD

**Issue by tyler8691** [angular/material#3015] opened 2015-05-28 14:57 UTC
Instead of absolute. If the user scrolls the page while it is displaying, it doesn't stick to the corner it's assigned to.

**Comment by smehrbrodt** [comment] 2015-06-18 09:27
Sounds like a duplicate of #1106

**Comment by ilanbiala** [comment] 2015-07-16 14:35
@tyler8691 @smehrbrodt @ThomasBurleson this is a duplicate.

**Closed** 2015-07-16 23:57 UTC
Labels: resolution: duplicate
