### ISSUE TITLE
md-select in latest master locks the screen

### ISSUE THREAD

**Issue by hodeyp** [angular/material#3704] opened 2015-07-13 11:38 UTC
when something is clicked in an md-select, ice the md-select closes you can no longer click any other element on the screen

**Comment by hodeyp** [comment] 2015-07-13 11:42
note - this is only on md-selects where the name attribute is set via {{}} binding

**Comment by epelc** [comment] 2015-07-13 21:06
I also just ran into this.

Here's a demo as it wasn't showing up on the docs website when I selected master for some reason.

http://codepen.io/anon/pen/XbYjNY

To reliable reproduce it open the dialog close it(click outside of it don't select something) then open again and notice you can't close it or select anything.

**Comment by chucre** [comment] 2015-07-14 02:40
+1 

Chrome Version 43.0.2357.132 (64-bit) under Mac OS 10.10.2 (14C1514)

**Comment by ThomasBurleson** [comment] 2015-07-15 14:29
See @hodeyp comment: https://github.com/angular/material/commit/0ebb9ebfb11632e8caa8170573d9380dd862542a#commitcomment-12172304

**Comment by hodeyp** [comment] 2015-07-15 15:15
Thanks for the fast resolution @ThomasBurleson. Unfortunately it has not fully resolved the issue. I am seeing that if you click a select it works first time. But going back into the same select and trying to select another item shows the select menu but then locks the screen.

**Comment by ThomasBurleson** [comment] 2015-07-15 17:11
@hodeyp - I cannot reproduce this on http://material.angularjs.org/#/demo/material.components.select.

**Comment by epelc** [comment] 2015-07-15 17:32
@ThomasBurleson I couldn't reproduce it directly on material.angularjs.org either. But if you run the demo on codepen then it can be reproduced.

Here's the demo running the latest master and angular 1.4.2

Open the select then click outside of it then open it again and you shouldn't be able to click anything.
http://codepen.io/anon/pen/XbYjNY

**Comment by ThomasBurleson** [comment] 2015-07-15 17:43
@epelc - this is an issue with Angular Material and Angular 1.4.x. If you use Angular 1.3.15, the issue does not manifest.

**Comment by hodeyp** [comment] 2015-07-16 06:05
@ThomasBurleson I concur, I have regressed to 1.3.15 and it seems to be ok. Interestingly 1.3.16 is not ok. So the issue is not specifically 1.4.x related. Looking the changelog for 1.3.16 there is a reference to 'core: ensure that multiple requests to requestAnimationFrame are buffered' - wondering if that is causing issues somewhere?

**Comment by Stexxen** [comment] 2015-07-16 15:30
I've closed, my issue, once I found this.
Here are my codepens with various combinations that I put together if its any help.

Works OK
Angular 1.3.14 and bower-material master
http://codepen.io/Stexxen/pen/qdyEQG

Does not work.
Angular 1.4.3 and bower-material master
http://codepen.io/Stexxen/pen/pJZJRO

Works OK.
Angular 1.4.3 and bower-material 0.10.0
http://codepen.io/Stexxen/pen/jPpPwp

**Comment by ThomasBurleson** [comment] 2015-07-16 17:03
@Stexxen - Thank you. These will be very helpful.

**Comment by ThomasBurleson** [comment] 2015-07-17 23:30
This is a duplicate of https://github.com/angular/material/issues/3780#issuecomment-122344455

**Closed** 2015-07-18 05:22 UTC
Labels: hotlist: angular-issue, hotlist: animations

**Comment by ThomasBurleson** [comment] 2015-07-18 05:38
@epelc - Here is an update demo using Angular 1.4.3 and the latest for bower-material master. The Select menu locking issue appears to be gone/fixed: http://codepen.io/ThomasBurleson/pen/bdjLMv

**Comment by Stexxen** [comment] 2015-07-18 11:58
@ThomasBurleson yes, all confirmed as working. Thanks, S.

**Comment by JDGoldman** [comment] 2015-07-21 14:32
Hi everybody,

On Firefox 39.0, the material.angularjs.org demo site, using material version 0.10.1-rc2, still exhibits this problem (you open the select, and the only way to close it is to chose an item from the select list -- you cannot click anywhere else on the page to close the select).  It appears the site is using AngularJS version 1.3.15.
