### ISSUE TITLE
<md-button> ng-click fires inconsistently with Ionic Framework/ng-Material latest versions

### ISSUE THREAD

**Issue by bradmartin** [angular/material#1406] opened 2015-02-05 22:09 UTC
http://codepen.io/anon/pen/MYOeap

The plunker above works fine, I found this on the Ionic Framework forums and it's functional and the click is fired as expected.

However the same code with the latest ionic css/js files along with latest Angular Material via bower install, the click doesn't work as intended.  Any reason? I've also installed the #master but the clicks on md-button still don't work very well.  It may fire once every 10-20 clicks, and sometimes it fires once every 5 clicks. This is a hangup for me right now on moving forward with a project.

**Comment by mikkokam** [comment] 2015-02-06 09:59
Note: ng-click is broken on *touch devices* and Chrome emulation of such. Chrome desktop is unaffected. The Codepen above: works fine using 0.6.1 or 0.7.0 -- broken on *0.7.1*.
I suspect it might be because of the hammer.js change on 0.7.1 - Ionic has a similar built-in version of hammer as well...

**Comment by drastick** [comment] 2015-02-20 18:10
I'm having issues with this as well.

**Comment by marcysutton** [comment] 2015-02-20 18:41
Can you verify whether this issue still exists in 0.8.0-rc1? Hammer.js was removed in 0.7.1 in favor of $mdGestures, so it's very likely because of that.

**Comment by bradmartin** [comment] 2015-02-20 18:46
@marcysutton Yes it still exists.

**Comment by stellasoft-will** [comment] 2015-02-21 15:49
this is an issue for me as well @marcysutton

**Comment by mikkokam** [comment] 2015-02-21 19:27
http://forum.ionicframework.com/t/is-there-a-tutorial-for-using-ionic-and-angular-material/14662/14

**Comment by iaaguilera** [comment] 2015-02-25 01:40
I am at a loss with this bug as well. Is there a version that has the autocomplete before hammer was removed?

**Comment by bradmartin** [comment] 2015-02-25 01:44
No, autocomplete wasnt implemented until after hammer was removed.

**Comment by jeffthompson1971** [comment] 2015-02-26 01:47
Is there an ETA for a fix or do I just rip it revert to an older version for the near future?

**Comment by bradmartin** [comment] 2015-02-26 04:49
@jeffthompson1971 - @ThomasBurleson  added it to the 0.9.0 milestone over a week ago, so just keep checking for updates.

**Comment by jeffthompson1971** [comment] 2015-02-28 19:52
Anyone?  is this going to be fixed?   I need to know what the plan is?   do i need to drop angular-material and move to something where clicks work on mobile devices?

**Comment by bradmartin** [comment] 2015-02-28 20:04
Its on the 0.9.0 milestone so they're planning on it but no official word
yet.

**Comment by ThomasBurleson** [comment] 2015-02-28 20:56
@ajoslin - Can you help us investigate and resolve this issue ?

**Comment by nglehien** [comment] 2015-03-04 09:36
tested in 0.8.3 and it s working now ! Thanks !

**Comment by drastick** [comment] 2015-03-04 13:58
This is still happening for me in 0.8.3

**Comment by bradmartin** [comment] 2015-03-04 15:46
@nglehien it's not working with v0.8.3-master-c9aae9b . What is your configuration? Did you test it on the mobile emulator or a device? From my testing it will work fine in a standard web browser but on mobile emulators and devices it does not function normally.

**Comment by SILVERjl** [comment] 2015-03-14 21:39
Any updates?  The latest here was 10 days ago.  This seems like a critical bug to me :)

**Comment by bradmartin** [comment] 2015-03-17 15:25
I haven't tested it but someone on the Ionic forums said using the rawgit refs it's working.  Can anyone confirm this?  http://forum.ionicframework.com/t/is-there-a-tutorial-for-using-ionic-and-angular-material/14662/20?u=bradmartin 

I'll try to test it later today.

**Comment by rlucian** [comment] 2015-03-18 08:25
@bradmartin it was me. and it used to work, but not anymore. that's a risk when using rawgit I guess, code keeps changing (or I jumped too fast to the conclusion).
However, as @mikkokam noted up in the thread, we now have it working and quite stable on 0.7.0. It has some minor drawbacks, but we will stay on it until it (hopefully) gets fixed in 0.9.0
We had some issues at first with the app showing only a blank screen after the splashscreen when running it on an Android device, but it seems my team figured it out last night, so if you go this way and run into the same issue let me know and I'll post more details.

**Comment by bradmartin** [comment] 2015-03-18 12:11
Yea im stuck on 0.7.0 also. I have a slight issue after the splash screen
but its not a blank screen, the actual app page flashes, then the login
page appears. I have the ionic.platformready() configured correctly as it
worked prior to using ng-material so if you want to share what youve done
it might be similar. Thanks.

**Comment by rlucian** [comment] 2015-03-18 14:01
@bradmartin for us it was a trivial issue, we were including the libraries by using //cdn/ url refferals, once we used web normalized 'http://cdn" addressing it was all ok.
Are you using a call to a modal for the login, or a controller? It may not be directly related to material, or just expected behavior.

**Comment by bradmartin** [comment] 2015-03-18 14:25
You're prob right. I just have to retrace my steps :/

**Comment by bradmartin** [comment] 2015-03-20 03:33
The current master has improved the use of <md-button> ng-click events within the Chrome mobile emulator (don't have a charged device right now to test). 
 
       <section layout="row" layout-align="center center">
                        <md-button nav-clear flex ng-click="Login()" class="md-raised md-primary">Login</md-button>
                    </section>
                    <br />
                    <br />
                    <br />
                    <p flex layout="row" layout-align="center center">
                        Don't have an account?
                    </p>
                    <section layout="row" layout-align="center center">
                        <md-button class="primary" flex md-no-ink href="#/register">Sign Up</md-button>
                    </section>
                    <br />
                    <br />
                    <br />
                    <div layout="row" layout-align="center center">
                        <md-button flex md-no-ink href="#/forgotpassword">Forgot password?</md-button>
                    </div>

In the markup above, the LOGIN button is working fine, just not the <md-button> with as anchors.

**Comment by stellasoft-will** [comment] 2015-04-13 14:55
any more information on this?

**Comment by bradmartin** [comment] 2015-04-13 14:57
If you search through the issues you will see a few other related issues to gestures and events. I think they are all planned for the 0.9.0 release.

**Comment by bradmartin** [comment] 2015-04-13 18:07
Just tried out the master version : v0.8.3-master-1cd1d69

<md-button> fires click events properly, however not when used with href property.
 
In the snippet below the Login <md-button> works, the SIGN UP and Forgot Password <md-buttons> do not. Was the href property dropped from support on <md-button>? I think in the demos in previous versions this was acceptable but I could be mistaken.
          
        <ion-view title="" hide-nav-bar="true">
            <ion-content>
                
                
                
                <md-content class="md-padding">
                    <div layout="row">
                        <h1 flex class="logo cursive">Truckers Only</h1>
                    </div>
                    <div layout="row">
                        <h4 flex class="motto">Connecting people on the move.</h4>
                    </div>
                    <form name="loginform" layout="row" layout-sm="column" novalidate>
                        <md-input-container flex>
                            <label>Username or Email</label>
                            <input ng-model="user.username" type="text">
                        </md-input-container>
                        <md-input-container flex>
                            <label>Password</label>
                            <input ng-model="user.password" type="password">
                        </md-input-container>
                    </form>
                    <section layout="row" layout-align="center center">
                        <md-button nav-clear flex ng-click="Login()" class="md-raised md-primary">Login</md-button>
                    </section>
                    <br />
                    <br />
                    <br />
                    <p flex layout="row" layout-align="center center">
                        Don't have an account?
                    </p>
                    <section layout="row" layout-align="center center">
                        <md-button class="primary" flex md-no-ink href="#/register">Sign Up</md-button>
                    </section>
                    <br />
                    <br />
                    <br />
                    <div layout="row" layout-align="center center">
                        <md-button flex md-no-ink href="#/forgotpassword">Forgot password?</md-button>
                    </div>
                </md-content>
            </ion-content>
        </ion-view>

**Comment by ThomasBurleson** [comment] 2015-04-13 18:27
For Ionic-Angular Material mobile solutions that using jQuery, you can now disable Material click hijacking by using $mdGestureProvider in 
```js
   app = angular.module('MyApp', ['ngMaterial'])
      .config(function( $mdGestureProvider ) {
          $mdGestureProvider.skipClickHijack();
      });
```
This will configure $mdGesture to **not** intercept clicks (stop propagation and prevent defaults).

**Comment by bradmartin** [comment] 2015-04-13 18:43
Works perfectly for my case. Thanks!

**Comment by sebmaniac** [comment] 2015-05-12 18:05
I tried using this and my Ionic Cordova App fails because Angular is throwing me an error:

```javascript
Uncaught ReferenceError: jQuery is not defined 
```

I had to do some code changes to make it work without an error.

Before:


```javascript
    var self = {
      handler: addHandler,
      register: register,
      // On mobile w/out jQuery, we normally intercept clicks. Should we skip that?
      isHijackingClicks: (isIos || isAndroid) && !JQuery && !forceSkipClickHijack
    };
```

After:

```javascript
var hasJQuery =  typeof jQuery !== 'undefined' && angular.element === jQuery;

    var self = {
      handler: addHandler,
      register: register,
      // On mobile w/out jQuery, we normally intercept clicks. Should we skip that?
      isHijackingClicks: (isIos || isAndroid) && !hasJQuery && !forceSkipClickHijack
    };
```

**Comment by ThomasBurleson** [comment] 2015-05-12 20:13
@sebmaniac - great catch. This should be improved with the commit SHA https://github.com/angular/material/commit/a22f6817fb6e89f7004d91bc8ba895b860ea8578

**Comment by ashishtilara** [comment] 2015-06-13 07:48
thank you @ThomasBurleson,

`$mdGestureProvider.skipClickHijack();` trick works perfectly for me

**Closed** 2015-07-06 16:57 UTC
Labels: bug, conflict, gestures

**Comment by yxh10** [comment] 2016-02-24 01:12
@ThomasBurleson FYI, this is happening again to Material v1.0.0 onwards. 
However, the solution 
`$mdGestureProvider.skipClickHijack();`

works nicely.

**Comment by ikhsanputra07** [comment] 2016-04-14 02:32
@ThomasBurleson thanks for your solution. it Works perfectly. Great

**Comment by ilkayhan** [comment] 2017-04-26 06:14
"   $mdGestureProvider.skipClickHijack();   "  Where to write it?  @ThomasBurleson ,

**Comment by thomcom** [comment] 2017-06-07 20:17
@ilkayhan first import ng-material to get $mdGestureProvider, then do it in app.config.

**Comment by daweedm** [comment] 2017-06-14 05:33
Could be a similar issue with the `blur` event firing when it is not necessary ? (Using ionic-v1)

**Comment by ThomasBurleson** [comment] 2017-06-14 13:58
@ilkayhan - try

```js
myAppModule.config(function($mdGestureProvider) {
    $mdGestureProvider.skipClickHijack();
});
```

**Comment by jonathan68** [comment] 2017-07-23 19:21
@ThomasBurleson How can I use this code in Ionic 2?

**Comment by Splaktar** [comment] 2018-01-17 08:57
@jonathan68 you are using AngularJS Material with Ionic 2 or Angular Material with Ionic 2? For Angular Material, you can ask questions in their [forums](https://groups.google.com/forum/#!topic/angular-material2).

**Comment by sas1018** [comment] 2018-06-11 12:27
@ilkayhan can you say more about where

`myAppModule.config(function($mdGestureProvider) {
    $mdGestureProvider.skipClickHijack();
});`

goes? I tried it in my main.js file but that didn't seem to work, do I need to import `angular-material` like @thomcom said?

**Comment by Splaktar** [comment] 2018-06-11 18:38
@sas1018 what exactly happened when you say "didn't seem to work"? The relevant docs can be found here: https://material.angularjs.org/latest/api/service/$mdGestureProvider
