### ISSUE TITLE
md-button stays discolored after being clicked

### ISSUE THREAD

**Issue by infomofo** [angular/material#2079] opened 2015-03-30 00:05 UTC
The angular material md-button implementation stays partially highlighted after being clicked. You can observe that in the demo [here](https://material.angularjs.org/#/demo/material.components.button). 

This is not the behavior expected based on the material design document specification, and it is not the behavior of the corresponding polymer paper button implementation [here](https://www.polymer-project.org/0.5/components/paper-elements/demo.html#paper-button).

**Comment by marcysutton** [comment] 2015-03-30 03:58
Hi, this is a known issue. It's caused by the fact that buttons natively stay focused after you click, so you're seeing the focus style persist. The only reason Polymer doesn't have this problem is there are no keyboard focus styles on the flat buttons, which is bad for accessibility and also doesn't align with the spec either. I have been experimenting with solutions for this, which you can track here: https://github.com/angular/material/pull/1594

Closing as duplicate.

**Closed by marcysutton** 2015-03-30 03:58 UTC
