### ISSUE TITLE
md-select container included in tab

### ISSUE THREAD

**Issue by hodeyp** [angular/material#2804] opened 2015-05-11 08:57 UTC
When tabbing through a form you need to tab twice when entering an md-select as the container gets focus on the first tab

**Comment by robertmesserle** [comment] 2015-05-29 20:15
@hodeyp Can you provide a codepen for this?

**Comment by robertmesserle** [comment] 2015-05-30 00:46
Unable to reproduce, closing for now.  Will reopen if a codepen is provided.

**Closed by robertmesserle** 2015-05-30 00:46 UTC
