### ISSUE TITLE
md-sidenav  with md-disable-backdrop="true" throw exception on iPad (iOS 9.3.5)

### ISSUE THREAD

**Issue by h2atecnologia** [angular/material#9576] opened 2016-09-11 22:20 UTC
**Actual Behavior**:
 -  `What is the issue? *`
Sidenav toggle() method works very well in many browsers, including Edge, MSIE 11, etc.
On Safari/iPad, it throws a exception when this method is called.
 -  `What is the expected behavior?`
Expected to open/close (toggle) the sidenav bar with no errors such as on others browsers.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
sorry no codepen demo
 -  `Details:`
steps: include a sidenav on your app with backdrop option = true. like code bellow:

```html
<md-sidenav layout="column" class="md-sidenav-left md-whiteframe-1dp" md-component-id="left" md-disable-backdrop="true">
</md-sidenav>
```

run on safari/ipad !!

debugging code, this exception throws on updateContainerPositions() method, on line 18868.

**Angular Versions**: *
 -  `Angular Version:`
1.5.6
 -  `Angular Material Version:`
1.1.10 ( minified e not minified ) stack trace below from not minified version

**Additional Information**:
 -  `Browser Type:`
Safari
 -  `Browser Version:` 
 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.8 (KHTML, like Gecko) Version/9.1.3 Safari/601.7.8
 -  `OS:`
iOS 9.3.5
 -  `Stack Traces:`
Error: undefined is not an object (evaluating 'backdrop')
http://ajax.googleapis.com/ajax/libs/angular_material/1.1.0/angular-material.js:18502:19
http://ajax.googleapis.com/ajax/libs/angular_material/1.1.0/angular-material.js:18465:49
http://ajax.googleapis.com/ajax/libs/angularjs/1.5.6/angular.min.js:130:410
$eval@http://ajax.googleapis.com/ajax/libs/angularjs/1.5.6/angular.min.js:145:107
$digest@http://ajax.googleapis.com/ajax/libs/angularjs/1.5.6/angular.min.js:142:178
http://ajax.googleapis.com/ajax/libs/angularjs/1.5.6/angular.min.js:145:201
e@http://ajax.googleapis.com/ajax/libs/angularjs/1.5.6/angular.min.js:45:355
http://ajax.googleapis.com/ajax/libs/angularjs/1.5.6/angular.min.js:48:276

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by crisbeto** [comment] 2016-09-13 18:43
@h2atecnologia can you post an example that shows the issue? I've tried running the HTML you posted [against the demos from the site](https://material.angularjs.org/HEAD/demo/sidenav) on a real iPad with 9.3.5, as well as on some different iOS version through Browserstrack, however I couldn't get it to throw the error in any of the cases.

**Comment by crisbeto** [comment] 2016-10-15 11:07
I gave it another try, but I still couldn't reproduce it. Closing the issue since there hasn't been a response in over a month. The issue can be reopened if there's a example that shows the error.

**Closed by crisbeto** 2016-10-15 11:07 UTC
Labels: needs: more info, P1 - Broken Renders / Major Use Cases
