### ISSUE TITLE
Side nav functions not working on returned instance

### ISSUE THREAD

**Issue by trainerbill** [angular/material#7452] opened 2016-03-07 22:16 UTC
I am trying to expose the instance returned by sidenav to my view:

```js
$mdSidenav('coreLeftNav')
      .then(function (instance) {
        vm.leftnav = instance;
      });
```

Then calling toggle in the view:

```js
<md-button class="md-fab md-mini md-accent md-raised" aria-label="Leftnav Menu" ng-click="vm.leftnav.toggle()">
```

but nothing happens.  The only way I can get it to work is to have a vm.toggle function that directly calls $mdSidenav('coreLeftNav').toggle().  When I output the instance returned in then it looks to have the correct functions but executing them does not work.  I have tried them all.

![image](https://cloud.githubusercontent.com/assets/3578259/13585186/f312052c-e47f-11e5-846b-e34fe0b4b2d4.png)

**Comment by topherfangio** [comment] 2016-03-17 21:33
Can you please provide a Codepen that shows the issue so we can debug it more easily?

**Comment by ThomasBurleson** [comment] 2016-04-25 22:09
Closing this issue due to insufficient information. Please resubmit with:

----
Required
----

**Behavior**:
-  What is the issue? * 
-  What is the expected behavior? 

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue :
-  Details: 

**Angular Versions**: *
-  Angular Version: 
-  Angular Material Version: 

**Additional Information**:
-  Browser Type: *
-  Browser Version: *
-  OS: *
-  Stack Traces: 

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

**Closed by ThomasBurleson** 2016-04-25 22:09 UTC
Labels: - In Progress, needs: demo
