### ISSUE TITLE
Right Sidebar Scroll Bar Problem

### ISSUE THREAD

**Issue by Nextt1** [angular/material#7969] opened 2016-04-10 07:32 UTC
Left sidebar wokrs as desired but whenever I use sidebar on right side and I open that sidebar scroll bar appears on the bottom. It should work smoothly as it is working on left sidebar. Here is the same example which is provided in angular material design docs.

http://codepen.io/next1/pen/NNyqYN

**Comment by topherfangio** [comment] 2016-04-11 19:19
Appears to be a duplicate of #5861. Please comment if it is different and we will reopen.

**Closed by topherfangio** 2016-04-11 19:19 UTC
