### ISSUE TITLE
mdSelect label behavior should match mdInput

### ISSUE THREAD

**Issue by kugler** [angular/material#1867] opened 2015-03-11 08:45 UTC
When no value is selected using md-select with md-select-label, the label is shown within the select. After a value is chosen, the label disappears and there is no way for the end user to understand the meaning of the value.
IMHO after selecting some value using md-select, the label should be resized and float above the input - the same way it does in mdInput.

**Comment by rschmukler** [comment] 2015-03-12 16:43
Closing as duplicate of #1586

**Closed by rschmukler** 2015-03-12 16:43 UTC
