### ISSUE TITLE
Datepicker and Select broken when disableBodyScroll

### ISSUE THREAD

**Issue by waldandrade** [angular/material#7437] opened 2016-03-07 04:15 UTC
In some moments, when scroll are down at the page, and i use datepicker or select .. the function disableBodyScroll broken the body position, cause are no more content down to move up!

> 
function disableBodyScroll() {
        var htmlNode = body.parentNode;
        var restoreHtmlStyle = htmlNode.style.cssText || '';
        var restoreBodyStyle = body.style.cssText || '';
        var scrollOffset = $mdUtil.scrollTop(body);
        var clientWidth = body.clientWidth;

        if (body.scrollHeight > body.clientHeight + 1) {
          applyStyles(body, {
            position: 'fixed',
            width: '100%',
            top: -scrollOffset + 'px'
          });

          applyStyles(htmlNode, {
            overflowY: 'scroll'
          });
        }

        if (body.clientWidth < clientWidth) applyStyles(body, {overflow: 'hidden'});

        return function restoreScroll() {
          body.style.cssText = restoreBodyStyle;
          htmlNode.style.cssText = restoreHtmlStyle;
          body.scrollTop = scrollOffset;
          htmlNode.scrollTop = scrollOffset;
        };
      }
> 

So .... i'll disable that ... but need help to undestand the need of this, and creating a good solution.

**Comment by topherfangio** [comment] 2016-03-17 21:49
Can you please provide a Codepen which demonstrates the issue? It will be much easier for us to debug.

**Comment by ThomasBurleson** [comment] 2016-04-25 22:10
Closing this issue due to insufficient information. Please resubmit with:

----
Required
----

**Behavior**:
-  What is the issue? * 
-  What is the expected behavior? 

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue :
-  Details: 

**Angular Versions**: *
-  Angular Version: 
-  Angular Material Version: 

**Additional Information**:
-  Browser Type: *
-  Browser Version: *
-  OS: *
-  Stack Traces: 

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

**Closed by ThomasBurleson** 2016-04-25 22:10 UTC
Labels: - In Progress, needs: demo
