### ISSUE TITLE
md-tabs: example is broken (font color)

### ISSUE THREAD

**Issue by csvan** [angular/material#5221] opened 2015-10-16 19:22 UTC
The color of an active tab fades into the background, and the one for unselected ones is unusually pale.

https://material.angularjs.org/latest/demo/tabs

![paletabs](https://cloud.githubusercontent.com/assets/1127729/10551222/01b11aae-744c-11e5-8cc8-22409aa57e3f.png)

**Comment by hkgrani** [comment] 2015-10-16 20:17
This had been fixed in HEAD - https://material.angularjs.org/HEAD/demo/tabs

**Comment by Splaktar** [comment] 2015-10-17 18:55
Duplicate of #5155. Fixed in https://github.com/angular/material/commit/c9f822ddbbee4dc148e62b8007dce5fca1feb0aa.

**Closed by Splaktar** 2015-10-17 18:55 UTC
