### ISSUE TITLE
md-autocomplete dosen't working when I clicked clear icon on it.

### ISSUE THREAD

**Issue by tsdragon0404** [angular/material#3498] opened 2015-06-29 08:33 UTC
https://material.angularjs.org/latest/#/demo/material.components.autocomplete
Angular Material 0.10.0
You choose one item, then click [X] on the right.
The page was locked. The element  [div class="md-scroll-mask" style="z-index: 99">  div class="md-scroll-mask-bar"></div</div] doesn't disappear.
It's not occur in previous version.

**Comment by navneet35371** [comment] 2015-06-29 08:42
+1

**Comment by clalag** [comment] 2015-06-29 11:31
+1

**Comment by lucasmartinez** [comment] 2015-06-29 12:36
same issue!

**Comment by cozyazure** [comment] 2015-06-30 08:25
+1

**Comment by jgoux** [comment] 2015-06-30 10:15
Duplicate of https://github.com/angular/material/issues/3287

**Comment by robertmesserle** [comment] 2015-07-06 20:45
This is resolved in master and will be fixed when 0.10.1 is released.

**Closed by robertmesserle** 2015-07-06 20:45 UTC

**Comment by venki-kratos** [comment] 2015-11-04 16:52
well looks like not working even in 0.11.1 - may be related to some issue in query which returns a promise - loading the auto-complete results

**Comment by tchornyi** [comment] 2017-10-10 10:00
Still reproduces on v1.1.4
