### ISSUE TITLE
md-tooltip sometimes remains locked visible after touch outside element in mobile chrome

### ISSUE THREAD

**Issue by mbellezi** [angular/material#5786] opened 2015-11-17 17:08 UTC
The md-tooltip, in some cases, remains locked visible even after touching outside the trigger element. After this situation is triggered, you can touch anywhere on the page and the tooltip does not goes away.

You can see here: http://codepen.io/mbellezi/pen/epxwva

Try to open on Android Chrome and touch inside and out of the button several times until theis situation is triggered. After that, the only way the get ride of the tooltip is touching again inside the button for the tooltip be created again.

**Comment by 0101adm** [comment] 2015-11-17 17:08
+1

**Comment by 0101adm** [comment] 2015-11-17 17:09
believe a dup of #5254

**Comment by SanderElias** [comment] 2015-11-19 12:33
This is indeed a duplicate of #5254. Closed to concentrate conversation in there

**Closed by SanderElias** 2015-11-19 12:33 UTC
