### ISSUE TITLE
Autocomplete Suggestions Scrolling Issue

### ISSUE THREAD

**Issue by Sriram143** [angular/material#4709] opened 2015-09-18 13:00 UTC
Hi

Autocomplete Suggestion are in wrong position if we scroll the browser when the suggestions are in open state

Plase See this screen shot
![image](https://cloud.githubusercontent.com/assets/4466654/9959658/57df6a5e-5e33-11e5-830e-51a448c739a9.png)

**Comment by topherfangio** [comment] 2015-09-18 15:46
Duplicate of #2296.

**Closed by topherfangio** 2015-09-18 15:46 UTC
