### ISSUE TITLE
$mdDialog does not appear from click origin when loaded from Factory.

### ISSUE THREAD

**Issue by vacarsu** [angular/material#2399] opened 2015-04-17 22:28 UTC
Here's the plunker: http://plnkr.co/edit/jgeM0BwkQTUpmPEihdTC?p=preview

**Comment by ThomasBurleson** [comment] 2015-04-18 15:47
I think this is a duplicate of feature request to improve how/where dialogs originate.

**Comment by ThomasBurleson** [comment] 2015-07-31 00:56
Fixed

**Closed by ThomasBurleson** 2015-07-31 00:56 UTC
