### ISSUE TITLE
md-autocomplete md-autocomplete-suggestions are empty

### ISSUE THREAD

**Issue by sfhojo** [angular/material#8840] opened 2016-06-23 21:52 UTC
I am trying to use md-autocomplete and the suggestions never appear. When debugging the code, I can see the objects being returned from the service to the controller, but nothing is displayed. The code is not throwing any errors. It almost seems like the md-autocomplete component isn't seeing the md-items object being passed. Has anyone seen this before? Or have a suggestion on how to debug it?

Here is my html:
`<md-input-container class="md-block" ng-controller="AutoCompleteController as acCtrl">
	<md-autocomplete md-input-name="srchFacility" 
					 md-input-minlength="2"
					 md-selected-item="acCtrl.selectedItem"
					 md-search-text="acCtrl.searchText"
					 md-items="item in acCtrl.querySearch(acCtrl.searchText)"
					 md-item-text="item.Facility1"
					 md-search-text-change="acCtrl.querySearch(acCtrl.searchText)"
					 md-selected-item-change="acCtrl.selectedItemChange(acCtrl.selectedItem)"
					 md-floating-label ="Facility"
		<md-item-template>
			<span md-highlight-text="acCtrl.searchText">{{item.Facility1}}</span>
		</md-item-template>
		<div ng-messages="srchFacility.$error" ng-if="srchFacility.$touched">
			<div ng-message="required">You <b>must</b> choose a facility.</div>
			<div ng-message="minlength">Your entry is not long enough.</div>
		</div>
	</md-autocomplete>
</md-input-container>`

Here is my service and controller:
`app.factory('facUnitService', ['$http', '$q', function ($http, $q) {
    return {
        getQueryableFacilities: function (query) {
            console.log(query);
            return $http.get(app.appConfig.pcaServiceURL + '/facility/query/' + query.toLowerCase() + '/10')
                .success(function (data) {
                    console.log(data.Data); //Displays an array of the 10 items returned
                    return data.Data;
                })
                .error(function (data) {
                    return;
                });
        }
    }
}]);

app.controller('AutoCompleteController', ['$http', '$q', 'facUnitService',
    function ($http, $q, facUnitService) {
        self.querySearch = querySearch;
        self.selectedItemChange = selectedItemChange;
        //******************************
        //Internal methods
        //******************************
        function querySearch(query) {
            var result = query ? facUnitService.getQueryableFacilities(query) : [];
            console.log(result); //Displays a promise with $$state.value.data.Data is the same array as above
            return result;
        }

        function selectedItemChange(item) {
            console.log('Item changed to ' + JSON.stringify(item));
        }

}]);`

**Comment by DevVersion** [comment] 2016-06-24 07:40
Closing this issue due to insufficient information. Please resubmit with:

----
Required
----

**Behavior**:
-  What is the issue? * 
-  What is the expected behavior? 

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue :
-  Details: 

**Angular Versions**: *
-  Angular Version: 
-  Angular Material Version: 

**Additional Information**:
-  Browser Type: *
-  Browser Version: *
-  OS: *
-  Stack Traces: 

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

**Closed by DevVersion** 2016-06-24 07:40 UTC
