### ISSUE TITLE
md-grid-list not working at Android 4.2.2

### ISSUE THREAD

**Issue by marcoocram** [angular/material#1834] opened 2015-03-08 23:26 UTC
I'm using an angular-material component "md-grid-list" in my app, but i noticed that is not working in Android versions under 4.4.

Isn't working at browser even.

The examples from website doesn't work too so you can test it visiting the web from 4.2.2 browser (and its possible lower versions)

Thanks and sorry for my english!

**Comment by shyndman** [comment] 2015-03-11 17:52
Dupe of #1859. This is a bug in the demos, not the grid list.

**Comment by shyndman** [comment] 2015-03-11 17:52
Oh, my mistake. This might be an issue with the default Android browser. I'll look into it.

**Closed by shyndman** 2015-03-11 17:52 UTC

**Comment by marcoocram** [comment] 2015-03-11 18:02
yes, i put the examples because this fails too but i found this bug with my own code :)
