### ISSUE TITLE
Invalid height during tab switch animation

### ISSUE THREAD

**Issue by Toilal** [angular/material#1919] opened 2015-03-16 15:54 UTC
If tabs have different height, when switching from tab X to tab Y, the Y tab is displayed using X height during animation, and it truncates the content. Height is properly set after animation, but UX is weird during the animation.

See this plunker : http://plnkr.co/edit/5THPBT?p=preview

**Comment by Toilal** [comment] 2015-03-17 09:55
Maybe it's related to https://github.com/angular/material/issues/1008

**Comment by robertmesserle** [comment] 2015-03-17 17:42
This is a duplicate of #1008 - Closing.

**Closed by robertmesserle** 2015-03-17 17:42 UTC
