### ISSUE TITLE
Navigating away from md-tabs triggers md-on-select

### ISSUE THREAD

**Issue by omida86** [angular/material#3096] opened 2015-06-03 11:53 UTC
In 0.9.7, every time I navigate away from a page that contains md-tabs using ng-click, it triggers "md-on-select".

Example at: http://plnkr.co/edit/zjuxgnB5z94s001Q63fQ?p=preview

**Comment by omida86** [comment] 2015-06-03 12:23
This does not happen if I change tab.

**Comment by andrewburgess** [comment] 2015-06-03 17:34
I'm experiencing this issue as well.

It seems to be caused by this line:
https://github.com/angular/material/blame/6c53d1127fc1cb7d2a86802e5831642a40ff1e41/src/components/tabs/js/tabsController.js#L184

Which was changed in relation to https://github.com/angular/material/issues/2837

That `removeTab` call is made, at least in my case, from here https://github.com/angular/material/blame/91576d0e7d7d1791e3688ba6ceac9a0750ea9e24/src/components/tabs/js/tabDirective.js#L127

If the tabs directive is being destroyed, we shouldn't care about selected tabs being changed I would assume.

**Comment by shprink** [comment] 2015-06-04 17:08
Having the same here!

**Comment by nvanbenschoten** [comment] 2015-06-05 21:03
Same issue here

**Comment by Praggie** [comment] 2015-06-06 05:36
facing same issue.

**Comment by jaytula** [comment] 2015-06-07 02:37
+1

**Comment by CavemanNinja** [comment] 2015-06-08 13:38
+1 0.9.8-rc1

**Comment by robertmesserle** [comment] 2015-06-09 06:44
This is resolved in 0.9.8 and higher.  Closing for now, please respond with browser details if you are experiencing it past 0.9.8.

@CavemanNinja Unfortunately, the fix was added just after RC1, but it should be good in 0.9.8.

**Closed by robertmesserle** 2015-06-09 06:44 UTC
