### ISSUE TITLE
sidenav,backdrop, dialog should be fixed

### ISSUE THREAD

**Issue by AlmogBaku** [angular/material#1084] opened 2014-12-31 18:39 UTC
On pages with long contents the backdrop nor the sidenav not covers the whole screen while scrolling.

On my case, the solution was:
```css
.md-opaque, md-sidenav, .md-dialog-container {
  position: fixed !important;
}
```

**Comment by epelc** [comment] 2015-01-02 15:29
@AlmogBaku Could you post a plunkr demonstrating this? It seems to be working fine for me.

**Comment by AlmogBaku** [comment] 2015-01-02 17:48
you can see it on http://www.chiefangel.com

**Comment by epelc** [comment] 2015-01-02 18:06
It probably has to do with your use of `layout-fill` which is very much like `height: 100%;` if you want full page elements. It needs to be applied on all parents. You probably forgot it on the `body` element.

**Comment by AlmogBaku** [comment] 2015-01-02 18:19
@epelc I just tried to add `layout-fill` class to all the parents of the `sidenav` with the "chrome dev tool" and it didn't solved the problem(without the fixed)

**Comment by epelc** [comment] 2015-01-02 18:22
@AlmogBaku maybe you can take a look at my example project [go-material](github.com/epelc/go-material). I don't remember if I added a dialog to it yet but it is using the same layout/structure of my app which dialogs work fine on.

Also can you check against the latest master and `0.7.0rc1` a lot of things get randomly broken and fixed. We may be running different versions.

**Comment by ThomasBurleson** [comment] 2015-01-06 16:55
Unable to reproduce.

**Comment by Bassel-m** [comment] 2016-03-09 11:35
Wow man this really fixed the issue for me but broken another feature, I'm trying to implement one sidebar on the right with two buttons that trigger it, one button to open it covering the content and the other to lock it open in the flow of content, this fix however fixed the one covering the content but the other no longer works

**Comment by DevVersion** [comment] 2016-03-09 11:36
@Bassel-m I didn't investigate at your issue yet, so if you think this is a issue, which relates to `ngMaterial`, then please file a new one.

**Comment by Bassel-m** [comment] 2016-03-09 12:13
@DevVersion Can you please have a look at this site basselahmed.com/myAdmin .. forgive me for the language it's in Arabic, Please scroll down and press the switch in the top right see the problem

**Comment by ThomasBurleson** [comment] 2016-04-28 20:27
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).

**Closed by ThomasBurleson** 2016-04-28 20:27 UTC
