### ISSUE TITLE
md-switch not properly bound to ng-model

### ISSUE THREAD

**Issue by cliffeby** [angular/material#9740] opened 2016-10-02 23:53 UTC
**Actual Behavior**:
 -  `What is the issue? *`Incorrect initial switch position when ng-model is true
 -  `What is the expected behavior?`  **true** value of model should show **true** switch position.

**CodePen** (or steps to reproduce the issue): *https://codepen.io/cliffeby/pen/RGLZOw
 -  `CodePen Demo which shows your issue:`Switch 2a and 2b
 -  `Details:`     Item_1. ng-true-value parameter disables the initial md-switch true setting.  Switch reads false when model value is true.  Removing ng-true-value="'x'" results in the correct behavior.  See Switch 2a and b.           Item_2.  md-switch is not bound to ng-model irrespective of ng-true-value.  Manually toggle Switch 2a and b to see this incorrect behavior.  

**Angular Versions**: *
 -  `Angular Version:` See CodePen
 -  `Angular Material Version:`See CodePen

**Additional Information**:
 -  `Browser Type: *`Chrome
 -  `Browser Version: *`Version 53.0.2785.116 m
 -  `OS: *`Win 10
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by jkjustjoshing** [comment] 2016-10-17 23:12
To me this looks like intended behavior. 

With the `ng-true-value` binding you're saying "treat this value as the value the switch sees as truthy". So if you set the model manually to `'yup'` then it will work as you're hoping for initially. Since the model is `true`, which doesn't match `'yup'`, the component considers the switch "off".

**Comment by ThomasBurleson** [comment] 2016-10-18 14:21
This issue is closed as it falls in the 'deprecated' category. We deprecate issues for one or more of the following reasons:

*  **Issue has a reasonable workaround**
*  Issue doesn't have a demo or reproducible case available
*  Issue is real, but fixing it is risky for users who depend on existing behavior
*  Issue is real, but only affects a very small use case
*  Issue is real, but would require significant work to fix, and is less urgent than other needs.

> Pull Requests are welcomed to resolve this issue. But note that **not** all community PRs will be merged into master. Pull Requests with large changes or large scope impacts will probably be rejected [due to stability risks to existing users].

**Closed by ThomasBurleson** 2016-10-18 14:21 UTC

**Comment by cliffeby** [comment] 2016-10-24 17:34
Thanks for the clarification and community support.  As a novice to JavaScript, I thought **true** was always truthy and could not be overridden.  Your approach works for me.

**Comment by jkjustjoshing** [comment] 2016-10-24 17:44
Awesome! 

And to clarify, it's not that `true` is getting overridden, it's just that you're telling the component only to turn "on" at a certain value. It's like if you have a children's race, but you tell them that instead of "on your marks, get set, GO!" the race only starts when you say "on your marks, get set, POTATO!". The meaning of the word "go" hasn't changed, but if you were to say "on your marks, get set, GO!" the kids shouldn't start running because you explicitly said "only run when I say 'POTATO'". "Go" still means the same thing, you've just told the kids that to start the race they should listen for the word "POTATO" instead.

Does that clear things up at all @cliffeby?

**Comment by cliffeby** [comment] 2016-10-26 04:01
Got it.  Once **ng-true-value** is assigned, **true** is ignored.  I always ran on GO!
