### ISSUE TITLE
any data table component?

### ISSUE THREAD

**Issue by lyrl** [angular/material#3836] opened 2015-07-21 10:07 UTC
i am looking for it.

**Comment by Koslun** [comment] 2015-07-21 11:49
Please post general questions to the forum instead: https://groups.google.com/forum/#!forum/ngmaterial. So we only have actual issues like bugs or new features here.

To answer the question. See issue #796 mdTable: Table Component. Summary: An official one is not planned until after the 1.0 release. There are a few working on ones that they hope to use in the mean time or possibly integrate later on. Namely http://iamisti.github.io/md-data-table/ and http://danielnagy.me/md-data-table/. Also been suggested to review https://github.com/Swimlane/angular-data-table.

Currently using http://danielnagy.me/md-data-table/ myself. Works fine for me so far.

**Comment by Anthropic** [comment] 2015-07-24 04:44
Look at this issue #796 on mdTable and maybe close this one if it is a duplicate.

**Comment by jelbourn** [comment] 2015-09-16 17:41
Dupe of #796

**Closed by jelbourn** 2015-09-16 17:41 UTC
