### ISSUE TITLE
"Illegal use of ngTransclude directive" when trying to compile a md-button

### ISSUE THREAD

**Issue by cadilhac** [angular/material#11700] opened 2019-04-03 18:10 UTC
## Bug:

I have an angularjs directive that creates a google map. As a child of this directive, a custom-control directive allows to add custom buttons in the corners of the map. This looks like this:

<ng-map>
    <custom-control id="openpanel" position="LEFT_TOP" index="1">
        <md-button class="md-fab md-mini" aria-label="" md-theme="theme-plusbutton" ng-click="$ctrl.showPanel()">
            <md-icon md-svg-icon="/path/to/icon"></md-icon>
        </md-button>
    </custom-control>
</ng-map>

My directive creates the md-button inside the map with:
$compile(customControlElement.innerHTML.trim())(scope);

At runtime, I get this in the console:

Illegal use of ngTransclude directive in the template! No parent directive that requires a transclusion found. Element: <button class="md-fab md-mini md-button md-theme-plusbutton-theme md-ink-ripple ng-scope" type="button" ng-transclude="" aria-label="" md-theme="theme-plusbutton" ng-click="$ctrl.showPanel()">

However, the button displays and runs well. So, why does MD gives this error?

**Comment by Splaktar** [comment] 2019-04-18 04:06
Thank you for taking the time to submit this issue. However it does not follow our **required** issue template. This gives the team the information needed to investigate the bug or prioritize the feature.

Please provide a reproduction via CodePen or a GitHub repo, reproduction steps, and the relevant versions of AngularJS, AngularJS Material, browser, OS, etc.

**Comment by Splaktar** [comment] 2019-07-21 23:15
Closing due to lack of information.

**Closed by Splaktar** 2019-07-21 23:15 UTC
Labels: needs: demo, needs: more info
