### ISSUE TITLE
Unmet peer dependencies on angular update to 1.6.0 from 1.5.9

### ISSUE THREAD

**Issue by davidalekna** [angular/material#10149] opened 2016-12-16 13:03 UTC
Hey guys, I have following problem on latest update to angular 1.6.0

**Actual Behavior**:
On npm update from angular 1.5.9 to 1.6.0 caused npm to throw dependency errors

npm WARN angular-material@1.1.1 requires a peer of angular@>=1.3 <1.6 but none was installed.
npm WARN angular-material@1.1.1 requires a peer of angular-animate@>=1.3 <1.6 but none was installed.
npm WARN angular-material@1.1.1 requires a peer of angular-aria@>=1.3 <1.6 but none was installed.
npm ERR! code 1

and ng-model-options stopped working throughout the application for md-select also including $$mdSelectId for every object selected.

**Angular Versions**: *
 -  `Angular Version:` ^1.6.0
 -  `Angular Material Version:` ^1.1.1
 -  `Angular Animate:` ^1.5.6
 -  `Angular Area:` ^1.5.6

Anyone else had anything like that recently? 

Thanks

**Comment by JodyJSmith** [comment] 2016-12-16 16:05
David,
Disclaimer: I'm a complete noob trying to learn Angular and Material simultaneously. That said, I'm getting the exact same dependency errors. I cloned the angular-seed git to local repo, then tried to install material into the seed via npm.

Not sure if it's a directory thing or what. I noticed the seed puts angular in bower_components, and material in node_modules. I tried moving stuff around, manually adding the entirety of 1.5.9 into my angular directory, but I'm still getting the same warnings and errors.

**Comment by davidalekna** [comment] 2016-12-16 19:07
Seems like downgrading to 1.5.9 solves dependency issues.

```
├── UNMET PEER DEPENDENCY angular@1.6.0
├── UNMET PEER DEPENDENCY angular-animate@1.6.0
├── UNMET PEER DEPENDENCY angular-aria@1.6.0
└── angular-material@1.1.1 
```

**Comment by stevemrd** [comment] 2016-12-20 14:33
I also found out about this the hard way from doing an npm update as well. Looks like we're sticking with 1.5.9 until Angular Material supports 1.6.0.

**Comment by fetters5** [comment] 2016-12-23 15:17
They just released angular 1.6.1 which looks like it may fix the  ngmodeloptions

[](https://github.com/angular/angular.js/blob/master/CHANGELOG.md#161-promise-rectification-2016-12-23)

**Comment by Galindo-janrain** [comment] 2016-12-23 19:42
+1

**Comment by stevemrd** [comment] 2016-12-27 15:52
Nope, still broken. Angular Material has a < 1.6 version requirement.

npm WARN angular-material@1.1.1 requires a peer of angular@>=1.3 <1.6 but none was installed.
npm WARN angular-material@1.1.1 requires a peer of angular-animate@>=1.3 <1.6 but none was installed.
npm WARN angular-material@1.1.1 requires a peer of angular-aria@>=1.3 <1.6 but none was installed.

Glad to see they've been steadily releasing new Angular versions at least, but my current node projects are unable to take advantage of this until Angular Material is updated to require the new Angular version. :(

**Comment by Kappyh** [comment] 2016-12-27 19:38
I have the same problem in my project:

npm WARN angular-material@1.1.1 requires a peer of angular@>=1.3 <1.6 but none was installed.
npm WARN angular-material@1.1.1 requires a peer of angular-animate@>=1.3 <1.6 but none was installed.
npm WARN angular-material@1.1.1 requires a peer of angular-aria@>=1.3 <1.6 but none was installed.

My boss ask me to resolve this, but I don't know what to do.Is really related with angular 1.6 incompatibility or is a other thing?

**Comment by stevemrd** [comment] 2016-12-27 19:52
@Kappyh you will have to downgrade Angular to the latest 1.5.x release for this to work.

As of this post, the latest 1.5.x version of AngularJS is 1.5.10.

npm upgrade angular@1.5.10
npm upgrade angular-animate@1.5.10
npm upgrade angular-aria@1.5.10

Don't run "npm update" until this issue is resolved. You can still upgrade other packages individually with "npm update <package@version>"

I recommend keeping all other angular components at this version to avoid any further breakage.

**Comment by vatsalpande** [comment] 2016-12-28 06:28
I am facing the same issue. I would like to use angular1.6 since its a new project. Is there any possibility of making it compatible with angular 1.6?

**Comment by bathos** [comment] 2016-12-28 07:09
The unmet peer dependency warning is only a warning. While 1.6.0 had some major issues with ngMaterial, it seems that many (not sure if "all") were fixed as of ng 1.6.1. In my case I’m using ngMaterial + 1.6.1 without seeing any problems so far.

**Comment by tugrulelmas** [comment] 2017-01-02 18:46
I wrote ng-model-options issue detail at [#10192 (comment)](https://github.com/angular/material/issues/10192#issuecomment-269969869). I drop it here in case it is useful for anyone else.

**Comment by bathos** [comment] 2017-01-02 22:33
Update: for md-datepicker (and perhaps other components, but this is the only one that has had this issue so far for me), you will need to enable the old assign-to-instance-before-constructor-is-invoked behavior with `$compileProvider.preAssignBindingsEnabled(true)`.

**Comment by Kappyh** [comment] 2017-01-03 12:18
> @bathos Update: for md-datepicker (and perhaps other components, but this is the only one that has had this issue so far for me), you will need to enable the old assign-bindings-to-instance-before-constructor-is-invoked behavior with $compileProvider.preAssignBindingsEnabled(true).

Solved my only problem . Thank you!!! :+1:

**Comment by stevemrd** [comment] 2017-01-03 15:34
The datepicker issue was reported in https://github.com/angular/material/issues/10168 and the fix is also listed there. The fix did work for me, but the unmet peer dependency issue should be kept separate. This can be fixed by the angular material team releasing a version which depends on <= angular 1.6.

So far, the datepicker component has been the only issue with angular material 1.1.1 and angular 1.6.

**Comment by ThomasBurleson** [comment] 2017-01-03 17:02
This issue will be address with the fixes to #10111.

**Comment by rochapablo** [comment] 2017-01-12 10:44
+1

**Comment by cloudinertia-system** [comment] 2017-01-20 11:02
@bathos 
Be aware of implications if using ES6 classes
> Disabling (by default) the pre-assignment of bindings on controller instances, which helps with support for native ES6 classes

[https://docs.angularjs.org/guide/migration#migrating-from-1-5-to-1-6](url)

**Comment by bathos** [comment] 2017-01-24 02:00
Good point. I am, actually, but since the project is in Electron, I don’t have to worry about browser differences in the `toString` results for constructors created with class syntax — my own classes will pass Angular’s regex test and get instantiated the new way, while just 3rd party libs get the old behavior. But it’s true that if using class syntax (untranspiled) and you do not have environmental assurances, you could run into problems with browsers that support the syntax but do not return something Angular recognizes as class syntax from `toString`.

**Comment by PedroF20** [comment] 2017-02-07 16:33
I have the same issue, but as I am planning to use only the Card, I don't think it will be too much of a problem.

**Closed** 2017-03-03 14:46 UTC
Labels: needs: Angular 1.6 support, P0 - Critical Fixes / Build or Deployment Issues

**Comment by PedroF20** [comment] 2017-03-03 15:02
Will there be a new release soon?

**Comment by joehoeller** [comment] 2018-02-16 14:13
Seems as if AngularJS v1.6.9 doesn't work with AngularJS Material v1.1.7 -- any one else have this issue?

**Comment by Splaktar** [comment] 2018-02-18 09:10
@joehoeller please open a new issue and provide a CodePen that demonstrates the issue and the NPM warnings/errors that you are seeing.

**Comment by joehoeller** [comment] 2018-04-24 21:43
Just now seeing this, the prob still persists. I'll post in a few...

**Comment by joehoeller** [comment] 2018-04-24 21:44
Router doesnt work with Material

**Comment by Splaktar** [comment] 2018-05-03 19:06
@joehoeller please open a new issue with a GitHub repo reproduction.
