### ISSUE TITLE
(bug) Ripple effect

### ISSUE THREAD

**Issue by thiagofront** [angular/material#2645] opened 2015-04-30 20:26 UTC
Hi guys,
Take a look about the last buttons, cause they are with problems with the ripple effect when are with scroll

http://jsbin.com/dovecamoke/2/edit

**Comment by ThomasBurleson** [comment] 2015-04-30 20:27
@thiagofront - plz search the issues list before submitting new bugs.
Duplicate of #2636

**Closed by ThomasBurleson** 2015-04-30 20:27 UTC
