### ISSUE TITLE
mdSelect: items appear multiple times

### ISSUE THREAD

**Issue by Frank3K** [angular/material#1643] opened 2015-02-24 20:55 UTC
Since ee4c7c1809558a51a58928e9fbe06ab16686742a, which fixed #1601, the items in a md-select appear multiple times. In my example, each item is repeated `n` times where `n` is the number of items in the `ng-repeat` collection.

In a previous version [v0.8.0-rc1-master-eda14e9](https://github.com/angular/bower-material/commit/5d70169b6147dc15144d3f85a929a9ac3f429584) this issue did not happen, see this [Plunker](http://plnkr.co/edit/FzvqHazia1AAmTt5BjNb?p=preview).

Updated [Plunker demonstrating the issue](http://plnkr.co/edit/Fnrd6fqg2LDdjQ4mOYdk?p=preview). Using master branch.

The demos on the demo-page do not seem to have this issue, which leads me to believe that this issue is somehow related to the ng-repeat combined with the `ng-model` or `ng-value` values used.

**Comment by IPRIT** [comment] 2015-02-24 21:01
I found a similar problem right now.

**Comment by seiyria** [comment] 2015-02-25 04:29
I believe this is a duplicate of #1653.

**Comment by Toilal** [comment] 2015-02-25 09:56
It's not a duplicate of #1653, I hit the issue in my own project too, using `master` or `v0.8.1`.

**Closed** 2015-02-25 17:01 UTC
Labels: bug

**Comment by jboothe** [comment] 2015-11-25 06:00
I am using v1.0.0-rc4 and md-select, replaces the first item in the dropdown list with the selected item. 
In a list of years, for instance, clicking 2013 replaces the first item (2015) with 2013. So the list looks like this after clicking 2013:

2013
2014
2013
2012
... 

Has this been addressed or user error?

**Comment by iamryandrake** [comment] 2016-02-08 07:11
This is still an issue -_-.

Any update on this?

**Comment by Frank3K** [comment] 2016-02-08 16:41
@iamryandrake are you sure you have the exact same issue? The issue I described has already been fixed for quite some time.

Can you include a demo or open a new issue if the issues are not the same?
