### ISSUE TITLE
md-card demo does not work on iOS devices

### ISSUE THREAD

**Issue by fstiffo** [angular/material#6573] opened 2016-01-07 08:48 UTC
The md-card demo on Material Angular site
https://material.angularjs.org/latest/demo/card
does not work on iOS devices safari browser (tested on various from iOS 8 to the latest iOS 9.2) and iPhone 5, 5S, 6, 6 Plus

**Comment by gvorster** [comment] 2016-01-07 10:54
Tried this as well on iPhone 5s IOS 9.2 and md-card is not shown in Safari.

**Comment by DevVersion** [comment] 2016-01-07 17:27
Yes, I can reproduce that - it seems to be related to the `flex-50` class, I debugged the IOS Safari, and it worked if I remove the `flex-50` class.

**Comment by DevVersion** [comment] 2016-01-19 19:35
Should be fixed in #6765

**Closed** 2016-01-21 21:54 UTC
Labels: P2 - Planned Work / Team PRs, ui: flexbox
