### ISSUE TITLE
md-virtual-repeat does not support gallery style lists (grid)

### ISSUE THREAD

**Issue by gkohen** [angular/material#5312] opened 2015-10-22 12:10 UTC
Hi,

We were excited to hear about the new visualization capability of lists is Angular Material. This helps us deal with rendering large datasets. Unfortunately, we found out that for one of our main uses which is a list represented by a tiled gallery grid, the md-virtual-repeat could not be used (Please correct me if I'm wrong). Here's an example:
http://goo.gl/ujXLs8
Mind you, I'm not asking for a more complex Pintrest/Masonry type tiling ability  (although it would be nice). We're trying to implement a gallery displaying large number of items, where all tiles are the same size. 
What I've found so far is that md-virtual-repeat supports a list that is either all vertical or all horizontal.

I'd love to hear any ideas folks might have to resolve this.

**Comment by bernyfox** [comment] 2015-10-22 12:53
+1

**Comment by gduford** [comment] 2015-10-22 13:09
+1

**Comment by johnmartel** [comment] 2015-10-22 13:26
+1

**Comment by BBeauchemin** [comment] 2015-10-22 13:43
+1

**Comment by gduchesneau** [comment] 2015-10-22 14:19
+1

**Comment by TwDrake** [comment] 2015-10-22 16:40
+1

**Comment by FrankTheTank9** [comment] 2015-10-22 17:34
+1

**Comment by vaibhavsharma27** [comment] 2015-10-23 06:35
+1

**Comment by JoeHetfield** [comment] 2015-10-29 09:09
+1

**Comment by bseyb** [comment] 2015-11-05 19:56
+!

**Comment by Todd-Werelius** [comment] 2015-11-06 07:37
+1

**Comment by kseamon** [comment] 2015-11-09 21:18
Dupe of #5068.

Should be doable for fixed-size items, but I'm not sure when I'll be able to get to it.

**Comment by kseamon** [comment] 2015-12-09 19:17
Closing as duplicate.

**Closed by kseamon** 2015-12-09 19:17 UTC
Labels: type: feature
