### ISSUE TITLE
select(multiple): closes when changing value in $scope

### ISSUE THREAD

**Issue by zuhairamahdi** [angular/material#11859] opened 2020-02-16 12:04 UTC
## Bug, enhancement request, or proposal:

# CodePen and steps to reproduce the issue:
#### Detailed Reproduction Steps: 
1. select item from `md-select multiple`
1.  change value in `$scope`
1. `md-select` will close by itself

### What is the expected behavior?
because `md-select multiple` is of a multiple selection it is not very user friendly to repoen the dialog every time

### What is the current behavior?
1. select item from `md-select multiple`
1.  change value in `$scope`
1. `md-select` will close by itself

### Which versions of AngularJS, Material, OS, and browsers are affected?

- AngularJS: 1.
- AngularJS Material: 1.
- OS:  Windows
- Browsers: Chrome
 
### Is there anything else we should know? Stack Traces, Screenshots, etc.
we have a filter fields and some fields are using `md-select multiple` and every time we change the value we call an api endpoint which will change another value
this is an example of the control:
```html
<md-input-container style="width: 100%;">
    <label ng-bind="control.name || control.key"></label>
    <md-select ng-model="data[control.key]" md-on-open="" ng-required="control.required" aria-label="{{control.key}}" multiple>
        <md-option ng-if="control.emptyOpt" ng-value="control.emptyOptValue" ng-click="$S.filters[$S.nav.root] = $H.merge({}, $D.filters[$S.nav.root] || {})">{{control.emptyOpt}}</md-option>
        <!--<md-option ng-repeat="i in control.lookup | orderBy:'te'" ng-value="i.k" ng-bind="i.t || i.te || i.k"></md-option>-->
        <md-option ng-repeat="r in control.lookup" value="{{r.k}}">{{r.te}}</md-option>
    </md-select>
    <div ng-messages="$f[control.key].$error" role="alert" multiple>
        <div ng-message="required">Required</div>
    </div>
</md-input-container>
```
and this is when we call the api:

```js
                      api.GET(query)
                        .then(function (data) {
                            $scope.data = data;
                            $scope.$readyTimeout = $timeout(function () {
                                $scope.state.ready = true
                                $scope.data.$pageCount = $H.keysCount(data.pages || {});
                            }, 100);
                        },function (response) {
                            $scope.data = {};
                            if (!response.errorDialog) {
                                alert($C.global.alerts["404"]);
                            }
                        }).finally(function () {
                            $timeout.cancel(overlay_timeout);
                            $scope.state.loading = false;
                            $scope.state.overlay = false;
                        })
```
the issue is with this statment:
`$scope.data = data;`
it closes the select dropdown menu when it should not.

**Comment by codymikol** [comment] 2020-02-25 16:52
rather than reassigning data, what if you modify it in place via 

```javascript
angular.copy(data, $scope.data)
```

**Comment by Splaktar** [comment] 2020-02-25 23:50
What versions of AngularJS and AngularJS Material are being used?

Can you please post a CodePen demo (required)?

**Comment by zuhairamahdi** [comment] 2020-03-03 08:41
> rather than reassigning data, what if you modify it in place via
> 
> ```js
> angular.copy(data, $scope.data)
> ```

@codymikol I still get the same behavior. we couldn't find a solution till now and our last resort is to create a new control element that uses checkbox instead of multiple select.

**Comment by Splaktar** [comment] 2020-11-15 04:09
Unable to reproduce without a CodePen, StackBlitz, or GitHub demo. Also no response to what version of AngularJS and AngularJS Material are being used.

**Comment by codymikol** [comment] 2020-11-15 04:10
You're on a roll @Splaktar , my inbox is blowing up :p

**Closed by Splaktar** 2020-11-15 04:09 UTC
Labels: needs: demo, needs: more info, resolution: can't reproduce
