### ISSUE TITLE
Rapidly clicking any css wave enabled directive, button(icon,fab,flat), checkbox and switch does not fade away

### ISSUE THREAD

**Issue by kevindstanley1988** [angular/material#2176] opened 2015-04-06 16:41 UTC
The rapid click will always eventually glitch this way. I have manually tried this about 100 times on different buttons and have always had the wave get 'stuck' in its outermost position in the animation.

rapidly clicked checkbox
![image](https://cloud.githubusercontent.com/assets/5685997/7007702/2f37e280-dc5a-11e4-8685-309f0ca74827.png)

rapidly clicked switch
![image](https://cloud.githubusercontent.com/assets/5685997/7007588/5fcf4a4c-dc59-11e4-9d93-ef286e45a55a.png)

Button before rapid clicking
![image](https://cloud.githubusercontent.com/assets/5685997/7007628/c321d740-dc59-11e4-8a38-1a19195fe966.png)

Button after rapid clicking(not active)
![image](https://cloud.githubusercontent.com/assets/5685997/7007622/b8941914-dc59-11e4-86f7-aedd1c9d995a.png)

The below heart was rapidly clicked on and is not active
![image](https://cloud.githubusercontent.com/assets/5685997/7007604/91a34c58-dc59-11e4-8c7a-e2141d81ee62.png)

**Comment by marcysutton** [comment] 2015-04-06 20:17
This is a duplicate of #2149.

**Closed by marcysutton** 2015-04-06 20:17 UTC
