### ISSUE TITLE
md-datepicker lost its css background style since 0.11.4 version

### ISSUE THREAD

**Issue by bastienJS** [angular/material#5165] opened 2015-10-14 18:52 UTC
see this plunker: http://plnkr.co/edit/B0xuv5pJyebju0SBb9gY

open a datepicker to choose a date.

**Comment by ThomasBurleson** [comment] 2015-10-14 19:00
Duplicate of known issue.

**Closed by ThomasBurleson** 2015-10-14 19:00 UTC
Labels: resolution: duplicate

**Comment by kpgarrod** [comment] 2015-11-10 07:25
Of which known issue is this a duplicate? In which version is it fixed? I am using v1.0.0-rc3 and still experiencing a transparent md-datepicker.

**Comment by Seiifer** [comment] 2015-11-16 12:44
@kpgarrod Try using v0.11.2

**Comment by kpgarrod** [comment] 2015-11-16 18:59
@Seiifer Have you seen how many other bugs have been fixed since 0.11.2? To take nothing away from the fantastic work that this project has done, it does seem that md-datepicker is the poor cousin. I have been waiting for it for over a year and I really think a V1 Release Candidate should have a usable version of it. I see the many md-datepicker bugs have been pushed out yet again to RC5. I am very disappointed. A datepicker was promised for 0.8.0 and there has never yet been one that is usable in a real life project. This is probably not the place to rant, but I needed to take my frustration out somewhere!
