### ISSUE TITLE
mdDialog: controller not present in scope when using contentElement and controllerAs

### ISSUE THREAD

**Issue by Looooong** [angular/material#9267] opened 2016-08-09 11:03 UTC
**Actual Behavior**:
 -  `What is the issue? *` When showing a dialog with options `contentElement` and `controllerAs`, the controller instance is not present in the scope.
 -  `What is the expected behavior?` controller instance should be present in the scope when using `contentElement` in conjunction with `controllerAs`.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` [$mdDialog pen](http://codepen.io/looooooooong/pen/qNQJdd)
 -  `Details:` The demo shows pre-rendered dialog and template dialog with similarity

**Angular Versions**: *
 -  `Angular Version:` 1.5.x
 -  `Angular Material Version:` 1.1.0-rc.5

**Additional Information**:
 -  `Browser Type: *` Google Chrome
 -  `Browser Version: *` Version 52.0.2743.116
 -  `OS: *` Ubuntu 16.02 LTS
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by DevVersion** [comment] 2016-08-09 15:06
So after looking at your codepen, this is actually the expected behavior.

- `contentElement` is not compiling the element
- It also doesn't link the element to another scope (like `controllerAs`)

I want to keep that issue open yet, because you probably have some other thoughts. Up for discussion.

**Comment by Looooong** [comment] 2016-08-10 10:25
My intention is to pass `locals` to the already compiled dialog. If not using `controllerAs`, I would have use `$broadcast` to send data to the dialog. Is there a better way to do this?

**Comment by DevVersion** [comment] 2016-08-13 17:00
I understand.

>  In this situation it doesn't really make any sense to use the `pre-rendered` dialog, because it is designed to not be `re-compiled` / `re-linked` (as mentioned above)

> To be able to pass the locals or instantiate the given controller, we would need to re-link the dialog.


The only way to link your dialog to a controller is to define the `ng-controller` attribute on the dialog element.

```html
<md-dialog ng-controller="MyDialogController">
  This is a pre-rendered dialog.
</md-dialog>
```

Closing this, since the pre-rendered dialog works as expected.

**Closed by DevVersion** 2016-08-13 17:00 UTC
