### ISSUE TITLE
Chips: possible to combine autoselect with custom values?

### ISSUE THREAD

**Issue by dopgm** [angular/material#3921] opened 2015-07-28 05:17 UTC
Hi,

Is it possible to combine chips auto-select with manual entry, like here: http://mbenford.github.io/ngTagsInput/demos ?

If not, please consider this to be a feature request.

Most frequent use-case: we want to let customers add their own tags, however would like them to see the pre-existing ones first to minimize number of variations (due to different spellings, misspellings, etc.). 
Example workflow:
- user entered some music styles from a list of predefined styles
- now he/she wants to add a "punk" music style, however it does not exist in our db yet
(  drop-down shows an existing style - "post-punk", as it matches the "punk" part )
- user decides to keep his own - "punk" and clicks on Enter or (defocus, etc)
- new chip appears in the input, in addition to the others, previously selected or loaded

Thank you!
D

**Comment by typotter** [comment] 2015-08-10 03:36
remove md-require-match from md-chips, and you will be able to add items not already in the autocomplete list.
You will need to provide an md-on-append expression.

**Comment by typotter** [comment] 2015-08-10 03:41
reopening for docs.

**Comment by dopgm** [comment] 2015-08-10 17:53
@typotter 
I confirm that the issue has been resolved.
Thank you, Sir!

**Comment by typotter** [comment] 2015-08-10 18:05
Thanks @dopgm. Am keeping open the issue to add to the docs, as that attribute is not documented yet.

**Comment by chr22** [comment] 2015-09-18 11:51
When you add a Chip with the enter key (not the mouse), it will add two chips, the correct one, and one with the text you entered.
Here is a [CodePen demo](http://codepen.io/anon/pen/ZbWMYX).

This is only without me-on-require-match.

**Comment by dopgm** [comment] 2015-09-18 13:54
@chr22 
I've just checked the CodePen demo. Yeah, I see the concept working. Thank you!
The only issue is that custom chips do not display text, just brackets :/

**Comment by chr22** [comment] 2015-09-18 14:33
@dopgm no if think you misunderstand me.

It adds two chips for one return-key hit.
I chose two different chips in the picture below, but it added four chips:
![chip](https://cloud.githubusercontent.com/assets/3649594/9961821/e971a740-5e22-11e5-8719-ecf063964a68.PNG)

**Comment by topherfangio** [comment] 2015-09-18 15:59
@chr22 See #4666 which points to two PRs that should alleviate this problem.

@typotter Mind if I close this in favor of #4666 which is specific to adding the docs?

**Comment by topherfangio** [comment] 2015-10-08 16:56
@chr22 Scratch my last comment; I think your issue is actually a duplicate of #4412.

Closing this due to duplicates.

**Closed by topherfangio** 2015-10-08 16:56 UTC
Labels: needs: demo, severity: inconvenient, type: docs
