### ISSUE TITLE
md-select multiselect design feedback

### ISSUE THREAD

**Issue by dohomi** [angular/material#4302] opened 2015-08-24 08:09 UTC
Hello,

After showing the ```md-select``` with ```multiple="true"```to several persons and almost nobody understood the component I'd like to post the feedback here.

One issue is, that the selected blue font color wasn't enough that they understood that the item is selected and they can select more fields. Some checkbox icon for selected items would make the selection more obvious for the user.

On smartphones the multiselect is missing an ```x-closing``` button in several cases. On huge lists its sometimes very difficult clicking outside of the element, so an closing button on top right would make it simple for the user.

Hope this feedback makes sense to you guys. Cheers

**Comment by rschmukler** [comment] 2015-09-10 16:10
Duplicate of #2239

**Comment by rschmukler** [comment] 2015-09-10 16:10
Ps. Thank you for the feedback. Apologies for the brief remark - issue triaging.

**Closed by rschmukler** 2015-09-10 16:10 UTC

**Comment by dohomi** [comment] 2015-09-10 16:47
Thanks for checking it out!
