### ISSUE TITLE
mdTooltip inside mdDialog wrong position

### ISSUE THREAD

**Issue by weisk** [angular/material#4954] opened 2015-10-01 00:05 UTC
mdTooltip position gets messed up when it is inside an $mdDialog, and the body is scrolled.

plunkr provided:
http://plnkr.co/edit/iEmViRI0wYke8onEsaok?p=preview

related to https://github.com/angular/material/issues/1883

**Comment by jelbourn** [comment] 2015-10-01 00:20
I can confirm that the tooltip is off.

**Comment by SanderElias** [comment] 2015-11-03 14:28
Duplicate of #2791. Closed to concentrate discussion in there.

**Closed** 2015-11-03 14:31 UTC
Labels: priority: critical, type: bug
