### ISSUE TITLE
md-datepicker: problems changing value for en-gb locale (probably others too)

### ISSUE THREAD

**Issue by bluebirdtech** [angular/material#4776] opened 2015-09-22 17:41 UTC
Repro: In the demo for md-datepicker at head, while using Chrome on Windows with en-gb locale, select the month date component and replace it with another valid month value.

Result: Month and day components sometimes swap around.  And other times the input becomes invalid.

Expected: Month value is replaced and the value change is propagated the model.

Workaround: Use moment.js to parse the date, using the current browser culture:
````
    myAppModule.config(function($mdDateLocaleProvider) {
        var locale = window.navigator.userLanguage || window.navigator.language;
        moment.locale(locale);

        $mdDateLocaleProvider.parseDate = function(dateString) {
            var m = moment(dateString, 'L', true);
            return m.isValid() ? m.toDate() : new Date(NaN);
        };
        $mdDateLocaleProvider.formatDate = function(date) {
            return moment(date).format('L');
        };
    });
````

Thoughts:
Given Date.parse is unreliable, will there need to be a strong recommendation to use a custom provider based on eg. moment.js to handle international date formats nicely?

Sub-issues:
 - In the md-date-locale-provider example, parse date is expecting an ISO-8601 formatted string. I suspect this is rarely helpful, but instead the sample could be updated to include a section from the above workaround.
 - It would be nice if parseDate accepted a falsy return value as invalid. With null/undefined it crashes, where new Date(NaN) successfully sets the invalid state.

**Comment by jelbourn** [comment] 2015-09-22 18:39
Using something like moment to do your parsing/formatting is 100% necessary for any real application. The real problem is that our demo page isn't doing so, so I'm closing this issue as a dupe of #4671.

For your first sub-issues, don't quite follow what you mean. For the second, can you file a separate issue with the error you're seeing if `parseDate` returns nulls?

**Closed by jelbourn** 2015-09-22 18:39 UTC
Labels: type: bug

**Comment by bluebirdtech** [comment] 2015-09-22 20:20
Thanks @jelbourn doc changes sound good.

The first sub-issue is related to the [md-date-locale-provider docs](https://material.angularjs.org/HEAD/#/api/material.components.datepicker/service/$mdDateLocaleProvider). I think the parse/format example methods would be better if they were inverse operations. If my understanding is correct, they are not currently as moment(dateString).toDate() accepts an ISO-8601 formatted date (year first), rather than a date formatted to the current locale as outputted by format(). The above snippet includes changes to make them inverse operations.

Let me know if that should be a separate issue.  I'll make one for the error now.

**Comment by jelbourn** [comment] 2015-09-22 21:03
Ah, good point. I took your suggestion with bf8251201ce980f936a11888bf30affe710b3475. Thanks!

**Comment by bluebirdtech** [comment] 2015-09-22 21:26
Great :)  I should really get comfortable submitting PRs.

**Comment by devotis** [comment] 2017-04-14 10:49
I've worked out a full example on SO: http://stackoverflow.com/questions/32566416/change-format-of-md-datepicker-in-angular-material/43409002#43409002
