### ISSUE TITLE
Select option from md-select taping first letter with keyboard

### ISSUE THREAD

**Issue by matthieuh** [angular/material#1884] opened 2015-03-12 11:27 UTC
Actually angular material select (md-select) haven't same behaviour that the native one.
An interesting behaviour is the possibility to select an option typing first letter with keyboard.
I hope that i'm not the only one to find this behaviour very usefull !

**Comment by rschmukler** [comment] 2015-03-12 16:33
Closing as duplicate of #1740. But yes, it'd be useful :)

**Closed by rschmukler** 2015-03-12 16:33 UTC
