### ISSUE TITLE
md-select does not show value set in model

### ISSUE THREAD

**Issue by LeoLozes** [angular/material#8772] opened 2016-06-15 16:00 UTC
**Actual behavior**:
-  What is the issue? The md-select does not show the value when initialized with one in the model. 
-  What is the expected behavior? To be able to view the value that has been assigned in the model. 

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue : http://plnkr.co/W21y1Y
-  Details: You can see that the "activate" function initializes the values of two selects. The first one is empty when rendered. When you select "references" in the first select, the value previously selected shows correctly in the second select. 

**Angular Versions**: *
-  Angular Version: 1.4.9
-  Angular Material Version: master

**Additional Information**:
-  Browser Type: Chrome
-  Browser Version: 51
-  OS: Windows 10

**Comment by DevVersion** [comment] 2016-06-15 16:38
Seems like this is caused by the `ngIf` on the parent `md-input-container` of the second select.

**Comment by LeoLozes** [comment] 2016-06-15 16:46
I don't really understand your answer. I have tried to remove all the ng-ifs of the plunker, and the first select is still not showing the selected "reference" item when rendered.

**Comment by DevVersion** [comment] 2016-06-15 16:50
I've updated your Plunkr. I'm not sure, about this being the behavior you expect?

- http://plnkr.co/edit/Qvrmnp?p=preview

**Comment by LeoLozes** [comment] 2016-06-15 17:00
You are totally right about the component expecting and object. 
My bad & thank you for pointing it out! :)

**Comment by DevVersion** [comment] 2016-06-15 18:31
Closing this, because it's actually not a bug. 

If I missed something, please let me know and I'll reopen if necessary.

**Closed by DevVersion** 2016-06-15 18:31 UTC
